function varargout = buildBeautyMasks(inputImage, beautyContext, faceBox)
%BUILDBEAUTYMASKS 聚合 v3 三类保护 Mask 和连续皮肤强度图。
%   两个输出时返回 [masks, diagnostics]；需要拆分结果时可请求
%   [texture, structure, tone, strength, diagnostics]。

if nargin < 2 || ~isstruct(beautyContext) || ~isscalar(beautyContext)
    error('masks:InvalidContext', '必须提供标量 Beauty Context。');
end
if nargin < 3 || isempty(faceBox)
    if isfield(beautyContext, 'faceBox')
        faceBox = beautyContext.faceBox;
    else
        error('masks:InvalidFaceBox', '必须提供人脸框。');
    end
end

[textureProtectionMask, textureDiagnostics] = ...
    masks.buildTextureProtectionMask(inputImage, beautyContext, faceBox);
[structureProtectionMask, structureDiagnostics] = ...
    masks.buildStructureProtectionMask(inputImage, beautyContext, faceBox);
[toneProtectionMask, toneDiagnostics] = ...
    masks.buildToneProtectionMask(inputImage, beautyContext, faceBox);
[strengthMap, strengthDiagnostics] = ...
    masks.buildBeautyStrengthMap(inputImage, beautyContext, faceBox);

hardProtectionMask = optionalMask(beautyContext, ...
    'hardProtectionMask', size(inputImage, 1:2));
skinMask = optionalMask(beautyContext, 'skinMask', size(inputImage, 1:2));
faceSkinMask = optionalMask(beautyContext, ...
    'faceSkinMask', size(inputImage, 1:2));
if isfield(beautyContext, 'nonFaceSkinMask')
    nonFaceSkinMask = optionalMask(beautyContext, ...
        'nonFaceSkinMask', size(inputImage, 1:2));
else
    nonFaceSkinMask = max(skinMask - min(skinMask, faceSkinMask), 0);
end

protectionMask = max(cat(3, textureProtectionMask, ...
    structureProtectionMask, toneProtectionMask), [], 3);
protectionMask = min(max(protectionMask, 0), 1);
beautyMasks = struct( ...
    'textureProtectionMask', textureProtectionMask, ...
    'structureProtectionMask', structureProtectionMask, ...
    'toneProtectionMask', toneProtectionMask, ...
    'protectionMask', protectionMask, ...
    'strengthMap', strengthMap, ...
    'faceStrengthMap', strengthDiagnostics.faceStrengthMap, ...
    'nonFaceStrengthMap', strengthDiagnostics.nonFaceStrengthMap, ...
    'skinMask', skinMask, ...
    'faceSkinMask', faceSkinMask, ...
    'nonFaceSkinMask', nonFaceSkinMask, ...
    'hardProtectionMask', hardProtectionMask, ...
    'faceBox', double(faceBox), ...
    'imageSize', [size(inputImage, 1:2), 3]);
diagnostics = struct( ...
    'texture', textureDiagnostics, ...
    'structure', structureDiagnostics, ...
    'tone', toneDiagnostics, ...
    'strength', strengthDiagnostics, ...
    'hardProtectionMask', hardProtectionMask, ...
    'protectionMask', protectionMask);

if nargout <= 2
    if nargout >= 1
        varargout{1} = beautyMasks;
    end
    if nargout == 2
        varargout{2} = diagnostics;
    end
else
    varargout{1} = textureProtectionMask;
    varargout{2} = structureProtectionMask;
    varargout{3} = toneProtectionMask;
    varargout{4} = strengthMap;
    varargout{5} = diagnostics;
    if nargout > 5
        varargout{6} = beautyMasks;
    end
end
end

function value = optionalMask(context, name, imageSize)
if ~isfield(context, name)
    value = zeros(imageSize);
    return;
end
value = context.(name);
if (~isnumeric(value) && ~islogical(value)) || ~isreal(value) || ...
        ~isequal(size(value), imageSize) || any(~isfinite(value(:))) || ...
        any(value(:) < 0) || any(value(:) > 1)
    error('masks:InvalidContext', 'Context 字段 %s 无效。', name);
end
value = double(value);
end

