function [summary, diagnostics] = diagnoseFaceBoundaryCoverage( ...
        imagePath, outputFolder, options)
%DIAGNOSEFACEBOUNDARYCOVERAGE 诊断单张人像的脸缘覆盖缺口。
%   入口固定同一输入、尺寸、参数和人工选区，记录皮肤支持、强度、
%   Fine/Mid 门控、阶段作用量和最终图像变化。单因素消融只在本入口内
%   复制 Mask，不改生产算法、公共 Context 或验收阈值。

projectRoot = fileparts(fileparts(mfilename('fullpath')));
addpath(fullfile(projectRoot, 'src'));
if nargin < 3
    options = [];
end
if nargin < 1 || isempty(imagePath)
    error('diagnoseFaceBoundaryCoverage:MissingImagePath', ...
        '必须提供输入图像路径。');
end
options = normalizeOptions(options);
inputImage = readInputImage(imagePath);
options.faceBoundaryRoi = validateRoiBounds(options.faceBoundaryRoi, ...
    size(inputImage), 'faceBoundaryRoi');
options.controlRoi = validateRoiBounds(options.controlRoi, ...
    size(inputImage), 'controlRoi');

if nargin < 2 || isempty(outputFolder)
    outputFolder = fullfile(tempdir, 'image_beauty_face_boundary_diagnosis');
end
if ~ischar(outputFolder) && ~(isstring(outputFolder) && isscalar(outputFolder))
    error('diagnoseFaceBoundaryCoverage:InvalidOutputFolder', ...
        '输出目录必须是文本路径。');
end
outputFolder = char(outputFolder);
if ~isfolder(outputFolder)
    mkdir(outputFolder);
end

contract = beautyPipelineContract();
[previewImage, previewScale] = makePreview(inputImage);
[previewFaceBox, hasFace, detection] = detectSingleFace(previewImage);
if ~hasFace
    error('diagnoseFaceBoundaryCoverage:NoFace', ...
        '输入图像未检测到可用的语义人脸。');
end
previewContext = prepareBeautyContext(previewImage, previewFaceBox, ...
    detection.selectedParsing, struct('rotationDegrees', ...
    detection.orientationDegrees));
fullFaceBox = scaleFaceBox(previewFaceBox, 1 / previewScale, ...
    size(inputImage));
if previewScale < 1
    fullContext = resizeBeautyContext(previewContext, size(inputImage), ...
        fullFaceBox, inputImage);
else
    fullContext = previewContext;
end

modes = { ...
    struct('name', 'preview', 'image', previewImage, ...
    'faceBox', previewFaceBox, 'context', previewContext, ...
    'scale', previewScale), ...
    struct('name', 'original', 'image', inputImage, ...
    'faceBox', fullFaceBox, 'context', fullContext, 'scale', 1)};

regionRows = repmat(emptyRegionRow(), 0, 1);
ablationRows = repmat(emptyAblationRow(), 0, 1);
modeDiagnostics = cell(1, numel(modes));
for modeIndex = 1:numel(modes)
    mode = modes{modeIndex};
    modeOptions = options;
    modeOptions.faceBoundaryRoi = scaleRoi(options.faceBoundaryRoi, ...
        mode.scale, size(mode.image));
    modeOptions.controlRoi = scaleRoi(options.controlRoi, ...
        mode.scale, size(mode.image));
    [modeResult, currentRegionRows, currentAblationRows] = ...
        diagnoseMode(mode, modeOptions);
    modeDiagnostics{modeIndex} = modeResult;
    regionRows = [regionRows; currentRegionRows]; %#ok<AGROW>
    ablationRows = [ablationRows; currentAblationRows]; %#ok<AGROW>
end

regionMetrics = struct2table(regionRows);
ablationMetrics = struct2table(ablationRows);
sourceRows = repmat(emptySourceRow(), 0, 1);
sourceAblationRows = repmat(emptySourceAblationRow(), 0, 1);
featureRows = repmat(emptyFeatureRow(), 0, 1);
for modeIndex = 1:numel(modeDiagnostics)
    mode = modeDiagnostics{modeIndex};
    sourceRows = [sourceRows; mode.attribution.sourceRows]; %#ok<AGROW>
    sourceAblationRows = [sourceAblationRows; ...
        mode.attribution.sourceAblationRows]; %#ok<AGROW>
    featureRows = [featureRows; mode.attribution.featureRows]; %#ok<AGROW>
end
sourceMetrics = struct2table(sourceRows);
sourceAblationMetrics = struct2table(sourceAblationRows);
featureMetrics = struct2table(featureRows);
paths = writeArtifacts(outputFolder, modeDiagnostics, regionMetrics, ...
    ablationMetrics, sourceMetrics, sourceAblationMetrics, featureMetrics);
summary = struct( ...
    'completed', true, ...
    'contract', contract, ...
    'imagePath', char(imagePath), ...
    'inputSize', size(inputImage), ...
    'previewScale', previewScale, ...
    'previewFaceBox', previewFaceBox, ...
    'originalFaceBox', fullFaceBox, ...
    'orientationDegrees', detection.orientationDegrees, ...
    'parameters', struct( ...
    'smoothingStrength', options.smoothingStrength, ...
    'whiteningStrength', options.whiteningStrength), ...
    'faceBoundaryRoi', options.faceBoundaryRoi, ...
    'controlRoi', options.controlRoi, ...
    'regionMetrics', regionMetrics, ...
    'ablationMetrics', ablationMetrics, ...
    'sourceMetrics', sourceMetrics, ...
    'sourceAblationMetrics', sourceAblationMetrics, ...
    'featureMetrics', featureMetrics, ...
    'diagnosticScope', struct( ...
        'sourceNames', {{'noseStructure', 'outsideStructure', ...
        'faceStructure', 'faceBoundary'}}, ...
        'legacyWholeInputAblationIncluded', ...
        options.includeLegacyAblations, ...
        'frozenAdaptiveStatistics', true, ...
        'repairRecomputationIsPropagation', true), ...
    'paths', paths);
compactModes = compactModeDiagnostics(modeDiagnostics);
diagnostics = struct( ...
    'contract', contract, ...
    'detection', compactDetection(detection), ...
    'modes', {compactModes}, ...
    'paths', paths);
dataPath = fullfile(outputFolder, 'faceBoundaryDiagnosticData.mat');
summary.paths.data = dataPath;
diagnostics.paths.data = dataPath;
clear modeDiagnostics compactModes;
save(dataPath, 'summary', 'diagnostics', '-v7.3');
end

function options = normalizeOptions(options)
if nargin < 1 || isempty(options)
    error('diagnoseFaceBoundaryCoverage:MissingOptions', ...
        ['必须提供 faceBoundaryRoi 和 controlRoi；选区必须依据原图 ', ...
        '或截图人工确定，不能由待验证的 Mask 自动生成。']);
end
if ~isstruct(options) || ~isscalar(options) || ...
        ~all(isfield(options, {'faceBoundaryRoi', 'controlRoi'}))
    error('diagnoseFaceBoundaryCoverage:InvalidOptions', ...
        '选项必须包含 faceBoundaryRoi 和 controlRoi。');
end
options.faceBoundaryRoi = validateRoi(options.faceBoundaryRoi, ...
    'faceBoundaryRoi');
options.controlRoi = validateRoi(options.controlRoi, 'controlRoi');
if ~isfield(options, 'smoothingStrength')
    options.smoothingStrength = 100;
end
if ~isfield(options, 'whiteningStrength')
    options.whiteningStrength = 15;
end
if ~isfield(options, 'includeLegacyAblations')
    options.includeLegacyAblations = false;
end
if ~isValidStrength(options.smoothingStrength) || ...
        ~isValidStrength(options.whiteningStrength)
    error('diagnoseFaceBoundaryCoverage:InvalidStrength', ...
        '磨皮和美白强度必须是范围 0 到 100 内的有限数值标量。');
end
if ~islogical(options.includeLegacyAblations) || ...
        ~isscalar(options.includeLegacyAblations)
    error('diagnoseFaceBoundaryCoverage:InvalidOptions', ...
        'includeLegacyAblations 必须是逻辑标量。');
end
end

function image = readInputImage(imagePath)
if ~ischar(imagePath) && ~(isstring(imagePath) && isscalar(imagePath))
    error('diagnoseFaceBoundaryCoverage:InvalidImagePath', ...
        '输入图像路径必须是文本。');
end
imagePath = char(imagePath);
if ~isfile(imagePath)
    error('diagnoseFaceBoundaryCoverage:MissingImage', ...
        '输入图像不存在：%s。', imagePath);
end
image = imread(imagePath);
if ~isa(image, 'uint8') || ~isreal(image) || ndims(image) ~= 3 || ...
        size(image, 3) ~= 3
    error('diagnoseFaceBoundaryCoverage:InvalidImage', ...
        '输入图像必须是 uint8 三通道 RGB 图像。');
end
end

function [modeResult, regionRows, ablationRows] = diagnoseMode(mode, options)
params = struct('smoothingStrength', options.smoothingStrength, ...
    'whiteningStrength', options.whiteningStrength);
[output, baseline] = beautifyImage(mode.image, params, mode.faceBox, ...
    mode.context);
baseline.output = output;
required = {'beautyMasks', 'blemishMap', 'smoothingResult', ...
    'repairResult', 'baseLuminanceResult', 'skinToneResult', ...
    'whiteningResult', 'compose'};
if ~all(isfield(baseline, required))
    error('diagnoseFaceBoundaryCoverage:IncompleteDiagnostics', ...
        '基线诊断缺少可定位脸缘作用量所需的阶段结果。');
end

[frequency, ~] = beauty.decomposeSkinFrequency(mode.image, mode.faceBox);
baseline.frequencyForDiagnosis = frequency;
beautyMasks = baseline.beautyMasks;
blemishMap = baseline.blemishMap;
if options.includeLegacyAblations
    ablation = runAblations(mode.image, frequency, beautyMasks, ...
        blemishMap, baseline, params);
else
    ablation = emptyLegacyAblation(size(mode.image, 1:2));
end
safetyMasks = buildSafetyMasks(mode.context, beautyMasks);
mode.faceBoundaryRoi = options.faceBoundaryRoi;
mode.controlRoi = options.controlRoi;
[attribution, sourceRows, sourceAblationRows, featureRows] = ...
    runStructureAttribution(mode, frequency, beautyMasks, blemishMap, ...
    baseline, params, safetyMasks);
regionDefinitions = { ...
    struct('name', 'faceBoundary', 'roi', options.faceBoundaryRoi), ...
    struct('name', 'control', 'roi', options.controlRoi)};
regionRows = repmat(emptyRegionRow(), 0, 1);
ablationRows = repmat(emptyAblationRow(), 0, 1);
for regionIndex = 1:numel(regionDefinitions)
    region = regionDefinitions{regionIndex};
    regionRows(end + 1, 1) = measureRegion( ...
        mode, region, beautyMasks, baseline, ablation, frequency); %#ok<AGROW>
    for ablationIndex = 1:numel(ablation.items)
        ablationRows(end + 1, 1) = measureAblation( ...
            mode, region, ablation.items(ablationIndex), ...
            baseline, safetyMasks); %#ok<AGROW>
    end
end

modeResult = struct( ...
    'name', mode.name, ...
    'image', mode.image, ...
    'faceBox', mode.faceBox, ...
    'context', mode.context, ...
    'faceBoundaryRoi', options.faceBoundaryRoi, ...
    'controlRoi', options.controlRoi, ...
    'output', output, ...
    'baseline', baseline, ...
    'frequency', frequency, ...
    'ablation', ablation, ...
    'attribution', struct( ...
        'sourceRows', sourceRows, ...
        'sourceAblationRows', sourceAblationRows, ...
        'featureRows', featureRows, ...
        'details', attribution), ...
    'safetyMasks', safetyMasks);
end

function ablation = emptyLegacyAblation(imageSize)
%EMPTYLEGACYABLATION 04 默认不重复执行 02 的整体输入消融。
%   保留与旧结果相同的字段形状，便于复用原有区域表和紧凑诊断；
%   空值明确表示本次没有运行旧实验，而不是把零当作测量结果。
ablation = struct( ...
    'items', repmat(emptyAblationItem(), 0, 1), ...
    'midWithoutRepeated', struct('suppression', nan(imageSize)));
end

function item = emptyAblationItem
item = struct( ...
    'name', '', 'output', uint8([]), 'smoothing', struct(), ...
    'repair', struct(), 'smoothingDetails', struct(), ...
    'repairDetails', struct(), 'compose', struct());
end

function ablation = runAblations(inputImage, frequency, beautyMasks, ...
        blemishMap, baseline, params)
processing = struct( ...
    'baseLuminance', baseline.baseLuminanceResult, ...
    'skinTone', baseline.skinToneResult, ...
    'whitening', baseline.whiteningResult);
originalSmoothing = baseline.smoothingResult;

withoutStructureMasks = beautyMasks;
withoutStructureMasks.structureProtectionMask = zeros( ...
    size(beautyMasks.structureProtectionMask));
[withoutStructureSmoothing, smoothingDetails] = ...
    beauty.smoothSkinTexture(frequency, withoutStructureMasks, ...
    params.smoothingStrength, blemishMap);
[withoutStructureRepair, repairDetails] = ...
    beauty.repairSkinBlemishes(withoutStructureSmoothing, beautyMasks, ...
    blemishMap, params.smoothingStrength);
[withoutStructureOutput, composeDetails] = ...
    composeAblation(inputImage, frequency, withoutStructureRepair, ...
    beautyMasks, params.whiteningStrength, processing);
items(1) = makeAblationItem('smoothingWithoutStructure', ...
    withoutStructureOutput, withoutStructureSmoothing, ...
    withoutStructureRepair, smoothingDetails, repairDetails, composeDetails);

[repairWithoutStructure, repairDetails] = ...
    beauty.repairSkinBlemishes(originalSmoothing, withoutStructureMasks, ...
    blemishMap, params.smoothingStrength);
[repairWithoutStructureOutput, composeDetails] = ...
    composeAblation(inputImage, frequency, repairWithoutStructure, ...
    beautyMasks, params.whiteningStrength, processing);
items(2) = makeAblationItem('repairWithoutStructure', ...
    repairWithoutStructureOutput, originalSmoothing, repairWithoutStructure, ...
    struct(), repairDetails, composeDetails);

withoutTextureMasks = beautyMasks;
withoutTextureMasks.textureProtectionMask = zeros( ...
    size(beautyMasks.textureProtectionMask));
[repairWithoutTexture, repairDetails] = ...
    beauty.repairSkinBlemishes(originalSmoothing, withoutTextureMasks, ...
    blemishMap, params.smoothingStrength);
[repairWithoutTextureOutput, composeDetails] = ...
    composeAblation(inputImage, frequency, repairWithoutTexture, ...
    beautyMasks, params.whiteningStrength, processing);
items(3) = makeAblationItem('repairWithoutTexture', ...
    repairWithoutTextureOutput, originalSmoothing, repairWithoutTexture, ...
    struct(), repairDetails, composeDetails);

% 这里只移除 Mid 的第二次结构门控，用于判断 gate^2 是否真的贡献了
% 当前选区的抑制；不把该对照接入生产结果。
midGate = baseline.smoothing.midStructureGate;
midAlphaWithoutRepeated = baseline.smoothing.alphaMap .* ...
    baseline.smoothing.noseMidGate;
midRetentionWithoutRepeated = 1 - midAlphaWithoutRepeated .* ...
    (1 - baseline.smoothing.midRetention);
midWithoutRepeated = frequency.mid .* midRetentionWithoutRepeated;
ablation.midWithoutRepeated = struct( ...
    'midStructureGate', midGate, ...
    'midAlphaMap', midAlphaWithoutRepeated, ...
    'mid', midWithoutRepeated, ...
    'suppression', abs(midAlphaWithoutRepeated - ...
    baseline.smoothing.midAlphaMap));
[repairWithoutRepeated, repairDetails] = ...
    beauty.repairSkinBlemishes( ...
    replaceSmoothingMid(originalSmoothing, midWithoutRepeated, ...
    midAlphaWithoutRepeated, midRetentionWithoutRepeated), beautyMasks, ...
    blemishMap, params.smoothingStrength);
[repairWithoutRepeatedOutput, composeDetails] = ...
    composeAblation(inputImage, frequency, repairWithoutRepeated, ...
    beautyMasks, params.whiteningStrength, processing);
items(4) = makeAblationItem('smoothingWithoutRepeatedMid', ...
    repairWithoutRepeatedOutput, ...
    replaceSmoothingMid(originalSmoothing, midWithoutRepeated, ...
    midAlphaWithoutRepeated, midRetentionWithoutRepeated), ...
    repairWithoutRepeated, struct(), repairDetails, composeDetails);
ablation.items = items;
end

function smoothed = replaceSmoothingMid(original, mid, alphaMap, retentionMap)
smoothed = original;
smoothed.mid = mid;
smoothed.midAlphaMap = alphaMap;
smoothed.midRetentionMap = retentionMap;
smoothed.mediumRetentionMap = retentionMap;
smoothed.actualMidRetentionMap = retentionMap;
smoothed.actualMediumRetentionMap = retentionMap;
smoothed.midActualRetentionMap = retentionMap;
smoothed.reconstructedLuminance = original.base + mid + original.fine;
smoothed.outputLuminance = smoothed.reconstructedLuminance;
end

function item = makeAblationItem(name, output, smoothing, repair, ...
        smoothingDetails, repairDetails, composeDetails)
item = struct( ...
    'name', name, ...
    'output', output, ...
    'smoothing', smoothing, ...
    'repair', repair, ...
    'smoothingDetails', smoothingDetails, ...
    'repairDetails', repairDetails, ...
    'compose', composeDetails);
end

function [output, diagnostics] = composeAblation(inputImage, frequency, ...
        repairedFrequency, beautyMasks, whiteningStrength, processing)
[output, diagnostics] = beauty.composeBeautyResult(inputImage, frequency, ...
    repairedFrequency, beautyMasks, whiteningStrength, processing);
end

function [attribution, sourceRows, sourceAblationRows, featureRows] = ...
        runStructureAttribution(mode, frequency, beautyMasks, blemishMap, ...
        baseline, params, safetyMasks)
%RUNSTRUCTUREATTRIBUTION 归因四个现有结构保护来源及其局部消融。
%   来源分解严格复现生产端的 max(...)*skin 顺序。消融只在诊断入口
%   替换一个来源，再使用基线的自适应保留率；Repair 的再次计算只作为
%   下游传播结果记录，不把它误写成单纯门控效果。
structure = extractStructureSources(mode, baseline, beautyMasks);
[frozenBaseline, ~] = buildFrozenSmoothing( ...
    frequency, beautyMasks, baseline.smoothing, structure.finalProtection);
frozenBaselineErrors = [ ...
    abs(frozenBaseline.fine(:) - baseline.smoothingResult.fine(:)); ...
    abs(frozenBaseline.mid(:) - baseline.smoothingResult.mid(:)); ...
    abs(frozenBaseline.outputLuminance(:) - ...
    baseline.smoothingResult.outputLuminance(:))];
frozenBaselineError = max(frozenBaselineErrors);
if frozenBaselineError > 1e-12
    error('diagnoseFaceBoundaryCoverage:FrozenBaselineMismatch', ...
        ['冻结基线重建误差为 %.17g，不能在未确认保留率和 ', ...
        '自适应统计一致性前继续做来源归因。'], frozenBaselineError);
end
structure.frozenBaselineMaxError = frozenBaselineError;

sourceNames = structure.sourceNames;
sourceRows = repmat(emptySourceRow(), 0, 1);
sourceAblationRows = repmat(emptySourceAblationRow(), 0, 1);
featureRows = repmat(emptyFeatureRow(), 0, 1);
regionDefinitions = { ...
    struct('name', 'faceBoundary', 'roi', mode.faceBoundaryRoi), ...
    struct('name', 'control', 'roi', mode.controlRoi)};
for regionIndex = 1:numel(regionDefinitions)
    region = regionDefinitions{regionIndex};
    subsets = buildSourceSubsets(mode, region, beautyMasks, baseline);
    for subsetIndex = 1:numel(subsets)
        subset = subsets(subsetIndex);
        for sourceIndex = 1:numel(sourceNames)
            sourceRows(end + 1, 1) = measureSource( ...
                mode, region, subset, sourceIndex, structure); %#ok<AGROW>
        end
    end
end

[featureMasks, featureDefinitions] = buildFeatureMasks( ...
    mode.context, safetyMasks);
sourceItems = repmat(emptySourceAblationItem(), 0, 1);
for sourceIndex = 1:numel(sourceNames)
    item = runSourceAblation(mode, frequency, beautyMasks, blemishMap, ...
        baseline, params, structure, sourceIndex);
    sourceItems(sourceIndex, 1) = item;
    for regionIndex = 1:numel(regionDefinitions)
        region = regionDefinitions{regionIndex};
        subsets = buildSourceSubsets(mode, region, beautyMasks, baseline);
        sourceAblationRows(end + 1, 1) = measureSourceAblation( ...
            mode, region, subsets(1), item, baseline, structure, ...
            safetyMasks); %#ok<AGROW>
    end
    currentFeatureRows = measureFeatureRows(mode, sourceNames{sourceIndex}, ...
        item, baseline, featureMasks, featureDefinitions, ...
        structure.lowPassSigma);
    featureRows = [featureRows; currentFeatureRows]; %#ok<AGROW>
end

attribution = struct( ...
    'sourceNames', {sourceNames}, ...
    'structure', structure, ...
    'sourceAblations', sourceItems, ...
    'featureMasks', featureMasks, ...
    'featureDefinitions', featureDefinitions, ...
    'sourceRows', sourceRows, ...
    'sourceAblationRows', sourceAblationRows, ...
    'featureRows', featureRows, ...
    'measurement', struct( ...
        'analysisRule', ['优先使用 ROI ∩ faceSkinMask >= 0.35；若该 ', ...
        '交集为空，改用 ROI ∩ skinMask >= 0.05。'], ...
        'gateZeroRule', 'gate <= 1e-12。', ...
        'gatePartialRule', '1e-12 < gate < 1 - 1e-12。', ...
        'dominanceRule', ['仅在最大最终来源值大于 1e-12 的像素上统计；', ...
        '并列最大值按并列项数等分主导权，唯一最大项另行记录。'], ...
        'energyRule', ['输入频率能量为 0 或选区为空时保留 NaN，', ...
        '不添加分母常数。'], ...
        'ablationRule', ['只移除一个来源并冻结基线自适应统计和保留率；', ...
        'Repair 使用消融后的结构 Mask 重新计算，作为传播后果。']));
end

function structure = extractStructureSources(mode, baseline, beautyMasks)
if ~isfield(baseline, 'mask') || ~isstruct(baseline.mask) || ...
        ~isfield(baseline.mask, 'structure')
    error('diagnoseFaceBoundaryCoverage:MissingStructureDiagnostics', ...
        '基线缺少结构保护来源诊断，不能进行来源归因。');
end
details = baseline.mask.structure;
required = {'continuousEvidence', 'noseStructure', ...
    'outsideStructure', 'faceBoundary', 'lowFrequency', ...
    'lowPassSigma', 'gradientMagnitude', 'orientationCoherence'};
if ~all(isfield(details, required))
    error('diagnoseFaceBoundaryCoverage:MissingStructureDiagnostics', ...
        '结构诊断缺少四来源重建所需字段。');
end
imageSize = size(mode.image, 1:2);
skin = readDiagnosticMap(beautyMasks.skinMask, imageSize, 'skinMask');
face = readDiagnosticMap(beautyMasks.faceSkinMask, imageSize, ...
    'faceSkinMask');
continuousEvidence = readDiagnosticMap(details.continuousEvidence, ...
    imageSize, 'continuousEvidence');
noseStructure = readDiagnosticMap(details.noseStructure, imageSize, ...
    'noseStructure');
outsideStructure = readDiagnosticMap(details.outsideStructure, imageSize, ...
    'outsideStructure');
faceBoundary = readDiagnosticMap(details.faceBoundary, imageSize, ...
    'faceBoundary');
% 生产端未把 faceStructure 放进公共诊断字段；在本入口按同一公式复算。
faceStructure = min(face, skin) .* continuousEvidence;
sourceNames = {'noseStructure', 'outsideStructure', ...
    'faceStructure', 'faceBoundary'};
rawSources = cat(3, noseStructure, outsideStructure, ...
    faceStructure, faceBoundary);
skinSupport = min(max(skin, 0), 1);
effectiveSources = rawSources .* skinSupport;
maxSource = max(rawSources, [], 3);
reconstructed = maxSource .* skinSupport;
baselineProtection = readDiagnosticMap( ...
    beautyMasks.structureProtectionMask, imageSize, ...
    'structureProtectionMask');
reconstructionError = reconstructed - baselineProtection;
maxAbsError = max(abs(reconstructionError(:)));
meanAbsError = mean(abs(reconstructionError(:)));
if maxAbsError > 1e-12
    error('diagnoseFaceBoundaryCoverage:StructureReconstructionMismatch', ...
        ['四来源按生产顺序重建的保护图与基线不一致：最大误差 %.17g，', ...
        '平均误差 %.17g。已停止归因。'], maxAbsError, meanAbsError);
end

tieTolerance = 1e-12;
activeMask = max(effectiveSources, [], 3) > tieTolerance;
winnerMask = false(size(effectiveSources));
maximum = max(effectiveSources, [], 3);
for sourceIndex = 1:numel(sourceNames)
    winnerMask(:, :, sourceIndex) = activeMask & ...
        abs(effectiveSources(:, :, sourceIndex) - maximum) <= ...
        tieTolerance;
end
tieCount = sum(winnerMask, 3);
dominanceWeights = zeros(size(effectiveSources));
dominantMask = false(size(effectiveSources));
dominantIndex = zeros(imageSize);
for sourceIndex = 1:numel(sourceNames)
    dominanceWeights(:, :, sourceIndex) = double( ...
        winnerMask(:, :, sourceIndex)) ./ max(tieCount, 1);
    dominantMask(:, :, sourceIndex) = winnerMask(:, :, sourceIndex) & ...
        tieCount == 1;
    dominantIndex(dominantMask(:, :, sourceIndex)) = sourceIndex;
end
tieMask = activeMask & tieCount > 1;

inputY = rgb2ycbcr(im2double(mode.image));
inputLuminance = inputY(:, :, 1);
[inputGradientX, inputGradientY] = gradient(inputLuminance);
inputGradientMagnitude = hypot(inputGradientX, inputGradientY);
contrastSigma = max(1.5, double(details.lowPassSigma));
lowFrequency = readDiagnosticMap(details.lowFrequency, imageSize, ...
    'lowFrequency');
localLowFrequency = imgaussfilt(lowFrequency, ...
    contrastSigma, 'Padding', 'replicate');
lowFrequencyContrast = abs(lowFrequency - ...
    localLowFrequency);
structure = struct( ...
    'sourceNames', {sourceNames}, ...
    'rawSources', rawSources, ...
    'effectiveSources', effectiveSources, ...
    'maxSource', maxSource, ...
    'finalProtection', reconstructed, ...
    'baselineProtection', baselineProtection, ...
    'reconstructionError', reconstructionError, ...
    'reconstructionMaxAbsError', maxAbsError, ...
    'reconstructionMeanAbsError', meanAbsError, ...
    'skinSupport', skinSupport, ...
    'activeMask', activeMask, ...
    'winnerMask', winnerMask, ...
    'dominantMask', dominantMask, ...
    'dominantIndex', dominantIndex, ...
    'tieMask', tieMask, ...
    'dominanceWeights', dominanceWeights, ...
    'tieTolerance', tieTolerance, ...
    'gradientMagnitude', readDiagnosticMap(details.gradientMagnitude, ...
    imageSize, 'gradientMagnitude'), ...
    'orientationCoherence', readDiagnosticMap( ...
    details.orientationCoherence, imageSize, 'orientationCoherence'), ...
    'continuousEvidence', continuousEvidence, ...
    'lowFrequency', lowFrequency, ...
    'lowFrequencyContrast', lowFrequencyContrast, ...
    'lowPassSigma', double(details.lowPassSigma), ...
    'inputLuminance', inputLuminance, ...
    'inputGradientMagnitude', inputGradientMagnitude, ...
    'frozenBaselineMaxError', NaN);
end

function value = readDiagnosticMap(value, imageSize, name)
if (~isnumeric(value) && ~islogical(value)) || ~isreal(value) || ...
        ~isequal(size(value), imageSize) || any(~isfinite(value(:)))
    error('diagnoseFaceBoundaryCoverage:InvalidDiagnosticMap', ...
        '诊断字段 %s 的尺寸或取值无效。', name);
end
value = double(value);
end

function subsets = buildSourceSubsets(mode, region, beautyMasks, baseline)
roi = roiMask(region.roi, size(mode.image));
faceSupport = roi & beautyMasks.faceSkinMask >= .35;
if any(faceSupport(:))
    analysis = faceSupport;
    analysisDefinition = 'ROI ∩ faceSkinMask >= 0.35';
else
    analysis = roi & beautyMasks.skinMask >= .05;
    analysisDefinition = 'ROI ∩ skinMask >= 0.05（脸部皮肤交集为空）';
end
fineGate = baseline.smoothing.fineStructureGate;
midGate = baseline.smoothing.midStructureGate;
subsets = repmat(struct('name', '', 'definition', '', 'mask', ...
    false(size(roi))), 5, 1);
subsets(1) = struct('name', 'all', 'definition', analysisDefinition, ...
    'mask', analysis);
subsets(2) = struct('name', 'fineZero', ...
    'definition', [analysisDefinition, ' 且 Fine 结构门控 <= 1e-12'], ...
    'mask', analysis & fineGate <= 1e-12);
subsets(3) = struct('name', 'finePartial', ...
    'definition', [analysisDefinition, ...
    ' 且 1e-12 < Fine 结构门控 < 1 - 1e-12'], ...
    'mask', analysis & fineGate > 1e-12 & fineGate < 1 - 1e-12);
subsets(4) = struct('name', 'midZero', ...
    'definition', [analysisDefinition, ' 且 Mid 结构门控 <= 1e-12'], ...
    'mask', analysis & midGate <= 1e-12);
subsets(5) = struct('name', 'midPartial', ...
    'definition', [analysisDefinition, ...
    ' 且 1e-12 < Mid 结构门控 < 1 - 1e-12'], ...
    'mask', analysis & midGate > 1e-12 & midGate < 1 - 1e-12);
end

function row = measureSource(mode, region, subset, sourceIndex, structure)
row = emptySourceRow();
source = structure.sourceNames{sourceIndex};
analysis = subset.mask;
roi = roiMask(region.roi, size(mode.image));
sourceRaw = structure.rawSources(:, :, sourceIndex);
sourceEffective = structure.effectiveSources(:, :, sourceIndex);
dominant = structure.dominantMask(:, :, sourceIndex);
dominanceWeight = structure.dominanceWeights(:, :, sourceIndex);
active = analysis & structure.activeMask;
dominantPixels = analysis & dominant;
row.mode = mode.name;
row.region = region.name;
row.gateSubset = subset.name;
row.gateSubsetDefinition = subset.definition;
row.source = source;
row.roiPixels = nnz(roi);
row.analysisPixels = nnz(analysis);
row.activeProtectionPixels = nnz(active);
row.dominantPixels = nnz(dominantPixels);
row.sourceRawMean = meanOn(sourceRaw, analysis);
row.sourceRawMedian = medianOn(sourceRaw, analysis);
row.sourceRawP90 = percentileOn(sourceRaw, analysis, .90);
row.sourceRawMax = maxOn(sourceRaw, analysis);
row.sourceEffectiveMean = meanOn(sourceEffective, analysis);
row.sourceEffectiveMedian = medianOn(sourceEffective, analysis);
row.sourceEffectiveP90 = percentileOn(sourceEffective, analysis, .90);
row.sourceEffectiveMax = maxOn(sourceEffective, analysis);
row.sourcePositiveFraction = fractionWithDenominator( ...
    nnz(analysis & sourceEffective > structure.tieTolerance), ...
    nnz(analysis));
row.dominanceFraction = fractionWithDenominator( ...
    sum(dominanceWeight(analysis)), nnz(active));
row.dominanceDenominatorPixels = nnz(active);
row.tiePixels = nnz(analysis & structure.tieMask);
row.tieFraction = fractionWithDenominator(row.tiePixels, nnz(active));
row.dominantGradientMean = meanOn(structure.gradientMagnitude, ...
    dominantPixels);
row.dominantGradientP90 = percentileOn(structure.gradientMagnitude, ...
    dominantPixels, .90);
row.dominantOrientationCoherenceMean = meanOn( ...
    structure.orientationCoherence, dominantPixels);
row.dominantOrientationCoherenceP90 = percentileOn( ...
    structure.orientationCoherence, dominantPixels, .90);
row.dominantContinuousEvidenceMean = meanOn( ...
    structure.continuousEvidence, dominantPixels);
row.dominantInputGradientMean = meanOn( ...
    structure.inputGradientMagnitude, dominantPixels);
row.dominantInputGradientP90 = percentileOn( ...
    structure.inputGradientMagnitude, dominantPixels, .90);
row.dominantLowFrequencyContrastMean = meanOn( ...
    structure.lowFrequencyContrast, dominantPixels);
row.dominantLowFrequencyContrastP90 = percentileOn( ...
    structure.lowFrequencyContrast, dominantPixels, .90);
end

function item = emptySourceAblationItem
item = struct( ...
    'source', '', 'sourceIndex', 0, 'output', uint8([]), ...
    'structureProtectionMask', [], 'smoothing', struct(), ...
    'repair', struct(), 'smoothingDetails', struct(), ...
    'repairDetails', struct(), 'compose', struct(), ...
    'frozenFineRetention', NaN, 'frozenMidRetention', NaN, ...
    'frozenBaselineMaxError', NaN, 'ablationProtocol', '');
end

function item = runSourceAblation(mode, frequency, beautyMasks, blemishMap, ...
        baseline, params, structure, sourceIndex)
ablatedRaw = structure.rawSources;
ablatedRaw(:, :, sourceIndex) = 0;
ablatedStructure = max(ablatedRaw, [], 3) .* structure.skinSupport;
ablatedMasks = beautyMasks;
ablatedMasks.structureProtectionMask = ablatedStructure;
if isfield(ablatedMasks, 'protectionMask')
    ablatedMasks.protectionMask = max(cat(3, ...
        ablatedMasks.textureProtectionMask, ablatedStructure, ...
        ablatedMasks.hardProtectionMask), [], 3);
end
[ablatedSmoothing, smoothingDetails] = buildFrozenSmoothing( ...
    frequency, ablatedMasks, baseline.smoothing, ablatedStructure);
[ablatedRepair, repairDetails] = beauty.repairSkinBlemishes( ...
    ablatedSmoothing, ablatedMasks, blemishMap, params.smoothingStrength);
processing = struct( ...
    'baseLuminance', baseline.baseLuminanceResult, ...
    'skinTone', baseline.skinToneResult, ...
    'whitening', baseline.whiteningResult);
[output, composeDetails] = composeAblation(mode.image, frequency, ...
    ablatedRepair, ablatedMasks, params.whiteningStrength, processing);
item = struct( ...
    'source', structure.sourceNames{sourceIndex}, ...
    'sourceIndex', sourceIndex, ...
    'output', output, ...
    'structureProtectionMask', ablatedStructure, ...
    'smoothing', ablatedSmoothing, ...
    'repair', ablatedRepair, ...
    'smoothingDetails', smoothingDetails, ...
    'repairDetails', repairDetails, ...
    'compose', composeDetails, ...
    'frozenFineRetention', double(baseline.smoothing.fineRetention), ...
    'frozenMidRetention', double(baseline.smoothing.midRetention), ...
    'frozenBaselineMaxError', structure.frozenBaselineMaxError, ...
    'ablationProtocol', ['单项来源消融；冻结基线自适应统计和保留率；', ...
    'Repair 重算只作为下游传播后果。']);
end

function [smoothed, diagnostics] = buildFrozenSmoothing( ...
        frequency, beautyMasks, baselineSmoothing, structureProtection)
%BUILD FROZEN SMOOTHING 仅重算门控，冻结基线的自适应保留率和统计量。
profile = baselineSmoothing.profile;
strengthMap = double(beautyMasks.strengthMap);
textureProtection = double(beautyMasks.textureProtectionMask);
hardProtection = double(beautyMasks.hardProtectionMask);
if all(isfield(beautyMasks, {'faceStrengthMap', 'nonFaceStrengthMap'}))
    nonFaceStrength = double(beautyMasks.nonFaceStrengthMap);
    effectStrength = profile.alphaCurve .* strengthMap;
    nonFacePixels = nonFaceStrength > .01;
    effectStrength(nonFacePixels) = profile.outsideFaceStrength .* ...
        nonFaceStrength(nonFacePixels);
else
    effectStrength = profile.alphaCurve .* strengthMap;
end
fineProtection = max(textureProtection, hardProtection);
fineStructureGate = max(0, 1 - 4 * structureProtection);
alphaMap = effectStrength .* (1 - fineProtection) .* fineStructureGate;
alphaMap = min(max(double(alphaMap), 0), 1);
noseMidGate = double(baselineSmoothing.noseMidGate);
midStructureGate = fineStructureGate;
midAlphaMap = alphaMap .* midStructureGate .* noseMidGate;
fineRetention = double(baselineSmoothing.fineRetention);
midRetention = double(baselineSmoothing.midRetention);
fineRetentionMap = 1 - alphaMap .* (1 - fineRetention);
midRetentionMap = 1 - midAlphaMap .* (1 - midRetention);
smoothedFine = double(frequency.fine) .* fineRetentionMap;
smoothedMid = double(frequency.mid) .* midRetentionMap;
outputLuminance = double(frequency.base) + smoothedMid + smoothedFine;
smoothed = frequency;
smoothed.fine = smoothedFine;
smoothed.mid = smoothedMid;
smoothed.reconstructedLuminance = outputLuminance;
smoothed.outputLuminance = outputLuminance;
smoothed.alphaMap = alphaMap;
smoothed.fineAlphaMap = alphaMap;
smoothed.fineRetention = fineRetention;
smoothed.effectiveProfileFineRetention = fineRetention;
smoothed.profileFineRetention = baselineSmoothing.profileFineRetention;
smoothed.profileMediumRetention = baselineSmoothing.profileMediumRetention;
smoothed.profile = profile;
smoothed.fineRetentionMap = fineRetentionMap;
smoothed.retentionMap = fineRetentionMap;
smoothed.actualFineRetentionMap = fineRetentionMap;
smoothed.fineActualRetentionMap = fineRetentionMap;
smoothed.midAlphaMap = midAlphaMap;
smoothed.midRetention = midRetention;
smoothed.mediumRetention = midRetention;
smoothed.midRetentionMap = midRetentionMap;
smoothed.mediumRetentionMap = midRetentionMap;
smoothed.actualMidRetentionMap = midRetentionMap;
smoothed.midActualRetentionMap = midRetentionMap;
smoothed.actualMediumRetentionMap = midRetentionMap;
diagnostics = struct( ...
    'alphaMap', alphaMap, ...
    'fineAlphaMap', alphaMap, ...
    'midAlphaMap', midAlphaMap, ...
    'profile', profile, ...
    'fineRetention', fineRetention, ...
    'effectiveProfileFineRetention', fineRetention, ...
    'profileFineRetention', baselineSmoothing.profileFineRetention, ...
    'profileMediumRetention', baselineSmoothing.profileMediumRetention, ...
    'adaptiveFineRetention', fineRetention, ...
    'noseMidGate', noseMidGate, ...
    'midStructureGate', midStructureGate, ...
    'fineStructureGate', fineStructureGate, ...
    'fineProtectionMask', fineProtection, ...
    'fineRetentionMap', fineRetentionMap, ...
    'retentionMap', fineRetentionMap, ...
    'midRetention', midRetention, ...
    'mediumRetention', midRetention, ...
    'midRetentionMap', midRetentionMap, ...
    'mediumRetentionMap', midRetentionMap, ...
    'fineActualRetentionMap', fineRetentionMap, ...
    'actualFineRetentionMap', fineRetentionMap, ...
    'midActualRetentionMap', midRetentionMap, ...
    'actualMidRetentionMap', midRetentionMap, ...
    'actualMediumRetentionMap', midRetentionMap, ...
    'protectionMask', max(cat(3, textureProtection, ...
    structureProtection, hardProtection), [], 3), ...
    'fineBefore', double(frequency.fine), ...
    'fineAfter', smoothedFine, ...
    'midBefore', double(frequency.mid), ...
    'midAfter', smoothedMid, ...
    'fineEnergyBefore', mean(abs(double(frequency.fine(:)))), ...
    'fineEnergyAfter', mean(abs(smoothedFine(:))), ...
    'midEnergyBefore', mean(abs(double(frequency.mid(:)))), ...
    'midEnergyAfter', mean(abs(smoothedMid(:))), ...
    'fineActualRetention', mean(fineRetentionMap(:)), ...
    'midActualRetention', mean(midRetentionMap(:)), ...
    'baseUnchanged', isequal(smoothed.base, frequency.base), ...
    'midUnchanged', isequal(smoothedMid, frequency.mid), ...
    'adaptiveStatisticsFrozen', true);
end

function row = emptySourceAblationRow
row = struct( ...
    'mode', '', 'region', '', 'source', '', 'roiPixels', 0, ...
    'analysisPixels', 0, 'sourceDominantPixels', 0, ...
    'baselineStructureMean', NaN, 'ablatedStructureMean', NaN, ...
    'structureReductionMean', NaN, 'frozenFineRetention', NaN, ...
    'frozenMidRetention', NaN, 'fineInputEnergyMean', NaN, ...
    'fineBaselineOutputEnergyMean', NaN, ...
    'fineBaselineRetentionRatio', NaN, ...
    'fineBaselineRetentionStatus', '', ...
    'fineAblatedOutputEnergyMean', NaN, ...
    'fineAblatedRetentionRatio', NaN, ...
    'fineAblatedRetentionStatus', '', 'midInputEnergyMean', NaN, ...
    'midBaselineOutputEnergyMean', NaN, ...
    'midBaselineRetentionRatio', NaN, ...
    'midBaselineRetentionStatus', '', ...
    'midAblatedOutputEnergyMean', NaN, ...
    'midAblatedRetentionRatio', NaN, ...
    'midAblatedRetentionStatus', '', ...
    'fineStageDifferenceMean', NaN, 'midStageDifferenceMean', NaN, ...
    'repairFineDifferenceMean', NaN, 'repairMidDifferenceMean', NaN, ...
    'finalRgbDifferenceMean', NaN, 'finalRgbDifferenceP90', NaN, ...
    'finalLuminanceDifferenceMean', NaN, 'hairPixels', 0, ...
    'eyePixels', 0, 'nosePixels', 0, 'backgroundPixels', 0, ...
    'hardProtectionPixels', 0, 'hairMaxChange', NaN, ...
    'eyeMaxChange', NaN, 'noseMaxChange', NaN, ...
    'backgroundMaxChange', NaN, 'hardProtectionMaxChange', NaN, ...
    'frozenBaselineMaxError', NaN, ...
    'adaptiveStatisticsFrozen', true, ...
    'repairRecomputationIsPropagation', true, ...
    'ablationProtocol', ['单项来源消融；冻结基线自适应统计和保留率；', ...
    'Repair 重算只作为下游传播后果。']);
end

function row = measureSourceAblation(mode, region, subset, item, ...
        baseline, structure, safetyMasks)
row = emptySourceAblationRow();
analysis = subset.mask;
roi = roiMask(region.roi, size(mode.image));
change = max(abs(double(item.output) - double(baseline.output)), [], 3);
row.mode = mode.name;
row.region = region.name;
row.source = item.source;
row.analysisPixels = nnz(analysis);
row.sourceDominantPixels = nnz(analysis & ...
    structure.dominantMask(:, :, item.sourceIndex));
row.baselineStructureMean = meanOn(structure.finalProtection, analysis);
row.ablatedStructureMean = meanOn(item.structureProtectionMask, analysis);
row.structureReductionMean = meanOn( ...
    max(structure.finalProtection - item.structureProtectionMask, 0), analysis);
row.frozenFineRetention = item.frozenFineRetention;
row.frozenMidRetention = item.frozenMidRetention;
[~, row.fineBaselineOutputEnergyMean, ...
    row.fineBaselineRetentionRatio, row.fineBaselineRetentionStatus] = ...
    energyRetention(double(baseline.frequencyForDiagnosis.fine), ...
    double(baseline.smoothingResult.fine), analysis);
[row.fineInputEnergyMean, row.fineAblatedOutputEnergyMean, ...
    row.fineAblatedRetentionRatio, row.fineAblatedRetentionStatus] = ...
    energyRetention(double(baseline.frequencyForDiagnosis.fine), ...
    double(item.smoothing.fine), analysis);
[~, row.midBaselineOutputEnergyMean, ...
    row.midBaselineRetentionRatio, row.midBaselineRetentionStatus] = ...
    energyRetention(double(baseline.frequencyForDiagnosis.mid), ...
    double(baseline.smoothingResult.mid), analysis);
[row.midInputEnergyMean, row.midAblatedOutputEnergyMean, ...
    row.midAblatedRetentionRatio, row.midAblatedRetentionStatus] = ...
    energyRetention(double(baseline.frequencyForDiagnosis.mid), ...
    double(item.smoothing.mid), analysis);
row.fineStageDifferenceMean = meanOn(abs(item.smoothing.fine - ...
    baseline.smoothingResult.fine), analysis);
row.midStageDifferenceMean = meanOn(abs(item.smoothing.mid - ...
    baseline.smoothingResult.mid), analysis);
row.repairFineDifferenceMean = meanOn(abs(item.repair.fine - ...
    baseline.repairResult.fine), analysis);
row.repairMidDifferenceMean = meanOn(abs(item.repair.mid - ...
    baseline.repairResult.mid), analysis);
row.finalRgbDifferenceMean = meanOn(change, analysis);
row.finalRgbDifferenceP90 = percentileOn(change, analysis, .90);
baselineY = rgb2ycbcr(im2double(baseline.output));
ablatedY = rgb2ycbcr(im2double(item.output));
row.finalLuminanceDifferenceMean = meanOn(abs(ablatedY(:, :, 1) - ...
    baselineY(:, :, 1)), analysis);
row.hairPixels = nnz(safetyMasks.hair);
row.eyePixels = nnz(safetyMasks.eye);
row.nosePixels = nnz(safetyMasks.nose);
row.backgroundPixels = nnz(safetyMasks.background);
row.hardProtectionPixels = nnz(safetyMasks.hard);
row.hairMaxChange = maxOn(change, safetyMasks.hair);
row.eyeMaxChange = maxOn(change, safetyMasks.eye);
row.noseMaxChange = maxOn(change, safetyMasks.nose);
row.backgroundMaxChange = maxOn(change, safetyMasks.background);
row.hardProtectionMaxChange = maxOn(change, safetyMasks.hard);
row.frozenBaselineMaxError = item.frozenBaselineMaxError;
row.adaptiveStatisticsFrozen = true;
row.repairRecomputationIsPropagation = true;
row.ablationProtocol = item.ablationProtocol;
row.roiPixels = nnz(roi);
end

function [energyBefore, energyAfter, ratio, status] = energyRetention( ...
        inputBand, outputBand, mask)
energyBefore = meanOn(abs(inputBand), mask);
energyAfter = meanOn(abs(outputBand), mask);
if isempty(inputBand(mask))
    ratio = NaN;
    status = '空选区';
elseif energyBefore <= eps
    ratio = NaN;
    status = '输入能量为零';
else
    ratio = energyAfter / energyBefore;
    status = '可用';
end
end

function [featureMasks, definitions] = buildFeatureMasks(context, safetyMasks)
imageSize = size(safetyMasks.hair);
regions = readSemanticStruct(context, 'regions', imageSize);
confidence = readSemanticStruct(context, 'regionConfidence', imageSize);
nose = semanticEvidence(regions, confidence, {'nose'}) >= .35;
columns = repmat(1:imageSize(2), imageSize(1), 1);
if any(nose(:))
    noseColumns = columns(nose);
    left = min(noseColumns);
    right = max(noseColumns);
    bridgeLeft = left + .25 * (right - left);
    bridgeRight = left + .75 * (right - left);
    noseBridge = nose & columns >= bridgeLeft & columns <= bridgeRight;
    noseWing = nose & ~noseBridge;
else
    noseBridge = false(imageSize);
    noseWing = false(imageSize);
end
featureMasks = struct( ...
    'noseBridge', noseBridge, ...
    'noseWing', noseWing, ...
    'facialFeatures', safetyMasks.facialFeatures, ...
    'hair', safetyMasks.hair, ...
    'background', safetyMasks.background);
definitions = struct( ...
    'noseBridge', '鼻语义支撑横向范围的中间 50%，仅作鼻梁近似测量', ...
    'noseWing', '鼻语义支撑横向范围的外侧区域，作为鼻翼近似测量', ...
    'facialFeatures', '眼、眉和口部语义证据 >= 0.35', ...
    'hair', 'hair 语义证据 >= 0.45', ...
    'background', 'background 语义证据 >= 0.45');
end

function rows = measureFeatureRows(mode, sourceName, item, baseline, ...
        featureMasks, definitions, lowPassSigma)
featureNames = fieldnames(featureMasks);
rows = repmat(emptyFeatureRow(), 0, 1);
inputLow = lowPassLuminance(mode.image, lowPassSigma);
baselineLow = lowPassLuminance(baseline.output, lowPassSigma);
ablatedLow = lowPassLuminance(item.output, lowPassSigma);
inputGradient = gradientMagnitudeOf(inputLow);
baselineGradient = gradientMagnitudeOf(baselineLow);
ablatedGradient = gradientMagnitudeOf(ablatedLow);
baselineRgbChange = max(abs(double(baseline.output) - ...
    double(mode.image)), [], 3);
ablatedRgbChange = max(abs(double(item.output) - ...
    double(mode.image)), [], 3);
for index = 1:numel(featureNames)
    name = featureNames{index};
    mask = featureMasks.(name);
    row = emptyFeatureRow();
    row.mode = mode.name;
    row.source = sourceName;
    row.feature = name;
    row.definition = definitions.(name);
    row.pixels = nnz(mask);
    row.inputLowFrequencyGradientMean = meanOn(inputGradient, mask);
    row.inputLowFrequencyGradientP90 = percentileOn(inputGradient, mask, .90);
    row.baselineLowFrequencyGradientMean = meanOn(baselineGradient, mask);
    row.baselineLowFrequencyGradientP90 = percentileOn( ...
        baselineGradient, mask, .90);
    row.ablatedLowFrequencyGradientMean = meanOn(ablatedGradient, mask);
    row.ablatedLowFrequencyGradientP90 = percentileOn( ...
        ablatedGradient, mask, .90);
    row.baselineGradientDifferenceMean = meanOn( ...
        abs(baselineGradient - inputGradient), mask);
    row.ablatedGradientDifferenceMean = meanOn( ...
        abs(ablatedGradient - inputGradient), mask);
    row.baselineRgbDifferenceMean = meanOn(baselineRgbChange, mask);
    row.ablatedRgbDifferenceMean = meanOn(ablatedRgbChange, mask);
    rows(end + 1, 1) = row; %#ok<AGROW>
end
end

function luminance = lowPassLuminance(image, sigma)
ycbcr = rgb2ycbcr(im2double(image));
luminance = imgaussfilt(ycbcr(:, :, 1), double(sigma), ...
    'Padding', 'replicate');
end

function magnitude = gradientMagnitudeOf(image)
[gradientX, gradientY] = gradient(image);
magnitude = hypot(gradientX, gradientY);
end

function row = measureRegion(mode, region, beautyMasks, ...
        baseline, ablation, frequency)
roi = roiMask(region.roi, size(mode.image));
faceSupport = roi & beautyMasks.faceSkinMask >= .35;
skinSupport = roi & beautyMasks.skinMask >= .05;
if ~any(faceSupport(:))
    analysis = roi & beautyMasks.skinMask >= .05;
else
    analysis = faceSupport;
end
smoothing = baseline.smoothing;
repair = baseline.repair;
compose = baseline.compose;
sourceY = rgb2ycbcr(im2double(mode.image));
outputY = rgb2ycbcr(im2double(baselineOutput(baseline, mode.image)));
row = emptyRegionRow();
row.mode = mode.name;
row.region = region.name;
row.roiX = region.roi(1);
row.roiY = region.roi(2);
row.roiWidth = region.roi(3);
row.roiHeight = region.roi(4);
row.roiPixels = nnz(roi);
row.skinSupportPixels = nnz(skinSupport);
row.faceSkinPixels = nnz(faceSupport);
row.analysisPixels = nnz(analysis);
row.skinSupportFraction = nnz(skinSupport) / nnz(roi);
row.faceSkinFraction = nnz(faceSupport) / nnz(roi);
row.faceSkinMean = meanOn(beautyMasks.faceSkinMask, roi);
row.faceSkinMedian = medianOn(beautyMasks.faceSkinMask, roi);
row.strengthMean = meanOn(beautyMasks.strengthMap, analysis);
row.strengthMedian = medianOn(beautyMasks.strengthMap, analysis);
row.structureProtectionMean = meanOn( ...
    beautyMasks.structureProtectionMask, analysis);
row.structureProtectionMedian = medianOn( ...
    beautyMasks.structureProtectionMask, analysis);
row.fineStructureGateMean = meanOn(smoothing.fineStructureGate, analysis);
row.fineStructureGateZeroFraction = fractionOf( ...
    smoothing.fineStructureGate <= 1e-12, analysis);
row.fineStructureGatePartialFraction = fractionOf( ...
    smoothing.fineStructureGate > 1e-12 & ...
    smoothing.fineStructureGate < 1 - 1e-12, analysis);
row.midStructureGateMean = meanOn(smoothing.midStructureGate, analysis);
row.midStructureGateZeroFraction = fractionOf( ...
    smoothing.midStructureGate <= 1e-12, analysis);
row.midStructureGatePartialFraction = fractionOf( ...
    smoothing.midStructureGate > 1e-12 & ...
    smoothing.midStructureGate < 1 - 1e-12, analysis);
row.noseMidGateMean = meanOn(smoothing.noseMidGate, analysis);
row.smoothingAlphaMean = meanOn(smoothing.alphaMap, analysis);
row.smoothingMidAlphaMean = meanOn(smoothing.midAlphaMap, analysis);
row.repairAllowedMean = meanOn(repair.allowed, analysis);
row.repairStructureGateMean = meanOn(repair.structureGate, analysis);
row.repairStructureGateZeroFraction = fractionOf( ...
    repair.structureGate <= 1e-12, analysis);
row.repairStructureGatePartialFraction = fractionOf( ...
    repair.structureGate > 1e-12 & repair.structureGate < 1 - 1e-12, ...
    analysis);
row.repairTextureGateMean = meanOn(repair.textureGate, analysis);
row.repairTextureGateZeroFraction = fractionOf( ...
    repair.textureGate <= 1e-12, analysis);
row.repairTextureGatePartialFraction = fractionOf( ...
    repair.textureGate > 1e-12 & repair.textureGate < 1 - 1e-12, ...
    analysis);
row.repairFineWeightMean = meanOn(repair.fineWeight, analysis);
row.repairMediumWeightMean = meanOn(repair.mediumWeight, analysis);
[
    row.fineInputEnergyMean, row.fineSmoothingEnergyMean, ...
    row.fineSmoothingRetentionRatio, row.fineSmoothingRetentionStatus] = ...
    energyRetention(double(frequency.fine), ...
    double(baseline.smoothingResult.fine), analysis);
[
    ~, row.fineRepairEnergyMean, row.fineRepairRetentionRatio, ...
    row.fineRepairRetentionStatus] = energyRetention( ...
    double(frequency.fine), double(baseline.repairResult.fine), analysis);
[
    row.midInputEnergyMean, row.midSmoothingEnergyMean, ...
    row.midSmoothingRetentionRatio, row.midSmoothingRetentionStatus] = ...
    energyRetention(double(frequency.mid), ...
    double(baseline.smoothingResult.mid), analysis);
[
    ~, row.midRepairEnergyMean, row.midRepairRetentionRatio, ...
    row.midRepairRetentionStatus] = energyRetention( ...
    double(frequency.mid), double(baseline.repairResult.mid), analysis);
row.smoothingFineActionMean = meanOn( ...
    abs(smoothing.fineAfter - smoothing.fineBefore), analysis);
row.smoothingMidActionMean = meanOn( ...
    abs(smoothing.midAfter - smoothing.midBefore), analysis);
row.repairFineActionMean = meanOn(abs(repair.fineCorrection), analysis);
row.repairMidActionMean = meanOn(abs(repair.mediumCorrection), analysis);
finalRgbChange = max(abs(double(baselineOutput(baseline, mode.image)) - ...
    double(mode.image)), [], 3);
row.finalRgbChangeMean = meanOn(finalRgbChange, roi);
row.finalRgbChangeP90 = percentileOn(finalRgbChange, roi, .90);
row.finalLuminanceChangeMean = meanOn( ...
    abs(outputY(:, :, 1) - sourceY(:, :, 1)), roi);
row.smoothingLuminanceActionMean = meanOn( ...
    abs(compose.smoothingDelta), analysis);
row.baseLuminanceActionMean = meanOn(abs(compose.baseDelta), analysis);
row.whiteningLuminanceActionMean = meanOn(abs(compose.whiteningDelta), analysis);
row.toneChromaActionMean = meanOn(max(abs(cat(3, ...
    compose.toneDeltaCb, compose.toneDeltaCr)), [], 3), analysis);
if isfield(ablation, 'midWithoutRepeated') && ...
        isfield(ablation.midWithoutRepeated, 'suppression') && ...
        any(isfinite(ablation.midWithoutRepeated.suppression(:)))
    row.midRepeatedGateSuppressionMean = meanOn( ...
        ablation.midWithoutRepeated.suppression, analysis);
    row.midRepeatedGateChangedFraction = fractionOf( ...
        ablation.midWithoutRepeated.suppression > 1e-12, analysis);
end
if numel(ablation.items) >= 3
    row.structureAblationSmoothingAlphaGainMean = meanOn( ...
        max(ablation.items(1).smoothing.alphaMap - smoothing.alphaMap, 0), ...
        analysis);
    row.structureAblationSmoothingFineActionChangeMean = meanOn( ...
        abs(ablation.items(1).smoothingDetails.fineAfter - ...
        ablation.items(1).smoothingDetails.fineBefore) - ...
        abs(smoothing.fineAfter - smoothing.fineBefore), analysis);
    row.structureAblationRepairChangeMean = meanOn( ...
        max(abs(ablation.items(2).repair.fine - ...
        baseline.repairResult.fine), abs(ablation.items(2).repair.mid - ...
        baseline.repairResult.mid)), analysis);
    row.textureAblationRepairChangeMean = meanOn( ...
        max(abs(ablation.items(3).repair.fine - ...
        baseline.repairResult.fine), abs(ablation.items(3).repair.mid - ...
        baseline.repairResult.mid)), analysis);
end
end

function row = measureAblation(mode, region, item, baseline, safetyMasks)
roi = roiMask(region.roi, size(mode.image));
analysis = roi & baseline.beautyMasks.faceSkinMask >= .35;
if ~any(analysis(:))
    analysis = roi & baseline.beautyMasks.skinMask >= .05;
end
change = max(abs(double(item.output) - ...
    double(baselineOutput(baseline, mode.image))), [], 3);
row = emptyAblationRow();
row.mode = mode.name;
row.region = region.name;
row.ablation = item.name;
row.analysisPixels = nnz(analysis);
row.finalRgbDifferenceMean = meanOn(change, analysis);
row.finalRgbDifferenceP90 = percentileOn(change, analysis, .90);
baselineY = rgb2ycbcr(im2double(baselineOutput(baseline, mode.image)));
ablatedY = rgb2ycbcr(im2double(item.output));
row.finalLuminanceDifferenceMean = meanOn( ...
    abs(ablatedY(:, :, 1) - baselineY(:, :, 1)), analysis);
row.fineStageDifferenceMean = meanOn(abs(item.smoothing.fine - ...
    baseline.smoothingResult.fine), analysis);
row.midStageDifferenceMean = meanOn(abs(item.smoothing.mid - ...
    baseline.smoothingResult.mid), analysis);
row.repairFineDifferenceMean = meanOn(abs(item.repair.fine - ...
    baseline.repairResult.fine), analysis);
row.repairMidDifferenceMean = meanOn(abs(item.repair.mid - ...
    baseline.repairResult.mid), analysis);
row.hairMaxChange = maxOn(change, safetyMasks.hair);
row.eyeMaxChange = maxOn(change, safetyMasks.eye);
row.noseMaxChange = maxOn(change, safetyMasks.nose);
row.backgroundMaxChange = maxOn(change, safetyMasks.background);
row.hardProtectionMaxChange = maxOn(change, safetyMasks.hard);
end

function output = baselineOutput(baseline, fallback)
if isfield(baseline, 'output')
    output = baseline.output;
else
    output = fallback;
end
end

function safety = buildSafetyMasks(context, beautyMasks)
imageSize = size(beautyMasks.skinMask);
regions = readSemanticStruct(context, 'regions', imageSize);
confidence = readSemanticStruct(context, 'regionConfidence', imageSize);
safety = struct( ...
    'hair', semanticEvidence(regions, confidence, {'hair'}) >= .45, ...
    'eye', semanticEvidence(regions, confidence, ...
    {'leftEye', 'rightEye'}) >= .45, ...
    'nose', semanticEvidence(regions, confidence, {'nose'}) >= .35, ...
    'facialFeatures', semanticEvidence(regions, confidence, ...
    {'leftEye', 'rightEye', 'leftBrow', 'rightBrow', 'mouth', ...
    'upperLip', 'lowerLip'}) >= .35, ...
    'background', semanticEvidence(regions, confidence, ...
    {'background'}) >= .45, ...
    'hard', beautyMasks.hardProtectionMask >= .999);
end

function values = readSemanticStruct(context, fieldName, imageSize)
names = faceParsingClassNames();
values = struct();
if isfield(context, fieldName)
    source = context.(fieldName);
else
    source = struct();
end
for index = 1:numel(names)
    name = names{index};
    if isfield(source, name) && isequal(size(source.(name)), imageSize)
        values.(name) = double(source.(name));
    else
        values.(name) = zeros(imageSize);
    end
end
end

function evidence = semanticEvidence(regions, confidence, names)
allNames = faceParsingClassNames();
reference = regions.(allNames{1});
evidence = zeros(size(reference));
for index = 1:numel(names)
    evidence = max(evidence, min(regions.(names{index}), ...
        confidence.(names{index})));
end
end

function values = compactModeDiagnostics(modeDiagnostics)
values = cell(size(modeDiagnostics));
for index = 1:numel(modeDiagnostics)
    mode = modeDiagnostics{index};
    baseline = mode.baseline;
    maps = struct( ...
        'skinMask', compactArray(mode.context.skinMask), ...
        'faceSkinMask', compactArray(mode.context.faceSkinMask), ...
        'strengthMap', compactArray(baseline.beautyMasks.strengthMap), ...
        'structureProtectionMask', compactArray( ...
        baseline.beautyMasks.structureProtectionMask), ...
        'textureProtectionMask', compactArray( ...
        baseline.beautyMasks.textureProtectionMask), ...
        'hardProtectionMask', compactArray( ...
        baseline.beautyMasks.hardProtectionMask), ...
        'fineStructureGate', compactArray( ...
        baseline.smoothing.fineStructureGate), ...
        'midStructureGate', compactArray( ...
        baseline.smoothing.midStructureGate), ...
        'noseMidGate', compactArray(baseline.smoothing.noseMidGate), ...
        'smoothingAlpha', compactArray(baseline.smoothing.alphaMap), ...
        'smoothingMidAlpha', compactArray( ...
        baseline.smoothing.midAlphaMap), ...
        'repairAllowed', compactArray(baseline.repair.allowed), ...
        'repairStructureGate', compactArray( ...
        baseline.repair.structureGate), ...
        'repairTextureGate', compactArray(baseline.repair.textureGate), ...
        'repairFineWeight', compactArray(baseline.repair.fineWeight), ...
        'repairMediumWeight', compactArray( ...
        baseline.repair.mediumWeight), ...
        'repairFineCorrection', compactArray( ...
        baseline.repair.fineCorrection), ...
        'repairMediumCorrection', compactArray( ...
        baseline.repair.mediumCorrection), ...
        'blemishMap', compactArray(baseline.blemishMap), ...
        'finalRgbChange', compactArray(max(abs(double(mode.output) - ...
        double(mode.image)), [], 3)), ...
        'smoothingLuminanceDelta', compactArray( ...
        baseline.compose.smoothingDelta), ...
        'baseLuminanceDelta', compactArray(baseline.compose.baseDelta), ...
        'whiteningLuminanceDelta', compactArray( ...
        baseline.compose.whiteningDelta), ...
        'toneDeltaCb', compactArray(baseline.compose.toneDeltaCb), ...
        'toneDeltaCr', compactArray(baseline.compose.toneDeltaCr), ...
        'luminanceDelta', compactArray(baseline.compose.luminanceDelta));
    ablationOutputs = cell(1, numel(mode.ablation.items));
    for ablationIndex = 1:numel(mode.ablation.items)
        ablationOutputs{ablationIndex} = ...
            mode.ablation.items(ablationIndex).output;
    end
    values{index} = struct( ...
        'name', mode.name, ...
        'image', mode.image, ...
        'output', mode.output, ...
        'faceBox', mode.faceBox, ...
        'faceBoundaryRoi', mode.faceBoundaryRoi, ...
        'controlRoi', mode.controlRoi, ...
        'maps', maps, ...
        'ablationOutputs', {ablationOutputs}, ...
        'midRepeatedGateSuppression', compactArray( ...
        mode.ablation.midWithoutRepeated.suppression), ...
        'attribution', compactAttribution(mode.attribution.details), ...
        'safetyMasks', mode.safetyMasks);
end
end

function value = compactAttribution(attribution)
items = attribution.sourceAblations;
sourceOutputs = cell(1, numel(items));
sourceStructures = cell(1, numel(items));
for index = 1:numel(items)
    sourceOutputs{index} = items(index).output;
    sourceStructures{index} = compactArray( ...
        items(index).structureProtectionMask);
end
value = struct( ...
    'sourceNames', {attribution.sourceNames}, ...
    'rawSources', compactArray(attribution.structure.rawSources), ...
    'effectiveSources', compactArray( ...
    attribution.structure.effectiveSources), ...
    'finalProtection', compactArray(attribution.structure.finalProtection), ...
    'reconstructionError', compactArray( ...
    attribution.structure.reconstructionError), ...
    'dominantIndex', compactArray(attribution.structure.dominantIndex), ...
    'tieMask', attribution.structure.tieMask, ...
    'gradientMagnitude', compactArray( ...
    attribution.structure.gradientMagnitude), ...
    'orientationCoherence', compactArray( ...
    attribution.structure.orientationCoherence), ...
    'continuousEvidence', compactArray( ...
    attribution.structure.continuousEvidence), ...
    'inputGradientMagnitude', compactArray( ...
    attribution.structure.inputGradientMagnitude), ...
    'lowFrequencyContrast', compactArray( ...
    attribution.structure.lowFrequencyContrast), ...
    'reconstructionMaxAbsError', ...
    attribution.structure.reconstructionMaxAbsError, ...
    'frozenBaselineMaxError', attribution.structure.frozenBaselineMaxError, ...
    'sourceAblationOutputs', {sourceOutputs}, ...
    'sourceAblationStructures', {sourceStructures}, ...
    'featureMasks', compactFeatureMasks(attribution.featureMasks), ...
    'measurement', attribution.measurement);
end

function value = compactFeatureMasks(masks)
names = fieldnames(masks);
value = struct();
for index = 1:numel(names)
    value.(names{index}) = masks.(names{index});
end
end

function value = compactDetection(detection)
value = detection;
if isfield(value, 'selectedParsing')
    value = rmfield(value, 'selectedParsing');
end
end

function value = compactArray(value)
if isnumeric(value) && ~isa(value, 'uint8') && ~isa(value, 'single')
    value = single(value);
end
end

function paths = writeArtifacts(outputFolder, modeDiagnostics, ...
        regionMetrics, ablationMetrics, sourceMetrics, ...
        sourceAblationMetrics, featureMetrics)
writetable(regionMetrics, fullfile(outputFolder, ...
    'faceBoundaryRegionMetrics.csv'));
writetable(ablationMetrics, fullfile(outputFolder, ...
    'faceBoundaryAblationMetrics.csv'));
writetable(sourceMetrics, fullfile(outputFolder, ...
    'faceBoundarySourceMetrics.csv'));
writetable(sourceAblationMetrics, fullfile(outputFolder, ...
    'faceBoundarySourceAblationMetrics.csv'));
writetable(featureMetrics, fullfile(outputFolder, ...
    'faceBoundaryFeatureMetrics.csv'));
paths = struct();
for index = 1:numel(modeDiagnostics)
    mode = modeDiagnostics{index};
    comparePath = fullfile(outputFolder, ...
        [mode.name, '-faceBoundaryCompare.png']);
    mapPath = fullfile(outputFolder, ...
        [mode.name, '-faceBoundaryMaps.png']);
    sourcePath = fullfile(outputFolder, ...
        [mode.name, '-faceBoundarySources.png']);
    sourceAblationPath = fullfile(outputFolder, ...
        [mode.name, '-faceBoundarySourceAblations.png']);
    writeComparisonFigure(mode, comparePath);
    writeMapsFigure(mode, mapPath);
    writeSourceFigure(mode, sourcePath);
    writeSourceAblationFigure(mode, sourceAblationPath);
    paths.(mode.name) = struct('compare', comparePath, ...
        'maps', mapPath, 'sources', sourcePath, ...
        'sourceAblations', sourceAblationPath);
    if ~isempty(mode.ablation.items)
        ablationPath = fullfile(outputFolder, ...
            [mode.name, '-faceBoundaryAblation.png']);
        writeAblationFigure(mode, ablationPath);
        paths.(mode.name).legacyAblation = ablationPath;
    end
end
paths.regionMetrics = fullfile(outputFolder, 'faceBoundaryRegionMetrics.csv');
paths.ablationMetrics = fullfile(outputFolder, ...
    'faceBoundaryAblationMetrics.csv');
paths.sourceMetrics = fullfile(outputFolder, 'faceBoundarySourceMetrics.csv');
paths.sourceAblationMetrics = fullfile(outputFolder, ...
    'faceBoundarySourceAblationMetrics.csv');
paths.featureMetrics = fullfile(outputFolder, 'faceBoundaryFeatureMetrics.csv');
end

function writeComparisonFigure(mode, outputPath)
figureHandle = figure('Visible', 'off', 'Color', 'white');
tiledlayout(1, 3, 'Padding', 'compact', 'TileSpacing', 'compact');
nexttile;
imshow(mode.image);
title('输入');
drawRois(mode);
nexttile;
imshow(mode.output);
title('v3.2 基线输出');
drawRois(mode);
nexttile;
difference = max(abs(double(mode.output) - double(mode.image)), [], 3);
imagesc(difference);
axis image off;
clim([0, 32]);
colorbar;
title('最终 RGB 变化（0--32）');
drawRois(mode);
exportgraphics(figureHandle, outputPath, 'Resolution', 140);
close(figureHandle);
end

function writeMapsFigure(mode, outputPath)
baseline = mode.baseline;
maps = { ...
    mode.context.skinMask, mode.context.faceSkinMask, ...
    baseline.beautyMasks.strengthMap, ...
    baseline.beautyMasks.structureProtectionMask, ...
    baseline.smoothing.fineStructureGate, ...
    baseline.smoothing.midStructureGate, baseline.smoothing.alphaMap, ...
    baseline.smoothing.midAlphaMap, baseline.repair.allowed, ...
    baseline.repair.structureGate, baseline.repair.textureGate, ...
    baseline.repair.repairWeight, ...
    abs(baseline.repair.fineCorrection), ...
    abs(baseline.repair.mediumCorrection), ...
    max(abs(double(mode.output) - double(mode.image)), [], 3)};
labels = {'皮肤支持', '脸部皮肤', '强度', '结构保护', ...
    'Fine 结构门控', 'Mid 结构门控', 'Fine 作用门控', ...
    'Mid 作用门控', 'Repair allowed', 'Repair 结构门控', ...
    'Repair 纹理门控', 'Repair 总权重', 'Repair Fine 作用量', ...
    'Repair Mid 作用量', '最终 RGB 变化'};
figureHandle = figure('Visible', 'off', 'Color', 'white');
tiledlayout(3, 5, 'Padding', 'compact', 'TileSpacing', 'compact');
for index = 1:numel(maps)
    nexttile;
    imagesc(maps{index});
    axis image off;
    colorbar;
    if index == numel(maps)
        clim([0, 32]);
    else
        clim([0, 1]);
    end
    title(labels{index});
    drawRois(mode);
end
exportgraphics(figureHandle, outputPath, 'Resolution', 140);
close(figureHandle);
end

function writeSourceFigure(mode, outputPath)
attribution = mode.attribution.details;
structure = attribution.structure;
figureHandle = figure('Visible', 'off', 'Color', 'white');
tiledlayout(4, 4, 'Padding', 'compact', 'TileSpacing', 'compact');
nexttile;
imshow(mode.image);
title('输入与固定选区');
drawRois(mode);
for index = 1:numel(structure.sourceNames)
    nexttile;
    showDiagnosticMap(structure.rawSources(:, :, index), ...
        structure.sourceNames{index}, [0, 1]);
    drawRois(mode);
end
nexttile;
showDiagnosticMap(structure.finalProtection, '四来源最终保护', [0, 1]);
drawRois(mode);
nexttile;
showDiagnosticMap(structure.dominantIndex, ...
    '唯一最大来源（0=非唯一/无作用）', [0, 4]);
drawRois(mode);
nexttile;
showDiagnosticMap(double(structure.tieMask), '并列最大来源', [0, 1]);
drawRois(mode);
nexttile;
showDiagnosticMap(structure.gradientMagnitude, ...
    '低频梯度幅值', []);
drawRois(mode);
nexttile;
showDiagnosticMap(structure.orientationCoherence, ...
    '方向连续性', [0, 1]);
drawRois(mode);
nexttile;
showDiagnosticMap(structure.continuousEvidence, ...
    '连续结构证据', [0, 1]);
drawRois(mode);
nexttile;
showDiagnosticMap(structure.lowFrequencyContrast, ...
    '低频局部对比', []);
drawRois(mode);
nexttile;
showDiagnosticMap(structure.inputGradientMagnitude, ...
    '原图亮度梯度', []);
drawRois(mode);
nexttile;
imshow(mode.image);
hold on;
boundary = structure.dominantMask(:, :, 4);
if any(boundary(:))
    contour(boundary, [.5, .5], 'r', 'LineWidth', 1.2);
end
title('原图叠加 faceBoundary 唯一主导');
drawRois(mode);
hold off;
nexttile;
showDiagnosticMap(structure.reconstructionError, ...
    '来源重建误差', [-1e-12, 1e-12]);
drawRois(mode);
exportgraphics(figureHandle, outputPath, 'Resolution', 140);
close(figureHandle);
end

function writeSourceAblationFigure(mode, outputPath)
attribution = mode.attribution.details;
items = attribution.sourceAblations;
figureHandle = figure('Visible', 'off', 'Color', 'white');
tiledlayout(2, 3, 'Padding', 'compact', 'TileSpacing', 'compact');
nexttile;
imshow(mode.output);
title('v3.2 基线');
drawRois(mode);
maximumChange = zeros(size(mode.image, 1:2));
for index = 1:numel(items)
    nexttile;
    imshow(items(index).output);
    title(['移除 ', items(index).source]);
    drawRois(mode);
    currentChange = max(abs(double(items(index).output) - ...
        double(mode.output)), [], 3);
    maximumChange = max(maximumChange, currentChange);
end
nexttile;
imagesc(maximumChange);
axis image off;
clim([0, 32]);
colorbar;
title('四项来源消融最大 RGB 差');
drawRois(mode);
exportgraphics(figureHandle, outputPath, 'Resolution', 140);
close(figureHandle);
end

function showDiagnosticMap(map, label, limits)
imagesc(map);
axis image off;
colorbar;
if ~isempty(limits)
    clim(limits);
end
title(label);
end

function writeAblationFigure(mode, outputPath)
labels = {'移除平滑结构门控', '移除 Repair 结构门控', ...
    '移除 Repair 纹理门控', '移除 Mid 第二次门控'};
figureHandle = figure('Visible', 'off', 'Color', 'white');
tiledlayout(2, 3, 'Padding', 'compact', 'TileSpacing', 'compact');
nexttile;
imshow(mode.output);
title('v3.2 基线');
drawRois(mode);
for index = 1:numel(mode.ablation.items)
    nexttile;
    imshow(mode.ablation.items(index).output);
    title(labels{index});
    drawRois(mode);
end
exportgraphics(figureHandle, outputPath, 'Resolution', 140);
close(figureHandle);
end

function drawRois(mode)
hold on;
rectangle('Position', mode.faceBoundaryRoi, ...
    'EdgeColor', 'c', 'LineWidth', 1.5);
rectangle('Position', mode.controlRoi, ...
    'EdgeColor', 'm', 'LineWidth', 1.5);
hold off;
end

function value = meanOn(data, mask)
values = double(data(mask));
if isempty(values)
    value = NaN;
else
    value = mean(values);
end
end

function value = medianOn(data, mask)
values = double(data(mask));
if isempty(values)
    value = NaN;
else
    value = median(values);
end
end

function value = percentileOn(data, mask, fraction)
values = sort(double(data(mask)));
if isempty(values)
    value = NaN;
    return;
end
position = 1 + fraction * (numel(values) - 1);
lower = floor(position);
upper = ceil(position);
if lower == upper
    value = values(lower);
else
    weight = position - lower;
    value = (1 - weight) * values(lower) + weight * values(upper);
end
end

function value = fractionOf(condition, mask)
count = nnz(mask);
if count == 0
    value = NaN;
else
    value = nnz(condition & mask) / count;
end
end

function value = fractionWithDenominator(numerator, denominator)
if denominator == 0
    value = NaN;
else
    value = double(numerator) / double(denominator);
end
end

function value = maxOn(data, mask)
values = double(data(mask));
if isempty(values)
    value = NaN;
else
    value = max(values);
end
end

function roi = roiMask(box, imageSize)
roi = false(imageSize(1), imageSize(2));
x1 = box(1);
y1 = box(2);
x2 = min(imageSize(2), x1 + box(3) - 1);
y2 = min(imageSize(1), y1 + box(4) - 1);
roi(y1:y2, x1:x2) = true;
end

function box = validateRoi(box, name)
if ~isnumeric(box) || ~isreal(box) || ~isequal(size(box), [1, 4]) || ...
        any(~isfinite(box)) || any(box(1:2) < 1) || ...
        any(box(3:4) < 1)
    error('diagnoseFaceBoundaryCoverage:InvalidRoi', ...
        '%s 必须是正整数 [x y width height]。', name);
end
box = round(double(box));
end

function box = validateRoiBounds(box, imageSize, name)
if box(1) + box(3) - 1 > imageSize(2) || ...
        box(2) + box(4) - 1 > imageSize(1)
    error('diagnoseFaceBoundaryCoverage:InvalidRoi', ...
        '%s 超出输入图像范围。', name);
end
end

function box = scaleRoi(sourceBox, scale, imageSize)
box = round(double(sourceBox) * scale);
box(1:2) = max(box(1:2), 1);
x2 = min(imageSize(2), box(1) + box(3) - 1);
y2 = min(imageSize(1), box(2) + box(4) - 1);
box(3:4) = max(1, [x2 - box(1) + 1, y2 - box(2) + 1]);
end

function [preview, scale] = makePreview(image)
scale = min(1, 640 / max(size(image, 1), size(image, 2)));
if scale < 1
    preview = imresize(image, scale, 'bilinear');
else
    preview = image;
end
end

function box = scaleFaceBox(box, scale, imageSize)
box = round(double(box) * scale);
box(1) = max(1, min(box(1), imageSize(2)));
box(2) = max(1, min(box(2), imageSize(1)));
x2 = min(imageSize(2), box(1) + box(3) - 1);
y2 = min(imageSize(1), box(2) + box(4) - 1);
box(3:4) = max(1, [x2 - box(1) + 1, y2 - box(2) + 1]);
end

function valid = isValidStrength(value)
valid = isnumeric(value) && isreal(value) && isscalar(value) && ...
    isfinite(value) && value >= 0 && value <= 100;
end

function row = emptySourceRow
row = struct( ...
    'mode', '', 'region', '', 'gateSubset', '', ...
    'gateSubsetDefinition', '', 'source', '', 'roiPixels', 0, ...
    'analysisPixels', 0, 'activeProtectionPixels', 0, ...
    'dominantPixels', 0, 'sourceRawMean', NaN, ...
    'sourceRawMedian', NaN, 'sourceRawP90', NaN, ...
    'sourceRawMax', NaN, 'sourceEffectiveMean', NaN, ...
    'sourceEffectiveMedian', NaN, 'sourceEffectiveP90', NaN, ...
    'sourceEffectiveMax', NaN, 'sourcePositiveFraction', NaN, ...
    'dominanceFraction', NaN, 'dominanceDenominatorPixels', 0, ...
    'tiePixels', 0, 'tieFraction', NaN, ...
    'dominantGradientMean', NaN, 'dominantGradientP90', NaN, ...
    'dominantOrientationCoherenceMean', NaN, ...
    'dominantOrientationCoherenceP90', NaN, ...
    'dominantContinuousEvidenceMean', NaN, ...
    'dominantInputGradientMean', NaN, ...
    'dominantInputGradientP90', NaN, ...
    'dominantLowFrequencyContrastMean', NaN, ...
    'dominantLowFrequencyContrastP90', NaN);
end

function row = emptyFeatureRow
row = struct( ...
    'mode', '', 'source', '', 'feature', '', 'definition', '', ...
    'pixels', 0, 'inputLowFrequencyGradientMean', NaN, ...
    'inputLowFrequencyGradientP90', NaN, ...
    'baselineLowFrequencyGradientMean', NaN, ...
    'baselineLowFrequencyGradientP90', NaN, ...
    'ablatedLowFrequencyGradientMean', NaN, ...
    'ablatedLowFrequencyGradientP90', NaN, ...
    'baselineGradientDifferenceMean', NaN, ...
    'ablatedGradientDifferenceMean', NaN, ...
    'baselineRgbDifferenceMean', NaN, ...
    'ablatedRgbDifferenceMean', NaN);
end

function row = emptyRegionRow
row = struct( ...
    'mode', '', 'region', '', 'roiX', 0, 'roiY', 0, 'roiWidth', 0, ...
    'roiHeight', 0, 'roiPixels', 0, 'skinSupportPixels', 0, ...
    'faceSkinPixels', 0, 'analysisPixels', 0, ...
    'skinSupportFraction', NaN, ...
    'faceSkinFraction', NaN, 'faceSkinMean', NaN, 'faceSkinMedian', NaN, ...
    'strengthMean', NaN, 'strengthMedian', NaN, ...
    'structureProtectionMean', NaN, 'structureProtectionMedian', NaN, ...
    'fineStructureGateMean', NaN, 'fineStructureGateZeroFraction', NaN, ...
    'fineStructureGatePartialFraction', NaN, 'midStructureGateMean', NaN, ...
    'midStructureGateZeroFraction', NaN, ...
    'midStructureGatePartialFraction', NaN, 'noseMidGateMean', NaN, ...
    'smoothingAlphaMean', NaN, 'smoothingMidAlphaMean', NaN, ...
    'repairAllowedMean', NaN, 'repairStructureGateMean', NaN, ...
    'repairStructureGateZeroFraction', NaN, ...
    'repairStructureGatePartialFraction', NaN, ...
    'repairTextureGateMean', NaN, 'repairTextureGateZeroFraction', NaN, ...
    'repairTextureGatePartialFraction', NaN, ...
    'repairFineWeightMean', NaN, 'repairMediumWeightMean', NaN, ...
    'fineInputEnergyMean', NaN, 'fineSmoothingEnergyMean', NaN, ...
    'fineSmoothingRetentionRatio', NaN, ...
    'fineSmoothingRetentionStatus', '', 'fineRepairEnergyMean', NaN, ...
    'fineRepairRetentionRatio', NaN, 'fineRepairRetentionStatus', '', ...
    'midInputEnergyMean', NaN, 'midSmoothingEnergyMean', NaN, ...
    'midSmoothingRetentionRatio', NaN, ...
    'midSmoothingRetentionStatus', '', 'midRepairEnergyMean', NaN, ...
    'midRepairRetentionRatio', NaN, 'midRepairRetentionStatus', '', ...
    'smoothingFineActionMean', NaN, 'smoothingMidActionMean', NaN, ...
    'repairFineActionMean', NaN, 'repairMidActionMean', NaN, ...
    'finalRgbChangeMean', NaN, 'finalRgbChangeP90', NaN, ...
    'finalLuminanceChangeMean', NaN, ...
    'smoothingLuminanceActionMean', NaN, ...
    'baseLuminanceActionMean', NaN, ...
    'whiteningLuminanceActionMean', NaN, ...
    'toneChromaActionMean', NaN, ...
    'midRepeatedGateSuppressionMean', NaN, ...
    'midRepeatedGateChangedFraction', NaN, ...
    'structureAblationSmoothingAlphaGainMean', NaN, ...
    'structureAblationSmoothingFineActionChangeMean', NaN, ...
    'structureAblationRepairChangeMean', NaN, ...
    'textureAblationRepairChangeMean', NaN);
end

function row = emptyAblationRow
row = struct( ...
    'mode', '', 'region', '', 'ablation', '', 'analysisPixels', 0, ...
    'finalRgbDifferenceMean', NaN, 'finalRgbDifferenceP90', NaN, ...
    'finalLuminanceDifferenceMean', NaN, ...
    'fineStageDifferenceMean', NaN, 'midStageDifferenceMean', NaN, ...
    'repairFineDifferenceMean', NaN, 'repairMidDifferenceMean', NaN, ...
    'hairMaxChange', NaN, 'eyeMaxChange', NaN, 'noseMaxChange', NaN, ...
    'backgroundMaxChange', NaN, 'hardProtectionMaxChange', NaN);
end
