function [summary, diagnostics] = diagnoseLashSupportGeometryCandidate( ...
        imagePath, outputFolder, options)
%DIAGNOSELASHSUPPORTGEOMETRYCANDIDATE 验证 Issue 08.6 唯一几何候选。
%   本入口不修改生产 src。它固定复用 77.png、77-manual-lash-v1、
%   faceBox/browEye/lashRoi、磨皮 100、美白 15 和当前生产链；Baseline
%   与 08.4 Candidate 由既有诊断入口生成，08.6 只替换 lash support
%   geometry，并继续执行同一 Smoothing、Repair 和 compose。
%
%   08.6 的几何候选只复用当前 buildTextureProtectionMask.m 已有的：
%   darkCandidate、edgeCandidate、lineSupport、eyeNeighborhood、当前
%   detector candidate seed、faceScale 派生尺度和当前 featherSoftMask
%   语义。候选使用 evidence 中与既有 detector seed 连通的区域；不使用
%   manualLashMask 生成候选，不新增模型、特征、阈值或绝对像素尺度。
%
%   [summary, diagnostics] = diagnoseLashSupportGeometryCandidate( ...
%       'E:\image_beauty\人脸\人脸\77.png', tempdir, struct( ...
%       'productionRoot', 'E:\image_beauty', ...
%       'baselinePath', ...
%       'C:\Users\JJiio\AppData\Local\Temp\image_beauty_issue02_probe\77_v32_probe.mat'));

projectRoot = fileparts(fileparts(mfilename('fullpath')));
if nargin < 2
    outputFolder = [];
end
if nargin < 3
    options = [];
end
options = normalizeOptions(options, projectRoot);

productionRoot = resolveProductionRoot(options.productionRoot);
addpath(fullfile(productionRoot, 'src'), '-begin');
addpath(fileparts(mfilename('fullpath')), '-begin');

if nargin < 1 || isempty(imagePath)
    error('diagnoseLashSupportGeometryCandidate:MissingImage', ...
        '必须提供固定 77.png 的输入图像路径。');
end
imagePath = normalizeText(imagePath, 'imagePath');
inputImage = readInputImage(imagePath);
imageSize = [size(inputImage, 1), size(inputImage, 2)];
validateFixed77Fixture(inputImage, options);
outputFolder = normalizeOutputFolder(outputFolder);

% 先复用已完成的 08.4 诊断，得到同一次生产基线、08.4 Candidate、
% frequency、blemishMap、其它 Mask 和冻结的 Base/tone/whitening。08.4
% Candidate 的生成路径本身不消费 manualLashMask；其人工真值只用于统计。
stageFolder = tempname;
mkdir(stageFolder);
[continuitySummary, continuityDiagnostics] = ...
    diagnoseLashSoftContinuityCandidate(imagePath, stageFolder, options);
validateContinuityStage(continuitySummary, continuityDiagnostics, imageSize);

manualLashMask = continuityDiagnostics.manualLashMask;
annotation = continuityDiagnostics.annotation;
if ~annotation.diagnosticsIndependent || ~annotation.fixedAfterAnnotation || ...
        ~strcmp(annotation.annotationId, '77-manual-lash-v1')
    error('diagnoseLashSupportGeometryCandidate:InvalidManualTruth', ...
        'manualLashMask 必须是固定、独立的 77-manual-lash-v1。');
end

loaded = loadBaselineContext(options.baselinePath);
sourceContext = stripDerivedContext(loaded.context);
faceScale = readFaceScale(continuityDiagnostics.frequency, options.faceBox);

baselineBeautyMasks = continuityDiagnostics.baselineBeautyMasks;
baselineTextureDiagnostics = continuityDiagnostics.baselineTextureDiagnostics;
baselineLashProtection = readDiagnosticArray( ...
    continuityDiagnostics.baselineLashProtection, imageSize, ...
    'baselineLashProtection');
validateTextureDiagnostics(baselineTextureDiagnostics, imageSize);

% 重新读取当前 detector 已有的内部 evidence。该函数只消费原图、固定
% Context 的 regions/regionConfidence 和 faceScale，不接收人工真值。
evidence = reconstructExistingLashEvidence(inputImage, sourceContext, ...
    faceScale);
validateEvidenceReconstruction(evidence, baselineTextureDiagnostics, ...
    baselineLashProtection, imageSize, options.formulaTolerance);
evidence.reconstructionMaxError = max(abs( ...
    evidence.existingLashProtection(:) - baselineLashProtection(:)));

% 唯一 08.6 几何候选：现有 detector seed 在已有 dark/edge/line evidence
% 中的连通重构；soft 值复用 detector 当前 featherSoftMask(radius, .99)。
candidateGeometrySeed = evidence.connectedEvidence;
candidateLashProtection = featherSoftMask(candidateGeometrySeed, ...
    evidence.softRadius, evidence.softPeak);
candidateLashProtection(~evidence.eyeNeighborhood) = 0;
candidateLashProtection = min(max(double(candidateLashProtection), 0), 1);
validateMask(candidateLashProtection, imageSize, ...
    'candidateLashProtection');

periocularProtection = readDiagnosticArray( ...
    baselineTextureDiagnostics.periocularProtection, imageSize, ...
    'periocularProtection');
doubleEyelidProtection = readDiagnosticArray( ...
    baselineTextureDiagnostics.doubleEyelidProtection, imageSize, ...
    'doubleEyelidProtection');
reconstructedBaselineEyeDetail = max(cat(3, periocularProtection, ...
    baselineLashProtection, doubleEyelidProtection), [], 3);
baselineEyeDetail = readDiagnosticArray( ...
    baselineTextureDiagnostics.eyeDetailProtection, imageSize, ...
    'baselineEyeDetailProtection');
if max(abs(reconstructedBaselineEyeDetail(:) - baselineEyeDetail(:))) > ...
        options.formulaTolerance
    error('diagnoseLashSupportGeometryCandidate:EyeDetailAggregationMismatch', ...
        'Baseline eyeDetailProtection 聚合不一致。');
end

candidateEyeDetailProtection = max(cat(3, periocularProtection, ...
    candidateLashProtection, doubleEyelidProtection), [], 3);
% 08.6 是 geometry replacement，不把旧 lashProtection 再次 max 回去；
% 其它 texture components 仍逐项冻结。
fixedTextureComponents = max(cat(3, ...
    readDiagnosticArray(baselineTextureDiagnostics.occluderProtection, ...
    imageSize, 'occluderProtection'), ...
    readDiagnosticArray(baselineTextureDiagnostics.browProtection, ...
    imageSize, 'browProtection'), ...
    readDiagnosticArray(baselineTextureDiagnostics.lipProtection, ...
    imageSize, 'lipProtection'), ...
    readDiagnosticArray(baselineTextureDiagnostics.noseProtection, ...
    imageSize, 'noseProtection')), [], 3);
candidateTextureProtectionMask = min(max(max(fixedTextureComponents, ...
    candidateEyeDetailProtection), 0), 1);
validateMask(candidateTextureProtectionMask, imageSize, ...
    'candidateTextureProtectionMask');

candidateBeautyMasks = baselineBeautyMasks;
candidateBeautyMasks.textureProtectionMask = candidateTextureProtectionMask;
candidateBeautyMasks.protectionMask = max(cat(3, ...
    candidateTextureProtectionMask, ...
    double(baselineBeautyMasks.structureProtectionMask), ...
    double(baselineBeautyMasks.hardProtectionMask)), [], 3);
validateCandidateMaskIsolation(baselineBeautyMasks, candidateBeautyMasks, ...
    candidateTextureProtectionMask, candidateEyeDetailProtection, ...
    imageSize, options.formulaTolerance);

frequency = continuityDiagnostics.frequency;
blemishMap = continuityDiagnostics.blemishMap;
params = struct('smoothingStrength', options.smoothingStrength, ...
    'whiteningStrength', options.whiteningStrength);

% 只重跑当前既有 Smoothing / Repair / compose。frequency、blemishMap、
% Base、tone、whitening 和其它 Mask 不从 08.6 候选重新推导。
[candidateSmoothedFrequency, candidateSmoothingDiagnostics] = ...
    beauty.smoothSkinTexture(frequency, candidateBeautyMasks, ...
    params.smoothingStrength, blemishMap);
[candidateRepairedFrequency, candidateRepairDiagnostics] = ...
    beauty.repairSkinBlemishes(candidateSmoothedFrequency, ...
    candidateBeautyMasks, blemishMap, params.smoothingStrength);
processing = buildFrozenProcessing( ...
    continuityDiagnostics.baselineComposeDiagnostics);

[baselineComposed, baselineComposeDiagnostics] = ...
    beauty.composeBeautyResult(inputImage, frequency, ...
    continuityDiagnostics.repairedFrequency, baselineBeautyMasks, ...
    params.whiteningStrength, processing);
[candidate084Composed, candidate084ComposeDiagnostics] = ...
    beauty.composeBeautyResult(inputImage, frequency, ...
    continuityDiagnostics.candidateRepairedFrequency, ...
    continuityDiagnostics.candidateBeautyMasks, params.whiteningStrength, ...
    processing);
[candidate086Output, candidate086ComposeDiagnostics] = ...
    beauty.composeBeautyResult(inputImage, frequency, ...
    candidateRepairedFrequency, candidateBeautyMasks, ...
    params.whiteningStrength, processing);

baselineOutput = continuityDiagnostics.baselineComposed;
candidate084Output = continuityDiagnostics.candidateOutput;
baselineComposeMaxRgbDifference = max(abs(double(baselineComposed(:)) - ...
    double(baselineOutput(:))));
candidate084ComposeMaxRgbDifference = max(abs( ...
    double(candidate084Composed(:)) - double(candidate084Output(:))));
if baselineComposeMaxRgbDifference > options.reconstructionTolerance || ...
        candidate084ComposeMaxRgbDifference > options.reconstructionTolerance
    error('diagnoseLashSupportGeometryCandidate:FrozenComposeMismatch', ...
        'Baseline/08.4 冻结 compose 重建不一致：%.17g / %.17g。', ...
        baselineComposeMaxRgbDifference, candidate084ComposeMaxRgbDifference);
end

baselineSmoothedFrequency = continuityDiagnostics.smoothedFrequency;
candidate084SmoothedFrequency = continuityDiagnostics.candidateSmoothedFrequency;
baselineRepairedFrequency = continuityDiagnostics.repairedFrequency;
candidate084RepairedFrequency = continuityDiagnostics.candidateRepairedFrequency;
baselineRepairFineDelta = double(baselineRepairedFrequency.fine) - ...
    double(baselineSmoothedFrequency.fine);
candidate084RepairFineDelta = double(candidate084RepairedFrequency.fine) - ...
    double(candidate084SmoothedFrequency.fine);
candidate086RepairFineDelta = double(candidateRepairedFrequency.fine) - ...
    double(candidateSmoothedFrequency.fine);
baselineRepairMidDelta = double(baselineRepairedFrequency.mid) - ...
    double(baselineSmoothedFrequency.mid);
candidate084RepairMidDelta = double(candidate084RepairedFrequency.mid) - ...
    double(candidate084SmoothedFrequency.mid);
candidate086RepairMidDelta = double(candidateRepairedFrequency.mid) - ...
    double(candidateSmoothedFrequency.mid);

originalLuminance = rgb2ycbcr(im2double(inputImage));
originalLuminance = originalLuminance(:, :, 1);
validateArray(originalLuminance, imageSize, 'originalLuminance');

baselineRgbDistance = max(abs(double(baselineOutput) - ...
    double(inputImage)), [], 3);
candidate084RgbDistance = max(abs(double(candidate084Output) - ...
    double(inputImage)), [], 3);
candidate086RgbDistance = max(abs(double(candidate086Output) - ...
    double(inputImage)), [], 3);
baselineLuminanceDistance = abs(double( ...
    baselineComposeDiagnostics.outputLuminance) - double(originalLuminance));
candidate084LuminanceDistance = abs(double( ...
    candidate084ComposeDiagnostics.outputLuminance) - double(originalLuminance));
candidate086LuminanceDistance = abs(double( ...
    candidate086ComposeDiagnostics.outputLuminance) - double(originalLuminance));

baselineSupport = baselineLashProtection > 0;
candidate084LashProtection = readDiagnosticArray( ...
    continuityDiagnostics.candidateLashProtection, imageSize, ...
    'candidate084LashProtection');
candidate084Support = candidate084LashProtection > 0;
candidate086Support = candidateLashProtection > 0;
metrics = makeMetrics(manualLashMask, baselineSupport, ...
    candidate084Support, candidate086Support, baselineLashProtection, ...
    candidate084LashProtection, candidateLashProtection, ...
    baselineRepairFineDelta, candidate084RepairFineDelta, ...
    candidate086RepairFineDelta, baselineRepairMidDelta, ...
    candidate084RepairMidDelta, candidate086RepairMidDelta, ...
    baselineRgbDistance, candidate084RgbDistance, candidate086RgbDistance, ...
    baselineLuminanceDistance, candidate084LuminanceDistance, ...
    candidate086LuminanceDistance, options.nonzeroTolerance);
metrics.numericGeometryAssessment = assessNumericGeometry(metrics, ...
    options.formulaTolerance);
metrics.repairAssessment = assessRepair(metrics, options.formulaTolerance);

paths = writeArtifacts(outputFolder, inputImage, manualLashMask, ...
    baselineSupport, candidate084Support, candidate086Support, ...
    baselineRepairFineDelta, candidate084RepairFineDelta, ...
    candidate086RepairFineDelta, baselineRepairMidDelta, ...
    candidate084RepairMidDelta, candidate086RepairMidDelta, ...
    baselineOutput, candidate084Output, candidate086Output, options.lashRoi);
paths.csv = fullfile(outputFolder, 'lash_support_geometry_metrics.csv');
writeMetricsCsv(paths.csv, metrics, metrics.numericGeometryAssessment, ...
    metrics.repairAssessment, options);
paths.data = fullfile(outputFolder, 'lash_support_geometry_diagnostic.mat');

hardProtectionMaskChangedPixels = nnz( ...
    double(candidateBeautyMasks.hardProtectionMask) ~= ...
    double(baselineBeautyMasks.hardProtectionMask));
hardCoreChangedPixels = nnz( ...
    logical(baselineTextureDiagnostics.lashCore) ~= ...
    logical(baselineTextureDiagnostics.lashCore));

summary = struct( ...
    'completed', true, ...
    'issue', '08.6', ...
    'case', 'requiresVisualReview', ...
    'caseAssessment', metrics.numericGeometryAssessment, ...
    'repairAssessment', metrics.repairAssessment, ...
    'contract', continuitySummary.contract, ...
    'imagePath', imagePath, ...
    'inputSize', size(inputImage), ...
    'faceBox', double(options.faceBox), ...
    'browEye', double(options.browEyeRoi), ...
    'lashRoi', double(options.lashRoi), ...
    'parameters', params, ...
    'baselinePath', options.baselinePath, ...
    'manualLashMaskId', annotation.annotationId, ...
    'manualLashMaskIndependent', annotation.diagnosticsIndependent, ...
    'manualLashMaskFixed', annotation.fixedAfterAnnotation, ...
    'manualLashMaskPixels', nnz(manualLashMask), ...
    'runtimeCacheReused', continuitySummary.runtimeCacheReused, ...
    'sameMaskRun', true, ...
    'baseToneWhiteningFrozen', true, ...
    'onlyLashSupportGeometryChanged', true, ...
    'manualTruthUsedForGeneration', false, ...
    'candidateSeedSource', 'current detector candidate seed', ...
    'candidateEvidenceSource', ...
        'current dark/edge/line evidence intersected with eyeNeighborhood', ...
    'candidateConnection', ...
        '8-connected reconstruction through existing evidence', ...
    'candidateSoftWeightSource', ...
        'current featherSoftMask with existing faceScale softRadius and peak', ...
    'faceScale', faceScale, ...
    'softRadius', evidence.softRadius, ...
    'softPeak', evidence.softPeak, ...
    'evidenceReconstructionMaxError', evidence.reconstructionMaxError, ...
    'baselineComposeMaxRgbDifference', baselineComposeMaxRgbDifference, ...
    'candidate084ComposeMaxRgbDifference', ...
        candidate084ComposeMaxRgbDifference, ...
    'hardProtectionMaskChangedPixels', hardProtectionMaskChangedPixels, ...
    'hardCoreChangedPixels', hardCoreChangedPixels, ...
    'metrics', metrics, ...
    'paths', paths);

diagnosticData = struct( ...
    'summary', summary, ...
    'inputImage', inputImage, ...
    'annotation', annotation, ...
    'manualLashMask', manualLashMask, ...
    'frequency', frequency, ...
    'blemishMap', blemishMap, ...
    'baselineBeautyMasks', baselineBeautyMasks, ...
    'candidate084BeautyMasks', continuityDiagnostics.candidateBeautyMasks, ...
    'candidate086BeautyMasks', candidateBeautyMasks, ...
    'baselineTextureDiagnostics', baselineTextureDiagnostics, ...
    'candidate084TextureDiagnostics', ...
        continuityDiagnostics.candidateTextureDiagnostics, ...
    'candidate086TextureDiagnostics', makeCandidateTextureDiagnostics( ...
        baselineTextureDiagnostics, candidateEyeDetailProtection, ...
        candidateLashProtection), ...
    'evidence', evidence, ...
    'baselineLashProtection', baselineLashProtection, ...
    'candidate084LashProtection', candidate084LashProtection, ...
    'candidate086LashProtection', candidateLashProtection, ...
    'baselineSupport', baselineSupport, ...
    'candidate084Support', candidate084Support, ...
    'candidate086Support', candidate086Support, ...
    'candidateGeometrySeed', candidateGeometrySeed, ...
    'candidateAllowedEvidence', evidence.allowedEvidence, ...
    'candidateSoftProtection', candidateLashProtection, ...
    'smoothedFrequency', baselineSmoothedFrequency, ...
    'candidate084SmoothedFrequency', candidate084SmoothedFrequency, ...
    'candidate086SmoothedFrequency', candidateSmoothedFrequency, ...
    'repairedFrequency', baselineRepairedFrequency, ...
    'candidate084RepairedFrequency', candidate084RepairedFrequency, ...
    'candidate086RepairedFrequency', candidateRepairedFrequency, ...
    'candidate086SmoothingDiagnostics', candidateSmoothingDiagnostics, ...
    'candidate086RepairDiagnostics', candidateRepairDiagnostics, ...
    'baselineRepairFineDelta', baselineRepairFineDelta, ...
    'candidate084RepairFineDelta', candidate084RepairFineDelta, ...
    'candidate086RepairFineDelta', candidate086RepairFineDelta, ...
    'baselineRepairMidDelta', baselineRepairMidDelta, ...
    'candidate084RepairMidDelta', candidate084RepairMidDelta, ...
    'candidate086RepairMidDelta', candidate086RepairMidDelta, ...
    'baselineOutput', baselineOutput, ...
    'candidate084Output', candidate084Output, ...
    'candidate086Output', candidate086Output, ...
    'baselineComposeDiagnostics', baselineComposeDiagnostics, ...
    'candidate084ComposeDiagnostics', candidate084ComposeDiagnostics, ...
    'candidate086ComposeDiagnostics', candidate086ComposeDiagnostics, ...
    'candidate086FinalRgbDistance', candidate086RgbDistance, ...
    'candidate086FinalLuminanceDistance', candidate086LuminanceDistance, ...
    'metrics', metrics);
save(paths.data, 'diagnosticData', '-v7.3');
summary.paths = paths;
diagnosticData.summary = summary;
diagnostics = diagnosticData;

fprintf('Issue 08.6 睫毛 Support Geometry 产物：%s\n', outputFolder);
fprintf('Baseline / 08.4 / 08.6 support：%d / %d / %d\n', ...
    metrics.baseline.supportPixels, metrics.candidate084.supportPixels, ...
    metrics.candidate086.supportPixels);
fprintf('Recall：%.17g / %.17g / %.17g；Precision：%.17g / %.17g / %.17g\n', ...
    metrics.baseline.recall, metrics.candidate084.recall, ...
    metrics.candidate086.recall, metrics.baseline.precision, ...
    metrics.candidate084.precision, metrics.candidate086.precision);
fprintf('Repair Fine 绝对作用量：%.17g -> %.17g -> %.17g\n', ...
    metrics.baselineRepairFineAbsAction.sum, ...
    metrics.candidate084RepairFineAbsAction.sum, ...
    metrics.candidate086RepairFineAbsAction.sum);
fprintf('Repair Mid 绝对作用量：%.17g -> %.17g -> %.17g\n', ...
    metrics.baselineRepairMidAbsAction.sum, ...
    metrics.candidate084RepairMidAbsAction.sum, ...
    metrics.candidate086RepairMidAbsAction.sum);
fprintf('数值几何证据：%s；最终 Case 需要人工核对主图。\n', ...
    metrics.numericGeometryAssessment.case);
end

function options = normalizeOptions(options, projectRoot)
if nargin < 1 || isempty(options)
    options = struct();
end
if ~isstruct(options) || ~isscalar(options)
    error('diagnoseLashSupportGeometryCandidate:InvalidOptions', ...
        'options 必须是标量结构。');
end
fixedFields = { ...
    'faceBox', [95, 79, 286, 372]; ...
    'browEyeRoi', [165, 205, 150, 100]; ...
    'lashRoi', [102, 248, 177, 48]};
for index = 1:size(fixedFields, 1)
    name = fixedFields{index, 1};
    defaultValue = fixedFields{index, 2};
    if ~isfield(options, name) || isempty(options.(name))
        options.(name) = defaultValue;
    end
    if ~isequal(double(options.(name)), double(defaultValue))
        error('diagnoseLashSupportGeometryCandidate:NonFixedFixture', ...
            '%s 必须复用 Issue 08.6 固定值。', name);
    end
end
options.faceBox = double(options.faceBox);
options.browEyeRoi = double(options.browEyeRoi);
options.lashRoi = double(options.lashRoi);
if ~isfield(options, 'smoothingStrength') || isempty(options.smoothingStrength)
    options.smoothingStrength = 100;
end
if ~isfield(options, 'whiteningStrength') || isempty(options.whiteningStrength)
    options.whiteningStrength = 15;
end
if ~isValidStrength(options.smoothingStrength) || ...
        ~isValidStrength(options.whiteningStrength)
    error('diagnoseLashSupportGeometryCandidate:InvalidStrength', ...
        '强度必须是 0 到 100 的有限数值标量。');
end
if ~isfield(options, 'productionRoot') || isempty(options.productionRoot)
    options.productionRoot = projectRoot;
end
options.productionRoot = normalizeText(options.productionRoot, ...
    'productionRoot');
if ~isfield(options, 'baselinePath') || isempty(options.baselinePath)
    options.baselinePath = ...
        'C:\Users\JJiio\AppData\Local\Temp\image_beauty_issue02_probe\77_v32_probe.mat';
end
options.baselinePath = normalizeText(options.baselinePath, 'baselinePath');
if ~isfield(options, 'formulaTolerance') || isempty(options.formulaTolerance)
    options.formulaTolerance = 1e-12;
end
if ~isfield(options, 'reconstructionTolerance') || ...
        isempty(options.reconstructionTolerance)
    options.reconstructionTolerance = 1e-12;
end
if ~isfield(options, 'nonzeroTolerance') || isempty(options.nonzeroTolerance)
    options.nonzeroTolerance = 1e-12;
end
if ~isscalar(options.formulaTolerance) || ...
        ~isfinite(options.formulaTolerance) || options.formulaTolerance <= 0 || ...
        ~isscalar(options.reconstructionTolerance) || ...
        ~isfinite(options.reconstructionTolerance) || ...
        options.reconstructionTolerance <= 0 || ...
        ~isscalar(options.nonzeroTolerance) || ...
        ~isfinite(options.nonzeroTolerance) || options.nonzeroTolerance <= 0
    error('diagnoseLashSupportGeometryCandidate:InvalidTolerance', ...
        '公式、重建和非零容差必须是正的有限标量。');
end
options.formulaTolerance = double(options.formulaTolerance);
options.reconstructionTolerance = double(options.reconstructionTolerance);
options.nonzeroTolerance = double(options.nonzeroTolerance);
end

function root = resolveProductionRoot(root)
if ~isfolder(root) || ~isfolder(fullfile(root, 'src'))
    error('diagnoseLashSupportGeometryCandidate:InvalidProductionRoot', ...
        '生产算法根目录或 src 目录不存在：%s。', root);
end
end

function validateFixed77Fixture(inputImage, options)
if ~isequal(size(inputImage), [450, 512, 3]) || ...
        ~isequal(options.faceBox, [95, 79, 286, 372]) || ...
        ~isequal(options.browEyeRoi, [165, 205, 150, 100]) || ...
        ~isequal(options.lashRoi, [102, 248, 177, 48])
    error('diagnoseLashSupportGeometryCandidate:UnexpectedFixture', ...
        'Issue 08.6 必须使用 77.png 的 450x512x3 和固定坐标。');
end
end

function validateContinuityStage(continuitySummary, diagnostics, imageSize)
if ~isstruct(continuitySummary) || ~continuitySummary.completed || ...
        ~strcmp(continuitySummary.issue, '08.4') || ...
        continuitySummary.runtimeCacheReused || ...
        ~isstruct(diagnostics) || ~isequal(size(diagnostics.inputImage), ...
        [imageSize, 3])
    error('diagnoseLashSupportGeometryCandidate:InvalidContinuityStage', ...
        'Issue 08.4 阶段未按无缓存固定链完成。');
end
end

function image = readInputImage(imagePath)
if ~isfile(imagePath)
    error('diagnoseLashSupportGeometryCandidate:MissingImage', ...
        '输入图像不存在：%s。', imagePath);
end
image = imread(imagePath);
if ~isa(image, 'uint8') || ~isreal(image) || ndims(image) ~= 3 || ...
        size(image, 3) ~= 3
    error('diagnoseLashSupportGeometryCandidate:InvalidImage', ...
        '输入图像必须是 uint8 三通道 RGB 图像。');
end
end

function loaded = loadBaselineContext(path)
if ~isfile(path)
    error('diagnoseLashSupportGeometryCandidate:MissingBaseline', ...
        '固定 77 Context 基线不存在：%s。', path);
end
loaded = load(path, 'context');
if ~isfield(loaded, 'context') || ~isstruct(loaded.context) || ...
        ~isscalar(loaded.context)
    error('diagnoseLashSupportGeometryCandidate:InvalidBaseline', ...
        '固定 77 基线缺少有效 context：%s。', path);
end
end

function context = stripDerivedContext(context)
names = {'runtimeCache', 'textureProtectionMask', ...
    'structureProtectionMask', 'whiteningProtectionMask', ...
    'chromaProtectionMask', 'toneProtectionMask', 'strengthMap', ...
    'faceStrengthMap', 'nonFaceStrengthMap', 'protectionMasks'};
present = names(isfield(context, names));
if ~isempty(present)
    context = rmfield(context, present);
end
end

function faceScale = readFaceScale(frequency, faceBox)
if isfield(frequency, 'faceScale') && isnumeric(frequency.faceScale) && ...
        isscalar(frequency.faceScale) && isfinite(frequency.faceScale) && ...
        frequency.faceScale > 0
    faceScale = double(frequency.faceScale);
else
    faceScale = min(double(faceBox(3:4)));
end
end

function evidence = reconstructExistingLashEvidence(inputImage, context, ...
        faceScale)
imageSize = [size(inputImage, 1), size(inputImage, 2)];
if ~isfield(context, 'regions') || ~isfield(context, 'regionConfidence')
    error('diagnoseLashSupportGeometryCandidate:MissingSemanticEvidence', ...
        '固定 Context 缺少当前 detector 所需的 regions/regionConfidence。');
end
regions = context.regions;
confidence = context.regionConfidence;
required = {'leftEye', 'rightEye', 'leftBrow', 'rightBrow'};
if ~all(isfield(regions, required)) || ~all(isfield(confidence, required))
    error('diagnoseLashSupportGeometryCandidate:MissingSemanticEvidence', ...
        '固定 Context 缺少眼睛或眉毛既有语义 evidence。');
end
leftEyeEvidence = min(double(regions.leftEye), ...
    double(confidence.leftEye));
rightEyeEvidence = min(double(regions.rightEye), ...
    double(confidence.rightEye));
browEvidence = max(min(double(regions.leftBrow), ...
    double(confidence.leftBrow)), min(double(regions.rightBrow), ...
    double(confidence.rightBrow)));
validateArray(leftEyeEvidence, imageSize, 'leftEyeEvidence');
validateArray(rightEyeEvidence, imageSize, 'rightEyeEvidence');
validateArray(browEvidence, imageSize, 'browEvidence');

grayImage = im2double(rgb2gray(inputImage));
identityThreshold = .45;
softSupportThreshold = .20;
identityMasks = {leftEyeEvidence >= identityThreshold, ...
    rightEyeEvidence >= identityThreshold};
softSupportMasks = {leftEyeEvidence >= softSupportThreshold & ...
    leftEyeEvidence < identityThreshold, ...
    rightEyeEvidence >= softSupportThreshold & ...
    rightEyeEvidence < identityThreshold};
browCore = browEvidence >= identityThreshold;
periocularRadius = min(24, max(9, round(.040 * double(faceScale))));
softRadius = min(5, max(2, round(.008 * double(faceScale))));

allNeighborhood = false(imageSize);
allRing = false(imageSize);
allDarkCandidate = false(imageSize);
allEdgeCandidate = false(imageSize);
allLineSupport = false(imageSize);
allDetectorCandidate = false(imageSize);
allLashCore = false(imageSize);
allLashProtection = zeros(imageSize);
allLaunchMask = false(imageSize);
allNearEye = false(imageSize);
perEye = cell(1, numel(identityMasks));
for eyeIndex = 1:numel(identityMasks)
    identityCore = identityMasks{eyeIndex};
    softSupport = softSupportMasks{eyeIndex};
    launchMask = identityCore | softSupport;
    if ~any(launchMask(:))
        continue;
    end
    currentBand = imdilate(launchMask, ...
        strel('disk', periocularRadius, 0));
    currentRing = currentBand & ~launchMask;
    if any(browCore(:))
        browRadius = min(5, max(2, round(.010 * double(faceScale))));
        browExclusion = imdilate(browCore, strel('disk', browRadius, 0));
        currentRing(browExclusion) = false;
    end
    current = reconstructExistingLashLines(grayImage, launchMask, ...
        currentRing, identityCore, faceScale, softRadius, ...
        any(softSupport(:)));
    allNeighborhood = allNeighborhood | currentBand;
    allRing = allRing | currentRing;
    allDarkCandidate = allDarkCandidate | current.darkCandidate;
    allEdgeCandidate = allEdgeCandidate | current.edgeCandidate;
    allLineSupport = allLineSupport | current.lineSupport;
    allDetectorCandidate = allDetectorCandidate | current.candidate;
    allLashCore = allLashCore | current.lashCore;
    allLashProtection = max(allLashProtection, current.protection);
    allLaunchMask = allLaunchMask | launchMask;
    allNearEye = allNearEye | current.nearEye;
    perEye{eyeIndex} = current;
end

% 当前 detector 的 evidence 只在现有眼周 ring 和既有 near-eye 约束内
% 允许参与几何重构。edgeCandidate 是 darkCandidate 的既有子集，仍显式
% 保留三类 evidence 名称以便离线诊断和审计。
allowedEvidence = allRing & allNearEye & ...
    (allDarkCandidate | allEdgeCandidate | allLineSupport);
seed = allDetectorCandidate & allowedEvidence;
if any(seed(:))
    connectedEvidence = imreconstruct(seed, allowedEvidence, 8);
else
    connectedEvidence = false(imageSize);
end

evidence = struct( ...
    'faceScale', double(faceScale), ...
    'periocularRadius', periocularRadius, ...
    'softRadius', softRadius, ...
    'softPeak', .99, ...
    'leftEyeEvidence', leftEyeEvidence, ...
    'rightEyeEvidence', rightEyeEvidence, ...
    'browEvidence', browEvidence, ...
    'browCore', browCore, ...
    'eyeNeighborhood', allNeighborhood, ...
    'ring', allRing, ...
    'launchMask', allLaunchMask, ...
    'nearEye', allNearEye, ...
    'darkCandidate', allDarkCandidate, ...
    'edgeCandidate', allEdgeCandidate, ...
    'lineSupport', allLineSupport, ...
    'detectorSeed', allDetectorCandidate, ...
    'lashCore', allLashCore, ...
    'existingLashProtection', allLashProtection, ...
    'allowedEvidence', allowedEvidence, ...
    'connectedEvidence', connectedEvidence, ...
    'perEye', {perEye});
end

function result = reconstructExistingLashLines(grayImage, launchMask, ...
        ring, identityCore, faceScale, softRadius, allowSoftProtection)
% 下列尺度、百分位和逻辑逐字复用当前生产 detectLashLines。它们不是
% 08.6 候选参数；该复制用于在不修改 src 的离线票中重建内部 evidence，
% 并由 baseline lashProtection 精确一致性检查防止诊断漂移。
result = struct();
result.lashCore = false(size(launchMask));
result.protection = zeros(size(launchMask));
result.darkCandidate = false(size(launchMask));
result.edgeCandidate = false(size(launchMask));
result.lineSupport = false(size(launchMask));
result.candidate = false(size(launchMask));
result.nearEye = false(size(launchMask));
if ~any(ring(:))
    return;
end

darkSigma = min(2.4, max(.7, .004 * double(faceScale)));
lineSigma = min(1.35, max(.45, .002 * double(faceScale)));
smoothed = imgaussfilt(grayImage, darkSigma, 'Padding', 'replicate');
lineImage = imgaussfilt(grayImage, lineSigma, 'Padding', 'replicate');
[gradientX, gradientY] = gradient(lineImage);
gradientMagnitude = hypot(gradientX, gradientY);
darkResidual = smoothed - grayImage;
darkValues = sort(darkResidual(ring));
gradientValues = sort(gradientMagnitude(ring));
darkThreshold = max(.010, percentileValue(darkValues, .62));
gradientThreshold = max(.012, percentileValue(gradientValues, .65));
darkCandidate = ring & darkResidual >= darkThreshold;
edgeCandidate = darkCandidate & gradientMagnitude >= gradientThreshold;
if ~any(darkCandidate(:))
    return;
end
lineLength = min(6, max(3, round(.007 * double(faceScale))));
gapLength = min(5, max(2, round(.006 * double(faceScale))));
lineSupport = false(size(darkCandidate));
for angle = 0:15:165
    closingElement = strel('line', gapLength, angle);
    openingElement = strel('line', lineLength, angle);
    closed = imclose(darkCandidate, closingElement);
    lineSupport = lineSupport | imdilate( ...
        imopen(closed, openingElement), strel('disk', 1, 0));
end
candidate = darkCandidate & (edgeCandidate | lineSupport);
lashDistance = min(9, max(4, round(.014 * double(faceScale))));
nearEye = bwdist(launchMask) <= lashDistance;
candidate = candidate & nearEye;
hardDarkThreshold = max(.045, percentileValue(darkValues, .80));
hardGradientThreshold = max(.018, percentileValue(gradientValues, .75));
if any(identityCore(:))
    hardNearEye = bwdist(identityCore) <= lashDistance;
    result.lashCore = candidate & ~identityCore & hardNearEye & ...
        darkResidual >= hardDarkThreshold & ...
        (gradientMagnitude >= hardGradientThreshold | lineSupport);
end
if allowSoftProtection
    protectionSeed = candidate;
else
    protectionSeed = result.lashCore;
end
if any(protectionSeed(:))
    result.protection = featherSoftMask(protectionSeed, softRadius, .99);
    result.protection(protectionSeed) = .99;
end
result.darkCandidate = darkCandidate;
result.edgeCandidate = edgeCandidate;
result.lineSupport = lineSupport;
result.candidate = candidate;
result.nearEye = nearEye;
end

function validateEvidenceReconstruction(evidence, textureDiagnostics, ...
        baselineLashProtection, imageSize, tolerance)
expectedNeighborhood = logical(textureDiagnostics.eyeNeighborhood);
expectedCore = logical(textureDiagnostics.lashCore);
if ~isequal(evidence.eyeNeighborhood, expectedNeighborhood)
    error('diagnoseLashSupportGeometryCandidate:EvidenceNeighborhoodMismatch', ...
        '重建的 eyeNeighborhood 与当前生产 evidence 不一致。');
end
if ~isequal(evidence.lashCore, expectedCore)
    error('diagnoseLashSupportGeometryCandidate:EvidenceCoreMismatch', ...
        '重建的 lashCore 与当前生产 evidence 不一致。');
end
maxError = max(abs(evidence.existingLashProtection(:) - ...
    baselineLashProtection(:)));
if maxError > tolerance
    error('diagnoseLashSupportGeometryCandidate:EvidenceProtectionMismatch', ...
        '重建的现有 lashProtection 最大误差 %.17g。', maxError);
end
evidence.reconstructionMaxError = maxError;
if any(evidence.connectedEvidence(:) & ~evidence.allowedEvidence(:))
    error('diagnoseLashSupportGeometryCandidate:InvalidConnectedEvidence', ...
        'connectedEvidence 超出 allowedEvidence。');
end
if any(evidence.connectedEvidence(:) & ~evidence.eyeNeighborhood(:))
    error('diagnoseLashSupportGeometryCandidate:InvalidNeighborhood', ...
        'connectedEvidence 超出 eyeNeighborhood。');
end
validateArray(evidence.existingLashProtection, imageSize, ...
    'existingLashProtection');
end

function validateTextureDiagnostics(textureDiagnostics, imageSize)
required = {'occluderProtection', 'browProtection', 'lipProtection', ...
    'noseProtection', 'eyeDetailProtection', 'lashProtection', ...
    'periocularProtection', 'doubleEyelidProtection', 'eyeNeighborhood', ...
    'lashCore'};
if ~isstruct(textureDiagnostics) || ~isscalar(textureDiagnostics) || ...
        ~all(isfield(textureDiagnostics, required))
    error('diagnoseLashSupportGeometryCandidate:MissingTextureDiagnostic', ...
        '纹理诊断缺少 Issue 08.6 所需字段。');
end
for index = 1:numel(required)
    name = required{index};
    value = textureDiagnostics.(name);
    if strcmp(name, 'lashCore')
        if ~islogical(value) || ~isequal(size(value), imageSize)
            error('diagnoseLashSupportGeometryCandidate:InvalidTextureDiagnostic', ...
                '%s 尺寸或类型无效。', name);
        end
    else
        validateMask(value, imageSize, name);
    end
end
end

function validateCandidateMaskIsolation(baselineMasks, candidateMasks, ...
        candidateTexture, candidateEye, imageSize, tolerance)
required = {'structureProtectionMask', 'hardProtectionMask'};
for index = 1:numel(required)
    name = required{index};
    if max(abs(double(baselineMasks.(name)(:)) - ...
            double(candidateMasks.(name)(:)))) > tolerance
        error('diagnoseLashSupportGeometryCandidate:SingleFactorViolation', ...
            '候选意外修改了 %s。', name);
    end
end
unchangedNames = {'whiteningProtectionMask', 'chromaProtectionMask', ...
    'toneProtectionMask', 'strengthMap', 'faceStrengthMap', ...
    'nonFaceStrengthMap', 'skinMask', 'faceSkinMask', ...
    'nonFaceSkinMask', 'noseMask'};
for index = 1:numel(unchangedNames)
    name = unchangedNames{index};
    if isfield(baselineMasks, name) && isfield(candidateMasks, name) && ...
            max(abs(double(baselineMasks.(name)(:)) - ...
            double(candidateMasks.(name)(:)))) > tolerance
        error('diagnoseLashSupportGeometryCandidate:SingleFactorViolation', ...
            '候选意外修改了 %s。', name);
    end
end
if any(candidateTexture(:) < 0) || any(candidateTexture(:) > 1) || ...
        any(candidateEye(:) < 0) || any(candidateEye(:) > 1)
    error('diagnoseLashSupportGeometryCandidate:InvalidCandidateProtection', ...
        '候选 texture/eye protection 必须位于 [0,1]。');
end
if ~isequal(size(candidateMasks.textureProtectionMask), imageSize)
    error('diagnoseLashSupportGeometryCandidate:InvalidCandidateMask', ...
        'Candidate textureProtectionMask 尺寸无效。');
end
end

function processing = buildFrozenProcessing(composeDiagnostics)
required = {'baseSupport', 'baseDelta', 'whiteningSupport', ...
    'whiteningDelta', 'toneSupport', 'toneTargetCb', 'toneTargetCr'};
if ~isstruct(composeDiagnostics) || ~all(isfield(composeDiagnostics, required))
    error('diagnoseLashSupportGeometryCandidate:MissingFrozenProcessing', ...
        '无法从同次 compose 诊断重建冻结的 Base/tone/whitening。');
end
processing = struct( ...
    'baseLuminance', struct('supportMap', composeDiagnostics.baseSupport, ...
    'baseDelta', composeDiagnostics.baseDelta), ...
    'skinTone', struct('toneSupport', composeDiagnostics.toneSupport, ...
    'outputCb', composeDiagnostics.toneTargetCb, ...
    'outputCr', composeDiagnostics.toneTargetCr), ...
    'whitening', struct('supportMap', composeDiagnostics.whiteningSupport, ...
    'delta', composeDiagnostics.whiteningDelta));
end

function metrics = makeMetrics(manualMask, baselineSupport, candidate084Support, ...
        candidate086Support, baselineLash, candidate084Lash, candidate086Lash, ...
        baselineFine, candidate084Fine, candidate086Fine, baselineMid, ...
        candidate084Mid, candidate086Mid, baselineRgb, candidate084Rgb, ...
        candidate086Rgb, baselineLuma, candidate084Luma, candidate086Luma, ...
        tolerance)
metrics = struct( ...
    'manualLashPixels', nnz(manualMask), ...
    'baseline', makeGeometryStats(baselineSupport, manualMask, ...
        baselineLash, tolerance), ...
    'candidate084', makeGeometryStats(candidate084Support, manualMask, ...
        candidate084Lash, tolerance), ...
    'candidate086', makeGeometryStats(candidate086Support, manualMask, ...
        candidate086Lash, tolerance), ...
    'baselineRepairFineAbsAction', makeStats(abs(baselineFine(manualMask)), tolerance), ...
    'candidate084RepairFineAbsAction', makeStats(abs(candidate084Fine(manualMask)), tolerance), ...
    'candidate086RepairFineAbsAction', makeStats(abs(candidate086Fine(manualMask)), tolerance), ...
    'baselineRepairMidAbsAction', makeStats(abs(baselineMid(manualMask)), tolerance), ...
    'candidate084RepairMidAbsAction', makeStats(abs(candidate084Mid(manualMask)), tolerance), ...
    'candidate086RepairMidAbsAction', makeStats(abs(candidate086Mid(manualMask)), tolerance), ...
    'baselineFinalRgbDistanceToOriginal', makeStats(baselineRgb(manualMask), tolerance), ...
    'candidate084FinalRgbDistanceToOriginal', makeStats(candidate084Rgb(manualMask), tolerance), ...
    'candidate086FinalRgbDistanceToOriginal', makeStats(candidate086Rgb(manualMask), tolerance), ...
    'baselineFinalLuminanceDistanceToOriginal', makeStats(baselineLuma(manualMask), tolerance), ...
    'candidate084FinalLuminanceDistanceToOriginal', makeStats(candidate084Luma(manualMask), tolerance), ...
    'candidate086FinalLuminanceDistanceToOriginal', makeStats(candidate086Luma(manualMask), tolerance));
end

function stats = makeGeometryStats(support, manualMask, protection, tolerance)
truePositive = support & manualMask;
falsePositive = support & ~manualMask;
falseNegative = ~support & manualMask;
fpStats = makeComponentStats(falsePositive);
stats = struct( ...
    'supportPixels', nnz(support), ...
    'truePositivePixels', nnz(truePositive), ...
    'falsePositivePixels', nnz(falsePositive), ...
    'falseNegativePixels', nnz(falseNegative), ...
    'recall', safeRatio(nnz(truePositive), nnz(manualMask)), ...
    'precision', safeRatio(nnz(truePositive), nnz(support)), ...
    'manualProtection', makeStats(protection(manualMask), tolerance), ...
    'falsePositiveComponents', fpStats);
end

function stats = makeComponentStats(mask)
components = bwconncomp(mask, 8);
if components.NumObjects == 0
    sizes = zeros(0, 1);
    largest = 0;
    longestSpan = 0;
else
    sizes = cellfun(@numel, components.PixelIdxList).';
    largest = max(sizes);
    [rows, columns] = find(mask);
    longestSpan = max(max(rows) - min(rows) + 1, ...
        max(columns) - min(columns) + 1);
end
stats = struct( ...
    'componentCount', components.NumObjects, ...
    'componentSizes', sizes, ...
    'largestComponentPixels', largest, ...
    'longestBoundingSpan', longestSpan);
end

function assessment = assessNumericGeometry(metrics, tolerance)
p84 = metrics.candidate084.precision;
p86 = metrics.candidate086.precision;
r84 = metrics.candidate084.recall;
r86 = metrics.candidate086.recall;
precisionImproved = p86 > p84 + tolerance;
recallNotLower = r86 >= r84 - tolerance;
fpPixelsReduced = metrics.candidate086.falsePositivePixels < ...
    metrics.candidate084.falsePositivePixels;
fpLargestReduced = metrics.candidate086.falsePositiveComponents ...
    .largestComponentPixels < ...
    metrics.candidate084.falsePositiveComponents.largestComponentPixels;
if precisionImproved && recallNotLower && (fpPixelsReduced || fpLargestReduced)
    caseName = 'numericGeometrySupportsCandidate';
else
    caseName = 'numericGeometryDoesNotSupportCandidate';
end
assessment = struct( ...
    'case', caseName, ...
    'requiresVisualReview', true, ...
    'precisionImproved', precisionImproved, ...
    'recallNotLower', recallNotLower, ...
    'falsePositivePixelsReduced', fpPixelsReduced, ...
    'falsePositiveLargestComponentReduced', fpLargestReduced, ...
    'basis', ['Precision/Recall 和 FP 连续分量仅作离线证据；', ...
    '最终 Case 必须结合同尺度主图人工确认。']);
end

function assessment = assessRepair(metrics, tolerance)
fine084 = metrics.candidate084RepairFineAbsAction.sum;
fine086 = metrics.candidate086RepairFineAbsAction.sum;
mid084 = metrics.candidate084RepairMidAbsAction.sum;
mid086 = metrics.candidate086RepairMidAbsAction.sum;
assessment = struct( ...
    'fineNotWorseThan084', fine086 <= fine084 + tolerance, ...
    'midNotWorseThan084', mid086 <= mid084 + tolerance, ...
    'fineReductionFrom084', fine084 - fine086, ...
    'midReductionFrom084', mid084 - mid086, ...
    'requiresVisualReview', true);
end

function value = safeRatio(numerator, denominator)
if denominator == 0
    value = NaN;
else
    value = numerator / denominator;
end
end

function stats = makeStats(values, tolerance)
values = double(values(:));
if isempty(values)
    stats = struct('values', values, 'count', 0, 'sum', 0, ...
        'mean', NaN, 'min', NaN, 'max', NaN, ...
        'nonzeroPixels', 0, 'nonzeroFraction', NaN);
    return;
end
stats = struct( ...
    'values', values, ...
    'count', numel(values), ...
    'sum', sum(values), ...
    'mean', mean(values), ...
    'min', min(values), ...
    'max', max(values), ...
    'nonzeroPixels', nnz(abs(values) > tolerance), ...
    'nonzeroFraction', nnz(abs(values) > tolerance) / numel(values));
end

function diagnostics = makeCandidateTextureDiagnostics(base, ...
        candidateEyeDetail, candidateLash)
diagnostics = base;
diagnostics.eyeDetailProtection = candidateEyeDetail;
diagnostics.lashProtection = candidateLash;
end

function paths = writeArtifacts(outputFolder, inputImage, manualMask, ...
        baselineSupport, candidate084Support, candidate086Support, ...
        baselineFine, candidate084Fine, candidate086Fine, baselineMid, ...
        candidate084Mid, candidate086Mid, baselineOutput, candidate084Output, ...
        candidate086Output, lashRoi)
originalCrop = cropImage(inputImage, lashRoi);
manualCrop = cropImage(manualMask, lashRoi);
paths = struct('outputFolder', outputFolder);
paths.originalLash = fullfile(outputFolder, 'original_lash.png');
writeFinalLashFigure(originalCrop, originalCrop, manualCrop, ...
    'A 原图 Original lash', paths.originalLash);
paths.baselineSupport = fullfile(outputFolder, 'baseline_support.png');
writeSupportFigure(originalCrop, cropImage(baselineSupport, lashRoi), ...
    manualCrop, 'Baseline support', paths.baselineSupport);
paths.candidate084Support = fullfile(outputFolder, ...
    'candidate_08_4_support.png');
writeSupportFigure(originalCrop, cropImage(candidate084Support, lashRoi), ...
    manualCrop, '08.4 Candidate support', paths.candidate084Support);
paths.candidate086Support = fullfile(outputFolder, ...
    'candidate_08_6_support.png');
writeSupportFigure(originalCrop, cropImage(candidate086Support, lashRoi), ...
    manualCrop, '08.6 Geometry Candidate support', paths.candidate086Support);
paths.manualVs084Support = fullfile(outputFolder, ...
    'manual_vs_08_4_support.png');
writeManualSupportComparison(originalCrop, manualCrop, ...
    cropImage(candidate084Support, lashRoi), '08.4 Candidate', ...
    paths.manualVs084Support);
paths.manualVs086Support = fullfile(outputFolder, ...
    'manual_vs_08_6_support.png');
writeManualSupportComparison(originalCrop, manualCrop, ...
    cropImage(candidate086Support, lashRoi), '08.6 Geometry Candidate', ...
    paths.manualVs086Support);
paths.falsePositive084 = fullfile(outputFolder, 'false_positive_08_4.png');
writeErrorFigure(originalCrop, cropImage(candidate084Support & ~manualMask, ...
    lashRoi), manualCrop, '08.4 false positive = support & ~manual', ...
    paths.falsePositive084);
paths.falsePositive086 = fullfile(outputFolder, 'false_positive_08_6.png');
writeErrorFigure(originalCrop, cropImage(candidate086Support & ~manualMask, ...
    lashRoi), manualCrop, '08.6 false positive = support & ~manual', ...
    paths.falsePositive086);
paths.falseNegative084 = fullfile(outputFolder, 'false_negative_08_4.png');
writeErrorFigure(originalCrop, cropImage(manualMask & ~candidate084Support, ...
    lashRoi), manualCrop, '08.4 false negative = manual & ~support', ...
    paths.falseNegative084);
paths.falseNegative086 = fullfile(outputFolder, 'false_negative_08_6.png');
writeErrorFigure(originalCrop, cropImage(manualMask & ~candidate086Support, ...
    lashRoi), manualCrop, '08.6 false negative = manual & ~support', ...
    paths.falseNegative086);
paths.baselineRepairFine = fullfile(outputFolder, ...
    'baseline_repair_fine_delta.png');
writeDeltaFigure(originalCrop, manualCrop, cropImage(baselineFine, lashRoi), ...
    'Baseline Repair Fine absolute delta', paths.baselineRepairFine);
paths.candidate084RepairFine = fullfile(outputFolder, ...
    'candidate_08_4_repair_fine_delta.png');
writeDeltaFigure(originalCrop, manualCrop, cropImage(candidate084Fine, lashRoi), ...
    '08.4 Candidate Repair Fine absolute delta', paths.candidate084RepairFine);
paths.candidate086RepairFine = fullfile(outputFolder, ...
    'candidate_08_6_repair_fine_delta.png');
writeDeltaFigure(originalCrop, manualCrop, cropImage(candidate086Fine, lashRoi), ...
    '08.6 Geometry Candidate Repair Fine absolute delta', ...
    paths.candidate086RepairFine);
paths.baselineRepairMid = fullfile(outputFolder, ...
    'baseline_repair_mid_delta.png');
writeDeltaFigure(originalCrop, manualCrop, cropImage(baselineMid, lashRoi), ...
    'Baseline Repair Mid absolute delta', paths.baselineRepairMid);
paths.candidate084RepairMid = fullfile(outputFolder, ...
    'candidate_08_4_repair_mid_delta.png');
writeDeltaFigure(originalCrop, manualCrop, cropImage(candidate084Mid, lashRoi), ...
    '08.4 Candidate Repair Mid absolute delta', paths.candidate084RepairMid);
paths.candidate086RepairMid = fullfile(outputFolder, ...
    'candidate_08_6_repair_mid_delta.png');
writeDeltaFigure(originalCrop, manualCrop, cropImage(candidate086Mid, lashRoi), ...
    '08.6 Geometry Candidate Repair Mid absolute delta', ...
    paths.candidate086RepairMid);
paths.baselineFinalLash = fullfile(outputFolder, ...
    'baseline_final_lash.png');
writeFinalLashFigure(originalCrop, cropImage(baselineOutput, lashRoi), ...
    manualCrop, 'B Baseline final lash', paths.baselineFinalLash);
paths.candidate084FinalLash = fullfile(outputFolder, ...
    'candidate_08_4_final_lash.png');
writeFinalLashFigure(originalCrop, cropImage(candidate084Output, lashRoi), ...
    manualCrop, 'C 08.4 Candidate final lash', paths.candidate084FinalLash);
paths.candidate086FinalLash = fullfile(outputFolder, ...
    'candidate_08_6_final_lash.png');
writeFinalLashFigure(originalCrop, cropImage(candidate086Output, lashRoi), ...
    manualCrop, 'D 08.6 Geometry Candidate final lash', ...
    paths.candidate086FinalLash);
paths.supportComparison = fullfile(outputFolder, ...
    'support_geometry_comparison.png');
writeSupportComparison(originalCrop, manualCrop, ...
    cropImage(baselineSupport, lashRoi), cropImage(candidate084Support, lashRoi), ...
    cropImage(candidate086Support, lashRoi), paths.supportComparison);
paths.finalComparison = fullfile(outputFolder, ...
    'final_geometry_comparison.png');
writeFinalComparison(originalCrop, cropImage(baselineOutput, lashRoi), ...
    cropImage(candidate084Output, lashRoi), cropImage(candidate086Output, ...
    lashRoi), manualCrop, paths.finalComparison);
end

function writeSupportFigure(originalCrop, supportCrop, manualCrop, label, path)
figureHandle = figure('Visible', 'off', 'Color', 'white', ...
    'Position', [100, 100, 1500, 560]);
tiledlayout(1, 2, 'Padding', 'compact', 'TileSpacing', 'compact');
nexttile;
imshow(originalCrop);
hold on;
drawContourIfPresent(manualCrop, 'r', 1.8);
hold off;
title('原图 + manualLashMask');
nexttile;
imagesc(double(supportCrop));
axis image off;
caxis([0, 1]);
colorbar;
hold on;
drawContourIfPresent(manualCrop, 'r', 1.5);
hold off;
title(label, 'Interpreter', 'none');
exportgraphics(figureHandle, path, 'Resolution', 170);
close(figureHandle);
end

function writeManualSupportComparison(originalCrop, manualCrop, supportCrop, ...
        label, path)
figureHandle = figure('Visible', 'off', 'Color', 'white', ...
    'Position', [80, 80, 2100, 560]);
tiledlayout(1, 3, 'Padding', 'compact', 'TileSpacing', 'compact');
nexttile;
imshow(originalCrop);
hold on;
drawContourIfPresent(manualCrop, 'r', 1.8);
hold off;
title('原图 + 红色 manualLashMask');
nexttile;
imagesc(double(supportCrop));
axis image off;
caxis([0, 1]);
colorbar;
hold on;
drawContourIfPresent(manualCrop, 'r', 1.5);
hold off;
title([label ' support'], 'Interpreter', 'none');
nexttile;
overlap = double(supportCrop) + 2 * double(manualCrop);
imagesc(overlap);
axis image off;
caxis([0, 3]);
colorbar;
title('0=背景，1=仅support，2=仅manual，3=交集');
exportgraphics(figureHandle, path, 'Resolution', 170);
close(figureHandle);
end

function writeErrorFigure(originalCrop, errorCrop, manualCrop, label, path)
figureHandle = figure('Visible', 'off', 'Color', 'white', ...
    'Position', [100, 100, 1500, 560]);
tiledlayout(1, 2, 'Padding', 'compact', 'TileSpacing', 'compact');
nexttile;
imshow(originalCrop);
hold on;
drawContourIfPresent(manualCrop, 'r', 1.8);
drawContourIfPresent(errorCrop, 'm', 1.6);
hold off;
title('原图：红=manual，洋红=错误区域');
nexttile;
imagesc(double(errorCrop));
axis image off;
caxis([0, 1]);
colorbar;
hold on;
drawContourIfPresent(manualCrop, 'r', 1.5);
hold off;
title(label, 'Interpreter', 'none');
exportgraphics(figureHandle, path, 'Resolution', 170);
close(figureHandle);
end

function writeDeltaFigure(originalCrop, manualCrop, deltaCrop, label, path)
figureHandle = figure('Visible', 'off', 'Color', 'white', ...
    'Position', [100, 100, 1500, 560]);
tiledlayout(1, 2, 'Padding', 'compact', 'TileSpacing', 'compact');
nexttile;
imshow(originalCrop);
hold on;
drawContourIfPresent(manualCrop, 'r', 1.8);
hold off;
title('原图 + manualLashMask');
nexttile;
imagesc(abs(double(deltaCrop)));
axis image off;
deltaLimit = max(abs(double(deltaCrop(:))));
if isempty(deltaLimit) || deltaLimit <= 0 || ~isfinite(deltaLimit)
    deltaLimit = 1;
end
caxis([0, deltaLimit]);
colorbar;
hold on;
drawContourIfPresent(manualCrop, 'r', 1.5);
hold off;
title(label, 'Interpreter', 'none');
exportgraphics(figureHandle, path, 'Resolution', 170);
close(figureHandle);
end

function writeFinalLashFigure(originalCrop, finalCrop, manualCrop, label, path)
figureHandle = figure('Visible', 'off', 'Color', 'white', ...
    'Position', [100, 100, 1500, 560]);
tiledlayout(1, 2, 'Padding', 'compact', 'TileSpacing', 'compact');
nexttile;
imshow(originalCrop);
hold on;
drawContourIfPresent(manualCrop, 'r', 1.8);
hold off;
title('原图 + manualLashMask');
nexttile;
imshow(finalCrop);
hold on;
drawContourIfPresent(manualCrop, 'r', 1.8);
hold off;
title(label, 'Interpreter', 'none');
exportgraphics(figureHandle, path, 'Resolution', 170);
close(figureHandle);
end

function writeSupportComparison(originalCrop, manualCrop, baselineCrop, ...
        candidate084Crop, candidate086Crop, path)
figureHandle = figure('Visible', 'off', 'Color', 'white', ...
    'Position', [80, 80, 2500, 560]);
tiledlayout(1, 4, 'Padding', 'compact', 'TileSpacing', 'compact');
items = {originalCrop, baselineCrop, candidate084Crop, candidate086Crop};
labels = {'A 原图', 'B Baseline support', ...
    'C 08.4 Candidate support', 'D 08.6 Geometry Candidate support'};
for index = 1:numel(items)
    nexttile;
    imagesc(double(items{index}));
    axis image off;
    if index == 1
        imshow(items{index});
    else
        caxis([0, 1]);
        colorbar;
    end
    hold on;
    drawContourIfPresent(manualCrop, 'r', 1.5);
    hold off;
    title(labels{index}, 'Interpreter', 'none');
end
exportgraphics(figureHandle, path, 'Resolution', 170);
close(figureHandle);
end

function writeFinalComparison(originalCrop, baselineCrop, candidate084Crop, ...
        candidate086Crop, manualCrop, path)
figureHandle = figure('Visible', 'off', 'Color', 'white', ...
    'Position', [80, 80, 2500, 560]);
tiledlayout(1, 4, 'Padding', 'compact', 'TileSpacing', 'compact');
items = {originalCrop, baselineCrop, candidate084Crop, candidate086Crop};
labels = {'A 原图', 'B Baseline', 'C 08.4 Candidate', ...
    'D 08.6 Geometry Candidate'};
for index = 1:numel(items)
    nexttile;
    imshow(items{index});
    hold on;
    drawContourIfPresent(manualCrop, 'r', 1.5);
    hold off;
    title(labels{index}, 'Interpreter', 'none');
end
exportgraphics(figureHandle, path, 'Resolution', 170);
close(figureHandle);
end

function writeMetricsCsv(path, metrics, geometryAssessment, ...
        repairAssessment, options)
row = struct( ...
    'issue', '08.6', ...
    'caseName', 'requiresVisualReview', ...
    'numericGeometryAssessment', geometryAssessment.case, ...
    'manualLashPixels', metrics.manualLashPixels, ...
    'baselineSupportPixels', metrics.baseline.supportPixels, ...
    'candidate084SupportPixels', metrics.candidate084.supportPixels, ...
    'candidate086SupportPixels', metrics.candidate086.supportPixels, ...
    'baselineTruePositivePixels', metrics.baseline.truePositivePixels, ...
    'candidate084TruePositivePixels', metrics.candidate084.truePositivePixels, ...
    'candidate086TruePositivePixels', metrics.candidate086.truePositivePixels, ...
    'baselineFalsePositivePixels', metrics.baseline.falsePositivePixels, ...
    'candidate084FalsePositivePixels', metrics.candidate084.falsePositivePixels, ...
    'candidate086FalsePositivePixels', metrics.candidate086.falsePositivePixels, ...
    'baselineFalseNegativePixels', metrics.baseline.falseNegativePixels, ...
    'candidate084FalseNegativePixels', metrics.candidate084.falseNegativePixels, ...
    'candidate086FalseNegativePixels', metrics.candidate086.falseNegativePixels, ...
    'baselineRecall', metrics.baseline.recall, ...
    'candidate084Recall', metrics.candidate084.recall, ...
    'candidate086Recall', metrics.candidate086.recall, ...
    'baselinePrecision', metrics.baseline.precision, ...
    'candidate084Precision', metrics.candidate084.precision, ...
    'candidate086Precision', metrics.candidate086.precision, ...
    'candidate086PrecisionImproved', geometryAssessment.precisionImproved, ...
    'candidate086RecallNotLower', geometryAssessment.recallNotLower, ...
    'candidate086FalsePositivePixelsReduced', ...
        geometryAssessment.falsePositivePixelsReduced, ...
    'candidate086FalsePositiveLargestComponentReduced', ...
        geometryAssessment.falsePositiveLargestComponentReduced, ...
    'baselineFalsePositiveLargestComponentPixels', ...
        metrics.baseline.falsePositiveComponents.largestComponentPixels, ...
    'candidate084FalsePositiveLargestComponentPixels', ...
        metrics.candidate084.falsePositiveComponents.largestComponentPixels, ...
    'candidate086FalsePositiveLargestComponentPixels', ...
        metrics.candidate086.falsePositiveComponents.largestComponentPixels, ...
    'baselineRepairFineAbsActionSum', ...
        metrics.baselineRepairFineAbsAction.sum, ...
    'candidate084RepairFineAbsActionSum', ...
        metrics.candidate084RepairFineAbsAction.sum, ...
    'candidate086RepairFineAbsActionSum', ...
        metrics.candidate086RepairFineAbsAction.sum, ...
    'baselineRepairMidAbsActionSum', ...
        metrics.baselineRepairMidAbsAction.sum, ...
    'candidate084RepairMidAbsActionSum', ...
        metrics.candidate084RepairMidAbsAction.sum, ...
    'candidate086RepairMidAbsActionSum', ...
        metrics.candidate086RepairMidAbsAction.sum, ...
    'candidate086RepairFineNotWorseThan084', ...
        repairAssessment.fineNotWorseThan084, ...
    'candidate086RepairMidNotWorseThan084', ...
        repairAssessment.midNotWorseThan084, ...
    'baselineFinalRgbDistanceToOriginalMean', ...
        metrics.baselineFinalRgbDistanceToOriginal.mean, ...
    'candidate084FinalRgbDistanceToOriginalMean', ...
        metrics.candidate084FinalRgbDistanceToOriginal.mean, ...
    'candidate086FinalRgbDistanceToOriginalMean', ...
        metrics.candidate086FinalRgbDistanceToOriginal.mean, ...
    'baselineFinalLuminanceDistanceToOriginalMean', ...
        metrics.baselineFinalLuminanceDistanceToOriginal.mean, ...
    'candidate084FinalLuminanceDistanceToOriginalMean', ...
        metrics.candidate084FinalLuminanceDistanceToOriginal.mean, ...
    'candidate086FinalLuminanceDistanceToOriginalMean', ...
        metrics.candidate086FinalLuminanceDistanceToOriginal.mean, ...
    'hardProtectionMaskChangedPixels', 0, ...
    'hardCoreChangedPixels', 0, ...
    'formulaTolerance', options.formulaTolerance, ...
    'reconstructionTolerance', options.reconstructionTolerance);
writetable(struct2table(row), path);
end

function pathsValue = normalizeOutputFolder(value)
if nargin < 1 || isempty(value)
    value = fullfile(tempdir, ...
        'image_beauty_issue08_6_lash_support_geometry_20260919');
end
pathsValue = normalizeText(value, 'outputFolder');
if ~isfolder(pathsValue)
    mkdir(pathsValue);
end
end

function image = cropImage(image, box)
x1 = box(1);
y1 = box(2);
x2 = min(size(image, 2), box(1) + box(3) - 1);
y2 = min(size(image, 1), box(2) + box(4) - 1);
if ismatrix(image)
    image = image(y1:y2, x1:x2);
else
    image = image(y1:y2, x1:x2, :);
end
end

function drawContourIfPresent(mask, color, lineWidth)
if any(mask(:))
    contour(mask, [0.5, 0.5], color, 'LineWidth', lineWidth);
end
end

function value = readDiagnosticArray(value, imageSize, name)
if (~isnumeric(value) && ~islogical(value)) || ~isreal(value) || ...
        ~isequal(size(value), imageSize) || any(~isfinite(value(:)))
    error('diagnoseLashSupportGeometryCandidate:InvalidDiagnosticArray', ...
        '%s 尺寸或取值无效。', name);
end
value = double(value);
end

function validateArray(value, imageSize, name)
if (~isnumeric(value) && ~islogical(value)) || ~isreal(value) || ...
        ~isequal(size(value), imageSize) || any(~isfinite(value(:)))
    error('diagnoseLashSupportGeometryCandidate:InvalidArray', ...
        '%s 尺寸或取值无效。', name);
end
end

function validateMask(value, imageSize, name)
validateArray(value, imageSize, name);
if any(double(value(:)) < 0) || any(double(value(:)) > 1)
    error('diagnoseLashSupportGeometryCandidate:InvalidMask', ...
        'Mask %s 的取值不在 [0,1]。', name);
end
end

function feather = featherSoftMask(core, radius, peak)
if ~any(core(:))
    feather = zeros(size(core));
    return;
end
distance = bwdist(core);
feather = peak * max(0, 1 - distance / (radius + 1));
feather(core) = peak;
end

function value = percentileValue(sortedValues, fraction)
index = 1 + round(fraction * (numel(sortedValues) - 1));
value = sortedValues(index);
end

function value = normalizeText(value, name)
if isstring(value) && isscalar(value)
    value = char(value);
end
if ~ischar(value) || size(value, 1) ~= 1
    error('diagnoseLashSupportGeometryCandidate:InvalidText', ...
        '%s 必须是单行文本。', name);
end
end

function valid = isValidStrength(value)
valid = isnumeric(value) && isreal(value) && isscalar(value) && ...
    isfinite(value) && value >= 0 && value <= 100;
end
