function [summary, diagnostics] = diagnoseLashProtectionSufficiencyUpperBound( ...
        imagePath, outputFolder, options)
%DIAGNOSELASHPROTECTIONSUFFICIENCYUPPERBOUND 验证 Issue 08.5。
%   固定复用 Issue 08.4 的 77.png、人工真值、faceBox、browEye、lashRoi
%   和当前生产链。Baseline/Candidate 由 Issue 08.4 诊断入口生成；本入口
%   只在 Candidate 已有 lashProtection support 内把强度提升到 1，随后重跑
%   当前已有 Smoothing、Repair 和 compose。不得修改 src/。
%
%   [summary, diagnostics] = diagnoseLashProtectionSufficiencyUpperBound( ...
%       'E:\image_beauty\人脸\人脸\77.png', tempdir, struct(...
%       'productionRoot', 'E:\image_beauty', ...
%       'baselinePath', ...
%       'C:\Users\JJiio\AppData\Local\Temp\image_beauty_issue02_probe\77_v32_probe.mat'));

projectRoot = fileparts(fileparts(mfilename('fullpath')));
if nargin < 2
    outputFolder = [];
end
if nargin < 3
    options = [];
end
options = normalizeOptions(options, projectRoot);

productionRoot = resolveProductionRoot(options.productionRoot);
addpath(fullfile(productionRoot, 'src'), '-begin');
addpath(fileparts(mfilename('fullpath')), '-begin');

if nargin < 1 || isempty(imagePath)
    error('diagnoseLashProtectionSufficiencyUpperBound:MissingImage', ...
        '必须提供固定 77.png 的输入图像路径。');
end
imagePath = normalizeText(imagePath, 'imagePath');
outputFolder = normalizeOutputFolder(outputFolder);
inputImage = readInputImage(imagePath);
validateCommonFixtureShape(inputImage, options);

% 先由 Issue 08.4 入口完成同一生产基线和 Candidate。manualLashMask
% 在该入口内仅用于验收统计，未进入 Candidate 的任何计算路径。
stageFolder = tempname;
mkdir(stageFolder);
[continuitySummary, continuityDiagnostics] = ...
    diagnoseLashSoftContinuityCandidate(imagePath, stageFolder, options);
if ~continuitySummary.completed || ...
        ~strcmp(continuitySummary.issue, '08.4') || ...
        continuitySummary.runtimeCacheReused
    error('diagnoseLashProtectionSufficiencyUpperBound:InvalidContinuityStage', ...
        'Issue 08.4 基线阶段未按无缓存固定链完成。');
end

manualLashMask = continuityDiagnostics.manualLashMask;
annotation = continuityDiagnostics.annotation;
imageSize = [size(inputImage, 1), size(inputImage, 2)];
if ~annotation.diagnosticsIndependent || ~annotation.fixedAfterAnnotation
    error('diagnoseLashProtectionSufficiencyUpperBound:InvalidManualTruth', ...
        'manualLashMask 必须声明为独立且固定的人工真值。');
end

inputParams = struct('smoothingStrength', options.smoothingStrength, ...
    'whiteningStrength', options.whiteningStrength);
frequency = continuityDiagnostics.frequency;
blemishMap = continuityDiagnostics.blemishMap;
baselineBeautyMasks = continuityDiagnostics.baselineBeautyMasks;
candidateBeautyMasks = continuityDiagnostics.candidateBeautyMasks;
baselineTextureDiagnostics = continuityDiagnostics.baselineTextureDiagnostics;
candidateTextureDiagnostics = continuityDiagnostics.candidateTextureDiagnostics;
baselineLashProtection = continuityDiagnostics.baselineLashProtection;
candidateLashProtection = continuityDiagnostics.candidateLashProtection;
baselineTextureProtectionMask = double( ...
    baselineBeautyMasks.textureProtectionMask);
candidateTextureProtectionMask = double( ...
    candidateBeautyMasks.textureProtectionMask);

validateCommonFixture(continuitySummary, annotation, inputImage, options);
validateArray(candidateLashProtection, imageSize, 'candidateLashProtection');
validateArray(baselineLashProtection, imageSize, 'baselineLashProtection');
validateMask(baselineTextureProtectionMask, imageSize, ...
    'baselineTextureProtectionMask');
validateMask(candidateTextureProtectionMask, imageSize, ...
    'candidateTextureProtectionMask');

% Upper Bound 的唯一变量：Candidate lashProtection 已经非零的位置。
% 这里不使用 manualLashMask、dilation、第二次 closing 或任何新 support。
candidateSupport = candidateLashProtection > 0;
upperBoundLashProtection = candidateLashProtection;
upperBoundLashProtection(candidateSupport) = 1;
upperBoundSupport = upperBoundLashProtection > 0;
supportChangedPixels = nnz(xor(candidateSupport, upperBoundSupport));
if supportChangedPixels ~= 0
    error('diagnoseLashProtectionSufficiencyUpperBound:SupportChanged', ...
        'Upper Bound 改变了 Candidate lashProtection 的 support。');
end

periocularProtection = readDiagnosticArray( ...
    baselineTextureDiagnostics.periocularProtection, imageSize, ...
    'periocularProtection');
doubleEyelidProtection = readDiagnosticArray( ...
    baselineTextureDiagnostics.doubleEyelidProtection, imageSize, ...
    'doubleEyelidProtection');
upperBoundEyeDetailProtection = max(cat(3, periocularProtection, ...
    upperBoundLashProtection, doubleEyelidProtection), [], 3);
upperBoundTextureProtectionMask = max(baselineTextureProtectionMask, ...
    upperBoundEyeDetailProtection);
upperBoundTextureProtectionMask = min(max(upperBoundTextureProtectionMask, ...
    0), 1);
validateMask(upperBoundTextureProtectionMask, imageSize, ...
    'upperBoundTextureProtectionMask');

candidateIncreaseOutsideSupport = ...
    abs(upperBoundTextureProtectionMask - candidateTextureProtectionMask) ...
    > options.formulaTolerance & ~candidateSupport;
if any(candidateIncreaseOutsideSupport(:))
    error('diagnoseLashProtectionSufficiencyUpperBound:SpatialSupportExpanded', ...
        'Upper Bound 在 Candidate lashProtection support 外增加了保护。');
end

upperBoundBeautyMasks = candidateBeautyMasks;
upperBoundBeautyMasks.textureProtectionMask = upperBoundTextureProtectionMask;
if isfield(upperBoundBeautyMasks, 'protectionMask')
    upperBoundBeautyMasks.protectionMask = max(cat(3, ...
        upperBoundTextureProtectionMask, ...
        double(upperBoundBeautyMasks.structureProtectionMask), ...
        double(upperBoundBeautyMasks.hardProtectionMask)), [], 3);
end
validateUpperBoundIsolation(candidateBeautyMasks, upperBoundBeautyMasks, ...
    candidateSupport, options.formulaTolerance);

% 只重跑现有 Smoothing / Repair / compose。Base、tone、whitening 由
% Issue 08.4 的同次 Baseline compose 诊断重建并冻结。
[upperBoundSmoothedFrequency, upperBoundSmoothingDiagnostics] = ...
    beauty.smoothSkinTexture(frequency, upperBoundBeautyMasks, ...
    inputParams.smoothingStrength, blemishMap);
[upperBoundRepairedFrequency, upperBoundRepairDiagnostics] = ...
    beauty.repairSkinBlemishes(upperBoundSmoothedFrequency, ...
    upperBoundBeautyMasks, blemishMap, inputParams.smoothingStrength);
processing = buildFrozenProcessing( ...
    continuityDiagnostics.baselineComposeDiagnostics);
[reconstructedBaseline, reconstructedBaselineComposeDiagnostics] = ...
    beauty.composeBeautyResult(inputImage, frequency, ...
    continuityDiagnostics.repairedFrequency, baselineBeautyMasks, ...
    inputParams.whiteningStrength, processing);
[reconstructedCandidate, reconstructedCandidateComposeDiagnostics] = ...
    beauty.composeBeautyResult(inputImage, frequency, ...
    continuityDiagnostics.candidateRepairedFrequency, candidateBeautyMasks, ...
    inputParams.whiteningStrength, processing);
[upperBoundOutput, upperBoundComposeDiagnostics] = ...
    beauty.composeBeautyResult(inputImage, frequency, ...
    upperBoundRepairedFrequency, upperBoundBeautyMasks, ...
    inputParams.whiteningStrength, processing);

baselineOutput = continuityDiagnostics.baselineComposed;
candidateOutput = continuityDiagnostics.candidateOutput;
baselineComposeMaxRgbDifference = max(abs(double(reconstructedBaseline(:)) - ...
    double(baselineOutput(:))));
candidateComposeMaxRgbDifference = max(abs(double(reconstructedCandidate(:)) - ...
    double(candidateOutput(:))));
if baselineComposeMaxRgbDifference > options.reconstructionTolerance || ...
        candidateComposeMaxRgbDifference > options.reconstructionTolerance
    error('diagnoseLashProtectionSufficiencyUpperBound:FrozenComposeMismatch', ...
        '冻结 Base/tone/whitening 重建不一致：Baseline %.17g，Candidate %.17g。', ...
        baselineComposeMaxRgbDifference, candidateComposeMaxRgbDifference);
end

originalLuminance = rgb2ycbcr(im2double(inputImage));
originalLuminance = originalLuminance(:, :, 1);
validateArray(originalLuminance, imageSize, 'originalLuminance');

baselineSmoothedFrequency = continuityDiagnostics.smoothedFrequency;
candidateSmoothedFrequency = continuityDiagnostics.candidateSmoothedFrequency;
baselineRepairedFrequency = continuityDiagnostics.repairedFrequency;
candidateRepairedFrequency = continuityDiagnostics.candidateRepairedFrequency;
baselineRepairFineDelta = double(baselineRepairedFrequency.fine) - ...
    double(baselineSmoothedFrequency.fine);
candidateRepairFineDelta = double(candidateRepairedFrequency.fine) - ...
    double(candidateSmoothedFrequency.fine);
upperBoundRepairFineDelta = double(upperBoundRepairedFrequency.fine) - ...
    double(upperBoundSmoothedFrequency.fine);
baselineRepairMidDelta = double(baselineRepairedFrequency.mid) - ...
    double(baselineSmoothedFrequency.mid);
candidateRepairMidDelta = double(candidateRepairedFrequency.mid) - ...
    double(candidateSmoothedFrequency.mid);
upperBoundRepairMidDelta = double(upperBoundRepairedFrequency.mid) - ...
    double(upperBoundSmoothedFrequency.mid);

baselineRgbDistance = max(abs(double(baselineOutput) - ...
    double(inputImage)), [], 3);
candidateRgbDistance = max(abs(double(candidateOutput) - ...
    double(inputImage)), [], 3);
upperBoundRgbDistance = max(abs(double(upperBoundOutput) - ...
    double(inputImage)), [], 3);
baselineLuminanceDistance = abs(double( ...
    continuityDiagnostics.baselineComposeDiagnostics.outputLuminance) - ...
    double(originalLuminance));
candidateLuminanceDistance = abs(double( ...
    continuityDiagnostics.candidateComposeDiagnostics.outputLuminance) - ...
    double(originalLuminance));
upperBoundLuminanceDistance = abs(double( ...
    upperBoundComposeDiagnostics.outputLuminance) - ...
    double(originalLuminance));

browEyeMask = makeRoiMask(options.browEyeRoi, imageSize);
manualOutsideBrowEyeMask = browEyeMask & ~manualLashMask;
candidateUpperRgbChange = max(abs(double(upperBoundOutput) - ...
    double(candidateOutput)), [], 3);
candidateUpperLuminanceChange = abs(double( ...
    upperBoundComposeDiagnostics.outputLuminance) - ...
    double(continuityDiagnostics.candidateComposeDiagnostics.outputLuminance));

baselineHardMask = double(baselineBeautyMasks.hardProtectionMask);
candidateHardMask = double(candidateBeautyMasks.hardProtectionMask);
upperBoundHardMask = double(upperBoundBeautyMasks.hardProtectionMask);
hardProtectionMaskChangedPixels = struct( ...
    'baselineToCandidate', nnz(baselineHardMask ~= candidateHardMask), ...
    'baselineToUpperBound', nnz(baselineHardMask ~= upperBoundHardMask), ...
    'candidateToUpperBound', nnz(candidateHardMask ~= upperBoundHardMask));

baselineLashCore = logical(baselineTextureDiagnostics.lashCore);
candidateLashCore = logical(candidateTextureDiagnostics.lashCore);
upperBoundLashCore = candidateLashCore;
lashCoreChangedPixels = struct( ...
    'baselineToCandidate', nnz(baselineLashCore ~= candidateLashCore), ...
    'baselineToUpperBound', nnz(baselineLashCore ~= upperBoundLashCore), ...
    'candidateToUpperBound', nnz(candidateLashCore ~= upperBoundLashCore));

hardRegion = baselineHardMask >= .999;
baselineHardChanged = max(abs(double(baselineOutput) - ...
    double(inputImage)), [], 3) > 0;
candidateHardChanged = max(abs(double(candidateOutput) - ...
    double(inputImage)), [], 3) > 0;
upperBoundHardChanged = max(abs(double(upperBoundOutput) - ...
    double(inputImage)), [], 3) > 0;
hardProtectedFinalRgbChangedCount = struct( ...
    'baseline', nnz(baselineHardChanged(hardRegion)), ...
    'candidate', nnz(candidateHardChanged(hardRegion)), ...
    'upperBound', nnz(upperBoundHardChanged(hardRegion)));

metrics = makeMetrics(manualLashMask, manualOutsideBrowEyeMask, ...
    candidateLashProtection, upperBoundLashProtection, ...
    candidateSupport, baselineRepairFineDelta, candidateRepairFineDelta, ...
    upperBoundRepairFineDelta, baselineRepairMidDelta, ...
    candidateRepairMidDelta, upperBoundRepairMidDelta, ...
    baselineRgbDistance, candidateRgbDistance, upperBoundRgbDistance, ...
    baselineLuminanceDistance, candidateLuminanceDistance, ...
    upperBoundLuminanceDistance, candidateUpperRgbChange, ...
    candidateUpperLuminanceChange, hardProtectionMaskChangedPixels, ...
    lashCoreChangedPixels, hardProtectedFinalRgbChangedCount, ...
    options.nonzeroTolerance);
metrics.candidateUpperTextureChangedPixels = nnz( ...
    abs(upperBoundTextureProtectionMask - candidateTextureProtectionMask) > ...
    options.formulaTolerance);
metrics.candidateUpperTextureChangedOutsideCandidateSupport = nnz( ...
    candidateIncreaseOutsideSupport);
metrics.upperBoundLashStrengthRaisedPixels = nnz( ...
    abs(upperBoundLashProtection - candidateLashProtection) > ...
    options.formulaTolerance);
metrics.upperBoundLashStrengthIncreaseTotal = sum( ...
    upperBoundLashProtection(:) - candidateLashProtection(:));
metrics.upperBoundLashStrengthIncreaseInsideManual = makeStats( ...
    (upperBoundLashProtection(manualLashMask) - ...
    candidateLashProtection(manualLashMask)), options.nonzeroTolerance);
metrics.numericAssessment = assessNumericEvidence(metrics, ...
    supportChangedPixels, options.formulaTolerance);

paths = writeArtifacts(outputFolder, inputImage, manualLashMask, ...
    baselineOutput, candidateOutput, upperBoundOutput, ...
    candidateLashProtection, upperBoundLashProtection, candidateSupport, ...
    baselineRepairFineDelta, candidateRepairFineDelta, ...
    upperBoundRepairFineDelta, baselineRepairMidDelta, ...
    candidateRepairMidDelta, upperBoundRepairMidDelta, options.lashRoi);
paths.csv = fullfile(outputFolder, ...
    'lash_protection_sufficiency_upper_bound_metrics.csv');
writeMetricsCsv(paths.csv, metrics, metrics.numericAssessment, ...
    supportChangedPixels, hardProtectionMaskChangedPixels, ...
    lashCoreChangedPixels, hardProtectedFinalRgbChangedCount);
paths.data = fullfile(outputFolder, ...
    'lash_protection_sufficiency_upper_bound_diagnostic.mat');

summary = struct( ...
    'completed', true, ...
    'issue', '08.5', ...
    'case', 'requiresVisualReview', ...
    'caseAssessment', metrics.numericAssessment, ...
    'contract', continuitySummary.contract, ...
    'imagePath', imagePath, ...
    'inputSize', size(inputImage), ...
    'faceBox', double(options.faceBox), ...
    'browEye', double(options.browEyeRoi), ...
    'lashRoi', double(options.lashRoi), ...
    'parameters', inputParams, ...
    'baselinePath', options.baselinePath, ...
    'manualLashMaskId', annotation.annotationId, ...
    'manualLashMaskIndependent', annotation.diagnosticsIndependent, ...
    'manualLashMaskFixed', annotation.fixedAfterAnnotation, ...
    'manualLashMaskPixels', nnz(manualLashMask), ...
    'runtimeCacheReused', continuitySummary.runtimeCacheReused, ...
    'sameMaskRun', true, ...
    'baseToneWhiteningFrozen', true, ...
    'upperBoundOnlyExistingCandidateSupport', true, ...
    'candidateSupportPixels', nnz(candidateSupport), ...
    'upperBoundSupportPixels', nnz(upperBoundSupport), ...
    'supportChangedPixels', supportChangedPixels, ...
    'baselineComposeMaxRgbDifference', baselineComposeMaxRgbDifference, ...
    'candidateComposeMaxRgbDifference', candidateComposeMaxRgbDifference, ...
    'candidateUpperTextureChangedOutsideCandidateSupport', ...
    metrics.candidateUpperTextureChangedOutsideCandidateSupport, ...
    'hardProtectionMaskChangedPixels', hardProtectionMaskChangedPixels, ...
    'hardProtectedFinalRgbChangedCount', hardProtectedFinalRgbChangedCount, ...
    'lashCoreChangedPixels', lashCoreChangedPixels, ...
    'metrics', metrics, ...
    'paths', paths);

diagnosticData = struct( ...
    'summary', summary, ...
    'inputImage', inputImage, ...
    'annotation', annotation, ...
    'manualLashMask', manualLashMask, ...
    'browEyeMask', browEyeMask, ...
    'manualOutsideBrowEyeMask', manualOutsideBrowEyeMask, ...
    'frequency', frequency, ...
    'blemishMap', blemishMap, ...
    'baselineBeautyMasks', baselineBeautyMasks, ...
    'candidateBeautyMasks', candidateBeautyMasks, ...
    'upperBoundBeautyMasks', upperBoundBeautyMasks, ...
    'baselineTextureDiagnostics', baselineTextureDiagnostics, ...
    'candidateTextureDiagnostics', candidateTextureDiagnostics, ...
    'upperBoundTextureDiagnostics', makeUpperTextureDiagnostics( ...
        baselineTextureDiagnostics, upperBoundEyeDetailProtection, ...
        upperBoundLashProtection), ...
    'baselineLashProtection', baselineLashProtection, ...
    'candidateLashProtection', candidateLashProtection, ...
    'upperBoundLashProtection', upperBoundLashProtection, ...
    'candidateSupport', candidateSupport, ...
    'upperBoundSupport', upperBoundSupport, ...
    'baselineSmoothedFrequency', baselineSmoothedFrequency, ...
    'candidateSmoothedFrequency', candidateSmoothedFrequency, ...
    'upperBoundSmoothedFrequency', upperBoundSmoothedFrequency, ...
    'baselineRepairedFrequency', baselineRepairedFrequency, ...
    'candidateRepairedFrequency', candidateRepairedFrequency, ...
    'upperBoundRepairedFrequency', upperBoundRepairedFrequency, ...
    'upperBoundSmoothingDiagnostics', upperBoundSmoothingDiagnostics, ...
    'upperBoundRepairDiagnostics', upperBoundRepairDiagnostics, ...
    'baselineOutput', baselineOutput, ...
    'candidateOutput', candidateOutput, ...
    'upperBoundOutput', upperBoundOutput, ...
    'baselineComposeDiagnostics', continuityDiagnostics.baselineComposeDiagnostics, ...
    'candidateComposeDiagnostics', continuityDiagnostics.candidateComposeDiagnostics, ...
    'upperBoundComposeDiagnostics', upperBoundComposeDiagnostics, ...
    'reconstructedBaselineComposeDiagnostics', reconstructedBaselineComposeDiagnostics, ...
    'reconstructedCandidateComposeDiagnostics', reconstructedCandidateComposeDiagnostics, ...
    'originalLuminance', originalLuminance, ...
    'baselineRepairFineDelta', baselineRepairFineDelta, ...
    'candidateRepairFineDelta', candidateRepairFineDelta, ...
    'upperBoundRepairFineDelta', upperBoundRepairFineDelta, ...
    'baselineRepairMidDelta', baselineRepairMidDelta, ...
    'candidateRepairMidDelta', candidateRepairMidDelta, ...
    'upperBoundRepairMidDelta', upperBoundRepairMidDelta, ...
    'candidateUpperRgbChange', candidateUpperRgbChange, ...
    'candidateUpperLuminanceChange', candidateUpperLuminanceChange, ...
    'metrics', metrics);
save(paths.data, 'diagnosticData', '-v7.3');
summary.paths = paths;
diagnosticData.summary = summary;
diagnostics = diagnosticData;

fprintf('Issue 08.5 睫毛 Protection Sufficiency Upper Bound 产物：%s\n', ...
    outputFolder);
fprintf('Candidate / Upper Bound support：%d / %d；changed：%d\n', ...
    nnz(candidateSupport), nnz(upperBoundSupport), supportChangedPixels);
fprintf('真实睫毛 lashProtection 均值 Candidate -> Upper：%.17g -> %.17g\n', ...
    metrics.candidateLashProtection.mean, metrics.upperBoundLashProtection.mean);
fprintf('真实睫毛 Repair Fine 绝对作用量：%.17g -> %.17g -> %.17g\n', ...
    metrics.baselineRepairFineAbsAction.sum, ...
    metrics.candidateRepairFineAbsAction.sum, ...
    metrics.upperBoundRepairFineAbsAction.sum);
fprintf('真实睫毛 Repair Mid 绝对作用量：%.17g -> %.17g -> %.17g\n', ...
    metrics.baselineRepairMidAbsAction.sum, ...
    metrics.candidateRepairMidAbsAction.sum, ...
    metrics.upperBoundRepairMidAbsAction.sum);
fprintf('真实睫毛最终 RGB 到原图均值：%.17g -> %.17g -> %.17g\n', ...
    metrics.baselineFinalRgbDistanceToOriginal.mean, ...
    metrics.candidateFinalRgbDistanceToOriginal.mean, ...
    metrics.upperBoundFinalRgbDistanceToOriginal.mean);
fprintf('真实睫毛最终 luminance 到原图均值：%.17g -> %.17g -> %.17g\n', ...
    metrics.baselineFinalLuminanceDistanceToOriginal.mean, ...
    metrics.candidateFinalLuminanceDistanceToOriginal.mean, ...
    metrics.upperBoundFinalLuminanceDistanceToOriginal.mean);
fprintf('hard mask changed B->C/C->U/B->U：%d / %d / %d；lashCore B->C/C->U/B->U：%d / %d / %d\n', ...
    hardProtectionMaskChangedPixels.baselineToCandidate, ...
    hardProtectionMaskChangedPixels.candidateToUpperBound, ...
    hardProtectionMaskChangedPixels.baselineToUpperBound, ...
    lashCoreChangedPixels.baselineToCandidate, ...
    lashCoreChangedPixels.candidateToUpperBound, ...
    lashCoreChangedPixels.baselineToUpperBound);
fprintf('数值证据：%s；最终 Case 需要人工核对四列主图。\n', ...
    metrics.numericAssessment.case);
end

function options = normalizeOptions(options, projectRoot)
if nargin < 1 || isempty(options)
    options = struct();
end
if ~isstruct(options) || ~isscalar(options)
    error('diagnoseLashProtectionSufficiencyUpperBound:InvalidOptions', ...
        'options 必须是标量结构。');
end
fixedFields = { ...
    'faceBox', [95, 79, 286, 372]; ...
    'browEyeRoi', [165, 205, 150, 100]; ...
    'lashRoi', [102, 248, 177, 48]};
for index = 1:size(fixedFields, 1)
    name = fixedFields{index, 1};
    defaultValue = fixedFields{index, 2};
    if ~isfield(options, name) || isempty(options.(name))
        options.(name) = defaultValue;
    end
    if ~isequal(double(options.(name)), double(defaultValue))
        error('diagnoseLashProtectionSufficiencyUpperBound:NonFixedFixture', ...
            '%s 必须复用 Issue 08.5 固定值。', name);
    end
end
options.faceBox = double(options.faceBox);
options.browEyeRoi = double(options.browEyeRoi);
options.lashRoi = double(options.lashRoi);
if ~isfield(options, 'smoothingStrength') || isempty(options.smoothingStrength)
    options.smoothingStrength = 100;
end
if ~isfield(options, 'whiteningStrength') || isempty(options.whiteningStrength)
    options.whiteningStrength = 15;
end
if ~isValidStrength(options.smoothingStrength) || ...
        ~isValidStrength(options.whiteningStrength)
    error('diagnoseLashProtectionSufficiencyUpperBound:InvalidStrength', ...
        '强度必须是 0 到 100 的有限数值标量。');
end
if ~isfield(options, 'productionRoot') || isempty(options.productionRoot)
    options.productionRoot = projectRoot;
end
options.productionRoot = normalizeText(options.productionRoot, ...
    'productionRoot');
if ~isfield(options, 'baselinePath') || isempty(options.baselinePath)
    options.baselinePath = ...
        'C:\Users\JJiio\AppData\Local\Temp\image_beauty_issue02_probe\77_v32_probe.mat';
end
options.baselinePath = normalizeText(options.baselinePath, 'baselinePath');
if ~isfield(options, 'formulaTolerance') || isempty(options.formulaTolerance)
    options.formulaTolerance = 1e-12;
end
if ~isfield(options, 'reconstructionTolerance') || ...
        isempty(options.reconstructionTolerance)
    options.reconstructionTolerance = 1e-12;
end
if ~isfield(options, 'nonzeroTolerance') || isempty(options.nonzeroTolerance)
    options.nonzeroTolerance = 1e-12;
end
if ~isscalar(options.formulaTolerance) || ...
        ~isfinite(options.formulaTolerance) || options.formulaTolerance <= 0 || ...
        ~isscalar(options.reconstructionTolerance) || ...
        ~isfinite(options.reconstructionTolerance) || ...
        options.reconstructionTolerance <= 0 || ...
        ~isscalar(options.nonzeroTolerance) || ...
        ~isfinite(options.nonzeroTolerance) || options.nonzeroTolerance <= 0
    error('diagnoseLashProtectionSufficiencyUpperBound:InvalidTolerance', ...
        '公式、重建和非零容差必须是正的有限标量。');
end
options.formulaTolerance = double(options.formulaTolerance);
options.reconstructionTolerance = double(options.reconstructionTolerance);
options.nonzeroTolerance = double(options.nonzeroTolerance);
end

function root = resolveProductionRoot(root)
if ~isfolder(root) || ~isfolder(fullfile(root, 'src'))
    error('diagnoseLashProtectionSufficiencyUpperBound:InvalidProductionRoot', ...
        '生产算法根目录或 src 目录不存在：%s。', root);
end
end

function validateCommonFixtureShape(inputImage, options)
if ~isequal(size(inputImage), [450, 512, 3]) || ...
        ~isequal(options.faceBox, [95, 79, 286, 372]) || ...
        ~isequal(options.browEyeRoi, [165, 205, 150, 100]) || ...
        ~isequal(options.lashRoi, [102, 248, 177, 48])
    error('diagnoseLashProtectionSufficiencyUpperBound:UnexpectedFixture', ...
        'Issue 08.5 必须复用固定 77 图像尺寸和坐标。');
end
end

function validateCommonFixture(continuitySummary, annotation, inputImage, options)
validateCommonFixtureShape(inputImage, options);
if ~strcmp(annotation.annotationId, '77-manual-lash-v1') || ...
        ~strcmp(continuitySummary.manualLashMaskId, '77-manual-lash-v1')
    error('diagnoseLashProtectionSufficiencyUpperBound:UnexpectedFixture', ...
        'Issue 08.5 必须复用固定 77 人工真值。');
end
end

function image = readInputImage(imagePath)
if ~isfile(imagePath)
    error('diagnoseLashProtectionSufficiencyUpperBound:MissingImage', ...
        '输入图像不存在：%s。', imagePath);
end
image = imread(imagePath);
if ~isa(image, 'uint8') || ~isreal(image) || ndims(image) ~= 3 || ...
        size(image, 3) ~= 3
    error('diagnoseLashProtectionSufficiencyUpperBound:InvalidImage', ...
        '输入图像必须是 uint8 三通道 RGB 图像。');
end
end

function validateUpperBoundIsolation(candidateMasks, upperMasks, support, tolerance)
unchangedNames = {'structureProtectionMask', 'hardProtectionMask', ...
    'whiteningProtectionMask', 'chromaProtectionMask', 'toneProtectionMask', ...
    'strengthMap', 'faceStrengthMap', 'nonFaceStrengthMap', 'skinMask', ...
    'faceSkinMask', 'nonFaceSkinMask', 'noseMask'};
for index = 1:numel(unchangedNames)
    name = unchangedNames{index};
    if isfield(candidateMasks, name) && isfield(upperMasks, name)
        if max(abs(double(candidateMasks.(name)(:)) - ...
                double(upperMasks.(name)(:)))) > tolerance
            error('diagnoseLashProtectionSufficiencyUpperBound:SingleFactorViolation', ...
                'Upper Bound 意外修改了 %s。', name);
        end
    end
end
candidateTexture = double(candidateMasks.textureProtectionMask);
upperTexture = double(upperMasks.textureProtectionMask);
changedOutside = abs(upperTexture - candidateTexture) > tolerance & ~support;
if any(changedOutside(:))
    error('diagnoseLashProtectionSufficiencyUpperBound:SingleFactorViolation', ...
        'Upper Bound 的最终 textureProtectionMask 在 lash support 外发生变化。');
end
if any(upperTexture(:) < -tolerance) || any(upperTexture(:) > 1 + tolerance)
    error('diagnoseLashProtectionSufficiencyUpperBound:InvalidUpperBoundMask', ...
        'Upper Bound textureProtectionMask 不在 [0,1]。');
end
end

function processing = buildFrozenProcessing(composeDiagnostics)
required = {'baseSupport', 'baseDelta', 'whiteningSupport', ...
    'whiteningDelta', 'toneSupport', 'toneTargetCb', 'toneTargetCr'};
if ~isstruct(composeDiagnostics) || ~all(isfield(composeDiagnostics, required))
    error('diagnoseLashProtectionSufficiencyUpperBound:MissingFrozenProcessing', ...
        '无法从同次 compose 诊断重建冻结的 Base/tone/whitening。');
end
processing = struct( ...
    'baseLuminance', struct('supportMap', composeDiagnostics.baseSupport, ...
        'baseDelta', composeDiagnostics.baseDelta), ...
    'skinTone', struct('toneSupport', composeDiagnostics.toneSupport, ...
        'outputCb', composeDiagnostics.toneTargetCb, ...
        'outputCr', composeDiagnostics.toneTargetCr), ...
    'whitening', struct('supportMap', composeDiagnostics.whiteningSupport, ...
        'delta', composeDiagnostics.whiteningDelta));
end

function metrics = makeMetrics(manualMask, outsideMask, candidateLash, ...
        upperLash, candidateSupport, baselineFine, candidateFine, upperFine, ...
        baselineMid, candidateMid, upperMid, baselineRgb, candidateRgb, ...
        upperRgb, baselineLuma, candidateLuma, upperLuma, upperRgbChange, ...
        upperLumaChange, hardMaskChanges, lashCoreChanges, hardFinalChanges, ...
        tolerance)
metrics = struct( ...
    'manualLashPixels', nnz(manualMask), ...
    'candidateLashProtection', makeStats(candidateLash(manualMask), tolerance), ...
    'upperBoundLashProtection', makeStats(upperLash(manualMask), tolerance), ...
    'candidateSupport', makeStats(double(candidateSupport(manualMask)), tolerance), ...
    'candidateSupportPixels', nnz(candidateSupport), ...
    'upperBoundSupportPixels', nnz(candidateSupport), ...
    'baselineRepairFineAbsAction', makeStats(abs(baselineFine(manualMask)), tolerance), ...
    'candidateRepairFineAbsAction', makeStats(abs(candidateFine(manualMask)), tolerance), ...
    'upperBoundRepairFineAbsAction', makeStats(abs(upperFine(manualMask)), tolerance), ...
    'baselineRepairMidAbsAction', makeStats(abs(baselineMid(manualMask)), tolerance), ...
    'candidateRepairMidAbsAction', makeStats(abs(candidateMid(manualMask)), tolerance), ...
    'upperBoundRepairMidAbsAction', makeStats(abs(upperMid(manualMask)), tolerance), ...
    'baselineFinalRgbDistanceToOriginal', makeStats(baselineRgb(manualMask), tolerance), ...
    'candidateFinalRgbDistanceToOriginal', makeStats(candidateRgb(manualMask), tolerance), ...
    'upperBoundFinalRgbDistanceToOriginal', makeStats(upperRgb(manualMask), tolerance), ...
    'baselineFinalLuminanceDistanceToOriginal', makeStats(baselineLuma(manualMask), tolerance), ...
    'candidateFinalLuminanceDistanceToOriginal', makeStats(candidateLuma(manualMask), tolerance), ...
    'upperBoundFinalLuminanceDistanceToOriginal', makeStats(upperLuma(manualMask), tolerance), ...
    'candidateUpperManualFinalRgbChange', makeStats(upperRgbChange(manualMask), tolerance), ...
    'candidateUpperManualFinalLuminanceChange', makeStats(upperLumaChange(manualMask), tolerance), ...
    'candidateUpperOutsideBrowEyeFinalRgbChange', makeStats(upperRgbChange(outsideMask), tolerance), ...
    'candidateUpperOutsideBrowEyeFinalLuminanceChange', makeStats(upperLumaChange(outsideMask), tolerance), ...
    'repairFineCandidateReduction', sum(abs(baselineFine(manualMask))) - ...
        sum(abs(candidateFine(manualMask))), ...
    'repairFineUpperBoundReduction', sum(abs(candidateFine(manualMask))) - ...
        sum(abs(upperFine(manualMask))), ...
    'repairMidCandidateReduction', sum(abs(baselineMid(manualMask))) - ...
        sum(abs(candidateMid(manualMask))), ...
    'repairMidUpperBoundReduction', sum(abs(candidateMid(manualMask))) - ...
        sum(abs(upperMid(manualMask))), ...
    'finalRgbCandidateDistanceReduction', mean(baselineRgb(manualMask)) - ...
        mean(candidateRgb(manualMask)), ...
    'finalRgbUpperBoundDistanceReduction', mean(candidateRgb(manualMask)) - ...
        mean(upperRgb(manualMask)), ...
    'finalLuminanceCandidateDistanceReduction', mean(baselineLuma(manualMask)) - ...
        mean(candidateLuma(manualMask)), ...
    'finalLuminanceUpperBoundDistanceReduction', mean(candidateLuma(manualMask)) - ...
        mean(upperLuma(manualMask)), ...
    'hardProtectionMaskChangedPixels', hardMaskChanges, ...
    'lashCoreChangedPixels', lashCoreChanges, ...
    'hardProtectedFinalRgbChangedCount', hardFinalChanges);
end

function assessment = assessNumericEvidence(metrics, supportChangedPixels, tolerance)
finiteValues = [ ...
    metrics.candidateLashProtection.mean, ...
    metrics.upperBoundLashProtection.mean, ...
    metrics.baselineRepairFineAbsAction.sum, ...
    metrics.candidateRepairFineAbsAction.sum, ...
    metrics.upperBoundRepairFineAbsAction.sum, ...
    metrics.baselineRepairMidAbsAction.sum, ...
    metrics.candidateRepairMidAbsAction.sum, ...
    metrics.upperBoundRepairMidAbsAction.sum, ...
    metrics.baselineFinalRgbDistanceToOriginal.mean, ...
    metrics.candidateFinalRgbDistanceToOriginal.mean, ...
    metrics.upperBoundFinalRgbDistanceToOriginal.mean, ...
    metrics.baselineFinalLuminanceDistanceToOriginal.mean, ...
    metrics.candidateFinalLuminanceDistanceToOriginal.mean, ...
    metrics.upperBoundFinalLuminanceDistanceToOriginal.mean];
finiteEvidence = all(isfinite(finiteValues));
hardUnchanged = all(struct2array(metrics.hardProtectionMaskChangedPixels) == 0) && ...
    all(struct2array(metrics.lashCoreChangedPixels) == 0) && ...
    all(struct2array(metrics.hardProtectedFinalRgbChangedCount) == 0);
strengthRaised = metrics.upperBoundLashProtection.mean >= ...
    metrics.candidateLashProtection.mean - tolerance && ...
    metrics.upperBoundLashStrengthRaisedPixels > 0;
fineReduced = metrics.repairFineUpperBoundReduction > tolerance;
midReduced = metrics.repairMidUpperBoundReduction > tolerance;
rgbCloser = metrics.finalRgbUpperBoundDistanceReduction > tolerance;
lumaCloser = metrics.finalLuminanceUpperBoundDistanceReduction > tolerance;
if finiteEvidence && supportChangedPixels == 0 && strengthRaised && ...
        hardUnchanged
    caseName = 'numericUpperBoundConstructed';
else
    caseName = 'numericUpperBoundConstructionFailed';
end
assessment = struct( ...
    'case', caseName, ...
    'requiresVisualReview', true, ...
    'supportUnchanged', supportChangedPixels == 0, ...
    'strengthRaised', strengthRaised, ...
    'fineAbsActionReduced', fineReduced, ...
    'midAbsActionReduced', midReduced, ...
    'finalRgbCloserToOriginal', rgbCloser, ...
    'finalLuminanceCloserToOriginal', lumaCloser, ...
    'hardAndCoreUnchanged', hardUnchanged, ...
    'finiteEvidence', finiteEvidence, ...
    'basis', ['数值部分只核对同一 Candidate support 内的强度上限、', ...
        '同次 Smoothing/Repair/compose 和硬保护不变；Case A/B/C 必须结合四列主图人工判定。']);
end

function stats = makeStats(values, tolerance)
values = double(values(:));
if isempty(values)
    stats = struct('values', values, 'count', 0, 'sum', 0, ...
        'mean', NaN, 'min', NaN, 'max', NaN, ...
        'nonzeroPixels', 0, 'nonzeroFraction', NaN);
    return;
end
stats = struct( ...
    'values', values, ...
    'count', numel(values), ...
    'sum', sum(values), ...
    'mean', mean(values), ...
    'min', min(values), ...
    'max', max(values), ...
    'nonzeroPixels', nnz(abs(values) > tolerance), ...
    'nonzeroFraction', nnz(abs(values) > tolerance) / numel(values));
end

function paths = writeArtifacts(outputFolder, inputImage, manualMask, ...
        baselineOutput, candidateOutput, upperOutput, candidateLash, ...
        upperLash, candidateSupport, baselineFine, candidateFine, upperFine, ...
        baselineMid, candidateMid, upperMid, lashRoi)
originalCrop = cropImage(inputImage, lashRoi);
manualCrop = cropImage(manualMask, lashRoi);
paths = struct('outputFolder', outputFolder);
paths.originalLash = fullfile(outputFolder, 'original_lash.png');
writeFinalLashFigure(originalCrop, originalCrop, manualCrop, ...
    'A 原图 Original lash', paths.originalLash);
paths.baselineFinalLash = fullfile(outputFolder, 'baseline_final_lash.png');
writeFinalLashFigure(originalCrop, cropImage(baselineOutput, lashRoi), ...
    manualCrop, 'B Baseline final lash', paths.baselineFinalLash);
paths.candidateFinalLash = fullfile(outputFolder, ...
    'candidate_final_lash.png');
writeFinalLashFigure(originalCrop, cropImage(candidateOutput, lashRoi), ...
    manualCrop, 'C 08.4 Candidate final lash', paths.candidateFinalLash);
paths.upperBoundFinalLash = fullfile(outputFolder, ...
    'upper_bound_final_lash.png');
writeFinalLashFigure(originalCrop, cropImage(upperOutput, lashRoi), ...
    manualCrop, 'D Candidate Upper Bound final lash', paths.upperBoundFinalLash);
paths.comparison = fullfile(outputFolder, ...
    'baseline_candidate_upperbound_comparison.png');
writeFinalComparison(originalCrop, cropImage(baselineOutput, lashRoi), ...
    cropImage(candidateOutput, lashRoi), cropImage(upperOutput, lashRoi), ...
    manualCrop, paths.comparison);
paths.candidateLashProtection = fullfile(outputFolder, ...
    'candidate_lash_protection.png');
writeProtectionFigure(originalCrop, manualCrop, cropImage(candidateLash, lashRoi), ...
    'Candidate lashProtection [0,1]', paths.candidateLashProtection, 1);
paths.upperBoundLashProtection = fullfile(outputFolder, ...
    'upper_bound_lash_protection.png');
writeProtectionFigure(originalCrop, manualCrop, cropImage(upperLash, lashRoi), ...
    'Upper Bound lashProtection [0,1]', paths.upperBoundLashProtection, 1);
paths.candidateSupport = fullfile(outputFolder, 'candidate_support.png');
writeProtectionFigure(originalCrop, manualCrop, cropImage(candidateSupport, lashRoi), ...
    'Candidate lashProtection support', paths.candidateSupport, 1);

fineLimit = max([abs(baselineFine(:)); abs(candidateFine(:)); abs(upperFine(:))]);
midLimit = max([abs(baselineMid(:)); abs(candidateMid(:)); abs(upperMid(:))]);
if isempty(fineLimit) || fineLimit <= 0 || ~isfinite(fineLimit)
    fineLimit = 1;
end
if isempty(midLimit) || midLimit <= 0 || ~isfinite(midLimit)
    midLimit = 1;
end
paths.baselineRepairFineDelta = fullfile(outputFolder, ...
    'baseline_repair_fine_delta.png');
writeDeltaFigure(originalCrop, manualCrop, cropImage(baselineFine, lashRoi), ...
    'Baseline Repair Fine absolute delta', paths.baselineRepairFineDelta, ...
    fineLimit);
paths.candidateRepairFineDelta = fullfile(outputFolder, ...
    'candidate_repair_fine_delta.png');
writeDeltaFigure(originalCrop, manualCrop, cropImage(candidateFine, lashRoi), ...
    'Candidate Repair Fine absolute delta', paths.candidateRepairFineDelta, ...
    fineLimit);
paths.upperBoundRepairFineDelta = fullfile(outputFolder, ...
    'upper_bound_repair_fine_delta.png');
writeDeltaFigure(originalCrop, manualCrop, cropImage(upperFine, lashRoi), ...
    'Upper Bound Repair Fine absolute delta', paths.upperBoundRepairFineDelta, ...
    fineLimit);
paths.baselineRepairMidDelta = fullfile(outputFolder, ...
    'baseline_repair_mid_delta.png');
writeDeltaFigure(originalCrop, manualCrop, cropImage(baselineMid, lashRoi), ...
    'Baseline Repair Mid absolute delta', paths.baselineRepairMidDelta, ...
    midLimit);
paths.candidateRepairMidDelta = fullfile(outputFolder, ...
    'candidate_repair_mid_delta.png');
writeDeltaFigure(originalCrop, manualCrop, cropImage(candidateMid, lashRoi), ...
    'Candidate Repair Mid absolute delta', paths.candidateRepairMidDelta, ...
    midLimit);
paths.upperBoundRepairMidDelta = fullfile(outputFolder, ...
    'upper_bound_repair_mid_delta.png');
writeDeltaFigure(originalCrop, manualCrop, cropImage(upperMid, lashRoi), ...
    'Upper Bound Repair Mid absolute delta', paths.upperBoundRepairMidDelta, ...
    midLimit);
end

function writeFinalLashFigure(originalCrop, finalCrop, manualCrop, label, path)
figureHandle = figure('Visible', 'off', 'Color', 'white', ...
    'Position', [100, 100, 1500, 600]);
tiledlayout(1, 2, 'Padding', 'compact', 'TileSpacing', 'compact');
nexttile;
imshow(originalCrop);
hold on;
drawContourIfPresent(manualCrop, 'r', 1.8);
hold off;
title('A 原图 + manualLashMask');
nexttile;
imshow(finalCrop);
hold on;
drawContourIfPresent(manualCrop, 'r', 1.8);
hold off;
title(label, 'Interpreter', 'none');
exportgraphics(figureHandle, path, 'Resolution', 170);
close(figureHandle);
end

function writeFinalComparison(originalCrop, baselineCrop, candidateCrop, ...
        upperCrop, manualCrop, path)
figureHandle = figure('Visible', 'off', 'Color', 'white', ...
    'Position', [80, 80, 2400, 650]);
tiledlayout(1, 4, 'Padding', 'compact', 'TileSpacing', 'compact');
nexttile;
imshow(originalCrop);
hold on;
drawContourIfPresent(manualCrop, 'r', 1.5);
hold off;
title('A 原图');
nexttile;
imshow(baselineCrop);
hold on;
drawContourIfPresent(manualCrop, 'r', 1.5);
hold off;
title('B Baseline');
nexttile;
imshow(candidateCrop);
hold on;
drawContourIfPresent(manualCrop, 'r', 1.5);
hold off;
title('C 08.4 Candidate');
nexttile;
imshow(upperCrop);
hold on;
drawContourIfPresent(manualCrop, 'r', 1.5);
hold off;
title('D Candidate Upper Bound');
exportgraphics(figureHandle, path, 'Resolution', 170);
close(figureHandle);
end

function writeProtectionFigure(originalCrop, manualCrop, mapCrop, label, path, limit)
figureHandle = figure('Visible', 'off', 'Color', 'white', ...
    'Position', [100, 100, 1500, 600]);
tiledlayout(1, 2, 'Padding', 'compact', 'TileSpacing', 'compact');
nexttile;
imshow(originalCrop);
hold on;
drawContourIfPresent(manualCrop, 'r', 1.8);
hold off;
title('原图 + manualLashMask');
nexttile;
imagesc(double(mapCrop));
axis image off;
caxis([0, limit]);
colorbar;
hold on;
drawContourIfPresent(manualCrop, 'r', 1.5);
hold off;
title(label, 'Interpreter', 'none');
exportgraphics(figureHandle, path, 'Resolution', 170);
close(figureHandle);
end

function writeDeltaFigure(originalCrop, manualCrop, deltaCrop, label, path, limit)
figureHandle = figure('Visible', 'off', 'Color', 'white', ...
    'Position', [100, 100, 1500, 600]);
tiledlayout(1, 2, 'Padding', 'compact', 'TileSpacing', 'compact');
nexttile;
imshow(originalCrop);
hold on;
drawContourIfPresent(manualCrop, 'r', 1.8);
hold off;
title('原图 + manualLashMask');
nexttile;
imagesc(abs(double(deltaCrop)));
axis image off;
caxis([0, limit]);
colorbar;
hold on;
drawContourIfPresent(manualCrop, 'r', 1.5);
hold off;
title(label, 'Interpreter', 'none');
exportgraphics(figureHandle, path, 'Resolution', 170);
close(figureHandle);
end

function writeMetricsCsv(path, metrics, assessment, supportChangedPixels, ...
        hardMaskChanges, lashCoreChanges, hardFinalChanges)
row = struct( ...
    'issue', '08.5', ...
    'caseName', 'requiresVisualReview', ...
    'numericAssessment', assessment.case, ...
    'manualLashPixels', metrics.manualLashPixels, ...
    'candidateLashProtectionMean', metrics.candidateLashProtection.mean, ...
    'upperBoundLashProtectionMean', metrics.upperBoundLashProtection.mean, ...
    'candidateLashProtectionSupportPixels', metrics.candidateSupportPixels, ...
    'upperBoundLashProtectionSupportPixels', metrics.upperBoundSupportPixels, ...
    'supportChangedPixels', supportChangedPixels, ...
    'upperBoundLashStrengthRaisedPixels', metrics.upperBoundLashStrengthRaisedPixels, ...
    'upperBoundLashStrengthIncreaseTotal', metrics.upperBoundLashStrengthIncreaseTotal, ...
    'baselineRepairFineAbsActionSum', metrics.baselineRepairFineAbsAction.sum, ...
    'candidateRepairFineAbsActionSum', metrics.candidateRepairFineAbsAction.sum, ...
    'upperBoundRepairFineAbsActionSum', metrics.upperBoundRepairFineAbsAction.sum, ...
    'repairFineCandidateReduction', metrics.repairFineCandidateReduction, ...
    'repairFineUpperBoundReduction', metrics.repairFineUpperBoundReduction, ...
    'baselineRepairMidAbsActionSum', metrics.baselineRepairMidAbsAction.sum, ...
    'candidateRepairMidAbsActionSum', metrics.candidateRepairMidAbsAction.sum, ...
    'upperBoundRepairMidAbsActionSum', metrics.upperBoundRepairMidAbsAction.sum, ...
    'repairMidCandidateReduction', metrics.repairMidCandidateReduction, ...
    'repairMidUpperBoundReduction', metrics.repairMidUpperBoundReduction, ...
    'baselineFinalRgbDistanceToOriginalMean', ...
        metrics.baselineFinalRgbDistanceToOriginal.mean, ...
    'candidateFinalRgbDistanceToOriginalMean', ...
        metrics.candidateFinalRgbDistanceToOriginal.mean, ...
    'upperBoundFinalRgbDistanceToOriginalMean', ...
        metrics.upperBoundFinalRgbDistanceToOriginal.mean, ...
    'baselineFinalLuminanceDistanceToOriginalMean', ...
        metrics.baselineFinalLuminanceDistanceToOriginal.mean, ...
    'candidateFinalLuminanceDistanceToOriginalMean', ...
        metrics.candidateFinalLuminanceDistanceToOriginal.mean, ...
    'upperBoundFinalLuminanceDistanceToOriginalMean', ...
        metrics.upperBoundFinalLuminanceDistanceToOriginal.mean, ...
    'candidateUpperOutsideBrowEyeFinalRgbChangeSum', ...
        metrics.candidateUpperOutsideBrowEyeFinalRgbChange.sum, ...
    'candidateUpperOutsideBrowEyeFinalRgbChangeMean', ...
        metrics.candidateUpperOutsideBrowEyeFinalRgbChange.mean, ...
    'candidateUpperOutsideBrowEyeFinalLuminanceChangeSum', ...
        metrics.candidateUpperOutsideBrowEyeFinalLuminanceChange.sum, ...
    'candidateUpperOutsideBrowEyeFinalLuminanceChangeMean', ...
        metrics.candidateUpperOutsideBrowEyeFinalLuminanceChange.mean, ...
    'hardProtectionBaselineToCandidateChangedPixels', ...
        hardMaskChanges.baselineToCandidate, ...
    'hardProtectionBaselineToUpperBoundChangedPixels', ...
        hardMaskChanges.baselineToUpperBound, ...
    'hardProtectionCandidateToUpperBoundChangedPixels', ...
        hardMaskChanges.candidateToUpperBound, ...
    'lashCoreBaselineToCandidateChangedPixels', ...
        lashCoreChanges.baselineToCandidate, ...
    'lashCoreBaselineToUpperBoundChangedPixels', ...
        lashCoreChanges.baselineToUpperBound, ...
    'lashCoreCandidateToUpperBoundChangedPixels', ...
        lashCoreChanges.candidateToUpperBound, ...
    'baselineHardProtectedFinalRgbChangedCount', hardFinalChanges.baseline, ...
    'candidateHardProtectedFinalRgbChangedCount', hardFinalChanges.candidate, ...
    'upperBoundHardProtectedFinalRgbChangedCount', hardFinalChanges.upperBound);
writetable(struct2table(row), path);
end

function diagnostics = makeUpperTextureDiagnostics(base, upperEyeDetail, upperLash)
diagnostics = base;
diagnostics.eyeDetailProtection = upperEyeDetail;
diagnostics.lashProtection = upperLash;
end

function pathsValue = normalizeOutputFolder(value)
if nargin < 1 || isempty(value)
    value = fullfile(tempdir, ...
        'image_beauty_issue08_5_lash_protection_sufficiency_upper_bound_20260919');
end
pathsValue = normalizeText(value, 'outputFolder');
if ~isfolder(pathsValue)
    mkdir(pathsValue);
end
end

function mask = makeRoiMask(roi, imageSize)
mask = false(imageSize(1), imageSize(2));
x1 = roi(1);
y1 = roi(2);
x2 = min(imageSize(2), roi(1) + roi(3) - 1);
y2 = min(imageSize(1), roi(2) + roi(4) - 1);
mask(y1:y2, x1:x2) = true;
end

function image = cropImage(image, box)
x1 = box(1);
y1 = box(2);
x2 = min(size(image, 2), box(1) + box(3) - 1);
y2 = min(size(image, 1), box(2) + box(4) - 1);
if ismatrix(image)
    image = image(y1:y2, x1:x2);
else
    image = image(y1:y2, x1:x2, :);
end
end

function drawContourIfPresent(mask, color, lineWidth)
if any(mask(:))
    contour(mask, [0.5, 0.5], color, 'LineWidth', lineWidth);
end
end

function value = readDiagnosticArray(value, imageSize, name)
if (~isnumeric(value) && ~islogical(value)) || ~isreal(value) || ...
        ~isequal(size(value), imageSize) || any(~isfinite(value(:)))
    error('diagnoseLashProtectionSufficiencyUpperBound:InvalidDiagnosticArray', ...
        '%s 尺寸或取值无效。', name);
end
value = double(value);
end

function validateArray(value, imageSize, name)
if (~isnumeric(value) && ~islogical(value)) || ~isreal(value) || ...
        ~isequal(size(value), imageSize) || any(~isfinite(value(:)))
    error('diagnoseLashProtectionSufficiencyUpperBound:InvalidArray', ...
        '%s 尺寸或取值无效。', name);
end
end

function validateMask(value, imageSize, name)
validateArray(value, imageSize, name);
if any(double(value(:)) < 0) || any(double(value(:)) > 1)
    error('diagnoseLashProtectionSufficiencyUpperBound:InvalidMask', ...
        'Mask %s 的取值不在 [0,1]。', name);
end
end

function value = normalizeText(value, name)
if isstring(value) && isscalar(value)
    value = char(value);
end
if ~ischar(value) || size(value, 1) ~= 1
    error('diagnoseLashProtectionSufficiencyUpperBound:InvalidText', ...
        '%s 必须是单行文本。', name);
end
end

function valid = isValidStrength(value)
valid = isnumeric(value) && isreal(value) && isscalar(value) && ...
    isfinite(value) && value >= 0 && value <= 100;
end
