function [summary, diagnostics] = diagnoseResidualEyelashLoss( ...
        imagePath, outputFolder, options)
%DIAGNOSERESIDUALEYELASHLOSS 归因 77 固定样本的睫毛残留损失。
%   本入口只做离线诊断，不修改生产算法、Context、runtimeCache 或
%   公共字段。它在一次无缓存生产调用中取得同一组 frequency、Mask、
%   Smoothing 和 Repair 产物，再生成纯 Fine/Mid 频率探针：
%   A 原图，B Smoothing-only，C Smoothing+Repair。
%
%   典型用法：
%       [summary, diagnostics] = diagnoseResidualEyelashLoss( ...
%           'E:\image_beauty\人脸\人脸\77.png', tempdir, struct( ...
%           'lashRoi', [102 248 177 48]));
%
%   lashRoi 必须由原图人工固定，不能由任何待验证的 Detector 或
%   Protection Mask 自动生成。所有局部图均使用同一 lashRoiBounds。

projectRoot = fileparts(fileparts(mfilename('fullpath')));
if nargin < 2
    outputFolder = [];
end
if nargin < 3
    options = [];
end
options = normalizeOptions(options, projectRoot);

productionRoot = resolveProductionRoot(options.productionRoot);
addpath(fullfile(productionRoot, 'src'), '-begin');
contract = beautyPipelineContract();
validateProductionContract(contract);

if nargin < 1 || isempty(imagePath)
    error('diagnoseResidualEyelashLoss:MissingImage', ...
        '必须提供固定 77.png 的输入图像路径。');
end
inputImage = readInputImage(imagePath);
imageSize = [size(inputImage, 1), size(inputImage, 2)];
validateRoiBounds(options.faceBox, imageSize, 'faceBox');
validateRoiBounds(options.browEyeRoi, imageSize, 'browEyeRoi');
for index = 1:size(options.lashRoi, 1)
    validateRoiBounds(options.lashRoi(index, :), imageSize, ...
        sprintf('lashRoi(%d)', index));
end
if options.strictFixed77
    validateFixed77Fixture(inputImage, options.faceBox);
end

outputFolder = normalizeOutputFolder(outputFolder);
if ~isfolder(outputFolder)
    mkdir(outputFolder);
end

loaded = loadBaselineContext(options.baselinePath);
sourceContext = stripDerivedContext(loaded.context);
params = struct('smoothingStrength', options.smoothingStrength, ...
    'whiteningStrength', options.whiteningStrength);

% 只运行一次当前生产链，并且显式剥离旧 runtimeCache 与派生 Mask。
% 这样所有频率、Mask、Smoothing 和 Repair 结果都来自同一运行。
[productionOutput, productionDiagnostics] = beautifyImage( ...
    inputImage, params, options.faceBox, sourceContext);
validateProductionDiagnostics(productionDiagnostics, imageSize);
if isfield(productionDiagnostics, 'reusedRuntimeCache') && ...
        productionDiagnostics.reusedRuntimeCache
    error('diagnoseResidualEyelashLoss:RuntimeCacheReused', ...
        '诊断意外复用了 runtimeCache，不能满足同一次运行核对。');
end

frequency = makeOriginalFrequency(productionDiagnostics, inputImage, ...
    options.faceBox, imageSize);
smoothedFrequency = productionDiagnostics.smoothingResult;
repairedFrequency = productionDiagnostics.repairResult;
validateStageConsistency(frequency, smoothedFrequency, repairedFrequency, ...
    productionDiagnostics, imageSize);

inputYcbcr = rgb2ycbcr(im2double(inputImage));
inputLuminance = inputYcbcr(:, :, 1);
originalReconstruction = double(frequency.base) + ...
    double(frequency.mid) + double(frequency.fine);
originalReconstructionMaxError = max(abs(originalReconstruction(:) - ...
    inputLuminance(:)));
if originalReconstructionMaxError > options.reconstructionTolerance
    error('diagnoseResidualEyelashLoss:FrequencyReconstructionMismatch', ...
        '原始 frequency 重建误差 %.17g 超出容差 %.17g。', ...
        originalReconstructionMaxError, options.reconstructionTolerance);
end

masks = readIssue08Masks(productionDiagnostics, imageSize);
deltas = struct( ...
    'smoothFine', double(smoothedFrequency.fine) - double(frequency.fine), ...
    'smoothMid', double(smoothedFrequency.mid) - double(frequency.mid), ...
    'repairFine', double(repairedFrequency.fine) - ...
    double(smoothedFrequency.fine), ...
    'repairMid', double(repairedFrequency.mid) - ...
    double(smoothedFrequency.mid));

roiDefinitions = makeRoiDefinitions(options, imageSize);
metrics = makeStageMetrics(roiDefinitions, deltas, masks, options);
probes = makeFrequencyProbes(inputImage, inputYcbcr, frequency, ...
    smoothedFrequency, repairedFrequency);
caseAssessment = classifyCase(metrics, probes, options);

paths = writeArtifacts(outputFolder, inputImage, probes, masks, deltas, ...
    roiDefinitions, metrics, caseAssessment, options);
paths.data = fullfile(outputFolder, 'eyelash_diagnostic_data.mat');

summary = struct( ...
    'completed', true, ...
    'issue', '08.1', ...
    'case', caseAssessment.case, ...
    'caseAssessment', caseAssessment, ...
    'contract', contract, ...
    'imagePath', char(imagePath), ...
    'inputSize', size(inputImage), ...
    'faceBox', double(options.faceBox), ...
    'browEye', double(options.browEyeRoi), ...
    'lashRoi', double(options.lashRoi), ...
    'lashRoiBounds', double(roiDefinitions(2).bounds), ...
    'parameters', params, ...
    'productionRoot', productionRoot, ...
    'baselinePath', options.baselinePath, ...
    'runtimeCacheReused', false, ...
    'sameMaskRun', true, ...
    'baseToneWhiteningDisabled', true, ...
    'originalReconstructionMaxError', originalReconstructionMaxError, ...
    'reconstructionTolerance', options.reconstructionTolerance, ...
    'nonzeroTolerance', options.nonzeroTolerance, ...
    'protectionStrongThreshold', options.protectionStrongThreshold, ...
    'deltaDisplayScale', paths.deltaDisplayScale, ...
    'metrics', metrics, ...
    'paths', paths);

% 返回的 diagnostics 只保存本票所需的完整数组；不把生产输出或旧缓存
% 写回 Context。完整可复核数据另存到系统临时目录的 MAT 文件。
diagnostics = struct( ...
    'contract', contract, ...
    'frequency', frequency, ...
    'smoothedFrequency', smoothedFrequency, ...
    'repairedFrequency', repairedFrequency, ...
    'masks', masks, ...
    'deltas', deltas, ...
    'probes', probes, ...
    'roiDefinitions', roiDefinitions, ...
    'metrics', metrics, ...
    'caseAssessment', caseAssessment, ...
    'productionOutput', productionOutput, ...
    'productionReusedRuntimeCache', false, ...
    'sameMaskRun', true);

diagnosticData = struct( ...
    'summary', summary, ...
    'diagnostics', diagnostics, ...
    'inputImage', inputImage, ...
    'inputYcbcr', inputYcbcr, ...
    'masks', masks, ...
    'deltas', deltas, ...
    'roiDefinitions', roiDefinitions, ...
    'frequency', frequency, ...
    'smoothedFrequency', smoothedFrequency, ...
    'repairedFrequency', repairedFrequency, ...
    'probes', probes);
save(paths.data, 'diagnosticData', '-v7.3');
diagnostics.paths = summary.paths;

fprintf('Issue 08.1 睫毛归因产物：%s\n', outputFolder);
fprintf('lashRoi bounds = [%d %d %d %d]\n', roiDefinitions(2).bounds);
fprintf('Case %s（数值阶段作用量分诊，需结合局部图人工核对）\n', ...
    caseAssessment.case);
fprintf('原始 frequency 重建最大误差：%.17g\n', ...
    originalReconstructionMaxError);
end

function options = normalizeOptions(options, projectRoot)
if nargin < 1 || isempty(options)
    options = struct();
end
if ~isstruct(options) || ~isscalar(options)
    error('diagnoseResidualEyelashLoss:InvalidOptions', ...
        'options 必须是标量结构。');
end
if ~isfield(options, 'faceBox') || isempty(options.faceBox)
    options.faceBox = [95, 79, 286, 372];
end
if ~isfield(options, 'browEyeRoi') || isempty(options.browEyeRoi)
    options.browEyeRoi = [165, 205, 150, 100];
end
if ~isfield(options, 'lashRoi') || isempty(options.lashRoi)
    error('diagnoseResidualEyelashLoss:MissingLashRoi', ...
        ['必须提供依据 77 原图人工确定的固定 lashRoi；不能由 ', ...
        'Detector 或 Protection Mask 生成。']);
end
options.faceBox = validateRoi(options.faceBox, 'faceBox');
options.browEyeRoi = validateRoi(options.browEyeRoi, 'browEyeRoi');
options.lashRoi = validateRoiList(options.lashRoi, 'lashRoi');
if ~isfield(options, 'smoothingStrength')
    options.smoothingStrength = 100;
end
if ~isfield(options, 'whiteningStrength')
    options.whiteningStrength = 15;
end
if ~isValidStrength(options.smoothingStrength) || ...
        ~isValidStrength(options.whiteningStrength)
    error('diagnoseResidualEyelashLoss:InvalidStrength', ...
        '强度必须是 0 到 100 的有限数值标量。');
end
if ~isfield(options, 'productionRoot') || isempty(options.productionRoot)
    options.productionRoot = projectRoot;
end
options.productionRoot = normalizeText(options.productionRoot, ...
    'productionRoot');
if ~isfield(options, 'baselinePath') || isempty(options.baselinePath)
    options.baselinePath = ...
        'C:\Users\JJiio\AppData\Local\Temp\image_beauty_issue02_probe\77_v32_probe.mat';
end
options.baselinePath = normalizeText(options.baselinePath, 'baselinePath');
if ~isfield(options, 'strictFixed77')
    options.strictFixed77 = true;
end
if ~isscalar(options.strictFixed77) || ...
        ~(islogical(options.strictFixed77) || isnumeric(options.strictFixed77))
    error('diagnoseResidualEyelashLoss:InvalidOptions', ...
        'strictFixed77 必须是逻辑标量。');
end
options.strictFixed77 = logical(options.strictFixed77);
if ~isfield(options, 'reconstructionTolerance')
    options.reconstructionTolerance = 1e-12;
end
if ~isfield(options, 'nonzeroTolerance')
    options.nonzeroTolerance = 1e-12;
end
if ~isfield(options, 'protectionStrongThreshold')
    options.protectionStrongThreshold = .50;
end
if ~isfield(options, 'stageActionThreshold')
    options.stageActionThreshold = 1e-4;
end
if ~isscalar(options.reconstructionTolerance) || ...
        ~isfinite(options.reconstructionTolerance) || ...
        options.reconstructionTolerance <= 0 || ...
        ~isscalar(options.nonzeroTolerance) || ...
        ~isfinite(options.nonzeroTolerance) || options.nonzeroTolerance <= 0 || ...
        ~isscalar(options.protectionStrongThreshold) || ...
        ~isfinite(options.protectionStrongThreshold) || ...
        options.protectionStrongThreshold <= 0 || ...
        options.protectionStrongThreshold > 1 || ...
        ~isscalar(options.stageActionThreshold) || ...
        ~isfinite(options.stageActionThreshold) || ...
        options.stageActionThreshold <= 0
    error('diagnoseResidualEyelashLoss:InvalidOptions', ...
        '数值容差、protectionStrongThreshold 或 stageActionThreshold 无效。');
end
options.reconstructionTolerance = double(options.reconstructionTolerance);
options.nonzeroTolerance = double(options.nonzeroTolerance);
options.protectionStrongThreshold = double(options.protectionStrongThreshold);
options.stageActionThreshold = double(options.stageActionThreshold);
end

function root = resolveProductionRoot(root)
if ~isfolder(root) || ~isfolder(fullfile(root, 'src'))
    error('diagnoseResidualEyelashLoss:InvalidProductionRoot', ...
        '生产算法根目录或 src 目录不存在：%s。', root);
end
end

function contract = validateProductionContract(contract)
required = {'schemaVersion', 'algorithmVersion', 'artifactVersion'};
if ~isstruct(contract) || ~isscalar(contract) || ...
        ~all(isfield(contract, required)) || ...
        ~strcmp(char(contract.schemaVersion), '4.0') || ...
        ~strcmp(char(contract.algorithmVersion), 'v3.6') || ...
        ~strcmp(char(contract.artifactVersion), 'v3.2')
    error('diagnoseResidualEyelashLoss:InvalidProductionBaseline', ...
        ['生产依赖必须是当前 v3.6、Schema 4.0、', ...
        '产物 v3.2 基线。']);
end
end

function image = readInputImage(imagePath)
imagePath = normalizeText(imagePath, 'imagePath');
if ~isfile(imagePath)
    error('diagnoseResidualEyelashLoss:MissingImage', ...
        '输入图像不存在：%s。', imagePath);
end
image = imread(imagePath);
if ~isa(image, 'uint8') || ~isreal(image) || ndims(image) ~= 3 || ...
        size(image, 3) ~= 3
    error('diagnoseResidualEyelashLoss:InvalidImage', ...
        '输入图像必须是 uint8 三通道 RGB 图像。');
end
end

function loaded = loadBaselineContext(path)
if ~isfile(path)
    error('diagnoseResidualEyelashLoss:MissingBaseline', ...
        '固定 77 Context 基线不存在：%s。', path);
end
loaded = load(path, 'context');
if ~isfield(loaded, 'context') || ~isstruct(loaded.context) || ...
        ~isscalar(loaded.context)
    error('diagnoseResidualEyelashLoss:InvalidBaseline', ...
        '固定 77 基线缺少有效 context：%s。', path);
end
end

function context = stripDerivedContext(context)
names = {'runtimeCache', 'textureProtectionMask', ...
    'structureProtectionMask', 'whiteningProtectionMask', ...
    'chromaProtectionMask', 'toneProtectionMask', 'strengthMap', ...
    'faceStrengthMap', 'nonFaceStrengthMap', 'protectionMasks'};
present = names(isfield(context, names));
if ~isempty(present)
    context = rmfield(context, present);
end
end

function validateFixed77Fixture(inputImage, faceBox)
if ~isequal(size(inputImage), [450, 512, 3]) || ...
        ~isequal(double(faceBox), [95, 79, 286, 372])
    error('diagnoseResidualEyelashLoss:UnexpectedFixture', ...
        'strictFixed77 要求 77.png 为 450x512x3，faceBox 为 [95 79 286 372]。');
end
end

function validateProductionDiagnostics(value, imageSize)
required = {'beautyMasks', 'mask', 'frequency', 'smoothing', ...
    'smoothingResult', 'repair', 'repairResult', 'reusedRuntimeCache'};
requireFields(value, required, '生产诊断');
if value.reusedRuntimeCache
    error('diagnoseResidualEyelashLoss:RuntimeCacheReused', ...
        '生产诊断标记为 runtimeCache 复用。');
end
requireFields(value.beautyMasks, {'textureProtectionMask', ...
    'hardProtectionMask'}, 'Beauty Masks');
requireFields(value.mask, {'texture'}, 'Mask 诊断');
requireFields(value.mask.texture, {'eyeDetailProtection', ...
    'lashProtection', 'doubleEyelidProtection'}, '纹理诊断');
requireFields(value.frequency, {'base', 'mid', 'fine'}, '频率诊断');
requireFields(value.smoothing, {'fineBefore', 'fineAfter', ...
    'midBefore', 'midAfter'}, 'Smoothing 诊断');
requireFields(value.repair, {'fineBefore', 'fineAfter', ...
    'midBefore', 'midAfter'}, 'Repair 诊断');
for name = {'base', 'mid', 'fine'}
    validateArray(value.frequency.(name{1}), imageSize, ...
        ['frequency.' name{1}]);
end
end

function frequency = makeOriginalFrequency(productionDiagnostics, ...
        inputImage, faceBox, imageSize)
frequency = productionDiagnostics.frequency;
frequency.sourceLuminance = rgb2ycbcr(im2double(inputImage));
frequency.sourceLuminance = frequency.sourceLuminance(:, :, 1);
frequency.imageSize = [imageSize, 3];
frequency.faceBox = double(faceBox);
frequency.faceScale = min(double(faceBox(3:4)));
frequency.reconstructedLuminance = double(frequency.base) + ...
    double(frequency.mid) + double(frequency.fine);
frequency.outputLuminance = frequency.reconstructedLuminance;
frequency.alphaMap = zeros(imageSize);
end

function validateStageConsistency(frequency, smoothed, repaired, diagnostics, ...
        imageSize)
validateFrequencyStruct(smoothed, imageSize, 'Smoothing 结果');
validateFrequencyStruct(repaired, imageSize, 'Repair 结果');
checks = { ...
    max(abs(double(diagnostics.smoothing.fineBefore(:)) - ...
    double(frequency.fine(:)))), ...
    max(abs(double(diagnostics.smoothing.midBefore(:)) - ...
    double(frequency.mid(:)))), ...
    max(abs(double(diagnostics.smoothing.fineAfter(:)) - ...
    double(smoothed.fine(:)))), ...
    max(abs(double(diagnostics.smoothing.midAfter(:)) - ...
    double(smoothed.mid(:)))), ...
    max(abs(double(diagnostics.repair.fineBefore(:)) - ...
    double(smoothed.fine(:)))), ...
    max(abs(double(diagnostics.repair.midBefore(:)) - ...
    double(smoothed.mid(:)))), ...
    max(abs(double(diagnostics.repair.fineAfter(:)) - ...
    double(repaired.fine(:)))), ...
    max(abs(double(diagnostics.repair.midAfter(:)) - ...
    double(repaired.mid(:))))};
if any([checks{:}] > 1e-12)
    error('diagnoseResidualEyelashLoss:StageMismatch', ...
        '生产诊断的频率阶段字段不是同一次运行的连续产物。');
end
end

function validateFrequencyStruct(value, imageSize, label)
requireFields(value, {'base', 'mid', 'fine'}, label);
for name = {'base', 'mid', 'fine'}
    validateArray(value.(name{1}), imageSize, ...
        [label '.' name{1}]);
end
end

function masks = readIssue08Masks(productionDiagnostics, imageSize)
beautyMasks = productionDiagnostics.beautyMasks;
texture = productionDiagnostics.mask.texture;
names = {'textureProtectionMask', 'eyeDetailProtection', ...
    'lashProtection', 'doubleEyelidProtection', 'hardProtectionMask'};
sources = {beautyMasks.textureProtectionMask, ...
    texture.eyeDetailProtection, texture.lashProtection, ...
    texture.doubleEyelidProtection, beautyMasks.hardProtectionMask};
masks = struct();
for index = 1:numel(names)
    validateArray(sources{index}, imageSize, names{index});
    masks.(names{index}) = min(max(double(sources{index}), 0), 1);
end
if isfield(texture, 'lashCore')
    validateArray(texture.lashCore, imageSize, 'lashCore');
    masks.lashCore = logical(texture.lashCore);
else
    masks.lashCore = false(imageSize);
end
end

function roiDefinitions = makeRoiDefinitions(options, imageSize)
browMask = makeRoiMask(options.browEyeRoi, imageSize);
lashMask = false(imageSize);
for index = 1:size(options.lashRoi, 1)
    lashMask = lashMask | makeRoiMask(options.lashRoi(index, :), imageSize);
end
lashBounds = boundsOfRoiList(options.lashRoi);
roiDefinitions = repmat(struct('name', '', 'boxes', [], ...
    'bounds', [], 'mask', false(imageSize)), 2, 1);
roiDefinitions(1) = struct('name', 'browEye', ...
    'boxes', options.browEyeRoi, 'bounds', options.browEyeRoi, ...
    'mask', browMask);
roiDefinitions(2) = struct('name', 'lashRoi', ...
    'boxes', options.lashRoi, 'bounds', lashBounds, 'mask', lashMask);
end

function metrics = makeStageMetrics(roiDefinitions, deltas, masks, options)
metricTemplate = emptyMetricRow();
metrics = repmat(metricTemplate, numel(roiDefinitions), 1);
for index = 1:numel(roiDefinitions)
    definition = roiDefinitions(index);
    mask = definition.mask;
    row = emptyMetricRow();
    row.roi = definition.name;
    row.roiX = definition.bounds(1);
    row.roiY = definition.bounds(2);
    row.roiWidth = definition.bounds(3);
    row.roiHeight = definition.bounds(4);
    row.roiPixels = nnz(mask);
    [row.smoothingFineMeanAbs, row.smoothingFineMaxAbs, ...
        row.smoothingFineNonzeroFraction] = summarizeDelta( ...
        deltas.smoothFine, mask, options.nonzeroTolerance);
    [row.smoothingMidMeanAbs, row.smoothingMidMaxAbs, ...
        row.smoothingMidNonzeroFraction] = summarizeDelta( ...
        deltas.smoothMid, mask, options.nonzeroTolerance);
    [row.repairFineMeanAbs, row.repairFineMaxAbs, ...
        row.repairFineNonzeroFraction] = summarizeDelta( ...
        deltas.repairFine, mask, options.nonzeroTolerance);
    [row.repairMidMeanAbs, row.repairMidMaxAbs, ...
        row.repairMidNonzeroFraction] = summarizeDelta( ...
        deltas.repairMid, mask, options.nonzeroTolerance);
    row.smoothingActionMeanAbs = row.smoothingFineMeanAbs + ...
        row.smoothingMidMeanAbs;
    row.smoothingActionMaxAbs = max(row.smoothingFineMaxAbs, ...
        row.smoothingMidMaxAbs);
    row.repairActionMeanAbs = row.repairFineMeanAbs + ...
        row.repairMidMeanAbs;
    row.repairActionMaxAbs = max(row.repairFineMaxAbs, ...
        row.repairMidMaxAbs);
    row.smoothingActionNonzeroFraction = fractionOfAny( ...
        abs(deltas.smoothFine) > options.nonzeroTolerance | ...
        abs(deltas.smoothMid) > options.nonzeroTolerance, mask);
    row.repairActionNonzeroFraction = fractionOfAny( ...
        abs(deltas.repairFine) > options.nonzeroTolerance | ...
        abs(deltas.repairMid) > options.nonzeroTolerance, mask);
    row.textureProtectionMean = meanOn(masks.textureProtectionMask, mask);
    row.textureProtectionMax = maxOn(masks.textureProtectionMask, mask);
    row.textureProtectionNonzeroFraction = fractionOfAny( ...
        masks.textureProtectionMask > options.nonzeroTolerance, mask);
    row.textureProtectionStrongFraction = fractionOfAny( ...
        masks.textureProtectionMask >= options.protectionStrongThreshold, mask);
    row.eyeDetailProtectionMean = meanOn(masks.eyeDetailProtection, mask);
    row.eyeDetailProtectionMax = maxOn(masks.eyeDetailProtection, mask);
    row.eyeDetailProtectionNonzeroFraction = fractionOfAny( ...
        masks.eyeDetailProtection > options.nonzeroTolerance, mask);
    row.eyeDetailProtectionStrongFraction = fractionOfAny( ...
        masks.eyeDetailProtection >= options.protectionStrongThreshold, mask);
    row.lashProtectionMean = meanOn(masks.lashProtection, mask);
    row.lashProtectionMax = maxOn(masks.lashProtection, mask);
    row.lashProtectionNonzeroFraction = fractionOfAny( ...
        masks.lashProtection > options.nonzeroTolerance, mask);
    row.lashProtectionStrongFraction = fractionOfAny( ...
        masks.lashProtection >= options.protectionStrongThreshold, mask);
    row.doubleEyelidProtectionMean = meanOn( ...
        masks.doubleEyelidProtection, mask);
    row.doubleEyelidProtectionMax = maxOn( ...
        masks.doubleEyelidProtection, mask);
    row.doubleEyelidProtectionNonzeroFraction = fractionOfAny( ...
        masks.doubleEyelidProtection > options.nonzeroTolerance, mask);
    row.doubleEyelidProtectionStrongFraction = fractionOfAny( ...
        masks.doubleEyelidProtection >= options.protectionStrongThreshold, mask);
    row.hardProtectionFraction = fractionOfAny( ...
        masks.hardProtectionMask >= .999, mask);
    row.lashCoreFraction = fractionOfAny(masks.lashCore, mask);
    metrics(index) = row;
end
end

function row = emptyMetricRow()
row = struct( ...
    'roi', '', 'roiX', 0, 'roiY', 0, 'roiWidth', 0, 'roiHeight', 0, ...
    'roiPixels', 0, ...
    'smoothingFineMeanAbs', NaN, 'smoothingFineMaxAbs', NaN, ...
    'smoothingFineNonzeroFraction', NaN, ...
    'smoothingMidMeanAbs', NaN, 'smoothingMidMaxAbs', NaN, ...
    'smoothingMidNonzeroFraction', NaN, ...
    'repairFineMeanAbs', NaN, 'repairFineMaxAbs', NaN, ...
    'repairFineNonzeroFraction', NaN, ...
    'repairMidMeanAbs', NaN, 'repairMidMaxAbs', NaN, ...
    'repairMidNonzeroFraction', NaN, ...
    'smoothingActionMeanAbs', NaN, 'smoothingActionMaxAbs', NaN, ...
    'smoothingActionNonzeroFraction', NaN, ...
    'repairActionMeanAbs', NaN, 'repairActionMaxAbs', NaN, ...
    'repairActionNonzeroFraction', NaN, ...
    'textureProtectionMean', NaN, 'textureProtectionMax', NaN, ...
    'textureProtectionNonzeroFraction', NaN, ...
    'textureProtectionStrongFraction', NaN, ...
    'eyeDetailProtectionMean', NaN, 'eyeDetailProtectionMax', NaN, ...
    'eyeDetailProtectionNonzeroFraction', NaN, ...
    'eyeDetailProtectionStrongFraction', NaN, ...
    'lashProtectionMean', NaN, 'lashProtectionMax', NaN, ...
    'lashProtectionNonzeroFraction', NaN, ...
    'lashProtectionStrongFraction', NaN, ...
    'doubleEyelidProtectionMean', NaN, ...
    'doubleEyelidProtectionMax', NaN, ...
    'doubleEyelidProtectionNonzeroFraction', NaN, ...
    'doubleEyelidProtectionStrongFraction', NaN, ...
    'hardProtectionFraction', NaN, 'lashCoreFraction', NaN);
end

function probes = makeFrequencyProbes(inputImage, inputYcbcr, frequency, ...
        smoothed, repaired)
originalY = double(frequency.base) + double(frequency.mid) + ...
    double(frequency.fine);
smoothingOnlyY = double(frequency.base) + double(smoothed.mid) + ...
    double(smoothed.fine);
smoothingPlusRepairY = double(frequency.base) + ...
    double(repaired.mid) + double(repaired.fine);
probes = struct( ...
    'original', [], ...
    'smoothingOnly', rebuildRgbWithOriginalChroma( ...
    smoothingOnlyY, inputYcbcr), ...
    'smoothingPlusRepair', rebuildRgbWithOriginalChroma( ...
    smoothingPlusRepairY, inputYcbcr), ...
    'originalLuminance', originalY, ...
    'smoothingOnlyLuminance', smoothingOnlyY, ...
    'smoothingPlusRepairLuminance', smoothingPlusRepairY, ...
    'smoothingOnlyLuminanceDelta', smoothingOnlyY - originalY, ...
    'repairLuminanceDelta', smoothingPlusRepairY - smoothingOnlyY, ...
    'baseStageApplied', false, ...
    'toneStageApplied', false, ...
    'whiteningStageApplied', false, ...
    'originalChromaPreserved', true);
% A 直接使用输入原图，不经过任何转换，作为真实视觉参考。
probes.original = inputImage;
end

function image = rebuildRgbWithOriginalChroma(luminance, inputYcbcr)
ycbcr = cat(3, min(max(double(luminance), 0), 1), ...
    inputYcbcr(:, :, 2), inputYcbcr(:, :, 3));
image = im2uint8(ycbcr2rgb(ycbcr));
end

function assessment = classifyCase(metrics, probes, options)
lash = metrics(strcmp({metrics.roi}, 'lashRoi'));
smoothingAction = lash.smoothingActionMeanAbs;
repairAction = lash.repairActionMeanAbs;
% 这里的阈值只用于“阶段作用量分诊”，不是视觉损伤分数。
meaningful = options.stageActionThreshold;
if smoothingAction < meaningful && repairAction < meaningful
    caseName = 'D';
    reason = 'Fine/Mid 两阶段在固定 lashRoi 内均未达到作用量分诊阈值。';
elseif smoothingAction >= meaningful && repairAction < meaningful
    caseName = 'A';
    reason = 'Smoothing 作用量达到阈值，Repair 作用量未达到阈值。';
elseif smoothingAction < meaningful && repairAction >= meaningful
    caseName = 'B';
    reason = 'Smoothing 作用量未达到阈值，Repair 作用量达到阈值。';
elseif repairAction <= .35 * smoothingAction
    caseName = 'A';
    reason = '两阶段均有作用，但 Repair 作用量不超过 Smoothing 的 35%。';
elseif smoothingAction <= .35 * repairAction
    caseName = 'B';
    reason = '两阶段均有作用，但 Smoothing 作用量不超过 Repair 的 35%。';
else
    caseName = 'C';
    reason = 'Smoothing 与 Repair 的作用量均达到阈值，且不存在明显单阶段主导。';
end
lashBounds = [lash.roiX, lash.roiY, lash.roiWidth, lash.roiHeight];
lashMask = makeRoiMask(lashBounds, ...
    [size(probes.original, 1), size(probes.original, 2)]);
assessment = struct( ...
    'case', caseName, ...
    'reason', reason, ...
    'classificationBasis', '固定 lashRoi 的 Fine/Mid 阶段作用量分诊；不是 RGB 损伤分数。', ...
    'smoothingActionMeanAbs', smoothingAction, ...
    'repairActionMeanAbs', repairAction, ...
    'stageActionThreshold', meaningful, ...
    'repairToSmoothingRatio', safeRatio(repairAction, smoothingAction), ...
    'smoothingProbeLuminanceChangeMean', mean(abs( ...
    probes.smoothingOnlyLuminanceDelta(lashMask))), ...
    'repairProbeLuminanceChangeMean', mean(abs( ...
    probes.repairLuminanceDelta(lashMask))));
end

function paths = writeArtifacts(outputFolder, inputImage, probes, masks, ...
        deltas, roiDefinitions, metrics, assessment, options)
paths = struct();
paths.outputFolder = outputFolder;
paths.deltaDisplayScale = max([1e-6, ...
    max(abs(deltas.smoothFine(roiDefinitions(2).mask))), ...
    max(abs(deltas.smoothMid(roiDefinitions(2).mask))), ...
    max(abs(deltas.repairFine(roiDefinitions(2).mask))), ...
    max(abs(deltas.repairMid(roiDefinitions(2).mask)))]);

lashBounds = roiDefinitions(2).bounds;
writePng(cropImage(inputImage, lashBounds), ...
    fullfile(outputFolder, 'eyelash_original.png'));
writePng(cropImage(probes.smoothingOnly, lashBounds), ...
    fullfile(outputFolder, 'eyelash_smoothing_only.png'));
writePng(cropImage(probes.smoothingPlusRepair, lashBounds), ...
    fullfile(outputFolder, 'eyelash_smoothing_plus_repair.png'));
writeMaskCrop(masks.textureProtectionMask, lashBounds, ...
    fullfile(outputFolder, 'eyelash_texture_protection.png'));
writeMaskCrop(masks.eyeDetailProtection, lashBounds, ...
    fullfile(outputFolder, 'eyelash_eye_detail_protection.png'));
writeMaskCrop(masks.lashProtection, lashBounds, ...
    fullfile(outputFolder, 'eyelash_lash_protection.png'));
writeMaskCrop(masks.doubleEyelidProtection, lashBounds, ...
    fullfile(outputFolder, 'eyelash_double_eyelid_protection.png'));
writeMaskCrop(masks.hardProtectionMask, lashBounds, ...
    fullfile(outputFolder, 'eyelash_hard_protection.png'));
writeDeltaCrop(deltas.smoothFine, lashBounds, paths.deltaDisplayScale, ...
    fullfile(outputFolder, 'eyelash_smoothing_fine_delta.png'));
writeDeltaCrop(deltas.smoothMid, lashBounds, paths.deltaDisplayScale, ...
    fullfile(outputFolder, 'eyelash_smoothing_mid_delta.png'));
writeDeltaCrop(deltas.repairFine, lashBounds, paths.deltaDisplayScale, ...
    fullfile(outputFolder, 'eyelash_repair_fine_delta.png'));
writeDeltaCrop(deltas.repairMid, lashBounds, paths.deltaDisplayScale, ...
    fullfile(outputFolder, 'eyelash_repair_mid_delta.png'));

metricsPath = fullfile(outputFolder, 'eyelash_stage_metrics.csv');
writetable(struct2table(metrics), metricsPath);
paths.stageMetrics = metricsPath;
coveragePath = fullfile(outputFolder, 'eyelash_coverage_comparison.png');
writeCoverageFigure(inputImage, masks, deltas, roiDefinitions, ...
    paths.deltaDisplayScale, options, coveragePath);
paths.coverageComparison = coveragePath;
stagePath = fullfile(outputFolder, 'eyelash_stage_comparison.png');
writeStageFigure(inputImage, probes, roiDefinitions, stagePath);
paths.stageComparison = stagePath;
paths.original = fullfile(outputFolder, 'eyelash_original.png');
paths.smoothingOnly = fullfile(outputFolder, 'eyelash_smoothing_only.png');
paths.smoothingPlusRepair = fullfile(outputFolder, ...
    'eyelash_smoothing_plus_repair.png');
paths.textureProtection = fullfile(outputFolder, ...
    'eyelash_texture_protection.png');
paths.eyeDetailProtection = fullfile(outputFolder, ...
    'eyelash_eye_detail_protection.png');
paths.lashProtection = fullfile(outputFolder, ...
    'eyelash_lash_protection.png');
paths.doubleEyelidProtection = fullfile(outputFolder, ...
    'eyelash_double_eyelid_protection.png');
paths.hardProtection = fullfile(outputFolder, ...
    'eyelash_hard_protection.png');
paths.smoothingFineDelta = fullfile(outputFolder, ...
    'eyelash_smoothing_fine_delta.png');
paths.smoothingMidDelta = fullfile(outputFolder, ...
    'eyelash_smoothing_mid_delta.png');
paths.repairFineDelta = fullfile(outputFolder, ...
    'eyelash_repair_fine_delta.png');
paths.repairMidDelta = fullfile(outputFolder, ...
    'eyelash_repair_mid_delta.png');
paths.case = assessment.case;
end

function writeCoverageFigure(inputImage, masks, deltas, roiDefinitions, ...
        deltaScale, options, outputPath)
box = roiDefinitions(2).bounds;
original = cropImage(inputImage, box);
mapNames = {'textureProtectionMask', 'eyeDetailProtection', ...
    'lashProtection', 'doubleEyelidProtection', 'hardProtectionMask'};
mapLabels = {'textureProtectionMask', 'eyeDetailProtection', ...
    'lashProtection', 'doubleEyelidProtection', 'hardProtectionMask'};
deltaValues = {deltas.smoothFine, deltas.smoothMid, ...
    deltas.repairFine, deltas.repairMid};
deltaLabels = {'Smoothing Fine delta', 'Smoothing Mid delta', ...
    'Repair Fine delta', 'Repair Mid delta'};
figureHandle = figure('Visible', 'off', 'Color', 'white', ...
    'Position', [100, 100, 1900, 1200]);
tiledlayout(3, 4, 'Padding', 'compact', 'TileSpacing', 'compact');
nexttile;
imshow(original);
title(sprintf('原图 lashRoi [%d %d %d %d]', box));
for index = 1:numel(mapNames)
    nexttile;
    map = cropImage(masks.(mapNames{index}), box);
    imagesc(map);
    axis image off;
    clim([0, 1]);
    colorbar;
    title(mapLabels{index}, 'Interpreter', 'none');
end
for index = 1:numel(deltaValues)
    nexttile;
    map = abs(cropImage(deltaValues{index}, box));
    imagesc(map);
    axis image off;
    clim([0, deltaScale]);
    colorbar;
    title(deltaLabels{index}, 'Interpreter', 'none');
end
nexttile;
imshow(original);
hold on;
colors = {'r', 'g', 'b', 'y', 'm'};
for index = 1:numel(mapNames)
    map = cropImage(masks.(mapNames{index}), box);
    contour(map >= options.protectionStrongThreshold, [0.5, 0.5], ...
        colors{index}, 'LineWidth', 1.0);
end
hold off;
title('原图叠加保护边界');
legend(mapLabels, 'Location', 'southoutside', 'Interpreter', 'none');
exportgraphics(figureHandle, outputPath, 'Resolution', 140);
close(figureHandle);
end

function writeStageFigure(inputImage, probes, roiDefinitions, outputPath)
box = roiDefinitions(2).bounds;
figureHandle = figure('Visible', 'off', 'Color', 'white', ...
    'Position', [100, 100, 1500, 520]);
tiledlayout(1, 3, 'Padding', 'compact', 'TileSpacing', 'compact');
nexttile; imshow(cropImage(inputImage, box)); title('A 原图');
nexttile; imshow(cropImage(probes.smoothingOnly, box)); ...
    title('B Smoothing-only');
nexttile; imshow(cropImage(probes.smoothingPlusRepair, box)); ...
    title('C Smoothing + Repair');
exportgraphics(figureHandle, outputPath, 'Resolution', 160);
close(figureHandle);
end

function folder = normalizeOutputFolder(folder)
if nargin < 1 || isempty(folder)
    folder = fullfile(tempdir, ...
        'image_beauty_issue08_1_eyelash_20260918');
end
folder = normalizeText(folder, 'outputFolder');
if ~isfolder(fileparts(folder)) && ~isempty(fileparts(folder))
    mkdir(fileparts(folder));
end
end

function value = normalizeText(value, name)
if isstring(value) && isscalar(value)
    value = char(value);
end
if ~ischar(value) || size(value, 1) ~= 1
    error('diagnoseResidualEyelashLoss:InvalidText', ...
        '%s 必须是单行文本。', name);
end
end

function value = validateRoi(value, name)
if ~isnumeric(value) || ~isreal(value) || ~isequal(size(value), [1, 4]) || ...
        any(~isfinite(value)) || any(value ~= round(value)) || ...
        value(1) < 1 || value(2) < 1 || any(value(3:4) <= 0)
    error('diagnoseResidualEyelashLoss:InvalidLashRoi', ...
        '%s 必须是正整数 [x y width height]。', name);
end
value = double(value);
end

function value = validateRoiList(value, name)
if ~isnumeric(value) || ~isreal(value) || size(value, 2) ~= 4 || ...
        isempty(value) || any(~isfinite(value(:))) || ...
        any(value(:) ~= round(value(:))) || any(value(:, 1:2) < 1, 'all') || ...
        any(value(:, 3:4) <= 0, 'all')
    error('diagnoseResidualEyelashLoss:InvalidLashRoi', ...
        '%s 必须是一个或多个正整数 [x y width height]。', name);
end
value = double(value);
end

function validateRoiBounds(roi, imageSize, name)
if roi(1) + roi(3) - 1 > imageSize(2) || ...
        roi(2) + roi(4) - 1 > imageSize(1)
    error('diagnoseResidualEyelashLoss:InvalidLashRoi', ...
        '%s 超出输入图像范围。', name);
end
end

function bounds = boundsOfRoiList(rois)
x1 = min(rois(:, 1));
y1 = min(rois(:, 2));
x2 = max(rois(:, 1) + rois(:, 3) - 1);
y2 = max(rois(:, 2) + rois(:, 4) - 1);
bounds = [x1, y1, x2 - x1 + 1, y2 - y1 + 1];
end

function mask = makeRoiMask(roi, imageSize)
mask = false(imageSize(1), imageSize(2));
x1 = roi(1);
y1 = roi(2);
x2 = roi(1) + roi(3) - 1;
y2 = roi(2) + roi(4) - 1;
mask(y1:y2, x1:x2) = true;
end

function [meanAbs, maximum, nonzeroFraction] = summarizeDelta(delta, mask, tolerance)
values = abs(double(delta(mask)));
if isempty(values)
    meanAbs = NaN;
    maximum = NaN;
    nonzeroFraction = NaN;
else
    meanAbs = mean(values);
    maximum = max(values);
    nonzeroFraction = nnz(values > tolerance) / numel(values);
end
end

function value = meanOn(data, mask)
values = double(data(mask));
if isempty(values)
    value = NaN;
else
    value = mean(values);
end
end

function value = maxOn(data, mask)
values = double(data(mask));
if isempty(values)
    value = NaN;
else
    value = max(values);
end
end

function value = fractionOfAny(data, mask)
values = logical(data(mask));
if isempty(values)
    value = NaN;
else
    value = nnz(values) / numel(values);
end
end

function value = safeRatio(numerator, denominator)
if denominator <= eps
    if numerator <= eps
        value = 0;
    else
        value = Inf;
    end
else
    value = numerator / denominator;
end
end

function image = cropImage(image, box)
x1 = box(1);
y1 = box(2);
x2 = min(size(image, 2), box(1) + box(3) - 1);
y2 = min(size(image, 1), box(2) + box(4) - 1);
if ismatrix(image)
    image = image(y1:y2, x1:x2);
else
    image = image(y1:y2, x1:x2, :);
end
end

function writeMaskCrop(mask, box, path)
writePng(uint8(min(max(round(255 * double(cropImage(mask, box))), 0), 255)), ...
    path);
end

function writeDeltaCrop(delta, box, scale, path)
value = abs(double(cropImage(delta, box))) / max(scale, eps);
writePng(uint8(min(max(round(255 * value), 0), 255)), path);
end

function writePng(image, path)
if ~isa(image, 'uint8')
    image = uint8(min(max(round(double(image)), 0), 255));
end
imwrite(image, path);
end

function validateArray(value, imageSize, name)
if (~isnumeric(value) && ~islogical(value)) || ~isreal(value) || ...
        ~isequal(size(value), imageSize) || any(~isfinite(value(:)))
    error('diagnoseResidualEyelashLoss:InvalidDiagnosticArray', ...
        '%s 尺寸或取值无效。', name);
end
end

function requireFields(value, names, label)
if ~isstruct(value) || ~isscalar(value) || ~all(isfield(value, names))
    error('diagnoseResidualEyelashLoss:MissingDiagnosticField', ...
        '%s 缺少必需字段。', label);
end
end

function valid = isValidStrength(value)
valid = isnumeric(value) && isreal(value) && isscalar(value) && ...
    isfinite(value) && value >= 0 && value <= 100;
end
