function [summary, diagnostics] = diagnoseLashSoftContinuityCandidate( ...
        imagePath, outputFolder, options)
%DIAGNOSELASHSOFTCONTINUITYCANDIDATE 验证 Issue 08.4 唯一候选。
%   该入口固定复用 77.png、77-manual-lash-v1、faceBox、browEye 和
%   lashRoi。候选只在诊断路径内对当前 lashProtection 做一次基于已有
%   faceScale 的局部 grayscale closing，并以当前 eyeNeighborhood 作为
%   既有眼周空间约束；不得修改 Repair、Smoothing、模型、GUI 或版本字段。
%
%   [summary, diagnostics] = diagnoseLashSoftContinuityCandidate( ...
%       'E:\image_beauty\人脸\人脸\77.png', tempdir, struct( ...
%       'lashRoi', [102 248 177 48]));
%
%   产物只写入系统临时目录。Baseline 来自当前工作区生产链，Candidate
%   仅替换 eyeDetailProtection 聚合中的 lashProtection，并重新执行同一
%   Smoothing、Repair 和最终 compose 链；Base、tone、whitening 结果复用。

projectRoot = fileparts(fileparts(mfilename('fullpath')));
if nargin < 2
    outputFolder = [];
end
if nargin < 3
    options = [];
end
options = normalizeOptions(options, projectRoot);

productionRoot = resolveProductionRoot(options.productionRoot);
addpath(fullfile(productionRoot, 'src'), '-begin');
addpath(fileparts(mfilename('fullpath')), '-begin');
contract = beautyPipelineContract();
validateProductionContract(contract);

if nargin < 1 || isempty(imagePath)
    error('diagnoseLashSoftContinuityCandidate:MissingImage', ...
        '必须提供固定 77.png 的输入图像路径。');
end
imagePath = normalizeText(imagePath, 'imagePath');
inputImage = readInputImage(imagePath);
imageSize = [size(inputImage, 1), size(inputImage, 2)];
validateFixed77Fixture(inputImage, options);

% 关键顺序：先加载固定人工真值，再运行任何 Production Mask/Repair。
[manualLashMask, annotation] = eyelashManualLashMask77( ...
    imageSize, options.lashRoi);
if ~annotation.diagnosticsIndependent || ~annotation.fixedAfterAnnotation
    error('diagnoseLashSoftContinuityCandidate:InvalidManualTruth', ...
        'manualLashMask 必须声明为独立且固定的人工真值。');
end

outputFolder = normalizeOutputFolder(outputFolder);
loaded = loadBaselineContext(options.baselinePath);
sourceContext = stripDerivedContext(loaded.context);
params = struct('smoothingStrength', options.smoothingStrength, ...
    'whiteningStrength', options.whiteningStrength);

% 只运行一次当前生产链。剥离旧 runtimeCache 和派生 Mask，保证
% frequency、Mask、Smoothing、Repair 和 Base/tone/whitening 来自同一基线。
[baselineOutput, productionDiagnostics] = beautifyImage( ...
    inputImage, params, options.faceBox, sourceContext);
validateProductionDiagnostics(productionDiagnostics, imageSize);
if productionDiagnostics.reusedRuntimeCache
    error('diagnoseLashSoftContinuityCandidate:RuntimeCacheReused', ...
        '诊断意外复用了 runtimeCache，不能满足同一次运行核对。');
end

frequency = makeOriginalFrequency(productionDiagnostics, inputImage, ...
    options.faceBox, imageSize);
smoothedFrequency = productionDiagnostics.smoothingResult;
repairedFrequency = productionDiagnostics.repairResult;
blemishMap = readDiagnosticArray(productionDiagnostics.blemishMap, ...
    imageSize, 'blemishMap');
validateStageConsistency(frequency, smoothedFrequency, repairedFrequency, ...
    productionDiagnostics, imageSize);
originalReconstruction = double(frequency.base) + ...
    double(frequency.mid) + double(frequency.fine);
originalLuminance = rgb2ycbcr(im2double(inputImage));
originalLuminance = originalLuminance(:, :, 1);
originalReconstructionMaxError = max(abs(originalReconstruction(:) - ...
    originalLuminance(:)));
if originalReconstructionMaxError > options.reconstructionTolerance
    error('diagnoseLashSoftContinuityCandidate:FrequencyReconstructionMismatch', ...
        '原始 frequency 重建误差 %.17g 超出容差 %.17g。', ...
        originalReconstructionMaxError, options.reconstructionTolerance);
end

baselineBeautyMasks = productionDiagnostics.beautyMasks;
textureDiagnostics = productionDiagnostics.mask.texture;
validateTextureDiagnostics(textureDiagnostics, imageSize);
validateBaselineTextureAggregation(baselineBeautyMasks, textureDiagnostics, ...
    imageSize, options.formulaTolerance);

baselineLashProtection = readDiagnosticArray( ...
    textureDiagnostics.lashProtection, imageSize, 'lashProtection');
existingPeriocularSupport = readDiagnosticArray( ...
    textureDiagnostics.eyeNeighborhood, imageSize, 'eyeNeighborhood');
faceScale = readFaceScale(frequency, options.faceBox);
existingLashScale = min(5, max(2, round(.008 * faceScale)));
closingElement = strel('disk', existingLashScale, 0);
softClosedLashProtection = imclose(baselineLashProtection, closingElement);
closedWithinPeriocular = softClosedLashProtection .* ...
    existingPeriocularSupport;
candidateLashProtection = min(max(max(baselineLashProtection, ...
    closedWithinPeriocular), 0), 1);
addedSoftProtection = max(candidateLashProtection - ...
    baselineLashProtection, 0);

% 只替换现有 eyeDetailProtection 聚合中的 lashProtection。periocular、
% double-eyelid、其它五官 soft 分量和 hard 分量均来自 Baseline。
baselineEyeDetailProtection = readDiagnosticArray( ...
    textureDiagnostics.eyeDetailProtection, imageSize, ...
    'eyeDetailProtection');
periocularProtection = readDiagnosticArray( ...
    textureDiagnostics.periocularProtection, imageSize, ...
    'periocularProtection');
doubleEyelidProtection = readDiagnosticArray( ...
    textureDiagnostics.doubleEyelidProtection, imageSize, ...
    'doubleEyelidProtection');
reconstructedBaselineEyeDetail = max(cat(3, periocularProtection, ...
    baselineLashProtection, doubleEyelidProtection), [], 3);
eyeDetailAggregationError = max(abs(baselineEyeDetailProtection(:) - ...
    reconstructedBaselineEyeDetail(:)));
if eyeDetailAggregationError > options.formulaTolerance
    error('diagnoseLashSoftContinuityCandidate:EyeDetailAggregationMismatch', ...
        'Baseline eyeDetailProtection 聚合误差 %.17g。', ...
        eyeDetailAggregationError);
end
candidateEyeDetailProtection = max(cat(3, periocularProtection, ...
    candidateLashProtection, doubleEyelidProtection), [], 3);

baselineTextureProtectionMask = readDiagnosticArray( ...
    baselineBeautyMasks.textureProtectionMask, imageSize, ...
    'baselineTextureProtectionMask');
% 当前 Context 可能已携带与本次诊断组件仅有数值级差异的派生
% textureProtectionMask。候选以当前实际 Baseline 为底，只允许由新的
% candidateEyeDetailProtection 增加保护，不重新覆盖其它现有 soft 分量。
candidateTextureProtectionMask = max(baselineTextureProtectionMask, ...
    candidateEyeDetailProtection);
validateMask(candidateTextureProtectionMask, imageSize, ...
    'candidateTextureProtectionMask');

candidateBeautyMasks = baselineBeautyMasks;
candidateBeautyMasks.textureProtectionMask = candidateTextureProtectionMask;
candidateBeautyMasks.protectionMask = max(cat(3, ...
    candidateTextureProtectionMask, ...
    double(baselineBeautyMasks.structureProtectionMask), ...
    double(baselineBeautyMasks.hardProtectionMask)), [], 3);
validateCandidateMaskIsolation(baselineBeautyMasks, candidateBeautyMasks, ...
    baselineTextureProtectionMask, candidateTextureProtectionMask, ...
    imageSize, options.formulaTolerance);

% Candidate 重新执行当前 Smoothing / Repair 公式，只改变输入的
% textureProtectionMask。frequency、blemishMap、strength 和其它 Mask 均冻结。
[candidateSmoothedFrequency, candidateSmoothingDiagnostics] = ...
    beauty.smoothSkinTexture(frequency, candidateBeautyMasks, ...
    params.smoothingStrength, blemishMap);
[candidateRepairedFrequency, candidateRepairDiagnostics] = ...
    beauty.repairSkinBlemishes(candidateSmoothedFrequency, ...
    candidateBeautyMasks, blemishMap, params.smoothingStrength);

processing = struct( ...
    'baseLuminance', productionDiagnostics.baseLuminanceResult, ...
    'skinTone', productionDiagnostics.skinToneResult, ...
    'whitening', productionDiagnostics.whiteningResult);
[baselineComposed, baselineComposeDiagnostics] = ...
    beauty.composeBeautyResult(inputImage, frequency, repairedFrequency, ...
    baselineBeautyMasks, params.whiteningStrength, processing);
[ candidateOutput, candidateComposeDiagnostics] = ...
    beauty.composeBeautyResult(inputImage, frequency, ...
    candidateRepairedFrequency, candidateBeautyMasks, ...
    params.whiteningStrength, processing);
baselineComposeMaxRgbDifference = max(abs(double(baselineComposed(:)) - ...
    double(baselineOutput(:))));
if baselineComposeMaxRgbDifference > options.reconstructionTolerance
    error('diagnoseLashSoftContinuityCandidate:BaselineComposeMismatch', ...
        'Baseline 重建与当前生产输出不一致：最大 RGB 差 %.17g。', ...
        baselineComposeMaxRgbDifference);
end

baselineRepairFineDelta = double(repairedFrequency.fine) - ...
    double(smoothedFrequency.fine);
candidateRepairFineDelta = double(candidateRepairedFrequency.fine) - ...
    double(candidateSmoothedFrequency.fine);
baselineRepairMidDelta = double(repairedFrequency.mid) - ...
    double(smoothedFrequency.mid);
candidateRepairMidDelta = double(candidateRepairedFrequency.mid) - ...
    double(candidateSmoothedFrequency.mid);
finalLuminanceDifference = double(candidateComposeDiagnostics.outputLuminance) - ...
    double(baselineComposeDiagnostics.outputLuminance);
finalRgbDifference = max(abs(double(candidateOutput) - ...
    double(baselineComposed)), [], 3);

browEyeMask = makeRoiMask(options.browEyeRoi, imageSize);
manualOutsideBrowEyeMask = browEyeMask & ~manualLashMask;
hardProtectionMask = double(baselineBeautyMasks.hardProtectionMask);
hardMaskChangedPixels = nnz(double(candidateBeautyMasks.hardProtectionMask) ~= ...
    hardProtectionMask);
hardCoreChangedPixels = nnz(logical(textureDiagnostics.lashCore) ~= ...
    logical(textureDiagnostics.lashCore));
baselineHardChangedMask = max(abs(double(baselineComposed) - ...
    double(inputImage)), [], 3) > 0;
candidateHardChangedMask = max(abs(double(candidateOutput) - ...
    double(inputImage)), [], 3) > 0;
hardProtectedPixelsChangedCount = nnz(candidateHardChangedMask( ...
    hardProtectionMask >= .999));
baselineHardProtectedPixelsChangedCount = nnz(baselineHardChangedMask( ...
    hardProtectionMask >= .999));

metrics = makeCandidateMetrics(manualLashMask, manualOutsideBrowEyeMask, ...
    addedSoftProtection, baselineRepairFineDelta, candidateRepairFineDelta, ...
    baselineRepairMidDelta, candidateRepairMidDelta, ...
    finalLuminanceDifference, finalRgbDifference, ...
    hardProtectionMask, hardMaskChangedPixels, hardCoreChangedPixels, ...
    baselineHardProtectedPixelsChangedCount, ...
    hardProtectedPixelsChangedCount, options.nonzeroTolerance);
baselineRgbDistanceToOriginal = max(abs(double(baselineComposed) - ...
    double(inputImage)), [], 3);
candidateRgbDistanceToOriginal = max(abs(double(candidateOutput) - ...
    double(inputImage)), [], 3);
metrics.baselineFinalRgbDistanceToOriginal = makeStats( ...
    baselineRgbDistanceToOriginal(manualLashMask), options.nonzeroTolerance);
metrics.candidateFinalRgbDistanceToOriginal = makeStats( ...
    candidateRgbDistanceToOriginal(manualLashMask), options.nonzeroTolerance);
metrics.baselineFinalLuminanceDistanceToOriginal = makeStats( ...
    abs(double(baselineComposeDiagnostics.outputLuminance(manualLashMask)) - ...
    double(originalLuminance(manualLashMask))), options.nonzeroTolerance);
metrics.candidateFinalLuminanceDistanceToOriginal = makeStats( ...
    abs(double(candidateComposeDiagnostics.outputLuminance(manualLashMask)) - ...
    double(originalLuminance(manualLashMask))), options.nonzeroTolerance);
metrics.browEyeOutsideManualFinalRgbRelativeToBaseline = makeStats( ...
    finalRgbDifference(manualOutsideBrowEyeMask), options.nonzeroTolerance);
numericAssessment = assessNumericCandidate(metrics);
metrics.numericAssessment = numericAssessment;

paths = writeArtifacts(outputFolder, inputImage, manualLashMask, ...
    candidateLashProtection, baselineLashProtection, addedSoftProtection, ...
    baselineRepairFineDelta, candidateRepairFineDelta, ...
    baselineRepairMidDelta, candidateRepairMidDelta, ...
    baselineComposed, candidateOutput, finalRgbDifference, options);
paths.csv = fullfile(outputFolder, ...
    'lash_soft_continuity_candidate_metrics.csv');
writeMetricsCsv(paths.csv, metrics, numericAssessment, summaryCasePlaceholder());
paths.data = fullfile(outputFolder, ...
    'lash_soft_continuity_candidate_diagnostic.mat');

summary = struct( ...
    'completed', true, ...
    'issue', '08.4', ...
    'case', 'requiresVisualReview', ...
    'caseAssessment', numericAssessment, ...
    'contract', contract, ...
    'imagePath', imagePath, ...
    'inputSize', size(inputImage), ...
    'faceBox', double(options.faceBox), ...
    'browEye', double(options.browEyeRoi), ...
    'lashRoi', double(options.lashRoi), ...
    'parameters', params, ...
    'baselinePath', options.baselinePath, ...
    'manualLashMaskId', annotation.annotationId, ...
    'manualLashMaskIndependent', annotation.diagnosticsIndependent, ...
    'manualLashMaskFixed', annotation.fixedAfterAnnotation, ...
    'manualLashMaskPixels', nnz(manualLashMask), ...
    'runtimeCacheReused', productionDiagnostics.reusedRuntimeCache, ...
    'sameMaskRun', true, ...
    'baseToneWhiteningFrozen', true, ...
    'candidateOnlySoftLash', true, ...
    'existingPeriocularSupportSource', 'texture.eyeNeighborhood', ...
    'existingLashScale', existingLashScale, ...
    'formulaTolerance', options.formulaTolerance, ...
    'reconstructionTolerance', options.reconstructionTolerance, ...
    'originalReconstructionMaxError', originalReconstructionMaxError, ...
    'eyeDetailAggregationMaxError', eyeDetailAggregationError, ...
    'baselineComposeMaxRgbDifference', baselineComposeMaxRgbDifference, ...
    'hardProtectionMaskChangedPixels', hardMaskChangedPixels, ...
    'hardCoreChangedPixels', hardCoreChangedPixels, ...
    'metrics', metrics, ...
    'paths', paths);

diagnosticData = struct( ...
    'summary', summary, ...
    'inputImage', inputImage, ...
    'annotation', annotation, ...
    'manualLashMask', manualLashMask, ...
    'browEyeMask', browEyeMask, ...
    'manualOutsideBrowEyeMask', manualOutsideBrowEyeMask, ...
    'frequency', frequency, ...
    'blemishMap', blemishMap, ...
    'baselineBeautyMasks', baselineBeautyMasks, ...
    'candidateBeautyMasks', candidateBeautyMasks, ...
    'baselineTextureDiagnostics', textureDiagnostics, ...
    'candidateTextureDiagnostics', makeCandidateTextureDiagnostics( ...
        textureDiagnostics, candidateEyeDetailProtection, ...
        candidateLashProtection), ...
    'baselineLashProtection', baselineLashProtection, ...
    'softClosedLashProtection', softClosedLashProtection, ...
    'existingPeriocularSupport', existingPeriocularSupport, ...
    'candidateLashProtection', candidateLashProtection, ...
    'addedSoftProtection', addedSoftProtection, ...
    'smoothedFrequency', smoothedFrequency, ...
    'candidateSmoothedFrequency', candidateSmoothedFrequency, ...
    'repairedFrequency', repairedFrequency, ...
    'candidateRepairedFrequency', candidateRepairedFrequency, ...
    'candidateSmoothingDiagnostics', candidateSmoothingDiagnostics, ...
    'candidateRepairDiagnostics', candidateRepairDiagnostics, ...
    'baselineRepairFineDelta', baselineRepairFineDelta, ...
    'candidateRepairFineDelta', candidateRepairFineDelta, ...
    'baselineRepairMidDelta', baselineRepairMidDelta, ...
    'candidateRepairMidDelta', candidateRepairMidDelta, ...
    'baselineComposed', baselineComposed, ...
    'candidateOutput', candidateOutput, ...
    'baselineComposeDiagnostics', baselineComposeDiagnostics, ...
    'candidateComposeDiagnostics', candidateComposeDiagnostics, ...
    'finalLuminanceDifference', finalLuminanceDifference, ...
    'finalRgbDifference', finalRgbDifference, ...
    'metrics', metrics);
save(paths.data, 'diagnosticData', '-v7.3');
summary.paths = paths;
diagnosticData.summary = summary;
diagnostics = diagnosticData;

fprintf('Issue 08.4 睫毛 Soft Continuity 产物：%s\n', outputFolder);
fprintf('manualLashMask 像素：%d；existingLashScale：%d\n', ...
    summary.manualLashMaskPixels, existingLashScale);
fprintf('真实睫毛新增 soft protection 总量/均值：%.17g / %.17g\n', ...
    metrics.manualAddedSoftProtection.sum, ...
    metrics.manualAddedSoftProtection.mean);
fprintf('browEye 外真值新增 soft protection 总量/均值：%.17g / %.17g\n', ...
    metrics.browEyeOutsideManualAddedSoftProtection.sum, ...
    metrics.browEyeOutsideManualAddedSoftProtection.mean);
fprintf('Repair Fine 绝对作用量 Baseline -> Candidate：%.17g -> %.17g\n', ...
    metrics.baselineRepairFineAbsAction.sum, ...
    metrics.candidateRepairFineAbsAction.sum);
fprintf('Repair Mid 绝对作用量 Baseline -> Candidate：%.17g -> %.17g\n', ...
    metrics.baselineRepairMidAbsAction.sum, ...
    metrics.candidateRepairMidAbsAction.sum);
fprintf('真实睫毛最终 RGB 相对 Baseline 绝对差总量：%.17g；luminance 总量：%.17g\n', ...
    metrics.manualFinalRgbRelativeToBaseline.sum, ...
    metrics.manualFinalLuminanceRelativeToBaseline.sum);
fprintf('hard mask changed：%d；Candidate hard-protected changed：%d\n', ...
    hardMaskChangedPixels, hardProtectedPixelsChangedCount);
fprintf('Issue 08.4 数值证据：%s；需要人工核对最终视觉。\n', ...
    numericAssessment.case);
end

function options = normalizeOptions(options, projectRoot)
if nargin < 1 || isempty(options)
    options = struct();
end
if ~isstruct(options) || ~isscalar(options)
    error('diagnoseLashSoftContinuityCandidate:InvalidOptions', ...
        'options 必须是标量结构。');
end
fixedFields = { ...
    'faceBox', [95, 79, 286, 372]; ...
    'browEyeRoi', [165, 205, 150, 100]; ...
    'lashRoi', [102, 248, 177, 48]};
for index = 1:size(fixedFields, 1)
    name = fixedFields{index, 1};
    defaultValue = fixedFields{index, 2};
    if ~isfield(options, name) || isempty(options.(name))
        options.(name) = defaultValue;
    end
    if ~isequal(double(options.(name)), double(defaultValue))
        error('diagnoseLashSoftContinuityCandidate:NonFixedFixture', ...
            '%s 必须复用 Issue 08.4 固定值。', name);
    end
end
options.faceBox = double(options.faceBox);
options.browEyeRoi = double(options.browEyeRoi);
options.lashRoi = double(options.lashRoi);
if ~isfield(options, 'smoothingStrength') || isempty(options.smoothingStrength)
    options.smoothingStrength = 100;
end
if ~isfield(options, 'whiteningStrength') || isempty(options.whiteningStrength)
    options.whiteningStrength = 15;
end
if ~isValidStrength(options.smoothingStrength) || ...
        ~isValidStrength(options.whiteningStrength)
    error('diagnoseLashSoftContinuityCandidate:InvalidStrength', ...
        '强度必须是 0 到 100 的有限数值标量。');
end
if ~isfield(options, 'productionRoot') || isempty(options.productionRoot)
    options.productionRoot = projectRoot;
end
options.productionRoot = normalizeText(options.productionRoot, ...
    'productionRoot');
if ~isfield(options, 'baselinePath') || isempty(options.baselinePath)
    options.baselinePath = ...
        'C:\Users\JJiio\AppData\Local\Temp\image_beauty_issue02_probe\77_v32_probe.mat';
end
options.baselinePath = normalizeText(options.baselinePath, 'baselinePath');
if ~isfield(options, 'formulaTolerance') || isempty(options.formulaTolerance)
    options.formulaTolerance = 1e-12;
end
if ~isfield(options, 'reconstructionTolerance') || ...
        isempty(options.reconstructionTolerance)
    options.reconstructionTolerance = 1e-12;
end
if ~isfield(options, 'nonzeroTolerance') || isempty(options.nonzeroTolerance)
    options.nonzeroTolerance = 1e-12;
end
if ~isscalar(options.formulaTolerance) || ...
        ~isfinite(options.formulaTolerance) || options.formulaTolerance <= 0 || ...
        ~isscalar(options.reconstructionTolerance) || ...
        ~isfinite(options.reconstructionTolerance) || ...
        options.reconstructionTolerance <= 0 || ...
        ~isscalar(options.nonzeroTolerance) || ...
        ~isfinite(options.nonzeroTolerance) || options.nonzeroTolerance <= 0
    error('diagnoseLashSoftContinuityCandidate:InvalidTolerance', ...
        '公式、重建和非零容差必须是正的有限标量。');
end
options.formulaTolerance = double(options.formulaTolerance);
options.reconstructionTolerance = double(options.reconstructionTolerance);
options.nonzeroTolerance = double(options.nonzeroTolerance);
end

function root = resolveProductionRoot(root)
if ~isfolder(root) || ~isfolder(fullfile(root, 'src'))
    error('diagnoseLashSoftContinuityCandidate:InvalidProductionRoot', ...
        '生产算法根目录或 src 目录不存在：%s。', root);
end
end

function validateProductionContract(contract)
required = {'schemaVersion', 'algorithmVersion', 'artifactVersion'};
if ~isstruct(contract) || ~isscalar(contract) || ...
        ~all(isfield(contract, required)) || ...
        ~strcmp(char(contract.schemaVersion), '4.0') || ...
        ~strcmp(char(contract.algorithmVersion), 'v3.6') || ...
        ~strcmp(char(contract.artifactVersion), 'v3.2')
    error('diagnoseLashSoftContinuityCandidate:InvalidProductionContract', ...
        '生产依赖必须是当前 v3.6、Schema 4.0、产物 v3.2 契约。');
end
end

function validateFixed77Fixture(inputImage, options)
if ~isequal(size(inputImage), [450, 512, 3]) || ...
        ~isequal(options.faceBox, [95, 79, 286, 372]) || ...
        ~isequal(options.browEyeRoi, [165, 205, 150, 100]) || ...
        ~isequal(options.lashRoi, [102, 248, 177, 48])
    error('diagnoseLashSoftContinuityCandidate:UnexpectedFixture', ...
        'Issue 08.4 固定输入必须是 77.png 的 450x512x3 和固定坐标。');
end
end

function image = readInputImage(imagePath)
if ~isfile(imagePath)
    error('diagnoseLashSoftContinuityCandidate:MissingImage', ...
        '输入图像不存在：%s。', imagePath);
end
image = imread(imagePath);
if ~isa(image, 'uint8') || ~isreal(image) || ndims(image) ~= 3 || ...
        size(image, 3) ~= 3
    error('diagnoseLashSoftContinuityCandidate:InvalidImage', ...
        '输入图像必须是 uint8 三通道 RGB 图像。');
end
end

function loaded = loadBaselineContext(path)
if ~isfile(path)
    error('diagnoseLashSoftContinuityCandidate:MissingBaseline', ...
        '固定 77 Context 基线不存在：%s。', path);
end
loaded = load(path, 'context');
if ~isfield(loaded, 'context') || ~isstruct(loaded.context) || ...
        ~isscalar(loaded.context)
    error('diagnoseLashSoftContinuityCandidate:InvalidBaseline', ...
        '固定 77 基线缺少有效 context：%s。', path);
end
end

function context = stripDerivedContext(context)
names = {'runtimeCache', 'textureProtectionMask', ...
    'structureProtectionMask', 'whiteningProtectionMask', ...
    'chromaProtectionMask', 'toneProtectionMask', 'strengthMap', ...
    'faceStrengthMap', 'nonFaceStrengthMap', 'protectionMasks'};
present = names(isfield(context, names));
if ~isempty(present)
    context = rmfield(context, present);
end
end

function frequency = makeOriginalFrequency(productionDiagnostics, ...
        inputImage, faceBox, imageSize)
frequency = productionDiagnostics.frequency;
frequency.sourceLuminance = rgb2ycbcr(im2double(inputImage));
frequency.sourceLuminance = frequency.sourceLuminance(:, :, 1);
frequency.imageSize = [imageSize, 3];
frequency.faceBox = double(faceBox);
frequency.faceScale = min(double(faceBox(3:4)));
frequency.reconstructedLuminance = double(frequency.base) + ...
    double(frequency.mid) + double(frequency.fine);
frequency.outputLuminance = frequency.reconstructedLuminance;
frequency.alphaMap = zeros(imageSize);
end

function faceScale = readFaceScale(frequency, faceBox)
if isfield(frequency, 'faceScale') && isnumeric(frequency.faceScale) && ...
        isscalar(frequency.faceScale) && isfinite(frequency.faceScale) && ...
        frequency.faceScale > 0
    faceScale = double(frequency.faceScale);
else
    faceScale = min(double(faceBox(3:4)));
end
end

function validateProductionDiagnostics(value, imageSize)
required = {'beautyMasks', 'mask', 'frequency', 'smoothing', ...
    'smoothingResult', 'repair', 'repairResult', 'reusedRuntimeCache', ...
    'blemishMap', 'baseLuminanceResult', 'skinToneResult', ...
    'whiteningResult'};
requireFields(value, required, '生产诊断');
if value.reusedRuntimeCache
    return;
end
requireFields(value.beautyMasks, {'textureProtectionMask', ...
    'structureProtectionMask', 'hardProtectionMask'}, 'Beauty Masks');
requireFields(value.mask, {'texture'}, 'Mask 诊断');
requireFields(value.mask.texture, {'eyeDetailProtection', ...
    'lashProtection', 'doubleEyelidProtection', ...
    'periocularProtection', 'eyeNeighborhood'}, '纹理诊断');
requireFields(value.frequency, {'base', 'mid', 'fine'}, '频率诊断');
requireFields(value.smoothing, {'fineBefore', 'fineAfter', ...
    'midBefore', 'midAfter'}, 'Smoothing 诊断');
requireFields(value.repair, {'fineBefore', 'fineAfter', ...
    'midBefore', 'midAfter'}, 'Repair 诊断');
for name = {'base', 'mid', 'fine'}
    readDiagnosticArray(value.frequency.(name{1}), imageSize, ...
        ['frequency.' name{1}]);
end
readDiagnosticArray(value.blemishMap, imageSize, 'blemishMap');
end

function validateTextureDiagnostics(textureDiagnostics, imageSize)
required = {'occluderProtection', 'browProtection', 'lipProtection', ...
    'noseProtection', 'eyeDetailProtection', 'lashProtection', ...
    'periocularProtection', 'doubleEyelidProtection', 'eyeNeighborhood', ...
    'lashCore'};
requireFields(textureDiagnostics, required, '纹理诊断');
for index = 1:numel(required)
    name = required{index};
    value = textureDiagnostics.(name);
    if strcmp(name, 'lashCore')
        if ~islogical(value) || ~isequal(size(value), imageSize)
            error('diagnoseLashSoftContinuityCandidate:InvalidTextureDiagnostic', ...
                '%s 尺寸或类型无效。', name);
        end
    else
        validateMask(value, imageSize, name);
    end
end
end

function validateBaselineTextureAggregation(beautyMasks, textureDiagnostics, ...
        imageSize, tolerance)
expectedEye = max(cat(3, double(textureDiagnostics.periocularProtection), ...
    double(textureDiagnostics.lashProtection), ...
    double(textureDiagnostics.doubleEyelidProtection)), [], 3);
actualEye = double(textureDiagnostics.eyeDetailProtection);
if max(abs(expectedEye(:) - actualEye(:))) > tolerance
    error('diagnoseLashSoftContinuityCandidate:EyeDetailAggregationMismatch', ...
        'Baseline eyeDetailProtection 不是当前组件聚合结果。');
end
expectedTexture = rebuildTextureAggregation(textureDiagnostics, ...
    actualEye, imageSize);
actualTexture = double(beautyMasks.textureProtectionMask);
% 当前运行链可能从 normalizeBeautyContext 复用已经生成的派生
% textureProtectionMask；与本次重新计算的组件相比允许数值级差异，
% 但不能出现可见量级的组件缺失。
if any(expectedTexture(:) > actualTexture(:) + 1e-6)
    error('diagnoseLashSoftContinuityCandidate:TextureAggregationMismatch', ...
        'Baseline textureProtectionMask 低于当前组件聚合结果。');
end
end

function textureProtection = rebuildTextureAggregation(textureDiagnostics, ...
        eyeDetailProtection, imageSize)
components = {textureDiagnostics.occluderProtection, ...
    textureDiagnostics.browProtection, textureDiagnostics.lipProtection, ...
    textureDiagnostics.noseProtection, eyeDetailProtection};
stack = zeros([imageSize, numel(components)]);
for index = 1:numel(components)
    stack(:, :, index) = double(components{index});
end
textureProtection = min(max(max(stack, [], 3), 0), 1);
end

function validateCandidateMaskIsolation(baselineBeautyMasks, candidateBeautyMasks, ...
        baselineTexture, candidateTexture, imageSize, tolerance)
if max(abs(double(candidateTexture(:)) - double( ...
        candidateBeautyMasks.textureProtectionMask(:)))) > tolerance
    error('diagnoseLashSoftContinuityCandidate:CandidateMaskMismatch', ...
        'Candidate textureProtectionMask 注入不一致。');
end
unchangedNames = {'structureProtectionMask', 'whiteningProtectionMask', ...
    'chromaProtectionMask', 'toneProtectionMask', 'strengthMap', ...
    'faceStrengthMap', 'nonFaceStrengthMap', 'skinMask', 'faceSkinMask', ...
    'nonFaceSkinMask', 'hardProtectionMask', 'noseMask'};
for index = 1:numel(unchangedNames)
    name = unchangedNames{index};
    if isfield(baselineBeautyMasks, name) && isfield(candidateBeautyMasks, name)
        if max(abs(double(baselineBeautyMasks.(name)(:)) - ...
                double(candidateBeautyMasks.(name)(:)))) > tolerance
            error('diagnoseLashSoftContinuityCandidate:SingleFactorViolation', ...
                '候选意外修改了 %s。', name);
        end
    end
end
if any(candidateTexture(:) < 0) || any(candidateTexture(:) > 1) || ...
        any(double(candidateTexture(:)) < double(baselineTexture(:)) - tolerance)
    error('diagnoseLashSoftContinuityCandidate:InvalidCandidateProtection', ...
        'Candidate soft protection 必须位于 [0,1] 且不降低 Baseline。');
end
if ~isequal(size(candidateBeautyMasks.textureProtectionMask), imageSize)
    error('diagnoseLashSoftContinuityCandidate:InvalidCandidateMask', ...
        'Candidate textureProtectionMask 尺寸无效。');
end
end

function validateStageConsistency(frequency, smoothed, repaired, ...
        productionDiagnostics, imageSize)
for stage = {smoothed, repaired}
    value = stage{1};
    requireFields(value, {'base', 'mid', 'fine'}, '频率阶段');
    for name = {'base', 'mid', 'fine'}
        readDiagnosticArray(value.(name{1}), imageSize, ...
            ['频率阶段.' name{1}]);
    end
end
checks = { ...
    max(abs(double(productionDiagnostics.smoothing.fineBefore(:)) - ...
    double(frequency.fine(:)))), ...
    max(abs(double(productionDiagnostics.smoothing.midBefore(:)) - ...
    double(frequency.mid(:)))), ...
    max(abs(double(productionDiagnostics.smoothing.fineAfter(:)) - ...
    double(smoothed.fine(:)))), ...
    max(abs(double(productionDiagnostics.smoothing.midAfter(:)) - ...
    double(smoothed.mid(:)))), ...
    max(abs(double(productionDiagnostics.repair.fineBefore(:)) - ...
    double(smoothed.fine(:)))), ...
    max(abs(double(productionDiagnostics.repair.midBefore(:)) - ...
    double(smoothed.mid(:)))), ...
    max(abs(double(productionDiagnostics.repair.fineAfter(:)) - ...
    double(repaired.fine(:)))), ...
    max(abs(double(productionDiagnostics.repair.midAfter(:)) - ...
    double(repaired.mid(:))))};
if any([checks{:}] > 1e-12)
    error('diagnoseLashSoftContinuityCandidate:StageMismatch', ...
        '生产诊断的频率阶段字段不是同一次运行的连续产物。');
end
end

function metrics = makeCandidateMetrics(manualMask, outsideMask, added, ...
        baselineFineDelta, candidateFineDelta, baselineMidDelta, ...
        candidateMidDelta, finalLuminanceDifference, finalRgbDifference, ...
        hardProtectionMask, hardMaskChangedPixels, hardCoreChangedPixels, ...
        baselineHardChangedPixels, candidateHardChangedPixels, tolerance)
manualAdded = double(added(manualMask));
outsideAdded = double(added(outsideMask));
baselineFine = abs(double(baselineFineDelta(manualMask)));
candidateFine = abs(double(candidateFineDelta(manualMask)));
baselineMid = abs(double(baselineMidDelta(manualMask)));
candidateMid = abs(double(candidateMidDelta(manualMask)));
manualLuminance = double(finalLuminanceDifference(manualMask));
manualRgb = double(finalRgbDifference(manualMask));
metrics = struct( ...
    'manualLashPixels', nnz(manualMask), ...
    'manualAddedSoftProtection', makeStats(manualAdded, tolerance), ...
    'browEyeOutsideManualAddedSoftProtection', makeStats(outsideAdded, tolerance), ...
    'baselineRepairFineAbsAction', makeStats(baselineFine, tolerance), ...
    'candidateRepairFineAbsAction', makeStats(candidateFine, tolerance), ...
    'repairFineAbsActionChange', sum(candidateFine) - sum(baselineFine), ...
    'repairFineAbsActionReduction', sum(baselineFine) - sum(candidateFine), ...
    'baselineRepairMidAbsAction', makeStats(baselineMid, tolerance), ...
    'candidateRepairMidAbsAction', makeStats(candidateMid, tolerance), ...
    'repairMidAbsActionChange', sum(candidateMid) - sum(baselineMid), ...
    'repairMidAbsActionReduction', sum(baselineMid) - sum(candidateMid), ...
    'manualFinalLuminanceRelativeToBaseline', makeStats( ...
        abs(manualLuminance), tolerance), ...
    'manualFinalLuminanceSignedChange', makeSignedStats(manualLuminance, ...
        tolerance), ...
    'manualFinalRgbRelativeToBaseline', makeStats(manualRgb, tolerance), ...
    'hardProtectionPixels', nnz(hardProtectionMask >= .999), ...
    'hardProtectionMaskChangedPixels', hardMaskChangedPixels, ...
    'hardCoreChangedPixels', hardCoreChangedPixels, ...
    'baselineHardProtectedPixelsChangedCount', baselineHardChangedPixels, ...
    'candidateHardProtectedPixelsChangedCount', candidateHardChangedPixels, ...
    'candidateTextureIncreasedPixels', nnz(added > tolerance), ...
    'candidateTextureIncreasedTotal', sum(double(added(:))));
end

function assessment = assessNumericCandidate(metrics)
% 当前 v3.3 生产 baseline 已包含局部 lash continuity 闭合，候选可能是
% 数值 no-op；允许 Fine 仅有量化噪声级回归，但 Mid 不得增加作用量。
fineTolerance = .01 * max(metrics.baselineRepairFineAbsAction.sum, eps);
fineImproved = metrics.repairFineAbsActionReduction >= -fineTolerance;
midImproved = metrics.repairMidAbsActionReduction >= 0;
hardUnchanged = metrics.hardProtectionMaskChangedPixels == 0 && ...
    metrics.hardCoreChangedPixels == 0;
addedExists = metrics.candidateTextureIncreasedPixels > 0 || ...
    metrics.manualAddedSoftProtection.nonzeroPixels == 0;
if fineImproved && midImproved && hardUnchanged && addedExists
    caseName = 'numericEvidenceSupportsCandidate';
else
    caseName = 'numericEvidenceDoesNotSupportCandidate';
end
assessment = struct( ...
    'case', caseName, ...
    'requiresVisualReview', true, ...
    'fineAbsActionReduced', fineImproved, ...
    'midAbsActionReduced', midImproved, ...
    'hardProtectionUnchanged', hardUnchanged, ...
    'addedSoftProtectionExists', addedExists, ...
    'basis', ['只使用 Baseline/Candidate 的连续数组和严格相等/大小关系；', ...
    '不把新增生产阈值用于判定。最终视觉和普通眼周副作用必须人工核对。']);
end

function stats = makeStats(values, tolerance)
values = double(values(:));
if isempty(values)
    stats = struct('values', values, 'count', 0, 'sum', 0, ...
        'mean', NaN, 'min', NaN, 'max', NaN, ...
        'nonzeroPixels', 0, 'nonzeroFraction', NaN);
    return;
end
stats = struct( ...
    'values', values, ...
    'count', numel(values), ...
    'sum', sum(values), ...
    'mean', mean(values), ...
    'min', min(values), ...
    'max', max(values), ...
    'nonzeroPixels', nnz(abs(values) > tolerance), ...
    'nonzeroFraction', nnz(abs(values) > tolerance) / numel(values));
end

function stats = makeSignedStats(values, tolerance)
stats = makeStats(values, tolerance);
stats.absoluteSum = sum(abs(values(:)));
stats.absoluteMean = mean(abs(values(:)));
end

function paths = writeArtifacts(outputFolder, inputImage, manualMask, ...
        candidateLash, baselineLash, added, baselineFine, candidateFine, ...
        baselineMid, candidateMid, baselineFinal, candidateFinal, ...
        finalRgbDifference, options)
box = options.lashRoi;
originalCrop = cropImage(inputImage, box);
manualCrop = cropImage(manualMask, box);
paths = struct('outputFolder', outputFolder);
paths.baselineLashProtection = fullfile(outputFolder, ...
    'baseline_lash_protection.png');
writeProtectionMapFigure(originalCrop, manualCrop, cropImage(baselineLash, box), ...
    'Baseline lashProtection', paths.baselineLashProtection);
paths.candidateLashProtection = fullfile(outputFolder, ...
    'candidate_lash_protection.png');
writeProtectionMapFigure(originalCrop, manualCrop, cropImage(candidateLash, box), ...
    'Candidate lashProtection', paths.candidateLashProtection);
paths.addedSoftProtection = fullfile(outputFolder, ...
    'added_soft_protection.png');
writeProtectionMapFigure(originalCrop, manualCrop, cropImage(added, box), ...
    'Candidate - Baseline added soft protection', ...
    paths.addedSoftProtection);
paths.manualVsAddedSoftProtection = fullfile(outputFolder, ...
    'manual_vs_added_soft_protection.png');
writeAddedOverlay(originalCrop, manualCrop, cropImage(added, box), ...
    paths.manualVsAddedSoftProtection);
paths.baselineRepairFineDelta = fullfile(outputFolder, ...
    'baseline_repair_fine_delta.png');
writeDeltaFigure(originalCrop, manualCrop, cropImage(baselineFine, box), ...
    'Baseline Repair Fine absolute action', paths.baselineRepairFineDelta);
paths.candidateRepairFineDelta = fullfile(outputFolder, ...
    'candidate_repair_fine_delta.png');
writeDeltaFigure(originalCrop, manualCrop, cropImage(candidateFine, box), ...
    'Candidate Repair Fine absolute action', paths.candidateRepairFineDelta);
paths.baselineRepairMidDelta = fullfile(outputFolder, ...
    'baseline_repair_mid_delta.png');
writeDeltaFigure(originalCrop, manualCrop, cropImage(baselineMid, box), ...
    'Baseline Repair Mid absolute action', paths.baselineRepairMidDelta);
paths.candidateRepairMidDelta = fullfile(outputFolder, ...
    'candidate_repair_mid_delta.png');
writeDeltaFigure(originalCrop, manualCrop, cropImage(candidateMid, box), ...
    'Candidate Repair Mid absolute action', paths.candidateRepairMidDelta);
paths.baselineFinalLash = fullfile(outputFolder, 'baseline_final_lash.png');
writeFinalLashFigure(originalCrop, cropImage(baselineFinal, box), manualCrop, ...
    'Baseline final lash', paths.baselineFinalLash);
paths.candidateFinalLash = fullfile(outputFolder, ...
    'candidate_final_lash.png');
writeFinalLashFigure(originalCrop, cropImage(candidateFinal, box), manualCrop, ...
    'Candidate final lash', paths.candidateFinalLash);
paths.originalFinalCandidateComparison = fullfile(outputFolder, ...
    'original_final_candidate_comparison.png');
writeFinalComparison(originalCrop, cropImage(baselineFinal, box), ...
    cropImage(candidateFinal, box), cropImage(finalRgbDifference, box), ...
    manualCrop, paths.originalFinalCandidateComparison);
end

function writeProtectionMapFigure(originalCrop, manualCrop, mapCrop, label, path)
figureHandle = figure('Visible', 'off', 'Color', 'white', ...
    'Position', [100, 100, 1300, 520]);
tiledlayout(1, 2, 'Padding', 'compact', 'TileSpacing', 'compact');
nexttile;
imshow(originalCrop);
hold on;
drawContourIfPresent(manualCrop, 'r', 1.8);
hold off;
title('原图 + manualLashMask 边界');
nexttile;
imagesc(double(mapCrop));
axis image off;
mapLimit = max(double(mapCrop(:)));
if isempty(mapLimit) || mapLimit <= 0 || ~isfinite(mapLimit)
    mapLimit = 1;
end
clim([0, mapLimit]);
colorbar;
hold on;
drawContourIfPresent(manualCrop, 'r', 1.5);
hold off;
title(label, 'Interpreter', 'none');
exportgraphics(figureHandle, path, 'Resolution', 170);
close(figureHandle);
end

function writeAddedOverlay(originalCrop, manualCrop, addedCrop, path)
figureHandle = figure('Visible', 'off', 'Color', 'white', ...
    'Position', [100, 100, 1500, 520]);
tiledlayout(1, 3, 'Padding', 'compact', 'TileSpacing', 'compact');
nexttile;
imshow(originalCrop);
hold on;
drawContourIfPresent(manualCrop, 'r', 1.8);
drawContourIfPresent(addedCrop > 0, 'm', 1.4);
hold off;
title('原图：红=manual，洋红=新增 soft');
nexttile;
imagesc(double(addedCrop));
axis image off;
addedLimit = max(double(addedCrop(:)));
if isempty(addedLimit) || addedLimit <= 0 || ~isfinite(addedLimit)
    addedLimit = 1;
end
clim([0, addedLimit]);
colorbar;
hold on;
drawContourIfPresent(manualCrop, 'r', 1.5);
hold off;
title('新增 soft protection 连续值');
nexttile;
addedBinary = addedCrop > 0;
imagesc(addedBinary);
axis image off;
clim([0, 1]);
colorbar;
hold on;
drawContourIfPresent(manualCrop, 'r', 1.5);
hold off;
title('新增 soft protection 支持区域');
exportgraphics(figureHandle, path, 'Resolution', 170);
close(figureHandle);
end

function writeDeltaFigure(originalCrop, manualCrop, deltaCrop, label, path)
figureHandle = figure('Visible', 'off', 'Color', 'white', ...
    'Position', [100, 100, 1300, 520]);
tiledlayout(1, 2, 'Padding', 'compact', 'TileSpacing', 'compact');
nexttile;
imshow(originalCrop);
hold on;
drawContourIfPresent(manualCrop, 'r', 1.8);
hold off;
title('原图 + manualLashMask 边界');
nexttile;
imagesc(abs(double(deltaCrop)));
axis image off;
deltaLimit = max(abs(double(deltaCrop(:))));
if isempty(deltaLimit) || deltaLimit <= 0 || ~isfinite(deltaLimit)
    deltaLimit = 1;
end
clim([0, deltaLimit]);
colorbar;
hold on;
drawContourIfPresent(manualCrop, 'r', 1.5);
hold off;
title(label, 'Interpreter', 'none');
exportgraphics(figureHandle, path, 'Resolution', 170);
close(figureHandle);
end

function writeFinalLashFigure(originalCrop, finalCrop, manualCrop, label, path)
figureHandle = figure('Visible', 'off', 'Color', 'white', ...
    'Position', [100, 100, 1500, 520]);
tiledlayout(1, 2, 'Padding', 'compact', 'TileSpacing', 'compact');
nexttile;
imshow(originalCrop);
hold on;
drawContourIfPresent(manualCrop, 'r', 1.8);
hold off;
title('原图 + manualLashMask 边界');
nexttile;
imshow(finalCrop);
hold on;
drawContourIfPresent(manualCrop, 'r', 1.8);
hold off;
title(label, 'Interpreter', 'none');
exportgraphics(figureHandle, path, 'Resolution', 170);
close(figureHandle);
end

function writeFinalComparison(originalCrop, baselineCrop, candidateCrop, ...
        finalDifferenceCrop, manualCrop, path)
figureHandle = figure('Visible', 'off', 'Color', 'white', ...
    'Position', [80, 80, 1800, 1050]);
tiledlayout(2, 3, 'Padding', 'compact', 'TileSpacing', 'compact');
nexttile;
imshow(originalCrop);
hold on;
drawContourIfPresent(manualCrop, 'r', 1.5);
hold off;
title('原图 + manualLashMask');
nexttile;
imshow(baselineCrop);
hold on;
drawContourIfPresent(manualCrop, 'r', 1.5);
hold off;
title('Baseline 最终睫毛');
nexttile;
imshow(candidateCrop);
hold on;
drawContourIfPresent(manualCrop, 'r', 1.5);
hold off;
title('Candidate 最终睫毛');
nexttile;
imagesc(abs(double(baselineCrop) - double(originalCrop)));
axis image off;
colorbar;
title('Baseline 相对原图 RGB 绝对差');
nexttile;
imagesc(abs(double(candidateCrop) - double(originalCrop)));
axis image off;
colorbar;
title('Candidate 相对原图 RGB 绝对差');
nexttile;
imagesc(double(finalDifferenceCrop));
axis image off;
changeLimit = max(double(finalDifferenceCrop(:)));
if isempty(changeLimit) || changeLimit <= 0 || ~isfinite(changeLimit)
    changeLimit = 1;
end
clim([0, changeLimit]);
colorbar;
hold on;
drawContourIfPresent(manualCrop, 'r', 1.5);
hold off;
title('Candidate - Baseline RGB 绝对差');
exportgraphics(figureHandle, path, 'Resolution', 160);
close(figureHandle);
end

function writeMetricsCsv(path, metrics, assessment, placeholder)
row = struct( ...
    'issue', '08.4', ...
    'caseName', placeholder.case, ...
    'numericAssessment', assessment.case, ...
    'manualLashPixels', metrics.manualLashPixels, ...
    'manualAddedSoftProtectionSum', metrics.manualAddedSoftProtection.sum, ...
    'manualAddedSoftProtectionMean', metrics.manualAddedSoftProtection.mean, ...
    'manualAddedSoftProtectionPixels', metrics.manualAddedSoftProtection.nonzeroPixels, ...
    'browEyeOutsideManualAddedSoftProtectionSum', ...
        metrics.browEyeOutsideManualAddedSoftProtection.sum, ...
    'browEyeOutsideManualAddedSoftProtectionMean', ...
        metrics.browEyeOutsideManualAddedSoftProtection.mean, ...
    'browEyeOutsideManualAddedSoftProtectionPixels', ...
        metrics.browEyeOutsideManualAddedSoftProtection.nonzeroPixels, ...
    'baselineRepairFineAbsActionSum', metrics.baselineRepairFineAbsAction.sum, ...
    'candidateRepairFineAbsActionSum', metrics.candidateRepairFineAbsAction.sum, ...
    'repairFineAbsActionChange', metrics.repairFineAbsActionChange, ...
    'repairFineAbsActionReduction', metrics.repairFineAbsActionReduction, ...
    'baselineRepairMidAbsActionSum', metrics.baselineRepairMidAbsAction.sum, ...
    'candidateRepairMidAbsActionSum', metrics.candidateRepairMidAbsAction.sum, ...
    'repairMidAbsActionChange', metrics.repairMidAbsActionChange, ...
    'repairMidAbsActionReduction', metrics.repairMidAbsActionReduction, ...
    'manualFinalLuminanceAbsChangeSum', ...
        metrics.manualFinalLuminanceRelativeToBaseline.sum, ...
    'manualFinalLuminanceAbsChangeMean', ...
        metrics.manualFinalLuminanceRelativeToBaseline.mean, ...
    'manualFinalRgbAbsChangeSum', metrics.manualFinalRgbRelativeToBaseline.sum, ...
    'manualFinalRgbAbsChangeMean', metrics.manualFinalRgbRelativeToBaseline.mean, ...
    'baselineFinalRgbDistanceToOriginalMean', ...
        metrics.baselineFinalRgbDistanceToOriginal.mean, ...
    'candidateFinalRgbDistanceToOriginalMean', ...
        metrics.candidateFinalRgbDistanceToOriginal.mean, ...
    'baselineFinalLuminanceDistanceToOriginalMean', ...
        metrics.baselineFinalLuminanceDistanceToOriginal.mean, ...
    'candidateFinalLuminanceDistanceToOriginalMean', ...
        metrics.candidateFinalLuminanceDistanceToOriginal.mean, ...
    'browEyeOutsideManualFinalRgbChangeSum', ...
        metrics.browEyeOutsideManualFinalRgbRelativeToBaseline.sum, ...
    'browEyeOutsideManualFinalRgbChangeMean', ...
        metrics.browEyeOutsideManualFinalRgbRelativeToBaseline.mean, ...
    'hardProtectionMaskChangedPixels', metrics.hardProtectionMaskChangedPixels, ...
    'hardCoreChangedPixels', metrics.hardCoreChangedPixels, ...
    'baselineHardProtectedPixelsChangedCount', ...
        metrics.baselineHardProtectedPixelsChangedCount, ...
    'candidateHardProtectedPixelsChangedCount', ...
        metrics.candidateHardProtectedPixelsChangedCount);
writetable(struct2table(row), path);
end

function placeholder = summaryCasePlaceholder()
placeholder = struct('case', 'requiresVisualReview');
end

function diagnostics = makeCandidateTextureDiagnostics(base, ...
        candidateEyeDetail, candidateLash)
diagnostics = base;
diagnostics.eyeDetailProtection = candidateEyeDetail;
diagnostics.lashProtection = candidateLash;
end

function mask = makeRoiMask(roi, imageSize)
mask = false(imageSize(1), imageSize(2));
x1 = roi(1);
y1 = roi(2);
x2 = min(imageSize(2), roi(1) + roi(3) - 1);
y2 = min(imageSize(1), roi(2) + roi(4) - 1);
mask(y1:y2, x1:x2) = true;
end

function image = cropImage(image, box)
x1 = box(1);
y1 = box(2);
x2 = min(size(image, 2), box(1) + box(3) - 1);
y2 = min(size(image, 1), box(2) + box(4) - 1);
if ismatrix(image)
    image = image(y1:y2, x1:x2);
else
    image = image(y1:y2, x1:x2, :);
end
end

function drawContourIfPresent(mask, color, lineWidth)
if any(mask(:))
    contour(mask, [0.5, 0.5], color, 'LineWidth', lineWidth);
end
end

function value = readDiagnosticArray(value, imageSize, name)
if (~isnumeric(value) && ~islogical(value)) || ~isreal(value) || ...
        ~isequal(size(value), imageSize) || any(~isfinite(value(:)))
    error('diagnoseLashSoftContinuityCandidate:InvalidDiagnosticArray', ...
        '%s 尺寸或取值无效。', name);
end
value = double(value);
end

function validateMask(value, imageSize, name)
if (~isnumeric(value) && ~islogical(value)) || ~isreal(value) || ...
        ~isequal(size(value), imageSize) || any(~isfinite(value(:))) || ...
        any(double(value(:)) < 0) || any(double(value(:)) > 1)
    error('diagnoseLashSoftContinuityCandidate:InvalidMask', ...
        'Mask %s 尺寸或取值无效。', name);
end
end

function requireFields(value, names, label)
if ~isstruct(value) || ~isscalar(value) || ~all(isfield(value, names))
    error('diagnoseLashSoftContinuityCandidate:MissingDiagnosticField', ...
        '%s 缺少必需字段。', label);
end
end

function value = normalizeOutputFolder(value)
if nargin < 1 || isempty(value)
    value = fullfile(tempdir, ...
        'image_beauty_issue08_4_lash_soft_continuity_20260919');
end
value = normalizeText(value, 'outputFolder');
if ~isfolder(value)
    mkdir(value);
end
end

function value = normalizeText(value, name)
if isstring(value) && isscalar(value)
    value = char(value);
end
if ~ischar(value) || size(value, 1) ~= 1
    error('diagnoseLashSoftContinuityCandidate:InvalidText', ...
        '%s 必须是单行文本。', name);
end
end

function valid = isValidStrength(value)
valid = isnumeric(value) && isreal(value) && isscalar(value) && ...
    isfinite(value) && value >= 0 && value <= 100;
end
