function [summary, diagnostics] = diagnoseResidualFeatureArtifacts( ...
        imagePath, outputFolder, options)
%DIAGNOSERESIDUALFEATUREARTIFACTS 诊断耳部、鼻孔及眉眼残留失真。
%   入口只接受人工指定的固定选区，记录语义证据、软硬保护、各处理
%   阶段的实际作用量，并在本诊断入口内执行单因素对照。所有消融和
%   局部保护注入都不写回生产 Context、Mask 或算法参数。

projectRoot = fileparts(fileparts(mfilename('fullpath')));
if nargin < 3
    options = [];
end
options = normalizeOptions(options);
productionRoot = resolveProductionRoot(projectRoot, options);
addpath(fullfile(productionRoot, 'src'), '-begin');
contract = beautyPipelineContract();
validateProductionContract(contract);
if nargin < 1 || isempty(imagePath)
    error('diagnoseResidualFeatureArtifacts:MissingImagePath', ...
        '必须提供输入图像路径。');
end
inputImage = readInputImage(imagePath);
if isfield(options, 'faceBox') && ~isempty(options.faceBox)
    validateRoiBounds(options.faceBox, size(inputImage), 'faceBox');
end
roiDefinitions = makeRegionDefinitions(options);
for index = 1:numel(roiDefinitions)
    roiDefinitions(index).roi = validateRoiBounds( ...
        roiDefinitions(index).roi, size(inputImage), ...
        roiDefinitions(index).name);
end

if nargin < 2 || isempty(outputFolder)
    outputFolder = fullfile(tempdir, ...
        'image_beauty_residual_feature_diagnosis');
end
if ~ischar(outputFolder) && ...
        ~(isstring(outputFolder) && isscalar(outputFolder))
    error('diagnoseResidualFeatureArtifacts:InvalidOutputFolder', ...
        '输出目录必须是文本路径。');
end
outputFolder = char(outputFolder);
if ~isfolder(outputFolder)
    mkdir(outputFolder);
end

if isfield(options, 'precomputedDiagnosticsPath') && ...
        ~isempty(options.precomputedDiagnosticsPath)
    [modes, previewScale, previewFaceBox, fullFaceBox, detection] = ...
        makePrecomputedModes(inputImage, options, roiDefinitions);
else
    [previewImage, previewScale] = makePreview(inputImage);
    [previewFaceBox, hasFace, detection] = detectSingleFace(previewImage);
    if ~hasFace
        error('diagnoseResidualFeatureArtifacts:NoFace', ...
            '输入图像未检测到可用的语义人脸。');
    end
    if isfield(options, 'faceBox') && ~isempty(options.faceBox)
        expectedPreviewFaceBox = scaleFaceBox(options.faceBox, previewScale, ...
            size(previewImage));
        if ~isequal(double(previewFaceBox), double(expectedPreviewFaceBox))
            error('diagnoseResidualFeatureArtifacts:FaceBoxMismatch', ...
                '检测到的人脸框与固定诊断人脸框不一致。');
        end
    end
    previewContext = prepareBeautyContext(previewImage, previewFaceBox, ...
        detection.selectedParsing, struct('rotationDegrees', ...
        detection.orientationDegrees));
    fullFaceBox = scaleFaceBox(previewFaceBox, 1 / previewScale, ...
        size(inputImage));
    if previewScale < 1
        fullContext = resizeBeautyContext(previewContext, size(inputImage), ...
            fullFaceBox, inputImage);
    else
        fullContext = previewContext;
    end

    if previewScale < 1
        modes = { ...
            struct('name', 'preview', 'image', previewImage, ...
            'faceBox', previewFaceBox, 'context', previewContext, ...
            'scale', previewScale), ...
            struct('name', 'original', 'image', inputImage, ...
            'faceBox', fullFaceBox, 'context', fullContext, 'scale', 1)};
    else
        modes = {struct('name', 'original', 'image', inputImage, ...
            'faceBox', fullFaceBox, 'context', fullContext, 'scale', 1)};
    end
end

regionRows = repmat(emptyRegionRow(), 0, 1);
ablationRows = repmat(emptyAblationRow(), 0, 1);
repairComponentRows = repmat(emptyRepairComponentRow(), 0, 1);
repairCombinationRows = repmat(emptyRepairCombinationRow(), 0, 1);
imageMetricRows = repmat(emptyImageMetricRow(), 0, 1);
modeDiagnostics = cell(1, numel(modes));
for modeIndex = 1:numel(modes)
    mode = modes{modeIndex};
    modeDefinitions = scaleDefinitions(roiDefinitions, mode.scale, ...
        size(mode.image));
    [modeResult, currentRegionRows, currentAblationRows, ...
        currentRepairComponentRows, currentRepairCombinationRows] = ...
        diagnoseMode(mode, modeDefinitions, options);
    modeDiagnostics{modeIndex} = modeResult;
    regionRows = [regionRows; currentRegionRows]; %#ok<AGROW>
    ablationRows = [ablationRows; currentAblationRows]; %#ok<AGROW>
    repairComponentRows = [repairComponentRows; ...
        currentRepairComponentRows]; %#ok<AGROW>
    repairCombinationRows = [repairCombinationRows; ...
        currentRepairCombinationRows]; %#ok<AGROW>
    imageMetricRows(end + 1, 1) = makeImageMetricRow( ...
        mode.name, modeResult.imageMetrics); %#ok<AGROW>
end

regionMetrics = struct2table(regionRows);
ablationMetrics = struct2table(ablationRows);
repairComponentMetrics = struct2table(repairComponentRows);
repairCombinationMetrics = struct2table(repairCombinationRows);
imageMetrics = struct2table(imageMetricRows);
paths = writeArtifacts(outputFolder, modeDiagnostics, regionMetrics, ...
    ablationMetrics, repairComponentMetrics, repairCombinationMetrics, ...
    imageMetrics);
summary = struct( ...
    'completed', true, ...
    'contract', contract, ...
    'imagePath', char(imagePath), ...
    'inputSize', size(inputImage), ...
    'previewScale', previewScale, ...
    'previewFaceBox', previewFaceBox, ...
    'originalFaceBox', fullFaceBox, ...
    'orientationDegrees', detection.orientationDegrees, ...
    'parameters', struct( ...
    'smoothingStrength', options.smoothingStrength, ...
    'whiteningStrength', options.whiteningStrength), ...
    'rois', roiDefinitions, ...
    'regionMetrics', regionMetrics, ...
    'ablationMetrics', ablationMetrics, ...
    'repairComponentMetrics', repairComponentMetrics, ...
    'repairCombinationMetrics', repairCombinationMetrics, ...
    'imageMetrics', imageMetrics, ...
    'paths', paths);
compactModes = compactModeDiagnostics(modeDiagnostics);
diagnostics = struct( ...
    'contract', contract, ...
    'detection', compactDetection(detection), ...
    'modes', {compactModes}, ...
    'paths', paths);
dataPath = fullfile(outputFolder, ...
    'residualFeatureDiagnosticData.mat');
summary.paths.data = dataPath;
diagnostics.paths.data = dataPath;
clear modeDiagnostics compactModes;
save(dataPath, 'summary', 'diagnostics', '-v7.3');
end

function root = resolveProductionRoot(projectRoot, options)
root = projectRoot;
if isfield(options, 'productionRoot') && ~isempty(options.productionRoot)
    if ~ischar(options.productionRoot) && ...
            ~(isstring(options.productionRoot) && ...
            isscalar(options.productionRoot))
        error('diagnoseResidualFeatureArtifacts:InvalidProductionRoot', ...
            '生产算法根目录必须是文本路径。');
    end
    root = char(options.productionRoot);
end
if ~isfolder(root) || ~isfolder(fullfile(root, 'src'))
    error('diagnoseResidualFeatureArtifacts:InvalidProductionRoot', ...
        '生产算法根目录或 src 目录不存在：%s。', root);
end
end

function validateProductionContract(contract)
required = {'schemaVersion', 'algorithmVersion', 'artifactVersion'};
if ~isstruct(contract) || ~isscalar(contract) || ...
        ~all(isfield(contract, required)) || ...
        ~strcmp(char(contract.schemaVersion), '4.0') || ...
        ~strcmp(char(contract.algorithmVersion), 'v3.3') || ...
        ~strcmp(char(contract.artifactVersion), 'v3.2')
    error('diagnoseResidualFeatureArtifacts:InvalidProductionBaseline', ...
        '生产依赖必须是已验证的 v3.3、Schema 4.0、产物 v3.2 基线。');
end
end

function [modes, previewScale, previewFaceBox, fullFaceBox, detection] = ...
        makePrecomputedModes(inputImage, options, definitions)
requiredOptions = {'faceBox', 'existingRegionMetricsPath', ...
    'existingImageMetricsPath'};
for index = 1:numel(requiredOptions)
    name = requiredOptions{index};
    if ~isfield(options, name) || isempty(options.(name))
        error('diagnoseResidualFeatureArtifacts:MissingPrecomputedArtifact', ...
            '复用已有基线时必须提供 %s。', name);
    end
end
diagnosticPath = requireFileOption(options, 'precomputedDiagnosticsPath');
regionPath = requireFileOption(options, 'existingRegionMetricsPath');
imageMetricPath = requireFileOption(options, 'existingImageMetricsPath');
loaded = load(diagnosticPath, 'diagnostics', 'context', 'output');
if ~isfield(loaded, 'diagnostics')
    error('diagnoseResidualFeatureArtifacts:InvalidPrecomputedArtifact', ...
        '已有基线 MAT 缺少 diagnostics 结构：%s。', diagnosticPath);
end
baseline = loaded.diagnostics;
if ~isstruct(baseline) || ~isscalar(baseline)
    error('diagnoseResidualFeatureArtifacts:InvalidPrecomputedArtifact', ...
        '已有基线诊断不是标量结构：%s。', diagnosticPath);
end
required = {'beautyMasks', 'mask', 'frequency', 'blemishMap', ...
    'blemish', 'repairResult', 'repair', 'smoothingResult', ...
    'smoothing', 'baseLuminanceResult', 'skinToneResult', ...
    'whiteningResult', 'compose'};
requireDiagnosticFields(baseline, required, '已有基线');
imageSize = size(inputImage, 1:2);
if ~isequal(size(baseline.beautyMasks.skinMask), imageSize) || ...
        ~isequal(double(baseline.beautyMasks.imageSize), [imageSize, 3])
    error('diagnoseResidualFeatureArtifacts:InvalidPrecomputedArtifact', ...
        '已有基线与输入图像尺寸不一致。');
end
fullFaceBox = options.faceBox;
if ~isequal(double(baseline.beautyMasks.faceBox), double(fullFaceBox))
    error('diagnoseResidualFeatureArtifacts:FaceBoxMismatch', ...
        '已有基线的人脸框与固定诊断人脸框不一致。');
end
readExistingRegionRows(regionPath, definitions);
frequency = makePrecomputedFrequency(baseline.frequency, inputImage, ...
    fullFaceBox, imageSize);
baseline.frequency = frequency;
elapsedSeconds = readExistingElapsedSeconds(imageMetricPath);
if isfield(loaded, 'output')
    baselineImage = loaded.output;
elseif isfield(options, 'existingBaselineImagePath') && ...
        ~isempty(options.existingBaselineImagePath)
    baselineImagePath = requireFileOption(options, ...
        'existingBaselineImagePath');
    baselineImage = imread(baselineImagePath);
else
    error('diagnoseResidualFeatureArtifacts:MissingPrecomputedArtifact', ...
        '已有基线 MAT 缺少 output，且未提供已有基线 PNG。');
end
validateExistingBaselineImageValue(baselineImage, imageSize);
sourceContext = loaded.context;
requireDiagnosticFields(sourceContext, ...
    {'skinMask', 'faceSkinMask', 'regions', 'regionConfidence'}, ...
    '已有 Beauty Context');
context = struct( ...
    'skinMask', sourceContext.skinMask, ...
    'faceSkinMask', sourceContext.faceSkinMask, ...
    'regions', sourceContext.regions, ...
    'regionConfidence', sourceContext.regionConfidence);
mode = struct('name', 'original', 'image', inputImage, ...
    'faceBox', fullFaceBox, 'context', context, 'scale', 1, ...
    'precomputedBaseline', baseline, ...
    'precomputedBaselineImage', baselineImage, ...
    'elapsedSeconds', elapsedSeconds);
modes = {mode};
previewScale = 1;
previewFaceBox = fullFaceBox;
detection = struct('orientationDegrees', 0, ...
    'selectedCandidateBox', fullFaceBox, ...
    'usedFullImageParsing', false, 'fullParsingCount', 0, ...
    'candidateAssessment', []);
end

function path = requireFileOption(options, name)
value = options.(name);
if ~ischar(value) && ~(isstring(value) && isscalar(value))
    error('diagnoseResidualFeatureArtifacts:InvalidPrecomputedArtifact', ...
        '%s 必须是文本路径。', name);
end
path = char(value);
if ~isfile(path)
    error('diagnoseResidualFeatureArtifacts:MissingPrecomputedArtifact', ...
        '已有诊断产物不存在：%s。', path);
end
end

function validateExistingBaselineImageValue(image, imageSize)
if ~isa(image, 'uint8') || ~isreal(image) || ndims(image) ~= 3 || ...
        size(image, 3) ~= 3 || ~isequal(size(image, 1:2), imageSize)
    error('diagnoseResidualFeatureArtifacts:InvalidPrecomputedArtifact', ...
        '已有基线输出不是匹配尺寸的 uint8 三通道图像。');
end
end

function frequency = makePrecomputedFrequency(frequency, inputImage, ...
        faceBox, imageSize)
required = {'base', 'mid', 'fine'};
requireDiagnosticFields(frequency, required, '已有频率基线');
sourceYcbcr = rgb2ycbcr(im2double(inputImage));
frequency.sourceLuminance = sourceYcbcr(:, :, 1);
frequency.imageSize = [imageSize, 3];
frequency.faceBox = faceBox;
frequency.faceScale = min(double(faceBox(3:4)));
frequency.reconstructedLuminance = double(frequency.base) + ...
    double(frequency.mid) + double(frequency.fine);
frequency.outputLuminance = frequency.reconstructedLuminance;
frequency.alphaMap = zeros(imageSize);
end

function rows = readExistingRegionRows(path, definitions)
tableValue = readtable(path, 'TextType', 'char');
expectedFields = fieldnames(emptyRegionRow());
if ~all(ismember(expectedFields, tableValue.Properties.VariableNames))
    error('diagnoseResidualFeatureArtifacts:MissingDiagnosticField', ...
        '已有区域诊断表缺少 03 字段。');
end
rows = table2struct(tableValue);
if numel(rows) ~= numel(definitions)
    error('diagnoseResidualFeatureArtifacts:InvalidPrecomputedArtifact', ...
        '已有区域诊断表的 ROI 数量与本票不一致。');
end
for index = 1:numel(definitions)
    matches = find(strcmp({rows.symptom}, definitions(index).name));
    if numel(matches) ~= 1
        error('diagnoseResidualFeatureArtifacts:InvalidPrecomputedArtifact', ...
            '已有区域诊断表缺少唯一 ROI %s。', definitions(index).name);
    end
    row = rows(matches);
    expected = definitions(index).roi;
    actual = [row.roiX, row.roiY, row.roiWidth, row.roiHeight];
    if ~isequal(double(actual), double(expected)) || ...
            ~strcmp(row.mode, 'original')
        error('diagnoseResidualFeatureArtifacts:InvalidPrecomputedArtifact', ...
            '已有区域诊断表的 %s ROI 或模式不匹配。', definitions(index).name);
    end
end
end

function elapsedSeconds = readExistingElapsedSeconds(path)
tableValue = readtable(path, 'TextType', 'char');
required = {'mode', 'elapsedSeconds'};
if ~all(ismember(required, tableValue.Properties.VariableNames))
    error('diagnoseResidualFeatureArtifacts:MissingDiagnosticField', ...
        '已有图像指标表缺少 mode 或 elapsedSeconds。');
end
matches = strcmp(tableValue.mode, 'original');
if nnz(matches) ~= 1
    error('diagnoseResidualFeatureArtifacts:InvalidPrecomputedArtifact', ...
        '已有图像指标表缺少唯一 original 记录。');
end
elapsedSeconds = tableValue.elapsedSeconds(matches);
if ~isfinite(elapsedSeconds) || elapsedSeconds < 0
    error('diagnoseResidualFeatureArtifacts:InvalidPrecomputedArtifact', ...
        '已有基线耗时无效。');
end
end

function options = normalizeOptions(options)
if nargin < 1 || isempty(options) || ~isstruct(options) || ...
        ~isscalar(options)
    error('diagnoseResidualFeatureArtifacts:MissingRoi', ...
        ['必须提供至少一个依据原图或截图人工确定的 ROI；不能由 ', ...
        '待验证的 Mask 自动生成选区。']);
end
roiFields = {'earRoi', 'nostrilRoi', 'browEyeRoi', ...
    'noseBridgeRoi', 'noseWingRoi', 'normalSkinRoi', 'freckleRoi', ...
    'hairRoi', 'backgroundRoi'};
hasRoi = false;
for index = 1:numel(roiFields)
    name = roiFields{index};
    if isfield(options, name) && ~isempty(options.(name))
        options.(name) = validateRoi(options.(name), name);
        hasRoi = true;
    end
end
if isfield(options, 'faceBox') && ~isempty(options.faceBox)
    options.faceBox = validateRoi(options.faceBox, 'faceBox');
end
if ~hasRoi
    error('diagnoseResidualFeatureArtifacts:MissingRoi', ...
        ['必须提供至少一个人工 ROI；ROI 不能由待验证的 ', ...
        '皮肤或保护 Mask 自动生成。']);
end
if ~isfield(options, 'smoothingStrength')
    options.smoothingStrength = 100;
end
if ~isfield(options, 'whiteningStrength')
    options.whiteningStrength = 15;
end
if ~isValidStrength(options.smoothingStrength) || ...
        ~isValidStrength(options.whiteningStrength)
    error('diagnoseResidualFeatureArtifacts:InvalidStrength', ...
        '磨皮和美白强度必须是范围 0 到 100 内的有限数值标量。');
end
end

function image = readInputImage(imagePath)
if ~ischar(imagePath) && ~(isstring(imagePath) && isscalar(imagePath))
    error('diagnoseResidualFeatureArtifacts:InvalidImagePath', ...
        '输入图像路径必须是文本。');
end
imagePath = char(imagePath);
if ~isfile(imagePath)
    error('diagnoseResidualFeatureArtifacts:MissingImage', ...
        '输入图像不存在：%s。', imagePath);
end
image = imread(imagePath);
if ~isa(image, 'uint8') || ~isreal(image) || ndims(image) ~= 3 || ...
        size(image, 3) ~= 3
    error('diagnoseResidualFeatureArtifacts:InvalidImage', ...
        '输入图像必须是 uint8 三通道 RGB 图像。');
end
end

function definitions = makeRegionDefinitions(options)
specs = { ...
    struct('name', 'ear', 'field', 'earRoi', ...
    'semanticNames', {{'leftEar', 'rightEar'}}, 'kind', 'feature'), ...
    struct('name', 'nostril', 'field', 'nostrilRoi', ...
    'semanticNames', {{'nose'}}, 'kind', 'feature'), ...
    struct('name', 'browEye', 'field', 'browEyeRoi', ...
    'semanticNames', {{'leftBrow', 'rightBrow', 'leftEye', 'rightEye'}}, ...
    'kind', 'feature'), ...
    struct('name', 'noseBridge', 'field', 'noseBridgeRoi', ...
    'semanticNames', {{'nose'}}, 'kind', 'structure'), ...
    struct('name', 'noseWing', 'field', 'noseWingRoi', ...
    'semanticNames', {{'nose'}}, 'kind', 'structure'), ...
    struct('name', 'normalSkin', 'field', 'normalSkinRoi', ...
    'semanticNames', {{'skin'}}, 'kind', 'reference'), ...
    struct('name', 'freckle', 'field', 'freckleRoi', ...
    'semanticNames', {{'skin'}}, 'kind', 'reference'), ...
    struct('name', 'hair', 'field', 'hairRoi', ...
    'semanticNames', {{'hair'}}, 'kind', 'safety'), ...
    struct('name', 'background', 'field', 'backgroundRoi', ...
    'semanticNames', {{'background'}}, 'kind', 'safety')};
definitions = struct('name', {}, 'roi', {}, ...
    'semanticNames', {}, 'kind', {});
for index = 1:numel(specs)
    spec = specs{index};
    if ~isfield(options, spec.field) || isempty(options.(spec.field))
        continue;
    end
    definition = struct('name', spec.name, ...
        'roi', options.(spec.field), 'kind', spec.kind);
    definition.semanticNames = spec.semanticNames;
    definitions(end + 1, 1) = definition; %#ok<AGROW>
end
end

function [modeResult, regionRows, ablationRows, repairComponentRows, ...
        repairCombinationRows] = diagnoseMode( ...
        mode, definitions, options)
params = struct('smoothingStrength', options.smoothingStrength, ...
    'whiteningStrength', options.whiteningStrength);
if isfield(mode, 'precomputedBaseline')
    baseline = mode.precomputedBaseline;
    frequency = baseline.frequency;
    processing = makeProcessing(baseline);
    [output, compose] = beauty.composeBeautyResult(mode.image, ...
        frequency, baseline.repairResult, baseline.beautyMasks, ...
        params.whiteningStrength, processing);
    existingDifference = max(abs(double(output) - ...
        double(mode.precomputedBaselineImage)), [], 'all');
    if existingDifference ~= 0
        error('diagnoseResidualFeatureArtifacts:PrecomputedBaselineMismatch', ...
            '已有基线组件重建与保存的 v3.2 输出不一致，最大 RGB 差为 %.17g。', ...
            existingDifference);
    end
    baseline.output = output;
    baseline.compose = compose;
    elapsedSeconds = mode.elapsedSeconds;
else
    startTime = tic;
    [output, baseline] = beautifyImage(mode.image, params, mode.faceBox, ...
        mode.context);
    elapsedSeconds = toc(startTime);
    [frequency, ~] = beauty.decomposeSkinFrequency( ...
        mode.image, mode.faceBox);
end
imageMetrics = evaluateImage(mode.image, output, elapsedSeconds);
baseline.output = output;
required = {'beautyMasks', 'blemishMap', 'smoothingResult', ...
    'repairResult', 'baseLuminanceResult', 'skinToneResult', ...
    'whiteningResult', 'compose'};
if ~all(isfield(baseline, required))
    error('diagnoseResidualFeatureArtifacts:IncompleteDiagnostics', ...
        '基线诊断缺少定位残留五官失真所需的阶段结果。');
end
validateRequiredDiagnostics(baseline, size(mode.image, 1:2));
baseline.frequency = frequency;
structureSources = reconstructStructureSources( ...
    mode.faceBox, baseline.beautyMasks, ...
    baseline.mask.structure);
safetyMasks = buildSafetyMasks(mode.context, definitions, ...
    baseline.beautyMasks);
ablation = runAblations(mode.image, frequency, baseline.beautyMasks, ...
    baseline.blemishMap, baseline, params, definitions);
processing = makeProcessing(baseline);
repairComponents = buildRepairComponents(mode.image, frequency, ...
    baseline, baseline.beautyMasks, params, processing);
repairCombination = measureRepairCombination(repairComponents, mode);

regionRows = repmat(emptyRegionRow(), 0, 1);
ablationRows = repmat(emptyAblationRow(), 0, 1);
repairComponentRows = repmat(emptyRepairComponentRow(), 0, 1);
repairCombinationRows = repmat(emptyRepairCombinationRow(), 0, 1);
for regionIndex = 1:numel(definitions)
    definition = definitions(regionIndex);
    if ~isfield(mode, 'reusedRegionRows')
        regionRows(end + 1, 1) = measureRegion(mode, definition, ...
            baseline.beautyMasks, baseline, structureSources, ...
            safetyMasks); %#ok<AGROW>
    end
    for ablationIndex = 1:numel(ablation.items)
        item = ablation.items(ablationIndex);
        ablationRows(end + 1, 1) = measureAblation(mode, definition, ...
            item, baseline, safetyMasks); %#ok<AGROW>
    end
    if strcmp(definition.kind, 'feature')
        for componentIndex = 1:numel(repairComponents)
            repairComponentRows(end + 1, 1) = measureRepairComponent( ...
                mode, definition, repairComponents(componentIndex), ...
                repairComponents, baseline, safetyMasks); %#ok<AGROW>
        end
    end
end
if isfield(mode, 'reusedRegionRows')
    regionRows = mode.reusedRegionRows;
end
repairCombinationRows(1, 1) = repairCombination;

modeResult = struct( ...
    'name', mode.name, ...
    'image', mode.image, ...
    'faceBox', mode.faceBox, ...
    'context', mode.context, ...
    'definitions', definitions, ...
    'output', output, ...
    'baseline', baseline, ...
    'frequency', frequency, ...
    'structureSources', structureSources, ...
    'ablation', ablation, ...
    'repairComponents', repairComponents, ...
    'repairCombination', repairCombination, ...
    'safetyMasks', safetyMasks, ...
    'imageMetrics', imageMetrics);
end

function structure = reconstructStructureSources(faceBox, beautyMasks, ...
        structureDiagnostics)
required = {'continuousEvidence', 'noseStructure', ...
    'outsideStructure', 'faceBoundary'};
if ~all(isfield(structureDiagnostics, required))
    error('diagnoseResidualFeatureArtifacts:MissingStructureEvidence', ...
        '结构诊断缺少现有生产公式所需的来源证据。');
end
imageSize = size(beautyMasks.skinMask);
skin = readMask(beautyMasks, 'skinMask', imageSize);
face = readMask(beautyMasks, 'faceSkinMask', imageSize);
continuousEvidence = readArray(structureDiagnostics.continuousEvidence, ...
    imageSize, 'continuousEvidence');
faceStructure = min(face, skin) .* continuousEvidence;
sourceNames = {'noseStructure', 'outsideStructure', ...
    'faceStructure', 'faceBoundary'};
sources = struct();
sources.noseStructure = readArray(structureDiagnostics.noseStructure, ...
    imageSize, 'noseStructure');
sources.outsideStructure = readArray( ...
    structureDiagnostics.outsideStructure, imageSize, 'outsideStructure');
sources.faceStructure = faceStructure;
sources.faceBoundary = readArray(structureDiagnostics.faceBoundary, ...
    imageSize, 'faceBoundary');
sourceStack = cat(3, sources.noseStructure, sources.outsideStructure, ...
    sources.faceStructure, sources.faceBoundary);
reconstructed = max(sourceStack, [], 3) .* min(max(skin, 0), 1);
baselineStructure = readMask(beautyMasks, ...
    'structureProtectionMask', imageSize);
[maximumSource, dominant] = max(sourceStack, [], 3);
validSource = maximumSource > 1e-12;
dominant(~validSource) = 0;
tieMask = validSource & ...
    sum(abs(sourceStack - maximumSource) <= 1e-12, 3) > 1;
structure = struct( ...
    'names', {sourceNames}, ...
    'sources', sources, ...
    'sourceStack', sourceStack, ...
    'reconstructed', reconstructed, ...
    'baseline', baselineStructure, ...
    'reconstructionMaxError', max(abs(reconstructed(:) - ...
    baselineStructure(:))), ...
    'dominant', dominant, ...
    'tieMask', tieMask, ...
    'faceScale', min(double(faceBox(3:4))));
end

function validateRequiredDiagnostics(baseline, imageSize)
requireDiagnosticFields(baseline, {'beautyMasks', 'blemishMap', ...
    'smoothingResult', 'repairResult', 'smoothing', 'repair', ...
    'mask', 'compose'}, '基线');
requireDiagnosticFields(baseline.beautyMasks, {'skinMask', ...
    'faceSkinMask', 'textureProtectionMask', ...
    'structureProtectionMask', 'hardProtectionMask', ...
    'whiteningProtectionMask', 'chromaProtectionMask', ...
    'strengthMap'}, 'Beauty Masks');
requireDiagnosticFields(baseline.smoothing, {'fineBefore', 'fineAfter', ...
    'midBefore', 'midAfter', 'fineStructureGate', 'midStructureGate'}, ...
    '平滑诊断');
requireDiagnosticFields(baseline.repair, {'fineBefore', 'fineAfter', ...
    'midBefore', 'midAfter', 'fineCorrection', 'mediumCorrection', ...
    'fineWeight', 'mediumWeight', 'textureGate', 'repairEvidence'}, ...
    'Repair 诊断');
requireDiagnosticFields(baseline.mask, {'structure', 'texture', ...
    'chroma', 'whitening'}, 'Mask 诊断');
requireDiagnosticFields(baseline.mask.structure, {'continuousEvidence', ...
    'noseStructure', 'outsideStructure', 'faceBoundary'}, '结构诊断');
requireDiagnosticFields(baseline.mask.texture, {'nostrilCore', ...
    'nostrilBoundary', 'occluderProtection', 'browProtection', ...
    'lipProtection', 'noseProtection', 'eyeDetailProtection', ...
    'periocularProtection', 'doubleEyelidProtection', ...
    'lashProtection'}, '纹理诊断');
requireDiagnosticFields(baseline.mask.chroma, ...
    {'nostrilCandidate', 'noseSemanticExcluded'}, '色度诊断');
requireDiagnosticFields(baseline.mask.whitening, {'nostrilCore'}, ...
    '美白诊断');
readArray(baseline.blemishMap, imageSize, 'blemishMap');
end

function requireDiagnosticFields(value, names, label)
if ~isstruct(value) || ~isscalar(value)
    error('diagnoseResidualFeatureArtifacts:MissingDiagnosticField', ...
        '%s 不是有效的诊断结构。', label);
end
for index = 1:numel(names)
    if ~isfield(value, names{index})
        error('diagnoseResidualFeatureArtifacts:MissingDiagnosticField', ...
            '%s 缺少诊断字段 %s。', label, names{index});
    end
end
end

function components = buildRepairComponents(inputImage, frequency, ...
        baseline, beautyMasks, params, processing)
smoothed = baseline.smoothingResult;
repairFrequency = baseline.repairResult;
repairDiagnostics = baseline.repair;
imageSize = size(inputImage, 1:2);
requireDiagnosticFields(smoothed, {'base', 'mid', 'fine', ...
    'outputLuminance', 'alphaMap'}, '平滑结果');
requireDiagnosticFields(repairFrequency, {'base', 'mid', 'fine', ...
    'outputLuminance', 'alphaMap'}, 'Repair 结果');
requireDiagnosticFields(repairDiagnostics, {'fineAfter', 'midAfter', ...
    'fineWeight', 'mediumWeight'}, 'Repair 诊断');
readArray(smoothed.base, imageSize, '平滑 Base');
readArray(smoothed.mid, imageSize, '平滑 Mid');
readArray(smoothed.fine, imageSize, '平滑 Fine');
readArray(repairDiagnostics.fineAfter, imageSize, 'Repair Fine');
readArray(repairDiagnostics.midAfter, imageSize, 'Repair Mid');
readArray(repairDiagnostics.fineWeight, imageSize, 'Repair Fine 权重');
readArray(repairDiagnostics.mediumWeight, imageSize, 'Repair Mid 权重');

names = {'completeRepair', 'fineOnly', 'midOnly', 'withoutRepair'};
components = repmat(emptyRepairComponentItem(), numel(names), 1);
for index = 1:numel(names)
    name = names{index};
    componentFrequency = makeRepairComponentFrequency( ...
        smoothed, repairFrequency, repairDiagnostics, name, imageSize);
    [output, compose] = beauty.composeBeautyResult(inputImage, ...
        frequency, componentFrequency, beautyMasks, ...
        params.whiteningStrength, processing);
    components(index) = makeRepairComponent(name, componentFrequency, ...
        output, compose, smoothed);
end

baselineDifference = max(abs(double(components(1).output) - ...
    double(baseline.output)), [], 'all');
components(1).baselineDifferenceMax = baselineDifference;
if baselineDifference ~= 0
    error('diagnoseResidualFeatureArtifacts:RepairReconstructionMismatch', ...
        '完整 Repair 重建与同一基线输出不一致，最大 RGB 差为 %.17g。', ...
        baselineDifference);
end
end

function componentFrequency = makeRepairComponentFrequency( ...
        smoothed, repairFrequency, repairDiagnostics, name, imageSize)
switch name
    case 'completeRepair'
        componentFrequency = repairFrequency;
    case 'fineOnly'
        componentFrequency = smoothed;
        componentFrequency.fine = repairDiagnostics.fineAfter;
        componentFrequency.alphaMap = min(1, max(double(smoothed.alphaMap), ...
            double(repairDiagnostics.fineWeight)));
    case 'midOnly'
        componentFrequency = smoothed;
        componentFrequency.mid = repairDiagnostics.midAfter;
        componentFrequency.alphaMap = min(1, max(double(smoothed.alphaMap), ...
            double(repairDiagnostics.mediumWeight)));
    case 'withoutRepair'
        componentFrequency = smoothed;
    otherwise
        error('diagnoseResidualFeatureArtifacts:InvalidRepairComponent', ...
            '未知 Repair 分量 %s。', name);
end
componentFrequency.reconstructedLuminance = double( ...
    componentFrequency.base) + double(componentFrequency.mid) + ...
    double(componentFrequency.fine);
componentFrequency.outputLuminance = ...
    componentFrequency.reconstructedLuminance;
if ~isequal(size(componentFrequency.outputLuminance), imageSize)
    error('diagnoseResidualFeatureArtifacts:InvalidRepairComponent', ...
        'Repair 分量 %s 的输出尺寸不匹配。', name);
end
end

function item = makeRepairComponent(name, frequency, output, compose, ...
        smoothed)
item = emptyRepairComponentItem();
item.name = name;
item.frequency = frequency;
item.output = output;
item.compose = compose;
item.fineCorrection = double(frequency.fine) - double(smoothed.fine);
item.mediumCorrection = double(frequency.mid) - double(smoothed.mid);
end

function row = measureRepairComponent(mode, definition, component, ...
        components, baseline, safetyMasks)
imageSize = size(mode.image, 1:2);
roi = regionMask(definition.roi, imageSize);
withoutRepair = findRepairComponent(components, 'withoutRepair');
smoothed = baseline.smoothingResult;
fine = readArray(component.frequency.fine, imageSize, ...
    [component.name ' Fine']);
mid = readArray(component.frequency.mid, imageSize, ...
    [component.name ' Mid']);
smoothFine = readArray(smoothed.fine, imageSize, '平滑 Fine');
smoothMid = readArray(smoothed.mid, imageSize, '平滑 Mid');
fineAction = abs(fine - smoothFine);
midAction = abs(mid - smoothMid);
blemishMap = readArray(baseline.blemishMap, imageSize, 'blemishMap');
energyBefore = (abs(smoothFine) + abs(smoothMid)) .* blemishMap;
energyAfter = (abs(fine) + abs(mid)) .* blemishMap;
outputChange = max(abs(double(component.output) - ...
    double(mode.image)), [], 3);
outputDifference = max(abs(double(component.output) - ...
    double(withoutRepair.output)), [], 3);
componentY = rgb2ycbcr(im2double(component.output));
withoutRepairY = rgb2ycbcr(im2double(withoutRepair.output));
base = readArray(smoothed.base, imageSize, '平滑 Base');
beforeGradient = lowFrequencyGradient(base + smoothMid);
afterGradient = lowFrequencyGradient(base + mid);

row = emptyRepairComponentRow();
row.mode = mode.name;
row.symptom = definition.name;
row.component = component.name;
row.roiX = definition.roi(1);
row.roiY = definition.roi(2);
row.roiWidth = definition.roi(3);
row.roiHeight = definition.roi(4);
row.roiPixels = nnz(roi);
row.fineActionMean = meanOn(fineAction, roi);
row.fineActionP90 = percentileOn(fineAction, roi, .90);
row.fineActiveFraction = fractionOf(fineAction > 1e-6, roi);
row.midActionMean = meanOn(midAction, roi);
row.midActionP90 = percentileOn(midAction, roi, .90);
row.midActiveFraction = fractionOf(midAction > 1e-6, roi);
row.fineRetentionRatio = safeRatio(meanOn(abs(fine), roi), ...
    meanOn(abs(smoothFine), roi));
row.midRetentionRatio = safeRatio(meanOn(abs(mid), roi), ...
    meanOn(abs(smoothMid), roi));
row.blemishEnergyBeforeMean = meanOn(energyBefore, roi);
row.blemishEnergyAfterMean = meanOn(energyAfter, roi);
row.blemishEnergyReductionRatio = 1 - safeRatio( ...
    row.blemishEnergyAfterMean, row.blemishEnergyBeforeMean);
row.outputRgbChangeFromInputMean = meanOn(outputChange, roi);
row.outputRgbChangeFromInputP90 = percentileOn(outputChange, roi, .90);
row.outputRgbChangeFromInputMax = maxOn(outputChange, roi);
row.outputRgbDifferenceFromNoRepairMean = meanOn(outputDifference, roi);
row.outputRgbDifferenceFromNoRepairP90 = percentileOn( ...
    outputDifference, roi, .90);
row.outputRgbDifferenceFromNoRepairMax = maxOn(outputDifference, roi);
row.outputLuminanceDifferenceFromNoRepairMean = meanOn( ...
    abs(componentY(:, :, 1) - withoutRepairY(:, :, 1)), roi);
row.lowFrequencyGradientBeforeMean = meanOn(beforeGradient, roi);
row.lowFrequencyGradientAfterMean = meanOn(afterGradient, roi);
row.lowFrequencyGradientRetentionRatio = safeRatio( ...
    row.lowFrequencyGradientAfterMean, row.lowFrequencyGradientBeforeMean);
row.hardProtectionMaxRgbChange = maxOn(outputChange, safetyMasks.hard);
row.hairMaxRgbChange = maxOn(outputChange, safetyMasks.hair);
row.backgroundMaxRgbChange = maxOn(outputChange, safetyMasks.background);
end

function row = measureRepairCombination(components, mode)
complete = findRepairComponent(components, 'completeRepair');
fineOnly = findRepairComponent(components, 'fineOnly');
midOnly = findRepairComponent(components, 'midOnly');
withoutRepair = findRepairComponent(components, 'withoutRepair');
expectedLuminance = fineOnly.frequency.outputLuminance + ...
    midOnly.frequency.outputLuminance - ...
    withoutRepair.frequency.outputLuminance;
internalResidual = abs(complete.frequency.outputLuminance - ...
    expectedLuminance);
expectedRgb = double(fineOnly.output) + double(midOnly.output) - ...
    double(withoutRepair.output);
expectedRgb = min(max(expectedRgb, 0), 255);
rgbResidual = max(abs(double(complete.output) - expectedRgb), [], 3);
row = emptyRepairCombinationRow();
row.mode = mode.name;
row.completeRepairReconstructionMaxRgbDifference = ...
    complete.baselineDifferenceMax;
row.internalLuminanceAdditivityMean = mean(internalResidual(:));
row.internalLuminanceAdditivityP90 = percentileOn( ...
    internalResidual, true(size(internalResidual)), .90);
row.internalLuminanceAdditivityMax = max(internalResidual(:));
row.rgbSuperpositionResidualMean = mean(rgbResidual(:));
row.rgbSuperpositionResidualP90 = percentileOn( ...
    rgbResidual, true(size(rgbResidual)), .90);
row.rgbSuperpositionResidualMax = max(rgbResidual(:));
end

function item = findRepairComponent(components, name)
for index = 1:numel(components)
    if strcmp(components(index).name, name)
        item = components(index);
        return;
    end
end
error('diagnoseResidualFeatureArtifacts:MissingRepairComponent', ...
    '缺少 Repair 分量 %s。', name);
end

function ablation = runAblations(inputImage, frequency, beautyMasks, ...
        blemishMap, baseline, params, definitions)
processing = makeProcessing(baseline);
overrideCount = 0;
for index = 1:numel(definitions)
    overrideCount = overrideCount + ...
        (strcmp(definitions(index).kind, 'feature') || ...
        strcmp(definitions(index).kind, 'structure'));
end
items = repmat(emptyAblationItem(), 5 + 2 * overrideCount, 1);
itemIndex = 0;

[output, composeDetails] = beauty.composeBeautyResult(inputImage, ...
    frequency, baseline.smoothingResult, beautyMasks, ...
    params.whiteningStrength, processing);
itemIndex = itemIndex + 1;
items(itemIndex) = makeAblationItem('withoutRepair', output, ...
    false(size(beautyMasks.skinMask)), composeDetails, 'stage');

identityFrequency = makeIdentityFrequency(frequency);
[output, composeDetails] = beauty.composeBeautyResult(inputImage, ...
    frequency, identityFrequency, beautyMasks, ...
    params.whiteningStrength, processing);
itemIndex = itemIndex + 1;
items(itemIndex) = makeAblationItem( ...
    'withoutSmoothingAndRepair', output, ...
    false(size(beautyMasks.skinMask)), composeDetails, 'stage');

noBaseProcessing = processing;
noBaseProcessing.baseLuminance = zeroBaseResult( ...
    processing.baseLuminance, size(beautyMasks.skinMask));
[output, composeDetails] = beauty.composeBeautyResult(inputImage, ...
    frequency, baseline.repairResult, beautyMasks, ...
    params.whiteningStrength, noBaseProcessing);
itemIndex = itemIndex + 1;
items(itemIndex) = makeAblationItem('withoutBaseLuminance', output, ...
    false(size(beautyMasks.skinMask)), composeDetails, 'stage');

noToneProcessing = processing;
noToneProcessing.skinTone = zeroToneResult( ...
    processing.skinTone, inputImage, size(beautyMasks.skinMask));
[output, composeDetails] = beauty.composeBeautyResult(inputImage, ...
    frequency, baseline.repairResult, beautyMasks, ...
    params.whiteningStrength, noToneProcessing);
itemIndex = itemIndex + 1;
items(itemIndex) = makeAblationItem('withoutSkinTone', output, ...
    false(size(beautyMasks.skinMask)), composeDetails, 'stage');

noWhiteningProcessing = processing;
noWhiteningProcessing.whitening = zeroWhiteningResult( ...
    processing.whitening, size(beautyMasks.skinMask));
[output, composeDetails] = beauty.composeBeautyResult(inputImage, ...
    frequency, baseline.repairResult, beautyMasks, ...
    params.whiteningStrength, noWhiteningProcessing);
itemIndex = itemIndex + 1;
items(itemIndex) = makeAblationItem('withoutWhitening', output, ...
    false(size(beautyMasks.skinMask)), composeDetails, 'stage');

for index = 1:numel(definitions)
    definition = definitions(index);
    if ~strcmp(definition.kind, 'feature') && ...
            ~strcmp(definition.kind, 'structure')
        continue;
    end
    scope = regionMask(definition.roi, size(beautyMasks.skinMask));

    textureMasks = beautyMasks;
    textureMasks.textureProtectionMask = max( ...
        readMask(beautyMasks, 'textureProtectionMask', ...
        size(scope)), double(scope));
    [output, details] = runPipelineWithMasks(inputImage, frequency, ...
        textureMasks, blemishMap, params);
    itemIndex = itemIndex + 1;
    items(itemIndex) = makeAblationItem( ...
        ['forceTexture_' definition.name], output, scope, ...
        details.compose, 'protection');

    hardMasks = beautyMasks;
    hardMasks.hardProtectionMask = max( ...
        readMask(beautyMasks, 'hardProtectionMask', size(scope)), ...
        double(scope));
    [output, details] = runPipelineWithMasks(inputImage, frequency, ...
        hardMasks, blemishMap, params);
    itemIndex = itemIndex + 1;
    items(itemIndex) = makeAblationItem( ...
        ['forceHard_' definition.name], output, scope, ...
        details.compose, 'protection');
end
ablation.items = items(1:itemIndex);
end

function processing = makeProcessing(baseline)
processing = struct( ...
    'baseLuminance', baseline.baseLuminanceResult, ...
    'skinTone', baseline.skinToneResult, ...
    'whitening', baseline.whiteningResult);
end

function frequency = makeIdentityFrequency(frequency)
frequency.alphaMap = zeros(size(frequency.base));
frequency.outputLuminance = frequency.sourceLuminance;
frequency.reconstructedLuminance = frequency.sourceLuminance;
end

function result = zeroBaseResult(result, imageSize)
result.supportMap = zeros(imageSize);
result.baseSupport = zeros(imageSize);
result.alphaMap = zeros(imageSize);
result.baseDelta = zeros(imageSize);
result.delta = zeros(imageSize);
result.luminanceDelta = zeros(imageSize);
end

function result = zeroToneResult(result, inputImage, imageSize)
ycbcr = rgb2ycbcr(im2double(inputImage));
result.outputCb = ycbcr(:, :, 2);
result.outputCr = ycbcr(:, :, 3);
result.deltaCb = zeros(imageSize);
result.deltaCr = zeros(imageSize);
result.toneSupport = zeros(imageSize);
result.alphaMap = zeros(imageSize);
result.weightMap = zeros(imageSize);
end

function result = zeroWhiteningResult(result, imageSize)
result.supportMap = zeros(imageSize);
result.delta = zeros(imageSize);
result.alphaMap = zeros(imageSize);
end

function [output, details] = runPipelineWithMasks(inputImage, frequency, ...
        beautyMasks, blemishMap, params)
[smoothed, smoothingDiagnostics] = beauty.smoothSkinTexture( ...
    frequency, beautyMasks, params.smoothingStrength, blemishMap);
[repaired, repairDiagnostics] = beauty.repairSkinBlemishes( ...
    smoothed, beautyMasks, blemishMap, params.smoothingStrength);
[base, baseDiagnostics] = beauty.evenSkinLuminance( ...
    frequency, beautyMasks, params.smoothingStrength);
[skinTone, skinToneDiagnostics] = beauty.normalizeSkinTone( ...
    inputImage, frequency, beautyMasks, blemishMap, ...
    params.smoothingStrength);
[whitening, whiteningDiagnostics] = beauty.applySkinWhitening( ...
    inputImage, frequency, beautyMasks, params.whiteningStrength);
processing = struct( ...
    'baseLuminance', base, ...
    'skinTone', skinTone, ...
    'whitening', whitening);
[output, composeDiagnostics] = beauty.composeBeautyResult( ...
    inputImage, frequency, repaired, beautyMasks, ...
    params.whiteningStrength, processing);
details = struct( ...
    'smoothing', smoothingDiagnostics, ...
    'repair', repairDiagnostics, ...
    'base', baseDiagnostics, ...
    'skinTone', skinToneDiagnostics, ...
    'whitening', whiteningDiagnostics, ...
    'compose', composeDiagnostics);
end

function item = makeAblationItem(name, output, scopeMask, compose, kind)
item = emptyAblationItem();
item.name = name;
item.output = output;
item.scopeMask = scopeMask;
item.compose = compose;
item.kind = kind;
end

function row = measureRegion(mode, definition, beautyMasks, baseline, ...
        structureSources, safetyMasks)
imageSize = size(mode.image, 1:2);
roi = regionMask(definition.roi, imageSize);
regions = readSemanticStruct(mode.context, 'regions', imageSize);
confidence = readSemanticStruct(mode.context, ...
    'regionConfidence', imageSize);
semanticEvidence = semanticUnion(regions, confidence, ...
    definition.semanticNames);
semanticProbability = semanticUnion(regions, ...
    makeUnitConfidence(regions), definition.semanticNames);
semanticConfidence = semanticUnion(confidence, ...
    makeUnitConfidence(confidence), definition.semanticNames);
skin = readMask(beautyMasks, 'skinMask', imageSize);
faceSkin = readMask(beautyMasks, 'faceSkinMask', imageSize);
texture = readMask(beautyMasks, 'textureProtectionMask', imageSize);
structure = readMask(beautyMasks, 'structureProtectionMask', imageSize);
whitening = readMask(beautyMasks, ...
    'whiteningProtectionMask', imageSize);
chroma = readMask(beautyMasks, 'chromaProtectionMask', imageSize);
hard = readMask(beautyMasks, 'hardProtectionMask', imageSize);
smoothing = baseline.smoothing;
repair = baseline.repair;
sourceY = rgb2ycbcr(im2double(mode.image));
outputY = rgb2ycbcr(im2double(baseline.output));
stageMaps = makeStageMaps(baseline, mode);
stageNames = {'smoothing', 'repair', 'baseLuminance', ...
    'skinTone', 'whitening'};
stageMeans = zeros(1, numel(stageNames));
stageActive = false(1, numel(stageNames));
for index = 1:numel(stageNames)
    values = stageMaps.(stageNames{index});
    stageMeans(index) = meanOn(values, roi);
    stageActive(index) = any(values(roi) > 1e-6);
end
firstActiveStage = 'none';
activeIndex = find(stageActive, 1, 'first');
if ~isempty(activeIndex)
    firstActiveStage = stageNames{activeIndex};
end

row = emptyRegionRow();
row.mode = mode.name;
row.symptom = definition.name;
row.roiX = definition.roi(1);
row.roiY = definition.roi(2);
row.roiWidth = definition.roi(3);
row.roiHeight = definition.roi(4);
row.roiPixels = nnz(roi);
row.skinSupportPixels = nnz(roi & skin > .05);
row.faceSkinPixels = nnz(roi & faceSkin > .35);
row.skinSupportFraction = fractionOf(skin > .05, roi);
row.faceSkinFraction = fractionOf(faceSkin > .35, roi);
row.semanticProbabilityMean = meanOn(semanticProbability, roi);
row.semanticEvidenceMean = meanOn(semanticEvidence, roi);
row.semanticEvidenceP90 = percentileOn(semanticEvidence, roi, .90);
row.semanticEvidenceMax = maxOn(semanticEvidence, roi);
row.semanticConfidenceMean = meanOn(semanticConfidence, roi);
row.semanticCoreFraction = fractionOf(semanticEvidence >= .60, roi);
row.leftEyeEvidenceMax = maxOn(min(regions.leftEye, ...
    confidence.leftEye), roi);
row.rightEyeEvidenceMax = maxOn(min(regions.rightEye, ...
    confidence.rightEye), roi);
row.leftBrowEvidenceMax = maxOn(min(regions.leftBrow, ...
    confidence.leftBrow), roi);
row.rightBrowEvidenceMax = maxOn(min(regions.rightBrow, ...
    confidence.rightBrow), roi);
row.blemishMean = meanOn(baseline.blemishMap, roi);
row.textureProtectionMean = meanOn(texture, roi);
row.textureProtectionP90 = percentileOn(texture, roi, .90);
row.structureProtectionMean = meanOn(structure, roi);
row.structureProtectionP90 = percentileOn(structure, roi, .90);
row.whiteningProtectionMean = meanOn(whitening, roi);
row.chromaProtectionMean = meanOn(chroma, roi);
row.hardProtectionFraction = fractionOf(hard >= .999, roi);
row.fineStructureGateMean = meanOn(smoothing.fineStructureGate, roi);
row.fineStructureGateZeroFraction = fractionOf( ...
    smoothing.fineStructureGate <= 1e-12, roi);
row.fineStructureGatePartialFraction = fractionOf( ...
    smoothing.fineStructureGate > 1e-12 & ...
    smoothing.fineStructureGate < 1 - 1e-12, roi);
row.midStructureGateMean = meanOn(smoothing.midStructureGate, roi);
row.midStructureGateZeroFraction = fractionOf( ...
    smoothing.midStructureGate <= 1e-12, roi);
row.midStructureGatePartialFraction = fractionOf( ...
    smoothing.midStructureGate > 1e-12 & ...
    smoothing.midStructureGate < 1 - 1e-12, roi);
row.repairAllowedMean = meanOn(repair.allowed, roi);
row.repairStructureGateMean = meanOn(repair.structureGate, roi);
row.repairTextureGateMean = meanOn(repair.textureGate, roi);
row.repairTextureGateZeroFraction = fractionOf( ...
    repair.textureGate <= 1e-12, roi);
row.smoothingFineActionMean = meanOn(stageMaps.smoothingFine, roi);
row.smoothingFineActionP90 = percentileOn(stageMaps.smoothingFine, roi, .90);
row.smoothingFineActiveFraction = fractionOf( ...
    stageMaps.smoothingFine > 1e-6, roi);
row.smoothingMidActionMean = meanOn(stageMaps.smoothingMid, roi);
row.smoothingMidActionP90 = percentileOn(stageMaps.smoothingMid, roi, .90);
row.smoothingMidActiveFraction = fractionOf( ...
    stageMaps.smoothingMid > 1e-6, roi);
row.repairFineActionMean = meanOn(stageMaps.repairFine, roi);
row.repairFineActionP90 = percentileOn(stageMaps.repairFine, roi, .90);
row.repairFineActiveFraction = fractionOf( ...
    stageMaps.repairFine > 1e-6, roi);
row.repairMidActionMean = meanOn(stageMaps.repairMid, roi);
row.repairMidActionP90 = percentileOn(stageMaps.repairMid, roi, .90);
row.repairMidActiveFraction = fractionOf( ...
    stageMaps.repairMid > 1e-6, roi);
row.repairEvidenceMean = meanOn(repair.repairEvidence, roi);
blemishEnergyBefore = (abs(repair.fineBefore) + ...
    abs(repair.midBefore)) .* baseline.blemishMap;
blemishEnergyAfter = (abs(repair.fineAfter) + ...
    abs(repair.midAfter)) .* baseline.blemishMap;
row.repairBlemishEnergyBeforeMean = meanOn(blemishEnergyBefore, roi);
row.repairBlemishEnergyAfterMean = meanOn(blemishEnergyAfter, roi);
row.repairBlemishEnergyReductionRatio = 1 - safeRatio( ...
    row.repairBlemishEnergyAfterMean, ...
    row.repairBlemishEnergyBeforeMean);
row.baseLuminanceActionMean = meanOn(stageMaps.baseLuminance, roi);
row.baseLuminanceActionP90 = percentileOn(stageMaps.baseLuminance, roi, .90);
row.baseLuminanceActiveFraction = fractionOf( ...
    stageMaps.baseLuminance > 1e-6, roi);
row.whiteningLuminanceActionMean = meanOn(stageMaps.whitening, roi);
row.whiteningLuminanceActionP90 = percentileOn(stageMaps.whitening, roi, .90);
row.whiteningLuminanceActiveFraction = fractionOf( ...
    stageMaps.whitening > 1e-6, roi);
row.toneChromaActionMean = meanOn(stageMaps.skinTone, roi);
row.toneChromaActionP90 = percentileOn(stageMaps.skinTone, roi, .90);
row.toneChromaActiveFraction = fractionOf( ...
    stageMaps.skinTone > 1e-6, roi);
row.firstActiveStage = firstActiveStage;
row.stageSmoothingMean = stageMeans(1);
row.stageRepairMean = stageMeans(2);
row.stageBaseLuminanceMean = stageMeans(3);
row.stageSkinToneMean = stageMeans(4);
row.stageWhiteningMean = stageMeans(5);
row.fineInputEnergyMean = meanOn(abs(smoothing.fineBefore), roi);
row.fineAfterSmoothingEnergyMean = meanOn(abs(smoothing.fineAfter), roi);
row.fineAfterRepairEnergyMean = meanOn(abs(repair.fineAfter), roi);
row.midInputEnergyMean = meanOn(abs(smoothing.midBefore), roi);
row.midAfterSmoothingEnergyMean = meanOn(abs(smoothing.midAfter), roi);
row.midAfterRepairEnergyMean = meanOn(abs(repair.midAfter), roi);
row.fineSmoothingRetentionRatio = safeRatio( ...
    row.fineAfterSmoothingEnergyMean, row.fineInputEnergyMean);
row.fineRepairRetentionRatio = safeRatio( ...
    row.fineAfterRepairEnergyMean, row.fineAfterSmoothingEnergyMean);
row.midSmoothingRetentionRatio = safeRatio( ...
    row.midAfterSmoothingEnergyMean, row.midInputEnergyMean);
row.midRepairRetentionRatio = safeRatio( ...
    row.midAfterRepairEnergyMean, row.midAfterSmoothingEnergyMean);
lowBefore = double(baseline.frequency.base) + ...
    double(baseline.frequency.mid);
lowAfter = double(baseline.frequency.base) + ...
    double(repair.midAfter);
beforeGradient = lowFrequencyGradient(lowBefore);
afterGradient = lowFrequencyGradient(lowAfter);
row.structureGradientBeforeMean = meanOn(beforeGradient, roi);
row.structureGradientAfterMean = meanOn(afterGradient, roi);
row.structureGradientRetentionRatio = safeRatio( ...
    row.structureGradientAfterMean, row.structureGradientBeforeMean);
row.nostrilTextureCoreFraction = fractionOf( ...
    diagnosticMask(baseline.mask.texture, 'nostrilCore', imageSize), roi);
row.nostrilTextureBoundaryFraction = fractionOf( ...
    diagnosticMask(baseline.mask.texture, 'nostrilBoundary', imageSize), roi);
row.nostrilToneCandidateFraction = fractionOf( ...
    diagnosticMask(baseline.mask.chroma, 'nostrilCandidate', imageSize), roi);
row.nostrilWhiteningCoreFraction = fractionOf( ...
    diagnosticMask(baseline.mask.whitening, 'nostrilCore', imageSize), roi);
row.nostrilDetectorDisagreementFraction = fractionOf( ...
    diagnosticMask(baseline.mask.texture, 'nostrilCore', imageSize) ~= ...
    diagnosticMask(baseline.mask.chroma, 'nostrilCandidate', imageSize), roi);
row.noseSemanticExcluded = double(readLogicalField( ...
    baseline.mask.chroma, 'noseSemanticExcluded'));
row.occluderProtectionMean = meanOn(diagnosticArray( ...
    baseline.mask.texture, 'occluderProtection', imageSize), roi);
row.browProtectionMean = meanOn(diagnosticArray( ...
    baseline.mask.texture, 'browProtection', imageSize), roi);
row.lipProtectionMean = meanOn(diagnosticArray( ...
    baseline.mask.texture, 'lipProtection', imageSize), roi);
row.noseProtectionMean = meanOn(diagnosticArray( ...
    baseline.mask.texture, 'noseProtection', imageSize), roi);
row.eyeDetailProtectionMean = meanOn(diagnosticArray( ...
    baseline.mask.texture, 'eyeDetailProtection', imageSize), roi);
row.periocularProtectionMean = meanOn(diagnosticArray( ...
    baseline.mask.texture, 'periocularProtection', imageSize), roi);
row.doubleEyelidProtectionMean = meanOn(diagnosticArray( ...
    baseline.mask.texture, 'doubleEyelidProtection', imageSize), roi);
row.lashProtectionMean = meanOn(diagnosticArray( ...
    baseline.mask.texture, 'lashProtection', imageSize), roi);
row.structureReconstructionMaxError = ...
    structureSources.reconstructionMaxError;
row.noseStructureMean = meanOn( ...
    structureSources.sources.noseStructure, roi);
row.outsideStructureMean = meanOn( ...
    structureSources.sources.outsideStructure, roi);
row.faceStructureMean = meanOn( ...
    structureSources.sources.faceStructure, roi);
row.faceBoundaryMean = meanOn( ...
    structureSources.sources.faceBoundary, roi);
dominance = structureSourceFractions(structureSources.dominant, roi);
row.noseStructureDominantFraction = dominance(1);
row.outsideStructureDominantFraction = dominance(2);
row.faceStructureDominantFraction = dominance(3);
row.faceBoundaryDominantFraction = dominance(4);
row.structureTieFraction = fractionOf(structureSources.tieMask, roi);
row.dominantStructureSource = dominantSourceName( ...
    dominance, structureSources.names);
finalRgbChange = max(abs(double(baseline.output) - ...
    double(mode.image)), [], 3);
row.finalRgbChangeMean = meanOn(finalRgbChange, roi);
row.finalRgbChangeP90 = percentileOn(finalRgbChange, roi, .90);
row.finalRgbChangeMax = maxOn(finalRgbChange, roi);
row.finalRgbActiveFraction = fractionOf(finalRgbChange > 0, roi);
row.finalLuminanceChangeMean = meanOn( ...
    abs(outputY(:, :, 1) - sourceY(:, :, 1)), roi);
row.hardProtectionMaxRgbChange = maxOn(finalRgbChange, ...
    safetyMasks.hard);
row.hairMaxRgbChange = maxOn(finalRgbChange, safetyMasks.hair);
row.backgroundMaxRgbChange = maxOn(finalRgbChange, safetyMasks.background);
row.safetyHairPixels = nnz(safetyMasks.hair);
row.safetyBackgroundPixels = nnz(safetyMasks.background);
row.safetyHardPixels = nnz(safetyMasks.hard);
end

function stageMaps = makeStageMaps(baseline, mode)
smoothing = baseline.smoothing;
repair = baseline.repair;
compose = baseline.compose;
stageMaps = struct( ...
    'smoothingFine', abs(smoothing.fineAfter - smoothing.fineBefore), ...
    'smoothingMid', abs(smoothing.midAfter - smoothing.midBefore), ...
    'repairFine', abs(repair.fineCorrection), ...
    'repairMid', abs(repair.mediumCorrection), ...
    'smoothing', abs(smoothing.fineAfter - smoothing.fineBefore) + ...
    abs(smoothing.midAfter - smoothing.midBefore), ...
    'repair', abs(repair.fineCorrection) + ...
    abs(repair.mediumCorrection), ...
    'baseLuminance', abs(compose.baseDelta), ...
    'skinTone', max(abs(cat(3, compose.toneDeltaCb, ...
    compose.toneDeltaCr)), [], 3), ...
    'whitening', abs(compose.whiteningDelta), ...
    'final', max(abs(double(baseline.output) - ...
    double(mode.image)), [], 3));
end

function row = measureAblation(mode, definition, item, baseline, safetyMasks)
imageSize = size(mode.image, 1:2);
roi = regionMask(definition.roi, imageSize);
baselineOutput = baseline.output;
change = max(abs(double(item.output) - double(baselineOutput)), [], 3);
baselineY = rgb2ycbcr(im2double(baselineOutput));
ablatedY = rgb2ycbcr(im2double(item.output));
row = emptyAblationRow();
row.mode = mode.name;
row.symptom = definition.name;
row.ablation = item.name;
row.kind = item.kind;
row.scopePixels = nnz(item.scopeMask);
row.roiPixels = nnz(roi);
row.finalRgbDifferenceMean = meanOn(change, roi);
row.finalRgbDifferenceP90 = percentileOn(change, roi, .90);
row.finalRgbDifferenceMax = maxOn(change, roi);
row.finalLuminanceDifferenceMean = meanOn( ...
    abs(ablatedY(:, :, 1) - baselineY(:, :, 1)), roi);
row.hairMaxRgbDifference = maxOn(change, safetyMasks.hair);
row.backgroundMaxRgbDifference = maxOn(change, safetyMasks.background);
row.hardProtectionMaxRgbDifference = maxOn(change, safetyMasks.hard);
row.scopeOutputRgbChangeMean = meanOn( ...
    max(abs(double(item.output) - double(mode.image)), [], 3), ...
    item.scopeMask);
row.scopeOutputRgbChangeMax = maxOn( ...
    max(abs(double(item.output) - double(mode.image)), [], 3), ...
    item.scopeMask);
end

function safety = buildSafetyMasks(context, definitions, beautyMasks)
imageSize = size(beautyMasks.skinMask);
safety = struct();
hairDefinition = findDefinition(definitions, 'hair');
backgroundDefinition = findDefinition(definitions, 'background');
if isempty(hairDefinition)
    regions = readSemanticStruct(context, 'regions', imageSize);
    confidence = readSemanticStruct(context, ...
        'regionConfidence', imageSize);
    safety.hair = semanticUnion(regions, confidence, {'hair'}) >= .45;
else
    safety.hair = regionMask(hairDefinition.roi, imageSize);
end
if isempty(backgroundDefinition)
    regions = readSemanticStruct(context, 'regions', imageSize);
    confidence = readSemanticStruct(context, ...
        'regionConfidence', imageSize);
    safety.background = semanticUnion(regions, confidence, ...
        {'background'}) >= .45;
else
    safety.background = regionMask(backgroundDefinition.roi, imageSize);
end
safety.hard = readMask(beautyMasks, 'hardProtectionMask', imageSize) >= .999;
end

function definition = findDefinition(definitions, name)
definition = [];
for index = 1:numel(definitions)
    if strcmp(definitions(index).name, name)
        definition = definitions(index);
        return;
    end
end
end

function values = structureSourceFractions(dominant, roi)
values = zeros(1, 4);
valid = roi & dominant > 0;
if ~any(valid(:))
    values(:) = NaN;
    return;
end
for index = 1:4
    values(index) = fractionOf(dominant == index, valid);
end
end

function name = dominantSourceName(fractions, names)
if all(isnan(fractions))
    name = '未适用';
    return;
end
maximum = max(fractions, [], 'omitnan');
if nnz(abs(fractions - maximum) <= 1e-12) ~= 1
    name = '并列';
else
    name = names{find(abs(fractions - maximum) <= 1e-12, 1)};
end
end

function semantics = readSemanticStruct(context, fieldName, imageSize)
names = faceParsingClassNames();
if ~isstruct(context) || ~isfield(context, fieldName) || ...
        ~isstruct(context.(fieldName)) || ...
        ~isscalar(context.(fieldName))
    error('diagnoseResidualFeatureArtifacts:MissingDiagnosticField', ...
        'Beauty Context 缺少语义字段 %s。', fieldName);
end
source = context.(fieldName);
semantics = struct();
for index = 1:numel(names)
    name = names{index};
    if ~isfield(source, name)
        error('diagnoseResidualFeatureArtifacts:MissingDiagnosticField', ...
            'Beauty Context 的 %s 缺少语义字段 %s。', fieldName, name);
    end
    sourceValue = source.(name);
    if ~isnumeric(sourceValue) || ~isreal(sourceValue) || ...
            ~isequal(size(sourceValue), imageSize) || ...
            any(~isfinite(sourceValue(:)))
        error('diagnoseResidualFeatureArtifacts:InvalidDiagnosticArray', ...
            'Beauty Context 的 %s.%s 尺寸或取值无效。', fieldName, name);
    end
    semantics.(name) = double(sourceValue);
end
end

function confidence = makeUnitConfidence(semantics)
confidence = semantics;
names = fieldnames(semantics);
for index = 1:numel(names)
    confidence.(names{index}) = ones(size(semantics.(names{index})));
end
end

function evidence = semanticUnion(regions, confidence, names)
evidence = zeros(size(regions.(names{1})));
for index = 1:numel(names)
    evidence = max(evidence, min(double(regions.(names{index})), ...
        double(confidence.(names{index}))));
end
evidence = min(max(evidence, 0), 1);
end

function values = readSemanticEvidence(context, names, imageSize)
regions = readSemanticStruct(context, 'regions', imageSize);
confidence = readSemanticStruct(context, ...
    'regionConfidence', imageSize);
values = semanticUnion(regions, confidence, names);
end

function value = readLogicalField(value, name)
if ~isfield(value, name)
    error('diagnoseResidualFeatureArtifacts:MissingDiagnosticField', ...
        '诊断结构缺少逻辑字段 %s。', name);
end
value = logical(value.(name));
if ~isscalar(value)
    value = any(value(:));
end
end

function value = diagnosticMask(diagnostics, name, imageSize)
if ~isstruct(diagnostics) || ~isfield(diagnostics, name)
    error('diagnoseResidualFeatureArtifacts:MissingDiagnosticField', ...
        '诊断结构缺少 Mask 字段 %s。', name);
end
value = diagnostics.(name);
if (~isnumeric(value) && ~islogical(value)) || ~isreal(value) || ...
        ~isequal(size(value), imageSize) || any(~isfinite(value(:)))
    error('diagnoseResidualFeatureArtifacts:InvalidDiagnosticMask', ...
        '诊断字段 %s 的尺寸或取值无效。', name);
end
value = value >= .5;
end

function value = diagnosticArray(diagnostics, name, imageSize)
if ~isstruct(diagnostics) || ~isfield(diagnostics, name)
    error('diagnoseResidualFeatureArtifacts:MissingDiagnosticField', ...
        '诊断结构缺少数组字段 %s。', name);
end
value = readArray(diagnostics.(name), imageSize, name);
end

function value = readArray(value, imageSize, name)
if ~isnumeric(value) || ~isreal(value) || ...
        ~isequal(size(value), imageSize) || any(~isfinite(value(:)))
    error('diagnoseResidualFeatureArtifacts:InvalidDiagnosticArray', ...
        '诊断数组 %s 的尺寸或取值无效。', name);
end
value = double(value);
end

function value = readMask(context, name, imageSize)
if ~isfield(context, name)
    error('diagnoseResidualFeatureArtifacts:MissingMask', ...
        'Beauty Masks 缺少字段 %s。', name);
end
value = context.(name);
if (~isnumeric(value) && ~islogical(value)) || ~isreal(value) || ...
        ~isequal(size(value), imageSize) || any(~isfinite(value(:))) || ...
        any(value(:) < 0) || any(value(:) > 1)
    error('diagnoseResidualFeatureArtifacts:InvalidMask', ...
        'Beauty Masks 字段 %s 无效。', name);
end
value = double(value);
end

function paths = writeArtifacts(outputFolder, modeDiagnostics, ...
        regionMetrics, ablationMetrics, repairComponentMetrics, ...
        repairCombinationMetrics, imageMetrics)
writetable(regionMetrics, fullfile(outputFolder, ...
    'residualFeatureRegionMetrics.csv'));
writetable(ablationMetrics, fullfile(outputFolder, ...
    'residualFeatureAblationMetrics.csv'));
writetable(repairComponentMetrics, fullfile(outputFolder, ...
    'residualFeatureRepairComponentMetrics.csv'));
writetable(repairCombinationMetrics, fullfile(outputFolder, ...
    'residualFeatureRepairCombinationMetrics.csv'));
writetable(imageMetrics, fullfile(outputFolder, ...
    'residualFeatureImageMetrics.csv'));
paths = struct();
for index = 1:numel(modeDiagnostics)
    mode = modeDiagnostics{index};
    comparePath = fullfile(outputFolder, ...
        [mode.name '-residualFeatureCompare.png']);
    mapsPath = fullfile(outputFolder, ...
        [mode.name '-residualFeatureMaps.png']);
    ablationPath = fullfile(outputFolder, ...
        [mode.name '-residualFeatureAblation.png']);
    repairComponentPath = fullfile(outputFolder, ...
        [mode.name '-residualFeatureRepairComponents.png']);
    writeComparisonFigure(mode, comparePath);
    writeMapsFigure(mode, mapsPath);
    writeAblationFigure(mode, ablationPath);
    writeRepairComponentFigure(mode, repairComponentPath);
    paths.(mode.name) = struct('compare', comparePath, ...
        'maps', mapsPath, 'ablation', ablationPath, ...
        'repairComponents', repairComponentPath);
end
paths.regionMetrics = fullfile(outputFolder, ...
    'residualFeatureRegionMetrics.csv');
paths.ablationMetrics = fullfile(outputFolder, ...
    'residualFeatureAblationMetrics.csv');
paths.repairComponentMetrics = fullfile(outputFolder, ...
    'residualFeatureRepairComponentMetrics.csv');
paths.repairCombinationMetrics = fullfile(outputFolder, ...
    'residualFeatureRepairCombinationMetrics.csv');
paths.imageMetrics = fullfile(outputFolder, ...
    'residualFeatureImageMetrics.csv');
end

function writeComparisonFigure(mode, outputPath)
featureDefinitions = mode.definitions(strcmp({mode.definitions.kind}, ...
    'feature'));
tileCount = max(3, 3 + numel(featureDefinitions));
figureHandle = figure('Visible', 'off', 'Color', 'white');
tiledlayout(2, ceil(tileCount / 2), ...
    'Padding', 'compact', 'TileSpacing', 'compact');
nexttile;
imshow(mode.image);
title('输入');
drawRois(mode);
nexttile;
imshow(mode.output);
title('v3.2 基线输出');
drawRois(mode);
nexttile;
difference = max(abs(double(mode.output) - double(mode.image)), [], 3);
imagesc(difference);
axis image off;
clim([0, 32]);
colorbar;
title('最终 RGB 变化（0--32）');
drawRois(mode);
for index = 1:numel(featureDefinitions)
    nexttile;
    imshow(cropImage(mode.output, featureDefinitions(index).roi));
    title([featureDefinitions(index).name '局部']);
end
exportgraphics(figureHandle, outputPath, 'Resolution', 140);
close(figureHandle);
end

function writeMapsFigure(mode, outputPath)
baseline = mode.baseline;
maps = { ...
    mode.context.skinMask, mode.context.faceSkinMask, ...
    readSemanticEvidence(mode.context, {'leftEar', 'rightEar'}, ...
    size(mode.image, 1:2)), ...
    readSemanticEvidence(mode.context, ...
    {'leftBrow', 'rightBrow', 'leftEye', 'rightEye'}, ...
    size(mode.image, 1:2)), ...
    baseline.beautyMasks.textureProtectionMask, ...
    baseline.beautyMasks.structureProtectionMask, ...
    baseline.beautyMasks.hardProtectionMask, ...
    baseline.beautyMasks.whiteningProtectionMask, ...
    baseline.beautyMasks.chromaProtectionMask, ...
    baseline.blemishMap, ...
    abs(baseline.smoothing.fineAfter - baseline.smoothing.fineBefore), ...
    abs(baseline.smoothing.midAfter - baseline.smoothing.midBefore), ...
    abs(baseline.repair.fineCorrection), ...
    abs(baseline.repair.mediumCorrection), ...
    abs(baseline.compose.baseDelta), ...
    abs(baseline.compose.whiteningDelta), ...
    max(abs(cat(3, baseline.compose.toneDeltaCb, ...
    baseline.compose.toneDeltaCr)), [], 3), ...
    max(abs(double(mode.output) - double(mode.image)), [], 3)};
labels = {'皮肤支持', '脸部皮肤', '耳部语义', '眉眼语义', ...
    '纹理保护', '结构保护', '硬保护', '美白保护', '色度保护', ...
    '瑕疵图', '平滑 Fine 作用量', '平滑 Mid 作用量', ...
    'Repair Fine 作用量', 'Repair Mid 作用量', 'Base 作用量', ...
    '美白作用量', '色度作用量', '最终 RGB 变化'};
figureHandle = figure('Visible', 'off', 'Color', 'white', ...
    'Position', [100, 100, 1800, 1000]);
tiledlayout(3, 6, 'Padding', 'compact', 'TileSpacing', 'compact');
for index = 1:numel(maps)
    nexttile;
    imagesc(maps{index});
    axis image off;
    colorbar;
    if index == numel(maps)
        clim([0, 32]);
    else
        clim([0, 1]);
    end
    title(labels{index});
    drawRois(mode);
end
exportgraphics(figureHandle, outputPath, 'Resolution', 140);
close(figureHandle);
end

function writeAblationFigure(mode, outputPath)
featureDefinitions = mode.definitions(strcmp({mode.definitions.kind}, ...
    'feature'));
columnLabels = {'v3.2 基线', '禁用 Repair', '注入纹理保护', ...
    '注入硬保护'};
figureHandle = figure('Visible', 'off', 'Color', 'white');
tiledlayout(max(1, numel(featureDefinitions)), 4, ...
    'Padding', 'compact', 'TileSpacing', 'compact');
for index = 1:numel(featureDefinitions)
    definition = featureDefinitions(index);
    names = {'', 'withoutRepair', ...
        ['forceTexture_' definition.name], ...
        ['forceHard_' definition.name]};
    for column = 1:numel(names)
        nexttile;
        if column == 1
            image = mode.output;
        else
            item = findAblation(mode.ablation.items, names{column});
            image = item.output;
        end
        imshow(cropImage(image, definition.roi));
        if index == 1
            title(columnLabels{column});
        end
        if column == 1
            ylabel(definition.name, 'Interpreter', 'none');
        end
    end
end
exportgraphics(figureHandle, outputPath, 'Resolution', 140);
close(figureHandle);
end

function writeRepairComponentFigure(mode, outputPath)
featureDefinitions = mode.definitions(strcmp({mode.definitions.kind}, ...
    'feature'));
if isempty(featureDefinitions)
    return;
end
columnLabels = {'原图', '基线输出', '完整 Repair', '仅 Fine', ...
    '仅 Mid', '无 Repair'};
figureHandle = figure('Visible', 'off', 'Color', 'white', ...
    'Position', [100, 100, 1800, max(360, 300 * numel(featureDefinitions))]);
tiledlayout(numel(featureDefinitions), numel(columnLabels), ...
    'Padding', 'compact', 'TileSpacing', 'compact');
for index = 1:numel(featureDefinitions)
    definition = featureDefinitions(index);
    names = {'', '', 'completeRepair', 'fineOnly', ...
        'midOnly', 'withoutRepair'};
    for column = 1:numel(names)
        nexttile;
        if column == 1
            image = mode.image;
        elseif column == 2
            image = mode.output;
        else
            component = findRepairComponent(mode.repairComponents, ...
                names{column});
            image = component.output;
        end
        imshow(cropImage(image, definition.roi));
        title(columnLabels{column});
        if column == 1
            ylabel(definition.name, 'Interpreter', 'none');
        end
    end
end
exportgraphics(figureHandle, outputPath, 'Resolution', 140);
close(figureHandle);
end

function item = findAblation(items, name)
for index = 1:numel(items)
    if strcmp(items(index).name, name)
        item = items(index);
        return;
    end
end
error('diagnoseResidualFeatureArtifacts:MissingAblation', ...
    '缺少诊断消融 %s。', name);
end

function image = cropImage(image, box)
imageSize = size(image, 1:2);
x1 = max(1, box(1));
y1 = max(1, box(2));
x2 = min(imageSize(2), box(1) + box(3) - 1);
y2 = min(imageSize(1), box(2) + box(4) - 1);
image = image(y1:y2, x1:x2, :);
end

function drawRois(mode)
hold on;
for index = 1:numel(mode.definitions)
    definition = mode.definitions(index);
    switch definition.kind
        case 'feature'
            color = 'c';
        case 'structure'
            color = 'y';
        case 'reference'
            color = 'm';
        otherwise
            color = 'w';
    end
    rectangle('Position', definition.roi, ...
        'EdgeColor', color, 'LineWidth', 1.2);
end
hold off;
end

function values = compactModeDiagnostics(modeDiagnostics)
values = cell(size(modeDiagnostics));
for index = 1:numel(modeDiagnostics)
    mode = modeDiagnostics{index};
    baseline = mode.baseline;
    maps = struct( ...
        'skinMask', compactArray(mode.context.skinMask), ...
        'faceSkinMask', compactArray(mode.context.faceSkinMask), ...
        'textureProtectionMask', compactArray( ...
        baseline.beautyMasks.textureProtectionMask), ...
        'structureProtectionMask', compactArray( ...
        baseline.beautyMasks.structureProtectionMask), ...
        'hardProtectionMask', compactArray( ...
        baseline.beautyMasks.hardProtectionMask), ...
        'whiteningProtectionMask', compactArray( ...
        baseline.beautyMasks.whiteningProtectionMask), ...
        'chromaProtectionMask', compactArray( ...
        baseline.beautyMasks.chromaProtectionMask), ...
        'smoothingFineAction', compactArray( ...
        abs(baseline.smoothing.fineAfter - ...
        baseline.smoothing.fineBefore)), ...
        'smoothingMidAction', compactArray( ...
        abs(baseline.smoothing.midAfter - ...
        baseline.smoothing.midBefore)), ...
        'repairFineAction', compactArray( ...
        abs(baseline.repair.fineCorrection)), ...
        'repairMidAction', compactArray( ...
        abs(baseline.repair.mediumCorrection)), ...
        'baseLuminanceAction', compactArray( ...
        abs(baseline.compose.baseDelta)), ...
        'whiteningAction', compactArray( ...
        abs(baseline.compose.whiteningDelta)), ...
        'toneAction', compactArray(max(abs(cat(3, ...
        baseline.compose.toneDeltaCb, baseline.compose.toneDeltaCr)), ...
        [], 3)), ...
        'finalRgbChange', compactArray(max(abs(double(mode.output) - ...
        double(mode.image)), [], 3)));
    repairComponents = compactRepairComponents(mode.repairComponents);
    values{index} = struct( ...
        'name', mode.name, ...
        'image', mode.image, ...
        'output', mode.output, ...
        'faceBox', mode.faceBox, ...
        'definitions', mode.definitions, ...
        'imageMetrics', mode.imageMetrics, ...
        'maps', maps, ...
        'repairComponents', repairComponents, ...
        'repairCombination', mode.repairCombination, ...
        'structureSources', compactStructureSources(mode.structureSources), ...
        'safetyMasks', mode.safetyMasks);
end
end

function value = compactRepairComponents(components)
value = repmat(struct('name', '', 'output', []), size(components));
for index = 1:numel(components)
    value(index).name = components(index).name;
    value(index).output = components(index).output;
end
end

function value = compactStructureSources(structure)
value = structure;
value.sourceStack = compactArray(value.sourceStack);
value.reconstructed = compactArray(value.reconstructed);
value.baseline = compactArray(value.baseline);
value.dominant = uint8(value.dominant);
value.tieMask = logical(value.tieMask);
sourceNames = fieldnames(value.sources);
for index = 1:numel(sourceNames)
    name = sourceNames{index};
    value.sources.(name) = compactArray(value.sources.(name));
end
end

function value = compactDetection(detection)
value = detection;
if isfield(value, 'selectedParsing')
    value = rmfield(value, 'selectedParsing');
end
end

function value = compactArray(value)
if isnumeric(value) && ~isa(value, 'uint8') && ~isa(value, 'single')
    value = single(value);
end
end

function definitions = scaleDefinitions(definitions, scale, imageSize)
for index = 1:numel(definitions)
    definitions(index).roi = scaleRoi(definitions(index).roi, ...
        scale, imageSize);
end
end

function roi = regionMask(box, imageSize)
roi = false(imageSize(1), imageSize(2));
x1 = max(1, box(1));
y1 = max(1, box(2));
x2 = min(imageSize(2), box(1) + box(3) - 1);
y2 = min(imageSize(1), box(2) + box(4) - 1);
roi(y1:y2, x1:x2) = true;
end

function value = meanOn(data, mask)
values = double(data(mask));
if isempty(values)
    value = NaN;
else
    value = mean(values);
end
end

function value = percentileOn(data, mask, fraction)
values = sort(double(data(mask)));
if isempty(values)
    value = NaN;
    return;
end
position = 1 + fraction * (numel(values) - 1);
lower = floor(position);
upper = ceil(position);
if lower == upper
    value = values(lower);
else
    weight = position - lower;
    value = (1 - weight) * values(lower) + weight * values(upper);
end
end

function value = fractionOf(condition, mask)
count = nnz(mask);
if count == 0
    value = NaN;
else
    value = nnz(condition & mask) / count;
end
end

function value = maxOn(data, mask)
values = double(data(mask));
if isempty(values)
    value = NaN;
else
    value = max(values);
end
end

function value = safeRatio(numerator, denominator)
if isempty(numerator) || isempty(denominator) || ...
        ~isfinite(numerator) || ~isfinite(denominator) || ...
        denominator <= 1e-12
    value = NaN;
else
    value = numerator / denominator;
end
end

function value = lowFrequencyGradient(image)
[gradientX, gradientY] = gradient(double(image));
value = hypot(gradientX, gradientY);
end

function box = validateRoi(box, name)
if ~isnumeric(box) || ~isreal(box) || ~isequal(size(box), [1, 4]) || ...
        any(~isfinite(box)) || any(box(1:2) < 1) || ...
        any(box(3:4) < 1)
    error('diagnoseResidualFeatureArtifacts:InvalidRoi', ...
        '%s 必须是正整数 [x y width height]。', name);
end
box = round(double(box));
end

function box = validateRoiBounds(box, imageSize, name)
if box(1) + box(3) - 1 > imageSize(2) || ...
        box(2) + box(4) - 1 > imageSize(1)
    error('diagnoseResidualFeatureArtifacts:InvalidRoi', ...
        '%s 超出输入图像范围。', name);
end
end

function box = scaleRoi(sourceBox, scale, imageSize)
box = round(double(sourceBox) * scale);
box(1:2) = max(box(1:2), 1);
x2 = min(imageSize(2), box(1) + box(3) - 1);
y2 = min(imageSize(1), box(2) + box(4) - 1);
box(3:4) = max(1, [x2 - box(1) + 1, y2 - box(2) + 1]);
end

function [preview, scale] = makePreview(image)
scale = min(1, 640 / max(size(image, 1), size(image, 2)));
if scale < 1
    preview = imresize(image, scale, 'bilinear');
else
    preview = image;
end
end

function box = scaleFaceBox(box, scale, imageSize)
box = round(double(box) * scale);
box(1) = max(1, min(box(1), imageSize(2)));
box(2) = max(1, min(box(2), imageSize(1)));
x2 = min(imageSize(2), box(1) + box(3) - 1);
y2 = min(imageSize(1), box(2) + box(4) - 1);
box(3:4) = max(1, [x2 - box(1) + 1, y2 - box(2) + 1]);
end

function value = isValidStrength(value)
value = isnumeric(value) && isreal(value) && isscalar(value) && ...
    isfinite(value) && value >= 0 && value <= 100;
end

function row = emptyRegionRow
row = struct( ...
    'mode', '', 'symptom', '', 'roiX', 0, 'roiY', 0, ...
    'roiWidth', 0, 'roiHeight', 0, 'roiPixels', 0, ...
    'skinSupportPixels', 0, 'faceSkinPixels', 0, ...
    'skinSupportFraction', NaN, 'faceSkinFraction', NaN, ...
    'semanticProbabilityMean', NaN, 'semanticEvidenceMean', NaN, ...
    'semanticEvidenceP90', NaN, 'semanticEvidenceMax', NaN, ...
    'semanticConfidenceMean', NaN, 'semanticCoreFraction', NaN, ...
    'leftEyeEvidenceMax', NaN, 'rightEyeEvidenceMax', NaN, ...
    'leftBrowEvidenceMax', NaN, 'rightBrowEvidenceMax', NaN, ...
    'blemishMean', NaN, 'textureProtectionMean', NaN, ...
    'textureProtectionP90', NaN, 'structureProtectionMean', NaN, ...
    'structureProtectionP90', NaN, 'whiteningProtectionMean', NaN, ...
    'chromaProtectionMean', NaN, 'hardProtectionFraction', NaN, ...
    'fineStructureGateMean', NaN, 'fineStructureGateZeroFraction', NaN, ...
    'fineStructureGatePartialFraction', NaN, 'midStructureGateMean', NaN, ...
    'midStructureGateZeroFraction', NaN, ...
    'midStructureGatePartialFraction', NaN, ...
    'repairAllowedMean', NaN, 'repairStructureGateMean', NaN, ...
    'repairTextureGateMean', NaN, 'repairTextureGateZeroFraction', NaN, ...
    'smoothingFineActionMean', NaN, 'smoothingFineActionP90', NaN, ...
    'smoothingFineActiveFraction', NaN, ...
    'smoothingMidActionMean', NaN, 'smoothingMidActionP90', NaN, ...
    'smoothingMidActiveFraction', NaN, ...
    'repairFineActionMean', NaN, 'repairFineActionP90', NaN, ...
    'repairFineActiveFraction', NaN, 'repairMidActionMean', NaN, ...
    'repairMidActionP90', NaN, 'repairMidActiveFraction', NaN, ...
    'repairEvidenceMean', NaN, ...
    'repairBlemishEnergyBeforeMean', NaN, ...
    'repairBlemishEnergyAfterMean', NaN, ...
    'repairBlemishEnergyReductionRatio', NaN, ...
    'baseLuminanceActionMean', NaN, 'baseLuminanceActionP90', NaN, ...
    'baseLuminanceActiveFraction', NaN, ...
    'whiteningLuminanceActionMean', NaN, ...
    'whiteningLuminanceActionP90', NaN, ...
    'whiteningLuminanceActiveFraction', NaN, ...
    'toneChromaActionMean', NaN, 'toneChromaActionP90', NaN, ...
    'toneChromaActiveFraction', NaN, 'firstActiveStage', '', ...
    'stageSmoothingMean', NaN, 'stageRepairMean', NaN, ...
    'stageBaseLuminanceMean', NaN, 'stageSkinToneMean', NaN, ...
    'stageWhiteningMean', NaN, 'fineInputEnergyMean', NaN, ...
    'fineAfterSmoothingEnergyMean', NaN, ...
    'fineAfterRepairEnergyMean', NaN, 'midInputEnergyMean', NaN, ...
    'midAfterSmoothingEnergyMean', NaN, 'midAfterRepairEnergyMean', NaN, ...
    'fineSmoothingRetentionRatio', NaN, 'fineRepairRetentionRatio', NaN, ...
    'midSmoothingRetentionRatio', NaN, 'midRepairRetentionRatio', NaN, ...
    'structureGradientBeforeMean', NaN, ...
    'structureGradientAfterMean', NaN, ...
    'structureGradientRetentionRatio', NaN, ...
    'nostrilTextureCoreFraction', NaN, ...
    'nostrilTextureBoundaryFraction', NaN, ...
    'nostrilToneCandidateFraction', NaN, ...
    'nostrilWhiteningCoreFraction', NaN, ...
    'nostrilDetectorDisagreementFraction', NaN, ...
    'noseSemanticExcluded', NaN, ...
    'occluderProtectionMean', NaN, 'browProtectionMean', NaN, ...
    'lipProtectionMean', NaN, 'noseProtectionMean', NaN, ...
    'eyeDetailProtectionMean', NaN, ...
    'periocularProtectionMean', NaN, ...
    'doubleEyelidProtectionMean', NaN, 'lashProtectionMean', NaN, ...
    'structureReconstructionMaxError', NaN, ...
    'noseStructureMean', NaN, 'outsideStructureMean', NaN, ...
    'faceStructureMean', NaN, 'faceBoundaryMean', NaN, ...
    'noseStructureDominantFraction', NaN, ...
    'outsideStructureDominantFraction', NaN, ...
    'faceStructureDominantFraction', NaN, ...
    'faceBoundaryDominantFraction', NaN, 'structureTieFraction', NaN, ...
    'dominantStructureSource', '', 'finalRgbChangeMean', NaN, ...
    'finalRgbChangeP90', NaN, 'finalRgbChangeMax', NaN, ...
    'finalRgbActiveFraction', NaN, 'finalLuminanceChangeMean', NaN, ...
    'hardProtectionMaxRgbChange', NaN, 'hairMaxRgbChange', NaN, ...
    'backgroundMaxRgbChange', NaN, 'safetyHairPixels', 0, ...
    'safetyBackgroundPixels', 0, 'safetyHardPixels', 0);
end

function row = emptyAblationRow
row = struct( ...
    'mode', '', 'symptom', '', 'ablation', '', 'kind', '', ...
    'scopePixels', 0, 'roiPixels', 0, ...
    'finalRgbDifferenceMean', NaN, 'finalRgbDifferenceP90', NaN, ...
    'finalRgbDifferenceMax', NaN, ...
    'finalLuminanceDifferenceMean', NaN, ...
    'hairMaxRgbDifference', NaN, 'backgroundMaxRgbDifference', NaN, ...
    'hardProtectionMaxRgbDifference', NaN, ...
    'scopeOutputRgbChangeMean', NaN, 'scopeOutputRgbChangeMax', NaN);
end

function row = emptyRepairComponentRow
row = struct( ...
    'mode', '', 'symptom', '', 'component', '', ...
    'roiX', 0, 'roiY', 0, 'roiWidth', 0, 'roiHeight', 0, ...
    'roiPixels', 0, 'fineActionMean', NaN, 'fineActionP90', NaN, ...
    'fineActiveFraction', NaN, 'midActionMean', NaN, ...
    'midActionP90', NaN, 'midActiveFraction', NaN, ...
    'fineRetentionRatio', NaN, 'midRetentionRatio', NaN, ...
    'blemishEnergyBeforeMean', NaN, 'blemishEnergyAfterMean', NaN, ...
    'blemishEnergyReductionRatio', NaN, ...
    'outputRgbChangeFromInputMean', NaN, ...
    'outputRgbChangeFromInputP90', NaN, ...
    'outputRgbChangeFromInputMax', NaN, ...
    'outputRgbDifferenceFromNoRepairMean', NaN, ...
    'outputRgbDifferenceFromNoRepairP90', NaN, ...
    'outputRgbDifferenceFromNoRepairMax', NaN, ...
    'outputLuminanceDifferenceFromNoRepairMean', NaN, ...
    'lowFrequencyGradientBeforeMean', NaN, ...
    'lowFrequencyGradientAfterMean', NaN, ...
    'lowFrequencyGradientRetentionRatio', NaN, ...
    'hardProtectionMaxRgbChange', NaN, 'hairMaxRgbChange', NaN, ...
    'backgroundMaxRgbChange', NaN);
end

function row = emptyRepairCombinationRow
row = struct( ...
    'mode', '', ...
    'completeRepairReconstructionMaxRgbDifference', NaN, ...
    'internalLuminanceAdditivityMean', NaN, ...
    'internalLuminanceAdditivityP90', NaN, ...
    'internalLuminanceAdditivityMax', NaN, ...
    'rgbSuperpositionResidualMean', NaN, ...
    'rgbSuperpositionResidualP90', NaN, ...
    'rgbSuperpositionResidualMax', NaN);
end

function item = emptyAblationItem
item = struct('name', '', 'output', [], 'scopeMask', false(0), ...
    'compose', struct(), 'kind', '');
end

function item = emptyRepairComponentItem
item = struct('name', '', 'frequency', struct(), 'output', [], ...
    'compose', struct(), 'fineCorrection', [], ...
    'mediumCorrection', [], 'baselineDifferenceMax', 0);
end

function row = makeImageMetricRow(modeName, metrics)
row = emptyImageMetricRow();
row.mode = modeName;
row.entropy = metrics.entropy;
row.standardDeviation = metrics.standardDeviation;
row.averageGradient = metrics.averageGradient;
row.elapsedSeconds = metrics.elapsedSeconds;
end

function row = emptyImageMetricRow
row = struct('mode', '', 'entropy', NaN, ...
    'standardDeviation', NaN, 'averageGradient', NaN, ...
    'elapsedSeconds', NaN);
end
