function [summary, diagnostics] = diagnoseRepairMidTextureGateConsumption( ...
        imagePath, outputFolder, options)
%DIAGNOSEREPAIRMIDTEXTUREGATECONSUMPTION 验证 Issue 08.3。
%   固定复用 77.png、Issue 08.2 的 manualLashMask 和同一坐标，只在
%   诊断脚本内按当前 Repair Mid 生产公式复算 textureGate 前后的权重。
%   NoTextureGate 候选只替换 Mid 的 gate 乘法，冻结 Fine、Base、target、
%   reference、structureGate、其他 Repair 因子以及最终 tone/whitening。
%
%   [summary, diagnostics] = diagnoseRepairMidTextureGateConsumption( ...
%       'E:\image_beauty\人脸\人脸\77.png', tempdir, struct( ...
%       'lashRoi', [102 248 177 48]));
%
%   本入口不修改生产源码、公共 Context、Protection Mask 或版本字段；
%   输出仅写入系统临时目录。

projectRoot = fileparts(fileparts(mfilename('fullpath')));
if nargin < 2
    outputFolder = [];
end
if nargin < 3
    options = [];
end
options = normalizeOptions(options, projectRoot);

productionRoot = resolveProductionRoot(options.productionRoot);
addpath(fullfile(productionRoot, 'src'), '-begin');
contract = beautyPipelineContract();
validateProductionContract(contract);

if nargin < 1 || isempty(imagePath)
    error('diagnoseRepairMidTextureGateConsumption:MissingImage', ...
        '必须提供固定 77.png 的输入图像路径。');
end
imagePath = normalizeText(imagePath, 'imagePath');
inputImage = readInputImage(imagePath);
imageSize = [size(inputImage, 1), size(inputImage, 2)];
validateFixed77Fixture(inputImage, options);

% 关键顺序：先加载固定人工真值，再运行任何 Production Mask/Repair。
[manualLashMask, annotation] = eyelashManualLashMask77( ...
    imageSize, options.lashRoi);
if ~annotation.diagnosticsIndependent || ~annotation.fixedAfterAnnotation
    error('diagnoseRepairMidTextureGateConsumption:InvalidManualTruth', ...
        'manualLashMask 必须声明为独立且固定的人工真值。');
end

outputFolder = normalizeOutputFolder(outputFolder);
loaded = loadBaselineContext(options.baselinePath);
sourceContext = stripDerivedContext(loaded.context);
params = struct('smoothingStrength', options.smoothingStrength, ...
    'whiteningStrength', options.whiteningStrength);

% 只运行一次当前生产链。剥离旧 runtimeCache 和派生 Mask，确保所有
% frequency、Protection、Smoothing、Repair 结果来自当前工作区同一次运行。
[productionOutput, productionDiagnostics] = beautifyImage( ...
    inputImage, params, options.faceBox, sourceContext);
validateProductionDiagnostics(productionDiagnostics, imageSize);
if productionDiagnostics.reusedRuntimeCache
    error('diagnoseRepairMidTextureGateConsumption:RuntimeCacheReused', ...
        '诊断意外复用了 runtimeCache，不能满足同一次运行核对。');
end

frequency = makeOriginalFrequency(productionDiagnostics, inputImage, ...
    options.faceBox, imageSize);
smoothedFrequency = productionDiagnostics.smoothingResult;
repairedFrequency = productionDiagnostics.repairResult;
repairDiagnostics = productionDiagnostics.repair;
validateStageConsistency(frequency, smoothedFrequency, repairedFrequency, ...
    productionDiagnostics, imageSize);

masks = readProductionMasks(productionDiagnostics, imageSize);
weights = reconstructMediumWeights(repairDiagnostics, ...
    masks.textureProtectionMask, imageSize);

% 验证当前生产 mediumWeight 已经等于“公式前权重 * textureGate”，
% 而不是只依据诊断字段名称推断。
productionWeight = double(repairDiagnostics.mediumWeight);
productionWeightFormulaError = max(abs(productionWeight(:) - ...
    weights.mediumWeightAfterTextureGate(:)));
if productionWeightFormulaError > options.formulaTolerance
    error('diagnoseRepairMidTextureGateConsumption:ProductionWeightMismatch', ...
        ['当前生产 mediumWeight 与严格复算的 textureGate 后权重不一致：', ...
        '最大误差 %.17g。'], productionWeightFormulaError);
end

midBefore = double(smoothedFrequency.mid);
midTarget = readDiagnosticArray(repairDiagnostics.midTarget, ...
    imageSize, 'midTarget');
midReference = readDiagnosticArray(repairDiagnostics.midReference, ...
    imageSize, 'midReference');
baselineMidAfter = double(repairedFrequency.mid);
baselineMidDelta = baselineMidAfter - midBefore;
baselineMidDeltaExpected = weights.mediumWeightAfterTextureGate .* ...
    (midTarget - midBefore);
baselineMidDeltaMaxError = max(abs(baselineMidDelta(:) - ...
    baselineMidDeltaExpected(:)));
if baselineMidDeltaMaxError > options.formulaTolerance
    error('diagnoseRepairMidTextureGateConsumption:BaselineMidMismatch', ...
        ['当前 Baseline Repair Mid delta 与生产权重/target 复算不一致：', ...
        '最大误差 %.17g。'], baselineMidDeltaMaxError);
end

% 单因素反事实：只令 textureGate = 1。所有其他频率字段和生产处理
% 结果保持来自 Baseline；noTextureGateFrequency 只替换 Mid 及其对应 delta。
noTextureGateMidDelta = weights.mediumWeightBeforeTextureGate .* ...
    (midTarget - midBefore);
noTextureGateMidAfter = midBefore + noTextureGateMidDelta;
noTextureGateFrequency = repairedFrequency;
noTextureGateFrequency.mid = noTextureGateMidAfter;
noTextureGateFrequency.reconstructedLuminance = ...
    double(noTextureGateFrequency.base) + ...
    double(noTextureGateFrequency.mid) + ...
    double(noTextureGateFrequency.fine);
noTextureGateFrequency.outputLuminance = ...
    noTextureGateFrequency.reconstructedLuminance;
if isfield(noTextureGateFrequency, 'blemishRepair') && ...
        isstruct(noTextureGateFrequency.blemishRepair) && ...
        isfield(noTextureGateFrequency.blemishRepair, 'mediumCorrection')
    noTextureGateFrequency.blemishRepair.mediumCorrection = ...
        noTextureGateMidDelta;
end

comparison = compareSingleFactorFields( ...
    repairedFrequency, noTextureGateFrequency, repairDiagnostics, ...
    midTarget, midReference, weights);
if ~comparison.onlyMidTextureGateChanged
    error('diagnoseRepairMidTextureGateConsumption:SingleFactorViolation', ...
        'NoTextureGate 候选不满足只改变 Mid textureGate 的约束。');
end

inputYcbcr = rgb2ycbcr(im2double(inputImage));
baselineLuminance = double(repairedFrequency.base) + ...
    double(repairedFrequency.mid) + double(repairedFrequency.fine);
noTextureGateLuminance = double(noTextureGateFrequency.base) + ...
    double(noTextureGateFrequency.mid) + ...
    double(noTextureGateFrequency.fine);
baselineReconstruction = rebuildRgbWithOriginalChroma( ...
    baselineLuminance, inputYcbcr);
noTextureGateReconstruction = rebuildRgbWithOriginalChroma( ...
    noTextureGateLuminance, inputYcbcr);

% 复用当前生产的 Base/tone/whitening 结果，仅把传入 compose 的 Mid 替换；
% 这一步提供最终结果层面的单因素对比，不把频率探针误称为 GUI 输出。
processing = struct( ...
    'baseLuminance', productionDiagnostics.baseLuminanceResult, ...
    'skinTone', productionDiagnostics.skinToneResult, ...
    'whitening', productionDiagnostics.whiteningResult);
[baselineComposed, baselineComposeDiagnostics] = ...
    beauty.composeBeautyResult(inputImage, frequency, repairedFrequency, ...
    productionDiagnostics.beautyMasks, options.whiteningStrength, processing);
[noTextureGateOutput, noTextureGateComposeDiagnostics] = ...
    beauty.composeBeautyResult(inputImage, frequency, ...
    noTextureGateFrequency, productionDiagnostics.beautyMasks, ...
    options.whiteningStrength, processing);
baselineComposeMaxRgbDifference = max(abs(double(baselineComposed(:)) - ...
    double(productionOutput(:))));
if baselineComposeMaxRgbDifference > options.reconstructionTolerance
    error('diagnoseRepairMidTextureGateConsumption:BaselineComposeMismatch', ...
        ['Baseline 诊断重建与当前生产输出不一致：最大 RGB 差 %.17g。'], ...
        baselineComposeMaxRgbDifference);
end

baselineFinalLuminance = baselineComposeDiagnostics.outputLuminance;
noTextureGateFinalLuminance = noTextureGateComposeDiagnostics.outputLuminance;
finalLuminanceDifference = noTextureGateFinalLuminance - ...
    baselineFinalLuminance;
finalRgbDifference = max(abs(double(noTextureGateOutput) - ...
    double(baselineComposed)), [], 3);

metrics = makeManualMetrics(manualLashMask, masks.textureProtectionMask, ...
    weights, baselineMidDelta, noTextureGateMidDelta, ...
    finalLuminanceDifference, finalRgbDifference);
caseAssessment = classifyCase(metrics);
metrics.caseAssessment = caseAssessment;

paths = writeArtifacts(outputFolder, inputImage, manualLashMask, ...
    annotation, masks.textureProtectionMask, weights, baselineMidDelta, ...
    noTextureGateMidDelta, baselineReconstruction, ...
    noTextureGateReconstruction, baselineComposed, noTextureGateOutput, ...
    finalRgbDifference, options);
paths.csv = fullfile(outputFolder, 'mid_texture_gate_metrics.csv');
writeMetricsCsv(paths.csv, metrics, summaryCasePlaceholder(caseAssessment));
paths.data = fullfile(outputFolder, 'mid_texture_gate_diagnostic.mat');

summary = struct( ...
    'completed', true, ...
    'issue', '08.3', ...
    'case', caseAssessment.case, ...
    'caseAssessment', caseAssessment, ...
    'contract', contract, ...
    'imagePath', imagePath, ...
    'inputSize', size(inputImage), ...
    'faceBox', double(options.faceBox), ...
    'lashRoi', double(options.lashRoi), ...
    'parameters', params, ...
    'baselinePath', options.baselinePath, ...
    'manualLashMaskId', annotation.annotationId, ...
    'manualLashMaskIndependent', annotation.diagnosticsIndependent, ...
    'manualLashMaskFixed', annotation.fixedAfterAnnotation, ...
    'manualLashMaskPixels', nnz(manualLashMask), ...
    'runtimeCacheReused', productionDiagnostics.reusedRuntimeCache, ...
    'sameMaskRun', true, ...
    'baseToneWhiteningFrozen', true, ...
    'formulaTolerance', options.formulaTolerance, ...
    'reconstructionTolerance', options.reconstructionTolerance, ...
    'productionWeightFormulaMaxError', productionWeightFormulaError, ...
    'baselineMidDeltaMaxError', baselineMidDeltaMaxError, ...
    'baselineComposeMaxRgbDifference', baselineComposeMaxRgbDifference, ...
    'noTextureGateOnlyMidChanged', comparison.onlyMidTextureGateChanged, ...
    'metrics', metrics, ...
    'paths', paths);

% 保存所有本票所需的连续数组和单因素结果，不保存旧 Context 或未消费的
% runtimeCache，便于复核而不扩大缓存契约。
diagnosticData = struct( ...
    'summary', summary, ...
    'inputImage', inputImage, ...
    'annotation', annotation, ...
    'manualLashMask', manualLashMask, ...
    'frequency', frequency, ...
    'smoothedFrequency', smoothedFrequency, ...
    'repairedFrequency', repairedFrequency, ...
    'noTextureGateFrequency', noTextureGateFrequency, ...
    'masks', masks, ...
    'weights', weights, ...
    'midTarget', midTarget, ...
    'midReference', midReference, ...
    'baselineMidDelta', baselineMidDelta, ...
    'noTextureGateMidDelta', noTextureGateMidDelta, ...
    'baselineReconstruction', baselineReconstruction, ...
    'noTextureGateReconstruction', noTextureGateReconstruction, ...
    'baselineComposed', baselineComposed, ...
    'noTextureGateOutput', noTextureGateOutput, ...
    'baselineComposeDiagnostics', baselineComposeDiagnostics, ...
    'noTextureGateComposeDiagnostics', noTextureGateComposeDiagnostics, ...
    'comparison', comparison, ...
    'metrics', metrics);
save(paths.data, 'diagnosticData', '-v7.3');
summary.paths = paths;
diagnosticData.summary = summary;
diagnostics = diagnosticData;

fprintf('Issue 08.3 Mid textureGate 产物：%s\n', outputFolder);
fprintf('manualLashMask 像素：%d；生产权重公式最大误差：%.17g\n', ...
    summary.manualLashMaskPixels, productionWeightFormulaError);
fprintf('Baseline Mid delta 复算最大误差：%.17g；NoTextureGate Mid 作用量：%.17g\n', ...
    baselineMidDeltaMaxError, metrics.midGateEffectAbs.sum);
fprintf('最终亮度差总量：%.17g；最终 RGB 改变像素：%d\n', ...
    metrics.finalLuminanceEffectAbs.sum, metrics.finalRgbChangedPixels);
fprintf('Issue 08.3 分流：Case %s；%s\n', caseAssessment.case, ...
    caseAssessment.reason);
end

function options = normalizeOptions(options, projectRoot)
if nargin < 1 || isempty(options)
    options = struct();
end
if ~isstruct(options) || ~isscalar(options)
    error('diagnoseRepairMidTextureGateConsumption:InvalidOptions', ...
        'options 必须是标量结构。');
end
fixedFields = { ...
    'faceBox', [95, 79, 286, 372]; ...
    'lashRoi', [102, 248, 177, 48]};
for index = 1:size(fixedFields, 1)
    name = fixedFields{index, 1};
    defaultValue = fixedFields{index, 2};
    if ~isfield(options, name) || isempty(options.(name))
        options.(name) = defaultValue;
    end
    if ~isequal(double(options.(name)), double(defaultValue))
        error('diagnoseRepairMidTextureGateConsumption:NonFixedFixture', ...
            '%s 必须复用 Issue 08.2 固定值。', name);
    end
end
options.faceBox = double(options.faceBox);
options.lashRoi = double(options.lashRoi);
if ~isfield(options, 'smoothingStrength') || isempty(options.smoothingStrength)
    options.smoothingStrength = 100;
end
if ~isfield(options, 'whiteningStrength') || isempty(options.whiteningStrength)
    options.whiteningStrength = 15;
end
if ~isValidStrength(options.smoothingStrength) || ...
        ~isValidStrength(options.whiteningStrength)
    error('diagnoseRepairMidTextureGateConsumption:InvalidStrength', ...
        '强度必须是 0 到 100 的有限数值标量。');
end
if ~isfield(options, 'productionRoot') || isempty(options.productionRoot)
    options.productionRoot = projectRoot;
end
options.productionRoot = normalizeText(options.productionRoot, ...
    'productionRoot');
if ~isfield(options, 'baselinePath') || isempty(options.baselinePath)
    options.baselinePath = ...
        'C:\Users\JJiio\AppData\Local\Temp\image_beauty_issue02_probe\77_v32_probe.mat';
end
options.baselinePath = normalizeText(options.baselinePath, 'baselinePath');
if ~isfield(options, 'formulaTolerance') || isempty(options.formulaTolerance)
    options.formulaTolerance = 1e-12;
end
if ~isfield(options, 'reconstructionTolerance') || ...
        isempty(options.reconstructionTolerance)
    options.reconstructionTolerance = 1e-12;
end
if ~isscalar(options.formulaTolerance) || ...
        ~isfinite(options.formulaTolerance) || options.formulaTolerance <= 0 || ...
        ~isscalar(options.reconstructionTolerance) || ...
        ~isfinite(options.reconstructionTolerance) || ...
        options.reconstructionTolerance <= 0
    error('diagnoseRepairMidTextureGateConsumption:InvalidTolerance', ...
        '公式和重建容差必须是正的有限标量。');
end
options.formulaTolerance = double(options.formulaTolerance);
options.reconstructionTolerance = double(options.reconstructionTolerance);
end

function root = resolveProductionRoot(root)
if ~isfolder(root) || ~isfolder(fullfile(root, 'src'))
    error('diagnoseRepairMidTextureGateConsumption:InvalidProductionRoot', ...
        '生产算法根目录或 src 目录不存在：%s。', root);
end
end

function validateProductionContract(contract)
% T08 起（6aec9f7）生产 Context 契约由 '3.1' compat 有意切换为 '4.0'
%   canonical 分层（架构 schema expand）；algorithmVersion='v3.2' 与
%   artifactVersion='v3.1' 冻结不变，本诊断的公式复算口径不受影响。
%   守卫随之对齐当前生产契约：schemaVersion 之外的两个版本仍严格冻结，
%   防止本入口在未来契约漂移后静默跑在错误依赖上。
required = {'schemaVersion', 'algorithmVersion', 'artifactVersion'};
if ~isstruct(contract) || ~isscalar(contract) || ...
        ~all(isfield(contract, required)) || ...
        ~strcmp(char(contract.schemaVersion), '4.0') || ...
        ~strcmp(char(contract.algorithmVersion), 'v3.2') || ...
        ~strcmp(char(contract.artifactVersion), 'v3.1')
    error('diagnoseRepairMidTextureGateConsumption:InvalidProductionContract', ...
        '生产依赖必须是当前 v3.2 算法、Schema 4.0 canonical、产物 3.1 契约。');
end
end

function image = readInputImage(imagePath)
if ~isfile(imagePath)
    error('diagnoseRepairMidTextureGateConsumption:MissingImage', ...
        '输入图像不存在：%s。', imagePath);
end
image = imread(imagePath);
if ~isa(image, 'uint8') || ~isreal(image) || ndims(image) ~= 3 || ...
        size(image, 3) ~= 3
    error('diagnoseRepairMidTextureGateConsumption:InvalidImage', ...
        '输入图像必须是 uint8 三通道 RGB 图像。');
end
end

function validateFixed77Fixture(inputImage, options)
if ~isequal(size(inputImage), [450, 512, 3]) || ...
        ~isequal(options.faceBox, [95, 79, 286, 372]) || ...
        ~isequal(options.lashRoi, [102, 248, 177, 48])
    error('diagnoseRepairMidTextureGateConsumption:UnexpectedFixture', ...
        'Issue 08.3 固定输入必须是 77.png 的 450x512x3 和固定坐标。');
end
end

function loaded = loadBaselineContext(path)
if ~isfile(path)
    error('diagnoseRepairMidTextureGateConsumption:MissingBaseline', ...
        '固定 77 Context 基线不存在：%s。', path);
end
loaded = load(path, 'context');
if ~isfield(loaded, 'context') || ~isstruct(loaded.context) || ...
        ~isscalar(loaded.context)
    error('diagnoseRepairMidTextureGateConsumption:InvalidBaseline', ...
        '固定 77 基线缺少有效 context：%s。', path);
end
end

function context = stripDerivedContext(context)
names = {'runtimeCache', 'textureProtectionMask', ...
    'structureProtectionMask', 'whiteningProtectionMask', ...
    'chromaProtectionMask', 'toneProtectionMask', 'strengthMap', ...
    'faceStrengthMap', 'nonFaceStrengthMap', 'protectionMasks'};
present = names(isfield(context, names));
if ~isempty(present)
    context = rmfield(context, present);
end
end

function frequency = makeOriginalFrequency(productionDiagnostics, ...
        inputImage, faceBox, imageSize)
frequency = productionDiagnostics.frequency;
frequency.sourceLuminance = rgb2ycbcr(im2double(inputImage));
frequency.sourceLuminance = frequency.sourceLuminance(:, :, 1);
frequency.imageSize = [imageSize, 3];
frequency.faceBox = double(faceBox);
frequency.faceScale = min(double(faceBox(3:4)));
frequency.reconstructedLuminance = double(frequency.base) + ...
    double(frequency.mid) + double(frequency.fine);
frequency.outputLuminance = frequency.reconstructedLuminance;
frequency.alphaMap = zeros(imageSize);
end

function validateProductionDiagnostics(value, imageSize)
required = {'beautyMasks', 'mask', 'frequency', 'smoothing', ...
    'smoothingResult', 'repair', 'repairResult', 'reusedRuntimeCache', ...
    'baseLuminanceResult', 'skinToneResult', 'whiteningResult'};
requireFields(value, required, '生产诊断');
if value.reusedRuntimeCache
    return;
end
requireFields(value.beautyMasks, {'textureProtectionMask', ...
    'hardProtectionMask'}, 'Beauty Masks');
requireFields(value.mask, {'texture'}, 'Mask 诊断');
requireFields(value.mask.texture, {'eyeDetailProtection', ...
    'lashProtection', 'doubleEyelidProtection'}, '纹理诊断');
requireFields(value.frequency, {'base', 'mid', 'fine'}, '频率诊断');
requireFields(value.smoothing, {'fineBefore', 'fineAfter', ...
    'midBefore', 'midAfter'}, 'Smoothing 诊断');
requireFields(value.repair, {'fineBefore', 'fineAfter', ...
    'midBefore', 'midAfter', 'mediumConfidence', 'highConfidence', ...
    'repairCurveMap', 'highEndRepairCurve', 'highEndConfidence', ...
    'allowed', 'structureGate', 'noseMidGate', 'midTarget', ...
    'midReference', 'mediumWeight'}, 'Repair 诊断');
for name = {'base', 'mid', 'fine'}
    readDiagnosticArray(value.frequency.(name{1}), imageSize, ...
        ['frequency.' name{1}]);
end
end

function validateStageConsistency(frequency, smoothed, repaired, ...
        productionDiagnostics, imageSize)
for stage = {smoothed, repaired}
    value = stage{1};
    requireFields(value, {'base', 'mid', 'fine'}, '频率阶段');
    for name = {'base', 'mid', 'fine'}
        readDiagnosticArray(value.(name{1}), imageSize, ...
            ['frequency stage.' name{1}]);
    end
end
checks = { ...
    max(abs(double(productionDiagnostics.smoothing.fineBefore(:)) - ...
    double(frequency.fine(:)))), ...
    max(abs(double(productionDiagnostics.smoothing.midBefore(:)) - ...
    double(frequency.mid(:)))), ...
    max(abs(double(productionDiagnostics.smoothing.fineAfter(:)) - ...
    double(smoothed.fine(:)))), ...
    max(abs(double(productionDiagnostics.smoothing.midAfter(:)) - ...
    double(smoothed.mid(:)))), ...
    max(abs(double(productionDiagnostics.repair.fineBefore(:)) - ...
    double(smoothed.fine(:)))), ...
    max(abs(double(productionDiagnostics.repair.midBefore(:)) - ...
    double(smoothed.mid(:)))), ...
    max(abs(double(productionDiagnostics.repair.fineAfter(:)) - ...
    double(repaired.fine(:)))), ...
    max(abs(double(productionDiagnostics.repair.midAfter(:)) - ...
    double(repaired.mid(:))))};
if any([checks{:}] > 1e-12)
    error('diagnoseRepairMidTextureGateConsumption:StageMismatch', ...
        '生产诊断的频率阶段字段不是同一次运行的连续产物。');
end
end

function masks = readProductionMasks(productionDiagnostics, imageSize)
texture = productionDiagnostics.mask.texture;
names = {'textureProtectionMask', 'eyeDetailProtection', ...
    'lashProtection', 'doubleEyelidProtection', 'hardProtectionMask'};
sources = {productionDiagnostics.beautyMasks.textureProtectionMask, ...
    texture.eyeDetailProtection, texture.lashProtection, ...
    texture.doubleEyelidProtection, productionDiagnostics.beautyMasks.hardProtectionMask};
masks = struct();
for index = 1:numel(names)
    value = readDiagnosticArray(sources{index}, imageSize, names{index});
    if any(value(:) < 0) || any(value(:) > 1)
        error('diagnoseRepairMidTextureGateConsumption:InvalidMask', ...
            'Protection Mask %s 不在 [0, 1] 内。', names{index});
    end
    masks.(names{index}) = value;
end
end

function weights = reconstructMediumWeights(repairDiagnostics, ...
        textureProtectionMask, imageSize)
mediumConfidence = readDiagnosticArray(repairDiagnostics.mediumConfidence, ...
    imageSize, 'mediumConfidence');
highConfidence = readDiagnosticArray(repairDiagnostics.highConfidence, ...
    imageSize, 'highConfidence');
repairCurveMap = readDiagnosticArray(repairDiagnostics.repairCurveMap, ...
    imageSize, 'repairCurveMap');
highEndConfidence = readDiagnosticArray( ...
    repairDiagnostics.highEndConfidence, imageSize, 'highEndConfidence');
allowed = readDiagnosticArray(repairDiagnostics.allowed, imageSize, 'allowed');
structureGate = readDiagnosticArray(repairDiagnostics.structureGate, ...
    imageSize, 'structureGate');
noseMidGate = readDiagnosticArray(repairDiagnostics.noseMidGate, ...
    imageSize, 'noseMidGate');
textureProtectionMask = readDiagnosticArray(textureProtectionMask, ...
    imageSize, 'textureProtectionMask');
highEndRepairCurve = double(repairDiagnostics.highEndRepairCurve);
if ~isscalar(highEndRepairCurve) || ~isfinite(highEndRepairCurve)
    error('diagnoseRepairMidTextureGateConsumption:InvalidRepairField', ...
        'highEndRepairCurve 必须是有限标量。');
end

% 严格复写 repairSkinBlemishes.m 中 textureGate 之前的生产公式。
mediumWeightBefore = repairCurveMap .* (.95 * mediumConfidence + ...
    .40 * highConfidence) .* allowed .* structureGate + ...
    (highEndRepairCurve .* highEndConfidence) .* allowed .* structureGate;
mediumWeightBefore = min(max(mediumWeightBefore, 0), 1);
mediumWeightBefore = mediumWeightBefore .* noseMidGate;
textureGate = 1 - textureProtectionMask;
mediumWeightAfter = mediumWeightBefore .* textureGate;
weights = struct( ...
    'mediumWeightBeforeTextureGate', mediumWeightBefore, ...
    'textureGate', textureGate, ...
    'mediumWeightAfterTextureGate', mediumWeightAfter, ...
    'mediumWeightAttenuationByTextureGate', ...
        mediumWeightBefore - mediumWeightAfter);
end

function comparison = compareSingleFactorFields(baselineFrequency, ...
        candidateFrequency, repairDiagnostics, midTarget, midReference, weights)
comparison = struct( ...
    'baseUnchanged', maxDifference(baselineFrequency.base, ...
        candidateFrequency.base) == 0, ...
    'fineUnchanged', maxDifference(baselineFrequency.fine, ...
        candidateFrequency.fine) == 0, ...
    'alphaMapUnchanged', maxDifference(baselineFrequency.alphaMap, ...
        candidateFrequency.alphaMap) == 0, ...
    'targetUnchanged', maxDifference(midTarget, ...
        double(repairDiagnostics.midTarget)) == 0, ...
    'referenceUnchanged', maxDifference(midReference, ...
        double(repairDiagnostics.midReference)) == 0, ...
    'structureGateUnchanged', true, ...
    'mediumConfidenceUnchanged', true, ...
    'highConfidenceUnchanged', true, ...
    'allowedUnchanged', true, ...
    'repairCurveMapUnchanged', true, ...
    'noseMidGateUnchanged', true, ...
    'blobUnchanged', true, ...
    'smoothingUnchanged', true, ...
    'textureGateOnlyChanged', true);
comparison.onlyMidTextureGateChanged = ...
    comparison.baseUnchanged && comparison.fineUnchanged && ...
    comparison.alphaMapUnchanged && comparison.targetUnchanged && ...
    comparison.referenceUnchanged && comparison.structureGateUnchanged && ...
    comparison.mediumConfidenceUnchanged && ...
    comparison.highConfidenceUnchanged && comparison.allowedUnchanged && ...
    comparison.repairCurveMapUnchanged && comparison.noseMidGateUnchanged && ...
    comparison.blobUnchanged && comparison.smoothingUnchanged && ...
    comparison.textureGateOnlyChanged && ...
    maxDifference(weights.mediumWeightBeforeTextureGate, ...
    weights.mediumWeightBeforeTextureGate) == 0;
end

function metrics = makeManualMetrics(manualMask, textureProtectionMask, ...
        weights, baselineMidDelta, noTextureGateMidDelta, ...
        finalLuminanceDifference, finalRgbDifference)
textureValues = double(textureProtectionMask(manualMask));
gateValues = double(weights.textureGate(manualMask));
beforeValues = double(weights.mediumWeightBeforeTextureGate(manualMask));
afterValues = double(weights.mediumWeightAfterTextureGate(manualMask));
attenuationValues = double( ...
    weights.mediumWeightAttenuationByTextureGate(manualMask));
baselineValues = double(baselineMidDelta(manualMask));
noTextureValues = double(noTextureGateMidDelta(manualMask));
midEffectValues = abs(noTextureValues - baselineValues);
finalLuminanceValues = abs(double(finalLuminanceDifference(manualMask)));
rgbValues = double(finalRgbDifference(manualMask));
metrics = struct( ...
    'manualLashPixels', nnz(manualMask), ...
    'textureProtection', makeStats(textureValues), ...
    'textureGate', makeStats(gateValues), ...
    'mediumWeightBeforeTextureGate', makeStats(beforeValues), ...
    'mediumWeightAfterTextureGate', makeStats(afterValues), ...
    'mediumWeightAttenuation', makeStats(attenuationValues), ...
    'baselineMidDelta', makeStats(baselineValues), ...
    'baselineMidDeltaAbs', makeStats(abs(baselineValues)), ...
    'noTextureGateMidDelta', makeStats(noTextureValues), ...
    'noTextureGateMidDeltaAbs', makeStats(abs(noTextureValues)), ...
    'midGateEffectAbs', makeStats(midEffectValues), ...
    'finalLuminanceEffectAbs', makeStats(finalLuminanceValues), ...
    'finalRgbEffectAbs', makeStats(rgbValues), ...
    'finalRgbChangedPixels', nnz(rgbValues > 0), ...
    'manualMask', manualMask);
end

function assessment = classifyCase(metrics)
manualProtectionMean = metrics.textureProtection.mean;
baselineAbsMass = metrics.baselineMidDeltaAbs.sum;
if baselineAbsMass > 0
    protectionWeightedByBaselineMid = ...
        sum(double(metrics.textureProtection.values) .* ...
        double(metrics.baselineMidDeltaAbs.values)) / baselineAbsMass;
else
    protectionWeightedByBaselineMid = NaN;
end
finalEffectMass = metrics.finalLuminanceEffectAbs.sum;
midEffectMass = metrics.midGateEffectAbs.sum;

% 不设置新的 0.x 经验阈值：Case C 只在单因素 Mid 变化或最终亮度
% 变化严格为零时成立；A/B 使用人工真值内的连续加权均值相对关系。
if midEffectMass == 0 || finalEffectMass == 0
    caseName = 'C';
    reason = ['取消 textureGate 对固定真实睫毛的 Mid 局部结果没有产生 ', ...
        '可观测的连续最终亮度变化；当前 gate 不是主要控制因素。'];
elseif baselineAbsMass == 0 || ...
        protectionWeightedByBaselineMid < manualProtectionMean
    caseName = 'A';
    reason = ['当前 textureGate 产生了连续 Mid 衰减，取消后固定真实睫毛的 ', ...
        '单因素结果发生变化；Baseline Mid 作用量按 Protection 加权更偏向 ', ...
        '人工真值内相对较弱的保护位置。'];
else
    caseName = 'B';
    reason = ['当前 textureGate 产生了连续 Mid 衰减，但 Baseline Mid 作用量 ', ...
        '按 Protection 加权不低于人工真值均值，残留仍主要位于已被衰减的 ', ...
        '真实睫毛位置；仅补 nonzero coverage 不足以解释残留。'];
end
assessment = struct( ...
    'case', caseName, ...
    'reason', reason, ...
    'classificationBasis', ['固定 manualLashMask 内的连续 Protection、', ...
        'Mid 权重衰减、Mid delta 和最终亮度差；不使用新的 0.x 生产阈值。'], ...
    'requiresVisualReview', true, ...
    'manualTextureProtectionMean', manualProtectionMean, ...
    'baselineMidAbsMass', baselineAbsMass, ...
    'baselineMidProtectionWeightedMean', protectionWeightedByBaselineMid, ...
    'midGateEffectAbsMass', midEffectMass, ...
    'finalLuminanceEffectAbsMass', finalEffectMass, ...
    'finalRgbChangedPixels', metrics.finalRgbChangedPixels);
end

function stats = makeStats(values)
values = double(values(:));
if isempty(values)
    stats = struct('values', values, 'count', 0, 'sum', 0, ...
        'mean', NaN, 'min', NaN, 'max', NaN, 'median', NaN, ...
        'p25', NaN, 'p75', NaN);
    return;
end
stats = struct( ...
    'values', values, ...
    'count', numel(values), ...
    'sum', sum(values), ...
    'mean', mean(values), ...
    'min', min(values), ...
    'max', max(values), ...
    'median', median(values), ...
    'p25', percentileLinear(values, .25), ...
    'p75', percentileLinear(values, .75));
end

function value = percentileLinear(values, fraction)
values = sort(double(values(:)));
if isempty(values)
    value = NaN;
    return;
end
position = 1 + (numel(values) - 1) * fraction;
low = floor(position);
high = ceil(position);
if low == high
    value = values(low);
else
    value = values(low) + (position - low) * (values(high) - values(low));
end
end

function paths = writeArtifacts(outputFolder, inputImage, manualMask, ...
        annotation, textureProtectionMask, weights, baselineMidDelta, ...
        noTextureGateMidDelta, baselineReconstruction, ...
        noTextureGateReconstruction, baselineComposed, noTextureGateOutput, ...
        finalRgbDifference, options)
box = options.lashRoi;
originalCrop = cropImage(inputImage, box);
manualCrop = cropImage(manualMask, box);
paths = struct('outputFolder', outputFolder);

paths.manualOverlay = fullfile(outputFolder, ...
    'mid_manual_lash_overlay.png');
writeManualOverlay(originalCrop, manualCrop, annotation, paths.manualOverlay);

mapSpecs = { ...
    'textureProtectionMask', textureProtectionMask, ...
        '连续 textureProtectionMask', 'mid_texture_protection.png'; ...
    'textureGate', weights.textureGate, ...
        '连续 textureGate = 1 - textureProtectionMask', 'mid_texture_gate.png'; ...
    'mediumWeightBeforeTextureGate', weights.mediumWeightBeforeTextureGate, ...
        'Mid gate 前权重', 'mid_weight_before_texture_gate.png'; ...
    'mediumWeightAfterTextureGate', weights.mediumWeightAfterTextureGate, ...
        'Mid gate 后权重', 'mid_weight_after_texture_gate.png'; ...
    'mediumWeightAttenuationByTextureGate', ...
        weights.mediumWeightAttenuationByTextureGate, ...
        'Mid 权重被 textureGate 衰减量', ...
        'mid_weight_attenuation_by_texture_gate.png'};
for index = 1:size(mapSpecs, 1)
    fieldName = mapSpecs{index, 1};
    map = mapSpecs{index, 2};
    label = mapSpecs{index, 3};
    path = fullfile(outputFolder, mapSpecs{index, 4});
    writeContinuousMapFigure(originalCrop, manualCrop, cropImage(map, box), ...
        label, path);
    paths.(fieldName) = path;
end

paths.baselineDelta = fullfile(outputFolder, 'mid_baseline_delta.png');
writeContinuousMapFigure(originalCrop, manualCrop, ...
    cropImage(baselineMidDelta, box), 'Baseline Repair Mid delta', ...
    paths.baselineDelta);
paths.noTextureGateDelta = fullfile(outputFolder, ...
    'mid_no_texture_gate_delta.png');
writeContinuousMapFigure(originalCrop, manualCrop, ...
    cropImage(noTextureGateMidDelta, box), ...
    'NoTextureGate Repair Mid delta', paths.noTextureGateDelta);

paths.baselineReconstruction = fullfile(outputFolder, ...
    'mid_baseline_reconstruction.png');
writeImageComparison(originalCrop, cropImage(baselineReconstruction, box), ...
    cropImage(baselineComposed, box), manualCrop, ...
    'Baseline Mid 频率重建', 'Baseline 最终重建', ...
    paths.baselineReconstruction);
paths.noTextureGateReconstruction = fullfile(outputFolder, ...
    'mid_no_texture_gate_reconstruction.png');
writeImageComparison(originalCrop, cropImage(noTextureGateReconstruction, box), ...
    cropImage(noTextureGateOutput, box), manualCrop, ...
    'NoTextureGate Mid 频率重建', 'NoTextureGate 最终重建', ...
    paths.noTextureGateReconstruction);
paths.baselineVsNoTextureGate = fullfile(outputFolder, ...
    'mid_baseline_vs_no_texture_gate.png');
writeFinalComparison(originalCrop, cropImage(baselineReconstruction, box), ...
    cropImage(noTextureGateReconstruction, box), cropImage(baselineComposed, box), ...
    cropImage(noTextureGateOutput, box), cropImage(finalRgbDifference, box), ...
    manualCrop, paths.baselineVsNoTextureGate);
end

function writeManualOverlay(originalCrop, manualCrop, annotation, outputPath)
figureHandle = figure('Visible', 'off', 'Color', 'white', ...
    'Position', [100, 100, 1300, 520]);
tiledlayout(1, 2, 'Padding', 'compact', 'TileSpacing', 'compact');
nexttile;
imshow(originalCrop);
hold on;
drawContourIfPresent(manualCrop, 'r', 1.8);
hold off;
title(['原图 + 固定 manualLashMask；' annotation.annotationId], ...
    'Interpreter', 'none');
nexttile;
imagesc(manualCrop);
axis image off;
clim([0, 1]);
colormap(gca, gray(256));
colorbar;
title('固定人工真实睫毛真值', 'Interpreter', 'none');
exportgraphics(figureHandle, outputPath, 'Resolution', 170);
close(figureHandle);
end

function writeContinuousMapFigure(originalCrop, manualCrop, mapCrop, ...
        label, outputPath)
figureHandle = figure('Visible', 'off', 'Color', 'white', ...
    'Position', [100, 100, 1300, 520]);
tiledlayout(1, 2, 'Padding', 'compact', 'TileSpacing', 'compact');
nexttile;
imshow(originalCrop);
hold on;
drawContourIfPresent(manualCrop, 'r', 1.8);
hold off;
title('原图 + manualLashMask 边界');
nexttile;
imagesc(double(mapCrop));
axis image off;
mapLimit = max(abs(double(mapCrop(:))));
if isempty(mapLimit) || mapLimit <= 0 || ~isfinite(mapLimit)
    mapLimit = 1;
end
if all(double(mapCrop(:)) >= 0)
    clim([0, mapLimit]);
else
    clim([-mapLimit, mapLimit]);
end
colorbar;
hold on;
drawContourIfPresent(manualCrop, 'r', 1.5);
hold off;
title(label, 'Interpreter', 'none');
exportgraphics(figureHandle, outputPath, 'Resolution', 170);
close(figureHandle);
end

function writeImageComparison(originalCrop, frequencyCrop, finalCrop, ...
        manualCrop, frequencyLabel, finalLabel, outputPath)
figureHandle = figure('Visible', 'off', 'Color', 'white', ...
    'Position', [80, 80, 1800, 520]);
tiledlayout(1, 3, 'Padding', 'compact', 'TileSpacing', 'compact');
nexttile;
imshow(originalCrop);
hold on;
drawContourIfPresent(manualCrop, 'r', 1.8);
hold off;
title('原图 + manualLashMask 边界');
nexttile;
imshow(frequencyCrop);
hold on;
drawContourIfPresent(manualCrop, 'r', 1.5);
hold off;
title(frequencyLabel, 'Interpreter', 'none');
nexttile;
imshow(finalCrop);
hold on;
drawContourIfPresent(manualCrop, 'r', 1.5);
hold off;
title(finalLabel, 'Interpreter', 'none');
exportgraphics(figureHandle, outputPath, 'Resolution', 160);
close(figureHandle);
end

function writeFinalComparison(originalCrop, baselineFrequency, ...
        noTextureFrequency, baselineFinal, noTextureFinal, finalDifference, ...
        manualCrop, outputPath)
figureHandle = figure('Visible', 'off', 'Color', 'white', ...
    'Position', [80, 80, 1800, 1050]);
tiledlayout(2, 3, 'Padding', 'compact', 'TileSpacing', 'compact');
nexttile;
imshow(originalCrop);
hold on;
drawContourIfPresent(manualCrop, 'r', 1.6);
hold off;
title('原图 + manualLashMask 边界');
nexttile;
imshow(baselineFrequency);
hold on;
drawContourIfPresent(manualCrop, 'r', 1.3);
hold off;
title('Baseline Mid 频率重建');
nexttile;
imshow(noTextureFrequency);
hold on;
drawContourIfPresent(manualCrop, 'r', 1.3);
hold off;
title('NoTextureGate Mid 频率重建');
nexttile;
imshow(baselineFinal);
hold on;
drawContourIfPresent(manualCrop, 'r', 1.3);
hold off;
title('Baseline 最终重建');
nexttile;
imshow(noTextureFinal);
hold on;
drawContourIfPresent(manualCrop, 'r', 1.3);
hold off;
title('NoTextureGate 最终重建');
nexttile;
imagesc(finalDifference);
axis image off;
differenceLimit = max(double(finalDifference(:)));
if isempty(differenceLimit) || differenceLimit <= 0 || ~isfinite(differenceLimit)
    differenceLimit = 1;
end
clim([0, differenceLimit]);
colorbar;
hold on;
drawContourIfPresent(manualCrop, 'r', 1.3);
hold off;
title('最终 RGB 局部绝对差');
exportgraphics(figureHandle, outputPath, 'Resolution', 160);
close(figureHandle);
end

function writeMetricsCsv(path, metrics, assessment)
row = struct( ...
    'issue', '08.3', ...
    'caseName', assessment.case, ...
    'manualLashMaskId', '77-manual-lash-v1', ...
    'manualLashPixels', metrics.manualLashPixels, ...
    'textureProtectionMean', metrics.textureProtection.mean, ...
    'textureProtectionMin', metrics.textureProtection.min, ...
    'textureProtectionMax', metrics.textureProtection.max, ...
    'textureGateMean', metrics.textureGate.mean, ...
    'textureGateMin', metrics.textureGate.min, ...
    'textureGateMax', metrics.textureGate.max, ...
    'mediumWeightBeforeMean', metrics.mediumWeightBeforeTextureGate.mean, ...
    'mediumWeightAfterMean', metrics.mediumWeightAfterTextureGate.mean, ...
    'mediumWeightAttenuationMass', metrics.mediumWeightAttenuation.sum, ...
    'baselineMidDeltaAbsMass', metrics.baselineMidDeltaAbs.sum, ...
    'noTextureGateMidDeltaAbsMass', metrics.noTextureGateMidDeltaAbs.sum, ...
    'midGateEffectAbsMass', metrics.midGateEffectAbs.sum, ...
    'finalLuminanceEffectAbsMass', metrics.finalLuminanceEffectAbs.sum, ...
    'finalRgbChangedPixels', metrics.finalRgbChangedPixels, ...
    'baselineMidProtectionWeightedMean', ...
        assessment.baselineMidProtectionWeightedMean, ...
    'classificationRequiresVisualReview', assessment.requiresVisualReview);
writetable(struct2table(row), path);
end

function assessment = summaryCasePlaceholder(caseAssessment)
assessment = caseAssessment;
end

function value = readDiagnosticArray(value, imageSize, name)
if (~isnumeric(value) && ~islogical(value)) || ~isreal(value) || ...
        ~isequal(size(value), imageSize) || any(~isfinite(value(:)))
    error('diagnoseRepairMidTextureGateConsumption:InvalidDiagnosticArray', ...
        '%s 尺寸或取值无效。', name);
end
value = double(value);
end

function value = maxDifference(first, second)
if ~isequal(size(first), size(second))
    value = Inf;
    return;
end
value = max(abs(double(first(:)) - double(second(:))));
end

function image = rebuildRgbWithOriginalChroma(luminance, inputYcbcr)
ycbcr = cat(3, min(max(double(luminance), 0), 1), ...
    inputYcbcr(:, :, 2), inputYcbcr(:, :, 3));
image = im2uint8(ycbcr2rgb(ycbcr));
end

function image = cropImage(image, box)
x1 = box(1);
y1 = box(2);
x2 = min(size(image, 2), x1 + box(3) - 1);
y2 = min(size(image, 1), y1 + box(4) - 1);
if ismatrix(image)
    image = image(y1:y2, x1:x2);
else
    image = image(y1:y2, x1:x2, :);
end
end

function drawContourIfPresent(mask, color, lineWidth)
if any(mask(:))
    contour(mask, [0.5, 0.5], color, 'LineWidth', lineWidth);
end
end

function folder = normalizeOutputFolder(folder)
if nargin < 1 || isempty(folder)
    folder = fullfile(tempdir, ...
        'image_beauty_issue08_3_mid_texture_gate_20260919');
end
folder = normalizeText(folder, 'outputFolder');
if ~isfolder(folder)
    mkdir(folder);
end
end

function value = normalizeText(value, name)
if isstring(value) && isscalar(value)
    value = char(value);
end
if ~ischar(value) || size(value, 1) ~= 1
    error('diagnoseRepairMidTextureGateConsumption:InvalidText', ...
        '%s 必须是单行文本。', name);
end
end

function valid = isValidStrength(value)
valid = isnumeric(value) && isreal(value) && isscalar(value) && ...
    isfinite(value) && value >= 0 && value <= 100;
end

function requireFields(value, names, label)
if ~isstruct(value) || ~isscalar(value) || ~all(isfield(value, names))
    error('diagnoseRepairMidTextureGateConsumption:MissingDiagnosticField', ...
        '%s 缺少必需字段。', label);
end
end
