function [summary, diagnostics] = diagnoseLashAngleGroupedReconstruction( ...
        imagePath, outputFolder, options)
%DIAGNOSELASHANGLEGROUPEDRECONSTRUCTION 验证 Issue 08.7 唯一角度分组候选。
%   本入口不修改生产 src。它固定复用 77.png、77-manual-lash-v1、
%   faceBox/browEye/lashRoi、磨皮 100、美白 15 和当前生产链；Baseline、
%   08.4 Candidate、08.6 Candidate 与 08.7 Candidate 使用同一冻结链。
%
%   08.7 只保留当前多角度 morphology response 的离散 angle identity，
%   对每个 angle 独立执行与 08.6 相同的 8-connected reconstruction，
%   最后 union。候选不使用 manualLashMask 生成，不新增 orientation field、
%   模型、特征、阈值、angle 或绝对像素尺度。
%
%   [summary, diagnostics] = diagnoseLashAngleGroupedReconstruction( ...
%       'E:\image_beauty\人脸\人脸\77.png', tempdir, struct( ...
%       'productionRoot', 'E:\image_beauty', ...
%       'baselinePath', ...
%       'C:\Users\JJiio\AppData\Local\Temp\image_beauty_issue02_probe\77_v32_probe.mat'));

projectRoot = fileparts(fileparts(mfilename('fullpath')));
if nargin < 2
    outputFolder = [];
end
if nargin < 3
    options = [];
end
options = normalizeOptions(options, projectRoot);

productionRoot = resolveProductionRoot(options.productionRoot);
addpath(fullfile(productionRoot, 'src'), '-begin');
addpath(fileparts(mfilename('fullpath')), '-begin');

if nargin < 1 || isempty(imagePath)
    error('diagnoseLashAngleGroupedReconstruction:MissingImage', ...
        '必须提供固定 77.png 的输入图像路径。');
end
imagePath = normalizeText(imagePath, 'imagePath');
inputImage = readInputImage(imagePath);
imageSize = [size(inputImage, 1), size(inputImage, 2)];
validateFixed77Fixture(inputImage, options);
outputFolder = normalizeOutputFolder(outputFolder);

% 先复用已完成的 08.4 诊断，得到同一次生产基线、08.4 Candidate、
% frequency、blemishMap、其它 Mask 和冻结的 Base/tone/whitening。08.4
% Candidate 的生成路径本身不消费 manualLashMask；其人工真值只用于统计。
stageFolder = tempname;
mkdir(stageFolder);
[continuitySummary, continuityDiagnostics] = ...
    diagnoseLashSoftContinuityCandidate(imagePath, stageFolder, options);
validateContinuityStage(continuitySummary, continuityDiagnostics, imageSize);

manualLashMask = continuityDiagnostics.manualLashMask;
annotation = continuityDiagnostics.annotation;
if ~annotation.diagnosticsIndependent || ~annotation.fixedAfterAnnotation || ...
        ~strcmp(annotation.annotationId, '77-manual-lash-v1')
    error('diagnoseLashAngleGroupedReconstruction:InvalidManualTruth', ...
        'manualLashMask 必须是固定、独立的 77-manual-lash-v1。');
end

loaded = loadBaselineContext(options.baselinePath);
sourceContext = stripDerivedContext(loaded.context);
faceScale = readFaceScale(continuityDiagnostics.frequency, options.faceBox);

baselineBeautyMasks = continuityDiagnostics.baselineBeautyMasks;
baselineTextureDiagnostics = continuityDiagnostics.baselineTextureDiagnostics;
baselineLashProtection = readDiagnosticArray( ...
    continuityDiagnostics.baselineLashProtection, imageSize, ...
    'baselineLashProtection');
validateTextureDiagnostics(baselineTextureDiagnostics, imageSize);

% 重新读取当前 detector 已有的内部 evidence。该函数只消费原图、固定
% Context 的 regions/regionConfidence 和 faceScale，不接收人工真值。
evidence = reconstructExistingLashEvidence(inputImage, sourceContext, ...
    faceScale);
validateEvidenceReconstruction(evidence, baselineTextureDiagnostics, ...
    baselineLashProtection, imageSize, options.formulaTolerance);
evidence.reconstructionMaxError = max(abs( ...
    evidence.existingLashProtection(:) - baselineLashProtection(:)));

% 08.6 固定对照：先 OR 所有 angle response，再做统一 8-connected
% reconstruction。08.7 只改变这里的 response 组织顺序，不改 detector 参数。
candidate086GeometrySeed = evidence.connectedEvidence;
candidate086LashProtection = featherSoftMask(candidate086GeometrySeed, ...
    evidence.softRadius, evidence.softPeak);
candidate086LashProtection(~evidence.eyeNeighborhood) = 0;
candidate086LashProtection = min(max(double(candidate086LashProtection), 0), 1);
validateMask(candidate086LashProtection, imageSize, ...
    'candidate086LashProtection');

% 08.7 唯一新候选：每个 angle 在自己的 allowed evidence 内独立重构，
% reconstruction 完成后才 union。soft 值仍复用当前 featherSoftMask。
angleGrouped = reconstructAngleGroupedGeometry(evidence);
candidate087GeometrySeed = angleGrouped.unionGeometry;
candidate087LashProtection = featherSoftMask(candidate087GeometrySeed, ...
    evidence.softRadius, evidence.softPeak);
candidate087LashProtection(~evidence.eyeNeighborhood) = 0;
candidate087LashProtection = min(max(double(candidate087LashProtection), 0), 1);
validateMask(candidate087LashProtection, imageSize, ...
    'candidate087LashProtection');

periocularProtection = readDiagnosticArray( ...
    baselineTextureDiagnostics.periocularProtection, imageSize, ...
    'periocularProtection');
doubleEyelidProtection = readDiagnosticArray( ...
    baselineTextureDiagnostics.doubleEyelidProtection, imageSize, ...
    'doubleEyelidProtection');
reconstructedBaselineEyeDetail = max(cat(3, periocularProtection, ...
    baselineLashProtection, doubleEyelidProtection), [], 3);
baselineEyeDetail = readDiagnosticArray( ...
    baselineTextureDiagnostics.eyeDetailProtection, imageSize, ...
    'baselineEyeDetailProtection');
if max(abs(reconstructedBaselineEyeDetail(:) - baselineEyeDetail(:))) > ...
        options.formulaTolerance
    error('diagnoseLashAngleGroupedReconstruction:EyeDetailAggregationMismatch', ...
        'Baseline eyeDetailProtection 聚合不一致。');
end

candidate086EyeDetailProtection = max(cat(3, periocularProtection, ...
    candidate086LashProtection, doubleEyelidProtection), [], 3);
candidate087EyeDetailProtection = max(cat(3, periocularProtection, ...
    candidate087LashProtection, doubleEyelidProtection), [], 3);
% 08.6/08.7 都是 geometry replacement，不把旧 lashProtection 再次
% max 回去；其它 texture components 仍逐项冻结。
fixedTextureComponents = max(cat(3, ...
    readDiagnosticArray(baselineTextureDiagnostics.occluderProtection, ...
    imageSize, 'occluderProtection'), ...
    readDiagnosticArray(baselineTextureDiagnostics.browProtection, ...
    imageSize, 'browProtection'), ...
    readDiagnosticArray(baselineTextureDiagnostics.lipProtection, ...
    imageSize, 'lipProtection'), ...
    readDiagnosticArray(baselineTextureDiagnostics.noseProtection, ...
    imageSize, 'noseProtection')), [], 3);
candidate086TextureProtectionMask = min(max(max(fixedTextureComponents, ...
    candidate086EyeDetailProtection), 0), 1);
candidate087TextureProtectionMask = min(max(max(fixedTextureComponents, ...
    candidate087EyeDetailProtection), 0), 1);
validateMask(candidate086TextureProtectionMask, imageSize, ...
    'candidate086TextureProtectionMask');
validateMask(candidate087TextureProtectionMask, imageSize, ...
    'candidate087TextureProtectionMask');

candidate086BeautyMasks = baselineBeautyMasks;
candidate086BeautyMasks.textureProtectionMask = candidate086TextureProtectionMask;
candidate086BeautyMasks.protectionMask = max(cat(3, ...
    candidate086TextureProtectionMask, ...
    double(baselineBeautyMasks.structureProtectionMask), ...
    double(baselineBeautyMasks.hardProtectionMask)), [], 3);
candidate087BeautyMasks = baselineBeautyMasks;
candidate087BeautyMasks.textureProtectionMask = candidate087TextureProtectionMask;
candidate087BeautyMasks.protectionMask = max(cat(3, ...
    candidate087TextureProtectionMask, ...
    double(baselineBeautyMasks.structureProtectionMask), ...
    double(baselineBeautyMasks.hardProtectionMask)), [], 3);
validateCandidateMaskIsolation(baselineBeautyMasks, candidate086BeautyMasks, ...
    candidate086TextureProtectionMask, candidate086EyeDetailProtection, ...
    imageSize, options.formulaTolerance);
validateCandidateMaskIsolation(baselineBeautyMasks, candidate087BeautyMasks, ...
    candidate087TextureProtectionMask, candidate087EyeDetailProtection, ...
    imageSize, options.formulaTolerance);

frequency = continuityDiagnostics.frequency;
blemishMap = continuityDiagnostics.blemishMap;
params = struct('smoothingStrength', options.smoothingStrength, ...
    'whiteningStrength', options.whiteningStrength);

% 只重跑当前既有 Smoothing / Repair / compose。frequency、blemishMap、
% Base、tone、whitening 和其它 Mask 均冻结。
[candidate086SmoothedFrequency, candidate086SmoothingDiagnostics] = ...
    beauty.smoothSkinTexture(frequency, candidate086BeautyMasks, ...
    params.smoothingStrength, blemishMap);
[candidate086RepairedFrequency, candidate086RepairDiagnostics] = ...
    beauty.repairSkinBlemishes(candidate086SmoothedFrequency, ...
    candidate086BeautyMasks, blemishMap, params.smoothingStrength);
[candidate087SmoothedFrequency, candidate087SmoothingDiagnostics] = ...
    beauty.smoothSkinTexture(frequency, candidate087BeautyMasks, ...
    params.smoothingStrength, blemishMap);
[candidate087RepairedFrequency, candidate087RepairDiagnostics] = ...
    beauty.repairSkinBlemishes(candidate087SmoothedFrequency, ...
    candidate087BeautyMasks, blemishMap, params.smoothingStrength);
processing = buildFrozenProcessing( ...
    continuityDiagnostics.baselineComposeDiagnostics);

[baselineComposed, baselineComposeDiagnostics] = ...
    beauty.composeBeautyResult(inputImage, frequency, ...
    continuityDiagnostics.repairedFrequency, baselineBeautyMasks, ...
    params.whiteningStrength, processing);
[candidate084Composed, candidate084ComposeDiagnostics] = ...
    beauty.composeBeautyResult(inputImage, frequency, ...
    continuityDiagnostics.candidateRepairedFrequency, ...
    continuityDiagnostics.candidateBeautyMasks, params.whiteningStrength, ...
    processing);
[candidate086Output, candidate086ComposeDiagnostics] = ...
    beauty.composeBeautyResult(inputImage, frequency, ...
    candidate086RepairedFrequency, candidate086BeautyMasks, ...
    params.whiteningStrength, processing);
[candidate087Output, candidate087ComposeDiagnostics] = ...
    beauty.composeBeautyResult(inputImage, frequency, ...
    candidate087RepairedFrequency, candidate087BeautyMasks, ...
    params.whiteningStrength, processing);

baselineOutput = continuityDiagnostics.baselineComposed;
candidate084Output = continuityDiagnostics.candidateOutput;
baselineComposeMaxRgbDifference = max(abs(double(baselineComposed(:)) - ...
    double(baselineOutput(:))));
candidate084ComposeMaxRgbDifference = max(abs( ...
    double(candidate084Composed(:)) - double(candidate084Output(:))));
if baselineComposeMaxRgbDifference > options.reconstructionTolerance || ...
        candidate084ComposeMaxRgbDifference > options.reconstructionTolerance
    error('diagnoseLashAngleGroupedReconstruction:FrozenComposeMismatch', ...
        'Baseline/08.4 冻结 compose 重建不一致：%.17g / %.17g。', ...
        baselineComposeMaxRgbDifference, candidate084ComposeMaxRgbDifference);
end

baselineSmoothedFrequency = continuityDiagnostics.smoothedFrequency;
candidate084SmoothedFrequency = continuityDiagnostics.candidateSmoothedFrequency;
baselineRepairedFrequency = continuityDiagnostics.repairedFrequency;
candidate084RepairedFrequency = continuityDiagnostics.candidateRepairedFrequency;
baselineRepairFineDelta = double(baselineRepairedFrequency.fine) - ...
    double(baselineSmoothedFrequency.fine);
candidate084RepairFineDelta = double(candidate084RepairedFrequency.fine) - ...
    double(candidate084SmoothedFrequency.fine);
candidate086RepairFineDelta = double(candidate086RepairedFrequency.fine) - ...
    double(candidate086SmoothedFrequency.fine);
candidate087RepairFineDelta = double(candidate087RepairedFrequency.fine) - ...
    double(candidate087SmoothedFrequency.fine);
baselineRepairMidDelta = double(baselineRepairedFrequency.mid) - ...
    double(baselineSmoothedFrequency.mid);
candidate084RepairMidDelta = double(candidate084RepairedFrequency.mid) - ...
    double(candidate084SmoothedFrequency.mid);
candidate086RepairMidDelta = double(candidate086RepairedFrequency.mid) - ...
    double(candidate086SmoothedFrequency.mid);
candidate087RepairMidDelta = double(candidate087RepairedFrequency.mid) - ...
    double(candidate087SmoothedFrequency.mid);

originalLuminance = rgb2ycbcr(im2double(inputImage));
originalLuminance = originalLuminance(:, :, 1);
validateArray(originalLuminance, imageSize, 'originalLuminance');

baselineRgbDistance = max(abs(double(baselineOutput) - ...
    double(inputImage)), [], 3);
candidate084RgbDistance = max(abs(double(candidate084Output) - ...
    double(inputImage)), [], 3);
candidate086RgbDistance = max(abs(double(candidate086Output) - ...
    double(inputImage)), [], 3);
candidate087RgbDistance = max(abs(double(candidate087Output) - ...
    double(inputImage)), [], 3);
baselineLuminanceDistance = abs(double( ...
    baselineComposeDiagnostics.outputLuminance) - double(originalLuminance));
candidate084LuminanceDistance = abs(double( ...
    candidate084ComposeDiagnostics.outputLuminance) - double(originalLuminance));
candidate086LuminanceDistance = abs(double( ...
    candidate086ComposeDiagnostics.outputLuminance) - double(originalLuminance));
candidate087LuminanceDistance = abs(double( ...
    candidate087ComposeDiagnostics.outputLuminance) - double(originalLuminance));

baselineSupport = baselineLashProtection > 0;
candidate084LashProtection = readDiagnosticArray( ...
    continuityDiagnostics.candidateLashProtection, imageSize, ...
    'candidate084LashProtection');
candidate084Support = candidate084LashProtection > 0;
candidate086Support = candidate086LashProtection > 0;
candidate087Support = candidate087LashProtection > 0;
candidate086TextureDiagnostics = makeCandidateTextureDiagnostics( ...
    baselineTextureDiagnostics, candidate086EyeDetailProtection, ...
    candidate086LashProtection);
candidate087TextureDiagnostics = makeCandidateTextureDiagnostics( ...
    baselineTextureDiagnostics, candidate087EyeDetailProtection, ...
    candidate087LashProtection);
metrics = makeMetrics(manualLashMask, baselineSupport, ...
    candidate084Support, candidate086Support, candidate087Support, ...
    baselineLashProtection, candidate084LashProtection, ...
    candidate086LashProtection, candidate087LashProtection, ...
    baselineRepairFineDelta, candidate084RepairFineDelta, ...
    candidate086RepairFineDelta, candidate087RepairFineDelta, ...
    baselineRepairMidDelta, candidate084RepairMidDelta, ...
    candidate086RepairMidDelta, candidate087RepairMidDelta, ...
    baselineRgbDistance, candidate084RgbDistance, candidate086RgbDistance, ...
    candidate087RgbDistance, baselineLuminanceDistance, ...
    candidate084LuminanceDistance, candidate086LuminanceDistance, ...
    candidate087LuminanceDistance, options.nonzeroTolerance);
metrics.numericGeometryAssessment = assessNumericGeometry(metrics, ...
    options.formulaTolerance);
metrics.repairAssessment = assessRepair(metrics, options.formulaTolerance);
metrics.candidate086HardProtectionMaskChangedPixels = nnz( ...
    double(candidate086BeautyMasks.hardProtectionMask) ~= ...
    double(baselineBeautyMasks.hardProtectionMask));
metrics.hardProtectionMaskChangedPixels = nnz( ...
    double(candidate087BeautyMasks.hardProtectionMask) ~= ...
    double(baselineBeautyMasks.hardProtectionMask));
metrics.hardCoreChangedPixels = nnz( ...
    logical(baselineTextureDiagnostics.lashCore) ~= ...
    logical(candidate087TextureDiagnostics.lashCore));

paths = writeArtifacts(outputFolder, inputImage, manualLashMask, ...
    baselineSupport, candidate084Support, candidate086Support, candidate087Support, ...
    baselineRepairFineDelta, candidate084RepairFineDelta, ...
    candidate086RepairFineDelta, candidate087RepairFineDelta, ...
    baselineRepairMidDelta, candidate084RepairMidDelta, ...
    candidate086RepairMidDelta, candidate087RepairMidDelta, ...
    baselineOutput, candidate084Output, candidate086Output, candidate087Output, ...
    angleGrouped, options.lashRoi);
paths.csv = fullfile(outputFolder, 'lash_angle_grouped_metrics.csv');
writeMetricsCsv(paths.csv, metrics, metrics.numericGeometryAssessment, ...
    metrics.repairAssessment, angleGrouped, options);
paths.perAngleCsv = fullfile(outputFolder, ...
    'lash_angle_grouped_per_angle_metrics.csv');
paths.data = fullfile(outputFolder, 'lash_angle_grouped_diagnostic.mat');

hardProtectionMaskChangedPixels = nnz( ...
    double(candidate087BeautyMasks.hardProtectionMask) ~= ...
    double(baselineBeautyMasks.hardProtectionMask));
candidate086HardProtectionMaskChangedPixels = nnz( ...
    double(candidate086BeautyMasks.hardProtectionMask) ~= ...
    double(baselineBeautyMasks.hardProtectionMask));
hardCoreChangedPixels = nnz( ...
    logical(baselineTextureDiagnostics.lashCore) ~= ...
    logical(candidate087TextureDiagnostics.lashCore));

summary = struct( ...
    'completed', true, ...
    'issue', '08.7', ...
    'case', 'requiresVisualReview', ...
    'caseAssessment', metrics.numericGeometryAssessment, ...
    'repairAssessment', metrics.repairAssessment, ...
    'contract', continuitySummary.contract, ...
    'imagePath', imagePath, ...
    'inputSize', size(inputImage), ...
    'faceBox', double(options.faceBox), ...
    'browEye', double(options.browEyeRoi), ...
    'lashRoi', double(options.lashRoi), ...
    'parameters', params, ...
    'baselinePath', options.baselinePath, ...
    'manualLashMaskId', annotation.annotationId, ...
    'manualLashMaskIndependent', annotation.diagnosticsIndependent, ...
    'manualLashMaskFixed', annotation.fixedAfterAnnotation, ...
    'manualLashMaskPixels', nnz(manualLashMask), ...
    'runtimeCacheReused', continuitySummary.runtimeCacheReused, ...
    'sameMaskRun', true, ...
    'baseToneWhiteningFrozen', true, ...
    'onlyLashSupportGeometryChanged', true, ...
    'manualTruthUsedForGeneration', false, ...
    'candidateSeedSource', 'current detector candidate seed', ...
    'candidateEvidenceSource', ...
        'current dark/edge/line evidence intersected with eyeNeighborhood', ...
    'candidate086Connection', ...
        '8-connected reconstruction after pre-OR of angle responses', ...
    'candidate087Connection', ...
        'independent 8-connected reconstruction per existing morphology angle', ...
    'candidateSoftWeightSource', ...
        'current featherSoftMask with existing faceScale softRadius and peak', ...
    'angles', evidence.angles, ...
    'faceScale', faceScale, ...
    'softRadius', evidence.softRadius, ...
    'softPeak', evidence.softPeak, ...
    'evidenceReconstructionMaxError', evidence.reconstructionMaxError, ...
    'lineSupportFromAngleMaxError', evidence.lineSupportFromAngleMaxError, ...
    'baselineComposeMaxRgbDifference', baselineComposeMaxRgbDifference, ...
    'candidate084ComposeMaxRgbDifference', ...
        candidate084ComposeMaxRgbDifference, ...
    'candidate086HardProtectionMaskChangedPixels', ...
        candidate086HardProtectionMaskChangedPixels, ...
    'hardProtectionMaskChangedPixels', hardProtectionMaskChangedPixels, ...
    'hardCoreChangedPixels', hardCoreChangedPixels, ...
    'metrics', metrics, ...
    'paths', paths);

diagnosticData = struct( ...
    'summary', summary, ...
    'inputImage', inputImage, ...
    'annotation', annotation, ...
    'manualLashMask', manualLashMask, ...
    'frequency', frequency, ...
    'blemishMap', blemishMap, ...
    'baselineBeautyMasks', baselineBeautyMasks, ...
    'candidate084BeautyMasks', continuityDiagnostics.candidateBeautyMasks, ...
    'candidate086BeautyMasks', candidate086BeautyMasks, ...
    'candidate087BeautyMasks', candidate087BeautyMasks, ...
    'baselineTextureDiagnostics', baselineTextureDiagnostics, ...
    'candidate084TextureDiagnostics', ...
        continuityDiagnostics.candidateTextureDiagnostics, ...
    'candidate086TextureDiagnostics', candidate086TextureDiagnostics, ...
    'candidate087TextureDiagnostics', candidate087TextureDiagnostics, ...
    'evidence', evidence, ...
    'angleGrouped', angleGrouped, ...
    'baselineLashProtection', baselineLashProtection, ...
    'candidate084LashProtection', candidate084LashProtection, ...
    'candidate086LashProtection', candidate086LashProtection, ...
    'candidate087LashProtection', candidate087LashProtection, ...
    'baselineSupport', baselineSupport, ...
    'candidate084Support', candidate084Support, ...
    'candidate086Support', candidate086Support, ...
    'candidate087Support', candidate087Support, ...
    'candidate086GeometrySeed', candidate086GeometrySeed, ...
    'candidate086AllowedEvidence', evidence.allowedEvidence, ...
    'candidate087GeometrySeed', candidate087GeometrySeed, ...
    'candidate087AllowedEvidence', {angleGrouped.allowedEvidence}, ...
    'candidate087SoftProtection', candidate087LashProtection, ...
    'smoothedFrequency', baselineSmoothedFrequency, ...
    'candidate084SmoothedFrequency', candidate084SmoothedFrequency, ...
    'candidate086SmoothedFrequency', candidate086SmoothedFrequency, ...
    'candidate087SmoothedFrequency', candidate087SmoothedFrequency, ...
    'repairedFrequency', baselineRepairedFrequency, ...
    'candidate084RepairedFrequency', candidate084RepairedFrequency, ...
    'candidate086RepairedFrequency', candidate086RepairedFrequency, ...
    'candidate087RepairedFrequency', candidate087RepairedFrequency, ...
    'candidate086SmoothingDiagnostics', candidate086SmoothingDiagnostics, ...
    'candidate086RepairDiagnostics', candidate086RepairDiagnostics, ...
    'candidate087SmoothingDiagnostics', candidate087SmoothingDiagnostics, ...
    'candidate087RepairDiagnostics', candidate087RepairDiagnostics, ...
    'baselineRepairFineDelta', baselineRepairFineDelta, ...
    'candidate084RepairFineDelta', candidate084RepairFineDelta, ...
    'candidate086RepairFineDelta', candidate086RepairFineDelta, ...
    'candidate087RepairFineDelta', candidate087RepairFineDelta, ...
    'baselineRepairMidDelta', baselineRepairMidDelta, ...
    'candidate084RepairMidDelta', candidate084RepairMidDelta, ...
    'candidate086RepairMidDelta', candidate086RepairMidDelta, ...
    'candidate087RepairMidDelta', candidate087RepairMidDelta, ...
    'baselineOutput', baselineOutput, ...
    'candidate084Output', candidate084Output, ...
    'candidate086Output', candidate086Output, ...
    'candidate087Output', candidate087Output, ...
    'baselineComposeDiagnostics', baselineComposeDiagnostics, ...
    'candidate084ComposeDiagnostics', candidate084ComposeDiagnostics, ...
    'candidate086ComposeDiagnostics', candidate086ComposeDiagnostics, ...
    'candidate087ComposeDiagnostics', candidate087ComposeDiagnostics, ...
    'candidate086FinalRgbDistance', candidate086RgbDistance, ...
    'candidate086FinalLuminanceDistance', candidate086LuminanceDistance, ...
    'candidate087FinalRgbDistance', candidate087RgbDistance, ...
    'candidate087FinalLuminanceDistance', candidate087LuminanceDistance, ...
    'metrics', metrics);
save(paths.data, 'diagnosticData', '-v7.3');
summary.paths = paths;
diagnosticData.summary = summary;
diagnostics = diagnosticData;

fprintf('Issue 08.7 Angle-Grouped Reconstruction 产物：%s\n', outputFolder);
fprintf('Baseline / 08.4 / 08.6 / 08.7 support：%d / %d / %d / %d\n', ...
    metrics.baseline.supportPixels, metrics.candidate084.supportPixels, ...
    metrics.candidate086.supportPixels, metrics.candidate087.supportPixels);
fprintf('Recall：%.17g / %.17g / %.17g / %.17g；Precision：%.17g / %.17g / %.17g\n', ...
    metrics.baseline.recall, metrics.candidate084.recall, ...
    metrics.candidate086.recall, metrics.candidate087.recall, ...
    metrics.baseline.precision, metrics.candidate084.precision, ...
    metrics.candidate086.precision, metrics.candidate087.precision);
fprintf('Repair Fine 绝对作用量：%.17g -> %.17g -> %.17g -> %.17g\n', ...
    metrics.baselineRepairFineAbsAction.sum, ...
    metrics.candidate084RepairFineAbsAction.sum, ...
    metrics.candidate086RepairFineAbsAction.sum, ...
    metrics.candidate087RepairFineAbsAction.sum);
fprintf('Repair Mid 绝对作用量：%.17g -> %.17g -> %.17g -> %.17g\n', ...
    metrics.baselineRepairMidAbsAction.sum, ...
    metrics.candidate084RepairMidAbsAction.sum, ...
    metrics.candidate086RepairMidAbsAction.sum, ...
    metrics.candidate087RepairMidAbsAction.sum);
fprintf('角度 response 重算最大误差：%.17g；数值几何证据：%s；最终 Case 需要人工核对主图。\n', ...
    evidence.lineSupportFromAngleMaxError, metrics.numericGeometryAssessment.case);
end

function options = normalizeOptions(options, projectRoot)
if nargin < 1 || isempty(options)
    options = struct();
end
if ~isstruct(options) || ~isscalar(options)
    error('diagnoseLashAngleGroupedReconstruction:InvalidOptions', ...
        'options 必须是标量结构。');
end
fixedFields = { ...
    'faceBox', [95, 79, 286, 372]; ...
    'browEyeRoi', [165, 205, 150, 100]; ...
    'lashRoi', [102, 248, 177, 48]};
for index = 1:size(fixedFields, 1)
    name = fixedFields{index, 1};
    defaultValue = fixedFields{index, 2};
    if ~isfield(options, name) || isempty(options.(name))
        options.(name) = defaultValue;
    end
    if ~isequal(double(options.(name)), double(defaultValue))
        error('diagnoseLashAngleGroupedReconstruction:NonFixedFixture', ...
            '%s 必须复用 Issue 08.7 固定值。', name);
    end
end
options.faceBox = double(options.faceBox);
options.browEyeRoi = double(options.browEyeRoi);
options.lashRoi = double(options.lashRoi);
if ~isfield(options, 'smoothingStrength') || isempty(options.smoothingStrength)
    options.smoothingStrength = 100;
end
if ~isfield(options, 'whiteningStrength') || isempty(options.whiteningStrength)
    options.whiteningStrength = 15;
end
if ~isValidStrength(options.smoothingStrength) || ...
        ~isValidStrength(options.whiteningStrength)
    error('diagnoseLashAngleGroupedReconstruction:InvalidStrength', ...
        '强度必须是 0 到 100 的有限数值标量。');
end
if ~isfield(options, 'productionRoot') || isempty(options.productionRoot)
    options.productionRoot = projectRoot;
end
options.productionRoot = normalizeText(options.productionRoot, ...
    'productionRoot');
if ~isfield(options, 'baselinePath') || isempty(options.baselinePath)
    options.baselinePath = ...
        'C:\Users\JJiio\AppData\Local\Temp\image_beauty_issue02_probe\77_v32_probe.mat';
end
options.baselinePath = normalizeText(options.baselinePath, 'baselinePath');
if ~isfield(options, 'formulaTolerance') || isempty(options.formulaTolerance)
    options.formulaTolerance = 1e-12;
end
if ~isfield(options, 'reconstructionTolerance') || ...
        isempty(options.reconstructionTolerance)
    options.reconstructionTolerance = 1e-12;
end
if ~isfield(options, 'nonzeroTolerance') || isempty(options.nonzeroTolerance)
    options.nonzeroTolerance = 1e-12;
end
if ~isscalar(options.formulaTolerance) || ...
        ~isfinite(options.formulaTolerance) || options.formulaTolerance <= 0 || ...
        ~isscalar(options.reconstructionTolerance) || ...
        ~isfinite(options.reconstructionTolerance) || ...
        options.reconstructionTolerance <= 0 || ...
        ~isscalar(options.nonzeroTolerance) || ...
        ~isfinite(options.nonzeroTolerance) || options.nonzeroTolerance <= 0
    error('diagnoseLashAngleGroupedReconstruction:InvalidTolerance', ...
        '公式、重建和非零容差必须是正的有限标量。');
end
options.formulaTolerance = double(options.formulaTolerance);
options.reconstructionTolerance = double(options.reconstructionTolerance);
options.nonzeroTolerance = double(options.nonzeroTolerance);
end

function root = resolveProductionRoot(root)
if ~isfolder(root) || ~isfolder(fullfile(root, 'src'))
    error('diagnoseLashAngleGroupedReconstruction:InvalidProductionRoot', ...
        '生产算法根目录或 src 目录不存在：%s。', root);
end
end

function validateFixed77Fixture(inputImage, options)
if ~isequal(size(inputImage), [450, 512, 3]) || ...
        ~isequal(options.faceBox, [95, 79, 286, 372]) || ...
        ~isequal(options.browEyeRoi, [165, 205, 150, 100]) || ...
        ~isequal(options.lashRoi, [102, 248, 177, 48])
    error('diagnoseLashAngleGroupedReconstruction:UnexpectedFixture', ...
        'Issue 08.6 必须使用 77.png 的 450x512x3 和固定坐标。');
end
end

function validateContinuityStage(continuitySummary, diagnostics, imageSize)
if ~isstruct(continuitySummary) || ~continuitySummary.completed || ...
        ~strcmp(continuitySummary.issue, '08.4') || ...
        continuitySummary.runtimeCacheReused || ...
        ~isstruct(diagnostics) || ~isequal(size(diagnostics.inputImage), ...
        [imageSize, 3])
    error('diagnoseLashAngleGroupedReconstruction:InvalidContinuityStage', ...
        'Issue 08.4 阶段未按无缓存固定链完成。');
end
end

function image = readInputImage(imagePath)
if ~isfile(imagePath)
    error('diagnoseLashAngleGroupedReconstruction:MissingImage', ...
        '输入图像不存在：%s。', imagePath);
end
image = imread(imagePath);
if ~isa(image, 'uint8') || ~isreal(image) || ndims(image) ~= 3 || ...
        size(image, 3) ~= 3
    error('diagnoseLashAngleGroupedReconstruction:InvalidImage', ...
        '输入图像必须是 uint8 三通道 RGB 图像。');
end
end

function loaded = loadBaselineContext(path)
if ~isfile(path)
    error('diagnoseLashAngleGroupedReconstruction:MissingBaseline', ...
        '固定 77 Context 基线不存在：%s。', path);
end
loaded = load(path, 'context');
if ~isfield(loaded, 'context') || ~isstruct(loaded.context) || ...
        ~isscalar(loaded.context)
    error('diagnoseLashAngleGroupedReconstruction:InvalidBaseline', ...
        '固定 77 基线缺少有效 context：%s。', path);
end
end

function context = stripDerivedContext(context)
names = {'runtimeCache', 'textureProtectionMask', ...
    'structureProtectionMask', 'whiteningProtectionMask', ...
    'chromaProtectionMask', 'toneProtectionMask', 'strengthMap', ...
    'faceStrengthMap', 'nonFaceStrengthMap', 'protectionMasks'};
present = names(isfield(context, names));
if ~isempty(present)
    context = rmfield(context, present);
end
end

function faceScale = readFaceScale(frequency, faceBox)
if isfield(frequency, 'faceScale') && isnumeric(frequency.faceScale) && ...
        isscalar(frequency.faceScale) && isfinite(frequency.faceScale) && ...
        frequency.faceScale > 0
    faceScale = double(frequency.faceScale);
else
    faceScale = min(double(faceBox(3:4)));
end
end

function evidence = reconstructExistingLashEvidence(inputImage, context, ...
        faceScale)
imageSize = [size(inputImage, 1), size(inputImage, 2)];
if ~isfield(context, 'regions') || ~isfield(context, 'regionConfidence')
    error('diagnoseLashAngleGroupedReconstruction:MissingSemanticEvidence', ...
        '固定 Context 缺少当前 detector 所需的 regions/regionConfidence。');
end
regions = context.regions;
confidence = context.regionConfidence;
required = {'leftEye', 'rightEye', 'leftBrow', 'rightBrow'};
if ~all(isfield(regions, required)) || ~all(isfield(confidence, required))
    error('diagnoseLashAngleGroupedReconstruction:MissingSemanticEvidence', ...
        '固定 Context 缺少眼睛或眉毛既有语义 evidence。');
end
leftEyeEvidence = min(double(regions.leftEye), ...
    double(confidence.leftEye));
rightEyeEvidence = min(double(regions.rightEye), ...
    double(confidence.rightEye));
browEvidence = max(min(double(regions.leftBrow), ...
    double(confidence.leftBrow)), min(double(regions.rightBrow), ...
    double(confidence.rightBrow)));
validateArray(leftEyeEvidence, imageSize, 'leftEyeEvidence');
validateArray(rightEyeEvidence, imageSize, 'rightEyeEvidence');
validateArray(browEvidence, imageSize, 'browEvidence');

grayImage = im2double(rgb2gray(inputImage));
identityThreshold = .45;
softSupportThreshold = .20;
identityMasks = {leftEyeEvidence >= identityThreshold, ...
    rightEyeEvidence >= identityThreshold};
softSupportMasks = {leftEyeEvidence >= softSupportThreshold & ...
    leftEyeEvidence < identityThreshold, ...
    rightEyeEvidence >= softSupportThreshold & ...
    rightEyeEvidence < identityThreshold};
browCore = browEvidence >= identityThreshold;
periocularRadius = min(24, max(9, round(.040 * double(faceScale))));
softRadius = min(5, max(2, round(.008 * double(faceScale))));

angles = 0:15:165;
angleCount = numel(angles);
allNeighborhood = false(imageSize);
allRing = false(imageSize);
allDarkCandidate = false(imageSize);
allEdgeCandidate = false(imageSize);
allLineSupport = false(imageSize);
allAngleResponse = cell(1, angleCount);
for angleIndex = 1:angleCount
    allAngleResponse{angleIndex} = false(imageSize);
end
allDetectorCandidate = false(imageSize);
allLashCore = false(imageSize);
allLashProtection = zeros(imageSize);
allLaunchMask = false(imageSize);
allNearEye = false(imageSize);
perEye = cell(1, numel(identityMasks));
for eyeIndex = 1:numel(identityMasks)
    identityCore = identityMasks{eyeIndex};
    softSupport = softSupportMasks{eyeIndex};
    launchMask = identityCore | softSupport;
    if ~any(launchMask(:))
        continue;
    end
    currentBand = imdilate(launchMask, ...
        strel('disk', periocularRadius, 0));
    currentRing = currentBand & ~launchMask;
    if any(browCore(:))
        browRadius = min(5, max(2, round(.010 * double(faceScale))));
        browExclusion = imdilate(browCore, strel('disk', browRadius, 0));
        currentRing(browExclusion) = false;
    end
    current = reconstructExistingLashLines(grayImage, launchMask, ...
        currentRing, identityCore, faceScale, softRadius, ...
        any(softSupport(:)));
    allNeighborhood = allNeighborhood | currentBand;
    allRing = allRing | currentRing;
    allDarkCandidate = allDarkCandidate | current.darkCandidate;
    allEdgeCandidate = allEdgeCandidate | current.edgeCandidate;
    allLineSupport = allLineSupport | current.lineSupport;
    for angleIndex = 1:angleCount
        allAngleResponse{angleIndex} = allAngleResponse{angleIndex} | ...
            current.lineResponse{angleIndex};
    end
    allDetectorCandidate = allDetectorCandidate | current.candidate;
    allLashCore = allLashCore | current.lashCore;
    allLashProtection = max(allLashProtection, current.protection);
    allLaunchMask = allLaunchMask | launchMask;
    allNearEye = allNearEye | current.nearEye;
    perEye{eyeIndex} = current;
end

lineSupportFromAngleResponse = false(imageSize);
for angleIndex = 1:angleCount
    lineSupportFromAngleResponse = lineSupportFromAngleResponse | ...
        allAngleResponse{angleIndex};
end
lineSupportFromAngleMaxError = max(abs(double(lineSupportFromAngleResponse(:)) - ...
    double(allLineSupport(:))));
if lineSupportFromAngleMaxError > 0
    error('diagnoseLashAngleGroupedReconstruction:AngleResponseUnionMismatch', ...
        '逐 angle response union 与当前 lineSupport 不一致。');
end

% 当前 detector 的 evidence 只在现有眼周 ring 和既有 near-eye 约束内
% 允许参与几何重构。edgeCandidate 是 darkCandidate 的既有子集，仍显式
% 保留三类 evidence 名称以便离线诊断和审计。
allowedEvidence = allRing & allNearEye & ...
    (allDarkCandidate | allEdgeCandidate | allLineSupport);
seed = allDetectorCandidate & allowedEvidence;
if any(seed(:))
    connectedEvidence = imreconstruct(seed, allowedEvidence, 8);
else
    connectedEvidence = false(imageSize);
end

evidence = struct( ...
    'angles', angles, ...
    'faceScale', double(faceScale), ...
    'periocularRadius', periocularRadius, ...
    'softRadius', softRadius, ...
    'softPeak', .99, ...
    'leftEyeEvidence', leftEyeEvidence, ...
    'rightEyeEvidence', rightEyeEvidence, ...
    'browEvidence', browEvidence, ...
    'browCore', browCore, ...
    'eyeNeighborhood', allNeighborhood, ...
    'ring', allRing, ...
    'launchMask', allLaunchMask, ...
    'nearEye', allNearEye, ...
    'darkCandidate', allDarkCandidate, ...
    'edgeCandidate', allEdgeCandidate, ...
    'lineSupport', allLineSupport, ...
    'lineResponse', {allAngleResponse}, ...
    'lineSupportFromAngleResponse', lineSupportFromAngleResponse, ...
    'lineSupportFromAngleMaxError', lineSupportFromAngleMaxError, ...
    'detectorSeed', allDetectorCandidate, ...
    'lashCore', allLashCore, ...
    'existingLashProtection', allLashProtection, ...
    'allowedEvidence', allowedEvidence, ...
    'connectedEvidence', connectedEvidence, ...
    'perEye', {perEye});
end

function result = reconstructExistingLashLines(grayImage, launchMask, ...
        ring, identityCore, faceScale, softRadius, allowSoftProtection)
% 下列尺度、百分位和逻辑逐字复用当前生产 detectLashLines。它们不是
% 08.7 候选参数；该复制用于在不修改 src 的离线票中重建内部 evidence，
% 并由 baseline lashProtection 精确一致性检查防止诊断漂移。
result = struct();
angles = 0:15:165;
result.angles = angles;
result.lineResponse = cell(1, numel(angles));
for angleIndex = 1:numel(angles)
    result.lineResponse{angleIndex} = false(size(launchMask));
end
result.lashCore = false(size(launchMask));
result.protection = zeros(size(launchMask));
result.darkCandidate = false(size(launchMask));
result.edgeCandidate = false(size(launchMask));
result.lineSupport = false(size(launchMask));
result.candidate = false(size(launchMask));
result.nearEye = false(size(launchMask));
if ~any(ring(:))
    return;
end

darkSigma = min(2.4, max(.7, .004 * double(faceScale)));
lineSigma = min(1.35, max(.45, .002 * double(faceScale)));
smoothed = imgaussfilt(grayImage, darkSigma, 'Padding', 'replicate');
lineImage = imgaussfilt(grayImage, lineSigma, 'Padding', 'replicate');
[gradientX, gradientY] = gradient(lineImage);
gradientMagnitude = hypot(gradientX, gradientY);
darkResidual = smoothed - grayImage;
darkValues = sort(darkResidual(ring));
gradientValues = sort(gradientMagnitude(ring));
darkThreshold = max(.010, percentileValue(darkValues, .62));
gradientThreshold = max(.012, percentileValue(gradientValues, .65));
darkCandidate = ring & darkResidual >= darkThreshold;
edgeCandidate = darkCandidate & gradientMagnitude >= gradientThreshold;
if ~any(darkCandidate(:))
    return;
end
lineLength = min(6, max(3, round(.007 * double(faceScale))));
gapLength = min(5, max(2, round(.006 * double(faceScale))));
lineSupport = false(size(darkCandidate));
for angleIndex = 1:numel(angles)
    angle = angles(angleIndex);
    closingElement = strel('line', gapLength, angle);
    openingElement = strel('line', lineLength, angle);
    closed = imclose(darkCandidate, closingElement);
    currentResponse = imdilate(imopen(closed, openingElement), ...
        strel('disk', 1, 0));
    result.lineResponse{angleIndex} = currentResponse;
    lineSupport = lineSupport | currentResponse;
end
candidate = darkCandidate & (edgeCandidate | lineSupport);
lashDistance = min(9, max(4, round(.014 * double(faceScale))));
nearEye = bwdist(launchMask) <= lashDistance;
candidate = candidate & nearEye;
hardDarkThreshold = max(.045, percentileValue(darkValues, .80));
hardGradientThreshold = max(.018, percentileValue(gradientValues, .75));
if any(identityCore(:))
    hardNearEye = bwdist(identityCore) <= lashDistance;
    result.lashCore = candidate & ~identityCore & hardNearEye & ...
        darkResidual >= hardDarkThreshold & ...
        (gradientMagnitude >= hardGradientThreshold | lineSupport);
end
if allowSoftProtection
    protectionSeed = candidate;
else
    protectionSeed = result.lashCore;
end
if any(protectionSeed(:))
    result.protection = featherSoftMask(protectionSeed, softRadius, .99);
    result.protection(protectionSeed) = .99;
end
result.darkCandidate = darkCandidate;
result.edgeCandidate = edgeCandidate;
result.lineSupport = lineSupport;
result.candidate = candidate;
result.nearEye = nearEye;
end

function grouped = reconstructAngleGroupedGeometry(evidence)
angles = evidence.angles;
angleCount = numel(angles);
angleResponse = evidence.lineResponse;
allowedEvidence = cell(1, angleCount);
seed = cell(1, angleCount);
reconstructed = cell(1, angleCount);
unionGeometry = false(size(evidence.eyeNeighborhood));
for angleIndex = 1:angleCount
    response = logical(angleResponse{angleIndex});
    % 08.7 只复用已有 detector evidence。与 08.6 相比，
    % lineResponse_k 在 reconstruction 前不再与其它 angle OR。
    currentAllowed = evidence.ring & evidence.nearEye & ...
        evidence.darkCandidate & ...
        (evidence.edgeCandidate | response) & response;
    currentSeed = evidence.detectorSeed & currentAllowed;
    if any(currentSeed(:))
        currentReconstruction = imreconstruct(currentSeed, ...
            currentAllowed, 8);
    else
        currentReconstruction = false(size(currentSeed));
    end
    if any(currentReconstruction(:) & ~currentAllowed(:))
        error('diagnoseLashAngleGroupedReconstruction:AngleReconstructionEscape', ...
            'angle %g reconstruction 超出自身 allowedEvidence。', ...
            angles(angleIndex));
    end
    allowedEvidence{angleIndex} = currentAllowed;
    seed{angleIndex} = currentSeed;
    reconstructed{angleIndex} = currentReconstruction;
    unionGeometry = unionGeometry | currentReconstruction;
end

overlapMatrix = zeros(angleCount, angleCount);
for row = 1:angleCount
    for column = row:angleCount
        overlapMatrix(row, column) = nnz(reconstructed{row} & ...
            reconstructed{column});
        overlapMatrix(column, row) = overlapMatrix(row, column);
    end
end
pairwiseOverlapPixels = sum(overlapMatrix(triu(true(angleCount), 1)));
angleOverlapMask = false(size(unionGeometry));
for angleIndex = 1:angleCount
    other = false(size(unionGeometry));
    for otherIndex = 1:angleCount
        if otherIndex ~= angleIndex
            other = other | reconstructed{otherIndex};
        end
    end
    angleOverlapMask = angleOverlapMask | ...
        (reconstructed{angleIndex} & other);
end
angleStats = struct( ...
    'angles', angles, ...
    'responsePixels', zeros(1, angleCount), ...
    'seedPixels', zeros(1, angleCount), ...
    'reconstructedPixels', zeros(1, angleCount), ...
    'overlapPixels', zeros(1, angleCount));
for angleIndex = 1:angleCount
    angleStats.responsePixels(angleIndex) = nnz(angleResponse{angleIndex});
    angleStats.seedPixels(angleIndex) = nnz(seed{angleIndex});
    angleStats.reconstructedPixels(angleIndex) = nnz(reconstructed{angleIndex});
    angleStats.overlapPixels(angleIndex) = nnz(angleOverlapMask & ...
        reconstructed{angleIndex});
end
angleStats.pairwiseOverlapPixels = pairwiseOverlapPixels;
angleStats.finalUnionPixels = nnz(unionGeometry);
angleStats.finalOverlapPixels = nnz(angleOverlapMask);

grouped = struct( ...
    'angles', angles, ...
    'response', {angleResponse}, ...
    'allowedEvidence', {allowedEvidence}, ...
    'seed', {seed}, ...
    'reconstructed', {reconstructed}, ...
    'unionGeometry', unionGeometry, ...
    'overlapMatrix', overlapMatrix, ...
    'overlapMask', angleOverlapMask, ...
    'angleStats', angleStats);
end

function validateEvidenceReconstruction(evidence, textureDiagnostics, ...
        baselineLashProtection, imageSize, tolerance)
expectedNeighborhood = logical(textureDiagnostics.eyeNeighborhood);
expectedCore = logical(textureDiagnostics.lashCore);
if ~isequal(evidence.eyeNeighborhood, expectedNeighborhood)
    error('diagnoseLashAngleGroupedReconstruction:EvidenceNeighborhoodMismatch', ...
        '重建的 eyeNeighborhood 与当前生产 evidence 不一致。');
end
if ~isequal(evidence.lashCore, expectedCore)
    error('diagnoseLashAngleGroupedReconstruction:EvidenceCoreMismatch', ...
        '重建的 lashCore 与当前生产 evidence 不一致。');
end
maxError = max(abs(evidence.existingLashProtection(:) - ...
    baselineLashProtection(:)));
if maxError > tolerance
    error('diagnoseLashAngleGroupedReconstruction:EvidenceProtectionMismatch', ...
        '重建的现有 lashProtection 最大误差 %.17g。', maxError);
end
evidence.reconstructionMaxError = maxError;
if evidence.lineSupportFromAngleMaxError > tolerance
    error('diagnoseLashAngleGroupedReconstruction:AngleResponseUnionMismatch', ...
        'angle response union 最大误差 %.17g。', ...
        evidence.lineSupportFromAngleMaxError);
end
if numel(evidence.lineResponse) ~= numel(evidence.angles)
    error('diagnoseLashAngleGroupedReconstruction:MissingAngleResponse', ...
        'angle response 数量与固定 angle 集合不一致。');
end
for angleIndex = 1:numel(evidence.angles)
    validateMask(evidence.lineResponse{angleIndex}, imageSize, ...
        sprintf('lineResponse{%d}', angleIndex));
end
if any(evidence.connectedEvidence(:) & ~evidence.allowedEvidence(:))
    error('diagnoseLashAngleGroupedReconstruction:InvalidConnectedEvidence', ...
        'connectedEvidence 超出 allowedEvidence。');
end
if any(evidence.connectedEvidence(:) & ~evidence.eyeNeighborhood(:))
    error('diagnoseLashAngleGroupedReconstruction:InvalidNeighborhood', ...
        'connectedEvidence 超出 eyeNeighborhood。');
end
validateArray(evidence.existingLashProtection, imageSize, ...
    'existingLashProtection');
end

function validateTextureDiagnostics(textureDiagnostics, imageSize)
required = {'occluderProtection', 'browProtection', 'lipProtection', ...
    'noseProtection', 'eyeDetailProtection', 'lashProtection', ...
    'periocularProtection', 'doubleEyelidProtection', 'eyeNeighborhood', ...
    'lashCore'};
if ~isstruct(textureDiagnostics) || ~isscalar(textureDiagnostics) || ...
        ~all(isfield(textureDiagnostics, required))
    error('diagnoseLashAngleGroupedReconstruction:MissingTextureDiagnostic', ...
        '纹理诊断缺少 Issue 08.7 所需字段。');
end
for index = 1:numel(required)
    name = required{index};
    value = textureDiagnostics.(name);
    if strcmp(name, 'lashCore')
        if ~islogical(value) || ~isequal(size(value), imageSize)
            error('diagnoseLashAngleGroupedReconstruction:InvalidTextureDiagnostic', ...
                '%s 尺寸或类型无效。', name);
        end
    else
        validateMask(value, imageSize, name);
    end
end
end

function validateCandidateMaskIsolation(baselineMasks, candidateMasks, ...
        candidateTexture, candidateEye, imageSize, tolerance)
required = {'structureProtectionMask', 'hardProtectionMask'};
for index = 1:numel(required)
    name = required{index};
    if max(abs(double(baselineMasks.(name)(:)) - ...
            double(candidateMasks.(name)(:)))) > tolerance
        error('diagnoseLashAngleGroupedReconstruction:SingleFactorViolation', ...
            '候选意外修改了 %s。', name);
    end
end
unchangedNames = {'whiteningProtectionMask', 'chromaProtectionMask', ...
    'toneProtectionMask', 'strengthMap', 'faceStrengthMap', ...
    'nonFaceStrengthMap', 'skinMask', 'faceSkinMask', ...
    'nonFaceSkinMask', 'noseMask'};
for index = 1:numel(unchangedNames)
    name = unchangedNames{index};
    if isfield(baselineMasks, name) && isfield(candidateMasks, name) && ...
            max(abs(double(baselineMasks.(name)(:)) - ...
            double(candidateMasks.(name)(:)))) > tolerance
        error('diagnoseLashAngleGroupedReconstruction:SingleFactorViolation', ...
            '候选意外修改了 %s。', name);
    end
end
if any(candidateTexture(:) < 0) || any(candidateTexture(:) > 1) || ...
        any(candidateEye(:) < 0) || any(candidateEye(:) > 1)
    error('diagnoseLashAngleGroupedReconstruction:InvalidCandidateProtection', ...
        '候选 texture/eye protection 必须位于 [0,1]。');
end
if ~isequal(size(candidateMasks.textureProtectionMask), imageSize)
    error('diagnoseLashAngleGroupedReconstruction:InvalidCandidateMask', ...
        'Candidate textureProtectionMask 尺寸无效。');
end
end

function processing = buildFrozenProcessing(composeDiagnostics)
required = {'baseSupport', 'baseDelta', 'whiteningSupport', ...
    'whiteningDelta', 'toneSupport', 'toneTargetCb', 'toneTargetCr'};
if ~isstruct(composeDiagnostics) || ~all(isfield(composeDiagnostics, required))
    error('diagnoseLashAngleGroupedReconstruction:MissingFrozenProcessing', ...
        '无法从同次 compose 诊断重建冻结的 Base/tone/whitening。');
end
processing = struct( ...
    'baseLuminance', struct('supportMap', composeDiagnostics.baseSupport, ...
    'baseDelta', composeDiagnostics.baseDelta), ...
    'skinTone', struct('toneSupport', composeDiagnostics.toneSupport, ...
    'outputCb', composeDiagnostics.toneTargetCb, ...
    'outputCr', composeDiagnostics.toneTargetCr), ...
    'whitening', struct('supportMap', composeDiagnostics.whiteningSupport, ...
    'delta', composeDiagnostics.whiteningDelta));
end

function metrics = makeMetrics(manualMask, baselineSupport, candidate084Support, ...
        candidate086Support, candidate087Support, baselineLash, ...
        candidate084Lash, candidate086Lash, candidate087Lash, baselineFine, ...
        candidate084Fine, candidate086Fine, candidate087Fine, baselineMid, ...
        candidate084Mid, candidate086Mid, candidate087Mid, baselineRgb, ...
        candidate084Rgb, candidate086Rgb, candidate087Rgb, baselineLuma, ...
        candidate084Luma, candidate086Luma, candidate087Luma, tolerance)
metrics = struct( ...
    'manualLashPixels', nnz(manualMask), ...
    'baseline', makeGeometryStats(baselineSupport, manualMask, ...
        baselineLash, tolerance), ...
    'candidate084', makeGeometryStats(candidate084Support, manualMask, ...
        candidate084Lash, tolerance), ...
    'candidate086', makeGeometryStats(candidate086Support, manualMask, ...
        candidate086Lash, tolerance), ...
    'candidate087', makeGeometryStats(candidate087Support, manualMask, ...
        candidate087Lash, tolerance), ...
    'baselineRepairFineAbsAction', makeStats(abs(baselineFine(manualMask)), tolerance), ...
    'candidate084RepairFineAbsAction', makeStats(abs(candidate084Fine(manualMask)), tolerance), ...
    'candidate086RepairFineAbsAction', makeStats(abs(candidate086Fine(manualMask)), tolerance), ...
    'candidate087RepairFineAbsAction', makeStats(abs(candidate087Fine(manualMask)), tolerance), ...
    'baselineRepairMidAbsAction', makeStats(abs(baselineMid(manualMask)), tolerance), ...
    'candidate084RepairMidAbsAction', makeStats(abs(candidate084Mid(manualMask)), tolerance), ...
    'candidate086RepairMidAbsAction', makeStats(abs(candidate086Mid(manualMask)), tolerance), ...
    'candidate087RepairMidAbsAction', makeStats(abs(candidate087Mid(manualMask)), tolerance), ...
    'baselineFinalRgbDistanceToOriginal', makeStats(baselineRgb(manualMask), tolerance), ...
    'candidate084FinalRgbDistanceToOriginal', makeStats(candidate084Rgb(manualMask), tolerance), ...
    'candidate086FinalRgbDistanceToOriginal', makeStats(candidate086Rgb(manualMask), tolerance), ...
    'candidate087FinalRgbDistanceToOriginal', makeStats(candidate087Rgb(manualMask), tolerance), ...
    'baselineFinalLuminanceDistanceToOriginal', makeStats(baselineLuma(manualMask), tolerance), ...
    'candidate084FinalLuminanceDistanceToOriginal', makeStats(candidate084Luma(manualMask), tolerance), ...
    'candidate086FinalLuminanceDistanceToOriginal', makeStats(candidate086Luma(manualMask), tolerance), ...
    'candidate087FinalLuminanceDistanceToOriginal', makeStats(candidate087Luma(manualMask), tolerance));
end

function stats = makeGeometryStats(support, manualMask, protection, tolerance)
truePositive = support & manualMask;
falsePositive = support & ~manualMask;
falseNegative = ~support & manualMask;
fpStats = makeComponentStats(falsePositive);
stats = struct( ...
    'supportPixels', nnz(support), ...
    'truePositivePixels', nnz(truePositive), ...
    'falsePositivePixels', nnz(falsePositive), ...
    'falseNegativePixels', nnz(falseNegative), ...
    'recall', safeRatio(nnz(truePositive), nnz(manualMask)), ...
    'precision', safeRatio(nnz(truePositive), nnz(support)), ...
    'manualProtection', makeStats(protection(manualMask), tolerance), ...
    'falsePositiveComponents', fpStats);
end

function stats = makeComponentStats(mask)
components = bwconncomp(mask, 8);
if components.NumObjects == 0
    sizes = zeros(0, 1);
    largest = 0;
    longestSpan = 0;
else
    sizes = cellfun(@numel, components.PixelIdxList).';
    largest = max(sizes);
    [rows, columns] = find(mask);
    longestSpan = max(max(rows) - min(rows) + 1, ...
        max(columns) - min(columns) + 1);
end
stats = struct( ...
    'componentCount', components.NumObjects, ...
    'componentSizes', sizes, ...
    'largestComponentPixels', largest, ...
    'longestBoundingSpan', longestSpan);
end

function assessment = assessNumericGeometry(metrics, tolerance)
p86 = metrics.candidate086.precision;
p87 = metrics.candidate087.precision;
r86 = metrics.candidate086.recall;
r87 = metrics.candidate087.recall;
precisionImproved = p87 > p86 + tolerance;
recallNotLower = r87 >= r86 - tolerance;
fpPixelsReduced = metrics.candidate087.falsePositivePixels < ...
    metrics.candidate086.falsePositivePixels;
fpLargestReduced = metrics.candidate087.falsePositiveComponents ...
    .largestComponentPixels < ...
    metrics.candidate086.falsePositiveComponents.largestComponentPixels;
if precisionImproved && recallNotLower && (fpPixelsReduced || fpLargestReduced)
    caseName = 'numericGeometrySupportsCandidate';
else
    caseName = 'numericGeometryDoesNotSupportCandidate';
end
assessment = struct( ...
    'case', caseName, ...
    'requiresVisualReview', true, ...
    'precisionImproved', precisionImproved, ...
    'recallNotLower', recallNotLower, ...
    'falsePositivePixelsReduced', fpPixelsReduced, ...
    'falsePositiveLargestComponentReduced', fpLargestReduced, ...
    'baselineComparison', '08.6 -> 08.7', ...
    'basis', ['Precision/Recall 和 FP 连续分量仅作离线证据；', ...
    '最终 Case 必须结合同尺度主图人工确认。']);
end

function assessment = assessRepair(metrics, tolerance)
fine086 = metrics.candidate086RepairFineAbsAction.sum;
fine087 = metrics.candidate087RepairFineAbsAction.sum;
mid086 = metrics.candidate086RepairMidAbsAction.sum;
mid087 = metrics.candidate087RepairMidAbsAction.sum;
assessment = struct( ...
    'fineNotWorseThan086', fine087 <= fine086 + tolerance, ...
    'midNotWorseThan086', mid087 <= mid086 + tolerance, ...
    'fineReductionFrom086', fine086 - fine087, ...
    'midReductionFrom086', mid086 - mid087, ...
    'requiresVisualReview', true);
end

function value = safeRatio(numerator, denominator)
if denominator == 0
    value = NaN;
else
    value = numerator / denominator;
end
end

function stats = makeStats(values, tolerance)
values = double(values(:));
if isempty(values)
    stats = struct('values', values, 'count', 0, 'sum', 0, ...
        'mean', NaN, 'min', NaN, 'max', NaN, ...
        'nonzeroPixels', 0, 'nonzeroFraction', NaN);
    return;
end
stats = struct( ...
    'values', values, ...
    'count', numel(values), ...
    'sum', sum(values), ...
    'mean', mean(values), ...
    'min', min(values), ...
    'max', max(values), ...
    'nonzeroPixels', nnz(abs(values) > tolerance), ...
    'nonzeroFraction', nnz(abs(values) > tolerance) / numel(values));
end

function diagnostics = makeCandidateTextureDiagnostics(base, ...
        candidateEyeDetail, candidateLash)
diagnostics = base;
diagnostics.eyeDetailProtection = candidateEyeDetail;
diagnostics.lashProtection = candidateLash;
end

function paths = writeArtifacts(outputFolder, inputImage, manualMask, ...
        baselineSupport, candidate084Support, candidate086Support, ...
        candidate087Support, baselineFine, candidate084Fine, ...
        candidate086Fine, candidate087Fine, baselineMid, candidate084Mid, ...
        candidate086Mid, candidate087Mid, baselineOutput, candidate084Output, ...
        candidate086Output, candidate087Output, angleGrouped, lashRoi)
originalCrop = cropImage(inputImage, lashRoi);
manualCrop = cropImage(manualMask, lashRoi);
paths = struct('outputFolder', outputFolder);
paths.originalLash = fullfile(outputFolder, 'original_lash.png');
writeFinalLashFigure(originalCrop, originalCrop, manualCrop, ...
    'A 原图 Original lash', paths.originalLash);
paths.baselineSupport = fullfile(outputFolder, 'baseline_support.png');
writeSupportFigure(originalCrop, cropImage(baselineSupport, lashRoi), ...
    manualCrop, 'Baseline support', paths.baselineSupport);
paths.support084 = fullfile(outputFolder, 'support_08_4.png');
writeSupportFigure(originalCrop, cropImage(candidate084Support, lashRoi), ...
    manualCrop, '08.4 Candidate support', paths.support084);
paths.support086 = fullfile(outputFolder, 'support_08_6.png');
writeSupportFigure(originalCrop, cropImage(candidate086Support, lashRoi), ...
    manualCrop, '08.6 Candidate support', paths.support086);
paths.support087 = fullfile(outputFolder, ...
    'support_08_7_angle_grouped.png');
writeSupportFigure(originalCrop, cropImage(candidate087Support, lashRoi), ...
    manualCrop, '08.7 Angle-Grouped Candidate support', paths.support087);
paths.manualVs086 = fullfile(outputFolder, 'manual_vs_08_6.png');
writeManualSupportComparison(originalCrop, manualCrop, ...
    cropImage(candidate086Support, lashRoi), '08.6 Candidate', ...
    paths.manualVs086);
paths.manualVs087 = fullfile(outputFolder, 'manual_vs_08_7.png');
writeManualSupportComparison(originalCrop, manualCrop, ...
    cropImage(candidate087Support, lashRoi), '08.7 Angle-Grouped Candidate', ...
    paths.manualVs087);
paths.falsePositive086 = fullfile(outputFolder, ...
    'false_positive_08_6.png');
writeErrorFigure(originalCrop, cropImage(candidate086Support & ~manualMask, ...
    lashRoi), manualCrop, '08.6 false positive = support & ~manual', ...
    paths.falsePositive086);
paths.falsePositive087 = fullfile(outputFolder, ...
    'false_positive_08_7.png');
writeErrorFigure(originalCrop, cropImage(candidate087Support & ~manualMask, ...
    lashRoi), manualCrop, '08.7 false positive = support & ~manual', ...
    paths.falsePositive087);
paths.falseNegative086 = fullfile(outputFolder, ...
    'false_negative_08_6.png');
writeErrorFigure(originalCrop, cropImage(manualMask & ~candidate086Support, ...
    lashRoi), manualCrop, '08.6 false negative = manual & ~support', ...
    paths.falseNegative086);
paths.falseNegative087 = fullfile(outputFolder, ...
    'false_negative_08_7.png');
writeErrorFigure(originalCrop, cropImage(manualMask & ~candidate087Support, ...
    lashRoi), manualCrop, '08.7 false negative = manual & ~support', ...
    paths.falseNegative087);
paths.repairFine086 = fullfile(outputFolder, 'repair_fine_08_6.png');
writeDeltaFigure(originalCrop, manualCrop, cropImage(candidate086Fine, lashRoi), ...
    '08.6 Repair Fine absolute action', paths.repairFine086);
paths.repairFine087 = fullfile(outputFolder, 'repair_fine_08_7.png');
writeDeltaFigure(originalCrop, manualCrop, cropImage(candidate087Fine, lashRoi), ...
    '08.7 Repair Fine absolute action', paths.repairFine087);
paths.repairMid086 = fullfile(outputFolder, 'repair_mid_08_6.png');
writeDeltaFigure(originalCrop, manualCrop, cropImage(candidate086Mid, lashRoi), ...
    '08.6 Repair Mid absolute action', paths.repairMid086);
paths.repairMid087 = fullfile(outputFolder, 'repair_mid_08_7.png');
writeDeltaFigure(originalCrop, manualCrop, cropImage(candidate087Mid, lashRoi), ...
    '08.7 Repair Mid absolute action', paths.repairMid087);
paths.final084 = fullfile(outputFolder, 'final_08_4.png');
writeFinalLashFigure(originalCrop, cropImage(candidate084Output, lashRoi), ...
    manualCrop, 'C 08.4 Candidate final lash', paths.final084);
paths.final086 = fullfile(outputFolder, 'final_08_6.png');
writeFinalLashFigure(originalCrop, cropImage(candidate086Output, lashRoi), ...
    manualCrop, 'D 08.6 Candidate final lash', paths.final086);
paths.final087 = fullfile(outputFolder, 'final_08_7.png');
writeFinalLashFigure(originalCrop, cropImage(candidate087Output, lashRoi), ...
    manualCrop, 'E 08.7 Angle-Grouped Candidate final lash', paths.final087);
paths.angleResponseOverview = fullfile(outputFolder, ...
    'angle_response_overview.png');
writeAngleOverview(originalCrop, manualCrop, angleGrouped.response, ...
    angleGrouped.angles, lashRoi, 'Line response by existing angle', ...
    paths.angleResponseOverview);
paths.angleReconstructionOverview = fullfile(outputFolder, ...
    'angle_reconstruction_overview.png');
writeAngleOverview(originalCrop, manualCrop, angleGrouped.reconstructed, ...
    angleGrouped.angles, lashRoi, 'Independent reconstruction by angle', ...
    paths.angleReconstructionOverview);
paths.angleResponse = cell(1, numel(angleGrouped.angles));
paths.angleReconstruction = cell(1, numel(angleGrouped.angles));
for angleIndex = 1:numel(angleGrouped.angles)
    angle = angleGrouped.angles(angleIndex);
    paths.angleResponse{angleIndex} = fullfile(outputFolder, ...
        sprintf('line_response_angle_%03d.png', angle));
    writeSingleAngleFigure(originalCrop, manualCrop, ...
        cropImage(angleGrouped.response{angleIndex}, lashRoi), ...
        sprintf('line response angle_%03d', angle), ...
        paths.angleResponse{angleIndex});
    paths.angleReconstruction{angleIndex} = fullfile(outputFolder, ...
        sprintf('reconstruction_angle_%03d.png', angle));
    writeSingleAngleFigure(originalCrop, manualCrop, ...
        cropImage(angleGrouped.reconstructed{angleIndex}, lashRoi), ...
        sprintf('reconstruction angle_%03d', angle), ...
        paths.angleReconstruction{angleIndex});
end
paths.supportComparison = fullfile(outputFolder, ...
    'support_geometry_comparison.png');
writeSupportComparison(originalCrop, manualCrop, ...
    cropImage(baselineSupport, lashRoi), cropImage(candidate084Support, lashRoi), ...
    cropImage(candidate086Support, lashRoi), cropImage(candidate087Support, lashRoi), ...
    paths.supportComparison);
paths.finalComparison = fullfile(outputFolder, ...
    'final_angle_grouped_comparison.png');
writeFinalComparison(originalCrop, cropImage(baselineOutput, lashRoi), ...
    cropImage(candidate084Output, lashRoi), cropImage(candidate086Output, lashRoi), ...
    cropImage(candidate087Output, lashRoi), manualCrop, paths.finalComparison);
end

function writeSupportFigure(originalCrop, supportCrop, manualCrop, label, path)
figureHandle = figure('Visible', 'off', 'Color', 'white', ...
    'Position', [100, 100, 1500, 560]);
tiledlayout(1, 2, 'Padding', 'compact', 'TileSpacing', 'compact');
nexttile;
imshow(originalCrop);
hold on;
drawContourIfPresent(manualCrop, 'r', 1.8);
hold off;
title('原图 + manualLashMask');
nexttile;
imagesc(double(supportCrop));
axis image off;
caxis([0, 1]);
colorbar;
hold on;
drawContourIfPresent(manualCrop, 'r', 1.5);
hold off;
title(label, 'Interpreter', 'none');
exportgraphics(figureHandle, path, 'Resolution', 170);
close(figureHandle);
end

function writeManualSupportComparison(originalCrop, manualCrop, supportCrop, ...
        label, path)
figureHandle = figure('Visible', 'off', 'Color', 'white', ...
    'Position', [80, 80, 2100, 560]);
tiledlayout(1, 3, 'Padding', 'compact', 'TileSpacing', 'compact');
nexttile;
imshow(originalCrop);
hold on;
drawContourIfPresent(manualCrop, 'r', 1.8);
hold off;
title('原图 + 红色 manualLashMask');
nexttile;
imagesc(double(supportCrop));
axis image off;
caxis([0, 1]);
colorbar;
hold on;
drawContourIfPresent(manualCrop, 'r', 1.5);
hold off;
title([label ' support'], 'Interpreter', 'none');
nexttile;
overlap = double(supportCrop) + 2 * double(manualCrop);
imagesc(overlap);
axis image off;
caxis([0, 3]);
colorbar;
title('0=背景，1=仅support，2=仅manual，3=交集');
exportgraphics(figureHandle, path, 'Resolution', 170);
close(figureHandle);
end

function writeErrorFigure(originalCrop, errorCrop, manualCrop, label, path)
figureHandle = figure('Visible', 'off', 'Color', 'white', ...
    'Position', [100, 100, 1500, 560]);
tiledlayout(1, 2, 'Padding', 'compact', 'TileSpacing', 'compact');
nexttile;
imshow(originalCrop);
hold on;
drawContourIfPresent(manualCrop, 'r', 1.8);
drawContourIfPresent(errorCrop, 'm', 1.6);
hold off;
title('原图：红=manual，洋红=错误区域');
nexttile;
imagesc(double(errorCrop));
axis image off;
caxis([0, 1]);
colorbar;
hold on;
drawContourIfPresent(manualCrop, 'r', 1.5);
hold off;
title(label, 'Interpreter', 'none');
exportgraphics(figureHandle, path, 'Resolution', 170);
close(figureHandle);
end

function writeDeltaFigure(originalCrop, manualCrop, deltaCrop, label, path)
figureHandle = figure('Visible', 'off', 'Color', 'white', ...
    'Position', [100, 100, 1500, 560]);
tiledlayout(1, 2, 'Padding', 'compact', 'TileSpacing', 'compact');
nexttile;
imshow(originalCrop);
hold on;
drawContourIfPresent(manualCrop, 'r', 1.8);
hold off;
title('原图 + manualLashMask');
nexttile;
imagesc(abs(double(deltaCrop)));
axis image off;
deltaLimit = max(abs(double(deltaCrop(:))));
if isempty(deltaLimit) || deltaLimit <= 0 || ~isfinite(deltaLimit)
    deltaLimit = 1;
end
caxis([0, deltaLimit]);
colorbar;
hold on;
drawContourIfPresent(manualCrop, 'r', 1.5);
hold off;
title(label, 'Interpreter', 'none');
exportgraphics(figureHandle, path, 'Resolution', 170);
close(figureHandle);
end

function writeFinalLashFigure(originalCrop, finalCrop, manualCrop, label, path)
figureHandle = figure('Visible', 'off', 'Color', 'white', ...
    'Position', [100, 100, 1500, 560]);
tiledlayout(1, 2, 'Padding', 'compact', 'TileSpacing', 'compact');
nexttile;
imshow(originalCrop);
hold on;
drawContourIfPresent(manualCrop, 'r', 1.8);
hold off;
title('原图 + manualLashMask');
nexttile;
imshow(finalCrop);
hold on;
drawContourIfPresent(manualCrop, 'r', 1.8);
hold off;
title(label, 'Interpreter', 'none');
exportgraphics(figureHandle, path, 'Resolution', 170);
close(figureHandle);
end

function writeSingleAngleFigure(originalCrop, manualCrop, angleCrop, ...
        figureTitle, path)
figureHandle = figure('Visible', 'off', 'Color', 'white', ...
    'Position', [100, 100, 1300, 560]);
tiledlayout(1, 2, 'Padding', 'compact', 'TileSpacing', 'compact');
nexttile;
imshow(originalCrop);
hold on;
drawContourIfPresent(manualCrop, 'r', 1.5);
hold off;
title('原图 + manualLashMask');
nexttile;
imagesc(double(angleCrop));
axis image off;
caxis([0, 1]);
colorbar;
hold on;
drawContourIfPresent(manualCrop, 'r', 1.3);
hold off;
title(figureTitle, 'Interpreter', 'none');
exportgraphics(figureHandle, path, 'Resolution', 170);
close(figureHandle);
end

function writeAngleOverview(originalCrop, manualCrop, angleMasks, angles, ...
        lashRoi, figureTitle, path)
figureHandle = figure('Visible', 'off', 'Color', 'white', ...
    'Position', [80, 80, 1900, 1200]);
tiledlayout(3, 4, 'Padding', 'compact', 'TileSpacing', 'compact');
for angleIndex = 1:numel(angles)
    nexttile;
    responseCrop = cropImage(angleMasks{angleIndex}, lashRoi);
    imagesc(double(responseCrop));
    axis image off;
    caxis([0, 1]);
    hold on;
    drawContourIfPresent(manualCrop, 'r', 1.1);
    hold off;
    title(sprintf('%s angle_%03d', figureTitle, angles(angleIndex)), ...
        'Interpreter', 'none', 'FontSize', 8);
end
sgtitle(figureTitle, 'Interpreter', 'none');
exportgraphics(figureHandle, path, 'Resolution', 160);
close(figureHandle);
end

function writeSupportComparison(originalCrop, manualCrop, baselineCrop, ...
        candidate084Crop, candidate086Crop, candidate087Crop, path)
figureHandle = figure('Visible', 'off', 'Color', 'white', ...
    'Position', [60, 60, 3000, 600]);
tiledlayout(1, 5, 'Padding', 'compact', 'TileSpacing', 'compact');
items = {originalCrop, baselineCrop, candidate084Crop, candidate086Crop, ...
    candidate087Crop};
labels = {'A 原图', 'B Baseline support', 'C 08.4 Candidate support', ...
    'D 08.6 Candidate support', 'E 08.7 Angle-Grouped support'};
for index = 1:numel(items)
    nexttile;
    if index == 1
        imshow(items{index});
    else
        imagesc(double(items{index}));
        axis image off;
        caxis([0, 1]);
        colorbar;
    end
    hold on;
    drawContourIfPresent(manualCrop, 'r', 1.5);
    hold off;
    title(labels{index}, 'Interpreter', 'none');
end
exportgraphics(figureHandle, path, 'Resolution', 170);
close(figureHandle);
end

function writeFinalComparison(originalCrop, baselineCrop, candidate084Crop, ...
        candidate086Crop, candidate087Crop, manualCrop, path)
figureHandle = figure('Visible', 'off', 'Color', 'white', ...
    'Position', [60, 60, 3000, 600]);
tiledlayout(1, 5, 'Padding', 'compact', 'TileSpacing', 'compact');
items = {originalCrop, baselineCrop, candidate084Crop, candidate086Crop, ...
    candidate087Crop};
labels = {'A 原图', 'B Baseline', 'C 08.4 Candidate', ...
    'D 08.6 Candidate', 'E 08.7 Angle-Grouped Candidate'};
for index = 1:numel(items)
    nexttile;
    imshow(items{index});
    hold on;
    drawContourIfPresent(manualCrop, 'r', 1.5);
    hold off;
    title(labels{index}, 'Interpreter', 'none');
end
exportgraphics(figureHandle, path, 'Resolution', 170);
close(figureHandle);
end

function writeMetricsCsv(path, metrics, geometryAssessment, ...
        repairAssessment, angleGrouped, options)
row = struct( ...
    'issue', '08.7', ...
    'caseName', 'requiresVisualReview', ...
    'numericGeometryAssessment', geometryAssessment.case, ...
    'manualLashPixels', metrics.manualLashPixels, ...
    'baselineSupportPixels', metrics.baseline.supportPixels, ...
    'candidate084SupportPixels', metrics.candidate084.supportPixels, ...
    'candidate086SupportPixels', metrics.candidate086.supportPixels, ...
    'candidate087SupportPixels', metrics.candidate087.supportPixels, ...
    'baselineTruePositivePixels', metrics.baseline.truePositivePixels, ...
    'candidate084TruePositivePixels', metrics.candidate084.truePositivePixels, ...
    'candidate086TruePositivePixels', metrics.candidate086.truePositivePixels, ...
    'candidate087TruePositivePixels', metrics.candidate087.truePositivePixels, ...
    'baselineFalsePositivePixels', metrics.baseline.falsePositivePixels, ...
    'candidate084FalsePositivePixels', metrics.candidate084.falsePositivePixels, ...
    'candidate086FalsePositivePixels', metrics.candidate086.falsePositivePixels, ...
    'candidate087FalsePositivePixels', metrics.candidate087.falsePositivePixels, ...
    'baselineFalseNegativePixels', metrics.baseline.falseNegativePixels, ...
    'candidate084FalseNegativePixels', metrics.candidate084.falseNegativePixels, ...
    'candidate086FalseNegativePixels', metrics.candidate086.falseNegativePixels, ...
    'candidate087FalseNegativePixels', metrics.candidate087.falseNegativePixels, ...
    'baselineRecall', metrics.baseline.recall, ...
    'candidate084Recall', metrics.candidate084.recall, ...
    'candidate086Recall', metrics.candidate086.recall, ...
    'candidate087Recall', metrics.candidate087.recall, ...
    'baselinePrecision', metrics.baseline.precision, ...
    'candidate084Precision', metrics.candidate084.precision, ...
    'candidate086Precision', metrics.candidate086.precision, ...
    'candidate087Precision', metrics.candidate087.precision, ...
    'candidate087PrecisionImproved', geometryAssessment.precisionImproved, ...
    'candidate087RecallNotLower', geometryAssessment.recallNotLower, ...
    'candidate087FalsePositivePixelsReduced', ...
        geometryAssessment.falsePositivePixelsReduced, ...
    'candidate087FalsePositiveLargestComponentReduced', ...
        geometryAssessment.falsePositiveLargestComponentReduced, ...
    'baselineFalsePositiveLargestComponentPixels', ...
        metrics.baseline.falsePositiveComponents.largestComponentPixels, ...
    'candidate084FalsePositiveLargestComponentPixels', ...
        metrics.candidate084.falsePositiveComponents.largestComponentPixels, ...
    'candidate086FalsePositiveLargestComponentPixels', ...
        metrics.candidate086.falsePositiveComponents.largestComponentPixels, ...
    'candidate087FalsePositiveLargestComponentPixels', ...
        metrics.candidate087.falsePositiveComponents.largestComponentPixels, ...
    'baselineFalsePositiveComponentCount', ...
        metrics.baseline.falsePositiveComponents.componentCount, ...
    'candidate084FalsePositiveComponentCount', ...
        metrics.candidate084.falsePositiveComponents.componentCount, ...
    'candidate086FalsePositiveComponentCount', ...
        metrics.candidate086.falsePositiveComponents.componentCount, ...
    'candidate087FalsePositiveComponentCount', ...
        metrics.candidate087.falsePositiveComponents.componentCount, ...
    'baselineRepairFineAbsActionSum', ...
        metrics.baselineRepairFineAbsAction.sum, ...
    'candidate084RepairFineAbsActionSum', ...
        metrics.candidate084RepairFineAbsAction.sum, ...
    'candidate086RepairFineAbsActionSum', ...
        metrics.candidate086RepairFineAbsAction.sum, ...
    'candidate087RepairFineAbsActionSum', ...
        metrics.candidate087RepairFineAbsAction.sum, ...
    'baselineRepairMidAbsActionSum', ...
        metrics.baselineRepairMidAbsAction.sum, ...
    'candidate084RepairMidAbsActionSum', ...
        metrics.candidate084RepairMidAbsAction.sum, ...
    'candidate086RepairMidAbsActionSum', ...
        metrics.candidate086RepairMidAbsAction.sum, ...
    'candidate087RepairMidAbsActionSum', ...
        metrics.candidate087RepairMidAbsAction.sum, ...
    'candidate087RepairFineNotWorseThan086', ...
        repairAssessment.fineNotWorseThan086, ...
    'candidate087RepairMidNotWorseThan086', ...
        repairAssessment.midNotWorseThan086, ...
    'baselineFinalRgbDistanceToOriginalMean', ...
        metrics.baselineFinalRgbDistanceToOriginal.mean, ...
    'candidate084FinalRgbDistanceToOriginalMean', ...
        metrics.candidate084FinalRgbDistanceToOriginal.mean, ...
    'candidate086FinalRgbDistanceToOriginalMean', ...
        metrics.candidate086FinalRgbDistanceToOriginal.mean, ...
    'candidate087FinalRgbDistanceToOriginalMean', ...
        metrics.candidate087FinalRgbDistanceToOriginal.mean, ...
    'baselineFinalLuminanceDistanceToOriginalMean', ...
        metrics.baselineFinalLuminanceDistanceToOriginal.mean, ...
    'candidate084FinalLuminanceDistanceToOriginalMean', ...
        metrics.candidate084FinalLuminanceDistanceToOriginal.mean, ...
    'candidate086FinalLuminanceDistanceToOriginalMean', ...
        metrics.candidate086FinalLuminanceDistanceToOriginal.mean, ...
    'candidate087FinalLuminanceDistanceToOriginalMean', ...
        metrics.candidate087FinalLuminanceDistanceToOriginal.mean, ...
    'candidate086HardProtectionMaskChangedPixels', ...
        metrics.candidate086HardProtectionMaskChangedPixels, ...
    'hardProtectionMaskChangedPixels', metrics.hardProtectionMaskChangedPixels, ...
    'hardCoreChangedPixels', metrics.hardCoreChangedPixels, ...
    'angleCount', numel(angleGrouped.angles), ...
    'angleResponsePixelsTotal', sum(angleGrouped.angleStats.responsePixels), ...
    'angleSeedPixelsTotal', sum(angleGrouped.angleStats.seedPixels), ...
    'angleReconstructedPixelsTotal', ...
        sum(angleGrouped.angleStats.reconstructedPixels), ...
    'anglePairwiseOverlapPixels', ...
        angleGrouped.angleStats.pairwiseOverlapPixels, ...
    'angleFinalOverlapPixels', angleGrouped.angleStats.finalOverlapPixels, ...
    'angleFinalUnionPixels', angleGrouped.angleStats.finalUnionPixels, ...
    'formulaTolerance', options.formulaTolerance, ...
    'reconstructionTolerance', options.reconstructionTolerance);
writetable(struct2table(row), path);

angleTable = table(angleGrouped.angles(:), ...
    angleGrouped.angleStats.responsePixels(:), ...
    angleGrouped.angleStats.seedPixels(:), ...
    angleGrouped.angleStats.reconstructedPixels(:), ...
    angleGrouped.angleStats.overlapPixels(:), ...
    'VariableNames', {'angle', 'responsePixels', 'seedPixels', ...
    'reconstructedPixels', 'overlapPixels'});
writetable(angleTable, fullfile(fileparts(path), ...
    'lash_angle_grouped_per_angle_metrics.csv'));
end

function pathsValue = normalizeOutputFolder(value)
if nargin < 1 || isempty(value)
    value = fullfile(tempdir, ...
        'image_beauty_issue08_7_lash_angle_grouped_20260919');
end
pathsValue = normalizeText(value, 'outputFolder');
if ~isfolder(pathsValue)
    mkdir(pathsValue);
end
end

function image = cropImage(image, box)
x1 = box(1);
y1 = box(2);
x2 = min(size(image, 2), box(1) + box(3) - 1);
y2 = min(size(image, 1), box(2) + box(4) - 1);
if ismatrix(image)
    image = image(y1:y2, x1:x2);
else
    image = image(y1:y2, x1:x2, :);
end
end

function drawContourIfPresent(mask, color, lineWidth)
if any(mask(:))
    contour(mask, [0.5, 0.5], color, 'LineWidth', lineWidth);
end
end

function value = readDiagnosticArray(value, imageSize, name)
if (~isnumeric(value) && ~islogical(value)) || ~isreal(value) || ...
        ~isequal(size(value), imageSize) || any(~isfinite(value(:)))
    error('diagnoseLashAngleGroupedReconstruction:InvalidDiagnosticArray', ...
        '%s 尺寸或取值无效。', name);
end
value = double(value);
end

function validateArray(value, imageSize, name)
if (~isnumeric(value) && ~islogical(value)) || ~isreal(value) || ...
        ~isequal(size(value), imageSize) || any(~isfinite(value(:)))
    error('diagnoseLashAngleGroupedReconstruction:InvalidArray', ...
        '%s 尺寸或取值无效。', name);
end
end

function validateMask(value, imageSize, name)
validateArray(value, imageSize, name);
if any(double(value(:)) < 0) || any(double(value(:)) > 1)
    error('diagnoseLashAngleGroupedReconstruction:InvalidMask', ...
        'Mask %s 的取值不在 [0,1]。', name);
end
end

function feather = featherSoftMask(core, radius, peak)
if ~any(core(:))
    feather = zeros(size(core));
    return;
end
distance = bwdist(core);
feather = peak * max(0, 1 - distance / (radius + 1));
feather(core) = peak;
end

function value = percentileValue(sortedValues, fraction)
index = 1 + round(fraction * (numel(sortedValues) - 1));
value = sortedValues(index);
end

function value = normalizeText(value, name)
if isstring(value) && isscalar(value)
    value = char(value);
end
if ~ischar(value) || size(value, 1) ~= 1
    error('diagnoseLashAngleGroupedReconstruction:InvalidText', ...
        '%s 必须是单行文本。', name);
end
end

function valid = isValidStrength(value)
valid = isnumeric(value) && isreal(value) && isscalar(value) && ...
    isfinite(value) && value >= 0 && value <= 100;
end
