function [manualLashMask, metadata] = eyelashManualLashMask77(imageSize, lashRoi)
%EYELASHMANUALLASHMASK77 返回固定 77 原图人工睫毛真值标注。
%   该函数只消费输入尺寸和固定人工 lashRoi，不读取任何 Protection Mask、
%   Repair delta、Smoothing delta、Detector 或生产诊断结果。坐标来自 77.png
%   原图视觉核对，定义后固定用于 Issue 08.2 及其后续候选比较。
%
%   [mask, metadata] = eyelashManualLashMask77([450 512], [102 248 177 48])
%
%   标注范围包含固定 lashRoi 内可直接辨认的两段上睫毛细线：右侧主眼
%   睫毛和左下方被 ROI 截断的可见睫毛。对无法可靠区分的眼线、眼睑褶皱、
%   眼球和皮肤不主动扩张标注；每条人工线使用固定 1 像素半径保留其可见
%   的 1--3 像素细线宽度。

if nargin < 1 || isempty(imageSize)
    imageSize = [450, 512];
end
if nargin < 2 || isempty(lashRoi)
    lashRoi = [102, 248, 177, 48];
end

imageSize = double(imageSize(:).');
if numel(imageSize) < 2 || any(~isfinite(imageSize(1:2))) || ...
        any(imageSize(1:2) ~= round(imageSize(1:2))) || ...
        ~isequal(imageSize(1:2), [450, 512])
    error('eyelashManualLashMask77:InvalidImageSize', ...
        '固定 77 人工标注要求二维尺寸 [450 512]。');
end
if ~isnumeric(lashRoi) || ~isequal(size(lashRoi), [1, 4]) || ...
        any(~isfinite(lashRoi)) || any(lashRoi ~= round(lashRoi)) || ...
        any(lashRoi ~= [102, 248, 177, 48])
    error('eyelashManualLashMask77:InvalidLashRoi', ...
        '固定 77 人工标注要求 lashRoi=[102 248 177 48]。');
end

% 坐标为 crop 内 1-based [x1 y1 x2 y2 radius]，由原图人工视觉核对后
% 固定。它们不由下游算法结果反推，也不在运行时根据任何诊断量调整。
localSegments = [ ...
    % 右侧主眼：上睫毛细线
     95, 28, 101, 25, 1; ...
     99, 30, 106, 26, 1; ...
    104, 31, 111, 27, 1; ...
    110, 31, 117, 27, 1; ...
    116, 31, 123, 27, 1; ...
    122, 30, 130, 25, 1; ...
    129, 29, 137, 23, 1; ...
    136, 27, 144, 21, 1; ...
    143, 25, 150, 18, 1; ...
    149, 22, 155, 14, 1; ...
    % 左下方被 ROI 截断的可见上睫毛细线
      1, 45,   8, 42, 1; ...
      5, 47,  14, 44, 1; ...
     12, 47,  20, 43, 1; ...
     19, 46,  27, 42, 1; ...
     26, 45,  34, 40, 1; ...
     33, 44,  40, 38, 1];

globalSegments = localSegments;
globalSegments(:, 1) = lashRoi(1) + localSegments(:, 1) - 1;
globalSegments(:, 3) = lashRoi(1) + localSegments(:, 3) - 1;
globalSegments(:, 2) = lashRoi(2) + localSegments(:, 2) - 1;
globalSegments(:, 4) = lashRoi(2) + localSegments(:, 4) - 1;

manualLashMask = false(imageSize(1), imageSize(2));
for index = 1:size(globalSegments, 1)
    manualLashMask = drawFixedSegment(manualLashMask, ...
        globalSegments(index, :));
end

roiMask = false(imageSize(1), imageSize(2));
x1 = lashRoi(1);
y1 = lashRoi(2);
x2 = x1 + lashRoi(3) - 1;
y2 = y1 + lashRoi(4) - 1;
roiMask(y1:y2, x1:x2) = true;
manualLashMask = manualLashMask & roiMask;

metadata = struct( ...
    'annotationId', '77-manual-lash-v1', ...
    'sourceImage', '77.png', ...
    'sourceImageSize', [450, 512, 3], ...
    'lashRoi', double(lashRoi), ...
    'coordinateSystem', 'global 1-based MATLAB [x y]', ...
    'localSegments', localSegments, ...
    'globalSegments', globalSegments, ...
    'lineRadiusPixels', 1, ...
    'annotationBasis', '77 原图视觉真值；只标可直接辨认的真实上睫毛细线', ...
    'excludedByRule', '眼线、双眼皮褶皱、眼球、眉毛、普通皮肤和不确定像素', ...
    'diagnosticsIndependent', true, ...
    'fixedAfterAnnotation', true, ...
    'manualPixelCount', nnz(manualLashMask));
end

function mask = drawFixedSegment(mask, segment)
imageHeight = size(mask, 1);
imageWidth = size(mask, 2);
x1 = segment(1);
y1 = segment(2);
x2 = segment(3);
y2 = segment(4);
radius = segment(5);
steps = max(abs(x2 - x1), abs(y2 - y1)) + 1;
xs = round(linspace(x1, x2, steps));
ys = round(linspace(y1, y2, steps));
for point = 1:numel(xs)
    xRange = max(1, xs(point) - radius):min(imageWidth, xs(point) + radius);
    yRange = max(1, ys(point) - radius):min(imageHeight, ys(point) + radius);
    mask(yRange, xRange) = true;
end
end
