function summary = runIssue08Validation()
%RUNISSUE08VALIDATION 验证低/中置信逐眼 soft support 及固定 77 回归。
%   该入口只使用固定 77 v3.2 MAT 作为基线输入；候选生产算法来自
%   当前工作树，输出和诊断全部写入系统临时目录。

projectRoot = fileparts(fileparts(mfilename('fullpath')));
addpath(fullfile(projectRoot, 'src'), '-begin');
addpath(fileparts(mfilename('fullpath')), '-begin');
outputFolder = fullfile(tempdir, 'image_beauty_issue08_validation_20260918');
if ~isfolder(outputFolder)
    mkdir(outputFolder);
end
inputPath = 'E:\image_beauty\人脸\人脸\77.png';
baselinePath = 'C:\Users\JJiio\AppData\Local\Temp\image_beauty_issue02_probe\77_v32_probe.mat';
loaded = load(baselinePath, 'context', 'diagnostics', 'output');
inputImage = imread(inputPath);
faceBox = [95 79 286 372];
params = struct('smoothingStrength', 100, 'whiteningStrength', 15);

% 固定基线重建核对，防止把候选结果与旧 v3.2 混淆。
baseDiagnostics = loaded.diagnostics;
frequency = baseDiagnostics.frequency;
frequency.sourceLuminance = rgb2ycbcr(im2double(inputImage));
frequency.sourceLuminance = frequency.sourceLuminance(:, :, 1);
frequency.imageSize = [size(inputImage, 1:2), 3];
frequency.faceBox = faceBox;
frequency.faceScale = min(faceBox(3:4));
frequency.reconstructedLuminance = double(frequency.base) + ...
    double(frequency.mid) + double(frequency.fine);
frequency.outputLuminance = frequency.reconstructedLuminance;
frequency.alphaMap = zeros(size(inputImage, 1:2));
processing = struct('baseLuminance', baseDiagnostics.baseLuminanceResult, ...
    'skinTone', baseDiagnostics.skinToneResult, ...
    'whitening', baseDiagnostics.whiteningResult);
[reconstructedBaseline, ~] = beauty.composeBeautyResult( ...
    inputImage, frequency, baseDiagnostics.repairResult, ...
    baseDiagnostics.beautyMasks, params.whiteningStrength, processing);
baselineReconstructionMaxRgbDifference = max(abs(double( ...
    reconstructedBaseline) - double(loaded.output)), [], 'all');
if baselineReconstructionMaxRgbDifference ~= 0
    error('runIssue08Validation:BaselineMismatch', ...
        '保存 v3.2 基线重建不一致：%.17g。', ...
        baselineReconstructionMaxRgbDifference);
end

% 固定 77 候选生产链。固定 MAT 内的旧 runtimeCache 和派生 Mask
% 不能作为候选输入，否则会把 v3.2 眼部保护缓存误当成当前候选结果；
% 候选验证明确只保留语义与基础皮肤字段，让当前生产链重建 Mask。
uncachedContext = stripDerivedContext(loaded.context);
[output, diagnostics] = beautifyImage( ...
    inputImage, params, faceBox, uncachedContext);
[directOutput, directDiagnostics] = beautifyImage( ...
    inputImage, params, faceBox, uncachedContext);
recomputeMaxRgbDifference = max(abs(double(output) - double(directOutput)), [], 'all');
if recomputeMaxRgbDifference ~= 0
    error('runIssue08Validation:RecomputeMismatch', ...
        '两次无缓存候选计算不一致：%.17g。', recomputeMaxRgbDifference);
end

texture = diagnostics.mask.texture;
roi = makeRoiMask([165 205 150 100], size(inputImage, 1:2));
baseRoi = baseDiagnostics.mask.texture;
summary = struct();
summary.baselineReconstructionMaxRgbDifference = baselineReconstructionMaxRgbDifference;
summary.recomputeMaxRgbDifference = recomputeMaxRgbDifference;
summary.output = output;
summary.directOutput = directOutput;
summary.diagnostics = diagnostics;
summary.directDiagnostics = directDiagnostics;
summary.browEye = struct( ...
    'leftEyeEvidenceMax', maxEvidence(loaded.context, 'leftEye', roi), ...
    'rightEyeEvidenceMax', maxEvidence(loaded.context, 'rightEye', roi), ...
    'leftBrowEvidenceMax', maxEvidence(loaded.context, 'leftBrow', roi), ...
    'rightBrowEvidenceMax', maxEvidence(loaded.context, 'rightBrow', roi), ...
    'baselineEyeDetailProtectionMean', mean(baseRoi.eyeDetailProtection(roi)), ...
    'candidateEyeDetailProtectionMean', mean(texture.eyeDetailProtection(roi)), ...
    'baselineEyeDetailProtectionMax', max(baseRoi.eyeDetailProtection(roi)), ...
    'candidateEyeDetailProtectionMax', max(texture.eyeDetailProtection(roi)), ...
    'baselineLashCorePixels', nnz(baseRoi.lashCore(roi)), ...
    'candidateLashCorePixels', nnz(texture.lashCore(roi)), ...
    'candidatePeriocularProtectionMean', mean(texture.periocularProtection(roi)), ...
    'candidateLashProtectionMean', mean(texture.lashProtection(roi)), ...
    'baselineRepairRgbDifferenceFromNoRepairMean', meanRepairDifference( ...
        inputImage, frequency, baseDiagnostics, loaded.output, roi, params), ...
    'candidateRepairRgbDifferenceFromNoRepairMean', meanRepairDifference( ...
        inputImage, frequency, diagnostics, output, roi, params));

summary.fullOutputDifferenceFromBaseline = max(abs(double(output) - ...
    double(loaded.output)), [], 3);
summary.hardMaskChangedPixels = nnz( ...
    diagnostics.beautyMasks.hardProtectionMask ~= ...
    baseDiagnostics.beautyMasks.hardProtectionMask);
hard3 = repmat(diagnostics.beautyMasks.hardProtectionMask >= .999, ...
    1, 1, 3);
summary.candidateHardProtectionMaxRgbChange = max(abs(double( ...
    output(hard3)) - double(inputImage(hard3))), [], 'all');
summary.roiDefinitions = struct('browEye', [165 205 150 100], ...
    'hair', [80 90 90 70], 'background', [465 20 40 140], ...
    'noseBridge', [160 295 90 50], 'noseWing', [155 325 80 45]);
writeIssue08Artifacts(outputFolder, inputImage, loaded.output, output, ...
    summary.fullOutputDifferenceFromBaseline, summary.roiDefinitions, ...
    texture);
summary.outputFolder = outputFolder;
save(fullfile(outputFolder, 'issue08_validation.mat'), 'summary', '-v7.3');
fprintf('issue 08 验证产物：%s\n', outputFolder);
fprintf('77 基线重建最大 RGB 差：%.17g\n', ...
    baselineReconstructionMaxRgbDifference);
fprintf('两次无缓存候选计算最大 RGB 差：%.17g\n', ...
    recomputeMaxRgbDifference);
fprintf('browEye eyeDetailProtection max：%.17g -> %.17g\n', ...
    summary.browEye.baselineEyeDetailProtectionMax, ...
    summary.browEye.candidateEyeDetailProtectionMax);
fprintf('browEye lashCore pixels：%d -> %d\n', ...
    summary.browEye.baselineLashCorePixels, summary.browEye.candidateLashCorePixels);
fprintf('browEye Repair 相对无 Repair RGB 差均值：%.17g -> %.17g\n', ...
    summary.browEye.baselineRepairRgbDifferenceFromNoRepairMean, ...
    summary.browEye.candidateRepairRgbDifferenceFromNoRepairMean);
fprintf('hard mask changed pixels：%d；候选 hard 区域相对输入最大 RGB 差：%g\n', ...
    summary.hardMaskChangedPixels, summary.candidateHardProtectionMaxRgbChange);
end

function context = stripDerivedContext(context)
names = {'runtimeCache', 'textureProtectionMask', ...
    'structureProtectionMask', 'whiteningProtectionMask', ...
    'chromaProtectionMask', 'toneProtectionMask', 'strengthMap', ...
    'faceStrengthMap', 'nonFaceStrengthMap', 'protectionMasks'};
present = names(isfield(context, names));
if ~isempty(present)
    context = rmfield(context, present);
end
end

function value = maxEvidence(context, name, roi)
evidence = min(context.regions.(name), context.regionConfidence.(name));
value = max(evidence(roi));
end

function value = meanRepairDifference(inputImage, frequency, candidateDiagnostics, ...
        candidate, roi, params)
processing = struct( ...
    'baseLuminance', candidateDiagnostics.baseLuminanceResult, ...
    'skinTone', candidateDiagnostics.skinToneResult, ...
    'whitening', candidateDiagnostics.whiteningResult);
% 保留同一 smoothingResult，仅替换 Repair 频率为未修复的平滑频率，
% 这样差异只表示 Repair 消费，不把普通磨皮作用混入统计。
[noRepair, ~] = beauty.composeBeautyResult(inputImage, frequency, ...
    candidateDiagnostics.smoothingResult, candidateDiagnostics.beautyMasks, ...
    params.whiteningStrength, processing);
difference = max(abs(double(candidate) - double(noRepair)), [], 3);
value = mean(difference(roi));
end

function writeIssue08Artifacts(outputFolder, inputImage, baselineImage, ...
        candidateImage, difference, rois, candidate)
writePng(inputImage, fullfile(outputFolder, '77_original.png'));
writePng(baselineImage, fullfile(outputFolder, '77_v32_baseline.png'));
writePng(candidateImage, fullfile(outputFolder, '77_issue08_candidate.png'));
writePng(cropImage(inputImage, rois.browEye), ...
    fullfile(outputFolder, '77_browEye_original.png'));
writePng(cropImage(baselineImage, rois.browEye), ...
    fullfile(outputFolder, '77_browEye_v32_baseline.png'));
writePng(cropImage(candidateImage, rois.browEye), ...
    fullfile(outputFolder, '77_browEye_issue08_candidate.png'));
writePng(uint8(min(max(round(difference), 0), 255)), ...
    fullfile(outputFolder, '77_issue08_difference.png'));
writeMask(candidate.eyeDetailProtection, ...
    fullfile(outputFolder, '77_issue08_eyeDetailProtection.png'));
writeMask(candidate.eyeNeighborhood, ...
    fullfile(outputFolder, '77_issue08_eyeNeighborhood.png'));
writeMask(candidate.lashProtection, ...
    fullfile(outputFolder, '77_issue08_lashProtection.png'));
writeMask(candidate.doubleEyelidProtection, ...
    fullfile(outputFolder, '77_issue08_doubleEyelidProtection.png'));
writeMask(candidate.hardProtectionMask, ...
    fullfile(outputFolder, '77_issue08_hardProtection.png'));
writeComparisonFigure(inputImage, baselineImage, candidateImage, ...
    rois, outputFolder);
end

function writeComparisonFigure(inputImage, baselineImage, candidateImage, ...
        rois, outputFolder)
figureHandle = figure('Visible', 'off', 'Color', 'white', ...
    'Position', [100, 100, 2200, 1000]);
tiledlayout(2, 4, 'Padding', 'compact', 'TileSpacing', 'compact');
nexttile; imshow(inputImage); title('77 原图');
nexttile; imshow(baselineImage); title('v3.2 基线');
nexttile; imshow(candidateImage); title('issue 08 候选');
nexttile; imshow(cropImage(candidateImage, rois.browEye)); title('候选 browEye');
nexttile; imshow(cropImage(inputImage, rois.browEye)); title('原图 browEye');
nexttile; imshow(cropImage(baselineImage, rois.browEye)); title('基线 browEye');
nexttile; imshow(cropImage(candidateImage, rois.hair)); title('候选 hair');
nexttile; imshow(cropImage(candidateImage, rois.background)); title('候选 background');
exportgraphics(figureHandle, fullfile(outputFolder, ...
    '77_issue08_full_and_browEye_comparison.png'), 'Resolution', 140);
close(figureHandle);
end

function writePng(image, path)
if ~isa(image, 'uint8')
    image = uint8(min(max(round(double(image)), 0), 255));
end
imwrite(image, path);
end

function writeMask(mask, path)
writePng(uint8(min(max(round(255 * double(mask)), 0), 255)), path);
end

function image = cropImage(image, roi)
x1 = max(1, roi(1)); y1 = max(1, roi(2));
x2 = min(size(image, 2), roi(1) + roi(3) - 1);
y2 = min(size(image, 1), roi(2) + roi(4) - 1);
image = image(y1:y2, x1:x2, :);
end

function mask = makeRoiMask(roi, imageSize)
mask = false(imageSize);
x1 = max(1, roi(1)); y1 = max(1, roi(2));
x2 = min(imageSize(2), roi(1) + roi(3) - 1);
y2 = min(imageSize(1), roi(2) + roi(4) - 1);
mask(y1:y2, x1:x2) = true;
end
