function result = smokeGuiWorkflow(inputPath, outputPath)
%SMOKEGUIWORKFLOW 在 MATLAB 中回归 GUI 的打开、预览、重置和保存流程。
%   使用公开的按路径接口驱动现有按钮逻辑，避免文件对话框阻断批处理；
%   不改变 GUI 的交互入口，输出文件由调用方指定并可直接查看。
%
%   T10 起，本 smoke 同时承担 Preview / Save / Cache 等价验收：
%   1. 以与 faceDetectionApp.openImageFromPath 完全相同的生产入口
%      （detectSingleFace → prepareBeautyContext → resizeBeautyContext
%      四参数 authoritative 路径）在本地重建 preview 与 full-size
%      Context，验证两者的 V4 分层完整性：schemaVersion='4.0'、
%      semantic/processability/evidence/protection/diagnostics 分层齐
%      全、八个 stage protection 字段在图像尺寸上合法、迁移期 compat
%      alias 齐全，且剥离 runtimeCache 后经 normalizeBeautyContext 只
%      读 reader 校验通过并保持幂等。GUI 的 Context 属性为
%      Access=private，在不修改生产代码的前提下无法直接内省，因此
%      改用像素级等价断言（第 2/3 条）证明 GUI 实例消费的是同一
%      V4 authoritative policy 链路。
%   2. GUI 预览（打开后默认参数与调参后）的坐标区图像必须与本地
%      重建链路的 beautifyImage 输出 bit-exact；GUI 预览结果若偏离
%      本地验证过的 V4 链路，说明 GUI 侧 Context 或调用链存在缺陷。
%   3. 原尺寸保存的 PNG 像素必须与本地重建链路的全尺寸输出
%      bit-exact，并保持输入尺寸/比例/分辨率；full-size Context 的
%      runtimeCache 必须挂在原尺寸输入上——保存链路缓存按目标原图
%      全量重建，预览缓存不得直接充当保存缓存（预览缓存混入保存链
%      路时的安全重建等价性由 testBeautyContextV3 的
%      testFullSizeSaveChainCacheEquivalence 覆盖）。

projectRoot = fileparts(fileparts(mfilename('fullpath')));
addpath(fullfile(projectRoot, 'src'));
addpath(fullfile(projectRoot, 'gui'));
if nargin < 1 || isempty(inputPath) || ~isfile(inputPath)
    error('smokeGuiWorkflow:InvalidInput', ...
        '必须提供存在的真实人像输入文件。');
end
if nargin < 2 || isempty(outputPath)
    outputPath = fullfile(tempdir, 'image_beauty_gui_workflow.png');
end

inputImage = imread(inputPath);
inputInfo = imfinfo(inputPath);
validateRgbImage(inputImage);

% 复现 GUI 打开图像时的生产 Context 链路：缩放规则、检测入口与
% Context 构建与 openImageFromPath 逐条一致。
previewScale = min(1, 640 / max(size(inputImage, 1), size(inputImage, 2)));
if previewScale < 1
    expectedPreviewImage = imresize(inputImage, previewScale, 'bilinear');
else
    expectedPreviewImage = inputImage;
end
[expectedPreviewFaceBox, isSingleFace] = detectSingleFace( ...
    expectedPreviewImage);
if ~isSingleFace
    error('smokeGuiWorkflow:DetectionFailed', ...
        '输入图像必须能检测到单张人脸。');
end
previewContext = prepareBeautyContext(expectedPreviewImage, ...
    expectedPreviewFaceBox);
previewLayerValidation = validateV4LayeredContext(previewContext, ...
    expectedPreviewImage, expectedPreviewFaceBox);
fullFaceBox = scaleFaceBox(expectedPreviewFaceBox, ...
    1 / previewScale, size(inputImage));
fullContext = resizeBeautyContext(previewContext, size(inputImage), ...
    fullFaceBox, inputImage);
fullLayerValidation = validateV4LayeredContext(fullContext, ...
    inputImage, fullFaceBox);
saveCacheRebuiltFromSource = isfield(fullContext, 'runtimeCache') && ...
    isequal(fullContext.runtimeCache.inputImage, inputImage) && ...
    isequal(fullContext.runtimeCache.imageSize, size(inputImage)) && ...
    ~isequal(fullContext.runtimeCache, previewContext.runtimeCache);

app = faceDetectionApp();
cleanup = onCleanup(@() delete(app)); %#ok<NASGU>
app.openImageFile(inputPath);

sourceDisplayed = readAxesImage(app.SourceAxes, ...
    'smokeGuiWorkflow:MissingSourceImage');
previewDisplayed = readAxesImage(app.DetectedAxes, ...
    'smokeGuiWorkflow:MissingPreviewImage');
initialPreviewSize = size(previewDisplayed);
initialSourceMatch = isequal(sourceDisplayed, inputImage);
initialPreviewBitExact = isequal(previewDisplayed, ...
    beautifyImage(expectedPreviewImage, struct( ...
    'smoothingStrength', 25, 'whiteningStrength', 15), ...
    expectedPreviewFaceBox, previewContext));
initialControlsEnabled = strcmp(app.SaveImageButton.Enable, 'on') && ...
    strcmp(app.OneClickBeautyButton.Enable, 'on') && ...
    strcmp(app.ResetBeautyButton.Enable, 'on');

app.setBeautyParameters(50, 25);
parameterPreview = readAxesImage(app.DetectedAxes, ...
    'smokeGuiWorkflow:MissingParameterPreview');
metricsVisible = ~contains(app.EntropyLabel.Text, '--') && ...
    ~contains(app.StandardDeviationLabel.Text, '--') && ...
    ~contains(app.AverageGradientLabel.Text, '--') && ...
    ~contains(app.ElapsedTimeLabel.Text, '--');
parameterPreviewChanged = ~isequal(parameterPreview, previewDisplayed);
parameterPreviewBitExact = isequal(parameterPreview, ...
    beautifyImage(expectedPreviewImage, struct( ...
    'smoothingStrength', 50, 'whiteningStrength', 25), ...
    expectedPreviewFaceBox, previewContext));

app.applyOneClickBeauty();
oneClickPreview = readAxesImage(app.DetectedAxes, ...
    'smokeGuiWorkflow:MissingOneClickPreview');
oneClickParameters = [app.SmoothingSlider.Value, app.WhiteningSlider.Value];
oneClickValid = all(isfinite(oneClickParameters)) && ...
    all(oneClickParameters >= 0) && all(oneClickParameters <= 100) && ...
    ~isempty(oneClickPreview);

app.resetBeauty();
resetDisplayed = readAxesImage(app.DetectedAxes, ...
    'smokeGuiWorkflow:MissingResetImage');
resetExact = isequal(resetDisplayed, inputImage) && ...
    app.SmoothingSlider.Value == 0 && app.WhiteningSlider.Value == 0;

app.setBeautyParameters(25, 15);
app.saveImageFile(outputPath);
savedImage = imread(outputPath);
savedInfo = imfinfo(outputPath);
savedSize = size(savedImage);
sameSize = isequal(savedSize, size(inputImage));
sameChannels = ndims(savedImage) == 3 && size(savedImage, 3) == 3;
sameAspectRatio = savedSize(2) * size(inputImage, 1) == ...
    size(inputImage, 2) * savedSize(1);
sameResolution = hasSameResolution(inputInfo, savedInfo);
saveChainBitExact = isequal(savedImage, ...
    beautifyImage(inputImage, struct( ...
    'smoothingStrength', 25, 'whiteningStrength', 15), ...
    fullFaceBox, fullContext));

checks = { ...
    'initialSourceMatch', initialSourceMatch; ...
    'initialControlsEnabled', initialControlsEnabled; ...
    'initialPreviewBitExact', initialPreviewBitExact; ...
    'parameterPreviewChanged', parameterPreviewChanged; ...
    'parameterPreviewBitExact', parameterPreviewBitExact; ...
    'metricsVisible', metricsVisible; ...
    'oneClickValid', oneClickValid; ...
    'resetExact', resetExact; ...
    'previewLayerValid', previewLayerValidation.passed; ...
    'fullLayerValid', fullLayerValidation.passed; ...
    'saveCacheRebuiltFromSource', saveCacheRebuiltFromSource; ...
    'sameSize', sameSize; ...
    'sameChannels', sameChannels; ...
    'sameAspectRatio', sameAspectRatio; ...
    'sameResolution', sameResolution; ...
    'saveChainBitExact', saveChainBitExact};

result = struct( ...
    'passed', all([checks{:, 2}]), ...
    'failedChecks', strjoin(checks([checks{:, 2}] == false, 1), ', '), ...
    'initialPreviewSize', initialPreviewSize, ...
    'previewLayerValidation', previewLayerValidation, ...
    'fullLayerValidation', fullLayerValidation, ...
    'saveCacheRebuiltFromSource', saveCacheRebuiltFromSource, ...
    'initialPreviewBitExact', initialPreviewBitExact, ...
    'parameterPreviewChanged', parameterPreviewChanged, ...
    'parameterPreviewBitExact', parameterPreviewBitExact, ...
    'metricsVisible', metricsVisible, ...
    'oneClickParameters', oneClickParameters, ...
    'resetExact', resetExact, ...
    'savedSize', savedSize, ...
    'sameAspectRatio', sameAspectRatio, ...
    'sameResolution', sameResolution, ...
    'saveChainBitExact', saveChainBitExact, ...
    'outputPath', outputPath);
if ~result.passed
    error('smokeGuiWorkflow:VerificationFailed', ...
        'GUI 流程、V4 分层或原尺寸保存校验失败：%s。%s', ...
        result.failedChecks, validationDetail( ...
        previewLayerValidation, fullLayerValidation));
end
end

function imageData = readAxesImage(axesHandle, identifier)
imageHandle = findobj(axesHandle, 'Type', 'image');
if isempty(imageHandle) || ~isvalid(imageHandle(1))
    error(identifier, '指定坐标区没有可读的图像结果。');
end
imageData = imageHandle(1).CData;
end

function same = hasSameResolution(inputInfo, outputInfo)
same = true;
if ~isstruct(inputInfo) || ~isscalar(inputInfo) || ...
        ~all(isfield(inputInfo, {'XResolution', 'YResolution'}))
    return;
end
if ~isstruct(outputInfo) || ~isscalar(outputInfo) || ...
        ~all(isfield(outputInfo, {'XResolution', 'YResolution'}))
    same = false;
    return;
end
[inputResolution, inputValid] = resolutionInMeters(inputInfo);
[outputResolution, outputValid] = resolutionInMeters(outputInfo);
same = inputValid && outputValid && ...
    all(abs(outputResolution - inputResolution) <= ...
    max(1, abs(inputResolution) * 1e-6));
end

function [resolution, valid] = resolutionInMeters(info)
resolution = double([info.XResolution, info.YResolution]);
valid = all(isfinite(resolution)) && all(resolution > 0);
if ~valid || ~isfield(info, 'ResolutionUnit')
    return;
end
unit = info.ResolutionUnit;
if isstring(unit) && isscalar(unit)
    unit = char(unit);
end
if ~ischar(unit) || size(unit, 1) ~= 1
    valid = false;
    return;
end
switch lower(strtrim(unit))
    case 'meter'
    case 'inch'
        resolution = resolution * 39.3700787401575;
    case 'centimeter'
        resolution = resolution * 100;
end
end

function validateRgbImage(image)
if ~isa(image, 'uint8') || ~isreal(image) || ndims(image) ~= 3 || ...
        size(image, 3) ~= 3
    error('smokeGuiWorkflow:InvalidImage', ...
        '输入图像必须是 uint8 三通道 RGB 图像。');
end
end

function validation = validateV4LayeredContext(context, image, faceBox)
%VALIDATEV4LAYEREDCONTEXT T10 验收口径：生产链 Context 必须是完整 V4
%   分层形态——schemaVersion='4.0'、semantic/processability/evidence/
%   protection/diagnostics 分层存在、八个 stage 字段在图像尺寸上合法
%   （protection.hard 严格二值）、迁移期 compat alias 齐全（缓存指纹
%   依赖），且剥离 runtimeCache 后通过只读 V4 reader 并保持幂等。
imageSize = size(image, [1, 2]);
validation = struct( ...
    'schemaVersion', '', ...
    'layersPresent', false, ...
    'stageFieldsValid', false, ...
    'compatAliasesPresent', false, ...
    'readerPassed', false, ...
    'readerError', '', ...
    'passed', false);
try
    validation.schemaVersion = char(string(context.schemaVersion));
catch
end
layerNames = {'semantic', 'processability', 'evidence', 'protection', ...
    'diagnostics'};
validation.layersPresent = isstruct(context) && isscalar(context) && ...
    all(isfield(context, layerNames));
if validation.layersPresent
    validation.stageFieldsValid = stageFieldsValid( ...
        context.protection, imageSize);
end
aliasNames = {'skinMask', 'faceSkinMask', 'nonFaceSkinMask', ...
    'textureProtectionMask', 'structureProtectionMask', ...
    'whiteningProtectionMask', 'chromaProtectionMask', ...
    'toneProtectionMask', 'strengthMap', 'faceStrengthMap', ...
    'nonFaceStrengthMap', 'protectionMasks', 'regions', ...
    'regionConfidence', 'semanticProbabilities', 'semanticConfidence'};
validation.compatAliasesPresent = isstruct(context) && ...
    isscalar(context) && all(isfield(context, aliasNames));
try
    if isfield(context, 'runtimeCache')
        contextWithoutCache = rmfield(context, 'runtimeCache');
    else
        contextWithoutCache = context;
    end
    normalized = normalizeBeautyContext(image, faceBox, ...
        contextWithoutCache);
    validation.readerPassed = strcmp(normalized.schemaVersion, '4.0') && ...
        isequal(normalized, contextWithoutCache);
catch exception
    validation.readerError = exception.identifier;
end
validation.passed = strcmp(validation.schemaVersion, '4.0') && ...
    validation.layersPresent && validation.stageFieldsValid && ...
    validation.compatAliasesPresent && validation.readerPassed;
end

function valid = stageFieldsValid(protection, imageSize)
stageNames = {'smoothingFine', 'smoothingMid', 'repairFine', ...
    'repairMid', 'baseLuminance', 'tone', 'whitening', 'hard'};
if ~isstruct(protection) || ~isscalar(protection) || ...
        ~all(isfield(protection, stageNames))
    valid = false;
    return;
end
valid = true;
for index = 1:numel(stageNames)
    value = protection.(stageNames{index});
    valid = valid && isnumeric(value) && ~islogical(value) && ...
        isequal(size(value), imageSize) && all(isfinite(value(:))) && ...
        all(value(:) >= 0) && all(value(:) <= 1);
end
valid = valid && all(protection.hard(:) == 0 | protection.hard(:) == 1);
end

function detail = validationDetail(previewValidation, fullValidation)
detail = sprintf( ...
    'previewContext[schema=%s layers=%d stage=%d alias=%d reader=%d err=%s] fullSizeContext[schema=%s layers=%d stage=%d alias=%d reader=%d err=%s]', ...
    previewValidation.schemaVersion, previewValidation.layersPresent, ...
    previewValidation.stageFieldsValid, ...
    previewValidation.compatAliasesPresent, ...
    previewValidation.readerPassed, previewValidation.readerError, ...
    fullValidation.schemaVersion, fullValidation.layersPresent, ...
    fullValidation.stageFieldsValid, ...
    fullValidation.compatAliasesPresent, ...
    fullValidation.readerPassed, fullValidation.readerError);
end

function box = scaleFaceBox(box, scale, imageSize)
%SCALEFACEBOX 复现 GUI 私有方法的人脸框缩放规则（与
%   testMaskSystemV4CompatibilityBaseline 的同名列保持一致）。
box = round(double(box) * scale);
box(1) = max(1, min(box(1), imageSize(2)));
box(2) = max(1, min(box(2), imageSize(1)));
x2 = min(imageSize(2), box(1) + box(3) - 1);
y2 = min(imageSize(1), box(2) + box(4) - 1);
box(3:4) = max(1, [x2 - box(1) + 1, y2 - box(2) + 1]);
end
