function tests = testBeautyV3
%TESTBEAUTYV3 v3 Mask package 和频率 tracer 测试。
tests = functiontests(localfunctions);
end

function setupOnce(~)
projectRoot = fileparts(fileparts(mfilename('fullpath')));
addpath(fullfile(projectRoot, 'src'));
end

function testPackagesResolveWithSourcePathOnly(testCase)
verifyNotEmpty(testCase, which('masks.buildBeautyMasks'));
verifyNotEmpty(testCase, which('masks.buildTextureProtectionMask'));
verifyNotEmpty(testCase, which('beauty.decomposeSkinFrequency'));
verifyNotEmpty(testCase, which('beauty.smoothSkinTexture'));
verifyNotEmpty(testCase, which('beauty.evenSkinLuminance'));
verifyNotEmpty(testCase, which('beauty.composeBeautyResult'));
end

function testBeautyMasksReturnPurposeSpecificContinuousMaps(testCase)
[image, faceBox, parsing] = fixtureImage(120, 160);
context = prepareBeautyContext(image, faceBox, parsing, ...
    emptyBodyParsing([120, 160]));

[beautyMasks, diagnostics] = masks.buildBeautyMasks( ...
    image, context, faceBox);
requiredFields = {'textureProtectionMask', 'structureProtectionMask', ...
    'chromaProtectionMask', 'toneProtectionMask', 'strengthMap', ...
    'faceStrengthMap', ...
    'nonFaceStrengthMap', 'hardProtectionMask'};
verifyTrue(testCase, all(isfield(beautyMasks, requiredFields)));
for index = 1:numel(requiredFields)
    verifySize(testCase, beautyMasks.(requiredFields{index}), [120, 160]);
end
verifyTrue(testCase, isfield(diagnostics, 'structure'));
verifyTrue(testCase, isfield(diagnostics.structure, 'orientationCoherence'));
verifyEqual(testCase, beautyMasks.chromaProtectionMask, ...
    beautyMasks.toneProtectionMask, 'AbsTol', 0);
verifyGreaterThan(testCase, ...
    mean(beautyMasks.textureProtectionMask(parsing.regions.leftEye > .5)), .5);
verifyGreaterThan(testCase, ...
    mean(beautyMasks.toneProtectionMask(parsing.regions.upperLip > .5)), .5);
verifyGreaterThan(testCase, ...
    mean(beautyMasks.structureProtectionMask(parsing.regions.nose > .5)), 0);
verifyGreaterThan(testCase, ...
    mean(beautyMasks.structureProtectionMask(parsing.regions.neck > .5)), 0);
verifyEqual(testCase, max(beautyMasks.strengthMap( ...
    context.skinMask <= .01)), 0, 'AbsTol', 1e-12);
verifyGreaterThan(testCase, ...
    mean(beautyMasks.faceStrengthMap(parsing.regions.skin > .5)), ...
    mean(beautyMasks.nonFaceStrengthMap(parsing.regions.neck > .5)));

[texture, structure, tone, strength] = masks.buildBeautyMasks( ...
    image, context, faceBox);
verifyEqual(testCase, texture, beautyMasks.textureProtectionMask, ...
    'AbsTol', 1e-12);
verifyEqual(testCase, structure, beautyMasks.structureProtectionMask, ...
    'AbsTol', 1e-12);
verifyEqual(testCase, tone, beautyMasks.toneProtectionMask, ...
    'AbsTol', 1e-12);
verifyEqual(testCase, strength, beautyMasks.strengthMap, ...
    'AbsTol', 1e-12);
end

function testFrequencyDecompositionReconstructsAndKeepsScalesFixed(testCase)
[image, faceBox, parsing] = fixtureImage(96, 128);
context = normalizeBeautyContext(image, faceBox, ...
    prepareBeautyContext(image, faceBox, parsing, ...
    emptyBodyParsing([96, 128])));
[beautyMasks, ~] = masks.buildBeautyMasks(image, context, faceBox);
[frequency, decomposition] = beauty.decomposeSkinFrequency(image, faceBox);
verifyLessThanOrEqual(testCase, decomposition.reconstructionError, 1e-12);
verifyEqual(testCase, frequency.base + frequency.mid + frequency.fine, ...
    frequency.sourceLuminance, 'AbsTol', 1e-12);

strengths = [0, 25, 50, 75, 100];
retentions = zeros(size(strengths));
fineEnergies = zeros(size(strengths));
midRetentions = zeros(size(strengths));
midEnergies = zeros(size(strengths));
for index = 1:numel(strengths)
    [smoothed, details] = beauty.smoothSkinTexture( ...
        frequency, beautyMasks, strengths(index));
    retentions(index) = mean(details.fineActualRetentionMap(:));
    fineEnergies(index) = details.fineEnergyAfter;
    midRetentions(index) = mean(details.midActualRetentionMap(:));
    midEnergies(index) = details.midEnergyAfter;
    verifyEqual(testCase, details.fineActualRetentionMap, ...
        1 - details.alphaMap .* (1 - details.fineRetention), ...
        'AbsTol', 1e-12);
    verifyEqual(testCase, details.midActualRetentionMap, ...
        1 - details.midAlphaMap .* (1 - details.midRetention), ...
        'AbsTol', 1e-12);
    verifyEqual(testCase, smoothed.base, frequency.base, ...
        'AbsTol', 1e-12);
    if strengths(index) == 0
        verifyEqual(testCase, smoothed.mid, frequency.mid, ...
            'AbsTol', 1e-12);
    else
        verifyGreaterThan(testCase, ...
            nnz(abs(smoothed.mid(:) - frequency.mid(:)) > 1e-12), 0);
    end
end
verifyEqual(testCase, retentions(1), 1, 'AbsTol', 1e-12);
verifyTrue(testCase, all(diff(retentions) <= 0));
verifyTrue(testCase, all(diff(fineEnergies) <= 1e-12));
verifyEqual(testCase, midRetentions(1), 1, 'AbsTol', 1e-12);
verifyTrue(testCase, all(diff(midRetentions) <= 0));
verifyTrue(testCase, all(diff(midEnergies) <= 1e-12));
verifyGreaterThan(testCase, retentions(end), .55);
verifyGreaterThan(testCase, midRetentions(end), .50);
end

function testV3PipelineUsesOneAlphaAndPreservesProtectedPixels(testCase)
[image, faceBox, parsing] = fixtureImage(120, 160);
context = prepareBeautyContext(image, faceBox, parsing, ...
    emptyBodyParsing([120, 160]));
params = struct('smoothingStrength', 100, ...
    'whiteningStrength', 50);
[output, diagnostics] = beautifyImage(image, params, faceBox, context);
verifyClass(testCase, output, 'uint8');
verifySize(testCase, output, size(image));
verifyEqual(testCase, output(repmat(diagnostics.beautyMasks.hardProtectionMask >= .999, ...
    [1, 1, 3])), image(repmat(diagnostics.beautyMasks.hardProtectionMask >= .999, ...
    [1, 1, 3])));
verifyEqual(testCase, output(repmat(context.skinMask <= .01, ...
    [1, 1, 3])), image(repmat(context.skinMask <= .01, ...
    [1, 1, 3])));

[frequency, ~] = beauty.decomposeSkinFrequency(image, faceBox);
[beautyMasks, ~] = masks.buildBeautyMasks(image, context, faceBox);
[smoothed, ~] = beauty.smoothSkinTexture(frequency, beautyMasks, 100);
[~, diagnostics] = beauty.composeBeautyResult( ...
    image, frequency, smoothed, beautyMasks, 50);
verifyEqual(testCase, diagnostics.alphaMap, ...
    max(smoothed.alphaMap, diagnostics.whiteningSupport), ...
    'AbsTol', 1e-12);
end

function testStageProtectionGatesReproduceProductionGating(testCase)
%TESTSTAGEPROTECTIONGATESREPRODUCEPRODUCTIONGATING T07：八个 stage
%   protection 字段满足唯一语义与 [0,1]；hard 可严格离散化（二值）且
%   nostrilCore/lashCore 的 hard identity 原样保留；用 stage protection
%   重算各生产 stage 的兼容门控，与生产诊断逐像素等价（容差仅为
%   1-x 补码往返与乘法结合顺序的浮点噪声，不放宽行为）。
[image, faceBox, parsing] = fixtureImage(120, 160);
context = prepareBeautyContext(image, faceBox, parsing, ...
    emptyBodyParsing([120, 160]));
[beautyMasks, maskDiagnostics] = masks.buildBeautyMasks( ...
    image, context, faceBox);
protection = masks.buildStageProtectionMasks(beautyMasks);

stageNames = {'smoothingFine'; 'smoothingMid'; 'repairFine'; ...
    'repairMid'; 'baseLuminance'; 'tone'; 'whitening'; 'hard'};
verifyEqual(testCase, fieldnames(protection), stageNames);
for index = 1:numel(stageNames)
    value = protection.(stageNames{index});
    verifyTrue(testCase, isnumeric(value) && ~islogical(value) && ...
        isreal(value));
    verifySize(testCase, value, [120, 160]);
    verifyTrue(testCase, all(isfinite(value(:))));
    verifyGreaterThanOrEqual(testCase, min(value(:)), 0);
    verifyLessThanOrEqual(testCase, max(value(:)), 1);
end

% hard：二值 identity，与生产 hardProtectionMask bit-exact；
% nostrilCore/lashCore/lipCore 全部保留在 hard 内。
verifyEqual(testCase, protection.hard, ...
    beautyMasks.hardProtectionMask, 'AbsTol', 0);
verifyEqual(testCase, protection.hard, ...
    double(maskDiagnostics.texture.hardProtectionMask), 'AbsTol', 0);
verifyTrue(testCase, all(protection.hard(:) == 0 | ...
    protection.hard(:) == 1));
identityCore = maskDiagnostics.texture.lipCore | ...
    maskDiagnostics.texture.nostrilCore | ...
    maskDiagnostics.texture.lashCore;
verifyTrue(testCase, nnz(identityCore) > 0);
verifyTrue(testCase, all(protection.hard(identityCore) == 1), ...
    'nostrilCore/lashCore 的 hard identity 必须原样保留。');

% Fine/Mid smoothing：alphaMap 与 midAlphaMap 用 stage fields 重算。
[frequency, ~] = beauty.decomposeSkinFrequency(image, faceBox);
strengths = [0, 25, 50, 75, 100];
for index = 1:numel(strengths)
    strength = strengths(index);
    [smoothed, details] = beauty.smoothSkinTexture(frequency, ...
        beautyMasks, strength);
    profile = beautySmoothingProfile(strength);
    effectStrength = profile.alphaCurve .* beautyMasks.strengthMap;
    nonFacePixels = beautyMasks.nonFaceStrengthMap > .01;
    effectStrength(nonFacePixels) = profile.outsideFaceStrength .* ...
        beautyMasks.nonFaceStrengthMap(nonFacePixels);
    fineGate = 1 - max(protection.smoothingFine, protection.hard);
    verifyEqual(testCase, details.alphaMap, effectStrength .* fineGate, ...
        'AbsTol', 1e-12);

    midGate = 1 - protection.smoothingMid;
    midRecomputed = details.alphaMap .* midGate;
    nosePixels = beautyMasks.noseMask > 0;
    if profile.alphaCurve == 1
        % 满档（alphaCurve=1）：mid 门控整体与生产逐像素等价。
        verifyEqual(testCase, details.midAlphaMap, midRecomputed, ...
            'AbsTol', 1e-12);
    else
        % 静态结构部分全场等价；nose 项生产值为快照与 1 的凸组合
        % （快照即最强保护），逐像素核对凸组合差值。
        verifyEqual(testCase, details.midAlphaMap(~nosePixels), ...
            midRecomputed(~nosePixels), 'AbsTol', 1e-12);
        midGap = details.midAlphaMap(nosePixels) - ...
            midRecomputed(nosePixels);
        expectedGap = details.alphaMap(nosePixels) .* ...
            details.fineStructureGate(nosePixels) .* ...
            (.50 * (1 - profile.alphaCurve));
        verifyGreaterThanOrEqual(testCase, min(midGap), 0);
        verifyEqual(testCase, midGap, expectedGap, 'AbsTol', 1e-9);
    end
end

% Repair：零瑕疵参考点的生产 structureGate（blemish=0）与
% textureGate/noseMidGate 的组合必须 bit-exact 重建两个 stage 字段。
blemishMap = zeros(size(image, 1), size(image, 2));
[~, repairDetails] = beauty.repairSkinBlemishes(smoothed, beautyMasks, ...
    blemishMap, 50);
verifyEqual(testCase, protection.repairFine, ...
    1 - repairDetails.structureGate .* ...
    (1 - beautyMasks.textureProtectionMask), 'AbsTol', 0);
verifyEqual(testCase, protection.repairMid, ...
    1 - repairDetails.structureGate .* repairDetails.noseMidGate .* ...
    (1 - beautyMasks.textureProtectionMask), 'AbsTol', 0);

% Base luminance：supportMap 完整重算（该 stage 无 runtime 耦合）。
[~, baseDetails] = beauty.evenSkinLuminance(frequency, beautyMasks, 50);
baseSupport = baseDetails.baseWeightCurve .* ...
    baseDetails.regionalSkinWeight .* (1 - protection.hard) .* ...
    (1 - protection.baseLuminance) .* baseDetails.referenceCoverage;
verifyEqual(testCase, baseDetails.supportMap, baseSupport, 'AbsTol', 1e-12);

% Tone：主 weight 分支重算（s=25 时 uniform 分支未激活）。
[~, toneDetails] = beauty.normalizeSkinTone(image, frequency, ...
    beautyMasks, blemishMap, 25);
profile25 = beautySmoothingProfile(25);
toneCurveMap = profile25.toneStrength + ((25 / 100) ^ .85 - ...
    profile25.toneStrength) .* smoothStep( ...
    toneDetails.chromaEvidence, .25, .65);
toneCurveMap = max(toneCurveMap, ...
    (25 / 100) ^ .85 .* toneDetails.localChromaEvidence);
toneAllowed = min(beautyMasks.skinMask, beautyMasks.strengthMap) .* ...
    (1 - protection.hard);
evidenceTerm = .08 + .35 * toneDetails.chromaEvidence + ...
    .35 * toneDetails.localChromaEvidence + ...
    .20 * toneDetails.blemishEvidence;
toneWeight = min(max(toneCurveMap .* toneAllowed .* ...
    (1 - protection.tone) .* evidenceTerm, 0), .55);
verifyEqual(testCase, toneDetails.weightMap, toneWeight, 'AbsTol', 1e-12);

% Whitening：supportMap 完整重算（该 stage 无 runtime 耦合）。
[~, whiteningDetails] = beauty.applySkinWhitening(image, frequency, ...
    beautyMasks, 50);
whiteningAllowed = min(beautyMasks.skinMask, beautyMasks.strengthMap) .* ...
    (1 - protection.hard);
faceSkin = beautyMasks.faceSkinMask >= .5;
whiteningAllowed(faceSkin) = max(whiteningAllowed(faceSkin), .85);
whiteningSupport = min(max((50 / 100) ^ .85 .* whiteningAllowed .* ...
    whiteningDetails.highlightProtection .* ...
    (1 - protection.whitening), 0), 1);
verifyEqual(testCase, whiteningDetails.supportMap, whiteningSupport, ...
    'AbsTol', 1e-12);
end

function testFineSmoothingConsumesStageProtectionContract(testCase)
%TESTFINESMOOTHINGCONSUMESSTAGEPROTECTIONCONTRACT T12：提供 stage
%   contract（protection 分层）时，Fine smoothing 只从
%   protection.smoothingFine / protection.hard 派生 Fine 门控，不再自行
%   解释 general texture/structure masks：扰动 textureProtectionMask 不
%   改变 stage 路径的任何输出，而 legacy 路径会随之变化。统计路径
%   （processableSkin → fineEnergy/blemishMean/fineRetention）改读生产
%   端合并 protectionMask，与旧 max(texture,structure,hard) bit-exact
%   同值；strength、频段分解与合成公式不变（Mid 门控自 T13 起迁移至
%   stage contract，见 testMidSmoothingConsumesStageProtectionContract）。
%   Fine alpha 与输出增量相对 legacy 仅有 1-x 补码与乘法结合顺序的
%   浮点噪声（≤1e-15，T07 推导基线 1.11e-16 同量级）。
[image, faceBox, parsing] = fixtureImage(120, 160);
context = prepareBeautyContext(image, faceBox, parsing, ...
    emptyBodyParsing([120, 160]));
[beautyMasks, ~] = masks.buildBeautyMasks(image, context, faceBox);
protection = masks.buildStageProtectionMasks(beautyMasks);
[frequency, ~] = beauty.decomposeSkinFrequency(image, faceBox);
[blemishMap, ~] = beauty.buildBlemishMap(image, frequency, beautyMasks);

% 统计路径数据源：合并 protectionMask 与 max(texture, structure, hard)
% 必须逐像素 bit-exact，保证可处理皮肤统计口径不变。
combinedProtection = max(cat(3, beautyMasks.textureProtectionMask, ...
    beautyMasks.structureProtectionMask, ...
    beautyMasks.hardProtectionMask), [], 3);
verifyEqual(testCase, beautyMasks.protectionMask, combinedProtection, ...
    'AbsTol', 0);

strengths = [0, 25, 50, 75, 100];
for index = 1:numel(strengths)
    strength = strengths(index);
    [smoothedLegacy, legacyDetails] = beauty.smoothSkinTexture( ...
        frequency, beautyMasks, strength, blemishMap);
    [smoothedStage, stageDetails] = beauty.smoothSkinTexture( ...
        frequency, beautyMasks, strength, blemishMap, protection);

    % stage 路径 Fine alpha 恰为 stage contract 重算（统一语义
    % gate = 1 - max(field, hard)），bit-exact；hard identity 保持。
    profile = beautySmoothingProfile(strength);
    effectStrength = profile.alphaCurve .* beautyMasks.strengthMap;
    nonFacePixels = beautyMasks.nonFaceStrengthMap > .01;
    effectStrength(nonFacePixels) = profile.outsideFaceStrength .* ...
        beautyMasks.nonFaceStrengthMap(nonFacePixels);
    verifyEqual(testCase, stageDetails.alphaMap, ...
        effectStrength .* (1 - max(protection.smoothingFine, ...
        protection.hard)), 'AbsTol', 0);
    verifyEqual(testCase, ...
        nnz(stageDetails.alphaMap(protection.hard >= .999)), 0);

    % 与 legacy 路径的等价性：alpha 与 Fine/Mid 输出增量仅浮点噪声；
    % 统计标量与合并保护图 bit-exact 不变；结构锚点同值（T13 起 Mid
    % 门控契约见 testMidSmoothingConsumesStageProtectionContract）。
    verifyLessThanOrEqual(testCase, ...
        max(abs(stageDetails.alphaMap(:) - legacyDetails.alphaMap(:))), ...
        1e-15);
    verifyLessThanOrEqual(testCase, ...
        max(abs(smoothedStage.fine(:) - smoothedLegacy.fine(:))), 1e-15);
    verifyLessThanOrEqual(testCase, ...
        max(abs(smoothedStage.mid(:) - smoothedLegacy.mid(:))), 1e-15);
    verifyEqual(testCase, stageDetails.fineEnergy, ...
        legacyDetails.fineEnergy, 'AbsTol', 0);
    verifyEqual(testCase, stageDetails.blemishMean, ...
        legacyDetails.blemishMean, 'AbsTol', 0);
    verifyEqual(testCase, stageDetails.fineRetention, ...
        legacyDetails.fineRetention, 'AbsTol', 0);
    verifyEqual(testCase, stageDetails.protectionMask, ...
        legacyDetails.protectionMask, 'AbsTol', 0);
    verifyEqual(testCase, stageDetails.fineStructureGate, ...
        legacyDetails.fineStructureGate, 'AbsTol', 0);
    verifyEqual(testCase, stageDetails.midStructureGate, ...
        legacyDetails.midStructureGate, 'AbsTol', 0);
    verifyLessThanOrEqual(testCase, ...
        max(abs(stageDetails.midAlphaMap(:) - ...
        legacyDetails.midAlphaMap(:))), 1e-15);
    % 合成公式与 base identity 不变。
    verifyEqual(testCase, smoothedStage.base, frequency.base, 'AbsTol', 0);
    verifyEqual(testCase, stageDetails.fineRetentionMap, ...
        1 - stageDetails.alphaMap .* (1 - stageDetails.fineRetention), ...
        'AbsTol', 0);
end

% 负向证明：stage 路径的输出对 textureProtectionMask 扰动完全不变
% （Fine 不再读取该字段），legacy 路径则会随之改变。
perturbedMasks = beautyMasks;
perturbedMasks.textureProtectionMask = ...
    min(1, beautyMasks.textureProtectionMask * .5 + .25);
[smoothedPerturbedLegacy, perturbedLegacyDetails] = ...
    beauty.smoothSkinTexture(frequency, perturbedMasks, 60, blemishMap);
[smoothedPerturbedStage, perturbedStageDetails] = ...
    beauty.smoothSkinTexture(frequency, perturbedMasks, 60, blemishMap, ...
    protection);
[smoothedStage60, stageDetails60] = beauty.smoothSkinTexture( ...
    frequency, beautyMasks, 60, blemishMap, protection);
[~, unperturbedLegacyDetails60] = beauty.smoothSkinTexture( ...
    frequency, beautyMasks, 60, blemishMap);
verifyTrue(testCase, ...
    nnz(perturbedLegacyDetails.alphaMap ~= ...
    unperturbedLegacyDetails60.alphaMap) > 0, ...
    'texture 扰动必须确实影响 legacy 路径，否则本断言无意义。');
verifyEqual(testCase, perturbedStageDetails.alphaMap, ...
    stageDetails60.alphaMap, 'AbsTol', 0);
verifyEqual(testCase, smoothedPerturbedStage.fine, ...
    smoothedStage60.fine, 'AbsTol', 0);
verifyEqual(testCase, smoothedPerturbedStage.mid, ...
    smoothedStage60.mid, 'AbsTol', 0);
end

function testMidSmoothingConsumesStageProtectionContract(testCase)
%TESTMIDSMOOTHINGCONSUMESSTAGEPROTECTIONCONTRACT T13：提供 stage
%   contract 时，Mid smoothing 只从 protection.smoothingMid 派生 Mid
%   门控，不再读取 noseMask/局部 nose 特判。快照 smoothingMid 取
%   alphaCurve=1 满档（T07），生产 noseMidGate 的强度插值归属
%   effect-strength 侧：midGate = alphaCurve .* (1 - smoothingMid) +
%   (1 - alphaCurve) .* fineStructureGate。该凸组合代数上恒等于生产
%   门控 fineStructureGate .* (1 - .50*nose.*alphaCurve)（快照为最强
%   保护端点，强度无关结构锚点为零 nose 保护端点），与生产仅差乘法
%   结合顺序与 1-x 补码往返的浮点噪声（≤1e-15，T07 推导基线
%   1.11e-16 同量级）。诊断收口：stage 路径不再报告 noseMask/
%   noseMidGate，新增 midGate 快照；legacy 路径字段不变。
[image, faceBox, parsing] = fixtureImage(120, 160);
context = prepareBeautyContext(image, faceBox, parsing, ...
    emptyBodyParsing([120, 160]));
[beautyMasks, ~] = masks.buildBeautyMasks(image, context, faceBox);
protection = masks.buildStageProtectionMasks(beautyMasks);
[frequency, ~] = beauty.decomposeSkinFrequency(image, faceBox);
[blemishMap, ~] = beauty.buildBlemishMap(image, frequency, beautyMasks);
verifyTrue(testCase, nnz(beautyMasks.noseMask > 0) > 0, ...
    'fixture 必须包含非空 noseMask，否则 nose 特判退役断言无意义。');

strengths = [0, 25, 50, 75, 100];
for index = 1:numel(strengths)
    strength = strengths(index);
    [smoothedLegacy, legacyDetails] = beauty.smoothSkinTexture( ...
        frequency, beautyMasks, strength, blemishMap);
    [smoothedStage, stageDetails] = beauty.smoothSkinTexture( ...
        frequency, beautyMasks, strength, blemishMap, protection);
    profile = beautySmoothingProfile(strength);

    % Mid 门控恰为 stage contract 凸组合重算（bit-exact），且与生产
    % 组合式 midStructureGate .* noseMidGate 只差浮点噪声（≤1e-15）。
    expectedMidGate = profile.alphaCurve .* ...
        (1 - protection.smoothingMid) + ...
        (1 - profile.alphaCurve) .* stageDetails.fineStructureGate;
    verifyEqual(testCase, stageDetails.midGate, expectedMidGate, ...
        'AbsTol', 0);
    verifyEqual(testCase, stageDetails.midAlphaMap, ...
        stageDetails.alphaMap .* stageDetails.midGate, 'AbsTol', 0);
    verifyLessThanOrEqual(testCase, ...
        max(abs(stageDetails.midGate(:) - ...
        legacyDetails.midStructureGate(:) .* ...
        legacyDetails.noseMidGate(:))), 1e-15);
    verifyLessThanOrEqual(testCase, ...
        max(abs(stageDetails.midAlphaMap(:) - ...
        legacyDetails.midAlphaMap(:))), 1e-15);
    verifyLessThanOrEqual(testCase, ...
        max(abs(smoothedStage.mid(:) - smoothedLegacy.mid(:))), 1e-15);

    % 结构锚点与统计路径保持生产原值；base identity 与合成公式不变。
    verifyEqual(testCase, stageDetails.midStructureGate, ...
        legacyDetails.midStructureGate, 'AbsTol', 0);
    verifyEqual(testCase, stageDetails.fineEnergy, ...
        legacyDetails.fineEnergy, 'AbsTol', 0);
    verifyEqual(testCase, smoothedStage.base, frequency.base, ...
        'AbsTol', 0);
    verifyEqual(testCase, stageDetails.midRetentionMap, ...
        1 - stageDetails.midAlphaMap .* ...
        (1 - stageDetails.midRetention), 'AbsTol', 0);
end

% 满档端点（alphaCurve=1）：Mid 门控恰为 T07 已验证的快照重算
% midAlphaMap = alphaMap .* (1 - smoothingMid)（≤1e-15 噪声）。
[~, stageDetails100] = beauty.smoothSkinTexture(frequency, ...
    beautyMasks, 100, blemishMap, protection);
verifyLessThanOrEqual(testCase, ...
    max(abs(stageDetails100.midAlphaMap(:) - ...
    stageDetails100.alphaMap(:) .* (1 - protection.smoothingMid(:)))), ...
    1e-15);

% 零强度端点（alphaCurve=0）：凸组合退化为纯结构锚点，Mid 保留率恒 1。
[smoothedStage0, stageDetails0] = beauty.smoothSkinTexture(frequency, ...
    beautyMasks, 0, blemishMap, protection);
verifyEqual(testCase, stageDetails0.midGate, ...
    stageDetails0.fineStructureGate, 'AbsTol', 0);
verifyEqual(testCase, smoothedStage0.mid, frequency.mid, 'AbsTol', 0);

% 负向证明：stage 路径的 Mid 输出对 noseMask 扰动完全不变（Mid 不再
% 读取该字段），legacy 路径则会随之变化。
perturbedMasks = beautyMasks;
perturbedMasks.noseMask = min(1, beautyMasks.noseMask * .5 + .25);
[smoothedPerturbedStage, perturbedStageDetails] = ...
    beauty.smoothSkinTexture(frequency, perturbedMasks, 60, ...
    blemishMap, protection);
[smoothedStage60, stageDetails60] = beauty.smoothSkinTexture( ...
    frequency, beautyMasks, 60, blemishMap, protection);
[~, perturbedLegacyDetails] = beauty.smoothSkinTexture( ...
    frequency, perturbedMasks, 60, blemishMap);
[~, legacyDetails60] = beauty.smoothSkinTexture( ...
    frequency, beautyMasks, 60, blemishMap);
verifyTrue(testCase, ...
    nnz(perturbedLegacyDetails.midAlphaMap ~= ...
    legacyDetails60.midAlphaMap) > 0, ...
    'noseMask 扰动必须确实影响 legacy 路径，否则本断言无意义。');
verifyEqual(testCase, perturbedStageDetails.midAlphaMap, ...
    stageDetails60.midAlphaMap, 'AbsTol', 0);
verifyEqual(testCase, smoothedPerturbedStage.mid, ...
    smoothedStage60.mid, 'AbsTol', 0);

% 诊断收口：stage 路径不再报告 nose 特判字段，新增 midGate 快照；
% legacy 路径字段保持不变。
verifyEqual(testCase, ...
    isfield(stageDetails60, {'noseMask', 'noseMidGate'}), ...
    [false, false], ...
    'stage 路径不得再报告 nose 特判诊断字段。');
verifyTrue(testCase, isfield(stageDetails60, 'midGate'));
verifyTrue(testCase, isfield(legacyDetails60, 'noseMask') && ...
    isfield(legacyDetails60, 'noseMidGate'));
end

function testFineRepairConsumesStageProtectionContract(testCase)
%TESTFINEREPAIRCONSUMESSTAGEPROTECTIONCONTRACT T14：提供生产端拼装的
%   Fine repair stage contract 时，fineWeight 门控只按生产原式从
%   contract 重建（min(blemishRelaxedGate, strongStructureCap) 与截断
%   后的 textureGate），不再自行组合 general texture/structure/hard
%   masks：扰动 textureProtectionMask 不改变 stage 路径的 fineWeight，
%   legacy 路径则会随之变化。生产链在结构门与纹理门之间对权重做
%   [0,1] 截断，且快照 repairFine 的 1-x 补码往返有舍入，因此 texture
%   不折叠进门控积：快照 repairFine 作为零瑕疵参考门消费（诊断
%   fineGateZeroBlemish），runtime 放宽量由生产端在零瑕疵参考门上重
%   建后随 contract 传入未折叠字段，消费侧与 legacy 路径逐位等价
%   （bit-exact）。v3.2 texture linear gate 的有效结果完整保留；Mid
%   权重、chromaWeight 与共享 referenceReliability 自 T15 起同样收口
%   到 stage contract（bit-exact 重建，下列共享路径断言保留为迁移等
%   价证明）。
[image, faceBox, parsing] = fixtureImage(120, 160);
context = prepareBeautyContext(image, faceBox, parsing, ...
    emptyBodyParsing([120, 160]));
[beautyMasks, ~] = masks.buildBeautyMasks(image, context, faceBox);
protection = masks.buildStageProtectionMasks(beautyMasks);
[frequency, ~] = beauty.decomposeSkinFrequency(image, faceBox);
[realBlemishMap, ~] = beauty.buildBlemishMap(image, frequency, beautyMasks);

% 注入高置信瑕疵证据：皮肤上的紧凑斑点（低局部密度，不触发
% sparseGate 抑制），其中两枚落在眼周 hard 特征 3px 带与鼻部结构保护
% 区，使 blemish 放宽量与 strongStructure 上限同时参与重建；真实
% buildBlemishMap 产物与零瑕疵参考各测一组。
[height, width] = size(image(:, :, 1));
[xGrid, yGrid] = meshgrid(1:width, 1:height);
injectedBlemish = zeros(height, width);
dotCenters = [44, 68; 55, 80; 70, 60; 80, 100; 60, 120; 35, 110; ...
    88, 66; 50, 45];
for dotIndex = 1:size(dotCenters, 1)
    injectedBlemish = max(injectedBlemish, .95 * exp( ...
        -((xGrid - dotCenters(dotIndex, 2)) .^ 2 + ...
        (yGrid - dotCenters(dotIndex, 1)) .^ 2) / (2 * 2.2 ^ 2)));
end
verifyTrue(testCase, max(injectedBlemish(:)) > .90, ...
    '注入斑点必须达到高置信瑕疵。');
verifyTrue(testCase, ...
    nnz(injectedBlemish(:) .* ...
    beautyMasks.structureProtectionMask(:)) > 0, ...
    '注入瑕疵必须与结构保护重叠，否则 blemish 放宽量重建未被覆盖。');
injectedSmoothed = beauty.smoothSkinTexture(frequency, beautyMasks, ...
    60, injectedBlemish, protection);
[~, injectedRepairDetails] = beauty.repairSkinBlemishes( ...
    injectedSmoothed, beautyMasks, injectedBlemish, 60);
verifyTrue(testCase, ...
    nnz(injectedRepairDetails.fineWeight) > 0, ...
    '注入斑点必须产生非零 fineWeight，否则 texture 门控断言无意义。');

strengths = [0, 25, 50, 75, 100];
blemishCases = {zeros(height, width), realBlemishMap, injectedBlemish};
for caseIndex = 1:numel(blemishCases)
    blemishMap = blemishCases{caseIndex};
    contract = makeTestRepairContract(beautyMasks, protection, ...
        blemishMap);
    for index = 1:numel(strengths)
        strength = strengths(index);
        [smoothed, ~] = beauty.smoothSkinTexture(frequency, ...
            beautyMasks, strength, blemishMap, protection);
        [repairedLegacy, legacyDetails] = ...
            beauty.repairSkinBlemishes(smoothed, beautyMasks, ...
            blemishMap, strength);
        [repairedStage, stageDetails] = ...
            beauty.repairSkinBlemishes(smoothed, beautyMasks, ...
            blemishMap, strength, contract);

        % stage 门控恰为 contract 按生产原式重建（bit-exact）。
        verifyEqual(testCase, stageDetails.fineGateRuntime, ...
            min(contract.blemishRelaxedGate, ...
            contract.strongStructureCap), 'AbsTol', 0);

        % 与 legacy 路径逐位等价：T14 迁移不改变任何数值。
        verifyEqual(testCase, stageDetails.fineWeight, ...
            legacyDetails.fineWeight, 'AbsTol', 0);
        verifyEqual(testCase, stageDetails.fineCorrection, ...
            legacyDetails.fineCorrection, 'AbsTol', 0);
        verifyEqual(testCase, repairedStage.fine, repairedLegacy.fine, ...
            'AbsTol', 0);
        verifyEqual(testCase, repairedStage.alphaMap, ...
            repairedLegacy.alphaMap, 'AbsTol', 0);

        % 零瑕疵快照语义（T07 衔接）：blemish = 0 时 stage 门控积与
        % 1 - repairFine 一致（仅 1-x 补码往返舍入）；blemish > 0 时
        % 相对快照只增不减（runtime 放宽约定）。
        gateProduct = stageDetails.fineGateRuntime .* ...
            contract.textureGate;
        snapshotReference = 1 - protection.repairFine;
        if max(blemishMap(:)) == 0
            verifyLessThanOrEqual(testCase, ...
                max(abs(gateProduct(:) - snapshotReference(:))), 1e-15);
        else
            verifyGreaterThanOrEqual(testCase, ...
                min(gateProduct(:) - snapshotReference(:)), -1e-15);
        end

        % 共享路径 bit-exact：T15 收口后 referenceReliability/chroma
        % 与 structureGate 从 contract 重建，与 legacy 计算逐位一致。
        verifyEqual(testCase, stageDetails.referenceReliability, ...
            legacyDetails.referenceReliability, 'AbsTol', 0);
        verifyEqual(testCase, stageDetails.mediumWeight, ...
            legacyDetails.mediumWeight, 'AbsTol', 0);
        verifyEqual(testCase, stageDetails.chromaWeight, ...
            legacyDetails.chromaWeight, 'AbsTol', 0);
        verifyEqual(testCase, stageDetails.structureGate, ...
            legacyDetails.structureGate, 'AbsTol', 0);
        verifyEqual(testCase, repairedStage.mid, repairedLegacy.mid, ...
            'AbsTol', 0);
        verifyEqual(testCase, repairedStage.base, repairedLegacy.base, ...
            'AbsTol', 0);

        % hard identity 保持：hard 区域 fineWeight 恒 0。
        verifyEqual(testCase, ...
            nnz(stageDetails.fineWeight(protection.hard >= .999)), 0);
    end
end

% 负向证明：stage 路径的 fineWeight 对 textureProtectionMask 扰动完全
% 不变（Fine 门控不再读取该字段），legacy 路径则会随之变化。
blemishMap = injectedBlemish;
contract = makeTestRepairContract(beautyMasks, protection, ...
    blemishMap);
[smoothed60, ~] = beauty.smoothSkinTexture(frequency, beautyMasks, 60, ...
    blemishMap, protection);
[~, legacyDetails60] = beauty.repairSkinBlemishes(smoothed60, ...
    beautyMasks, blemishMap, 60);
[~, stageDetails60] = beauty.repairSkinBlemishes(smoothed60, ...
    beautyMasks, blemishMap, 60, contract);
perturbedMasks = beautyMasks;
perturbedMasks.textureProtectionMask = ...
    min(1, beautyMasks.textureProtectionMask * .5 + .25);
[~, perturbedLegacyDetails] = beauty.repairSkinBlemishes(smoothed60, ...
    perturbedMasks, blemishMap, 60);
[~, perturbedStageDetails] = beauty.repairSkinBlemishes(smoothed60, ...
    perturbedMasks, blemishMap, 60, contract);
verifyTrue(testCase, ...
    nnz(perturbedLegacyDetails.fineWeight ~= ...
    legacyDetails60.fineWeight) > 0, ...
    'texture 扰动必须确实影响 legacy 路径，否则本断言无意义。');
verifyEqual(testCase, perturbedStageDetails.fineWeight, ...
    stageDetails60.fineWeight, 'AbsTol', 0);
% fineCorrection 的 texture 独立性由 T15 的
% testMidRepairConsumesStageProtectionContract 断言：共享
% referenceReliability 收口后，stage 全输出（含 fineCorrection/
% mediumCorrection）对 texture 扰动不变。

% 缺字段 fail-fast：不静默回退拼装。
brokenContract = rmfield(contract, 'blemishRelaxedGate');
verifyError(testCase, @() beauty.repairSkinBlemishes( ...
    smoothed60, beautyMasks, blemishMap, 60, brokenContract), ...
    'beauty:InvalidBlemishRepair');
end

function testMidRepairConsumesStageProtectionContract(testCase)
%TESTMIDREPAIRCONSUMESSTAGEPROTECTIONCONTRACT T15：提供生产端拼装的
%   repair stage contract 时，mediumWeight 门控只按生产原式从 contract
%   重建（结构门 min(blemishRelaxedGate, strongStructureCap) 作用于
%   [0,1] 截断之前，noseMidGate 与 textureGate 按生产顺序作用于截断之
%   后），不再自行组合 general texture/structure/nose masks；共享
%   referenceReliability 与 chromaWeight 的门控来源同步收口（bit-exact
%   同值）：扰动 texture/structure/nose masks 不改变 stage 路径的任何
%   输出（含 fineCorrection/mediumCorrection），legacy 路径则会随之变
%   化。快照 repairMid 为 T07 零瑕疵参考门：blemish = 0 时
%   structureGate·noseMidGate·textureGate 与 1 - repairMid 一致
%   （≤1e-15，1-x 补码往返舍入），blemish > 0 时相对快照只增不减。
%   T15 迁移不改变任何数值：stage 与 legacy 全输出逐位等价
%   （bit-exact）。诊断随之收口：stage 路径不再报告 noseMask，新增
%   mediumGateZeroBlemish 快照；legacy 路径字段不变。
[image, faceBox, parsing] = fixtureImage(120, 160);
context = prepareBeautyContext(image, faceBox, parsing, ...
    emptyBodyParsing([120, 160]));
[beautyMasks, ~] = masks.buildBeautyMasks(image, context, faceBox);
protection = masks.buildStageProtectionMasks(beautyMasks);
[frequency, ~] = beauty.decomposeSkinFrequency(image, faceBox);
[realBlemishMap, ~] = beauty.buildBlemishMap(image, frequency, beautyMasks);

% 注入高置信瑕疵证据：皮肤上 24 枚紧凑斑点（确定性网格，全局证据超
% 过 globalGate 阈值且低于 sparseGate 抑制线），使 mediumConfidence、
% blemish 放宽量、strongStructure 上限与 noseMidGate 同时参与重建。
% 真实 buildBlemishMap 产物与零瑕疵参考各测一组。
[height, width] = size(image(:, :, 1));
[xGrid, yGrid] = meshgrid(1:width, 1:height);
[dotRows, dotCols] = meshgrid(40:12:76, 42:12:102);
dotCenters = [dotRows(:), dotCols(:)];
injectedBlemish = zeros(height, width);
for dotIndex = 1:size(dotCenters, 1)
    injectedBlemish = max(injectedBlemish, .95 * exp( ...
        -((xGrid - dotCenters(dotIndex, 2)) .^ 2 + ...
        (yGrid - dotCenters(dotIndex, 1)) .^ 2) / (2 * 2.2 ^ 2)));
end
verifyTrue(testCase, max(injectedBlemish(:)) > .90, ...
    '注入斑点必须达到高置信瑕疵。');
verifyTrue(testCase, nnz(beautyMasks.noseMask > 0) > 0, ...
    'fixture 必须包含非空 noseMask，否则 noseMidGate 重建断言无意义。');
verifyTrue(testCase, ...
    nnz(injectedBlemish(:) .* beautyMasks.structureProtectionMask(:)) > 0, ...
    '注入瑕疵必须与结构保护重叠，否则 blemish 放宽量重建未被覆盖。');
injectedSmoothed = beauty.smoothSkinTexture(frequency, beautyMasks, ...
    60, injectedBlemish, protection);
[~, injectedRepairDetails] = beauty.repairSkinBlemishes( ...
    injectedSmoothed, beautyMasks, injectedBlemish, 60);
verifyTrue(testCase, nnz(injectedRepairDetails.mediumWeight) > 0, ...
    '注入斑点必须产生非零 mediumWeight，否则 Mid 门控断言无意义。');

strengths = [0, 25, 50, 75, 100];
blemishCases = {zeros(height, width), realBlemishMap, injectedBlemish};
for caseIndex = 1:numel(blemishCases)
    blemishMap = blemishCases{caseIndex};
    contract = makeTestRepairContract(beautyMasks, protection, ...
        blemishMap);
    for index = 1:numel(strengths)
        strength = strengths(index);
        [smoothed, ~] = beauty.smoothSkinTexture(frequency, ...
            beautyMasks, strength, blemishMap, protection);
        [repairedLegacy, legacyDetails] = ...
            beauty.repairSkinBlemishes(smoothed, beautyMasks, ...
            blemishMap, strength);
        [repairedStage, stageDetails] = ...
            beauty.repairSkinBlemishes(smoothed, beautyMasks, ...
            blemishMap, strength, contract);

        % stage 门控恰为 contract 按生产原式、原顺序重建（bit-exact）：
        % 结构门在截断之前，nose/texture 门在截断之后。
        structureGateRuntime = min(contract.blemishRelaxedGate, ...
            contract.strongStructureCap);
        verifyEqual(testCase, stageDetails.structureGate, ...
            structureGateRuntime, 'AbsTol', 0);
        expectedMedium = stageDetails.repairCurveMap .* ...
            (.95 * stageDetails.mediumConfidence + ...
            .40 * stageDetails.highConfidence) .* ...
            stageDetails.allowed .* structureGateRuntime + ...
            (stageDetails.highEndRepairCurve .* ...
            stageDetails.highEndConfidence) .* ...
            stageDetails.allowed .* structureGateRuntime;
        expectedMedium = min(max(expectedMedium, 0), 1);
        expectedMedium = expectedMedium .* contract.noseMidGate;
        expectedMedium = expectedMedium .* contract.textureGate;
        verifyEqual(testCase, stageDetails.mediumWeight, ...
            expectedMedium, 'AbsTol', 0);
        expectedChroma = .16 * stageDetails.repairCurveMap .* ...
            stageDetails.highConfidence .* stageDetails.allowed .* ...
            structureGateRuntime;
        expectedChroma = min(max(expectedChroma, 0), 1);
        expectedChroma = expectedChroma .* contract.textureGate;
        verifyEqual(testCase, stageDetails.chromaWeight, ...
            expectedChroma, 'AbsTol', 0);
        expectedReference = stageDetails.allowed .* ...
            contract.textureGate .* (1 - .86 * blemishMap) .* ...
            structureGateRuntime;
        verifyEqual(testCase, stageDetails.referenceReliability, ...
            expectedReference, 'AbsTol', 0);

        % 与 legacy 路径逐位等价：T15 迁移不改变任何数值。
        verifyEqual(testCase, stageDetails.mediumWeight, ...
            legacyDetails.mediumWeight, 'AbsTol', 0);
        verifyEqual(testCase, stageDetails.mediumCorrection, ...
            legacyDetails.mediumCorrection, 'AbsTol', 0);
        verifyEqual(testCase, stageDetails.chromaWeight, ...
            legacyDetails.chromaWeight, 'AbsTol', 0);
        verifyEqual(testCase, stageDetails.referenceReliability, ...
            legacyDetails.referenceReliability, 'AbsTol', 0);
        verifyEqual(testCase, repairedStage.mid, repairedLegacy.mid, ...
            'AbsTol', 0);
        verifyEqual(testCase, repairedStage.fine, repairedLegacy.fine, ...
            'AbsTol', 0);
        verifyEqual(testCase, repairedStage.alphaMap, ...
            repairedLegacy.alphaMap, 'AbsTol', 0);
        verifyEqual(testCase, repairedStage.base, repairedLegacy.base, ...
            'AbsTol', 0);

        % 零瑕疵快照语义（T07 衔接）：blemish = 0 时结构门·noseMidGate
        % ·textureGate 与 1 - repairMid 一致（仅 1-x 补码往返舍入）；
        % blemish > 0 时相对快照只增不减（runtime 放宽约定）。
        gateProduct = stageDetails.structureGate .* ...
            contract.noseMidGate .* contract.textureGate;
        snapshotReference = 1 - protection.repairMid;
        verifyEqual(testCase, stageDetails.mediumGateZeroBlemish, ...
            snapshotReference, 'AbsTol', 0);
        if max(blemishMap(:)) == 0
            verifyLessThanOrEqual(testCase, ...
                max(abs(gateProduct(:) - snapshotReference(:))), 1e-15);
        else
            verifyGreaterThanOrEqual(testCase, ...
                min(gateProduct(:) - snapshotReference(:)), -1e-15);
        end

        % hard identity 保持：hard 区域 mediumWeight 恒 0。
        verifyEqual(testCase, ...
            nnz(stageDetails.mediumWeight(protection.hard >= .999)), 0);
    end
end

% 负向证明：stage 路径的全部输出对 texture/structure/nose masks 扰动
% 完全不变（Fine/Mid 只消费 stage contract），legacy 路径则会随之变化。
blemishMap = injectedBlemish;
contract = makeTestRepairContract(beautyMasks, protection, blemishMap);
[smoothed60, ~] = beauty.smoothSkinTexture(frequency, beautyMasks, 60, ...
    blemishMap, protection);
[~, legacyDetails60] = beauty.repairSkinBlemishes(smoothed60, ...
    beautyMasks, blemishMap, 60);
[~, stageDetails60] = beauty.repairSkinBlemishes(smoothed60, ...
    beautyMasks, blemishMap, 60, contract);
[repairedStage60, ~] = beauty.repairSkinBlemishes(smoothed60, ...
    beautyMasks, blemishMap, 60, contract);
perturbedMasks = beautyMasks;
perturbedMasks.textureProtectionMask = ...
    min(1, beautyMasks.textureProtectionMask * .5 + .25);
perturbedMasks.structureProtectionMask = ...
    min(1, beautyMasks.structureProtectionMask * .5 + .25);
perturbedMasks.noseMask = min(1, beautyMasks.noseMask * .5 + .25);
[repairedPerturbedLegacy, perturbedLegacyDetails] = ...
    beauty.repairSkinBlemishes(smoothed60, perturbedMasks, blemishMap, 60);
[repairedPerturbedStage, perturbedStageDetails] = ...
    beauty.repairSkinBlemishes(smoothed60, perturbedMasks, blemishMap, ...
    60, contract);
verifyTrue(testCase, ...
    nnz(perturbedLegacyDetails.mediumWeight ~= ...
    legacyDetails60.mediumWeight) > 0, ...
    'texture/structure/nose 扰动必须确实影响 legacy Mid 权重，否则本断言无意义。');
verifyTrue(testCase, ...
    nnz(perturbedLegacyDetails.fineWeight ~= ...
    legacyDetails60.fineWeight) > 0, ...
    'texture/structure 扰动必须确实影响 legacy Fine 权重，否则本断言无意义。');
verifyEqual(testCase, perturbedStageDetails.mediumWeight, ...
    stageDetails60.mediumWeight, 'AbsTol', 0);
verifyEqual(testCase, perturbedStageDetails.fineWeight, ...
    stageDetails60.fineWeight, 'AbsTol', 0);
verifyEqual(testCase, perturbedStageDetails.referenceReliability, ...
    stageDetails60.referenceReliability, 'AbsTol', 0);
verifyEqual(testCase, repairedPerturbedStage, repairedStage60, ...
    'AbsTol', 0);

% 诊断收口：stage 路径不再报告 noseMask（Mid 不读取 nose 特判输入），
% 新增 mediumGateZeroBlemish 快照；legacy 路径字段保持不变。
verifyEqual(testCase, isfield(stageDetails60, 'noseMask'), false, ...
    'stage 路径不得再报告 noseMask 诊断字段。');
verifyTrue(testCase, isfield(stageDetails60, ...
    'mediumGateZeroBlemish'));
verifyTrue(testCase, isfield(legacyDetails60, 'noseMask') && ...
    isfield(legacyDetails60, 'noseMidGate') && ...
    ~isfield(legacyDetails60, 'mediumGateZeroBlemish'));

% 缺字段 fail-fast：不静默回退拼装。
brokenContract = rmfield(contract, 'noseMidGate');
verifyError(testCase, @() beauty.repairSkinBlemishes( ...
    smoothed60, beautyMasks, blemishMap, 60, brokenContract), ...
    'beauty:InvalidBlemishRepair');
brokenContract = rmfield(contract, 'repairMid');
verifyError(testCase, @() beauty.repairSkinBlemishes( ...
    smoothed60, beautyMasks, blemishMap, 60, brokenContract), ...
    'beauty:InvalidBlemishRepair');
end

function testBaseLuminanceConsumesStageProtectionContract(testCase)
%TESTBASELUMINANCECONSUMESSTAGEPROTECTIONCONTRACT T16：提供生产端拼装的
%   Base Luminance stage contract 时，feature/reference support 的保护
%   输入只从 contract 的未折叠 structureGate/featureGate 与 hard 按生
%   产原式、原顺序重建（referenceReliability 与 supportMap 共用），不再
%   自行组合 general texture/chroma/structure/hard masks：扰动这些
%   masks 不改变 stage 路径的任何输出，legacy 路径则会随之变化。快照
%   baseLuminance 的折叠含 1-x 补码往返舍入，不参与输出算术：runtime
%   门控积 structureGate·featureGate 与 1 - baseLuminance 一致
%   （≤1e-15，1-x 补码往返舍入），T07 supportMap =
%   baseWeightCurve·regionalSkinWeight·(1-hard)·(1-baseLuminance)·
%   referenceCoverage 的语义由该快照衔接。T16 迁移不改变任何数值：
%   stage 与 legacy 全输出逐位等价（bit-exact）。诊断随之收口：stage
%   路径不再报告 chroma/tone 兼容 alias，新增 baseGateSnapshot 快照；
%   legacy 路径字段不变。
[image, faceBox, parsing] = fixtureImage(120, 160);
context = prepareBeautyContext(image, faceBox, parsing, ...
    emptyBodyParsing([120, 160]));
[beautyMasks, ~] = masks.buildBeautyMasks(image, context, faceBox);
protection = masks.buildStageProtectionMasks(beautyMasks);
[frequency, ~] = beauty.decomposeSkinFrequency(image, faceBox);
contract = makeTestBaseLuminanceContract(beautyMasks, protection);

strengths = [0, 25, 50, 75, 100];
for index = 1:numel(strengths)
    strength = strengths(index);
    [resultLegacy, legacyDetails] = beauty.evenSkinLuminance( ...
        frequency, beautyMasks, strength);
    [resultStage, stageDetails] = beauty.evenSkinLuminance( ...
        frequency, beautyMasks, strength, contract);

    % stage 结果与 legacy 全字段逐位一致：T16 迁移不改变任何数值。
    verifyTrue(testCase, isequaln(resultStage, resultLegacy), ...
        'stage 路径的 base luminance 结果必须与 legacy 逐位一致。');
    % 共享参考与门控逐位一致（显式断言关键数值字段）。
    verifyEqual(testCase, stageDetails.referenceReliability, ...
        legacyDetails.referenceReliability, 'AbsTol', 0);
    verifyEqual(testCase, stageDetails.referenceWeight, ...
        legacyDetails.referenceWeight, 'AbsTol', 0);
    verifyEqual(testCase, stageDetails.referenceCoverage, ...
        legacyDetails.referenceCoverage, 'AbsTol', 0);
    verifyEqual(testCase, stageDetails.referenceOffset, ...
        legacyDetails.referenceOffset, 'AbsTol', 0);
    verifyEqual(testCase, stageDetails.supportMap, ...
        legacyDetails.supportMap, 'AbsTol', 0);
    verifyEqual(testCase, stageDetails.baseDelta, ...
        legacyDetails.baseDelta, 'AbsTol', 0);
    verifyEqual(testCase, stageDetails.structureGate, ...
        legacyDetails.structureGate, 'AbsTol', 0);
    verifyEqual(testCase, stageDetails.hardProtectionGate, ...
        legacyDetails.hardProtectionGate, 'AbsTol', 0);
    verifyEqual(testCase, stageDetails.featureGate, ...
        legacyDetails.featureGate, 'AbsTol', 0);

    % 快照语义（T07 衔接）：runtime 门控积与 1 - baseLuminance 一致
    % （仅 1-x 补码往返舍入）；supportMap 与 T07 快照重算一致。
    verifyEqual(testCase, stageDetails.baseGateSnapshot, ...
        1 - protection.baseLuminance, 'AbsTol', 0);
    verifyLessThanOrEqual(testCase, ...
        max(abs(stageDetails.structureGate(:) .* ...
        stageDetails.featureGate(:) - ...
        stageDetails.baseGateSnapshot(:))), 1e-15);
    snapshotSupport = stageDetails.baseWeightCurve .* ...
        stageDetails.regionalSkinWeight .* ...
        stageDetails.hardProtectionGate .* ...
        stageDetails.baseGateSnapshot .* ...
        stageDetails.referenceCoverage;
    verifyLessThanOrEqual(testCase, ...
        max(abs(stageDetails.supportMap(:) - snapshotSupport(:))), 1e-15);

    % hard identity 保持：hard 区域 supportMap/baseDelta 恒 0。
    verifyEqual(testCase, ...
        nnz(stageDetails.supportMap(protection.hard >= .999)), 0);
    verifyEqual(testCase, ...
        nnz(stageDetails.baseDelta(protection.hard >= .999)), 0);
end

% 负向证明：stage 路径的全部输出对 texture/chroma/structure/hard masks
% 扰动完全不变（只消费 stage contract），legacy 路径则会随之变化。
[~, legacyDetails60] = beauty.evenSkinLuminance(frequency, beautyMasks, 60);
[~, stageDetails60] = beauty.evenSkinLuminance(frequency, beautyMasks, ...
    60, contract);
perturbedMasks = beautyMasks;
perturbedMasks.textureProtectionMask = ...
    min(1, beautyMasks.textureProtectionMask * .5 + .25);
perturbedMasks.structureProtectionMask = ...
    min(1, beautyMasks.structureProtectionMask * .5 + .25);
perturbedMasks.chromaProtectionMask = ...
    min(1, beautyMasks.chromaProtectionMask * .5 + .25);
perturbedMasks.toneProtectionMask = perturbedMasks.chromaProtectionMask;
perturbedMasks.hardProtectionMask = ...
    min(1, beautyMasks.hardProtectionMask * .5 + .25);
[~, perturbedLegacyDetails] = beauty.evenSkinLuminance( ...
    frequency, perturbedMasks, 60);
[~, perturbedStageDetails] = beauty.evenSkinLuminance( ...
    frequency, perturbedMasks, 60, contract);
verifyTrue(testCase, ...
    nnz(perturbedLegacyDetails.supportMap ~= ...
    legacyDetails60.supportMap) > 0, ...
    'texture/chroma/structure/hard 扰动必须确实影响 legacy 路径，否则本断言无意义。');
verifyEqual(testCase, perturbedStageDetails.supportMap, ...
    stageDetails60.supportMap, 'AbsTol', 0);
verifyEqual(testCase, perturbedStageDetails.baseDelta, ...
    stageDetails60.baseDelta, 'AbsTol', 0);
verifyEqual(testCase, perturbedStageDetails.referenceReliability, ...
    stageDetails60.referenceReliability, 'AbsTol', 0);

% 诊断收口：stage 路径不再报告 chroma/tone 兼容 alias，新增
% baseGateSnapshot 快照；legacy 路径字段保持不变。
verifyEqual(testCase, ...
    isfield(stageDetails60, {'chromaProtectionMask', ...
    'toneProtectionMask'}), [false, false], ...
    'stage 路径不得再报告 chroma/tone 兼容 alias 诊断字段。');
verifyTrue(testCase, isfield(stageDetails60, 'baseGateSnapshot'));
verifyTrue(testCase, isfield(legacyDetails60, ...
    'chromaProtectionMask') && isfield(legacyDetails60, ...
    'toneProtectionMask') && ...
    ~isfield(legacyDetails60, 'baseGateSnapshot'));
verifyEqual(testCase, legacyDetails60.chromaProtectionMask, ...
    beautyMasks.chromaProtectionMask, 'AbsTol', 0);

% 缺字段与取值越界 fail-fast：不静默回退拼装。
brokenContract = rmfield(contract, 'featureGate');
verifyError(testCase, @() beauty.evenSkinLuminance( ...
    frequency, beautyMasks, 60, brokenContract), ...
    'beauty:InvalidEvenLuminanceInput');
brokenContract = rmfield(contract, 'baseLuminance');
verifyError(testCase, @() beauty.evenSkinLuminance( ...
    frequency, beautyMasks, 60, brokenContract), ...
    'beauty:InvalidEvenLuminanceInput');
brokenContract = contract;
brokenContract.structureGate = min(1, ...
    brokenContract.structureGate) + .25;
verifyError(testCase, @() beauty.evenSkinLuminance( ...
    frequency, beautyMasks, 60, brokenContract), ...
    'beauty:InvalidEvenLuminanceInput');
end

function testToneConsumesStageProtectionContract(testCase)
%TESTTONECONSUMESSTAGEPROTECTIONCONTRACT T17：提供生产端拼装的 Tone
%   stage contract 时，主/uniform 两分支的保护门控与候选色度保护门限
%   只按生产原式从 contract 的未折叠 structureGate/featureGate/
%   uniformFeatureGate/candidateChromaGate 与 hard 重建，不再自行组合
%   general structure/chroma/hard masks：扰动这些 masks 不改变 stage
%   路径的任何输出，legacy 路径则会随之变化。快照 tone 的折叠只覆盖
%   主分支且含 1-x 补码往返舍入，不参与输出算术：主分支门控积
%   structureGate·featureGate 与 1 - tone 一致（≤1e-15），uniform 分
%   支门控积不高于该快照（T07 已知残差：uniform 分支保护更强）。
%   strengthMap/skinMask 继续显式控制效果幅度，strength 与 protection
%   不合并。T17 迁移不改变任何数值：stage 与 legacy 全输出逐位等价
%   （bit-exact）。诊断随之收口：stage 路径不再报告 structure/chroma/
%   tone 兼容 alias，新增 toneGateSnapshot 快照；legacy 路径字段不变。
[image, faceBox, parsing] = fixtureImage(120, 160);
context = prepareBeautyContext(image, faceBox, parsing, ...
    emptyBodyParsing([120, 160]));
[beautyMasks, ~] = masks.buildBeautyMasks(image, context, faceBox);
protection = masks.buildStageProtectionMasks(beautyMasks);
[frequency, ~] = beauty.decomposeSkinFrequency(image, faceBox);
[realBlemishMap, ~] = beauty.buildBlemishMap(image, frequency, beautyMasks);
contract = makeTestToneContract(beautyMasks, protection);

% 强度序列覆盖两分支：25 走主分支（ratio<=.50），60 处于 uniform
% ramp 中段，75/100 为 uniform 档；0 为零强度端点。
strengths = [0, 25, 50, 60, 75, 100];
blemishCases = {zeros(size(realBlemishMap)), realBlemishMap};
for caseIndex = 1:numel(blemishCases)
    blemishMap = blemishCases{caseIndex};
    for index = 1:numel(strengths)
        strength = strengths(index);
        [toneLegacy, legacyDetails] = beauty.normalizeSkinTone( ...
            image, frequency, beautyMasks, blemishMap, strength);
        [toneStage, stageDetails] = beauty.normalizeSkinTone( ...
            image, frequency, beautyMasks, blemishMap, strength, ...
            contract);

        % 与 legacy 路径逐位等价：T17 迁移不改变任何数值（toneResult
        % 不含保护字段，整体逐位一致，含渲染输出图像）。
        verifyTrue(testCase, isequaln(toneStage, toneLegacy), ...
            'stage 路径的 tone 结果必须与 legacy 逐位一致。');
        % 关键门控与输出字段显式断言（含两分支权重与候选选择）。
        verifyEqual(testCase, stageDetails.weightMap, ...
            legacyDetails.weightMap, 'AbsTol', 0);
        verifyEqual(testCase, stageDetails.candidateMask, ...
            legacyDetails.candidateMask, 'AbsTol', 0);
        verifyEqual(testCase, stageDetails.uniformToneCurve, ...
            legacyDetails.uniformToneCurve, 'AbsTol', 0);
        verifyEqual(testCase, stageDetails.localBlend, ...
            legacyDetails.localBlend, 'AbsTol', 0);
        verifyEqual(testCase, stageDetails.deltaCb, ...
            legacyDetails.deltaCb, 'AbsTol', 0);
        verifyEqual(testCase, stageDetails.deltaCr, ...
            legacyDetails.deltaCr, 'AbsTol', 0);

        % 快照语义（T07 衔接）：主分支门控积与 1 - tone 一致（仅 1-x
        % 补码往返舍入）；uniform 分支门控积不高于快照（更强保护）。
        verifyEqual(testCase, stageDetails.toneGateSnapshot, ...
            1 - protection.tone, 'AbsTol', 0);
        verifyLessThanOrEqual(testCase, max(abs( ...
            contract.structureGate(:) .* contract.featureGate(:) - ...
            stageDetails.toneGateSnapshot(:))), 1e-15);
        uniformGateProduct = contract.structureGate .* ...
            contract.uniformFeatureGate;
        verifyLessThanOrEqual(testCase, max(uniformGateProduct(:) - ...
            stageDetails.toneGateSnapshot(:)), 1e-15);

        % hard identity 保持：hard 区域权重恒 0。
        verifyEqual(testCase, ...
            nnz(stageDetails.weightMap(protection.hard >= .999)), 0);
    end
end

% 两分支覆盖确认：s=25 未激活 uniform 分支，s=60 已激活；fixture 在
% 两个分支下都必须产生非零权重，否则门控断言无意义。
[~, details25] = beauty.normalizeSkinTone(image, frequency, ...
    beautyMasks, realBlemishMap, 25, contract);
[~, details60] = beauty.normalizeSkinTone(image, frequency, ...
    beautyMasks, realBlemishMap, 60, contract);
verifyEqual(testCase, details25.uniformToneCurve, 0, 'AbsTol', 0);
verifyGreaterThan(testCase, details60.uniformToneCurve, 0);
verifyTrue(testCase, nnz(details25.weightMap) > 0, ...
    'fixture 必须产生非零主分支 tone 权重，否则本测试断言无意义。');
verifyTrue(testCase, nnz(details60.weightMap) > 0, ...
    'fixture 必须产生非零 uniform 分支 tone 权重，否则本测试断言无意义。');

% 负向证明：stage 路径的全部输出对 structure/chroma/tone/hard masks
% 扰动完全不变（只消费 stage contract），legacy 路径则会随之变化。
[~, legacyDetails60] = beauty.normalizeSkinTone(image, frequency, ...
    beautyMasks, realBlemishMap, 60);
[~, stageDetails60] = beauty.normalizeSkinTone(image, frequency, ...
    beautyMasks, realBlemishMap, 60, contract);
perturbedMasks = beautyMasks;
perturbedMasks.structureProtectionMask = ...
    min(1, beautyMasks.structureProtectionMask * .5 + .25);
perturbedMasks.chromaProtectionMask = ...
    min(1, beautyMasks.chromaProtectionMask * .5 + .25);
perturbedMasks.toneProtectionMask = perturbedMasks.chromaProtectionMask;
perturbedMasks.hardProtectionMask = ...
    min(1, beautyMasks.hardProtectionMask * .5 + .25);
[~, perturbedLegacyDetails] = beauty.normalizeSkinTone(image, ...
    frequency, perturbedMasks, realBlemishMap, 60);
[~, perturbedStageDetails] = beauty.normalizeSkinTone(image, ...
    frequency, perturbedMasks, realBlemishMap, 60, contract);
verifyTrue(testCase, ...
    nnz(perturbedLegacyDetails.weightMap ~= ...
    legacyDetails60.weightMap) > 0, ...
    'structure/chroma/tone/hard 扰动必须确实影响 legacy 路径，否则本断言无意义。');
verifyEqual(testCase, perturbedStageDetails.weightMap, ...
    stageDetails60.weightMap, 'AbsTol', 0);
verifyEqual(testCase, perturbedStageDetails.candidateMask, ...
    stageDetails60.candidateMask, 'AbsTol', 0);
verifyEqual(testCase, perturbedStageDetails.deltaCb, ...
    stageDetails60.deltaCb, 'AbsTol', 0);
verifyEqual(testCase, perturbedStageDetails.deltaCr, ...
    stageDetails60.deltaCr, 'AbsTol', 0);

% 诊断收口：stage 路径不再报告 structure/chroma/tone 兼容 alias，
% 新增 toneGateSnapshot 快照；legacy 路径字段保持不变。
verifyEqual(testCase, isfield(stageDetails60, ...
    {'structureProtectionMask', 'chromaProtectionMask', ...
    'toneProtectionMask'}), [false, false, false], ...
    'stage 路径不得再报告 structure/chroma/tone 兼容 alias 诊断字段。');
verifyTrue(testCase, isfield(stageDetails60, 'toneGateSnapshot'));
verifyTrue(testCase, isfield(legacyDetails60, ...
    'structureProtectionMask') && isfield(legacyDetails60, ...
    'chromaProtectionMask') && isfield(legacyDetails60, ...
    'toneProtectionMask') && ...
    ~isfield(legacyDetails60, 'toneGateSnapshot'));
verifyEqual(testCase, legacyDetails60.chromaProtectionMask, ...
    beautyMasks.chromaProtectionMask, 'AbsTol', 0);
verifyEqual(testCase, stageDetails60.hardProtectionMask, ...
    beautyMasks.hardProtectionMask, 'AbsTol', 0);

% 缺字段与取值越界 fail-fast：不静默回退拼装。
brokenContract = rmfield(contract, 'uniformFeatureGate');
verifyError(testCase, @() beauty.normalizeSkinTone(image, frequency, ...
    beautyMasks, realBlemishMap, 60, brokenContract), ...
    'beauty:InvalidSkinToneInput');
brokenContract = rmfield(contract, 'candidateChromaGate');
verifyError(testCase, @() beauty.normalizeSkinTone(image, frequency, ...
    beautyMasks, realBlemishMap, 60, brokenContract), ...
    'beauty:InvalidSkinToneInput');
brokenContract = rmfield(contract, 'tone');
verifyError(testCase, @() beauty.normalizeSkinTone(image, frequency, ...
    beautyMasks, realBlemishMap, 60, brokenContract), ...
    'beauty:InvalidSkinToneInput');
brokenContract = contract;
brokenContract.structureGate = min(1, ...
    brokenContract.structureGate) + .25;
verifyError(testCase, @() beauty.normalizeSkinTone(image, frequency, ...
    beautyMasks, realBlemishMap, 60, brokenContract), ...
    'beauty:InvalidSkinToneInput');
end

function testRuntimeEvidenceAssemblesProducerArtifactsBitExact(testCase)
%TESTRUNTIMEEVIDENCEASSEMBLESPRODUCERARTIFACTSBITEXACT T11：beautifyImage
%   内部组装的运行期 evidence（frequency/blemish）必须与独立调用
%   producer 的产物 bit-exact 一致，证明编排层只搬运 runtime evidence、
%   不改变任何数值；blemish map 不读取美颜强度，不同参数组合下完全一致。
[image, faceBox, parsing] = fixtureImage(120, 160);
context = prepareBeautyContext(image, faceBox, parsing, ...
    emptyBodyParsing([120, 160]));
uncachedContext = rmfield(context, 'runtimeCache');
params = struct('smoothingStrength', 60, 'whiteningStrength', 30);
[~, diagnostics] = beautifyImage(image, params, faceBox, uncachedContext);

[beautyMasks, ~] = masks.buildBeautyMasks(image, uncachedContext, faceBox);
[frequency, decompositionDiagnostics] = beauty.decomposeSkinFrequency( ...
    image, faceBox);
[blemishMap, blemishDiagnostics] = beauty.buildBlemishMap( ...
    image, frequency, beautyMasks);

% blemish map 与 blemish 运行期证据：与 producer 逐字段 bit-exact。
verifyEqual(testCase, diagnostics.blemishMap, blemishMap, 'AbsTol', 0);
evidenceNames = {'fineEvidence', 'midEvidence', 'chromaEvidence', ...
    'skinCandidate', 'structureProtectionMask'};
for index = 1:numel(evidenceNames)
    verifyEqual(testCase, ...
        diagnostics.blemish.(evidenceNames{index}), ...
        blemishDiagnostics.(evidenceNames{index}), 'AbsTol', 0);
end

% frequency 分解：与 producer bit-exact。
bandNames = {'base', 'mid', 'fine'};
for index = 1:numel(bandNames)
    verifyEqual(testCase, ...
        diagnostics.frequency.(bandNames{index}), ...
        decompositionDiagnostics.(bandNames{index}), 'AbsTol', 0);
end
verifyEqual(testCase, diagnostics.frequency.reconstructionError, ...
    decompositionDiagnostics.reconstructionError, 'AbsTol', 0);
verifyEqual(testCase, diagnostics.frequency.fineSigma, ...
    decompositionDiagnostics.fineSigma, 'AbsTol', 0);
verifyEqual(testCase, diagnostics.frequency.mediumSigma, ...
    decompositionDiagnostics.mediumSigma, 'AbsTol', 0);

% blemish map 不读取强度：不同参数组合下与 producer 完全一致。
strengthCombos = [0, 100; 100, 0; 100, 100; 25, 75];
for index = 1:size(strengthCombos, 1)
    comboParams = struct( ...
        'smoothingStrength', strengthCombos(index, 1), ...
        'whiteningStrength', strengthCombos(index, 2));
    [~, comboDiagnostics] = beautifyImage(image, comboParams, faceBox, ...
        uncachedContext);
    verifyEqual(testCase, comboDiagnostics.blemishMap, blemishMap, ...
        'AbsTol', 0);
end
end

function testRuntimeEvidenceStaysOutOfPersistedPolicyTimeContext(testCase)
%TESTRUNTIMEEVIDENCESTAYSOUTOFPERSISTEDPOLICYTIMECONTEXT T11 验收：
%   runtime evidence（frequency/blemish）不得成为持久化 policy-time
%   Context 的必要输入——不进 V4 canonical 分层（semantic/
%   processability/evidence/protection），不出现在 T06 policy-time
%   evidence 层，规范化往返后也不引入运行期字段。
[image, faceBox, parsing] = fixtureImage(120, 160);
context = prepareBeautyContext(image, faceBox, parsing, ...
    emptyBodyParsing([120, 160]));

runtimeNames = {'runtimeEvidence', 'blemishMap', 'blemish', 'frequency'};
verifyEqual(testCase, isfield(context, runtimeNames), ...
    [false, false, false, false], ...
    '持久化 Context 不得携带 runtime evidence 字段。');
verifyTrue(testCase, isfield(context, 'evidence'));
verifyEqual(testCase, isfield(context.evidence, ...
    {'blemishMap', 'blemish', 'frequency', 'fine', 'mid', 'base'}), ...
    false(1, 6), ...
    'policy-time evidence 层显式不含 blemish/frequency 结果。');

reread = normalizeBeautyContext(image, faceBox, context);
verifyEqual(testCase, isfield(reread, runtimeNames), ...
    [false, false, false, false], ...
    '规范化往返后 Context 不得引入 runtime evidence 字段。');
end

function [image, faceBox, parsing] = fixtureImage(height, width)
image = uint8(ones(height, width, 3) * 145);
[xGrid, yGrid] = meshgrid(1:width, 1:height);
skin = ((xGrid - width * .50) / (width * .33)) .^ 2 + ...
    ((yGrid - height * .43) / (height * .40)) .^ 2 <= 1;
neck = xGrid >= width * .40 & xGrid <= width * .60 & ...
    yGrid >= height * .73 & yGrid <= height * .94;
skin = skin | neck;
for channel = 1:3
    channelImage = image(:, :, channel);
    channelImage(skin) = uint8(168 + 7 * sin(2 * pi * xGrid(skin) / 17));
    image(:, :, channel) = channelImage;
end
nose = ((xGrid - width * .50) / (width * .10)) .^ 2 + ...
    ((yGrid - height * .45) / (height * .20)) .^ 2 <= 1;
image(:, :, 1) = image(:, :, 1) + uint8(12 * nose);
image(:, :, 2) = image(:, :, 2) + uint8(7 * nose);
image(:, :, 3) = image(:, :, 3) + uint8(4 * nose);
image(ceil(height * .45):ceil(height * .55), ...
    ceil(width * .43):ceil(width * .46), :) = uint8(95);
eye = false(height, width);
eye(ceil(height * .30):ceil(height * .33), ...
    ceil(width * .38):ceil(width * .46)) = true;
lip = false(height, width);
lip(ceil(height * .62):ceil(height * .66), ...
    ceil(width * .43):ceil(width * .57)) = true;
faceBox = [round(width * .17), round(height * .08), ...
    round(width * .66), round(height * .67)];
parsing = emptyFaceParsing([height, width]);
parsing.regions.skin = double(skin);
parsing.regionConfidence.skin = double(skin);
parsing.regions.neck = double(neck);
parsing.regionConfidence.neck = double(neck);
parsing.regions.nose = double(nose);
parsing.regionConfidence.nose = double(nose);
parsing.regions.leftEye = double(eye);
parsing.regionConfidence.leftEye = double(eye);
parsing.regions.upperLip = double(lip);
parsing.regionConfidence.upperLip = double(lip);
parsing.regions.lowerLip = double(lip);
parsing.regionConfidence.lowerLip = double(lip);
end

function parsing = emptyFaceParsing(imageSize)
names = faceParsingClassNames();
parsing = struct('regions', struct(), 'regionConfidence', struct());
for index = 1:numel(names)
    parsing.regions.(names{index}) = zeros(imageSize);
    parsing.regionConfidence.(names{index}) = zeros(imageSize);
end
end

function options = emptyBodyParsing(imageSize)
options = struct('probabilities', zeros([imageSize, 20], 'single'));
end

function contract = makeTestRepairContract(beautyMasks, protection, ...
    blemishMap)
%MAKETESTREPAIRCONTRACT 复现生产端 makeRepairStageContract（T14/T15）
%   的未折叠字段公式，供消费侧重建断言与扰动负向证明使用。
hard = protection.hard;
hardFeatureBand = bwdist(hard >= .999) <= 3;
strongStructure = smoothStep(beautyMasks.structureProtectionMask, ...
    .70, .90) .* double(hardFeatureBand);
contract = struct( ...
    'repairFine', protection.repairFine, ...
    'repairMid', protection.repairMid, ...
    'hard', hard, ...
    'blemishRelaxedGate', 1 - beautyMasks.structureProtectionMask .* ...
    (1 - .90 * blemishMap), ...
    'strongStructureCap', 1 - .65 * strongStructure, ...
    'textureGate', 1 - beautyMasks.textureProtectionMask, ...
    'noseMidGate', 1 - .50 * beautyMasks.noseMask);
end

function contract = makeTestBaseLuminanceContract(beautyMasks, protection)
%MAKETESTBASELUMINANCECONTRACT 复现生产端
%   makeBaseLuminanceStageContract（T16）的未折叠字段公式，供消费侧
%   等价断言与扰动负向证明使用。
contract = struct( ...
    'baseLuminance', protection.baseLuminance, ...
    'hard', protection.hard, ...
    'structureGate', 1 - beautyMasks.structureProtectionMask, ...
    'featureGate', 1 - max(beautyMasks.textureProtectionMask, ...
    beautyMasks.chromaProtectionMask));
end

function contract = makeTestToneContract(beautyMasks, protection)
%MAKETESTTONECONTRACT 复现生产端 makeToneStageContract（T17）的未折叠
%   字段公式（含 chroma/tone alias 解析与缺省回退，与 consumer legacy
%   路径同源），供消费侧等价断言与扰动负向证明使用。
imageSize = size(beautyMasks.skinMask, 1:2);
[chromaProtection, hasChromaProtection] = resolveChromaProtectionMask( ...
    beautyMasks, imageSize, 'beauty:InvalidSkinToneInput', ...
    'beauty:ChromaProtectionConflict');
if ~hasChromaProtection
    chromaProtection = zeros(imageSize);
end
contract = struct( ...
    'tone', protection.tone, ...
    'hard', protection.hard, ...
    'structureGate', 1 - beautyMasks.structureProtectionMask, ...
    'featureGate', 1 - .78 * chromaProtection, ...
    'uniformFeatureGate', 1 - chromaProtection, ...
    'candidateChromaGate', double(chromaProtection < .70));
end

function value = smoothStep(inputValue, low, high)
%SMOOTHSTEP 复现生产 smoothstep 曲线（t^2*(3-2t)），供 tone 重算使用。
t = min(max((double(inputValue) - low) / max(high - low, eps), 0), 1);
value = t .^ 2 .* (3 - 2 * t);
end
