function tests = testLashOrientationCoherenceEvidence
%TESTLASHORIENTATIONCOHERENCEEVIDENCE 验证 Issue 08.8 离线诊断契约。
tests = functiontests(localfunctions);
end

function setupOnce(~)
testRoot = fileparts(mfilename('fullpath'));
projectRoot = fileparts(testRoot);
addpath(fullfile(projectRoot, 'src'), '-begin');
addpath(testRoot, '-begin');
end

function testRejectsNonFixedFixtureBeforeUpstreamRun(testCase)
projectRoot = fileparts(fileparts(mfilename('fullpath')));
inputPath = fullfile(projectRoot, '人脸', '人脸', '77.png');
options = fixedOptions();
options.lashRoi = [103, 248, 177, 48];
verifyError(testCase, @() diagnoseLashOrientationCoherenceEvidence( ...
    inputPath, tempdir, options), ...
    'diagnoseLashOrientationCoherenceEvidence:NonFixedFixture');
end

function testFixed77WritesOrientationCoherenceEvidence(testCase)
projectRoot = fileparts(fileparts(mfilename('fullpath')));
inputPath = fullfile(projectRoot, '人脸', '人脸', '77.png');
outputFolder = fullfile(tempdir, ...
    'image_beauty_issue08_8_lash_orientation_coherence_20260919');
[summary, diagnostics] = diagnoseLashOrientationCoherenceEvidence( ...
    inputPath, outputFolder, fixedOptions());

verifyTrue(testCase, summary.completed);
verifyEqual(testCase, summary.issue, '08.8');
verifyEqual(testCase, summary.case, 'caseC_notSeparable');
verifyEqual(testCase, summary.inputSize, [450, 512, 3]);
verifyEqual(testCase, summary.faceBox, [95, 79, 286, 372]);
verifyEqual(testCase, summary.browEye, [165, 205, 150, 100]);
verifyEqual(testCase, summary.lashRoi, [102, 248, 177, 48]);
verifyEqual(testCase, summary.manualLashMaskId, '77-manual-lash-v1');
verifyEqual(testCase, summary.manualLashMaskPixels, 576);
verifyTrue(testCase, summary.manualLashMaskIndependent);
verifyTrue(testCase, summary.manualLashMaskFixed);
verifyFalse(testCase, summary.manualTruthUsedForFeature);
verifyFalse(testCase, summary.manualTruthUsedForGeneration);
verifyFalse(testCase, summary.productionModified);
verifyFalse(testCase, summary.coherenceThresholdUsed);
verifyFalse(testCase, summary.parameterScanUsed);
verifyFalse(testCase, summary.tensorEnergyThresholdUsed);
verifyFalse(testCase, summary.orientationAngularThresholdUsed);
verifyEqual(testCase, summary.tensorSigma, summary.lineSigma, 'AbsTol', 1e-12);
verifyEqual(testCase, summary.tensorSmoothingScaleSource, ...
    'existing detectLashLines lineImage sigma');
verifyLessThanOrEqual(testCase, ...
    diagnostics.upstreamEvidence.lineSupportFromAngleMaxError, 1e-12);

verifyEqual(testCase, size(diagnostics.gradientX), [450, 512]);
verifyEqual(testCase, size(diagnostics.gradientY), [450, 512]);
verifyEqual(testCase, size(diagnostics.Jxx), [450, 512]);
verifyEqual(testCase, size(diagnostics.Jyy), [450, 512]);
verifyEqual(testCase, size(diagnostics.Jxy), [450, 512]);
verifyEqual(testCase, size(diagnostics.orientation), [450, 512]);
verifyEqual(testCase, size(diagnostics.coherence), [450, 512]);
verifyTrue(testCase, all(diagnostics.coherence(:) >= 0));
verifyTrue(testCase, all(diagnostics.coherence(:) <= 1));
verifyTrue(testCase, all(diagnostics.orientation(:) >= -pi / 2 - 1e-12));
verifyTrue(testCase, all(diagnostics.orientation(:) <= pi / 2 + 1e-12));
verifyTrue(testCase, islogical(diagnostics.manualLashMask));
verifyTrue(testCase, islogical(diagnostics.fp08_6));
verifyTrue(testCase, islogical(diagnostics.fp08_7));
verifyTrue(testCase, islogical(diagnostics.eyeNeighborhood));
verifyTrue(testCase, islogical(diagnostics.lineSupport));

requiredGroups = {'manual_lash', 'fp08_6', 'fp08_7', ...
    'browEye_non_lash', 'eyeNeighborhood_non_lash', ...
    'manual_lash_lineSupport', 'fp08_6_lineSupport', ...
    'fp08_7_lineSupport'};
actualGroups = {diagnostics.groupStats.group};
verifyEqual(testCase, actualGroups, requiredGroups);
for index = 1:numel(diagnostics.groupStats)
    row = diagnostics.groupStats(index);
    verifyGreaterThan(testCase, row.count, 0);
    verifyTrue(testCase, isfinite(row.mean));
    verifyTrue(testCase, isfinite(row.median));
    verifyTrue(testCase, isfinite(row.p10));
    verifyTrue(testCase, isfinite(row.p25));
    verifyTrue(testCase, isfinite(row.p50));
    verifyTrue(testCase, isfinite(row.p75));
    verifyTrue(testCase, isfinite(row.p90));
end

verifyEqual(testCase, numel(diagnostics.comparisonStats), 6);
for index = 1:numel(diagnostics.comparisonStats)
    row = diagnostics.comparisonStats(index);
    verifyGreaterThan(testCase, row.positiveCount, 0);
    verifyGreaterThan(testCase, row.negativeCount, 0);
    verifyTrue(testCase, isfinite(row.auc));
    verifyTrue(testCase, isfinite(row.mannWhitneyU));
    verifyTrue(testCase, isfinite(row.rankBiserial));
end
verifyEqual(testCase, numel(diagnostics.continuityStats), 3);
for index = 1:numel(diagnostics.continuityStats)
    row = diagnostics.continuityStats(index);
    verifyGreaterThan(testCase, row.validPairCount, 0);
    verifyTrue(testCase, isfinite(row.meanAxialAngularDifference));
    verifyTrue(testCase, isfinite(row.medianAxialAngularDifference));
    verifyTrue(testCase, isfinite(row.p75AxialAngularDifference));
    verifyTrue(testCase, isfinite(row.p90AxialAngularDifference));
    verifyLessThanOrEqual(testCase, row.maxAxialAngularDifference, pi / 2);
end

requiredFiles = { ...
    'line_image.png', ...
    'gradient_magnitude.png', ...
    'tensor_coherence.png', ...
    'tensor_orientation.png', ...
    'coherence_manual_overlay.png', ...
    'coherence_08_6_fp_overlay.png', ...
    'coherence_08_7_fp_overlay.png', ...
    'orientation_manual_overlay.png', ...
    'orientation_08_6_fp_overlay.png', ...
    'orientation_08_7_fp_overlay.png', ...
    'coherence_histogram.png', ...
    'coherence_ecdf.png', ...
    'coherence_boxplot.png', ...
    'coherence_gradient_joint.png', ...
    'coherence_by_gradient_bin.png', ...
    'orientation_continuity_distribution.png', ...
    'lash_orientation_coherence_metrics.csv', ...
    'lash_orientation_coherence_group_stats.csv', ...
    'lash_orientation_continuity_stats.csv', ...
    'lash_orientation_coherence_gradient_bins.csv', ...
    'lash_orientation_coherence_diagnostic.mat'};
for index = 1:numel(requiredFiles)
    verifyTrue(testCase, isfile(fullfile(outputFolder, requiredFiles{index})), ...
        ['缺少 Issue 08.8 产物：' requiredFiles{index}]);
end

metricsTable = readtable(fullfile(outputFolder, ...
    'lash_orientation_coherence_metrics.csv'), 'TextType', 'char');
verifyEqual(testCase, height(metricsTable), 1);
requiredMetricColumns = { ...
    'manualVsFp086Auc', 'manualVsFp087Auc', ...
    'manualVsBrowEyeNonLashAuc', ...
    'lineSupportManualVsFp086Auc', ...
    'lineSupportManualVsFp087Auc', ...
    'manualVsFp086RankBiserial', ...
    'manualVsFp087RankBiserial', ...
    'gradientCoherencePearsonAll', ...
    'manualOrientationMeanAxialDifference', ...
    'fp08_6OrientationMeanAxialDifference', ...
    'fp08_7OrientationMeanAxialDifference'};
for index = 1:numel(requiredMetricColumns)
    name = requiredMetricColumns{index};
    verifyTrue(testCase, ismember(name, metricsTable.Properties.VariableNames), ...
        ['metrics.csv 缺少字段：' name]);
    verifyTrue(testCase, isfinite(metricsTable.(name)), ...
        ['metrics.csv 字段不是有限值：' name]);
end

groupTable = readtable(fullfile(outputFolder, ...
    'lash_orientation_coherence_group_stats.csv'), 'TextType', 'char');
verifyEqual(testCase, height(groupTable), 8);
requiredGroupColumns = {'group', 'count', 'mean', 'median', 'std', ...
    'p10', 'p25', 'p50', 'p75', 'p90'};
for index = 1:numel(requiredGroupColumns)
    verifyTrue(testCase, ismember(requiredGroupColumns{index}, ...
        groupTable.Properties.VariableNames));
end
verifyEqual(testCase, groupTable.count(strcmp(groupTable.group, ...
    'manual_lash')), 576);

gradientTable = readtable(fullfile(outputFolder, ...
    'lash_orientation_coherence_gradient_bins.csv'), 'TextType', 'char');
verifyEqual(testCase, height(gradientTable), 30);
verifyEqual(testCase, sort(unique(gradientTable.group)), ...
    {'fp08_6'; 'fp08_7'; 'manual_lash'});
end

function options = fixedOptions()
options = struct( ...
    'productionRoot', 'E:\image_beauty', ...
    'baselinePath', ...
    'C:\Users\JJiio\AppData\Local\Temp\image_beauty_issue02_probe\77_v32_probe.mat', ...
    'sourceDiagnosticPath', ...
    'C:\Users\JJiio\AppData\Local\Temp\image_beauty_issue08_7_lash_angle_grouped_20260919\lash_angle_grouped_diagnostic.mat', ...
    'faceBox', [95, 79, 286, 372], ...
    'browEyeRoi', [165, 205, 150, 100], ...
    'lashRoi', [102, 248, 177, 48]);
end
