function tests = testLashSoftContinuityCandidate
%TESTLASHSOFTCONTINUITYCANDIDATE 验证 Issue 08.4 局部连续性候选。
tests = functiontests(localfunctions);
end

function setupOnce(~)
testRoot = fileparts(mfilename('fullpath'));
projectRoot = fileparts(testRoot);
addpath(fullfile(projectRoot, 'src'), '-begin');
addpath(testRoot, '-begin');
end

function testRejectsNonFixedFixtureBeforeProductionRun(testCase)
options = fixedOptions();
options.lashRoi = [103, 248, 177, 48];
verifyError(testCase, @() diagnoseLashSoftContinuityCandidate( ...
    'not-an-image.png', tempdir, options), ...
    'diagnoseLashSoftContinuityCandidate:NonFixedFixture');
end

function testFixed77CandidateWritesRequiredArtifacts(testCase)
projectRoot = fileparts(fileparts(mfilename('fullpath')));
inputPath = fullfile(projectRoot, '人脸', '人脸', '77.png');
outputFolder = fullfile(tempdir, ...
    'image_beauty_issue08_4_lash_soft_continuity_20260919');
[summary, diagnostics] = diagnoseLashSoftContinuityCandidate( ...
    inputPath, outputFolder, fixedOptions());

verifyTrue(testCase, summary.completed);
verifyEqual(testCase, summary.issue, '08.4');
verifyEqual(testCase, summary.case, 'requiresVisualReview');
verifyEqual(testCase, summary.faceBox, [95, 79, 286, 372]);
verifyEqual(testCase, summary.browEye, [165, 205, 150, 100]);
verifyEqual(testCase, summary.lashRoi, [102, 248, 177, 48]);
verifyEqual(testCase, summary.manualLashMaskId, '77-manual-lash-v1');
verifyTrue(testCase, summary.manualLashMaskIndependent);
verifyTrue(testCase, summary.manualLashMaskFixed);
verifyFalse(testCase, summary.runtimeCacheReused);
verifyTrue(testCase, summary.sameMaskRun);
verifyTrue(testCase, summary.baseToneWhiteningFrozen);
verifyTrue(testCase, summary.candidateOnlySoftLash);
verifyEqual(testCase, summary.existingPeriocularSupportSource, ...
    'texture.eyeNeighborhood');
verifyGreaterThanOrEqual(testCase, summary.existingLashScale, 2);
verifyLessThanOrEqual(testCase, summary.existingLashScale, 5);
verifyLessThanOrEqual(testCase, ...
    summary.originalReconstructionMaxError, summary.reconstructionTolerance);
verifyLessThanOrEqual(testCase, ...
    summary.eyeDetailAggregationMaxError, summary.formulaTolerance);
verifyLessThanOrEqual(testCase, ...
    summary.baselineComposeMaxRgbDifference, summary.reconstructionTolerance);
verifyEqual(testCase, summary.hardProtectionMaskChangedPixels, 0);
verifyEqual(testCase, summary.hardCoreChangedPixels, 0);
% v3.3 baseline 已包含生产端局部闭合；候选可以是 no-op，但不能增加
% Repair 作用量，Fine 允许 1% 以内的 uint8/浮点量化级波动。
verifyGreaterThanOrEqual(testCase, ...
    summary.metrics.manualAddedSoftProtection.sum, 0);
verifyGreaterThanOrEqual(testCase, ...
    summary.metrics.repairFineAbsActionReduction, ...
    -.01 * max(summary.metrics.baselineRepairFineAbsAction.sum, eps));
verifyGreaterThanOrEqual(testCase, ...
    summary.metrics.repairMidAbsActionReduction, 0);
verifyLessThan(testCase, ...
    summary.metrics.candidateFinalRgbDistanceToOriginal.mean, ...
    summary.metrics.baselineFinalRgbDistanceToOriginal.mean);
verifyLessThan(testCase, ...
    summary.metrics.candidateFinalLuminanceDistanceToOriginal.mean, ...
    summary.metrics.baselineFinalLuminanceDistanceToOriginal.mean);
verifyTrue(testCase, summary.caseAssessment.requiresVisualReview);

expectedLash = max(diagnostics.baselineLashProtection, ...
    diagnostics.softClosedLashProtection .* ...
    diagnostics.existingPeriocularSupport);
verifyEqual(testCase, diagnostics.candidateLashProtection, expectedLash, ...
    'AbsTol', summary.formulaTolerance);
verifyGreaterThanOrEqual(testCase, ...
    diagnostics.candidateLashProtection(:), ...
    diagnostics.baselineLashProtection(:));
verifyEqual(testCase, diagnostics.candidateTextureDiagnostics.lashCore, ...
    diagnostics.baselineTextureDiagnostics.lashCore);
verifyEqual(testCase, diagnostics.candidateBeautyMasks.hardProtectionMask, ...
    diagnostics.baselineBeautyMasks.hardProtectionMask, 'AbsTol', 0);
verifyEqual(testCase, diagnostics.candidateBeautyMasks.structureProtectionMask, ...
    diagnostics.baselineBeautyMasks.structureProtectionMask, 'AbsTol', 0);
verifyEqual(testCase, diagnostics.candidateBeautyMasks.textureProtectionMask, ...
    max(diagnostics.baselineBeautyMasks.textureProtectionMask, ...
    diagnostics.candidateTextureDiagnostics.eyeDetailProtection), ...
    'AbsTol', summary.formulaTolerance);

requiredFiles = { ...
    'baseline_lash_protection.png', ...
    'candidate_lash_protection.png', ...
    'added_soft_protection.png', ...
    'manual_vs_added_soft_protection.png', ...
    'baseline_repair_fine_delta.png', ...
    'candidate_repair_fine_delta.png', ...
    'baseline_repair_mid_delta.png', ...
    'candidate_repair_mid_delta.png', ...
    'baseline_final_lash.png', ...
    'candidate_final_lash.png', ...
    'original_final_candidate_comparison.png', ...
    'lash_soft_continuity_candidate_metrics.csv', ...
    'lash_soft_continuity_candidate_diagnostic.mat'};
for index = 1:numel(requiredFiles)
    verifyTrue(testCase, isfile(fullfile(outputFolder, requiredFiles{index})), ...
        ['缺少 Issue 08.4 产物：' requiredFiles{index}]);
end

metricsTable = readtable(fullfile(outputFolder, ...
    'lash_soft_continuity_candidate_metrics.csv'), 'TextType', 'char');
verifyEqual(testCase, height(metricsTable), 1);
verifyTrue(testCase, ismember('manualAddedSoftProtectionSum', ...
    metricsTable.Properties.VariableNames));
verifyTrue(testCase, ismember('repairFineAbsActionReduction', ...
    metricsTable.Properties.VariableNames));
verifyTrue(testCase, ismember('repairMidAbsActionReduction', ...
    metricsTable.Properties.VariableNames));
verifyTrue(testCase, ismember('candidateHardProtectedPixelsChangedCount', ...
    metricsTable.Properties.VariableNames));
verifyTrue(testCase, isfinite(metricsTable.manualAddedSoftProtectionSum));
verifyTrue(testCase, isfinite(metricsTable.browEyeOutsideManualAddedSoftProtectionSum));
verifyTrue(testCase, isfinite(metricsTable.baselineRepairFineAbsActionSum));
verifyTrue(testCase, isfinite(metricsTable.candidateRepairFineAbsActionSum));
verifyTrue(testCase, isfinite(metricsTable.baselineRepairMidAbsActionSum));
verifyTrue(testCase, isfinite(metricsTable.candidateRepairMidAbsActionSum));
verifyEqual(testCase, metricsTable.hardProtectionMaskChangedPixels, 0);
end

function options = fixedOptions()
options = struct( ...
    'productionRoot', 'E:\image_beauty', ...
    'baselinePath', ...
    'C:\Users\JJiio\AppData\Local\Temp\image_beauty_issue02_probe\77_v32_probe.mat', ...
    'faceBox', [95, 79, 286, 372], ...
    'browEyeRoi', [165, 205, 150, 100], ...
    'lashRoi', [102, 248, 177, 48], ...
    'smoothingStrength', 100, ...
    'whiteningStrength', 15);
end
