function tests = testDenseBlemishField
%TESTDENSEBLEMISHFIELD 验证连续瑕疵包络、保护排除和参考覆盖门。
tests = functiontests(localfunctions);
end

function setupOnce(~)
projectRoot = fileparts(fileparts(mfilename('fullpath')));
addpath(fullfile(projectRoot, 'src'));
end

function testDenseFieldCoversContinuousEvidence(testCase)
[image, frequency, beautyMasks, protection, denseArea] = ...
    makeDenseEvidenceFixture;
[~, diagnostics] = beauty.buildBlemishMap( ...
    image, frequency, beautyMasks, protection);

verifyGreaterThan(testCase, nnz(diagnostics.denseBlemishField), 0, ...
    '连续高置信瑕疵证据必须生成 denseBlemishField。');
verifyGreaterThan(testCase, nnz(diagnostics.denseBlemishField(denseArea)), ...
    200, 'dense field 必须覆盖大片连续证据，而不是只保留孤立种子。');
verifyLessThanOrEqual(testCase, max(diagnostics.denseBlemishField(:)), 1);
verifyGreaterThanOrEqual(testCase, min(diagnostics.denseBlemishField(:)), 0);
end

function testDenseFieldRejectsProtectedStructures(testCase)
[image, frequency, beautyMasks, protection, ~, forbidden] = ...
    makeDenseEvidenceFixture;
[~, diagnostics] = beauty.buildBlemishMap( ...
    image, frequency, beautyMasks, protection);

names = fieldnames(forbidden);
for index = 1:numel(names)
    region = forbidden.(names{index});
    verifyEqual(testCase, nnz(diagnostics.denseBlemishField(region)), 0, ...
        sprintf('%s 不得进入 denseBlemishField。', names{index}));
end

function testFaceSurfacePriorRejectsBodyDenseEvidence(testCase)
[image, frequency, beautyMasks, protection, denseArea] = ...
    makeDenseEvidenceFixture;
faceMask = false(size(denseArea));
faceMask(1:60, 1:80) = true;
bodyArea = false(size(denseArea));
bodyArea(62:75, 72:95) = true;
frequency.fine(bodyArea) = .20;
frequency.mid(bodyArea) = .12;
beautyMasks.faceSkinMask = double(faceMask);
[~, diagnostics] = beauty.buildBlemishMap( ...
    image, frequency, beautyMasks, protection);
verifyEqual(testCase, nnz(diagnostics.denseBlemishField(bodyArea)), 0, ...
    'bodySkin/手臂高瑕疵证据不得进入 face-only dense field。');

[repairFrequency, repairMasks, repairProtection, repairInput] = ...
    makeDenseRepairFixture;
repairFaceMask = false(size(repairFrequency.base));
repairFaceMask(20:90, 30:125) = true;
repairBodyArea = false(size(repairFrequency.base));
repairBodyArea(95:110, 120:145) = true;
repairMasks.faceSkinMask = double(repairFaceMask);
repairInput.denseBlemishField = zeros(size(repairFrequency.base));
repairInput.denseBlemishField(repairBodyArea) = 1;
repairInput.blemishMap(repairBodyArea) = .95;
contract = beauty.repairStageContract(repairProtection, ...
    repairInput.blemishMap);
[~, repairDiagnostics] = beauty.repairSkinBlemishes( ...
    repairFrequency, repairMasks, repairInput, 100, contract);
verifyEqual(testCase, repairDiagnostics.denseAllowedWeight(repairBodyArea), ...
    zeros(nnz(repairBodyArea), 1), 'AbsTol', 0, ...
    'bodySkin/手臂不得获得 dense Repair 权重。');
verifyEqual(testCase, ...
    repairDiagnostics.denseSurfaceReferenceReliability(repairBodyArea), ...
    zeros(nnz(repairBodyArea), 1), 'AbsTol', 0, ...
    'bodySkin/手臂不得进入全脸曲面参考池。');
end
end

function testReferenceCoverageRejectsInsufficientSupport(testCase)
[frequency, beautyMasks, protection, blemishInput] = makeReferenceFixture;
contract = beauty.repairStageContract(protection, blemishInput.blemishMap);
[repaired, diagnostics] = beauty.repairSkinBlemishes( ...
    frequency, beautyMasks, blemishInput, 100, contract);

lowCoverage = diagnostics.referenceWeight > eps & ...
    diagnostics.referenceCoverage < .05;
verifyTrue(testCase, any(lowCoverage(:)), ...
    'fixture 必须包含非零但不足的归一化参考覆盖。');
verifyEqual(testCase, diagnostics.fineWeight(lowCoverage), ...
    zeros(nnz(lowCoverage), 1), 'AbsTol', 0);
verifyEqual(testCase, diagnostics.mediumWeight(lowCoverage), ...
    zeros(nnz(lowCoverage), 1), 'AbsTol', 0);
verifyEqual(testCase, diagnostics.chromaWeight(lowCoverage), ...
    zeros(nnz(lowCoverage), 1), 'AbsTol', 0);
verifyEqual(testCase, diagnostics.denseAllowedWeight(lowCoverage), ...
    zeros(nnz(lowCoverage), 1), 'AbsTol', 0);
verifyEqual(testCase, repaired.fine, frequency.fine, 'AbsTol', 0);
verifyEqual(testCase, repaired.mid, frequency.mid, 'AbsTol', 0);
end

function testZeroTo75KeepsCompactRepairBehavior(testCase)
[frequency, beautyMasks, protection, blemishInput] = makeReferenceFixture;
imageSize = size(frequency.base);
% 把 dense field 放在远离紧凑斑点的普通皮肤区域；它只能提供后续
% 大面积消费者的诊断输入，不得在 0--75 档改变现有 compact Repair。
blemishInput.denseBlemishField = zeros(imageSize);
blemishInput.denseBlemishField(55:75, 60:80) = 1;
contract = beauty.repairStageContract(protection, blemishInput.blemishMap);
plainInput = rmfield(blemishInput, 'denseBlemishField');

for strength = [0, 25, 50, 75]
    [plainFrequency, plainDiagnostics] = beauty.repairSkinBlemishes( ...
        frequency, beautyMasks, plainInput, strength, contract);
    [denseFrequency, denseDiagnostics] = beauty.repairSkinBlemishes( ...
        frequency, beautyMasks, blemishInput, strength, contract);
    verifyEqual(testCase, denseFrequency.fine, plainFrequency.fine, ...
        'AbsTol', 0, '0--75 档 Fine 行为不得因 dense field 改变。');
    verifyEqual(testCase, denseFrequency.mid, plainFrequency.mid, ...
        'AbsTol', 0, '0--75 档 Mid 行为不得因 dense field 改变。');
    verifyEqual(testCase, denseDiagnostics.fineWeight, ...
        plainDiagnostics.fineWeight, 'AbsTol', 0);
    verifyEqual(testCase, denseDiagnostics.mediumWeight, ...
        plainDiagnostics.mediumWeight, 'AbsTol', 0);
    verifyEqual(testCase, denseDiagnostics.denseAllowedWeight, ...
        zeros(imageSize), 'AbsTol', 0, ...
        '0--75 档 denseAllowedWeight 必须保持关闭。');
end
end

function testDenseRepairUsesIndependentHighEndBranch(testCase)
[frequency, beautyMasks, protection, blemishInput] = ...
    makeDenseRepairFixture;
contract = beauty.repairStageContract(protection, blemishInput.blemishMap);
plainInput = rmfield(blemishInput, 'denseBlemishField');

[plain75, plainDiagnostics75] = beauty.repairSkinBlemishes( ...
    frequency, beautyMasks, plainInput, 75, contract);
[dense75, denseDiagnostics75] = beauty.repairSkinBlemishes( ...
    frequency, beautyMasks, blemishInput, 75, contract);
[dense100, denseDiagnostics100] = beauty.repairSkinBlemishes( ...
    frequency, beautyMasks, blemishInput, 100, contract);

verifyEqual(testCase, dense75.fine, plain75.fine, 'AbsTol', 0);
verifyEqual(testCase, dense75.mid, plain75.mid, 'AbsTol', 0);
verifyEqual(testCase, denseDiagnostics75.fineWeight, ...
    plainDiagnostics75.fineWeight, 'AbsTol', 0);
verifyEqual(testCase, denseDiagnostics75.denseAllowedWeight, ...
    zeros(size(frequency.base)), 'AbsTol', 0);
verifyGreaterThan(testCase, nnz(denseDiagnostics100.denseAllowedWeight), 0, ...
    '高档 dense 分支必须获得独立作用权重。');
verifyGreaterThan(testCase, nnz(denseDiagnostics100.denseMidWeight), 0);
verifyGreaterThan(testCase, nnz(denseDiagnostics100.denseFineWeight), 0);
verifyGreaterThan(testCase, nnz(denseDiagnostics100.denseChromaWeight), 0);
verifyGreaterThan(testCase, nnz(denseDiagnostics100.denseMediumCorrection), 0);
verifyTrue(testCase, any(dense100.mid(:) ~= frequency.mid(:)));
verifyTrue(testCase, any(dense100.fine(:) ~= frequency.fine(:)));

protected = false(size(frequency.base));
protected(50:60, 75:85) = true;
protectedInput = blemishInput;
protectedInput.denseBlemishField(protected) = 1;
protectedContract = contract;
protectedContract.hard(protected) = 1;
[~, protectedDiagnostics] = beauty.repairSkinBlemishes( ...
    frequency, beautyMasks, protectedInput, 100, protectedContract);
verifyEqual(testCase, protectedDiagnostics.denseAllowedWeight(protected), ...
    zeros(nnz(protected), 1), 'AbsTol', 0, ...
    'hard protection 不得被 dense 分支放宽。');
end

function testDenseConsumersDriveToneAndBoundedBase(testCase)
[frequency, beautyMasks, protection, blemishInput] = ...
    makeDenseRepairFixture;
contract = beauty.repairStageContract(protection, blemishInput.blemishMap);
[~, repairDiagnostics] = beauty.repairSkinBlemishes( ...
    frequency, beautyMasks, blemishInput, 100, contract);

image = uint8(150 * ones([size(frequency.base), 3]));
image(50:60, 75:85, 1) = 205;
image(50:60, 75:85, 2) = 125;
image(50:60, 75:85, 3) = 105;
toneContract = struct( ...
    'tone', zeros(size(frequency.base)), ...
    'hard', zeros(size(frequency.base)), ...
    'structureGate', ones(size(frequency.base)), ...
    'featureGate', ones(size(frequency.base)), ...
    'uniformFeatureGate', ones(size(frequency.base)), ...
    'candidateChromaGate', ones(size(frequency.base)));
[~, toneDiagnostics] = beauty.normalizeSkinTone( ...
    image, frequency, beautyMasks, repairDiagnostics, 100, toneContract);
verifyGreaterThan(testCase, nnz(toneDiagnostics.denseToneWeight), 0, ...
    'dense 诊断必须进入高档色度修正。');
verifyGreaterThan(testCase, max(abs(toneDiagnostics.deltaCb(:))) + ...
    max(abs(toneDiagnostics.deltaCr(:))), 0);

baseContract = struct( ...
    'hard', zeros(size(frequency.base)), ...
    'target', struct('baseLuminance', zeros(size(frequency.base))), ...
    'support', struct('baseLuminance', zeros(size(frequency.base))), ...
    'regionBandGate', ones(size(frequency.base)));
[~, baseDiagnostics] = beauty.evenSkinLuminance( ...
    frequency, beautyMasks, 100, baseContract, repairDiagnostics);
verifyGreaterThan(testCase, nnz(baseDiagnostics.denseBaseWeight), 0, ...
    'dense 诊断必须进入高档 Base 支持。');
verifyLessThanOrEqual(testCase, max(abs(baseDiagnostics.baseDelta(:))), ...
    .03 + eps, 'Base 亮度增量必须保持限幅。');
end

function testHighEndToneLimitAndDarkStructureProtection(testCase)
[frequency, beautyMasks, protection, blemishInput] = ...
    makeDenseRepairFixture;
repairContract = beauty.repairStageContract(protection, ...
    blemishInput.blemishMap);
[~, repairDiagnostics] = beauty.repairSkinBlemishes( ...
    frequency, beautyMasks, blemishInput, 100, repairContract);

image = uint8(150 * ones([size(frequency.base), 3]));
image(50:60, 75:85, 1) = 205;
image(50:60, 75:85, 2) = 125;
image(50:60, 75:85, 3) = 105;
image(48:62, 73:87, :) = max(image(48:62, 73:87, :) - 40, 0);
zero = zeros(size(frequency.base));
one = ones(size(frequency.base));
toneContract = struct( ...
    'tone', zero, ...
    'hard', zero, ...
    'structureGate', one, ...
    'featureGate', one, ...
    'uniformFeatureGate', one, ...
    'candidateChromaGate', one);
[tone100, toneDiagnostics100] = beauty.normalizeSkinTone( ...
    image, frequency, beautyMasks, repairDiagnostics, 100, toneContract);

verifyLessThanOrEqual(testCase, max(abs(toneDiagnostics100.deltaCb(:))), ...
    toneDiagnostics100.toneChromaDeltaLimit + eps, ...
    '高档 Tone 的 Cb 改变量必须受限。');
verifyLessThanOrEqual(testCase, max(abs(toneDiagnostics100.deltaCr(:))), ...
    toneDiagnostics100.toneChromaDeltaLimit + eps, ...
    '高档 Tone 的 Cr 改变量必须受限。');
rgbDelta = max(abs(double(tone100.outputImage) - double(image)), [], 3);
rgbLimit = 255 * 1.772 * toneDiagnostics100.toneChromaDeltaLimit + 1;
verifyLessThanOrEqual(testCase, max(rgbDelta(:)), rgbLimit, ...
    '高档 Tone 的 RGB 单通道改变量必须由色度限幅约束。');
verifyLessThan(testCase, min(toneDiagnostics100.darkStructureGate(:)), 1, ...
    '暗结构保护门必须在暗部边缘生效。');

protected = false(size(zero));
protected(50:60, 75:85) = true;
protectedContract = toneContract;
protectedContract.featureGate(protected) = 0;
[~, protectedDiagnostics] = beauty.normalizeSkinTone( ...
    image, frequency, beautyMasks, repairDiagnostics, 100, protectedContract);
verifyEqual(testCase, protectedDiagnostics.deltaCb(protected), ...
    zeros(nnz(protected), 1), 'AbsTol', 0, ...
    'Tone feature 保护区不得产生 Cb 改动。');
verifyEqual(testCase, protectedDiagnostics.deltaCr(protected), ...
    zeros(nnz(protected), 1), 'AbsTol', 0, ...
    'Tone feature 保护区不得产生 Cr 改动。');

plainInput = rmfield(blemishInput, 'denseBlemishField');
[plain75, ~] = beauty.normalizeSkinTone( ...
    image, frequency, beautyMasks, plainInput, 75, toneContract);
[dense75, ~] = beauty.normalizeSkinTone( ...
    image, frequency, beautyMasks, blemishInput, 75, toneContract);
verifyEqual(testCase, dense75.outputCb, plain75.outputCb, 'AbsTol', 0, ...
    '75 档不得因高档 Tone 运行期证据改变。');
verifyEqual(testCase, dense75.outputCr, plain75.outputCr, 'AbsTol', 0, ...
    '75 档不得因高档 Tone 运行期证据改变。');
end

function [image, frequency, beautyMasks, protection, denseArea, forbidden] = ...
        makeDenseEvidenceFixture
imageSize = [80, 100];
image = uint8(ones([imageSize, 3]) * 150);
[columns, rows] = meshgrid(1:imageSize(2), 1:imageSize(1));
denseArea = rows >= 16 & rows <= 55 & columns >= 20 & columns <= 65;
seedArea = denseArea & mod(rows + columns, 4) == 0;

frequency = struct( ...
    'sourceLuminance', .5 * ones(imageSize), ...
    'base', .5 * ones(imageSize), ...
    'mid', zeros(imageSize), ...
    'fine', zeros(imageSize), ...
    'imageSize', [imageSize, 3], ...
    'faceScale', 60, ...
    'faceBox', [20, 10, 60, 60]);
frequency.fine(seedArea) = .20;
frequency.mid(seedArea) = .12;

beautyMasks = struct( ...
    'skinMask', ones(imageSize), ...
    'hardProtectionMask', zeros(imageSize), ...
    'textureProtectionMask', zeros(imageSize), ...
    'structureProtectionMask', zeros(imageSize), ...
    'protectionMask', zeros(imageSize));
zero = zeros(imageSize);
protection = struct( ...
    'hard', zero, ...
    'target', struct('repairFine', zero, 'repairMid', zero), ...
    'support', struct('repairFine', zero, 'repairMid', zero), ...
    'regionBandFine', zero, ...
    'regionBandMid', zero, ...
    'regionBandBase', zero, ...
    'regionBandTone', zero, ...
    'regionBandWhitening', zero);

forbidden = struct();
forbidden.hard = false(imageSize);
forbidden.hard(25:30, 32:38) = true;
protection.hard(forbidden.hard) = 1;
beautyMasks.hardProtectionMask(forbidden.hard) = 1;

forbidden.longLine = false(imageSize);
forbidden.longLine(40:42, 20:65) = true;
beautyMasks.structureProtectionMask(forbidden.longLine) = .80;

forbidden.lash = false(imageSize);
forbidden.lash(18:22, 22:28) = true;
protection.regionBandFine(forbidden.lash) = .95;

forbidden.brow = false(imageSize);
forbidden.brow(20:25, 50:58) = true;
protection.support.repairFine(forbidden.brow) = .80;

forbidden.alar = false(imageSize);
forbidden.alar(35:42, 45:50) = true;
protection.regionBandMid(forbidden.alar) = .85;
protection.support.repairMid(forbidden.alar) = .80;

forbidden.earRing = false(imageSize);
forbidden.earRing(45:52, 58:65) = true;
protection.regionBandBase(forbidden.earRing) = .95;
end

function [frequency, beautyMasks, protection, blemishInput] = ...
        makeReferenceFixture
imageSize = [90, 100];
frequency = struct( ...
    'base', zeros(imageSize), ...
    'mid', .03 * ones(imageSize), ...
    'fine', .06 * ones(imageSize), ...
    'sourceLuminance', .09 * ones(imageSize), ...
    'imageSize', [imageSize, 3], ...
    'faceScale', 40, ...
    'faceBox', [1, 1, 40, 40]);
frequency.fine(20:22, 20:22) = .20;
frequency.mid(20:22, 20:22) = .10;

beautyMasks = struct( ...
    'skinMask', ones(imageSize), ...
    'strengthMap', ones(imageSize), ...
    'nonFaceStrengthMap', zeros(imageSize));
zero = zeros(imageSize);
protection = struct( ...
    'hard', zero, ...
    'target', struct('repairFine', zero, 'repairMid', zero), ...
    'support', struct('repairFine', zero, 'repairMid', zero), ...
    'noseMidProtection', zero, ...
    'regionBandFine', zero, ...
    'regionBandMid', zero);
protection.regionBandFine(5, 5) = .95;

blemishMap = zeros(imageSize);
blemishMap(20:22, 20:22) = .95;
denseBlemishField = ones(imageSize);
% 只保留一个参考像素，令 referenceWeight > 0 但归一化 coverage 不足。
denseBlemishField(19, 19) = 0;
blemishInput = struct('blemishMap', blemishMap, ...
    'denseBlemishField', denseBlemishField);
end

function [frequency, beautyMasks, protection, blemishInput] = ...
        makeDenseRepairFixture
imageSize = [120, 160];
frequency = struct( ...
    'base', .50 * ones(imageSize), ...
    'mid', .02 * ones(imageSize), ...
    'fine', .03 * ones(imageSize), ...
    'sourceLuminance', .50 * ones(imageSize), ...
    'imageSize', [imageSize, 3], ...
    'faceScale', 100, ...
    'faceBox', [20, 10, 100, 100]);
frequency.mid(35:80, 45:100) = .12;
frequency.fine(35:80, 45:100) = .16;

beautyMasks = struct( ...
    'skinMask', ones(imageSize), ...
    'strengthMap', ones(imageSize), ...
    'nonFaceStrengthMap', zeros(imageSize));
zero = zeros(imageSize);
protection = struct( ...
    'hard', zero, ...
    'target', struct('repairFine', zero, 'repairMid', zero), ...
    'support', struct('repairFine', zero, 'repairMid', zero), ...
    'noseMidProtection', zero, ...
    'regionBandFine', zero, ...
    'regionBandMid', zero);
% 非零 policy band 只用于启用 compact policy；dense 区域本身不应
% 因此被拆入 compact blob。
protection.regionBandFine(1, 1) = .95;
blemishMap = zeros(imageSize);
blemishMap(35:80, 45:100) = .95;
denseBlemishField = zeros(imageSize);
denseBlemishField(35:80, 45:100) = 1;
blemishInput = struct('blemishMap', blemishMap, ...
    'denseBlemishField', denseBlemishField);
end
