function tests = testLashAngleGroupedReconstruction
%TESTLASHANGLEGROUPEDRECONSTRUCTION 验证 Issue 08.7 角度分组重构。
tests = functiontests(localfunctions);
end

function setupOnce(~)
testRoot = fileparts(mfilename('fullpath'));
projectRoot = fileparts(testRoot);
addpath(fullfile(projectRoot, 'src'), '-begin');
addpath(testRoot, '-begin');
end

function testRejectsNonFixedFixtureBeforeProductionRun(testCase)
options = fixedOptions();
options.lashRoi = [103, 248, 177, 48];
verifyError(testCase, @() diagnoseLashAngleGroupedReconstruction( ...
    'not-an-image.png', tempdir, options), ...
    'diagnoseLashAngleGroupedReconstruction:NonFixedFixture');
end

function testFixed77AngleGroupedCandidateWritesRequiredArtifacts(testCase)
projectRoot = fileparts(fileparts(mfilename('fullpath')));
inputPath = fullfile(projectRoot, '人脸', '人脸', '77.png');
outputFolder = fullfile(tempdir, ...
    'image_beauty_issue08_7_lash_angle_grouped_20260919');
[summary, diagnostics] = diagnoseLashAngleGroupedReconstruction( ...
    inputPath, outputFolder, fixedOptions());

verifyTrue(testCase, summary.completed);
verifyEqual(testCase, summary.issue, '08.7');
verifyEqual(testCase, summary.case, 'requiresVisualReview');
verifyEqual(testCase, summary.faceBox, [95, 79, 286, 372]);
verifyEqual(testCase, summary.browEye, [165, 205, 150, 100]);
verifyEqual(testCase, summary.lashRoi, [102, 248, 177, 48]);
verifyEqual(testCase, summary.manualLashMaskId, '77-manual-lash-v1');
verifyTrue(testCase, summary.manualLashMaskIndependent);
verifyTrue(testCase, summary.manualLashMaskFixed);
verifyFalse(testCase, summary.manualTruthUsedForGeneration);
verifyFalse(testCase, summary.runtimeCacheReused);
verifyTrue(testCase, summary.sameMaskRun);
verifyTrue(testCase, summary.baseToneWhiteningFrozen);
verifyTrue(testCase, summary.onlyLashSupportGeometryChanged);
verifyEqual(testCase, summary.angles, 0:15:165);
verifyLessThanOrEqual(testCase, summary.evidenceReconstructionMaxError, 1e-12);
verifyLessThanOrEqual(testCase, summary.lineSupportFromAngleMaxError, 1e-12);
verifyEqual(testCase, summary.hardProtectionMaskChangedPixels, 0);
verifyEqual(testCase, summary.candidate086HardProtectionMaskChangedPixels, 0);
verifyEqual(testCase, summary.hardCoreChangedPixels, 0);
verifyTrue(testCase, summary.caseAssessment.requiresVisualReview);
verifyTrue(testCase, summary.repairAssessment.requiresVisualReview);

angleCount = numel(summary.angles);
verifyEqual(testCase, numel(diagnostics.evidence.lineResponse), angleCount);
verifyEqual(testCase, numel(diagnostics.angleGrouped.response), angleCount);
verifyEqual(testCase, numel(diagnostics.angleGrouped.reconstructed), angleCount);

responseUnion = false(size(diagnostics.evidence.lineSupport));
for angleIndex = 1:angleCount
    response = diagnostics.evidence.lineResponse{angleIndex};
    verifyEqual(testCase, response, diagnostics.angleGrouped.response{angleIndex});
    responseUnion = responseUnion | response;
    reconstructed = diagnostics.angleGrouped.reconstructed{angleIndex};
    allowed = diagnostics.angleGrouped.allowedEvidence{angleIndex};
    seed = diagnostics.angleGrouped.seed{angleIndex};
    verifyFalse(testCase, any(reconstructed(:) & ~allowed(:)));
    verifyFalse(testCase, any(seed(:) & ~allowed(:)));
    verifyFalse(testCase, any(seed(:) & ~response(:)));
end
verifyEqual(testCase, responseUnion, diagnostics.evidence.lineSupport);
verifyEqual(testCase, diagnostics.candidate086GeometrySeed, ...
    imreconstruct(diagnostics.evidence.detectorSeed & ...
    diagnostics.evidence.allowedEvidence, diagnostics.evidence.allowedEvidence, 8));
expected087 = false(size(diagnostics.candidate087GeometrySeed));
for angleIndex = 1:angleCount
    expected087 = expected087 | diagnostics.angleGrouped.reconstructed{angleIndex};
end
verifyEqual(testCase, diagnostics.candidate087GeometrySeed, expected087);
verifyEqual(testCase, diagnostics.angleGrouped.angleStats.finalUnionPixels, ...
    nnz(expected087));

expectedSoft087 = makeExpectedSoftMask(diagnostics.candidate087GeometrySeed, ...
    summary.softRadius, summary.softPeak);
expectedSoft087(~diagnostics.evidence.eyeNeighborhood) = 0;
expectedSoft087 = min(max(double(expectedSoft087), 0), 1);
verifyEqual(testCase, diagnostics.candidate087LashProtection, expectedSoft087, ...
    'AbsTol', 1e-12);
verifyEqual(testCase, diagnostics.candidate087Support, ...
    diagnostics.candidate087LashProtection > 0);
verifyEqual(testCase, diagnostics.candidate086Support, ...
    diagnostics.candidate086LashProtection > 0);
verifyEqual(testCase, diagnostics.candidate087TextureDiagnostics.lashCore, ...
    diagnostics.baselineTextureDiagnostics.lashCore);
verifyEqual(testCase, diagnostics.candidate087BeautyMasks.hardProtectionMask, ...
    diagnostics.baselineBeautyMasks.hardProtectionMask, 'AbsTol', 0);
verifyEqual(testCase, diagnostics.candidate087BeautyMasks.structureProtectionMask, ...
    diagnostics.baselineBeautyMasks.structureProtectionMask, 'AbsTol', 0);

for group = {'baseline', 'candidate084', 'candidate086', 'candidate087'}
    metrics = summary.metrics.(group{1});
    verifyEqual(testCase, metrics.truePositivePixels + ...
        metrics.falseNegativePixels, summary.manualLashMaskPixels);
    verifyEqual(testCase, metrics.truePositivePixels + ...
        metrics.falsePositivePixels, metrics.supportPixels);
    verifyTrue(testCase, isfinite(metrics.recall));
    verifyTrue(testCase, isfinite(metrics.precision));
end
verifyEqual(testCase, ...
    summary.metrics.candidate087RepairFineAbsAction.sum, ...
    sum(abs(diagnostics.candidate087RepairFineDelta( ...
    diagnostics.manualLashMask))), 'AbsTol', 1e-12);
verifyEqual(testCase, ...
    summary.metrics.candidate087RepairMidAbsAction.sum, ...
    sum(abs(diagnostics.candidate087RepairMidDelta( ...
    diagnostics.manualLashMask))), 'AbsTol', 1e-12);

requiredFiles = { ...
    'original_lash.png', ...
    'support_08_4.png', ...
    'support_08_6.png', ...
    'support_08_7_angle_grouped.png', ...
    'manual_vs_08_6.png', ...
    'manual_vs_08_7.png', ...
    'false_positive_08_6.png', ...
    'false_positive_08_7.png', ...
    'false_negative_08_6.png', ...
    'false_negative_08_7.png', ...
    'angle_response_overview.png', ...
    'angle_reconstruction_overview.png', ...
    'repair_fine_08_6.png', ...
    'repair_fine_08_7.png', ...
    'repair_mid_08_6.png', ...
    'repair_mid_08_7.png', ...
    'final_08_4.png', ...
    'final_08_6.png', ...
    'final_08_7.png', ...
    'support_geometry_comparison.png', ...
    'final_angle_grouped_comparison.png', ...
    'lash_angle_grouped_metrics.csv', ...
    'lash_angle_grouped_per_angle_metrics.csv', ...
    'lash_angle_grouped_diagnostic.mat'};
for angle = 0:15:165
    requiredFiles{end + 1} = sprintf('line_response_angle_%03d.png', angle);
    requiredFiles{end + 1} = sprintf('reconstruction_angle_%03d.png', angle);
end
for index = 1:numel(requiredFiles)
    verifyTrue(testCase, isfile(fullfile(outputFolder, requiredFiles{index})), ...
        ['缺少 Issue 08.7 产物：' requiredFiles{index}]);
end

metricsTable = readtable(fullfile(outputFolder, ...
    'lash_angle_grouped_metrics.csv'), 'TextType', 'char');
verifyEqual(testCase, height(metricsTable), 1);
requiredColumns = { ...
    'baselineRecall', 'candidate084Recall', 'candidate086Recall', ...
    'candidate087Recall', 'baselinePrecision', 'candidate084Precision', ...
    'candidate086Precision', 'candidate087Precision', ...
    'candidate087PrecisionImproved', 'candidate087RecallNotLower', ...
    'candidate087FalsePositivePixelsReduced', ...
    'candidate087FalsePositiveLargestComponentReduced', ...
    'baselineFalsePositiveComponentCount', ...
    'candidate084FalsePositiveComponentCount', ...
    'candidate086FalsePositiveComponentCount', ...
    'candidate087FalsePositiveComponentCount', ...
    'baselineRepairFineAbsActionSum', ...
    'candidate084RepairFineAbsActionSum', ...
    'candidate086RepairFineAbsActionSum', ...
    'candidate087RepairFineAbsActionSum', ...
    'baselineRepairMidAbsActionSum', ...
    'candidate084RepairMidAbsActionSum', ...
    'candidate086RepairMidAbsActionSum', ...
    'candidate087RepairMidAbsActionSum', ...
    'angleCount', 'angleResponsePixelsTotal', 'angleSeedPixelsTotal', ...
    'angleReconstructedPixelsTotal', 'anglePairwiseOverlapPixels', ...
    'angleFinalUnionPixels'};
for index = 1:numel(requiredColumns)
    name = requiredColumns{index};
    verifyTrue(testCase, ismember(name, metricsTable.Properties.VariableNames), ...
        ['CSV 缺少字段：' name]);
    verifyTrue(testCase, isfinite(metricsTable.(name)), ...
        ['CSV 字段不是有限值：' name]);
end
perAngleTable = readtable(fullfile(outputFolder, ...
    'lash_angle_grouped_per_angle_metrics.csv'));
verifyEqual(testCase, height(perAngleTable), angleCount);
verifyEqual(testCase, perAngleTable.angle(:), summary.angles(:));
end

function options = fixedOptions()
options = struct( ...
    'productionRoot', 'E:\image_beauty', ...
    'baselinePath', ...
    'C:\Users\JJiio\AppData\Local\Temp\image_beauty_issue02_probe\77_v32_probe.mat', ...
    'faceBox', [95, 79, 286, 372], ...
    'browEyeRoi', [165, 205, 150, 100], ...
    'lashRoi', [102, 248, 177, 48], ...
    'smoothingStrength', 100, ...
    'whiteningStrength', 15);
end

function feather = makeExpectedSoftMask(core, radius, peak)
if ~any(core(:))
    feather = zeros(size(core));
    return;
end
distance = bwdist(core);
feather = peak * max(0, 1 - distance / (radius + 1));
feather(core) = peak;
end
