function tests = testRepairMidTextureGateConsumption
%TESTREPAIRMIDTEXTUREGATECONSUMPTION 验证 Issue 08.3 单因素诊断。
tests = functiontests(localfunctions);
end

function setupOnce(~)
testRoot = fileparts(mfilename('fullpath'));
projectRoot = fileparts(testRoot);
addpath(fullfile(projectRoot, 'src'), '-begin');
addpath(testRoot, '-begin');
end

function testRejectsNonFixedFixtureBeforeProductionRun(testCase)
options = fixedOptions();
options.lashRoi = [103, 248, 177, 48];
verifyError(testCase, @() diagnoseRepairMidTextureGateConsumption( ...
    'not-an-image.png', tempdir, options), ...
    'diagnoseRepairMidTextureGateConsumption:NonFixedFixture');
end

function testFixed77MidTextureGateConsumption(testCase)
projectRoot = fileparts(fileparts(mfilename('fullpath')));
inputPath = fullfile(projectRoot, '人脸', '人脸', '77.png');
outputFolder = fullfile(tempdir, ...
    'image_beauty_issue08_3_mid_texture_gate_20260919');
[summary, diagnostics] = diagnoseRepairMidTextureGateConsumption( ...
    inputPath, outputFolder, fixedOptions());

verifyTrue(testCase, summary.completed);
verifyEqual(testCase, summary.issue, '08.3');
verifyTrue(testCase, any(strcmp(summary.case, {'A', 'B', 'C'})));
verifyEqual(testCase, summary.faceBox, [95, 79, 286, 372]);
verifyEqual(testCase, summary.lashRoi, [102, 248, 177, 48]);
verifyEqual(testCase, summary.manualLashMaskId, '77-manual-lash-v1');
verifyTrue(testCase, summary.manualLashMaskIndependent);
verifyTrue(testCase, summary.manualLashMaskFixed);
verifyFalse(testCase, summary.runtimeCacheReused);
verifyTrue(testCase, summary.sameMaskRun);
verifyTrue(testCase, summary.baseToneWhiteningFrozen);
verifyLessThanOrEqual(testCase, ...
    summary.productionWeightFormulaMaxError, summary.formulaTolerance);
verifyLessThanOrEqual(testCase, ...
    summary.baselineMidDeltaMaxError, summary.formulaTolerance);
verifyLessThanOrEqual(testCase, ...
    summary.baselineComposeMaxRgbDifference, summary.reconstructionTolerance);
verifyTrue(testCase, summary.noTextureGateOnlyMidChanged);
verifyTrue(testCase, diagnostics.comparison.onlyMidTextureGateChanged);

verifyEqual(testCase, diagnostics.manualLashMask, ...
    diagnostics.metrics.manualMask);
verifyEqual(testCase, nnz(diagnostics.manualLashMask), ...
    summary.manualLashMaskPixels);
verifyEqual(testCase, diagnostics.weights.textureGate, ...
    1 - diagnostics.masks.textureProtectionMask, 'AbsTol', 0);
verifyEqual(testCase, diagnostics.repairedFrequency.base, ...
    diagnostics.noTextureGateFrequency.base);
verifyEqual(testCase, diagnostics.repairedFrequency.fine, ...
    diagnostics.noTextureGateFrequency.fine);
verifyEqual(testCase, diagnostics.repairedFrequency.alphaMap, ...
    diagnostics.noTextureGateFrequency.alphaMap);
verifyEqual(testCase, diagnostics.midTarget, ...
    diagnostics.midTarget);
verifyEqual(testCase, diagnostics.midReference, ...
    diagnostics.midReference);
expectedAfter = diagnostics.weights.mediumWeightAfterTextureGate .* ...
    (diagnostics.midTarget - diagnostics.smoothedFrequency.mid);
expectedNoTextureGate = diagnostics.weights.mediumWeightBeforeTextureGate .* ...
    (diagnostics.midTarget - diagnostics.smoothedFrequency.mid);
verifyEqual(testCase, diagnostics.baselineMidDelta, expectedAfter, ...
    'AbsTol', summary.formulaTolerance);
verifyEqual(testCase, diagnostics.noTextureGateMidDelta, ...
    expectedNoTextureGate, 'AbsTol', summary.formulaTolerance);

requiredFiles = { ...
    'mid_manual_lash_overlay.png', ...
    'mid_texture_protection.png', ...
    'mid_texture_gate.png', ...
    'mid_weight_before_texture_gate.png', ...
    'mid_weight_after_texture_gate.png', ...
    'mid_weight_attenuation_by_texture_gate.png', ...
    'mid_baseline_delta.png', ...
    'mid_no_texture_gate_delta.png', ...
    'mid_baseline_reconstruction.png', ...
    'mid_no_texture_gate_reconstruction.png', ...
    'mid_baseline_vs_no_texture_gate.png', ...
    'mid_texture_gate_metrics.csv', ...
    'mid_texture_gate_diagnostic.mat'};
for index = 1:numel(requiredFiles)
    verifyTrue(testCase, isfile(fullfile(outputFolder, requiredFiles{index})), ...
        ['缺少 Issue 08.3 产物：' requiredFiles{index}]);
end

metricsTable = readtable(fullfile(outputFolder, ...
    'mid_texture_gate_metrics.csv'), 'TextType', 'char');
verifyEqual(testCase, height(metricsTable), 1);
verifyTrue(testCase, ismember('mediumWeightAttenuationMass', ...
    metricsTable.Properties.VariableNames));
verifyTrue(testCase, isfinite(metricsTable.mediumWeightAttenuationMass));
verifyTrue(testCase, isfinite(metricsTable.midGateEffectAbsMass));
end

function options = fixedOptions()
options = struct( ...
    'productionRoot', 'E:\image_beauty', ...
    'baselinePath', ...
    'C:\Users\JJiio\AppData\Local\Temp\image_beauty_issue02_probe\77_v32_probe.mat', ...
    'faceBox', [95, 79, 286, 372], ...
    'lashRoi', [102, 248, 177, 48], ...
    'smoothingStrength', 100, ...
    'whiteningStrength', 15);
end
