function tests = testLashSupportGeometryCandidate
%TESTLASHSUPPORTGEOMETRYCANDIDATE 验证 Issue 08.6 几何候选与单因素隔离。
tests = functiontests(localfunctions);
end

function setupOnce(~)
testRoot = fileparts(mfilename('fullpath'));
projectRoot = fileparts(testRoot);
addpath(fullfile(projectRoot, 'src'), '-begin');
addpath(testRoot, '-begin');
end

function testRejectsNonFixedFixtureBeforeProductionRun(testCase)
options = fixedOptions();
options.lashRoi = [103, 248, 177, 48];
verifyError(testCase, @() diagnoseLashSupportGeometryCandidate( ...
    'not-an-image.png', tempdir, options), ...
    'diagnoseLashSupportGeometryCandidate:NonFixedFixture');
end

function testFixed77GeometryCandidateWritesRequiredArtifacts(testCase)
projectRoot = fileparts(fileparts(mfilename('fullpath')));
inputPath = fullfile(projectRoot, '人脸', '人脸', '77.png');
outputFolder = fullfile(tempdir, ...
    'image_beauty_issue08_6_lash_support_geometry_20260919');
[summary, diagnostics] = diagnoseLashSupportGeometryCandidate( ...
    inputPath, outputFolder, fixedOptions());

verifyTrue(testCase, summary.completed);
verifyEqual(testCase, summary.issue, '08.6');
verifyEqual(testCase, summary.case, 'requiresVisualReview');
verifyEqual(testCase, summary.faceBox, [95, 79, 286, 372]);
verifyEqual(testCase, summary.browEye, [165, 205, 150, 100]);
verifyEqual(testCase, summary.lashRoi, [102, 248, 177, 48]);
verifyEqual(testCase, summary.manualLashMaskId, '77-manual-lash-v1');
verifyTrue(testCase, summary.manualLashMaskIndependent);
verifyTrue(testCase, summary.manualLashMaskFixed);
verifyFalse(testCase, summary.manualTruthUsedForGeneration);
verifyFalse(testCase, summary.runtimeCacheReused);
verifyTrue(testCase, summary.sameMaskRun);
verifyTrue(testCase, summary.baseToneWhiteningFrozen);
verifyTrue(testCase, summary.onlyLashSupportGeometryChanged);
verifyLessThanOrEqual(testCase, ...
    summary.evidenceReconstructionMaxError, 1e-12);
verifyEqual(testCase, summary.hardProtectionMaskChangedPixels, 0);
verifyEqual(testCase, summary.hardCoreChangedPixels, 0);
verifyTrue(testCase, summary.caseAssessment.requiresVisualReview);
verifyTrue(testCase, summary.repairAssessment.requiresVisualReview);

expectedConnected = imreconstruct( ...
    diagnostics.evidence.detectorSeed & diagnostics.evidence.allowedEvidence, ...
    diagnostics.evidence.allowedEvidence, 8);
verifyEqual(testCase, diagnostics.candidateGeometrySeed, expectedConnected);
verifyFalse(testCase, any(diagnostics.candidateGeometrySeed(:) & ...
    ~diagnostics.candidateAllowedEvidence(:)));
verifyFalse(testCase, any(diagnostics.candidateGeometrySeed(:) & ...
    ~diagnostics.evidence.eyeNeighborhood(:)));
verifyEqual(testCase, diagnostics.candidate086Support, ...
    diagnostics.candidate086LashProtection > 0);
verifyEqual(testCase, diagnostics.candidate084Support, ...
    diagnostics.candidate084LashProtection > 0);

expectedSoft = makeExpectedSoftMask(diagnostics.candidateGeometrySeed, ...
    summary.softRadius, summary.softPeak);
expectedSoft(~diagnostics.evidence.eyeNeighborhood) = 0;
expectedSoft = min(max(double(expectedSoft), 0), 1);
verifyEqual(testCase, diagnostics.candidate086LashProtection, expectedSoft, ...
    'AbsTol', 1e-12);
verifyEqual(testCase, diagnostics.candidate086TextureDiagnostics.lashCore, ...
    diagnostics.baselineTextureDiagnostics.lashCore);
verifyEqual(testCase, diagnostics.candidate086BeautyMasks.hardProtectionMask, ...
    diagnostics.baselineBeautyMasks.hardProtectionMask, 'AbsTol', 0);
verifyEqual(testCase, diagnostics.candidate086BeautyMasks.structureProtectionMask, ...
    diagnostics.baselineBeautyMasks.structureProtectionMask, 'AbsTol', 0);

for group = {'baseline', 'candidate084', 'candidate086'}
    metrics = summary.metrics.(group{1});
    verifyEqual(testCase, metrics.truePositivePixels + ...
        metrics.falseNegativePixels, summary.manualLashMaskPixels);
    verifyEqual(testCase, metrics.truePositivePixels + ...
        metrics.falsePositivePixels, metrics.supportPixels);
    verifyTrue(testCase, isfinite(metrics.recall));
    verifyTrue(testCase, isfinite(metrics.precision));
end
verifyEqual(testCase, ...
    summary.metrics.candidate086RepairFineAbsAction.sum, ...
    sum(abs(diagnostics.candidate086RepairFineDelta( ...
    diagnostics.manualLashMask))), 'AbsTol', 1e-12);
verifyEqual(testCase, ...
    summary.metrics.candidate086RepairMidAbsAction.sum, ...
    sum(abs(diagnostics.candidate086RepairMidDelta( ...
    diagnostics.manualLashMask))), 'AbsTol', 1e-12);

requiredFiles = { ...
    'original_lash.png', ...
    'baseline_support.png', ...
    'candidate_08_4_support.png', ...
    'candidate_08_6_support.png', ...
    'manual_vs_08_4_support.png', ...
    'manual_vs_08_6_support.png', ...
    'false_positive_08_4.png', ...
    'false_positive_08_6.png', ...
    'false_negative_08_4.png', ...
    'false_negative_08_6.png', ...
    'baseline_repair_fine_delta.png', ...
    'candidate_08_4_repair_fine_delta.png', ...
    'candidate_08_6_repair_fine_delta.png', ...
    'baseline_repair_mid_delta.png', ...
    'candidate_08_4_repair_mid_delta.png', ...
    'candidate_08_6_repair_mid_delta.png', ...
    'baseline_final_lash.png', ...
    'candidate_08_4_final_lash.png', ...
    'candidate_08_6_final_lash.png', ...
    'support_geometry_comparison.png', ...
    'final_geometry_comparison.png', ...
    'lash_support_geometry_metrics.csv', ...
    'lash_support_geometry_diagnostic.mat'};
for index = 1:numel(requiredFiles)
    verifyTrue(testCase, isfile(fullfile(outputFolder, requiredFiles{index})), ...
        ['缺少 Issue 08.6 产物：' requiredFiles{index}]);
end

metricsTable = readtable(fullfile(outputFolder, ...
    'lash_support_geometry_metrics.csv'), 'TextType', 'char');
verifyEqual(testCase, height(metricsTable), 1);
requiredColumns = { ...
    'baselineRecall', 'candidate084Recall', 'candidate086Recall', ...
    'baselinePrecision', 'candidate084Precision', 'candidate086Precision', ...
    'candidate086PrecisionImproved', ...
    'candidate086RecallNotLower', ...
    'candidate086FalsePositivePixelsReduced', ...
    'baselineRepairFineAbsActionSum', ...
    'candidate084RepairFineAbsActionSum', ...
    'candidate086RepairFineAbsActionSum', ...
    'baselineRepairMidAbsActionSum', ...
    'candidate084RepairMidAbsActionSum', ...
    'candidate086RepairMidAbsActionSum'};
for index = 1:numel(requiredColumns)
    name = requiredColumns{index};
    verifyTrue(testCase, ismember(name, metricsTable.Properties.VariableNames), ...
        ['CSV 缺少字段：' name]);
    verifyTrue(testCase, isfinite(metricsTable.(name)), ...
        ['CSV 字段不是有限值：' name]);
end
end

function options = fixedOptions()
options = struct( ...
    'productionRoot', 'E:\image_beauty', ...
    'baselinePath', ...
    'C:\Users\JJiio\AppData\Local\Temp\image_beauty_issue02_probe\77_v32_probe.mat', ...
    'faceBox', [95, 79, 286, 372], ...
    'browEyeRoi', [165, 205, 150, 100], ...
    'lashRoi', [102, 248, 177, 48], ...
    'smoothingStrength', 100, ...
    'whiteningStrength', 15);
end

function feather = makeExpectedSoftMask(core, radius, peak)
if ~any(core(:))
    feather = zeros(size(core));
    return;
end
distance = bwdist(core);
feather = peak * max(0, 1 - distance / (radius + 1));
feather(core) = peak;
end
