function tests = testResidualEyelashLossDiagnostics
%TESTRESIDUALEYELASHLOSSDIAGNOSTICS 验证 Issue 08.1 睫毛归因入口。
tests = functiontests(localfunctions);
end

function setupOnce(~)
testRoot = fileparts(mfilename('fullpath'));
projectRoot = fileparts(testRoot);
addpath(fullfile(projectRoot, 'src'), '-begin');
addpath(testRoot, '-begin');
end

function testRequiresManualLashRoi(testCase)
options = struct('productionRoot', 'E:\image_beauty');
verifyError(testCase, @() diagnoseResidualEyelashLoss( ...
    'not-an-image.png', tempdir, options), ...
    'diagnoseResidualEyelashLoss:MissingLashRoi');
end

function testRejectsInvalidLashRoiBeforeReadingImage(testCase)
options = fixedOptions();
options.lashRoi = [0, 248, 177, 48];
verifyError(testCase, @() diagnoseResidualEyelashLoss( ...
    'not-an-image.png', tempdir, options), ...
    'diagnoseResidualEyelashLoss:InvalidLashRoi');
end

function testRejectsMissingImageAfterManualRoiValidation(testCase)
options = fixedOptions();
verifyError(testCase, @() diagnoseResidualEyelashLoss( ...
    'not-an-image.png', tempdir, options), ...
    'diagnoseResidualEyelashLoss:MissingImage');
end

function testRejectsOutOfBoundsManualLashRoi(testCase)
projectRoot = fileparts(fileparts(mfilename('fullpath')));
options = fixedOptions();
options.productionRoot = projectRoot;
options.lashRoi = [500, 400, 40, 40];
verifyError(testCase, @() diagnoseResidualEyelashLoss( ...
    fullfile(projectRoot, '人脸', '人脸', '77.png'), tempdir, options), ...
    'diagnoseResidualEyelashLoss:InvalidLashRoi');
end

function testFixed77AttributionWritesSingleRunArtifacts(testCase)
projectRoot = fileparts(fileparts(mfilename('fullpath')));
inputPath = fullfile(projectRoot, '人脸', '人脸', '77.png');
options = fixedOptions();
options.productionRoot = projectRoot;
outputFolder = fullfile(tempdir, ...
    'image_beauty_issue08_1_eyelash_20260918');
[summary, diagnostics] = diagnoseResidualEyelashLoss( ...
    inputPath, outputFolder, options);

verifyTrue(testCase, summary.completed);
verifyEqual(testCase, summary.issue, '08.1');
verifyTrue(testCase, summary.sameMaskRun);
verifyFalse(testCase, summary.runtimeCacheReused);
verifyTrue(testCase, summary.baseToneWhiteningDisabled);
verifyLessThanOrEqual(testCase, summary.originalReconstructionMaxError, ...
    summary.reconstructionTolerance);
verifyEqual(testCase, summary.lashRoi, [102, 248, 177, 48]);
verifyTrue(testCase, any(strcmp(summary.case, {'A', 'B', 'C', 'D'})));
verifySize(testCase, diagnostics.deltas.smoothFine, [450, 512]);
verifySize(testCase, diagnostics.deltas.smoothMid, [450, 512]);
verifySize(testCase, diagnostics.deltas.repairFine, [450, 512]);
verifySize(testCase, diagnostics.deltas.repairMid, [450, 512]);
verifyTrue(testCase, diagnostics.sameMaskRun);
verifyFalse(testCase, diagnostics.productionReusedRuntimeCache);

requiredFiles = { ...
    'eyelash_original.png', ...
    'eyelash_smoothing_only.png', ...
    'eyelash_smoothing_plus_repair.png', ...
    'eyelash_texture_protection.png', ...
    'eyelash_eye_detail_protection.png', ...
    'eyelash_lash_protection.png', ...
    'eyelash_double_eyelid_protection.png', ...
    'eyelash_hard_protection.png', ...
    'eyelash_smoothing_fine_delta.png', ...
    'eyelash_smoothing_mid_delta.png', ...
    'eyelash_repair_fine_delta.png', ...
    'eyelash_repair_mid_delta.png', ...
    'eyelash_stage_metrics.csv', ...
    'eyelash_coverage_comparison.png', ...
    'eyelash_stage_comparison.png', ...
    'eyelash_diagnostic_data.mat'};
for index = 1:numel(requiredFiles)
    verifyTrue(testCase, isfile(fullfile(outputFolder, requiredFiles{index})), ...
        ['缺少 Issue 08.1 产物：' requiredFiles{index}]);
end
metrics = readtable(summary.paths.stageMetrics, 'TextType', 'char');
verifyEqual(testCase, height(metrics), 2);
verifyTrue(testCase, all(ismember( ...
    {'browEye', 'lashRoi'}, metrics.roi)));
verifyTrue(testCase, all(isfinite(metrics.smoothingFineMeanAbs)));
verifyTrue(testCase, all(isfinite(metrics.smoothingMidMeanAbs)));
verifyTrue(testCase, all(isfinite(metrics.repairFineMeanAbs)));
verifyTrue(testCase, all(isfinite(metrics.repairMidMeanAbs)));
end

function options = fixedOptions()
options = struct( ...
    'productionRoot', 'E:\image_beauty', ...
    'faceBox', [95, 79, 286, 372], ...
    'browEyeRoi', [165, 205, 150, 100], ...
    'lashRoi', [102, 248, 177, 48], ...
    'smoothingStrength', 100, ...
    'whiteningStrength', 15, ...
    'strictFixed77', true);
end
