function tests = testBaseLuminanceEqualization
%TESTBASELUMINANCEEQUALIZATION Base-only 亮度均匀化与最终合成回归。
tests = functiontests(localfunctions);
end

function setupOnce(~)
projectRoot = fileparts(fileparts(mfilename('fullpath')));
addpath(fullfile(projectRoot, 'src'));
end

function testBaseOnlyReferenceSupportsBothCorrectionSigns(testCase)
imageSize = [120, 160];
[xGrid, ~] = meshgrid(1:imageSize(2), 1:imageSize(1));
base = .55 + .10 * tanh((xGrid - 80) / 18);
frequency = struct( ...
    'base', base, ...
    'mid', nan(imageSize), ...
    'fine', nan(imageSize), ...
    'sourceLuminance', nan(imageSize));
masks = simpleMasks(imageSize, [1, 1, 160, 120]);

[result, diagnostics] = beauty.evenSkinLuminance( ...
    frequency, masks, 100);

verifyGreaterThan(testCase, nnz(diagnostics.positiveSupport), 0);
verifyGreaterThan(testCase, nnz(diagnostics.negativeSupport), 0);
verifyGreaterThanOrEqual(testCase, min(result.baseDelta(:)), -.03);
verifyLessThanOrEqual(testCase, max(result.baseDelta(:)), .03);
verifyEqual(testCase, result.baseDelta, ...
    diagnostics.limitedBaseDelta .* result.supportMap, 'AbsTol', 1e-12);
verifyTrue(testCase, isequaln(frequency.mid, nan(imageSize)));
verifyTrue(testCase, diagnostics.frequencyUnchanged);
end

function testZeroStrengthAndMissingReferenceAreIdentity(testCase)
imageSize = [32, 48];
base = .50 * ones(imageSize);
frequency = struct('base', base, 'mid', zeros(imageSize), ...
    'fine', zeros(imageSize));
masks = simpleMasks(imageSize, [1, 1, 48, 32]);

[zeroResult, zeroDiagnostics] = beauty.evenSkinLuminance( ...
    frequency, masks, 0);
verifyEqual(testCase, zeroResult.baseDelta, zeros(imageSize), ...
    'AbsTol', 1e-12);
verifyEqual(testCase, zeroResult.supportMap, zeros(imageSize), ...
    'AbsTol', 1e-12);
verifyEqual(testCase, zeroDiagnostics.baseCurve, 0, 'AbsTol', 1e-12);

masks.skinMask = zeros(imageSize);
masks.strengthMap = zeros(imageSize);
[emptyResult, emptyDiagnostics] = beauty.evenSkinLuminance( ...
    frequency, masks, 100);
verifyEqual(testCase, emptyResult.baseDelta, zeros(imageSize), ...
    'AbsTol', 1e-12);
verifyEqual(testCase, emptyResult.supportMap, zeros(imageSize), ...
    'AbsTol', 1e-12);
verifyFalse(testCase, emptyDiagnostics.hasReliableReference);
end

function testHardProtectionZeroesBaseSupport(testCase)
imageSize = [64, 80];
[xGrid, ~] = meshgrid(1:imageSize(2), 1:imageSize(1));
frequency = struct('base', .55 + .08 * sin(xGrid / 10), ...
    'mid', zeros(imageSize), 'fine', zeros(imageSize));
masks = simpleMasks(imageSize, [1, 1, 80, 64]);
hard = false(imageSize);
hard(25:35, 32:45) = true;
masks.hardProtectionMask = double(hard);

[result, ~] = beauty.evenSkinLuminance(frequency, masks, 100);
verifyEqual(testCase, result.supportMap(hard), zeros(nnz(hard), 1), ...
    'AbsTol', 1e-12);
verifyEqual(testCase, result.baseDelta(hard), zeros(nnz(hard), 1), ...
    'AbsTol', 1e-12);
end

function testComposeAddsWeightedBaseDeltaOnce(testCase)
imageSize = [24, 32];
image = uint8(ones([imageSize, 3]) * 128);
sourceYcbcr = rgb2ycbcr(im2double(image));
sourceLuminance = sourceYcbcr(:, :, 1);
frequency = struct('sourceLuminance', sourceLuminance, ...
    'base', sourceLuminance, 'mid', zeros(imageSize), ...
    'fine', zeros(imageSize));
masks = simpleMasks(imageSize, [1, 1, 32, 24]);
smoothed = struct('outputLuminance', sourceLuminance, ...
    'alphaMap', zeros(imageSize));
baseResult = struct('baseDelta', .02 * ones(imageSize), ...
    'supportMap', .50 * ones(imageSize));
processing = struct('baseLuminance', baseResult);

[~, diagnostics] = beauty.composeBeautyResult( ...
    image, frequency, smoothed, masks, 0, processing);

verifyEqual(testCase, diagnostics.alphaMap, .50 * ones(imageSize), ...
    'AbsTol', 1e-12);
verifyEqual(testCase, diagnostics.luminanceDelta, .02 * ones(imageSize), ...
    'AbsTol', 1e-12);
verifyEqual(testCase, diagnostics.outputLuminance, ...
    sourceLuminance + .02, 'AbsTol', 1e-12);
end

function testStageContractDrivesProtectionGates(testCase)
%TESTSTAGECONTRACTDRIVESPROTECTIONGATES T16/T32：提供 Base Luminance stage
%   contract 时，逐像素修改门与参考池门只来自 contract 的规范门
%   （target.baseLuminance / support.baseLuminance / hard / regionBandGate），
%   不再自行组合 general texture/chroma/structure/hard masks：stage 路径与
%   经唯一组装点的 legacy 路径逐位等价（bit-exact），扰动 general 保护
%   masks 不改变 stage 路径输出，缺字段或取值越界 fail-fast。
imageSize = [64, 96];
[xGrid, ~] = meshgrid(1:imageSize(2), 1:imageSize(1));
base = .55 + .10 * tanh((xGrid - 48) / 14);
frequency = struct('base', base, 'mid', zeros(imageSize), ...
    'fine', zeros(imageSize));
beautyMasks = simpleMasks(imageSize, [1, 1, 96, 64]);
beautyMasks.structureProtectionMask = .60 * double(base > .60);
beautyMasks.textureProtectionMask = .30 + .20 * sin(xGrid / 7);
beautyMasks.chromaProtectionMask = .25 * ones(imageSize);
beautyMasks.toneProtectionMask = beautyMasks.chromaProtectionMask;
hardMask = false(imageSize);
hardMask(8:14, 10:22) = true;
beautyMasks.hardProtectionMask = double(hardMask);
protection = masks.buildStageProtectionMasks(beautyMasks);
contract = beauty.baseLuminanceStageContract(protection);

% contract 只发布规范门：逐位等于 policy 发布值 / 补码。
verifyEqual(testCase, contract.hard, protection.hard, 'AbsTol', 0);
verifyEqual(testCase, contract.target.baseLuminance, ...
    protection.target.baseLuminance, 'AbsTol', 0);
verifyEqual(testCase, contract.support.baseLuminance, ...
    protection.support.baseLuminance, 'AbsTol', 0);
verifyEqual(testCase, contract.regionBandGate, ...
    1 - protection.regionBandBase, 'AbsTol', 0);
verifyTrue(testCase, ~isfield(contract, 'baseLuminance'), ...
    '旧扁平折叠名 baseLuminance 已被 target.baseLuminance 取代并删除。');

strengths = [0, 40, 100];
for index = 1:numel(strengths)
    strength = strengths(index);
    [legacyResult, legacyDetails] = beauty.evenSkinLuminance( ...
        frequency, beautyMasks, strength);
    [stageResult, stageDetails] = beauty.evenSkinLuminance( ...
        frequency, beautyMasks, strength, contract);
    verifyTrue(testCase, isequaln(stageResult, legacyResult), ...
        'stage 路径结果必须与 legacy 路径逐位一致。');
    verifyEqual(testCase, stageDetails.supportMap, ...
        legacyDetails.supportMap, 'AbsTol', 0);
    verifyEqual(testCase, stageDetails.referenceReliability, ...
        legacyDetails.referenceReliability, 'AbsTol', 0);
    verifyEqual(testCase, stageDetails.baseDelta, ...
        legacyDetails.baseDelta, 'AbsTol', 0);
    % 门来源收口：target/support 门逐位等于 1 - contract 规范门。
    verifyEqual(testCase, stageDetails.targetGate, ...
        1 - contract.target.baseLuminance, 'AbsTol', 0);
    verifyEqual(testCase, stageDetails.supportGate, ...
        1 - contract.support.baseLuminance, 'AbsTol', 0);
    % hard identity：hard 区域 supportMap/baseDelta 恒 0。
    verifyEqual(testCase, nnz(stageDetails.supportMap(hardMask)), 0);
    verifyEqual(testCase, nnz(stageDetails.baseDelta(hardMask)), 0);
end

% 负向证明：stage 路径输出对 general 保护 masks 扰动完全不变（只消费
% stage contract），legacy 路径则会随之变化。
[~, legacyDetails60] = beauty.evenSkinLuminance(frequency, beautyMasks, 60);
[~, stageDetails60] = beauty.evenSkinLuminance(frequency, beautyMasks, 60, ...
    contract);
perturbedMasks = beautyMasks;
perturbedMasks.structureProtectionMask = ...
    min(1, beautyMasks.structureProtectionMask * .5 + .25);
perturbedMasks.textureProtectionMask = ...
    min(1, beautyMasks.textureProtectionMask * .5 + .25);
perturbedMasks.chromaProtectionMask = ...
    min(1, beautyMasks.chromaProtectionMask * .5 + .25);
perturbedMasks.toneProtectionMask = perturbedMasks.chromaProtectionMask;
perturbedMasks.hardProtectionMask = ...
    min(1, beautyMasks.hardProtectionMask * .5 + .25);
[~, perturbedLegacyDetails] = beauty.evenSkinLuminance( ...
    frequency, perturbedMasks, 60);
[~, perturbedStageDetails] = beauty.evenSkinLuminance( ...
    frequency, perturbedMasks, 60, contract);
verifyTrue(testCase, ...
    nnz(perturbedLegacyDetails.supportMap ~= ...
    legacyDetails60.supportMap) > 0, ...
    '保护 masks 扰动必须确实影响 legacy 路径，否则本断言无意义。');
verifyEqual(testCase, perturbedStageDetails.supportMap, ...
    stageDetails60.supportMap, 'AbsTol', 0);
verifyEqual(testCase, perturbedStageDetails.baseDelta, ...
    stageDetails60.baseDelta, 'AbsTol', 0);
verifyEqual(testCase, perturbedStageDetails.referenceReliability, ...
    stageDetails60.referenceReliability, 'AbsTol', 0);

% 缺字段与取值越界 fail-fast：不静默回退拼装。
brokenContract = rmfield(contract, 'target');
verifyError(testCase, @() beauty.evenSkinLuminance( ...
    frequency, beautyMasks, 60, brokenContract), ...
    'beauty:InvalidEvenLuminanceInput');
brokenContract = rmfield(contract, 'support');
verifyError(testCase, @() beauty.evenSkinLuminance( ...
    frequency, beautyMasks, 60, brokenContract), ...
    'beauty:InvalidEvenLuminanceInput');
brokenContract = rmfield(contract, 'hard');
verifyError(testCase, @() beauty.evenSkinLuminance( ...
    frequency, beautyMasks, 60, brokenContract), ...
    'beauty:InvalidEvenLuminanceInput');
brokenContract = rmfield(contract, 'regionBandGate');
verifyError(testCase, @() beauty.evenSkinLuminance( ...
    frequency, beautyMasks, 60, brokenContract), ...
    'beauty:InvalidEvenLuminanceInput');
brokenContract = contract;
brokenContract.target.baseLuminance = ...
    min(1, brokenContract.target.baseLuminance) + .25;
verifyError(testCase, @() beauty.evenSkinLuminance( ...
    frequency, beautyMasks, 60, brokenContract), ...
    'beauty:InvalidEvenLuminanceInput');
end

function testTargetAndSupportGatesAreIndependent(testCase)
%TESTTARGETANDSUPPORTGATESAREINDEPENDENT T32 双门控独立性单测（上位契约
%   第 3.3、5.6 节）：target 门（能不能做低频亮度均衡）与 support 门
%   （能不能进参考统计）严格解耦。
%     只改 target.baseLuminance：参考统计（referenceReliability /
%       referenceWeight / referenceCoverage / referenceOffset / targetBase）
%       逐位不变，逐像素 supportMap 单调下降（保护增大 → 均衡量减小）。
%     只改 support.baseLuminance：逐像素门（targetGate /
%       hardProtectionGate / regionBandGate）逐位不变，参考统计按预期
%       变化（参考池被收窄）。
%   该拆分是 T30 已验证的 target/support 分离被提升为规范字段的直接举证。
imageSize = [64, 96];
[xGrid, ~] = meshgrid(1:imageSize(2), 1:imageSize(1));
base = .55 + .10 * tanh((xGrid - 48) / 14);
frequency = struct('base', base, 'mid', zeros(imageSize), ...
    'fine', zeros(imageSize));
beautyMasks = simpleMasks(imageSize, [1, 1, 96, 64]);
beautyMasks.structureProtectionMask = .40 * ones(imageSize);
beautyMasks.textureProtectionMask = .25 + .20 * sin(xGrid / 9);
beautyMasks.chromaProtectionMask = .20 * ones(imageSize);
hardMask = false(imageSize);
hardMask(6:12, 9:20) = true;
beautyMasks.hardProtectionMask = double(hardMask);
protection = masks.buildStageProtectionMasks(beautyMasks);
contract = beauty.baseLuminanceStageContract(protection);

[~, baseline] = beauty.evenSkinLuminance(frequency, beautyMasks, 80, contract);
verifyTrue(testCase, nnz(baseline.supportMap > 0) > 0, ...
    'fixture 必须产生非空 supportMap，否则独立性断言无意义。');

% 只改 target 门：参考统计逐位不变，逐像素 supportMap 单调下降。
targetPerturbed = contract;
targetPerturbed.target.baseLuminance = ...
    min(1, contract.target.baseLuminance + .30);
verifyTrue(testCase, ...
    nnz(targetPerturbed.target.baseLuminance ~= ...
    contract.target.baseLuminance) > 0, ...
    'fixture 的 target 门必须确实被扰动。');
[~, targetDetails] = beauty.evenSkinLuminance(frequency, beautyMasks, 80, ...
    targetPerturbed);
verifyEqual(testCase, targetDetails.referenceReliability, ...
    baseline.referenceReliability, 'AbsTol', 0, ...
    '只改 target 门时参考统计必须逐位不变。');
verifyEqual(testCase, targetDetails.referenceWeight, ...
    baseline.referenceWeight, 'AbsTol', 0);
verifyEqual(testCase, targetDetails.referenceCoverage, ...
    baseline.referenceCoverage, 'AbsTol', 0);
verifyEqual(testCase, targetDetails.referenceOffset, ...
    baseline.referenceOffset, 'AbsTol', 0);
verifyEqual(testCase, targetDetails.targetBase, ...
    baseline.targetBase, 'AbsTol', 0);
verifyTrue(testCase, ...
    all(targetDetails.supportMap(:) <= baseline.supportMap(:)), ...
    'target 保护增大必须使逐像素 supportMap 不增。');
verifyTrue(testCase, ...
    nnz(targetDetails.supportMap ~= baseline.supportMap) > 0, ...
    '只改 target 门必须改变逐像素 supportMap，否则本断言无意义。');

% 只改 support 门：逐像素门逐位不变，参考统计按预期变化。
supportPerturbed = contract;
supportPerturbed.support.baseLuminance = ...
    min(1, contract.support.baseLuminance + .30);
verifyTrue(testCase, ...
    nnz(supportPerturbed.support.baseLuminance ~= ...
    contract.support.baseLuminance) > 0, ...
    'fixture 的 support 门必须确实被扰动。');
[~, supportDetails] = beauty.evenSkinLuminance(frequency, beautyMasks, 80, ...
    supportPerturbed);
verifyEqual(testCase, supportDetails.targetGate, baseline.targetGate, ...
    'AbsTol', 0, '只改 support 门时逐像素修改门必须逐位不变。');
verifyEqual(testCase, supportDetails.hardProtectionGate, ...
    baseline.hardProtectionGate, 'AbsTol', 0);
verifyEqual(testCase, supportDetails.regionBandGate, ...
    baseline.regionBandGate, 'AbsTol', 0);
verifyTrue(testCase, ...
    nnz(supportDetails.referenceReliability ~= ...
    baseline.referenceReliability) > 0, ...
    '只改 support 门必须改变参考统计，否则本断言无意义。');
verifyTrue(testCase, ...
    all(supportDetails.referenceReliability(:) <= ...
    baseline.referenceReliability(:)), ...
    'support 保护增大必须使参考池门不增。');
end

function masks = simpleMasks(imageSize, faceBox)
% T32：兼容入口经唯一组装点向 policy 层索取零带 stageProtection
%   （masks.buildStageProtectionMasks），故 fixture 必须携带 v3.1 保护层
%   要求的全部字段（whitening/nose/faceSkin 补零即零带，不改变 legacy
%   折叠值）。hardProtectionMask 由各用例按需覆盖，透传为 contract.hard。
masks = struct( ...
    'skinMask', ones(imageSize), ...
    'strengthMap', ones(imageSize), ...
    'structureProtectionMask', zeros(imageSize), ...
    'hardProtectionMask', zeros(imageSize), ...
    'textureProtectionMask', zeros(imageSize), ...
    'toneProtectionMask', zeros(imageSize), ...
    'chromaProtectionMask', zeros(imageSize), ...
    'whiteningProtectionMask', zeros(imageSize), ...
    'noseMask', zeros(imageSize), ...
    'faceSkinMask', zeros(imageSize), ...
    'faceBox', faceBox);
end
