function tests = testLashProtectionSufficiencyUpperBound
%TESTLASHPROTECTIONSUFFICIENCYUPPERBOUND 验证 Issue 08.5 上界构造与证据链。
tests = functiontests(localfunctions);
end

function setupOnce(~)
testRoot = fileparts(mfilename('fullpath'));
projectRoot = fileparts(testRoot);
addpath(fullfile(projectRoot, 'src'), '-begin');
addpath(testRoot, '-begin');
end

function testRejectsNonFixedFixtureBeforeProductionRun(testCase)
options = fixedOptions();
options.lashRoi = [103, 248, 177, 48];
verifyError(testCase, @() diagnoseLashProtectionSufficiencyUpperBound( ...
    'not-an-image.png', tempdir, options), ...
    'diagnoseLashProtectionSufficiencyUpperBound:NonFixedFixture');
end

function testFixed77UpperBoundWritesRequiredArtifacts(testCase)
projectRoot = fileparts(fileparts(mfilename('fullpath')));
inputPath = fullfile(projectRoot, '人脸', '人脸', '77.png');
outputFolder = fullfile(tempdir, ...
    'image_beauty_issue08_5_lash_protection_sufficiency_upper_bound_20260919');
[summary, diagnostics] = diagnoseLashProtectionSufficiencyUpperBound( ...
    inputPath, outputFolder, fixedOptions());

verifyTrue(testCase, summary.completed);
verifyEqual(testCase, summary.issue, '08.5');
verifyEqual(testCase, summary.case, 'requiresVisualReview');
verifyEqual(testCase, summary.faceBox, [95, 79, 286, 372]);
verifyEqual(testCase, summary.browEye, [165, 205, 150, 100]);
verifyEqual(testCase, summary.lashRoi, [102, 248, 177, 48]);
verifyEqual(testCase, summary.manualLashMaskId, '77-manual-lash-v1');
verifyTrue(testCase, summary.manualLashMaskIndependent);
verifyTrue(testCase, summary.manualLashMaskFixed);
verifyFalse(testCase, summary.runtimeCacheReused);
verifyTrue(testCase, summary.sameMaskRun);
verifyTrue(testCase, summary.baseToneWhiteningFrozen);
verifyTrue(testCase, summary.upperBoundOnlyExistingCandidateSupport);
verifyEqual(testCase, summary.supportChangedPixels, 0);
verifyGreaterThan(testCase, summary.candidateSupportPixels, 0);
verifyEqual(testCase, summary.candidateSupportPixels, ...
    summary.upperBoundSupportPixels);
verifyLessThanOrEqual(testCase, ...
    summary.metrics.candidateLashProtection.mean, 1);
verifyEqual(testCase, summary.metrics.upperBoundLashProtection.max, 1, ...
    'AbsTol', summary.caseAssessment.finiteEvidence * 1e-12 + 1e-12);
verifyGreaterThan(testCase, ...
    summary.metrics.upperBoundLashStrengthRaisedPixels, 0);
verifyLessThanOrEqual(testCase, ...
    summary.metrics.candidateUpperTextureChangedOutsideCandidateSupport, 0);
verifyLessThanOrEqual(testCase, ...
    summary.baselineComposeMaxRgbDifference, 1e-12);
verifyLessThanOrEqual(testCase, ...
    summary.candidateComposeMaxRgbDifference, 1e-12);

verifyEqual(testCase, ...
    summary.hardProtectionMaskChangedPixels.baselineToCandidate, 0);
verifyEqual(testCase, ...
    summary.hardProtectionMaskChangedPixels.baselineToUpperBound, 0);
verifyEqual(testCase, ...
    summary.hardProtectionMaskChangedPixels.candidateToUpperBound, 0);
verifyEqual(testCase, summary.lashCoreChangedPixels.baselineToCandidate, 0);
verifyEqual(testCase, summary.lashCoreChangedPixels.baselineToUpperBound, 0);
verifyEqual(testCase, summary.lashCoreChangedPixels.candidateToUpperBound, 0);
verifyEqual(testCase, ...
    summary.hardProtectedFinalRgbChangedCount.baseline, 0);
verifyEqual(testCase, ...
    summary.hardProtectedFinalRgbChangedCount.candidate, 0);
verifyEqual(testCase, ...
    summary.hardProtectedFinalRgbChangedCount.upperBound, 0);

verifyTrue(testCase, summary.caseAssessment.requiresVisualReview);
verifyTrue(testCase, summary.caseAssessment.finiteEvidence);
verifyTrue(testCase, summary.caseAssessment.supportUnchanged);
verifyTrue(testCase, summary.caseAssessment.strengthRaised);

expectedUpperSupport = diagnostics.candidateLashProtection > 0;
verifyEqual(testCase, diagnostics.candidateSupport, expectedUpperSupport);
verifyEqual(testCase, diagnostics.upperBoundSupport, expectedUpperSupport);
expectedUpperLash = diagnostics.candidateLashProtection;
expectedUpperLash(expectedUpperSupport) = 1;
verifyEqual(testCase, diagnostics.upperBoundLashProtection, expectedUpperLash, ...
    'AbsTol', 1e-12);
verifyEqual(testCase, ...
    diagnostics.upperBoundBeautyMasks.hardProtectionMask, ...
    diagnostics.candidateBeautyMasks.hardProtectionMask, 'AbsTol', 0);
verifyEqual(testCase, ...
    diagnostics.upperBoundBeautyMasks.structureProtectionMask, ...
    diagnostics.candidateBeautyMasks.structureProtectionMask, 'AbsTol', 0);
verifyLessThanOrEqual(testCase, ...
    diagnostics.upperBoundTextureDiagnostics.eyeDetailProtection(:), 1);

requiredFiles = { ...
    'original_lash.png', ...
    'baseline_final_lash.png', ...
    'candidate_final_lash.png', ...
    'upper_bound_final_lash.png', ...
    'baseline_candidate_upperbound_comparison.png', ...
    'candidate_lash_protection.png', ...
    'upper_bound_lash_protection.png', ...
    'candidate_support.png', ...
    'baseline_repair_fine_delta.png', ...
    'candidate_repair_fine_delta.png', ...
    'upper_bound_repair_fine_delta.png', ...
    'baseline_repair_mid_delta.png', ...
    'candidate_repair_mid_delta.png', ...
    'upper_bound_repair_mid_delta.png', ...
    'lash_protection_sufficiency_upper_bound_metrics.csv', ...
    'lash_protection_sufficiency_upper_bound_diagnostic.mat'};
for index = 1:numel(requiredFiles)
    verifyTrue(testCase, isfile(fullfile(outputFolder, requiredFiles{index})), ...
        ['缺少 Issue 08.5 产物：' requiredFiles{index}]);
end

metricsTable = readtable(fullfile(outputFolder, ...
    'lash_protection_sufficiency_upper_bound_metrics.csv'), ...
    'TextType', 'char');
verifyEqual(testCase, height(metricsTable), 1);
requiredColumns = { ...
    'candidateLashProtectionMean', ...
    'upperBoundLashProtectionMean', ...
    'supportChangedPixels', ...
    'baselineRepairFineAbsActionSum', ...
    'candidateRepairFineAbsActionSum', ...
    'upperBoundRepairFineAbsActionSum', ...
    'baselineRepairMidAbsActionSum', ...
    'candidateRepairMidAbsActionSum', ...
    'upperBoundRepairMidAbsActionSum', ...
    'baselineFinalRgbDistanceToOriginalMean', ...
    'candidateFinalRgbDistanceToOriginalMean', ...
    'upperBoundFinalRgbDistanceToOriginalMean', ...
    'baselineFinalLuminanceDistanceToOriginalMean', ...
    'candidateFinalLuminanceDistanceToOriginalMean', ...
    'upperBoundFinalLuminanceDistanceToOriginalMean', ...
    'candidateUpperOutsideBrowEyeFinalRgbChangeMean', ...
    'hardProtectionBaselineToUpperBoundChangedPixels', ...
    'upperBoundHardProtectedFinalRgbChangedCount'};
for index = 1:numel(requiredColumns)
    name = requiredColumns{index};
    verifyTrue(testCase, ismember(name, metricsTable.Properties.VariableNames), ...
        ['CSV 缺少字段：' name]);
    verifyTrue(testCase, isfinite(metricsTable.(name)), ...
        ['CSV 字段不是有限值：' name]);
end
verifyEqual(testCase, metricsTable.supportChangedPixels, 0);
verifyEqual(testCase, metricsTable.hardProtectionBaselineToUpperBoundChangedPixels, 0);
verifyEqual(testCase, metricsTable.upperBoundHardProtectedFinalRgbChangedCount, 0);
end

function options = fixedOptions()
options = struct( ...
    'productionRoot', 'E:\image_beauty', ...
    'baselinePath', ...
    'C:\Users\JJiio\AppData\Local\Temp\image_beauty_issue02_probe\77_v32_probe.mat', ...
    'faceBox', [95, 79, 286, 372], ...
    'browEyeRoi', [165, 205, 150, 100], ...
    'lashRoi', [102, 248, 177, 48], ...
    'smoothingStrength', 100, ...
    'whiteningStrength', 15);
end
