function tests = testBaseLuminanceEqualization
%TESTBASELUMINANCEEQUALIZATION Base-only 亮度均匀化与最终合成回归。
tests = functiontests(localfunctions);
end

function setupOnce(~)
projectRoot = fileparts(fileparts(mfilename('fullpath')));
addpath(fullfile(projectRoot, 'src'));
end

function testBaseOnlyReferenceSupportsBothCorrectionSigns(testCase)
imageSize = [120, 160];
[xGrid, ~] = meshgrid(1:imageSize(2), 1:imageSize(1));
base = .55 + .10 * tanh((xGrid - 80) / 18);
frequency = struct( ...
    'base', base, ...
    'mid', nan(imageSize), ...
    'fine', nan(imageSize), ...
    'sourceLuminance', nan(imageSize));
masks = simpleMasks(imageSize, [1, 1, 160, 120]);

[result, diagnostics] = beauty.evenSkinLuminance( ...
    frequency, masks, 100);

verifyGreaterThan(testCase, nnz(diagnostics.positiveSupport), 0);
verifyGreaterThan(testCase, nnz(diagnostics.negativeSupport), 0);
verifyGreaterThanOrEqual(testCase, min(result.baseDelta(:)), -.03);
verifyLessThanOrEqual(testCase, max(result.baseDelta(:)), .03);
verifyEqual(testCase, result.baseDelta, ...
    diagnostics.limitedBaseDelta .* result.supportMap, 'AbsTol', 1e-12);
verifyTrue(testCase, isequaln(frequency.mid, nan(imageSize)));
verifyTrue(testCase, diagnostics.frequencyUnchanged);
end

function testZeroStrengthAndMissingReferenceAreIdentity(testCase)
imageSize = [32, 48];
base = .50 * ones(imageSize);
frequency = struct('base', base, 'mid', zeros(imageSize), ...
    'fine', zeros(imageSize));
masks = simpleMasks(imageSize, [1, 1, 48, 32]);

[zeroResult, zeroDiagnostics] = beauty.evenSkinLuminance( ...
    frequency, masks, 0);
verifyEqual(testCase, zeroResult.baseDelta, zeros(imageSize), ...
    'AbsTol', 1e-12);
verifyEqual(testCase, zeroResult.supportMap, zeros(imageSize), ...
    'AbsTol', 1e-12);
verifyEqual(testCase, zeroDiagnostics.baseCurve, 0, 'AbsTol', 1e-12);

masks.skinMask = zeros(imageSize);
masks.strengthMap = zeros(imageSize);
[emptyResult, emptyDiagnostics] = beauty.evenSkinLuminance( ...
    frequency, masks, 100);
verifyEqual(testCase, emptyResult.baseDelta, zeros(imageSize), ...
    'AbsTol', 1e-12);
verifyEqual(testCase, emptyResult.supportMap, zeros(imageSize), ...
    'AbsTol', 1e-12);
verifyFalse(testCase, emptyDiagnostics.hasReliableReference);
end

function testHardProtectionZeroesBaseSupport(testCase)
imageSize = [64, 80];
[xGrid, ~] = meshgrid(1:imageSize(2), 1:imageSize(1));
frequency = struct('base', .55 + .08 * sin(xGrid / 10), ...
    'mid', zeros(imageSize), 'fine', zeros(imageSize));
masks = simpleMasks(imageSize, [1, 1, 80, 64]);
hard = false(imageSize);
hard(25:35, 32:45) = true;
masks.hardProtectionMask = double(hard);

[result, ~] = beauty.evenSkinLuminance(frequency, masks, 100);
verifyEqual(testCase, result.supportMap(hard), zeros(nnz(hard), 1), ...
    'AbsTol', 1e-12);
verifyEqual(testCase, result.baseDelta(hard), zeros(nnz(hard), 1), ...
    'AbsTol', 1e-12);
end

function testComposeAddsWeightedBaseDeltaOnce(testCase)
imageSize = [24, 32];
image = uint8(ones([imageSize, 3]) * 128);
sourceYcbcr = rgb2ycbcr(im2double(image));
sourceLuminance = sourceYcbcr(:, :, 1);
frequency = struct('sourceLuminance', sourceLuminance, ...
    'base', sourceLuminance, 'mid', zeros(imageSize), ...
    'fine', zeros(imageSize));
masks = simpleMasks(imageSize, [1, 1, 32, 24]);
smoothed = struct('outputLuminance', sourceLuminance, ...
    'alphaMap', zeros(imageSize));
baseResult = struct('baseDelta', .02 * ones(imageSize), ...
    'supportMap', .50 * ones(imageSize));
processing = struct('baseLuminance', baseResult);

[~, diagnostics] = beauty.composeBeautyResult( ...
    image, frequency, smoothed, masks, 0, processing);

verifyEqual(testCase, diagnostics.alphaMap, .50 * ones(imageSize), ...
    'AbsTol', 1e-12);
verifyEqual(testCase, diagnostics.luminanceDelta, .02 * ones(imageSize), ...
    'AbsTol', 1e-12);
verifyEqual(testCase, diagnostics.outputLuminance, ...
    sourceLuminance + .02, 'AbsTol', 1e-12);
end

function testStageContractDrivesProtectionGates(testCase)
%TESTSTAGECONTRACTDRIVESPROTECTIONGATES T16：提供 Base Luminance stage
%   contract 时，feature/reference support 的保护输入只来自 contract
%   （未折叠 structureGate/featureGate 与 hard），不再自行组合 general
%   texture/chroma/structure/hard masks：stage 路径与 legacy 路径逐位
%   等价（bit-exact），扰动 general 保护 masks 不改变 stage 路径输出，
%   缺字段或取值越界 fail-fast。
imageSize = [64, 96];
[xGrid, ~] = meshgrid(1:imageSize(2), 1:imageSize(1));
base = .55 + .10 * tanh((xGrid - 48) / 14);
frequency = struct('base', base, 'mid', zeros(imageSize), ...
    'fine', zeros(imageSize));
masks = simpleMasks(imageSize, [1, 1, 96, 64]);
masks.structureProtectionMask = .60 * double(base > .60);
masks.textureProtectionMask = .30 + .20 * sin(xGrid / 7);
masks.chromaProtectionMask = .25 * ones(imageSize);
masks.toneProtectionMask = masks.chromaProtectionMask;
hardMask = false(imageSize);
hardMask(8:14, 10:22) = true;
masks.hardProtectionMask = double(hardMask);
contract = struct( ...
    'baseLuminance', 1 - (1 - masks.structureProtectionMask) .* ...
    (1 - max(masks.textureProtectionMask, masks.chromaProtectionMask)), ...
    'hard', masks.hardProtectionMask, ...
    'structureGate', 1 - masks.structureProtectionMask, ...
    'featureGate', 1 - max(masks.textureProtectionMask, ...
    masks.chromaProtectionMask));

strengths = [0, 40, 100];
for index = 1:numel(strengths)
    strength = strengths(index);
    [legacyResult, legacyDetails] = beauty.evenSkinLuminance( ...
        frequency, masks, strength);
    [stageResult, stageDetails] = beauty.evenSkinLuminance( ...
        frequency, masks, strength, contract);
    verifyTrue(testCase, isequaln(stageResult, legacyResult), ...
        'stage 路径结果必须与 legacy 路径逐位一致。');
    verifyEqual(testCase, stageDetails.supportMap, ...
        legacyDetails.supportMap, 'AbsTol', 0);
    verifyEqual(testCase, stageDetails.referenceReliability, ...
        legacyDetails.referenceReliability, 'AbsTol', 0);
    verifyEqual(testCase, stageDetails.baseDelta, ...
        legacyDetails.baseDelta, 'AbsTol', 0);
    % runtime 门控积与 T07 快照参考一致（仅 1-x 补码往返舍入）。
    verifyLessThanOrEqual(testCase, max(abs( ...
        stageDetails.structureGate(:) .* stageDetails.featureGate(:) - ...
        stageDetails.baseGateSnapshot(:))), 1e-15);
    % hard identity：hard 区域 supportMap/baseDelta 恒 0。
    verifyEqual(testCase, nnz(stageDetails.supportMap(hardMask)), 0);
    verifyEqual(testCase, nnz(stageDetails.baseDelta(hardMask)), 0);
end

% 负向证明：stage 路径输出对 general 保护 masks 扰动完全不变（只消费
% stage contract），legacy 路径则会随之变化。
[~, legacyDetails60] = beauty.evenSkinLuminance(frequency, masks, 60);
[~, stageDetails60] = beauty.evenSkinLuminance(frequency, masks, 60, ...
    contract);
perturbedMasks = masks;
perturbedMasks.structureProtectionMask = ...
    min(1, masks.structureProtectionMask * .5 + .25);
perturbedMasks.textureProtectionMask = ...
    min(1, masks.textureProtectionMask * .5 + .25);
perturbedMasks.chromaProtectionMask = ...
    min(1, masks.chromaProtectionMask * .5 + .25);
perturbedMasks.toneProtectionMask = perturbedMasks.chromaProtectionMask;
perturbedMasks.hardProtectionMask = ...
    min(1, masks.hardProtectionMask * .5 + .25);
[~, perturbedLegacyDetails] = beauty.evenSkinLuminance( ...
    frequency, perturbedMasks, 60);
[~, perturbedStageDetails] = beauty.evenSkinLuminance( ...
    frequency, perturbedMasks, 60, contract);
verifyTrue(testCase, ...
    nnz(perturbedLegacyDetails.supportMap ~= ...
    legacyDetails60.supportMap) > 0, ...
    '保护 masks 扰动必须确实影响 legacy 路径，否则本断言无意义。');
verifyEqual(testCase, perturbedStageDetails.supportMap, ...
    stageDetails60.supportMap, 'AbsTol', 0);
verifyEqual(testCase, perturbedStageDetails.baseDelta, ...
    stageDetails60.baseDelta, 'AbsTol', 0);

% 缺字段与取值越界 fail-fast：不静默回退拼装。
brokenContract = rmfield(contract, 'structureGate');
verifyError(testCase, @() beauty.evenSkinLuminance( ...
    frequency, masks, 60, brokenContract), ...
    'beauty:InvalidEvenLuminanceInput');
brokenContract = rmfield(contract, 'hard');
verifyError(testCase, @() beauty.evenSkinLuminance( ...
    frequency, masks, 60, brokenContract), ...
    'beauty:InvalidEvenLuminanceInput');
brokenContract = contract;
brokenContract.featureGate = brokenContract.featureGate + .5;
verifyError(testCase, @() beauty.evenSkinLuminance( ...
    frequency, masks, 60, brokenContract), ...
    'beauty:InvalidEvenLuminanceInput');
end

function masks = simpleMasks(imageSize, faceBox)
masks = struct( ...
    'skinMask', ones(imageSize), ...
    'strengthMap', ones(imageSize), ...
    'structureProtectionMask', zeros(imageSize), ...
    'hardProtectionMask', zeros(imageSize), ...
    'textureProtectionMask', zeros(imageSize), ...
    'toneProtectionMask', zeros(imageSize), ...
    'chromaProtectionMask', zeros(imageSize), ...
    'faceBox', faceBox);
end
