function tests = testResidualEyelashCoverageAttribution
%TESTRESIDUALEYELASHCOVERAGEATTRIBUTION 验证 Issue 08.2 空间对应诊断。
tests = functiontests(localfunctions);
end

function setupOnce(~)
testRoot = fileparts(mfilename('fullpath'));
projectRoot = fileparts(testRoot);
addpath(fullfile(projectRoot, 'src'), '-begin');
addpath(testRoot, '-begin');
end

function testManualTruthUsesFixedIndependentAnnotation(testCase)
[mask, metadata] = eyelashManualLashMask77([450, 512], ...
    [102, 248, 177, 48]);
verifyTrue(testCase, islogical(mask));
verifyEqual(testCase, size(mask), [450, 512]);
verifyGreaterThan(testCase, nnz(mask), 0);
verifyTrue(testCase, metadata.diagnosticsIndependent);
verifyTrue(testCase, metadata.fixedAfterAnnotation);
verifyEqual(testCase, metadata.annotationId, '77-manual-lash-v1');
verifyEqual(testCase, metadata.lashRoi, [102, 248, 177, 48]);
verifyEqual(testCase, metadata.sourceImageSize, [450, 512, 3]);
verifyEqual(testCase, metadata.manualPixelCount, nnz(mask));
end

function testManualTruthRejectsNonFixedFixture(testCase)
verifyError(testCase, @() eyelashManualLashMask77( ...
    [450, 512], [103, 248, 177, 48]), ...
    'eyelashManualLashMask77:InvalidLashRoi');
verifyError(testCase, @() eyelashManualLashMask77( ...
    [451, 512], [102, 248, 177, 48]), ...
    'eyelashManualLashMask77:InvalidImageSize');
end

function testCoverageEntryRejectsNonFixedFixtureBeforeProductionRun(testCase)
options = struct('productionRoot', 'E:\image_beauty', ...
    'lashRoi', [103, 248, 177, 48]);
verifyError(testCase, @() diagnoseResidualEyelashCoverageAttribution( ...
    'not-an-image.png', tempdir, options), ...
    'diagnoseResidualEyelashCoverageAttribution:NonFixedFixture');
end

function testFixed77CoverageAttributionWritesRequiredArtifacts(testCase)
projectRoot = fileparts(fileparts(mfilename('fullpath')));
inputPath = fullfile(projectRoot, '人脸', '人脸', '77.png');
outputFolder = fullfile(tempdir, ...
    'image_beauty_issue08_2_eyelash_20260918');
options = struct( ...
    'productionRoot', projectRoot, ...
    'baselinePath', ...
    'C:\Users\JJiio\AppData\Local\Temp\image_beauty_issue02_probe\77_v32_probe.mat', ...
    'faceBox', [95, 79, 286, 372], ...
    'browEyeRoi', [165, 205, 150, 100], ...
    'lashRoi', [102, 248, 177, 48], ...
    'smoothingStrength', 100, ...
    'whiteningStrength', 15);
[summary, diagnostics] = diagnoseResidualEyelashCoverageAttribution( ...
    inputPath, outputFolder, options);

verifyTrue(testCase, summary.completed);
verifyEqual(testCase, summary.issue, '08.2');
verifyEqual(testCase, summary.baseIssue, '08.1');
verifyTrue(testCase, summary.manualLashMaskIndependent);
verifyTrue(testCase, summary.manualLashMaskFixed);
verifyEqual(testCase, summary.manualLashMaskId, '77-manual-lash-v1');
verifyEqual(testCase, summary.lashRoi, [102, 248, 177, 48]);
verifyTrue(testCase, summary.sameMaskRun);
verifyFalse(testCase, summary.runtimeCacheReused);
verifyTrue(testCase, summary.baseToneWhiteningDisabled);
verifyLessThanOrEqual(testCase, summary.originalReconstructionMaxError, ...
    summary.reconstructionTolerance);
verifyGreaterThan(testCase, summary.manualLashMaskPixels, 0);
verifyEqual(testCase, size(diagnostics.manualLashMask), [450, 512]);
verifyEqual(testCase, nnz(diagnostics.manualLashMask), ...
    summary.manualLashMaskPixels);
verifyEqual(testCase, diagnostics.annotation.annotationId, ...
    summary.manualLashMaskId);

requiredPaths = { ...
    'eyelash_manual_lash_mask.png', ...
    'eyelash_manual_lash_overlay.png', ...
    'eyelash_manual_vs_texture_protection.png', ...
    'eyelash_manual_vs_lash_protection.png', ...
    'eyelash_manual_vs_eye_detail_protection.png', ...
    'eyelash_manual_vs_repair_fine.png', ...
    'eyelash_manual_vs_repair_mid.png', ...
    'eyelash_manual_protection_repair_overlay.png', ...
    'eyelash_coverage_attribution.csv', ...
    'eyelash_coverage_attribution.mat'};
for index = 1:numel(requiredPaths)
    verifyTrue(testCase, isfile(fullfile(outputFolder, requiredPaths{index})), ...
        ['缺少 Issue 08.2 产物：' requiredPaths{index}]);
end

metrics = readtable(fullfile(outputFolder, ...
    'eyelash_coverage_attribution.csv'), 'TextType', 'char');
verifyEqual(testCase, height(metrics), 3);
verifyTrue(testCase, all(ismember( ...
    {'manualLash', 'coveredBySoftSupport', 'uncoveredProtectionHole'}, ...
    metrics.scope)));
verifyTrue(testCase, all(metrics.pixels >= 0));
verifyTrue(testCase, all(isfinite(metrics.repairFineMass)));
verifyTrue(testCase, all(isfinite(metrics.repairMidMass)));
verifyTrue(testCase, any(strcmp(summary.case, {'A', 'B', 'C'})));
verifyTrue(testCase, isfield(summary.caseAssessment, ...
    'requiresVisualReview'));
end
