function tests = testBeautyV3
%TESTBEAUTYV3 v3 Mask package 和频率 tracer 测试。
tests = functiontests(localfunctions);
end

function setupOnce(~)
projectRoot = fileparts(fileparts(mfilename('fullpath')));
addpath(fullfile(projectRoot, 'src'));
end

function testPackagesResolveWithSourcePathOnly(testCase)
verifyNotEmpty(testCase, which('masks.buildBeautyMasks'));
verifyNotEmpty(testCase, which('masks.buildTextureProtectionMask'));
verifyNotEmpty(testCase, which('beauty.decomposeSkinFrequency'));
verifyNotEmpty(testCase, which('beauty.smoothSkinTexture'));
verifyNotEmpty(testCase, which('beauty.evenSkinLuminance'));
verifyNotEmpty(testCase, which('beauty.composeBeautyResult'));
end

function testBeautyMasksReturnPurposeSpecificContinuousMaps(testCase)
[image, faceBox, parsing] = fixtureImage(120, 160);
context = prepareBeautyContext(image, faceBox, parsing, ...
    emptyBodyParsing([120, 160]));

[beautyMasks, diagnostics] = masks.buildBeautyMasks( ...
    image, context, faceBox);
requiredFields = {'textureProtectionMask', 'structureProtectionMask', ...
    'chromaProtectionMask', 'toneProtectionMask', 'strengthMap', ...
    'faceStrengthMap', ...
    'nonFaceStrengthMap', 'hardProtectionMask'};
verifyTrue(testCase, all(isfield(beautyMasks, requiredFields)));
for index = 1:numel(requiredFields)
    verifySize(testCase, beautyMasks.(requiredFields{index}), [120, 160]);
end
verifyTrue(testCase, isfield(diagnostics, 'structure'));
verifyTrue(testCase, isfield(diagnostics.structure, 'orientationCoherence'));
verifyEqual(testCase, beautyMasks.chromaProtectionMask, ...
    beautyMasks.toneProtectionMask, 'AbsTol', 0);
verifyGreaterThan(testCase, ...
    mean(beautyMasks.textureProtectionMask(parsing.regions.leftEye > .5)), .5);
verifyGreaterThan(testCase, ...
    mean(beautyMasks.toneProtectionMask(parsing.regions.upperLip > .5)), .5);
verifyGreaterThan(testCase, ...
    mean(beautyMasks.structureProtectionMask(parsing.regions.nose > .5)), 0);
verifyGreaterThan(testCase, ...
    mean(beautyMasks.structureProtectionMask(parsing.regions.neck > .5)), 0);
verifyEqual(testCase, max(beautyMasks.strengthMap( ...
    context.skinMask <= .01)), 0, 'AbsTol', 1e-12);
verifyGreaterThan(testCase, ...
    mean(beautyMasks.faceStrengthMap(parsing.regions.skin > .5)), ...
    mean(beautyMasks.nonFaceStrengthMap(parsing.regions.neck > .5)));

[texture, structure, tone, strength] = masks.buildBeautyMasks( ...
    image, context, faceBox);
verifyEqual(testCase, texture, beautyMasks.textureProtectionMask, ...
    'AbsTol', 1e-12);
verifyEqual(testCase, structure, beautyMasks.structureProtectionMask, ...
    'AbsTol', 1e-12);
verifyEqual(testCase, tone, beautyMasks.toneProtectionMask, ...
    'AbsTol', 1e-12);
verifyEqual(testCase, strength, beautyMasks.strengthMap, ...
    'AbsTol', 1e-12);
end

function testFrequencyDecompositionReconstructsAndKeepsScalesFixed(testCase)
[image, faceBox, parsing] = fixtureImage(96, 128);
context = normalizeBeautyContext(image, faceBox, ...
    prepareBeautyContext(image, faceBox, parsing, ...
    emptyBodyParsing([96, 128])));
[beautyMasks, ~] = masks.buildBeautyMasks(image, context, faceBox);
[frequency, decomposition] = beauty.decomposeSkinFrequency(image, faceBox);
verifyLessThanOrEqual(testCase, decomposition.reconstructionError, 1e-12);
verifyEqual(testCase, frequency.base + frequency.mid + frequency.fine, ...
    frequency.sourceLuminance, 'AbsTol', 1e-12);

strengths = [0, 25, 50, 75, 100];
retentions = zeros(size(strengths));
fineEnergies = zeros(size(strengths));
midRetentions = zeros(size(strengths));
midEnergies = zeros(size(strengths));
for index = 1:numel(strengths)
    [smoothed, details] = beauty.smoothSkinTexture( ...
        frequency, beautyMasks, strengths(index));
    retentions(index) = mean(details.fineActualRetentionMap(:));
    fineEnergies(index) = details.fineEnergyAfter;
    midRetentions(index) = mean(details.midActualRetentionMap(:));
    midEnergies(index) = details.midEnergyAfter;
    verifyEqual(testCase, details.fineActualRetentionMap, ...
        1 - details.alphaMap .* (1 - details.fineRetention), ...
        'AbsTol', 1e-12);
    verifyEqual(testCase, details.midActualRetentionMap, ...
        1 - details.midAlphaMap .* (1 - details.midRetention), ...
        'AbsTol', 1e-12);
    verifyEqual(testCase, smoothed.base, frequency.base, ...
        'AbsTol', 1e-12);
    if strengths(index) == 0
        verifyEqual(testCase, smoothed.mid, frequency.mid, ...
            'AbsTol', 1e-12);
    else
        verifyGreaterThan(testCase, ...
            nnz(abs(smoothed.mid(:) - frequency.mid(:)) > 1e-12), 0);
    end
end
verifyEqual(testCase, retentions(1), 1, 'AbsTol', 1e-12);
verifyTrue(testCase, all(diff(retentions) <= 0));
verifyTrue(testCase, all(diff(fineEnergies) <= 1e-12));
verifyEqual(testCase, midRetentions(1), 1, 'AbsTol', 1e-12);
verifyTrue(testCase, all(diff(midRetentions) <= 0));
verifyTrue(testCase, all(diff(midEnergies) <= 1e-12));
verifyGreaterThan(testCase, retentions(end), .40);
verifyGreaterThan(testCase, midRetentions(end), .50);
end

function testV3PipelineUsesOneAlphaAndPreservesProtectedPixels(testCase)
[image, faceBox, parsing] = fixtureImage(120, 160);
context = prepareBeautyContext(image, faceBox, parsing, ...
    emptyBodyParsing([120, 160]));
params = struct('smoothingStrength', 100, ...
    'whiteningStrength', 50);
[output, diagnostics] = beautifyImage(image, params, faceBox, context);
verifyClass(testCase, output, 'uint8');
verifySize(testCase, output, size(image));
verifyEqual(testCase, output(repmat(diagnostics.beautyMasks.hardProtectionMask >= .999, ...
    [1, 1, 3])), image(repmat(diagnostics.beautyMasks.hardProtectionMask >= .999, ...
    [1, 1, 3])));
verifyEqual(testCase, output(repmat(context.skinMask <= .01, ...
    [1, 1, 3])), image(repmat(context.skinMask <= .01, ...
    [1, 1, 3])));

[frequency, ~] = beauty.decomposeSkinFrequency(image, faceBox);
[beautyMasks, ~] = masks.buildBeautyMasks(image, context, faceBox);
[smoothed, ~] = beauty.smoothSkinTexture(frequency, beautyMasks, 100);
[~, diagnostics] = beauty.composeBeautyResult( ...
    image, frequency, smoothed, beautyMasks, 50);
verifyEqual(testCase, diagnostics.alphaMap, ...
    max(smoothed.alphaMap, diagnostics.whiteningSupport), ...
    'AbsTol', 1e-12);
end

function testStageProtectionGatesReproduceProductionGating(testCase)
%TESTSTAGEPROTECTIONGATESREPRODUCEPRODUCTIONGATING T07：八个 stage
%   protection 字段满足唯一语义与 [0,1]；hard 可严格离散化（二值）且
%   nostrilCore/lashCore 的 hard identity 原样保留；用 stage protection
%   重算各生产 stage 的兼容门控，与生产诊断逐像素等价（容差仅为
%   1-x 补码往返与乘法结合顺序的浮点噪声，不放宽行为）。
[image, faceBox, parsing] = fixtureImage(120, 160);
context = prepareBeautyContext(image, faceBox, parsing, ...
    emptyBodyParsing([120, 160]));
[beautyMasks, maskDiagnostics] = masks.buildBeautyMasks( ...
    image, context, faceBox);
protection = masks.buildStageProtectionMasks(beautyMasks);

% T31/T32/T33：发布规范双门控 target.*/support.*（+ 独立 hard、过渡扁平
% 字段 noseMidProtection/regionBand*、门源 toneGates/whiteningGates 与鼻部
% 幅度上限 whiteningAmplitudeCeiling）。T07 的扁平折叠名 smoothingFine/
% smoothingMid/repairFine/repairMid/baseLuminance/tone/whitening 已被
% target.* 取代并删除（同一语义只留一个规范字段）。
stageNames = {'hard'; 'target'; 'support'; 'noseMidProtection'; ...
    'toneGates'; 'whiteningGates'; 'whiteningAmplitudeCeiling'; ...
    'regionBandFine'; 'regionBandMid'; 'regionBandBase'; ...
    'regionBandTone'; 'regionBandWhitening'};
verifyEqual(testCase, fieldnames(protection), stageNames);
verifyFalse(testCase, any(isfield(protection, ...
    {'baseLuminance', 'tone', 'whitening'})), ...
    'T32/T33 起旧扁平折叠名 baseLuminance/tone/whitening 必须删除。');
targetNames = {'smoothingFine'; 'smoothingMid'; 'repairFine'; ...
    'repairMid'; 'baseLuminance'; 'tone'; 'whitening'};
for index = 1:numel(stageNames)
    name = stageNames{index};
    value = protection.(name);
    if strcmp(name, 'target') || strcmp(name, 'support')
        verifyEqual(testCase, fieldnames(value), targetNames);
        for innerIndex = 1:numel(targetNames)
            inner = value.(targetNames{innerIndex});
            verifyTrue(testCase, isnumeric(inner) && ~islogical(inner) && ...
                isreal(inner));
            verifySize(testCase, inner, [120, 160]);
            verifyTrue(testCase, all(isfinite(inner(:))));
            verifyGreaterThanOrEqual(testCase, min(inner(:)), 0);
            verifyLessThanOrEqual(testCase, max(inner(:)), 1);
        end
        continue;
    end
    if strcmp(name, 'toneGates') || strcmp(name, 'whiteningGates')
        % T33 门源：未折叠门控因子，逐像素 [0,1]，与 target/support 同口径。
        if strcmp(name, 'toneGates')
            gateNames = {'structureGate'; 'featureGate'; ...
                'uniformFeatureGate'};
        else
            gateNames = {'structureGate'; 'featureGate'};
        end
        verifyEqual(testCase, fieldnames(value), gateNames);
        for innerIndex = 1:numel(gateNames)
            inner = value.(gateNames{innerIndex});
            verifyTrue(testCase, isnumeric(inner) && ~islogical(inner) && ...
                isreal(inner));
            verifySize(testCase, inner, [120, 160]);
            verifyTrue(testCase, all(isfinite(inner(:))));
            verifyGreaterThanOrEqual(testCase, min(inner(:)), 0);
            verifyLessThanOrEqual(testCase, max(inner(:)), 1);
        end
        continue;
    end
    if strcmp(name, 'whiteningAmplitudeCeiling')
        % T33 鼻部退让幅度上限：正标量（无鼻部结构时为 Inf）。
        verifyTrue(testCase, isnumeric(value) && ~islogical(value) && ...
            isreal(value) && isscalar(value) && ~isnan(value));
        verifyGreaterThan(testCase, value, 0);
        continue;
    end
    verifyTrue(testCase, isnumeric(value) && ~islogical(value) && ...
        isreal(value));
    verifySize(testCase, value, [120, 160]);
    verifyTrue(testCase, all(isfinite(value(:))));
    verifyGreaterThanOrEqual(testCase, min(value(:)), 0);
    verifyLessThanOrEqual(testCase, max(value(:)), 1);
end

% hard：二值 identity，与生产 hardProtectionMask bit-exact；
% nostrilCore/lashCore/lipCore 全部保留在 hard 内。
verifyEqual(testCase, protection.hard, ...
    beautyMasks.hardProtectionMask, 'AbsTol', 0);
verifyEqual(testCase, protection.hard, ...
    double(maskDiagnostics.texture.hardProtectionMask), 'AbsTol', 0);
verifyTrue(testCase, all(protection.hard(:) == 0 | ...
    protection.hard(:) == 1));
identityCore = maskDiagnostics.texture.lipCore | ...
    maskDiagnostics.texture.nostrilCore | ...
    maskDiagnostics.texture.lashCore;
verifyTrue(testCase, nnz(identityCore) > 0);
verifyTrue(testCase, all(protection.hard(identityCore) == 1), ...
    'nostrilCore/lashCore 的 hard identity 必须原样保留。');

% Fine/Mid smoothing：alphaMap 与 midAlphaMap 用 stage fields 重算。
[frequency, ~] = beauty.decomposeSkinFrequency(image, faceBox);
strengths = [0, 25, 50, 75, 100];
for index = 1:numel(strengths)
    strength = strengths(index);
    [smoothed, details] = beauty.smoothSkinTexture(frequency, ...
        beautyMasks, strength);
    profile = beautySmoothingProfile(strength);
    effectStrength = profile.alphaCurve .* beautyMasks.strengthMap;
    nonFacePixels = beautyMasks.nonFaceStrengthMap > .01;
    effectStrength(nonFacePixels) = profile.outsideFaceStrength .* ...
        beautyMasks.nonFaceStrengthMap(nonFacePixels);
    fineGate = 1 - max(protection.target.smoothingFine, protection.hard);
    verifyEqual(testCase, details.alphaMap, effectStrength .* fineGate, ...
        'AbsTol', 1e-12);

    midGate = 1 - protection.target.smoothingMid;
    midRecomputed = details.alphaMap .* midGate;
    nosePixels = beautyMasks.noseMask > 0;
    if profile.alphaCurve == 1
        % 满档（alphaCurve=1）：mid 门控整体与生产逐像素等价。
        verifyEqual(testCase, details.midAlphaMap, midRecomputed, ...
            'AbsTol', 1e-12);
    else
        % 静态结构部分全场等价；nose 项生产值为快照与 1 的凸组合
        % （快照即最强保护），逐像素核对凸组合差值。
        verifyEqual(testCase, details.midAlphaMap(~nosePixels), ...
            midRecomputed(~nosePixels), 'AbsTol', 1e-12);
        midGap = details.midAlphaMap(nosePixels) - ...
            midRecomputed(nosePixels);
        expectedGap = details.alphaMap(nosePixels) .* ...
            details.fineStructureGate(nosePixels) .* ...
            (.50 * (1 - profile.alphaCurve));
        verifyGreaterThanOrEqual(testCase, min(midGap), 0);
        verifyEqual(testCase, midGap, expectedGap, 'AbsTol', 1e-9);
    end
end

% Repair：零瑕疵参考点的生产 structureGate（blemish=0）与
% textureGate/noseMidGate 的组合必须 bit-exact 重建两个 target 字段。
blemishMap = zeros(size(image, 1), size(image, 2));
[~, repairDetails] = beauty.repairSkinBlemishes(smoothed, beautyMasks, ...
    blemishMap, 50);
verifyEqual(testCase, protection.target.repairFine, ...
    1 - repairDetails.structureGate .* ...
    (1 - beautyMasks.textureProtectionMask), 'AbsTol', 0);
verifyEqual(testCase, protection.target.repairMid, ...
    1 - repairDetails.structureGate .* (1 - .50 * beautyMasks.noseMask) .* ...
    (1 - beautyMasks.textureProtectionMask), 'AbsTol', 0);

% Base luminance：supportMap 完整重算（该 stage 无 runtime 耦合）。
% T32：逐像素门来自 target.baseLuminance，T30 纯 policy 带经
% regionBandGate = 1 - regionBandBase 单独注入（本 fixture 零带，恒等 1）。
[~, baseDetails] = beauty.evenSkinLuminance(frequency, beautyMasks, 50);
baseSupport = baseDetails.baseWeightCurve .* ...
    baseDetails.regionalSkinWeight .* ...
    (1 - protection.target.baseLuminance) .* (1 - protection.hard) .* ...
    (1 - protection.regionBandBase) .* baseDetails.referenceCoverage;
verifyEqual(testCase, baseDetails.supportMap, baseSupport, 'AbsTol', 1e-12);

% Tone：主 weight 分支重算（s=25 时 uniform 分支未激活）。
[~, toneDetails] = beauty.normalizeSkinTone(image, frequency, ...
    beautyMasks, blemishMap, 25);
profile25 = beautySmoothingProfile(25);
toneCurveMap = profile25.toneStrength + ((25 / 100) ^ .85 - ...
    profile25.toneStrength) .* smoothStep( ...
    toneDetails.chromaEvidence, .25, .65);
toneCurveMap = max(toneCurveMap, ...
    (25 / 100) ^ .85 .* toneDetails.localChromaEvidence);
toneAllowed = min(beautyMasks.skinMask, beautyMasks.strengthMap) .* ...
    (1 - protection.hard);
evidenceTerm = .08 + .35 * toneDetails.chromaEvidence + ...
    .35 * toneDetails.localChromaEvidence + ...
    .20 * toneDetails.blemishEvidence;
toneWeight = min(max(toneCurveMap .* toneAllowed .* ...
    (1 - protection.target.tone) .* evidenceTerm, 0), .55);
verifyEqual(testCase, toneDetails.weightMap, toneWeight, 'AbsTol', 1e-12);

% T33：tone 门源由 policy 发布，执行层按生产原位相乘——主分支门控积
% structureGate·featureGate 与 1 - target.tone 一致（仅 1-x 补码往返
% 舍入），uniform 分支更强（≤ 快照）。
verifyLessThanOrEqual(testCase, max(abs( ...
    protection.toneGates.structureGate(:) .* ...
    protection.toneGates.featureGate(:) - ...
    (1 - protection.target.tone(:)))), 1e-15);
verifyLessThanOrEqual(testCase, max( ...
    protection.toneGates.structureGate(:) .* ...
    protection.toneGates.uniformFeatureGate(:) - ...
    (1 - protection.target.tone(:))), 1e-15);

% Whitening：supportMap 完整重算（该 stage 无 runtime 耦合）。
[~, whiteningDetails] = beauty.applySkinWhitening(image, frequency, ...
    beautyMasks, 50);
whiteningAllowed = min(beautyMasks.skinMask, beautyMasks.strengthMap) .* ...
    (1 - protection.hard);
faceSkin = beautyMasks.faceSkinMask >= .5;
whiteningAllowed(faceSkin) = max(whiteningAllowed(faceSkin), .85);
whiteningSupport = min(max((50 / 100) ^ .85 .* whiteningAllowed .* ...
    whiteningDetails.highlightProtection .* ...
    (1 - protection.target.whitening), 0), 1);
verifyEqual(testCase, whiteningDetails.supportMap, whiteningSupport, ...
    'AbsTol', 1e-12);

% T33：whitening 门源同理——门控积与 1 - target.whitening 一致（仅 1-x
% 补码往返舍入）；幅度上限为 policy 发布的标量，本 fixture 含鼻部结构
% 故上限为 .07，且执行层按 min(.20*curve, ceiling) 与旧分支逐位同式。
verifyLessThanOrEqual(testCase, max(abs( ...
    protection.whiteningGates.structureGate(:) .* ...
    protection.whiteningGates.featureGate(:) - ...
    (1 - protection.target.whitening(:)))), 1e-15);
if any(beautyMasks.noseMask(:) > .5)
    expectedCeiling = .07;
else
    expectedCeiling = Inf;
end
verifyEqual(testCase, protection.whiteningAmplitudeCeiling, ...
    expectedCeiling, 'AbsTol', 0);
end

function testSupportGatesAreCanonicalAndBitEqualLegacy(testCase)
%TESTSUPPORTGATESARECANONICALANDBITEQUALLegacy T31：protection 层发布规范
%   双门控 target.*/support.*，同一语义只留一个规范字段（T07 扁平折叠名
%   smoothingFine/smoothingMid/repairFine/repairMid 已删除）。
%   target.* 的零带值逐位等于 T07 折叠式；support.* 的零带值逐位等于
%   T30 之前各 stage 参考池/结构锚点的等价门（补码逐位还原生产门控）。
[image, faceBox, parsing] = fixtureImage(120, 160);
context = prepareBeautyContext(image, faceBox, parsing, ...
    emptyBodyParsing([120, 160]));
[beautyMasks, ~] = masks.buildBeautyMasks(image, context, faceBox);
protection = masks.buildStageProtectionMasks(beautyMasks);

% 同一语义只留一个规范字段：旧扁平折叠名必须已删除。
verifyFalse(testCase, any(isfield(protection, ...
    {'smoothingFine', 'smoothingMid', 'repairFine', 'repairMid'})), ...
    'T07 扁平折叠名必须被 target.* 取代并删除。');

texture = double(beautyMasks.textureProtectionMask);
structure = double(beautyMasks.structureProtectionMask);
hard = double(beautyMasks.hardProtectionMask);
nose = double(beautyMasks.noseMask);

% support.*：零带值逐位等于 legacy 参考池等价门。
verifyEqual(testCase, protection.support.smoothingFine, ...
    max(cat(3, texture, structure, hard), [], 3), 'AbsTol', 0, ...
    'support.smoothingFine 必须逐位等于 legacy 合并 protectionMask。');
verifyEqual(testCase, protection.support.smoothingFine, ...
    beautyMasks.protectionMask, 'AbsTol', 0);
verifyEqual(testCase, protection.support.smoothingMid, ...
    min(4 * structure, 1), 'AbsTol', 0);
verifyEqual(testCase, 1 - protection.support.smoothingMid, ...
    max(0, 1 - 4 * structure), 'AbsTol', 0, ...
    '补码必须逐位还原 legacy fineStructureGate。');
verifyEqual(testCase, protection.support.repairFine, texture, 'AbsTol', 0);
verifyEqual(testCase, 1 - protection.support.repairFine, ...
    1 - texture, 'AbsTol', 0, '补码必须逐位还原 legacy textureGate。');
verifyEqual(testCase, protection.support.repairMid, structure, 'AbsTol', 0);

% target.*：零带值逐位等于 T07 折叠式。
fineStructureGate = max(0, 1 - 4 * structure);
verifyEqual(testCase, protection.target.smoothingFine, ...
    1 - (1 - texture) .* fineStructureGate, 'AbsTol', 0);
verifyEqual(testCase, protection.target.smoothingMid, ...
    1 - fineStructureGate .* (1 - .50 * nose), 'AbsTol', 0);
strongStructure = smoothStep(structure, .70, .90) .* ...
    double(bwdist(hard >= .999) <= 3);
structureGateRepair = min(1 - structure, 1 - .65 * strongStructure);
verifyEqual(testCase, protection.target.repairFine, ...
    1 - structureGateRepair .* (1 - texture), 'AbsTol', 0);
verifyEqual(testCase, protection.target.repairMid, ...
    1 - structureGateRepair .* (1 - .50 * nose) .* (1 - texture), ...
    'AbsTol', 0);

% hard 独立发布，严格二值，不参与 target/support 的 max 折叠。
verifyEqual(testCase, protection.hard, hard, 'AbsTol', 0);
verifyTrue(testCase, all(protection.hard(:) == 0 | protection.hard(:) == 1));
verifyEqual(testCase, protection.noseMidProtection, .50 * nose, 'AbsTol', 0);
end

function testFineSmoothingConsumesStageProtectionContract(testCase)
%TESTFINESMOOTHINGCONSUMESSTAGEPROTECTIONCONTRACT T12：提供 stage
%   contract（protection 分层）时，Fine smoothing 只从
%   protection.target.smoothingFine / protection.hard 派生 Fine 门控，不再自行
%   解释 general texture/structure masks：扰动 textureProtectionMask 不
%   改变 stage 路径的任何输出，而 legacy 路径会随之变化。统计路径
%   （processableSkin → fineEnergy/blemishMean/fineRetention）改读生产
%   端合并 protectionMask，与旧 max(texture,structure,hard) bit-exact
%   同值；strength、频段分解与合成公式不变（Mid 门控自 T13 起迁移至
%   stage contract，见 testMidSmoothingConsumesStageProtectionContract）。
%   Fine alpha 与输出增量相对 legacy 仅有 1-x 补码与乘法结合顺序的
%   浮点噪声（≤1e-15，T07 推导基线 1.11e-16 同量级）。
[image, faceBox, parsing] = fixtureImage(120, 160);
context = prepareBeautyContext(image, faceBox, parsing, ...
    emptyBodyParsing([120, 160]));
[beautyMasks, ~] = masks.buildBeautyMasks(image, context, faceBox);
protection = masks.buildStageProtectionMasks(beautyMasks);
[frequency, ~] = beauty.decomposeSkinFrequency(image, faceBox);
[blemishMap, ~] = beauty.buildBlemishMap(image, frequency, beautyMasks);

% 统计路径数据源：合并 protectionMask 与 max(texture, structure, hard)
% 必须逐像素 bit-exact，保证可处理皮肤统计口径不变。
combinedProtection = max(cat(3, beautyMasks.textureProtectionMask, ...
    beautyMasks.structureProtectionMask, ...
    beautyMasks.hardProtectionMask), [], 3);
verifyEqual(testCase, beautyMasks.protectionMask, combinedProtection, ...
    'AbsTol', 0);

strengths = [0, 25, 50, 75, 100];
for index = 1:numel(strengths)
    strength = strengths(index);
    [smoothedLegacy, legacyDetails] = beauty.smoothSkinTexture( ...
        frequency, beautyMasks, strength, blemishMap);
    [smoothedStage, stageDetails] = beauty.smoothSkinTexture( ...
        frequency, beautyMasks, strength, blemishMap, protection);

    % stage 路径 Fine alpha 恰为 stage contract 重算（统一语义
    % gate = 1 - max(field, hard)），bit-exact；hard identity 保持。
    profile = beautySmoothingProfile(strength);
    effectStrength = profile.alphaCurve .* beautyMasks.strengthMap;
    nonFacePixels = beautyMasks.nonFaceStrengthMap > .01;
    effectStrength(nonFacePixels) = profile.outsideFaceStrength .* ...
        beautyMasks.nonFaceStrengthMap(nonFacePixels);
    verifyEqual(testCase, stageDetails.alphaMap, ...
        effectStrength .* (1 - max(protection.target.smoothingFine, ...
        protection.hard)), 'AbsTol', 0);
    verifyEqual(testCase, ...
        nnz(stageDetails.alphaMap(protection.hard >= .999)), 0);

    % 与 legacy 路径的等价性：alpha 与 Fine/Mid 输出增量仅浮点噪声；
    % 统计标量与合并保护图 bit-exact 不变；结构锚点同值（T13 起 Mid
    % 门控契约见 testMidSmoothingConsumesStageProtectionContract）。
    verifyLessThanOrEqual(testCase, ...
        max(abs(stageDetails.alphaMap(:) - legacyDetails.alphaMap(:))), ...
        1e-15);
    verifyLessThanOrEqual(testCase, ...
        max(abs(smoothedStage.fine(:) - smoothedLegacy.fine(:))), 1e-15);
    verifyLessThanOrEqual(testCase, ...
        max(abs(smoothedStage.mid(:) - smoothedLegacy.mid(:))), 1e-15);
    verifyEqual(testCase, stageDetails.fineEnergy, ...
        legacyDetails.fineEnergy, 'AbsTol', 0);
    verifyEqual(testCase, stageDetails.blemishMean, ...
        legacyDetails.blemishMean, 'AbsTol', 0);
    verifyEqual(testCase, stageDetails.fineRetention, ...
        legacyDetails.fineRetention, 'AbsTol', 0);
    verifyEqual(testCase, stageDetails.protectionMask, ...
        legacyDetails.protectionMask, 'AbsTol', 0);
    verifyEqual(testCase, stageDetails.fineStructureGate, ...
        legacyDetails.fineStructureGate, 'AbsTol', 0);
    verifyEqual(testCase, stageDetails.midStructureGate, ...
        legacyDetails.midStructureGate, 'AbsTol', 0);
    verifyLessThanOrEqual(testCase, ...
        max(abs(stageDetails.midAlphaMap(:) - ...
        legacyDetails.midAlphaMap(:))), 1e-15);
    % 合成公式与 base identity 不变。
    verifyEqual(testCase, smoothedStage.base, frequency.base, 'AbsTol', 0);
    verifyEqual(testCase, stageDetails.fineRetentionMap, ...
        1 - stageDetails.alphaMap .* (1 - stageDetails.fineRetention), ...
        'AbsTol', 0);
end

% 负向证明：stage 路径的输出对 textureProtectionMask 扰动完全不变
% （Fine 不再读取该字段），legacy 路径则会随之改变。
perturbedMasks = beautyMasks;
perturbedMasks.textureProtectionMask = ...
    min(1, beautyMasks.textureProtectionMask * .5 + .25);
[smoothedPerturbedLegacy, perturbedLegacyDetails] = ...
    beauty.smoothSkinTexture(frequency, perturbedMasks, 60, blemishMap);
[smoothedPerturbedStage, perturbedStageDetails] = ...
    beauty.smoothSkinTexture(frequency, perturbedMasks, 60, blemishMap, ...
    protection);
[smoothedStage60, stageDetails60] = beauty.smoothSkinTexture( ...
    frequency, beautyMasks, 60, blemishMap, protection);
[~, unperturbedLegacyDetails60] = beauty.smoothSkinTexture( ...
    frequency, beautyMasks, 60, blemishMap);
verifyTrue(testCase, ...
    nnz(perturbedLegacyDetails.alphaMap ~= ...
    unperturbedLegacyDetails60.alphaMap) > 0, ...
    'texture 扰动必须确实影响 legacy 路径，否则本断言无意义。');
verifyEqual(testCase, perturbedStageDetails.alphaMap, ...
    stageDetails60.alphaMap, 'AbsTol', 0);
verifyEqual(testCase, smoothedPerturbedStage.fine, ...
    smoothedStage60.fine, 'AbsTol', 0);
verifyEqual(testCase, smoothedPerturbedStage.mid, ...
    smoothedStage60.mid, 'AbsTol', 0);
end

function testMidSmoothingConsumesStageProtectionContract(testCase)
%TESTMIDSMOOTHINGCONSUMESSTAGEPROTECTIONCONTRACT T13：提供 stage
%   contract 时，Mid smoothing 只从 protection.target.smoothingMid 派生 Mid
%   门控，不再读取 noseMask/局部 nose 特判。快照 smoothingMid 取
%   alphaCurve=1 满档（T07），生产 noseMidGate 的强度插值归属
%   effect-strength 侧：midGate = alphaCurve .* (1 - smoothingMid) +
%   (1 - alphaCurve) .* fineStructureGate。该凸组合代数上恒等于生产
%   门控 fineStructureGate .* (1 - .50*nose.*alphaCurve)（快照为最强
%   保护端点，强度无关结构锚点为零 nose 保护端点），与生产仅差乘法
%   结合顺序与 1-x 补码往返的浮点噪声（≤1e-15，T07 推导基线
%   1.11e-16 同量级）。诊断收口：stage 路径不再报告 noseMask/
%   noseMidGate，新增 midGate 快照；legacy 路径字段不变。
[image, faceBox, parsing] = fixtureImage(120, 160);
context = prepareBeautyContext(image, faceBox, parsing, ...
    emptyBodyParsing([120, 160]));
[beautyMasks, ~] = masks.buildBeautyMasks(image, context, faceBox);
protection = masks.buildStageProtectionMasks(beautyMasks);
[frequency, ~] = beauty.decomposeSkinFrequency(image, faceBox);
[blemishMap, ~] = beauty.buildBlemishMap(image, frequency, beautyMasks);
verifyTrue(testCase, nnz(beautyMasks.noseMask > 0) > 0, ...
    'fixture 必须包含非空 noseMask，否则 nose 特判退役断言无意义。');

strengths = [0, 25, 50, 75, 100];
for index = 1:numel(strengths)
    strength = strengths(index);
    [smoothedLegacy, legacyDetails] = beauty.smoothSkinTexture( ...
        frequency, beautyMasks, strength, blemishMap);
    [smoothedStage, stageDetails] = beauty.smoothSkinTexture( ...
        frequency, beautyMasks, strength, blemishMap, protection);
    profile = beautySmoothingProfile(strength);

    % Mid 门控恰为 stage contract 凸组合重算（bit-exact），且与生产
    % 组合式 midStructureGate .* noseMidGate 只差浮点噪声（≤1e-15）；
    % T31 起 noseMidGate 由 policy 层从 nose 保护发布，算法侧不再持有。
    expectedMidGate = profile.alphaCurve .* ...
        (1 - protection.target.smoothingMid) + ...
        (1 - profile.alphaCurve) .* stageDetails.fineStructureGate;
    verifyEqual(testCase, stageDetails.midGate, expectedMidGate, ...
        'AbsTol', 0);
    verifyEqual(testCase, stageDetails.midAlphaMap, ...
        stageDetails.alphaMap .* stageDetails.midGate, 'AbsTol', 0);
    noseMidGate = 1 - .50 * beautyMasks.noseMask .* profile.alphaCurve;
    verifyLessThanOrEqual(testCase, ...
        max(abs(stageDetails.midGate(:) - ...
        legacyDetails.midStructureGate(:) .* noseMidGate(:))), 1e-15);
    verifyLessThanOrEqual(testCase, ...
        max(abs(stageDetails.midAlphaMap(:) - ...
        legacyDetails.midAlphaMap(:))), 1e-15);
    verifyLessThanOrEqual(testCase, ...
        max(abs(smoothedStage.mid(:) - smoothedLegacy.mid(:))), 1e-15);

    % 结构锚点与统计路径保持生产原值；base identity 与合成公式不变。
    verifyEqual(testCase, stageDetails.midStructureGate, ...
        legacyDetails.midStructureGate, 'AbsTol', 0);
    verifyEqual(testCase, stageDetails.fineEnergy, ...
        legacyDetails.fineEnergy, 'AbsTol', 0);
    verifyEqual(testCase, smoothedStage.base, frequency.base, ...
        'AbsTol', 0);
    verifyEqual(testCase, stageDetails.midRetentionMap, ...
        1 - stageDetails.midAlphaMap .* ...
        (1 - stageDetails.midRetention), 'AbsTol', 0);
end

% 满档端点（alphaCurve=1）：Mid 门控恰为 T07 已验证的快照重算
% midAlphaMap = alphaMap .* (1 - smoothingMid)（≤1e-15 噪声）。
[~, stageDetails100] = beauty.smoothSkinTexture(frequency, ...
    beautyMasks, 100, blemishMap, protection);
verifyLessThanOrEqual(testCase, ...
    max(abs(stageDetails100.midAlphaMap(:) - ...
    stageDetails100.alphaMap(:) .* (1 - protection.target.smoothingMid(:)))), ...
    1e-15);

% 零强度端点（alphaCurve=0）：凸组合退化为纯结构锚点，Mid 保留率恒 1。
[smoothedStage0, stageDetails0] = beauty.smoothSkinTexture(frequency, ...
    beautyMasks, 0, blemishMap, protection);
verifyEqual(testCase, stageDetails0.midGate, ...
    stageDetails0.fineStructureGate, 'AbsTol', 0);
verifyEqual(testCase, smoothedStage0.mid, frequency.mid, 'AbsTol', 0);

% 负向证明：stage 路径的 Mid 输出对 noseMask 扰动完全不变（Mid 不再
% 读取该字段），legacy 路径则会随之变化。
perturbedMasks = beautyMasks;
perturbedMasks.noseMask = min(1, beautyMasks.noseMask * .5 + .25);
[smoothedPerturbedStage, perturbedStageDetails] = ...
    beauty.smoothSkinTexture(frequency, perturbedMasks, 60, ...
    blemishMap, protection);
[smoothedStage60, stageDetails60] = beauty.smoothSkinTexture( ...
    frequency, beautyMasks, 60, blemishMap, protection);
[~, perturbedLegacyDetails] = beauty.smoothSkinTexture( ...
    frequency, perturbedMasks, 60, blemishMap);
[~, legacyDetails60] = beauty.smoothSkinTexture( ...
    frequency, beautyMasks, 60, blemishMap);
verifyTrue(testCase, ...
    nnz(perturbedLegacyDetails.midAlphaMap ~= ...
    legacyDetails60.midAlphaMap) > 0, ...
    'noseMask 扰动必须确实影响 legacy 路径，否则本断言无意义。');
verifyEqual(testCase, perturbedStageDetails.midAlphaMap, ...
    stageDetails60.midAlphaMap, 'AbsTol', 0);
verifyEqual(testCase, smoothedPerturbedStage.mid, ...
    smoothedStage60.mid, 'AbsTol', 0);

% 诊断收口：T31 起算法侧不再持有 nose 语义，两条入口都只报告
% protection（= support.smoothingFine 参考样本池门）与单一 midGate 快照，
% 不再报告 noseMask/noseMidGate。
verifyEqual(testCase, ...
    isfield(stageDetails60, {'noseMask', 'noseMidGate'}), ...
    [false, false], ...
    'smoothing 诊断不得再报告 nose 特判字段。');
verifyTrue(testCase, isfield(stageDetails60, 'midGate'));
verifyEqual(testCase, ...
    isfield(legacyDetails60, {'noseMask', 'noseMidGate'}), ...
    [false, false], ...
    '兼容入口同样不得再报告 nose 特判字段。');
end

function testFineRepairConsumesStageProtectionContract(testCase)
%TESTFINEREPAIRCONSUMESSTAGEPROTECTIONCONTRACT T14：提供生产端拼装的
%   Fine repair stage contract 时，fineWeight 门控只按生产原式从
%   contract 重建（前置结构门 = 1 - support.repairMid，截断后纹理门 =
%   1 - target.repairFine），不再自行组合 general texture/structure/hard
%   masks：扰动 textureProtectionMask 不改变 stage 路径的 fineWeight，
%   legacy 路径则会随之变化。生产链在结构门与纹理门之间对权重做
%   [0,1] 截断，且快照 repairFine 的 1-x 补码往返有舍入，因此 texture
%   不折叠进门控积：快照 repairFine 作为零瑕疵参考门消费（诊断
%   fineGateZeroBlemish），runtime 放宽量由生产端在零瑕疵参考门上重
%   建后随 contract 传入未折叠字段，消费侧与 legacy 路径逐位等价
%   （bit-exact）。v3.2 texture linear gate 的有效结果完整保留；Mid
%   权重、chromaWeight 与共享 referenceReliability 自 T15 起同样收口
%   到 stage contract（bit-exact 重建，下列共享路径断言保留为迁移等
%   价证明）。
[image, faceBox, parsing] = fixtureImage(120, 160);
context = prepareBeautyContext(image, faceBox, parsing, ...
    emptyBodyParsing([120, 160]));
[beautyMasks, ~] = masks.buildBeautyMasks(image, context, faceBox);
protection = masks.buildStageProtectionMasks(beautyMasks);
[frequency, ~] = beauty.decomposeSkinFrequency(image, faceBox);
[realBlemishMap, ~] = beauty.buildBlemishMap(image, frequency, beautyMasks);

% 注入高置信瑕疵证据：皮肤上的紧凑斑点（低局部密度，不触发
% sparseGate 抑制），其中两枚落在眼周 hard 特征 3px 带与鼻部结构保护
% 区，使 blemish 放宽量与 strongStructure 上限同时参与重建；真实
% buildBlemishMap 产物与零瑕疵参考各测一组。
[height, width] = size(image(:, :, 1));
[xGrid, yGrid] = meshgrid(1:width, 1:height);
injectedBlemish = zeros(height, width);
dotCenters = [44, 68; 55, 80; 70, 60; 80, 100; 60, 120; 35, 110; ...
    88, 66; 50, 45];
for dotIndex = 1:size(dotCenters, 1)
    injectedBlemish = max(injectedBlemish, .95 * exp( ...
        -((xGrid - dotCenters(dotIndex, 2)) .^ 2 + ...
        (yGrid - dotCenters(dotIndex, 1)) .^ 2) / (2 * 2.2 ^ 2)));
end
verifyTrue(testCase, max(injectedBlemish(:)) > .90, ...
    '注入斑点必须达到高置信瑕疵。');
verifyTrue(testCase, ...
    nnz(injectedBlemish(:) .* ...
    beautyMasks.structureProtectionMask(:)) > 0, ...
    '注入瑕疵必须与结构保护重叠，否则 blemish 放宽量重建未被覆盖。');
injectedSmoothed = beauty.smoothSkinTexture(frequency, beautyMasks, ...
    60, injectedBlemish, protection);
[~, injectedRepairDetails] = beauty.repairSkinBlemishes( ...
    injectedSmoothed, beautyMasks, injectedBlemish, 60);
verifyTrue(testCase, ...
    nnz(injectedRepairDetails.fineWeight) > 0, ...
    '注入斑点必须产生非零 fineWeight，否则 texture 门控断言无意义。');

strengths = [0, 25, 50, 75, 100];
blemishCases = {zeros(height, width), realBlemishMap, injectedBlemish};
for caseIndex = 1:numel(blemishCases)
    blemishMap = blemishCases{caseIndex};
    contract = makeTestRepairContract(beautyMasks, protection, ...
        blemishMap);
    for index = 1:numel(strengths)
        strength = strengths(index);
        [smoothed, ~] = beauty.smoothSkinTexture(frequency, ...
            beautyMasks, strength, blemishMap, protection);
        [repairedLegacy, legacyDetails] = ...
            beauty.repairSkinBlemishes(smoothed, beautyMasks, ...
            blemishMap, strength);
        [repairedStage, stageDetails] = ...
            beauty.repairSkinBlemishes(smoothed, beautyMasks, ...
            blemishMap, strength, contract);

        % stage 门控恰为 contract 按生产原式重建（bit-exact）：
        % 前置结构门 = 1 - contract.support.repairMid。
        verifyEqual(testCase, stageDetails.fineGateRuntime, ...
            1 - contract.support.repairMid, 'AbsTol', 0);

        % 与 legacy 路径逐位等价：T14 迁移不改变任何数值。
        verifyEqual(testCase, stageDetails.fineWeight, ...
            legacyDetails.fineWeight, 'AbsTol', 0);
        verifyEqual(testCase, stageDetails.fineCorrection, ...
            legacyDetails.fineCorrection, 'AbsTol', 0);
        verifyEqual(testCase, repairedStage.fine, repairedLegacy.fine, ...
            'AbsTol', 0);
        verifyEqual(testCase, repairedStage.alphaMap, ...
            repairedLegacy.alphaMap, 'AbsTol', 0);

        % 零瑕疵快照语义（T07 衔接）：blemish = 0 时 stage 门控积与
        % 1 - protection.target.repairFine 一致（仅 1-x 补码往返舍入）；
        % blemish > 0 时相对快照只增不减（runtime 放宽约定）。
        gateProduct = stageDetails.fineGateRuntime .* ...
            (1 - contract.target.repairFine);
        snapshotReference = 1 - protection.target.repairFine;
        if max(blemishMap(:)) == 0
            verifyLessThanOrEqual(testCase, ...
                max(abs(gateProduct(:) - snapshotReference(:))), 1e-15);
        else
            verifyGreaterThanOrEqual(testCase, ...
                min(gateProduct(:) - snapshotReference(:)), -1e-15);
        end

        % 共享路径 bit-exact：T15 收口后 referenceReliability/chroma
        % 与 structureGate 从 contract 重建，与 legacy 计算逐位一致。
        verifyEqual(testCase, stageDetails.referenceReliability, ...
            legacyDetails.referenceReliability, 'AbsTol', 0);
        verifyEqual(testCase, stageDetails.mediumWeight, ...
            legacyDetails.mediumWeight, 'AbsTol', 0);
        verifyEqual(testCase, stageDetails.chromaWeight, ...
            legacyDetails.chromaWeight, 'AbsTol', 0);
        verifyEqual(testCase, stageDetails.structureGate, ...
            legacyDetails.structureGate, 'AbsTol', 0);
        verifyEqual(testCase, repairedStage.mid, repairedLegacy.mid, ...
            'AbsTol', 0);
        verifyEqual(testCase, repairedStage.base, repairedLegacy.base, ...
            'AbsTol', 0);

        % hard identity 保持：hard 区域 fineWeight 恒 0。
        verifyEqual(testCase, ...
            nnz(stageDetails.fineWeight(protection.hard >= .999)), 0);
    end
end

% 负向证明：stage 路径的 fineWeight 对 textureProtectionMask 扰动完全
% 不变（Fine 门控不再读取该字段），legacy 路径则会随之变化。
blemishMap = injectedBlemish;
contract = makeTestRepairContract(beautyMasks, protection, ...
    blemishMap);
[smoothed60, ~] = beauty.smoothSkinTexture(frequency, beautyMasks, 60, ...
    blemishMap, protection);
[~, legacyDetails60] = beauty.repairSkinBlemishes(smoothed60, ...
    beautyMasks, blemishMap, 60);
[~, stageDetails60] = beauty.repairSkinBlemishes(smoothed60, ...
    beautyMasks, blemishMap, 60, contract);
perturbedMasks = beautyMasks;
perturbedMasks.textureProtectionMask = ...
    min(1, beautyMasks.textureProtectionMask * .5 + .25);
[~, perturbedLegacyDetails] = beauty.repairSkinBlemishes(smoothed60, ...
    perturbedMasks, blemishMap, 60);
[~, perturbedStageDetails] = beauty.repairSkinBlemishes(smoothed60, ...
    perturbedMasks, blemishMap, 60, contract);
verifyTrue(testCase, ...
    nnz(perturbedLegacyDetails.fineWeight ~= ...
    legacyDetails60.fineWeight) > 0, ...
    'texture 扰动必须确实影响 legacy 路径，否则本断言无意义。');
verifyEqual(testCase, perturbedStageDetails.fineWeight, ...
    stageDetails60.fineWeight, 'AbsTol', 0);
% fineCorrection 的 texture 独立性由 T15 的
% testMidRepairConsumesStageProtectionContract 断言：共享
% referenceReliability 收口后，stage 全输出（含 fineCorrection/
% mediumCorrection）对 texture 扰动不变。

% 缺字段 fail-fast：不静默回退拼装。
brokenContract = rmfield(contract, 'textureBandGate');
verifyError(testCase, @() beauty.repairSkinBlemishes( ...
    smoothed60, beautyMasks, blemishMap, 60, brokenContract), ...
    'beauty:InvalidBlemishRepair');
brokenContract = rmfield(contract, 'midBandGate');
verifyError(testCase, @() beauty.repairSkinBlemishes( ...
    smoothed60, beautyMasks, blemishMap, 60, brokenContract), ...
    'beauty:InvalidBlemishRepair');
end

function testMidRepairConsumesStageProtectionContract(testCase)
%TESTMIDREPAIRCONSUMESSTAGEPROTECTIONCONTRACT T15：提供生产端拼装的
%   repair stage contract 时，mediumWeight 门控只按生产原式从 contract
%   重建（结构门 = 1 - support.repairMid 作用于 [0,1] 截断之前，
%   target.repairMid（鼻部）与 midBandGate（T30 Mid 专属纯 policy 带）
%   合成后与 target.repairFine（纹理）按生产顺序作用于截断之后），不再
%   自行组合 general texture/structure/nose masks；共享
%   referenceReliability 与 chromaWeight 的门控来源同步收口（bit-exact
%   同值）：扰动 texture/structure/nose masks 不改变 stage 路径的任何
%   输出（含 fineCorrection/mediumCorrection），legacy 路径则会随之变
%   化。快照 repairMid 为 T07 零瑕疵参考门：blemish = 0 时
%   structureGate·noseMidGate·textureGate 与 1 - repairMid 一致
%   （≤1e-15，1-x 补码往返舍入），blemish > 0 时相对快照只增不减。
%   T15 迁移不改变任何数值：stage 与 legacy 全输出逐位等价
%   （bit-exact）。诊断随之收口：stage 路径不再报告 noseMask，新增
%   mediumGateZeroBlemish 快照；legacy 路径字段不变。
[image, faceBox, parsing] = fixtureImage(120, 160);
context = prepareBeautyContext(image, faceBox, parsing, ...
    emptyBodyParsing([120, 160]));
[beautyMasks, ~] = masks.buildBeautyMasks(image, context, faceBox);
protection = masks.buildStageProtectionMasks(beautyMasks);
[frequency, ~] = beauty.decomposeSkinFrequency(image, faceBox);
[realBlemishMap, ~] = beauty.buildBlemishMap(image, frequency, beautyMasks);

% 注入高置信瑕疵证据：皮肤上 24 枚紧凑斑点（确定性网格，全局证据超
% 过 globalGate 阈值且低于 sparseGate 抑制线），使 mediumConfidence、
% blemish 放宽量、strongStructure 上限与 noseMidGate 同时参与重建。
% 真实 buildBlemishMap 产物与零瑕疵参考各测一组。
[height, width] = size(image(:, :, 1));
[xGrid, yGrid] = meshgrid(1:width, 1:height);
[dotRows, dotCols] = meshgrid(40:12:76, 42:12:102);
dotCenters = [dotRows(:), dotCols(:)];
injectedBlemish = zeros(height, width);
for dotIndex = 1:size(dotCenters, 1)
    injectedBlemish = max(injectedBlemish, .95 * exp( ...
        -((xGrid - dotCenters(dotIndex, 2)) .^ 2 + ...
        (yGrid - dotCenters(dotIndex, 1)) .^ 2) / (2 * 2.2 ^ 2)));
end
verifyTrue(testCase, max(injectedBlemish(:)) > .90, ...
    '注入斑点必须达到高置信瑕疵。');
verifyTrue(testCase, nnz(beautyMasks.noseMask > 0) > 0, ...
    'fixture 必须包含非空 noseMask，否则 noseMidGate 重建断言无意义。');
verifyTrue(testCase, ...
    nnz(injectedBlemish(:) .* beautyMasks.structureProtectionMask(:)) > 0, ...
    '注入瑕疵必须与结构保护重叠，否则 blemish 放宽量重建未被覆盖。');
injectedSmoothed = beauty.smoothSkinTexture(frequency, beautyMasks, ...
    60, injectedBlemish, protection);
[~, injectedRepairDetails] = beauty.repairSkinBlemishes( ...
    injectedSmoothed, beautyMasks, injectedBlemish, 60);
verifyTrue(testCase, nnz(injectedRepairDetails.mediumWeight) > 0, ...
    '注入斑点必须产生非零 mediumWeight，否则 Mid 门控断言无意义。');

strengths = [0, 25, 50, 75, 100];
blemishCases = {zeros(height, width), realBlemishMap, injectedBlemish};
for caseIndex = 1:numel(blemishCases)
    blemishMap = blemishCases{caseIndex};
    contract = makeTestRepairContract(beautyMasks, protection, ...
        blemishMap);
    for index = 1:numel(strengths)
        strength = strengths(index);
        [smoothed, ~] = beauty.smoothSkinTexture(frequency, ...
            beautyMasks, strength, blemishMap, protection);
        [repairedLegacy, legacyDetails] = ...
            beauty.repairSkinBlemishes(smoothed, beautyMasks, ...
            blemishMap, strength);
        [repairedStage, stageDetails] = ...
            beauty.repairSkinBlemishes(smoothed, beautyMasks, ...
            blemishMap, strength, contract);

        % stage 门控恰为 contract 按生产原式、原顺序重建（bit-exact）：
        % 前置结构门在截断之前，target 门（鼻部→纹理）在截断之后。
        structureGateRuntime = 1 - contract.support.repairMid;
        verifyEqual(testCase, stageDetails.structureGate, ...
            structureGateRuntime, 'AbsTol', 0);
        expectedMedium = stageDetails.repairCurveMap .* ...
            (.95 * stageDetails.mediumConfidence + ...
            .40 * stageDetails.highConfidence) .* ...
            stageDetails.allowed .* structureGateRuntime + ...
            (stageDetails.highEndRepairCurve .* ...
            stageDetails.highEndConfidence) .* ...
            stageDetails.allowed .* structureGateRuntime;
        expectedMedium = min(max(expectedMedium, 0), 1);
        % Mid 逐像素门 = (1 - target.repairMid) .* midBandGate（鼻部退让 ×
        % T30 Mid 专属纯 policy 带），按生产原式的结合序先乘，再乘纹理门与
        % textureBandGate。
        expectedMedium = expectedMedium .* ...
            ((1 - contract.target.repairMid) .* contract.midBandGate) .* ...
            (1 - contract.target.repairFine);
        expectedMedium = expectedMedium .* contract.textureBandGate;
        verifyEqual(testCase, stageDetails.mediumWeight, ...
            expectedMedium, 'AbsTol', 0);
        expectedChroma = .16 * stageDetails.repairCurveMap .* ...
            stageDetails.highConfidence .* stageDetails.allowed .* ...
            structureGateRuntime;
        expectedChroma = min(max(expectedChroma, 0), 1);
        expectedChroma = expectedChroma .* ...
            (1 - contract.target.repairFine) .* contract.textureBandGate;
        verifyEqual(testCase, stageDetails.chromaWeight, ...
            expectedChroma, 'AbsTol', 0);
        expectedReference = stageDetails.allowed .* ...
            (1 - contract.support.repairFine) .* (1 - .86 * blemishMap) .* ...
            (1 - contract.support.repairMid);
        verifyEqual(testCase, stageDetails.referenceReliability, ...
            expectedReference, 'AbsTol', 0);

        % 与 legacy 路径逐位等价：T15 迁移不改变任何数值。
        verifyEqual(testCase, stageDetails.mediumWeight, ...
            legacyDetails.mediumWeight, 'AbsTol', 0);
        verifyEqual(testCase, stageDetails.mediumCorrection, ...
            legacyDetails.mediumCorrection, 'AbsTol', 0);
        verifyEqual(testCase, stageDetails.chromaWeight, ...
            legacyDetails.chromaWeight, 'AbsTol', 0);
        verifyEqual(testCase, stageDetails.referenceReliability, ...
            legacyDetails.referenceReliability, 'AbsTol', 0);
        verifyEqual(testCase, repairedStage.mid, repairedLegacy.mid, ...
            'AbsTol', 0);
        verifyEqual(testCase, repairedStage.fine, repairedLegacy.fine, ...
            'AbsTol', 0);
        verifyEqual(testCase, repairedStage.alphaMap, ...
            repairedLegacy.alphaMap, 'AbsTol', 0);
        verifyEqual(testCase, repairedStage.base, repairedLegacy.base, ...
            'AbsTol', 0);

        % 零瑕疵快照语义（T07 衔接）：blemish = 0 时前置结构门·
        % target 门与 1 - protection.target.repairMid 一致（仅 1-x 补码往返舍入）；
        % blemish > 0 时相对快照只增不减（runtime 放宽约定）。
        gateProduct = stageDetails.structureGate .* ...
            (1 - contract.target.repairMid) .* ...
            (1 - contract.target.repairFine);
        snapshotReference = 1 - protection.target.repairMid;
        verifyEqual(testCase, stageDetails.mediumGateZeroBlemish, ...
            snapshotReference, 'AbsTol', 0);
        if max(blemishMap(:)) == 0
            verifyLessThanOrEqual(testCase, ...
                max(abs(gateProduct(:) - snapshotReference(:))), 1e-15);
        else
            verifyGreaterThanOrEqual(testCase, ...
                min(gateProduct(:) - snapshotReference(:)), -1e-15);
        end

        % hard identity 保持：hard 区域 mediumWeight 恒 0。
        verifyEqual(testCase, ...
            nnz(stageDetails.mediumWeight(protection.hard >= .999)), 0);
    end
end

% 负向证明：stage 路径的全部输出对 texture/structure/nose masks 扰动
% 完全不变（Fine/Mid 只消费 stage contract），legacy 路径则会随之变化。
blemishMap = injectedBlemish;
contract = makeTestRepairContract(beautyMasks, protection, blemishMap);
[smoothed60, ~] = beauty.smoothSkinTexture(frequency, beautyMasks, 60, ...
    blemishMap, protection);
[~, legacyDetails60] = beauty.repairSkinBlemishes(smoothed60, ...
    beautyMasks, blemishMap, 60);
[~, stageDetails60] = beauty.repairSkinBlemishes(smoothed60, ...
    beautyMasks, blemishMap, 60, contract);
[repairedStage60, ~] = beauty.repairSkinBlemishes(smoothed60, ...
    beautyMasks, blemishMap, 60, contract);
perturbedMasks = beautyMasks;
perturbedMasks.textureProtectionMask = ...
    min(1, beautyMasks.textureProtectionMask * .5 + .25);
perturbedMasks.structureProtectionMask = ...
    min(1, beautyMasks.structureProtectionMask * .5 + .25);
perturbedMasks.noseMask = min(1, beautyMasks.noseMask * .5 + .25);
[repairedPerturbedLegacy, perturbedLegacyDetails] = ...
    beauty.repairSkinBlemishes(smoothed60, perturbedMasks, blemishMap, 60);
[repairedPerturbedStage, perturbedStageDetails] = ...
    beauty.repairSkinBlemishes(smoothed60, perturbedMasks, blemishMap, ...
    60, contract);
verifyTrue(testCase, ...
    nnz(perturbedLegacyDetails.mediumWeight ~= ...
    legacyDetails60.mediumWeight) > 0, ...
    'texture/structure/nose 扰动必须确实影响 legacy Mid 权重，否则本断言无意义。');
verifyTrue(testCase, ...
    nnz(perturbedLegacyDetails.fineWeight ~= ...
    legacyDetails60.fineWeight) > 0, ...
    'texture/structure 扰动必须确实影响 legacy Fine 权重，否则本断言无意义。');
verifyEqual(testCase, perturbedStageDetails.mediumWeight, ...
    stageDetails60.mediumWeight, 'AbsTol', 0);
verifyEqual(testCase, perturbedStageDetails.fineWeight, ...
    stageDetails60.fineWeight, 'AbsTol', 0);
verifyEqual(testCase, perturbedStageDetails.referenceReliability, ...
    stageDetails60.referenceReliability, 'AbsTol', 0);
verifyEqual(testCase, repairedPerturbedStage, repairedStage60, ...
    'AbsTol', 0);

% contract 只发布规范门：midBandGate 逐位等于 1 - regionBandMid（T30 Mid
% 专属纯 policy 带的补码），target/support 门逐位等于 policy 发布值。
verifyEqual(testCase, contract.midBandGate, ...
    1 - protection.regionBandMid, 'AbsTol', 0);
verifyEqual(testCase, contract.target.repairMid, ...
    protection.noseMidProtection, 'AbsTol', 0);
verifyEqual(testCase, contract.support.repairFine, ...
    protection.support.repairFine, 'AbsTol', 0);

% 诊断收口：T31 起 repair 算法侧不再持有 nose/texture 语义，两条入口都
% 报告 mediumGateZeroBlemish 快照，且都不再报告 noseMask/noseMidGate。
verifyEqual(testCase, isfield(stageDetails60, 'noseMask'), false, ...
    'repair 诊断不得再报告 noseMask 诊断字段。');
verifyTrue(testCase, isfield(stageDetails60, ...
    'mediumGateZeroBlemish'));
verifyEqual(testCase, ...
    isfield(legacyDetails60, {'noseMask', 'noseMidGate'}), ...
    [false, false], ...
    '兼容入口同样不得再报告 nose 特判字段。');

% 缺字段 fail-fast：不静默回退拼装。
brokenContract = rmfield(contract, 'textureBandGate');
verifyError(testCase, @() beauty.repairSkinBlemishes( ...
    smoothed60, beautyMasks, blemishMap, 60, brokenContract), ...
    'beauty:InvalidBlemishRepair');
brokenContract = rmfield(contract, 'midBandGate');
verifyError(testCase, @() beauty.repairSkinBlemishes( ...
    smoothed60, beautyMasks, blemishMap, 60, brokenContract), ...
    'beauty:InvalidBlemishRepair');
brokenContract = rmfield(contract, 'target');
verifyError(testCase, @() beauty.repairSkinBlemishes( ...
    smoothed60, beautyMasks, blemishMap, 60, brokenContract), ...
    'beauty:InvalidBlemishRepair');
brokenContract = rmfield(contract, 'support');
verifyError(testCase, @() beauty.repairSkinBlemishes( ...
    smoothed60, beautyMasks, blemishMap, 60, brokenContract), ...
    'beauty:InvalidBlemishRepair');
end

function testBaseLuminanceConsumesStageProtectionContract(testCase)
%TESTBASELUMINANCECONSUMESSTAGEPROTECTIONCONTRACT T32：提供生产端拼装的
%   Base Luminance stage contract 时，逐像素均衡与参考统计的门只来自
%   contract 的规范门（target.baseLuminance / support.baseLuminance /
%   hard / regionBandGate），不再自行组合 general
%   texture/chroma/structure/hard masks：扰动这些 masks 不改变 stage 路径
%   的任何输出，legacy 路径则会随之变化。零带下 stage 与 legacy 全输出
%   逐位等价（bit-exact，两条路径都经唯一组装点）。
%   双门控分离（上位契约第 3.3/5.6 节）：referenceReliability 只消费
%   support.baseLuminance（含 (1-hard)），supportMap 只消费
%   target.baseLuminance（不含 hard，hard 单独相乘）与 regionBandGate；
%   改动 target 门不扰动参考统计，改动 support 门不扰动逐像素门。
%   诊断收口：两条路径都不再报告 chroma/tone 兼容 alias 与
%   structureGate/featureGate，统一报告 targetGate/supportGate 与
%   baseGateSnapshot 快照。
[image, faceBox, parsing] = fixtureImage(120, 160);
context = prepareBeautyContext(image, faceBox, parsing, ...
    emptyBodyParsing([120, 160]));
[beautyMasks, ~] = masks.buildBeautyMasks(image, context, faceBox);
protection = masks.buildStageProtectionMasks(beautyMasks);
[frequency, ~] = beauty.decomposeSkinFrequency(image, faceBox);
contract = makeTestBaseLuminanceContract(beautyMasks, protection);

% contract 只发布规范门：target/support 门逐位等于 policy 发布值。
verifyEqual(testCase, contract.target.baseLuminance, ...
    protection.target.baseLuminance, 'AbsTol', 0);
verifyEqual(testCase, contract.support.baseLuminance, ...
    protection.support.baseLuminance, 'AbsTol', 0);
verifyEqual(testCase, contract.hard, protection.hard, 'AbsTol', 0);
verifyEqual(testCase, contract.regionBandGate, ...
    1 - protection.regionBandBase, 'AbsTol', 0);

strengths = [0, 25, 50, 75, 100];
for index = 1:numel(strengths)
    strength = strengths(index);
    [resultLegacy, legacyDetails] = beauty.evenSkinLuminance( ...
        frequency, beautyMasks, strength);
    [resultStage, stageDetails] = beauty.evenSkinLuminance( ...
        frequency, beautyMasks, strength, contract);

    % stage 结果与 legacy 全字段逐位一致：T32 迁移不改变任何数值。
    verifyTrue(testCase, isequaln(resultStage, resultLegacy), ...
        'stage 路径的 base luminance 结果必须与 legacy 逐位一致。');
    verifyEqual(testCase, stageDetails.referenceReliability, ...
        legacyDetails.referenceReliability, 'AbsTol', 0);
    verifyEqual(testCase, stageDetails.referenceWeight, ...
        legacyDetails.referenceWeight, 'AbsTol', 0);
    verifyEqual(testCase, stageDetails.referenceCoverage, ...
        legacyDetails.referenceCoverage, 'AbsTol', 0);
    verifyEqual(testCase, stageDetails.referenceOffset, ...
        legacyDetails.referenceOffset, 'AbsTol', 0);
    verifyEqual(testCase, stageDetails.supportMap, ...
        legacyDetails.supportMap, 'AbsTol', 0);
    verifyEqual(testCase, stageDetails.baseDelta, ...
        legacyDetails.baseDelta, 'AbsTol', 0);
    verifyEqual(testCase, stageDetails.targetGate, ...
        legacyDetails.targetGate, 'AbsTol', 0);
    verifyEqual(testCase, stageDetails.supportGate, ...
        legacyDetails.supportGate, 'AbsTol', 0);
    verifyEqual(testCase, stageDetails.hardProtectionGate, ...
        legacyDetails.hardProtectionGate, 'AbsTol', 0);

    % 门来源收口：target/support 门逐位等于 1 - contract 规范门。
    verifyEqual(testCase, stageDetails.targetGate, ...
        1 - contract.target.baseLuminance, 'AbsTol', 0);
    verifyEqual(testCase, stageDetails.supportGate, ...
        1 - contract.support.baseLuminance, 'AbsTol', 0);
    % T07 快照衔接：baseGateSnapshot = 1 - target.baseLuminance。
    verifyEqual(testCase, stageDetails.baseGateSnapshot, ...
        1 - protection.target.baseLuminance, 'AbsTol', 0);
    % supportMap 与按规范门重算逐位一致。
    snapshotSupport = stageDetails.baseWeightCurve .* ...
        stageDetails.regionalSkinWeight .* ...
        stageDetails.hardProtectionGate .* stageDetails.targetGate .* ...
        stageDetails.regionBandGate .* stageDetails.referenceCoverage;
    verifyLessThanOrEqual(testCase, ...
        max(abs(stageDetails.supportMap(:) - snapshotSupport(:))), 1e-15);
    % referenceReliability 只消费 support 门（含 (1-hard)）。
    snapshotReference = stageDetails.regionalSkinWeight .* ...
        stageDetails.supportGate;
    snapshotReference = min(max(snapshotReference, 0), 1);
    verifyLessThanOrEqual(testCase, ...
        max(abs(stageDetails.referenceReliability(:) - ...
        snapshotReference(:))), 1e-15);

    % hard identity 保持：hard 区域 supportMap/baseDelta 恒 0。
    verifyEqual(testCase, ...
        nnz(stageDetails.supportMap(protection.hard >= .999)), 0);
    verifyEqual(testCase, ...
        nnz(stageDetails.baseDelta(protection.hard >= .999)), 0);
end

% 负向证明：stage 路径的全部输出对 texture/chroma/structure/hard masks
% 扰动完全不变（只消费 stage contract），legacy 路径则会随之变化。
[~, legacyDetails60] = beauty.evenSkinLuminance(frequency, beautyMasks, 60);
[~, stageDetails60] = beauty.evenSkinLuminance(frequency, beautyMasks, ...
    60, contract);
perturbedMasks = beautyMasks;
perturbedMasks.textureProtectionMask = ...
    min(1, beautyMasks.textureProtectionMask * .5 + .25);
perturbedMasks.structureProtectionMask = ...
    min(1, beautyMasks.structureProtectionMask * .5 + .25);
perturbedMasks.chromaProtectionMask = ...
    min(1, beautyMasks.chromaProtectionMask * .5 + .25);
perturbedMasks.toneProtectionMask = perturbedMasks.chromaProtectionMask;
perturbedMasks.hardProtectionMask = ...
    min(1, beautyMasks.hardProtectionMask * .5 + .25);
[~, perturbedLegacyDetails] = beauty.evenSkinLuminance( ...
    frequency, perturbedMasks, 60);
[~, perturbedStageDetails] = beauty.evenSkinLuminance( ...
    frequency, perturbedMasks, 60, contract);
verifyTrue(testCase, ...
    nnz(perturbedLegacyDetails.supportMap ~= ...
    legacyDetails60.supportMap) > 0, ...
    'texture/chroma/structure/hard 扰动必须确实影响 legacy 路径，否则本断言无意义。');
verifyEqual(testCase, perturbedStageDetails.supportMap, ...
    stageDetails60.supportMap, 'AbsTol', 0);
verifyEqual(testCase, perturbedStageDetails.baseDelta, ...
    stageDetails60.baseDelta, 'AbsTol', 0);
verifyEqual(testCase, perturbedStageDetails.referenceReliability, ...
    stageDetails60.referenceReliability, 'AbsTol', 0);

% 双门控独立：只改 target.baseLuminance -> 参考统计逐位不变；
% 只改 support.baseLuminance -> 参考统计变化而逐像素门逐位不变。
targetPerturbed = contract;
targetPerturbed.target.baseLuminance = ...
    min(1, contract.target.baseLuminance * .5 + .25);
[~, targetPerturbedDetails] = beauty.evenSkinLuminance(frequency, ...
    beautyMasks, 60, targetPerturbed);
verifyEqual(testCase, targetPerturbedDetails.referenceReliability, ...
    stageDetails60.referenceReliability, 'AbsTol', 0);
verifyEqual(testCase, targetPerturbedDetails.referenceWeight, ...
    stageDetails60.referenceWeight, 'AbsTol', 0);
verifyEqual(testCase, targetPerturbedDetails.referenceCoverage, ...
    stageDetails60.referenceCoverage, 'AbsTol', 0);
verifyEqual(testCase, targetPerturbedDetails.referenceOffset, ...
    stageDetails60.referenceOffset, 'AbsTol', 0);
verifyTrue(testCase, ...
    nnz(targetPerturbedDetails.supportMap ~= stageDetails60.supportMap) > 0, ...
    '只改 target 门必须改变逐像素 supportMap，否则本断言无意义。');
supportPerturbed = contract;
supportPerturbed.support.baseLuminance = ...
    min(1, contract.support.baseLuminance * .5 + .25);
[~, supportPerturbedDetails] = beauty.evenSkinLuminance(frequency, ...
    beautyMasks, 60, supportPerturbed);
verifyEqual(testCase, supportPerturbedDetails.targetGate, ...
    stageDetails60.targetGate, 'AbsTol', 0);
verifyEqual(testCase, supportPerturbedDetails.hardProtectionGate, ...
    stageDetails60.hardProtectionGate, 'AbsTol', 0);
verifyEqual(testCase, supportPerturbedDetails.regionBandGate, ...
    stageDetails60.regionBandGate, 'AbsTol', 0);
verifyTrue(testCase, ...
    nnz(supportPerturbedDetails.referenceReliability ~= ...
    stageDetails60.referenceReliability) > 0, ...
    '只改 support 门必须改变参考统计，否则本断言无意义。');

% 诊断收口：两条路径都不再报告 chroma/tone 兼容 alias 与
% structureGate/featureGate，统一报告 targetGate/supportGate 快照。
verifyEqual(testCase, ...
    isfield(stageDetails60, {'chromaProtectionMask', ...
    'toneProtectionMask', 'structureGate', 'featureGate'}), ...
    [false, false, false, false], ...
    'stage 路径不得再报告 chroma/tone alias 或 structureGate/featureGate。');
verifyTrue(testCase, isfield(stageDetails60, 'baseGateSnapshot'));
verifyEqual(testCase, ...
    isfield(legacyDetails60, {'chromaProtectionMask', ...
    'toneProtectionMask', 'structureGate', 'featureGate'}), ...
    [false, false, false, false], ...
    '兼容入口同样走唯一组装点，不得再报告 legacy 保护语义诊断。');

% 缺字段与取值越界 fail-fast：不静默回退拼装。
brokenContract = rmfield(contract, 'regionBandGate');
verifyError(testCase, @() beauty.evenSkinLuminance( ...
    frequency, beautyMasks, 60, brokenContract), ...
    'beauty:InvalidEvenLuminanceInput');
brokenContract = rmfield(contract, 'target');
verifyError(testCase, @() beauty.evenSkinLuminance( ...
    frequency, beautyMasks, 60, brokenContract), ...
    'beauty:InvalidEvenLuminanceInput');
brokenContract = rmfield(contract, 'support');
verifyError(testCase, @() beauty.evenSkinLuminance( ...
    frequency, beautyMasks, 60, brokenContract), ...
    'beauty:InvalidEvenLuminanceInput');
brokenContract = rmfield(contract, 'hard');
verifyError(testCase, @() beauty.evenSkinLuminance( ...
    frequency, beautyMasks, 60, brokenContract), ...
    'beauty:InvalidEvenLuminanceInput');
brokenContract = contract;
brokenContract.target.baseLuminance = ...
    min(1, brokenContract.target.baseLuminance) + .25;
verifyError(testCase, @() beauty.evenSkinLuminance( ...
    frequency, beautyMasks, 60, brokenContract), ...
    'beauty:InvalidEvenLuminanceInput');
end

function testToneConsumesStageProtectionContract(testCase)
%TESTTONECONSUMESSTAGEPROTECTIONCONTRACT T17：提供生产端拼装的 Tone
%   stage contract 时，主/uniform 两分支的保护门控与候选色度保护门限
%   只按生产原式从 contract 的未折叠 structureGate/featureGate/
%   uniformFeatureGate/candidateChromaGate 与 hard 重建，不再自行组合
%   general structure/chroma/hard masks：扰动这些 masks 不改变 stage
%   路径的任何输出，legacy 路径则会随之变化。快照 tone 的折叠只覆盖
%   主分支且含 1-x 补码往返舍入，不参与输出算术：主分支门控积
%   structureGate·featureGate 与 1 - tone 一致（≤1e-15），uniform 分
%   支门控积不高于该快照（T07 已知残差：uniform 分支保护更强）。
%   strengthMap/skinMask 继续显式控制效果幅度，strength 与 protection
%   不合并。T17 迁移不改变任何数值：stage 与 legacy 全输出逐位等价
%   （bit-exact）。诊断随之收口：stage 路径不再报告 structure/chroma/
%   tone 兼容 alias，新增 toneGateSnapshot 快照；legacy 路径字段不变。
[image, faceBox, parsing] = fixtureImage(120, 160);
context = prepareBeautyContext(image, faceBox, parsing, ...
    emptyBodyParsing([120, 160]));
[beautyMasks, ~] = masks.buildBeautyMasks(image, context, faceBox);
protection = masks.buildStageProtectionMasks(beautyMasks);
[frequency, ~] = beauty.decomposeSkinFrequency(image, faceBox);
[realBlemishMap, ~] = beauty.buildBlemishMap(image, frequency, beautyMasks);
contract = makeTestToneContract(beautyMasks, protection);

% 强度序列覆盖两分支：25 走主分支（ratio<=.50），60 处于 uniform
% ramp 中段，75/100 为 uniform 档；0 为零强度端点。
strengths = [0, 25, 50, 60, 75, 100];
blemishCases = {zeros(size(realBlemishMap)), realBlemishMap};
for caseIndex = 1:numel(blemishCases)
    blemishMap = blemishCases{caseIndex};
    for index = 1:numel(strengths)
        strength = strengths(index);
        [toneLegacy, legacyDetails] = beauty.normalizeSkinTone( ...
            image, frequency, beautyMasks, blemishMap, strength);
        [toneStage, stageDetails] = beauty.normalizeSkinTone( ...
            image, frequency, beautyMasks, blemishMap, strength, ...
            contract);

        % 与 legacy 路径逐位等价：T17 迁移不改变任何数值（toneResult
        % 不含保护字段，整体逐位一致，含渲染输出图像）。
        verifyTrue(testCase, isequaln(toneStage, toneLegacy), ...
            'stage 路径的 tone 结果必须与 legacy 逐位一致。');
        % 关键门控与输出字段显式断言（含两分支权重与候选选择）。
        verifyEqual(testCase, stageDetails.weightMap, ...
            legacyDetails.weightMap, 'AbsTol', 0);
        verifyEqual(testCase, stageDetails.candidateMask, ...
            legacyDetails.candidateMask, 'AbsTol', 0);
        verifyEqual(testCase, stageDetails.uniformToneCurve, ...
            legacyDetails.uniformToneCurve, 'AbsTol', 0);
        verifyEqual(testCase, stageDetails.localBlend, ...
            legacyDetails.localBlend, 'AbsTol', 0);
        verifyEqual(testCase, stageDetails.deltaCb, ...
            legacyDetails.deltaCb, 'AbsTol', 0);
        verifyEqual(testCase, stageDetails.deltaCr, ...
            legacyDetails.deltaCr, 'AbsTol', 0);

        % 快照语义（T07 衔接）：主分支门控积与 1 - tone 一致（仅 1-x
        % 补码往返舍入）；uniform 分支门控积不高于快照（更强保护）。
        verifyEqual(testCase, stageDetails.toneGateSnapshot, ...
            1 - protection.target.tone, 'AbsTol', 0);
        verifyLessThanOrEqual(testCase, max(abs( ...
            contract.structureGate(:) .* contract.featureGate(:) - ...
            stageDetails.toneGateSnapshot(:))), 1e-15);
        uniformGateProduct = contract.structureGate .* ...
            contract.uniformFeatureGate;
        verifyLessThanOrEqual(testCase, max(uniformGateProduct(:) - ...
            stageDetails.toneGateSnapshot(:)), 1e-15);

        % hard identity 保持：hard 区域权重恒 0。
        verifyEqual(testCase, ...
            nnz(stageDetails.weightMap(protection.hard >= .999)), 0);
    end
end

% 两分支覆盖确认：s=25 未激活 uniform 分支，s=60 已激活；fixture 在
% 两个分支下都必须产生非零权重，否则门控断言无意义。
[~, details25] = beauty.normalizeSkinTone(image, frequency, ...
    beautyMasks, realBlemishMap, 25, contract);
[~, details60] = beauty.normalizeSkinTone(image, frequency, ...
    beautyMasks, realBlemishMap, 60, contract);
verifyEqual(testCase, details25.uniformToneCurve, 0, 'AbsTol', 0);
verifyGreaterThan(testCase, details60.uniformToneCurve, 0);
verifyTrue(testCase, nnz(details25.weightMap) > 0, ...
    'fixture 必须产生非零主分支 tone 权重，否则本测试断言无意义。');
verifyTrue(testCase, nnz(details60.weightMap) > 0, ...
    'fixture 必须产生非零 uniform 分支 tone 权重，否则本测试断言无意义。');

% 负向证明：stage 路径的全部输出对 structure/chroma/tone/hard masks
% 扰动完全不变（只消费 stage contract），legacy 路径则会随之变化。
[~, legacyDetails60] = beauty.normalizeSkinTone(image, frequency, ...
    beautyMasks, realBlemishMap, 60);
[~, stageDetails60] = beauty.normalizeSkinTone(image, frequency, ...
    beautyMasks, realBlemishMap, 60, contract);
perturbedMasks = beautyMasks;
perturbedMasks.structureProtectionMask = ...
    min(1, beautyMasks.structureProtectionMask * .5 + .25);
perturbedMasks.chromaProtectionMask = ...
    min(1, beautyMasks.chromaProtectionMask * .5 + .25);
perturbedMasks.toneProtectionMask = perturbedMasks.chromaProtectionMask;
perturbedMasks.hardProtectionMask = ...
    min(1, beautyMasks.hardProtectionMask * .5 + .25);
[~, perturbedLegacyDetails] = beauty.normalizeSkinTone(image, ...
    frequency, perturbedMasks, realBlemishMap, 60);
[~, perturbedStageDetails] = beauty.normalizeSkinTone(image, ...
    frequency, perturbedMasks, realBlemishMap, 60, contract);
verifyTrue(testCase, ...
    nnz(perturbedLegacyDetails.weightMap ~= ...
    legacyDetails60.weightMap) > 0, ...
    'structure/chroma/tone/hard 扰动必须确实影响 legacy 路径，否则本断言无意义。');
verifyEqual(testCase, perturbedStageDetails.weightMap, ...
    stageDetails60.weightMap, 'AbsTol', 0);
verifyEqual(testCase, perturbedStageDetails.candidateMask, ...
    stageDetails60.candidateMask, 'AbsTol', 0);
verifyEqual(testCase, perturbedStageDetails.deltaCb, ...
    stageDetails60.deltaCb, 'AbsTol', 0);
verifyEqual(testCase, perturbedStageDetails.deltaCr, ...
    stageDetails60.deltaCr, 'AbsTol', 0);

% 诊断收口：stage 路径不再报告 structure/chroma/tone 兼容 alias，
% 新增 toneGateSnapshot 快照；legacy 路径字段保持不变。
verifyEqual(testCase, isfield(stageDetails60, ...
    {'structureProtectionMask', 'chromaProtectionMask', ...
    'toneProtectionMask'}), [false, false, false], ...
    'stage 路径不得再报告 structure/chroma/tone 兼容 alias 诊断字段。');
verifyTrue(testCase, isfield(stageDetails60, 'toneGateSnapshot'));
legacyToneAliases = isfield(legacyDetails60, ...
    {'structureProtectionMask', 'chromaProtectionMask', 'toneProtectionMask'});
verifyFalse(testCase, any(legacyToneAliases), ...
    '兼容入口不得再报告 legacy 保护诊断字段。');
verifyTrue(testCase, isfield(legacyDetails60, 'toneGateSnapshot'), ...
    '兼容入口与生产入口必须共享规范 Tone contract 诊断。');
verifyEqual(testCase, stageDetails60.hardProtectionMask, ...
    protection.hard, 'AbsTol', 0);

% 缺字段与取值越界 fail-fast：不静默回退拼装。
brokenContract = rmfield(contract, 'uniformFeatureGate');
verifyError(testCase, @() beauty.normalizeSkinTone(image, frequency, ...
    beautyMasks, realBlemishMap, 60, brokenContract), ...
    'beauty:InvalidSkinToneInput');
brokenContract = rmfield(contract, 'candidateChromaGate');
verifyError(testCase, @() beauty.normalizeSkinTone(image, frequency, ...
    beautyMasks, realBlemishMap, 60, brokenContract), ...
    'beauty:InvalidSkinToneInput');
brokenContract = rmfield(contract, 'tone');
verifyError(testCase, @() beauty.normalizeSkinTone(image, frequency, ...
    beautyMasks, realBlemishMap, 60, brokenContract), ...
    'beauty:InvalidSkinToneInput');
brokenContract = contract;
brokenContract.structureGate = min(1, ...
    brokenContract.structureGate) + .25;
verifyError(testCase, @() beauty.normalizeSkinTone(image, frequency, ...
    beautyMasks, realBlemishMap, 60, brokenContract), ...
    'beauty:InvalidSkinToneInput');
end

function testWhiteningConsumesStageProtectionContract(testCase)
%TESTWHITENINGCONSUMESSTAGEPROTECTIONCONTRACT T18：提供生产端拼装的
%   Whitening stage contract 时，supportBase 的保护门控只按生产原式从
%   contract 的未折叠 structureGate（含脸部/脸外差异分支）/featureGate
%   与 hard 重建，亮度统计选点改用 featureZeroGate 门限，不再自行解释
%   general structure/whitening/hard masks：扰动这些 masks 不改变
%   stage 路径的任何输出，legacy 路径则会随之变化。快照 whitening 的
%   折叠含 1-x 补码往返舍入，不参与输出算术：门控积
%   structureGate·featureGate 与 1 - whitening 一致（≤1e-15）。
%   strengthMap/skinMask 继续显式控制效果幅度（含脸部 allowed 下限与
%   鼻部幅度封顶），strength 与 protection 不合并。T18 迁移不改变任
%   何数值：stage 与 legacy 全输出逐位等价（bit-exact）。诊断随之收
%   口：stage 路径不再报告 structure/whitening 兼容 alias，新增
%   whiteningGateSnapshot 快照；legacy 路径字段不变。
[image, faceBox, parsing] = fixtureImage(120, 160);
context = prepareBeautyContext(image, faceBox, parsing, ...
    emptyBodyParsing([120, 160]));
[beautyMasks, ~] = masks.buildBeautyMasks(image, context, faceBox);
protection = masks.buildStageProtectionMasks(beautyMasks);
[frequency, ~] = beauty.decomposeSkinFrequency(image, faceBox);
contract = makeTestWhiteningContract(beautyMasks, protection);
verifyTrue(testCase, nnz(beautyMasks.noseMask > 0) > 0, ...
    'fixture 必须包含非空 noseMask，否则鼻部幅度封顶路径未被覆盖。');
verifyTrue(testCase, ...
    nnz(beautyMasks.whiteningProtectionMask > 0) > 0, ...
    'fixture 必须包含非零 whitening 保护带，否则 featureGate 断言无意义。');

% structureGate 的脸部/脸外差异分支必须按生产原式重建。
expectedStructureGate = 1 - beautyMasks.structureProtectionMask;
faceSkinSupport = beautyMasks.faceSkinMask >= .5;
expectedStructureGate(faceSkinSupport) = ...
    1 - .10 * beautyMasks.structureProtectionMask(faceSkinSupport);
verifyEqual(testCase, contract.structureGate, expectedStructureGate, ...
    'AbsTol', 0);
verifyTrue(testCase, nnz(faceSkinSupport & ...
    beautyMasks.structureProtectionMask > 0) > 0, ...
    'fixture 必须在脸部包含结构保护，否则浅退让分支未被覆盖。');

strengths = [0, 15, 25, 50, 75, 100];
for index = 1:numel(strengths)
    strength = strengths(index);
    [whiteLegacy, legacyDetails] = beauty.applySkinWhitening( ...
        image, frequency, beautyMasks, strength);
    [whiteStage, stageDetails] = beauty.applySkinWhitening( ...
        image, frequency, beautyMasks, strength, contract);

    % 与 legacy 路径逐位等价：T18 迁移不改变任何数值（结果结构除收
    % 口的 whitening 兼容 alias 外整体逐位一致，含渲染输出图像）。
    verifyTrue(testCase, isequaln(whiteStage, whiteLegacy), ...
        'stage 路径的 whitening 结果必须与 legacy 逐位一致。');
    % 关键门控与输出字段显式断言（含统计选点与两分支门控）。
    verifyEqual(testCase, stageDetails.supportMap, ...
        legacyDetails.supportMap, 'AbsTol', 0);
    verifyEqual(testCase, stageDetails.delta, legacyDetails.delta, ...
        'AbsTol', 0);
    verifyEqual(testCase, stageDetails.outputLuminance, ...
        legacyDetails.outputLuminance, 'AbsTol', 0);
    verifyEqual(testCase, stageDetails.structureGate, ...
        legacyDetails.structureGate, 'AbsTol', 0);
    verifyEqual(testCase, stageDetails.whiteningGate, ...
        legacyDetails.whiteningGate, 'AbsTol', 0);
    verifyEqual(testCase, stageDetails.brightnessNeed, ...
        legacyDetails.brightnessNeed, 'AbsTol', 0);
    verifyEqual(testCase, stageDetails.globalHeadroom, ...
        legacyDetails.globalHeadroom, 'AbsTol', 0);
    verifyEqual(testCase, stageDetails.hardProtectionMask, ...
        legacyDetails.hardProtectionMask, 'AbsTol', 0);

    % 快照语义（T07 衔接）：门控积与 1 - whitening 快照一致（仅 1-x
    % 补码往返舍入）；supportMap 与 T07 快照重算一致。
    verifyEqual(testCase, stageDetails.whiteningGateSnapshot, ...
        1 - protection.target.whitening, 'AbsTol', 0);
    verifyLessThanOrEqual(testCase, max(abs( ...
        contract.structureGate(:) .* contract.featureGate(:) - ...
        stageDetails.whiteningGateSnapshot(:))), 1e-15);
    whiteningAllowed = min(beautyMasks.skinMask, ...
        beautyMasks.strengthMap) .* (1 - protection.hard);
    whiteningAllowed(faceSkinSupport) = ...
        max(whiteningAllowed(faceSkinSupport), .85);
    snapshotSupport = min(max((strength / 100) ^ .85 .* ...
        whiteningAllowed .* stageDetails.highlightProtection .* ...
        (1 - protection.target.whitening), 0), 1);
    verifyLessThanOrEqual(testCase, ...
        max(abs(stageDetails.supportMap(:) - snapshotSupport(:))), ...
        1e-15);

    % hard identity 保持：hard 区域 supportMap/delta 恒 0。
    verifyEqual(testCase, ...
        nnz(stageDetails.supportMap(protection.hard >= .999)), 0);
    verifyEqual(testCase, ...
        nnz(stageDetails.delta(protection.hard >= .999)), 0);
end

% 鼻部不被整体排除：fixture 含鼻部结构（幅度封顶激活），美白 delta
% 在鼻部语义内必须非零。
[~, stageDetails50] = beauty.applySkinWhitening(image, frequency, ...
    beautyMasks, 50, contract);
noseRegion = beautyMasks.noseMask > .5;
verifyGreaterThan(testCase, sum(stageDetails50.delta(noseRegion)), 0, ...
    '鼻部美白不得因 consumer migration 被整体排除。');

% 负向证明：stage 路径的全部输出对 structure/whitening/hard masks 扰
% 动完全不变（只消费 stage contract），legacy 路径则会随之变化。
[~, legacyDetails60] = beauty.applySkinWhitening(image, frequency, ...
    beautyMasks, 60);
[~, stageDetails60] = beauty.applySkinWhitening(image, frequency, ...
    beautyMasks, 60, contract);
perturbedMasks = beautyMasks;
perturbedMasks.structureProtectionMask = ...
    min(1, beautyMasks.structureProtectionMask * .5 + .25);
perturbedMasks.whiteningProtectionMask = ...
    min(1, beautyMasks.whiteningProtectionMask * .5 + .25);
perturbedMasks.hardProtectionMask = ...
    min(1, beautyMasks.hardProtectionMask * .5 + .25);
[~, perturbedLegacyDetails] = beauty.applySkinWhitening(image, ...
    frequency, perturbedMasks, 60);
[~, perturbedStageDetails] = beauty.applySkinWhitening(image, ...
    frequency, perturbedMasks, 60, contract);
verifyTrue(testCase, ...
    nnz(perturbedLegacyDetails.supportMap ~= ...
    legacyDetails60.supportMap) > 0, ...
    'structure/whitening/hard 扰动必须确实影响 legacy 路径，否则本断言无意义。');
verifyEqual(testCase, perturbedStageDetails.supportMap, ...
    stageDetails60.supportMap, 'AbsTol', 0);
verifyEqual(testCase, perturbedStageDetails.delta, ...
    stageDetails60.delta, 'AbsTol', 0);
verifyEqual(testCase, perturbedStageDetails.brightnessNeed, ...
    stageDetails60.brightnessNeed, 'AbsTol', 0);
verifyEqual(testCase, perturbedStageDetails.globalHeadroom, ...
    stageDetails60.globalHeadroom, 'AbsTol', 0);

% 诊断收口：stage 路径不再报告 structure/whitening 兼容 alias，新增
% whiteningGateSnapshot 快照；legacy 路径字段保持不变。
verifyEqual(testCase, isfield(stageDetails60, ...
    {'structureProtectionMask', 'whiteningProtectionMask'}), ...
    [false, false], ...
    'stage 路径不得再报告 structure/whitening 兼容 alias 诊断字段。');
verifyTrue(testCase, isfield(stageDetails60, 'whiteningGateSnapshot'));
legacyWhiteningAliases = isfield(legacyDetails60, ...
    {'structureProtectionMask', 'whiteningProtectionMask'});
verifyFalse(testCase, any(legacyWhiteningAliases), ...
    '兼容入口不得再报告 legacy 保护诊断字段。');
verifyTrue(testCase, isfield(legacyDetails60, 'whiteningGateSnapshot'), ...
    '兼容入口与生产入口必须共享规范 Whitening contract 诊断。');
verifyFalse(testCase, isfield(whiteStage, 'whiteningProtectionMask'), ...
    'stage 结果不得再报告 whitening 兼容 alias 字段。');
verifyFalse(testCase, isfield(whiteLegacy, 'whiteningProtectionMask'), ...
    'legacy 入口也必须收口为规范 contract，不得继续发布 protection alias。');

% 缺字段与取值越界 fail-fast：不静默回退拼装。
brokenContract = rmfield(contract, 'featureGate');
verifyError(testCase, @() beauty.applySkinWhitening(image, frequency, ...
    beautyMasks, 60, brokenContract), 'beauty:InvalidWhiteningInput');
brokenContract = rmfield(contract, 'featureZeroGate');
verifyError(testCase, @() beauty.applySkinWhitening(image, frequency, ...
    beautyMasks, 60, brokenContract), 'beauty:InvalidWhiteningInput');
brokenContract = rmfield(contract, 'whitening');
verifyError(testCase, @() beauty.applySkinWhitening(image, frequency, ...
    beautyMasks, 60, brokenContract), 'beauty:InvalidWhiteningInput');
brokenContract = contract;
brokenContract.structureGate = min(1, ...
    brokenContract.structureGate) + .25;
verifyError(testCase, @() beauty.applySkinWhitening(image, frequency, ...
    beautyMasks, 60, brokenContract), 'beauty:InvalidWhiteningInput');
end

function testComposeConsumesStageProtectionContract(testCase)
%TESTCOMPOSECONSUMESSTAGEPROTECTIONCONTRACT T19：提供生产端拼装的
%   Final Compose stage contract 时，hard identity restore 的唯一来源
%   是 contract.hard（T07 单独发布的严格二值 identity），compose 不再
%   解释 legacy general hardProtectionMask：扰动该字段不改变 stage 路
%   径的任何输出（含 diagnostics.hardProtectionMask），legacy 路径则
%   会随之变化；stage 路径甚至不再要求 beautyMasks 携带该字段。hard
%   restore 仍在合成最终权威位置执行（RGB 渲染与 inactive 恢复之后），
%   hard 区域最终 RGB 与源图逐位相等；非 hard 区域合成与迁移前等价
%   （stage 与 legacy 全输出、全诊断逐位一致，bit-exact）。缺字段与
%   取值越界 fail-fast：不静默回退拼装。
[image, faceBox, parsing] = fixtureImage(120, 160);
context = prepareBeautyContext(image, faceBox, parsing, ...
    emptyBodyParsing([120, 160]));
[beautyMasks, ~] = masks.buildBeautyMasks(image, context, faceBox);
protection = masks.buildStageProtectionMasks(beautyMasks);
[frequency, ~] = beauty.decomposeSkinFrequency(image, faceBox);
[blemishMap, ~] = beauty.buildBlemishMap(image, frequency, beautyMasks);
contract = makeTestComposeContract(protection);
verifyTrue(testCase, nnz(protection.hard >= .999) > 0, ...
    'fixture 必须包含非空 hard identity 区域，否则断言无意义。');
verifyTrue(testCase, all(protection.hard(:) == 0 | ...
    protection.hard(:) == 1), 'hard 必须是严格二值 identity mask。');
verifyEqual(testCase, protection.hard, ...
    beautyMasks.hardProtectionMask, 'AbsTol', 0);

strengthCombos = [80, 30; 100, 0; 25, 75; 0, 100];
hardPixels = repmat(protection.hard >= .999, [1, 1, 3]);
for index = 1:size(strengthCombos, 1)
    smoothingStrength = strengthCombos(index, 1);
    whiteningStrength = strengthCombos(index, 2);
    [processing, repairedFrequency] = makeComposeProcessing(image, ...
        frequency, beautyMasks, protection, blemishMap, ...
        smoothingStrength, whiteningStrength);
    [legacyOutput, legacyDiagnostics] = beauty.composeBeautyResult( ...
        image, frequency, repairedFrequency, beautyMasks, ...
        whiteningStrength, processing);
    [stageOutput, stageDiagnostics] = beauty.composeBeautyResult( ...
        image, frequency, repairedFrequency, beautyMasks, ...
        whiteningStrength, processing, contract);

    % 与 legacy 路径逐位等价：T19 迁移不改变任何数值（protection.hard
    % 与 legacy hard 来源 bit-exact 同值，hard 区域定义不变）。
    verifyTrue(testCase, isequaln(stageOutput, legacyOutput), ...
        'stage 路径的合成结果必须与 legacy 逐位一致。');
    verifyTrue(testCase, isequaln(stageDiagnostics, legacyDiagnostics), ...
        'stage 路径的合成诊断必须与 legacy 逐位一致。');

    % hard restore 权威位置：hard 区域最终 RGB 与源图逐位相等。
    verifyEqual(testCase, stageOutput(hardPixels), image(hardPixels));
    verifyEqual(testCase, stageDiagnostics.hardProtectionMask, ...
        protection.hard, 'AbsTol', 0);
    verifyEqual(testCase, stageDiagnostics.hardProtectionUnchanged, 0);
end

% 负向证明：stage 路径对 beautyMasks.hardProtectionMask 扰动完全不变
% （compose 不再解释 legacy general hard mask），legacy 路径则会随之
% 变化：在原 hard 之外注入一块活动皮肤作为新增 hard 区域。
[processing, repairedFrequency] = makeComposeProcessing(image, ...
    frequency, beautyMasks, protection, blemishMap, 80, 30);
[legacyOutput, ~] = beauty.composeBeautyResult(image, frequency, ...
    repairedFrequency, beautyMasks, 30, processing);
[stageOutput, stageDiagnostics] = beauty.composeBeautyResult(image, ...
    frequency, repairedFrequency, beautyMasks, 30, processing, ...
    contract);
blobMask = zeros(size(protection.hard));
blobMask(55:66, 35:46) = 1;
verifyTrue(testCase, ...
    nnz(blobMask & beautyMasks.strengthMap > .05) > 0, ...
    '注入 blob 必须落在活动皮肤上，否则本断言无意义。');
verifyTrue(testCase, ...
    nnz(blobMask & protection.hard >= .999) == 0, ...
    '注入 blob 必须落在原 hard 之外，否则本断言无意义。');
perturbedMasks = beautyMasks;
perturbedMasks.hardProtectionMask = ...
    max(beautyMasks.hardProtectionMask, blobMask);
[legacyPerturbedOutput, ~] = beauty.composeBeautyResult(image, ...
    frequency, repairedFrequency, perturbedMasks, 30, processing);
[stagePerturbedOutput, stagePerturbedDiagnostics] = ...
    beauty.composeBeautyResult(image, frequency, repairedFrequency, ...
    perturbedMasks, 30, processing, contract);
verifyTrue(testCase, nnz(legacyPerturbedOutput ~= legacyOutput) > 0, ...
    'hardProtectionMask 扰动必须确实影响 legacy 路径，否则本断言无意义。');
verifyEqual(testCase, stagePerturbedOutput, stageOutput, 'AbsTol', 0);
verifyEqual(testCase, stagePerturbedDiagnostics.hardProtectionMask, ...
    protection.hard, 'AbsTol', 0);

% stage 路径不再要求 beautyMasks 携带 legacy hardProtectionMask：
% 移除该字段后 stage 输出与诊断不变，legacy 路径 fail-fast。
masksWithoutHard = rmfield(beautyMasks, 'hardProtectionMask');
[stageNoLegacyOutput, stageNoLegacyDiagnostics] = ...
    beauty.composeBeautyResult(image, frequency, repairedFrequency, ...
    masksWithoutHard, 30, processing, contract);
verifyEqual(testCase, stageNoLegacyOutput, stageOutput, 'AbsTol', 0);
verifyTrue(testCase, isequaln(stageNoLegacyDiagnostics, ...
    stageDiagnostics), ...
    '移除 legacy hard 字段不得改变 stage 路径的诊断。');
verifyError(testCase, @() beauty.composeBeautyResult(image, ...
    frequency, repairedFrequency, masksWithoutHard, 30, processing), ...
    'beauty:InvalidMasks');

% 缺字段与取值越界 fail-fast：不静默回退拼装。
brokenContract = rmfield(contract, 'hard');
verifyError(testCase, @() beauty.composeBeautyResult(image, ...
    frequency, repairedFrequency, beautyMasks, 30, processing, ...
    brokenContract), 'beauty:InvalidComposeInput');
brokenContract = contract;
brokenContract.hard = min(1, brokenContract.hard) + .25;
verifyError(testCase, @() beauty.composeBeautyResult(image, ...
    frequency, repairedFrequency, beautyMasks, 30, processing, ...
    brokenContract), 'beauty:InvalidMasks');
end

function testRuntimeEvidenceAssemblesProducerArtifactsBitExact(testCase)
%TESTRUNTIMEEVIDENCEASSEMBLESPRODUCERARTIFACTSBITEXACT T11：beautifyImage
%   内部组装的运行期 evidence（frequency/blemish）必须与独立调用
%   producer 的产物 bit-exact 一致，证明编排层只搬运 runtime evidence、
%   不改变任何数值；blemish map 不读取美颜强度，不同参数组合下完全一致。
[image, faceBox, parsing] = fixtureImage(120, 160);
context = prepareBeautyContext(image, faceBox, parsing, ...
    emptyBodyParsing([120, 160]));
uncachedContext = rmfield(context, 'runtimeCache');
params = struct('smoothingStrength', 60, 'whiteningStrength', 30);
[~, diagnostics] = beautifyImage(image, params, faceBox, uncachedContext);

[beautyMasks, ~] = masks.buildBeautyMasks(image, uncachedContext, faceBox);
[frequency, decompositionDiagnostics] = beauty.decomposeSkinFrequency( ...
    image, faceBox);
[blemishMap, blemishDiagnostics] = beauty.buildBlemishMap( ...
    image, frequency, beautyMasks);

% blemish map 与 blemish 运行期证据：与 producer 逐字段 bit-exact。
verifyEqual(testCase, diagnostics.blemishMap, blemishMap, 'AbsTol', 0);
evidenceNames = {'fineEvidence', 'midEvidence', 'chromaEvidence', ...
    'skinCandidate', 'structureProtectionMask'};
for index = 1:numel(evidenceNames)
    verifyEqual(testCase, ...
        diagnostics.blemish.(evidenceNames{index}), ...
        blemishDiagnostics.(evidenceNames{index}), 'AbsTol', 0);
end

% frequency 分解：与 producer bit-exact。
bandNames = {'base', 'mid', 'fine'};
for index = 1:numel(bandNames)
    verifyEqual(testCase, ...
        diagnostics.frequency.(bandNames{index}), ...
        decompositionDiagnostics.(bandNames{index}), 'AbsTol', 0);
end
verifyEqual(testCase, diagnostics.frequency.reconstructionError, ...
    decompositionDiagnostics.reconstructionError, 'AbsTol', 0);
verifyEqual(testCase, diagnostics.frequency.fineSigma, ...
    decompositionDiagnostics.fineSigma, 'AbsTol', 0);
verifyEqual(testCase, diagnostics.frequency.mediumSigma, ...
    decompositionDiagnostics.mediumSigma, 'AbsTol', 0);

% blemish map 不读取强度：不同参数组合下与 producer 完全一致。
strengthCombos = [0, 100; 100, 0; 100, 100; 25, 75];
for index = 1:size(strengthCombos, 1)
    comboParams = struct( ...
        'smoothingStrength', strengthCombos(index, 1), ...
        'whiteningStrength', strengthCombos(index, 2));
    [~, comboDiagnostics] = beautifyImage(image, comboParams, faceBox, ...
        uncachedContext);
    verifyEqual(testCase, comboDiagnostics.blemishMap, blemishMap, ...
        'AbsTol', 0);
end
end

function testRuntimeEvidenceStaysOutOfPersistedPolicyTimeContext(testCase)
%TESTRUNTIMEEVIDENCESTAYSOUTOFPERSISTEDPOLICYTIMECONTEXT T11 验收：
%   runtime evidence（frequency/blemish）不得成为持久化 policy-time
%   Context 的必要输入——不进 V4 canonical 分层（semantic/
%   processability/evidence/protection），不出现在 T06 policy-time
%   evidence 层，规范化往返后也不引入运行期字段。
[image, faceBox, parsing] = fixtureImage(120, 160);
context = prepareBeautyContext(image, faceBox, parsing, ...
    emptyBodyParsing([120, 160]));

runtimeNames = {'runtimeEvidence', 'blemishMap', 'blemish', 'frequency'};
verifyEqual(testCase, isfield(context, runtimeNames), ...
    [false, false, false, false], ...
    '持久化 Context 不得携带 runtime evidence 字段。');
verifyTrue(testCase, isfield(context, 'evidence'));
verifyEqual(testCase, isfield(context.evidence, ...
    {'blemishMap', 'blemish', 'frequency', 'fine', 'mid', 'base'}), ...
    false(1, 6), ...
    'policy-time evidence 层显式不含 blemish/frequency 结果。');

reread = normalizeBeautyContext(image, faceBox, context);
verifyEqual(testCase, isfield(reread, runtimeNames), ...
    [false, false, false, false], ...
    '规范化往返后 Context 不得引入 runtime evidence 字段。');
end

function [image, faceBox, parsing] = fixtureImage(height, width)
image = uint8(ones(height, width, 3) * 145);
[xGrid, yGrid] = meshgrid(1:width, 1:height);
skin = ((xGrid - width * .50) / (width * .33)) .^ 2 + ...
    ((yGrid - height * .43) / (height * .40)) .^ 2 <= 1;
neck = xGrid >= width * .40 & xGrid <= width * .60 & ...
    yGrid >= height * .73 & yGrid <= height * .94;
skin = skin | neck;
for channel = 1:3
    channelImage = image(:, :, channel);
    channelImage(skin) = uint8(168 + 7 * sin(2 * pi * xGrid(skin) / 17));
    image(:, :, channel) = channelImage;
end
nose = ((xGrid - width * .50) / (width * .10)) .^ 2 + ...
    ((yGrid - height * .45) / (height * .20)) .^ 2 <= 1;
image(:, :, 1) = image(:, :, 1) + uint8(12 * nose);
image(:, :, 2) = image(:, :, 2) + uint8(7 * nose);
image(:, :, 3) = image(:, :, 3) + uint8(4 * nose);
image(ceil(height * .45):ceil(height * .55), ...
    ceil(width * .43):ceil(width * .46), :) = uint8(95);
eye = false(height, width);
eye(ceil(height * .30):ceil(height * .33), ...
    ceil(width * .38):ceil(width * .46)) = true;
lip = false(height, width);
lip(ceil(height * .62):ceil(height * .66), ...
    ceil(width * .43):ceil(width * .57)) = true;
faceBox = [round(width * .17), round(height * .08), ...
    round(width * .66), round(height * .67)];
parsing = emptyFaceParsing([height, width]);
parsing.regions.skin = double(skin);
parsing.regionConfidence.skin = double(skin);
parsing.regions.neck = double(neck);
parsing.regionConfidence.neck = double(neck);
parsing.regions.nose = double(nose);
parsing.regionConfidence.nose = double(nose);
parsing.regions.leftEye = double(eye);
parsing.regionConfidence.leftEye = double(eye);
parsing.regions.upperLip = double(lip);
parsing.regionConfidence.upperLip = double(lip);
parsing.regions.lowerLip = double(lip);
parsing.regionConfidence.lowerLip = double(lip);
end

function parsing = emptyFaceParsing(imageSize)
names = faceParsingClassNames();
parsing = struct('regions', struct(), 'regionConfidence', struct());
for index = 1:numel(names)
    parsing.regions.(names{index}) = zeros(imageSize);
    parsing.regionConfidence.(names{index}) = zeros(imageSize);
end
end

function options = emptyBodyParsing(imageSize)
options = struct('probabilities', zeros([imageSize, 20], 'single'));
end

function contract = makeTestRepairContract(beautyMasks, protection, ...
    blemishMap) %#ok<INUSD>
%MAKETESTREPAIRCONTRACT 调用生产端唯一组装点 beauty.repairStageContract
%   （T14/T15/T30/T31），供消费侧重建断言与扰动负向证明使用：组装只消费
%   stage protection 的规范门（target.*/support.*/hard/noseMidProtection/
%   regionBandFine/regionBandMid）与 runtime blemish 证据，不读取任何
%   general mask。
contract = beauty.repairStageContract(protection, blemishMap);
end

function contract = makeTestBaseLuminanceContract(beautyMasks, protection) %#ok<INUSD>
%MAKETESTBASELUMINANCECONTRACT 调用生产端唯一组装点
%   beauty.baseLuminanceStageContract（T16/T32），供消费侧等价断言与扰动
%   负向证明使用：组装只消费 stage protection 的规范门
%   （target.baseLuminance/support.baseLuminance/hard/regionBandBase），
%   不读取任何 legacy general mask。
contract = beauty.baseLuminanceStageContract(protection);
end

function contract = makeTestToneContract(beautyMasks, protection) %#ok<INUSD>
%MAKETESTTONECONTRACT 调用生产端唯一组装点 beauty.toneStageContract
%   （T17/T33），供消费侧等价断言与扰动负向证明使用：组装只消费 stage
%   protection 的规范门（target.tone/support.tone/hard/toneGates），
%   不读取任何 legacy general mask（structure/chroma/hard/tone 保护图）。
contract = beauty.toneStageContract(protection);
end

function contract = makeTestWhiteningContract(beautyMasks, protection) %#ok<INUSD>
%MAKETESTWHITENINGCONTRACT 调用生产端唯一组装点
%   beauty.whiteningStageContract（T18/T33），供消费侧等价断言与扰动负向
%   证明使用：组装只消费 stage protection 的规范门（target.whitening/
%   support.whitening/hard/whiteningGates/whiteningAmplitudeCeiling），
%   不读取任何 legacy general mask（structure/whitening/faceSkin/nose 保护图）。
contract = beauty.whiteningStageContract(protection);
end

function contract = makeTestComposeContract(protection)
%MAKETESTCOMPOSECONTRACT 复现生产端 makeComposeStageContract（T19）的
%   拼装，供消费侧等价断言与扰动负向证明使用。
contract = struct('hard', protection.hard);
end

function [processing, repairedFrequency] = makeComposeProcessing( ...
    image, frequency, beautyMasks, protection, blemishMap, ...
    smoothingStrength, whiteningStrength)
%MAKECOMPOSEPROCESSING 按生产顺序拼装 compose 的 repairedFrequency 与
%   processing 输入（smoothing 走 stage contract 路径，与生产一致；
%   repair/baseLuminance/tone/whitening 走各自 legacy 调用，其 contract
%   迁移与本测试无关：两条 compose 路径共用同一组输入产物）。
[smoothed, ~] = beauty.smoothSkinTexture(frequency, beautyMasks, ...
    smoothingStrength, blemishMap, protection);
[repairedFrequency, ~] = beauty.repairSkinBlemishes(smoothed, ...
    beautyMasks, blemishMap, smoothingStrength);
[baseResult, ~] = beauty.evenSkinLuminance(frequency, beautyMasks, ...
    smoothingStrength);
[toneResult, ~] = beauty.normalizeSkinTone(image, frequency, ...
    beautyMasks, blemishMap, smoothingStrength);
[whiteningResult, ~] = beauty.applySkinWhitening(image, frequency, ...
    beautyMasks, whiteningStrength);
processing = struct( ...
    'baseLuminance', baseResult, ...
    'skinTone', toneResult, ...
    'whitening', whiteningResult);
end

function value = smoothStep(inputValue, low, high)
%SMOOTHSTEP 复现生产 smoothstep 曲线（t^2*(3-2t)），供 tone 重算使用。
t = min(max((double(inputValue) - low) / max(high - low, eps), 0), 1);
value = t .^ 2 .* (3 - 2 * t);
end
