function [whiteningResult, diagnostics] = applySkinWhitening( ...
        inputImage, frequency, beautyMasks, whiteningStrength)
%APPLYSKINWHITENING 生成受保护的低频亮度提亮结果。
%   美白只产生亮度增量，不读取或修改 Fine/Mid。强度曲线连续单调，
%   增量同时受 toneProtectionMask、structureProtectionMask、硬保护和
%   当前低频高光余量限制，最终由 composeBeautyResult 一次合成。

if nargin < 4
    error('beauty:InvalidWhiteningInput', ...
        '美白需要输入图像、频率结构、Beauty Masks 和美白强度。');
end
validateImage(inputImage);
imageSize = size(inputImage, 1:2);
validateFrequency(frequency, imageSize);
validateMasks(beautyMasks, imageSize);
if ~isValidStrength(whiteningStrength)
    error('beauty:InvalidStrength', '美白强度必须是 0 到 100 的数值标量。');
end

sourceLuminance = double(frequency.sourceLuminance);
base = double(frequency.base);
skinMask = readMask(beautyMasks, 'skinMask', imageSize);
strengthMap = readMask(beautyMasks, 'strengthMap', imageSize);
structureProtection = readMask(beautyMasks, ...
    'structureProtectionMask', imageSize);
toneProtection = readOptionalMask(beautyMasks, ...
    'toneProtectionMask', imageSize);
hardProtection = readOptionalMask(beautyMasks, ...
    'hardProtectionMask', imageSize);

skinPixels = skinMask > .35 & strengthMap > .05 & ...
    hardProtection < .999;
if any(skinPixels(:))
    luminanceValues = sourceLuminance(skinPixels);
    medianLuminance = median(luminanceValues);
    upperLuminance = percentileValue(luminanceValues, .85);
else
    medianLuminance = .78;
    upperLuminance = .78;
end
brightnessNeed = min(max((.78 - medianLuminance) / .35, .18), 1);
globalHeadroom = min(max((.98 - upperLuminance) / .20, .15), 1);

ratio = double(whiteningStrength) / 100;
whiteningCurve = ratio ^ .85;
highlightProtection = min(max((.985 - base) / .18, 0), 1);
% 高光保护采用低频亮度判断，避免被 Fine/Mid 的细节误导。
highlightProtection = highlightProtection .^ .80;
structureGate = 1 - structureProtection;
toneGate = 1 - .86 * toneProtection;
allowed = min(skinMask, strengthMap) .* (1 - hardProtection);

% 硬保护边缘使用连续退让，避免皮肤与五官之间形成亮度台阶。
hardCore = hardProtection >= .999;
featureSetback = ones(imageSize);
if any(hardCore(:))
    faceScale = readFaceScale(frequency, beautyMasks, imageSize);
    setbackRadius = min(10, max(8, round(.024 * faceScale)));
    setbackT = min(max(bwdist(hardCore) ./ (setbackRadius + 1), 0), 1);
    featureSetback = setbackT .^ 2 .* (3 - 2 * setbackT);
end

whiteningSupport = whiteningCurve .* allowed .* highlightProtection .* ...
    structureGate .* toneGate .* featureSetback;
whiteningSupport = min(max(whiteningSupport, 0), 1);
whiteningDelta = .20 * brightnessNeed * globalHeadroom .* ...
    whiteningSupport;
whiteningDelta = min(max(whiteningDelta, 0), ...
    max(.001, .20 * brightnessNeed));
outputLuminance = min(max(sourceLuminance + whiteningDelta, 0), 1);

whiteningResult = struct( ...
    'whiteningCurve', whiteningCurve, ...
    'brightnessNeed', brightnessNeed, ...
    'globalHeadroom', globalHeadroom, ...
    'highlightProtection', highlightProtection, ...
    'structureGate', structureGate, ...
    'toneGate', toneGate, ...
    'featureSetback', featureSetback, ...
    'supportMap', whiteningSupport, ...
    'alphaMap', whiteningSupport, ...
    'whiteningSupport', whiteningSupport, ...
    'delta', whiteningDelta, ...
    'luminanceDelta', whiteningDelta, ...
    'whiteningDelta', whiteningDelta, ...
    'baseBefore', base, ...
    'baseAfter', base + whiteningDelta, ...
    'fineBefore', double(frequency.fine), ...
    'fineAfter', double(frequency.fine), ...
    'midBefore', double(frequency.mid), ...
    'midAfter', double(frequency.mid), ...
    'fineRetention', 1, ...
    'mediumRetention', 1, ...
    'outputLuminance', outputLuminance, ...
    'imageSize', [imageSize, 3], ...
    'whiteningStrength', double(whiteningStrength));
whiteningResult.outputImage = renderWhiteningImage(inputImage, ...
    outputLuminance);

diagnostics = struct( ...
    'whiteningCurve', whiteningCurve, ...
    'brightnessNeed', brightnessNeed, ...
    'globalHeadroom', globalHeadroom, ...
    'highlightProtection', highlightProtection, ...
    'structureGate', structureGate, ...
    'toneGate', toneGate, ...
    'featureSetback', featureSetback, ...
    'supportMap', whiteningSupport, ...
    'alphaMap', whiteningSupport, ...
    'whiteningSupport', whiteningSupport, ...
    'delta', whiteningDelta, ...
    'luminanceDelta', whiteningDelta, ...
    'whiteningDelta', whiteningDelta, ...
    'outputLuminance', outputLuminance, ...
    'fineRetention', 1, ...
    'mediumRetention', 1, ...
    'skinPixels', skinPixels, ...
    'structureProtectionMask', structureProtection, ...
    'toneProtectionMask', toneProtection, ...
    'hardProtectionMask', hardProtection, ...
    'imageSize', [imageSize, 3], ...
    'whiteningStrength', double(whiteningStrength));
end

function validateImage(inputImage)
if ~isa(inputImage, 'uint8') || ~isreal(inputImage) || ...
        ndims(inputImage) ~= 3 || size(inputImage, 3) ~= 3
    error('beauty:InvalidWhiteningInput', ...
        '美白输入图像必须是 uint8 三通道 RGB 图像。');
end
end

function validateFrequency(frequency, imageSize)
if ~isstruct(frequency) || ~isscalar(frequency) || ...
        ~all(isfield(frequency, {'sourceLuminance', 'base', 'mid', 'fine'}))
    error('beauty:InvalidWhiteningInput', ...
        '美白需要完整的亮度和 Base/Mid/Fine 频率结构。');
end
for name = {'sourceLuminance', 'base', 'mid', 'fine'}
    value = frequency.(name{1});
    if ~isnumeric(value) || ~isreal(value) || ...
            ~isequal(size(value), imageSize) || any(~isfinite(value(:)))
        error('beauty:InvalidWhiteningInput', ...
            '频率字段 %s 的尺寸或取值无效。', name{1});
    end
end
end

function validateMasks(beautyMasks, imageSize)
if ~isstruct(beautyMasks) || ~isscalar(beautyMasks)
    error('beauty:InvalidWhiteningInput', ...
        '美白需要标量 v3 Beauty Masks。');
end
required = {'skinMask', 'strengthMap', 'structureProtectionMask'};
for index = 1:numel(required)
    if ~isfield(beautyMasks, required{index})
        error('beauty:InvalidWhiteningInput', ...
            'Beauty Masks 缺少字段 %s。', required{index});
    end
    readMask(beautyMasks, required{index}, imageSize);
end
end

function value = readMask(context, name, imageSize)
if ~isfield(context, name)
    error('beauty:InvalidWhiteningInput', ...
        'Beauty Masks 缺少字段 %s。', name);
end
value = context.(name);
if (~isnumeric(value) && ~islogical(value)) || ~isreal(value) || ...
        ~isequal(size(value), imageSize) || any(~isfinite(value(:))) || ...
        any(value(:) < 0) || any(value(:) > 1)
    error('beauty:InvalidWhiteningInput', ...
        'Beauty Masks 字段 %s 无效。', name);
end
value = double(value);
end

function value = readOptionalMask(context, name, imageSize)
if isfield(context, name)
    value = readMask(context, name, imageSize);
else
    value = zeros(imageSize);
end
end

function value = percentileValue(values, fraction)
values = sort(double(values(:)));
if isempty(values)
    value = 0;
    return;
end
position = 1 + (numel(values) - 1) * fraction;
lower = floor(position);
upper = ceil(position);
if lower == upper
    value = values(lower);
else
    weight = position - lower;
    value = (1 - weight) * values(lower) + weight * values(upper);
end
end

function faceScale = readFaceScale(frequency, beautyMasks, imageSize)
if isfield(frequency, 'faceScale') && isnumeric(frequency.faceScale) && ...
        isscalar(frequency.faceScale) && isfinite(frequency.faceScale) && ...
        frequency.faceScale > 0
    faceScale = double(frequency.faceScale);
elseif isfield(beautyMasks, 'faceBox')
    faceScale = min(double(beautyMasks.faceBox(3:4)));
else
    faceScale = min(imageSize);
end
end

function outputImage = renderWhiteningImage(inputImage, outputLuminance)
ycbcr = rgb2ycbcr(im2double(inputImage));
sourceLuminance = ycbcr(:, :, 1);
ycbcr(:, :, 1) = outputLuminance;
outputImage = uint8(round(min(max(ycbcr2rgb(ycbcr), 0), 1) * 255));
inactive = abs(outputLuminance - sourceLuminance) <= eps;
for channel = 1:size(inputImage, 3)
    outputChannel = outputImage(:, :, channel);
    sourceChannel = inputImage(:, :, channel);
    outputChannel(inactive) = sourceChannel(inactive);
    outputImage(:, :, channel) = outputChannel;
end
end

function valid = isValidStrength(value)
valid = isnumeric(value) && isreal(value) && isscalar(value) && ...
    isfinite(value) && value >= 0 && value <= 100;
end
