function [blemishMap, diagnostics] = buildBlemishMap( ...
        inputImage, frequency, beautyMasks)
%BUILDBLEMISHMAP 根据固定频率和色度残差生成瑕疵置信度图。
%   瑕疵图不读取任何美颜强度，因此同一输入在不同滑块档位下保持
%   同一分类结果。Fine、Mid 和色度证据先分别归一化，再合成为一张
%   连续的 [0, 1] 置信度图；结构保护只在后续修复时限制修改量。
%
%   运行期 evidence 定位（T11）：本函数是 blemish 运行期 evidence 的
%   唯一生产者，输入仍是 BeautyMasks 与频率分解，数值逻辑（阈值、
%   权重、平滑）冻结不变。产物由 beautifyImage 组装进局部
%   runtimeEvidence 结构供 stage 消费；不写入持久化 policy-time
%   Context（不进 V4 分层、不进缓存兼容判定），与
%   masks.buildBeautyPolicyEvidence 的 policy-time evidence 层无
%   依赖关系。后续 Repair/Tone consumer 应从 runtimeEvidence 读取
%   本图，而不是假设它存在于静态 Context。

validateInput(inputImage, frequency, beautyMasks);
imageSize = size(inputImage, 1:2);
fine = double(frequency.fine);
mid = double(frequency.mid);
ycbcr = rgb2ycbcr(im2double(inputImage));
cb = ycbcr(:, :, 2);
cr = ycbcr(:, :, 3);

skinMask = readMask(beautyMasks, 'skinMask', imageSize);
hardProtection = readOptionalMask(beautyMasks, ...
    'hardProtectionMask', imageSize);
skinCandidate = skinMask .* (1 - hardProtection);
skinSupport = skinCandidate > .05;
if ~any(skinSupport(:))
    blemishMap = zeros(imageSize);
    diagnostics = emptyDiagnostics(imageSize, skinCandidate);
    return;
end

faceScale = readFaceScale(frequency, beautyMasks);
chromaSigma = min(12, max(2.5, .025 * faceScale));
localCb = imgaussfilt(cb, chromaSigma, 'Padding', 'replicate');
localCr = imgaussfilt(cr, chromaSigma, 'Padding', 'replicate');

fineMagnitude = abs(fine);
midMagnitude = abs(mid);
chromaMagnitude = max(abs(cb - localCb), abs(cr - localCr));

[fineEvidence, fineThresholds] = residualEvidence( ...
    fineMagnitude, skinSupport, .50, .88, .35, .95, .0035);
[midEvidence, midThresholds] = residualEvidence( ...
    midMagnitude, skinSupport, .50, .88, .40, 1.05, .0060);
[chromaEvidence, chromaThresholds] = residualEvidence( ...
    chromaMagnitude, skinSupport, .50, .88, .40, 1.05, .0100);

% 一个单独的证据只构成低置信度；多种证据同时出现时才逐步进入
% 中高置信度，避免把正常毛孔或鼻梁梯度整片判为瑕疵。
combinedEvidence = .30 * fineEvidence + .38 * midEvidence + ...
    .32 * chromaEvidence;
synergy = max(cat(3, fineEvidence .* midEvidence, ...
    fineEvidence .* chromaEvidence, midEvidence .* chromaEvidence), [], 3);
combinedEvidence = min(1, combinedEvidence + .22 * sqrt(synergy));

evidenceSigma = max(.65, min(2.5, .0025 * faceScale));
smoothedEvidence = imgaussfilt(combinedEvidence, evidenceSigma, ...
    'Padding', 'replicate');
confidence = .78 * combinedEvidence + .22 * smoothedEvidence;
confidence = min(max(confidence, 0), 1) .* double(skinCandidate > .01);

% 保留原始证据的空间位置，平滑项只负责让修复权重连续，不扩大皮肤
% 候选区域，也不削弱结构保护本身。
blemishMap = min(max(confidence, 0), 1);
structureProtection = readOptionalMask(beautyMasks, ...
    'structureProtectionMask', imageSize);
[chromaProtection, hasChromaProtection] = resolveChromaProtectionMask( ...
    beautyMasks, imageSize, 'beauty:InvalidBlemishInput', ...
    'beauty:ChromaProtectionConflict');
if ~hasChromaProtection
    chromaProtection = zeros(imageSize);
end
faceMask = readOptionalMask(beautyMasks, 'faceSkinMask', imageSize);
faceMask = min(faceMask, skinMask);
nonFaceMask = readOptionalMask(beautyMasks, ...
    'nonFaceSkinMask', imageSize);
nonFaceMask = min(nonFaceMask, skinMask);

diagnostics = struct( ...
    'blemishMap', blemishMap, ...
    'map', blemishMap, ...
    'confidence', blemishMap, ...
    'fineEvidence', fineEvidence, ...
    'midEvidence', midEvidence, ...
    'chromaEvidence', chromaEvidence, ...
    'fineMagnitude', fineMagnitude, ...
    'midMagnitude', midMagnitude, ...
    'chromaMagnitude', chromaMagnitude, ...
    'localCb', localCb, ...
    'localCr', localCr, ...
    'skinCandidate', skinCandidate, ...
    'faceCandidate', min(faceMask, skinCandidate), ...
    'nonFaceCandidate', min(nonFaceMask, skinCandidate), ...
    'structureProtectionMask', structureProtection, ...
    'chromaProtectionMask', chromaProtection, ...
    'toneProtectionMask', chromaProtection, ...
    'hardProtectionMask', hardProtection, ...
    'faceScale', faceScale, ...
    'imageSize', [imageSize, 3], ...
    'fineThresholds', fineThresholds, ...
    'midThresholds', midThresholds, ...
    'chromaThresholds', chromaThresholds);
end

function [evidence, thresholds] = residualEvidence( ...
        magnitude, support, centerFraction, highFraction, ...
        spreadMultiplier, upperMultiplier, floorValue)
values = magnitude(support);
center = percentileValue(values, centerFraction);
upper = percentileValue(values, highFraction);
spread = max(upper - center, floorValue);
low = center + spreadMultiplier * spread;
high = center + upperMultiplier * spread;
if high <= low
    high = low + floorValue;
end
evidence = smoothStep(magnitude, low, high) .* double(support);
thresholds = struct('center', center, 'upper', upper, ...
    'spread', spread, 'low', low, 'high', high);
end

function value = percentileValue(values, fraction)
values = sort(double(values(:)));
if isempty(values)
    value = 0;
    return;
end
position = 1 + (numel(values) - 1) * fraction;
lower = floor(position);
upper = ceil(position);
if lower == upper
    value = values(lower);
else
    weight = position - lower;
    value = (1 - weight) * values(lower) + weight * values(upper);
end
end

function value = smoothStep(inputValue, low, high)
t = min(max((double(inputValue) - low) / max(high - low, eps), 0), 1);
value = t .^ 2 .* (3 - 2 * t);
end

function faceScale = readFaceScale(frequency, beautyMasks)
if isfield(frequency, 'faceScale') && isnumeric(frequency.faceScale) && ...
        isscalar(frequency.faceScale) && isfinite(frequency.faceScale) && ...
        frequency.faceScale > 0
    faceScale = double(frequency.faceScale);
elseif isfield(frequency, 'faceBox')
    faceScale = min(double(frequency.faceBox(3:4)));
elseif isfield(beautyMasks, 'faceBox')
    faceScale = min(double(beautyMasks.faceBox(3:4)));
else
    faceScale = min(size(frequency.sourceLuminance));
end
end

function validateInput(inputImage, frequency, beautyMasks)
if ~isa(inputImage, 'uint8') || ~isreal(inputImage) || ...
        ndims(inputImage) ~= 3 || size(inputImage, 3) ~= 3
    error('beauty:InvalidBlemishInput', ...
        '瑕疵检测输入图像必须是 uint8 三通道 RGB 图像。');
end
if ~isstruct(frequency) || ~isscalar(frequency) || ...
        ~all(isfield(frequency, {'sourceLuminance', 'fine', 'mid'}))
    error('beauty:InvalidBlemishInput', ...
        '瑕疵检测需要完整的亮度、Fine 和 Mid 频率结构。');
end
imageSize = size(inputImage, 1:2);
for name = {'sourceLuminance', 'fine', 'mid'}
    value = frequency.(name{1});
    if ~isnumeric(value) || ~isreal(value) || ...
            ~isequal(size(value), imageSize) || ...
            any(~isfinite(value(:)))
        error('beauty:InvalidBlemishInput', ...
            '频率字段 %s 的尺寸或取值无效。', name{1});
    end
end
if ~isstruct(beautyMasks) || ~isscalar(beautyMasks)
    error('beauty:InvalidBlemishInput', ...
        '瑕疵检测需要标量 v3 Beauty Masks。');
end
end

function value = readMask(context, name, imageSize)
if ~isfield(context, name)
    error('beauty:InvalidBlemishInput', ...
        'Beauty Masks 缺少字段 %s。', name);
end
value = context.(name);
if (~isnumeric(value) && ~islogical(value)) || ~isreal(value) || ...
        ~isequal(size(value), imageSize) || any(~isfinite(value(:))) || ...
        any(value(:) < 0) || any(value(:) > 1)
    error('beauty:InvalidBlemishInput', ...
        'Beauty Masks 字段 %s 无效。', name);
end
value = double(value);
end

function value = readOptionalMask(context, name, imageSize)
if ~isfield(context, name)
    value = zeros(imageSize);
    return;
end
value = readMask(context, name, imageSize);
end

function diagnostics = emptyDiagnostics(imageSize, skinCandidate)
empty = zeros(imageSize);
diagnostics = struct( ...
    'blemishMap', empty, ...
    'confidence', empty, ...
    'fineEvidence', empty, ...
    'midEvidence', empty, ...
    'chromaEvidence', empty, ...
    'fineMagnitude', empty, ...
    'midMagnitude', empty, ...
    'chromaMagnitude', empty, ...
    'localCb', empty, ...
    'localCr', empty, ...
    'skinCandidate', skinCandidate, ...
    'faceCandidate', empty, ...
    'nonFaceCandidate', empty, ...
    'structureProtectionMask', empty, ...
    'chromaProtectionMask', empty, ...
    'toneProtectionMask', empty, ...
    'hardProtectionMask', empty, ...
    'faceScale', 0, ...
    'imageSize', [imageSize, 3], ...
    'fineThresholds', emptyThresholds(), ...
    'midThresholds', emptyThresholds(), ...
    'chromaThresholds', emptyThresholds());
end

function thresholds = emptyThresholds
thresholds = struct('center', 0, 'upper', 0, 'spread', 0, ...
    'low', 0, 'high', 0);
end
