function [frequency, diagnostics] = decomposeSkinFrequency(inputImage, faceBox)
%DECOMPOSESKINFREQUENCY 将亮度分解为 Base、Mid、Fine 三个固定频带。
%   两个频率尺度只由图像与人脸框决定，与滑块强度无关；三项相加
%   可以恢复原始亮度。

validateInput(inputImage, faceBox);
if exist('imgaussfilt', 'file') == 0 || exist('rgb2ycbcr', 'file') == 0
    error('beauty:MissingToolbox', ...
        '频率分解需要 Image Processing Toolbox。');
end

faceScale = min(faceBox(3:4));
fineSigma = min(4.5, max(.9, .006 * faceScale));
mediumSigma = min(32, max(5, .045 * faceScale));
ycbcr = rgb2ycbcr(im2double(inputImage));
sourceLuminance = ycbcr(:, :, 1);
fineBase = imgaussfilt(sourceLuminance, fineSigma, ...
    'Padding', 'replicate');
base = imgaussfilt(sourceLuminance, mediumSigma, ...
    'Padding', 'replicate');
mid = fineBase - base;
fine = sourceLuminance - fineBase;
reconstructed = base + mid + fine;

frequency = struct( ...
    'base', base, ...
    'mid', mid, ...
    'fine', fine, ...
    'sourceLuminance', sourceLuminance, ...
    'reconstructedLuminance', reconstructed, ...
    'fineBase', fineBase, ...
    'scales', struct('fineSigma', fineSigma, ...
    'mediumSigma', mediumSigma), ...
    'faceScale', faceScale, ...
    'imageSize', size(inputImage), ...
    'faceBox', double(faceBox));
diagnostics = struct( ...
    'fineSigma', fineSigma, ...
    'mediumSigma', mediumSigma, ...
    'reconstructionError', max(abs(reconstructed(:) - ...
    sourceLuminance(:))), ...
    'base', base, ...
    'mid', mid, ...
    'fine', fine);
end

function validateInput(inputImage, faceBox)
if ~isa(inputImage, 'uint8') || ~isreal(inputImage) || ...
        ndims(inputImage) ~= 3 || size(inputImage, 3) ~= 3
    error('beauty:InvalidImage', ...
        '输入图像必须是 uint8 三通道 RGB 图像。');
end
if ~isnumeric(faceBox) || ~isreal(faceBox) || ...
        ~isequal(size(faceBox), [1, 4]) || any(~isfinite(faceBox)) || ...
        faceBox(1) < 1 || faceBox(2) < 1 || any(faceBox(3:4) <= 0) || ...
        faceBox(1) + faceBox(3) - 1 > size(inputImage, 2) || ...
        faceBox(2) + faceBox(4) - 1 > size(inputImage, 1)
    error('beauty:InvalidFaceBox', '人脸框超出图像范围。');
end
end

