function [luminanceResult, diagnostics] = evenSkinLuminance( ...
        frequency, beautyMasks, smoothingStrength)
%EVENSKINLUMINANCE 对皮肤 Base 亮度执行局部均匀化。
%   本模块只读取 frequency.base。可靠皮肤的归一化加权局部参考用于
%   生成目标 Base；输出 baseDelta 已经包含全部作用权重，合成阶段不再
%   重复乘权，也不在此处渲染 RGB。

if nargin < 3
    error('beauty:InvalidEvenLuminanceInput', ...
        'Base 亮度均匀化需要频率、Beauty Masks 和磨皮强度。');
end
validateFrequency(frequency);
imageSize = size(frequency.base);
validateMasks(beautyMasks, imageSize);
if ~isValidStrength(smoothingStrength)
    error('beauty:InvalidStrength', ...
        '磨皮强度必须是 0 到 100 的数值标量。');
end

% 仅从 frequency.base 读取低频亮度；不依赖 sourceLuminance、Mid 或
% Fine，避免把已有模块的残差再次带入 Base 校正。
base = double(frequency.base);
skinMask = readMask(beautyMasks, 'skinMask', imageSize);
strengthMap = readMask(beautyMasks, 'strengthMap', imageSize);
structureProtection = readMask(beautyMasks, ...
    'structureProtectionMask', imageSize);
hardProtection = readOptionalMask(beautyMasks, ...
    'hardProtectionMask', imageSize);
textureProtection = readOptionalMask(beautyMasks, ...
    'textureProtectionMask', imageSize);
toneProtection = readOptionalMask(beautyMasks, ...
    'toneProtectionMask', imageSize);
chromaProtection = readOptionalMask(beautyMasks, ...
    'chromaProtectionMask', imageSize);
faceSkinMask = readOptionalMask(beautyMasks, 'faceSkinMask', imageSize);

% 参考权重与作用权重分开：前者只决定局部参考是否可信，后者决定
% 当前像素实际校正多少。这样五官和强结构不会污染邻域参考，也不会
% 通过同一张权重在最终合成时被再次衰减。
featureProtection = max(cat(3, textureProtection, toneProtection, ...
    chromaProtection), [], 3);
referenceReliability = skinMask .* strengthMap .* ...
    (1 - structureProtection) .* (1 - hardProtection) .* ...
    (1 - featureProtection);
referenceReliability = min(max(referenceReliability, 0), 1);

faceScale = readFaceScale(frequency, beautyMasks, imageSize);
referenceSigma = readReferenceSigma(frequency, faceScale);
referenceWeight = imgaussfilt(referenceReliability, referenceSigma, ...
    'Padding', 'replicate');
weightedReference = imgaussfilt(referenceReliability .* base, ...
    referenceSigma, 'Padding', 'replicate');
minimumReferenceWeight = .05;
referenceValid = referenceWeight >= minimumReferenceWeight;
localReference = base;
localReference(referenceValid) = weightedReference(referenceValid) ./ ...
    referenceWeight(referenceValid);

% 局部均值只负责消除空间不均，整体亮度基线以可靠脸部皮肤为零点
% 归一化。偏移是全图常量，不会在脸部和脸外交界制造新的梯度。
normalizationMask = referenceValid & faceSkinMask > .35 & ...
    referenceReliability > .05;
if ~any(normalizationMask(:))
    normalizationMask = referenceValid & referenceReliability > .05;
end
if any(normalizationMask(:))
    referenceOffset = median(base(normalizationMask) - ...
        localReference(normalizationMask));
else
    referenceOffset = 0;
end
localReference(referenceValid) = localReference(referenceValid) + ...
    referenceOffset;

% 参考覆盖度让非常稀疏的皮肤参考平滑退让；没有任何有效参考时为
% 零，保证该位置既没有 Base 增量，也不会被误诊为已支持校正。
referenceCoverage = min(referenceWeight / .20, 1);
referenceCoverage = smoothStep(referenceCoverage, .10, .75);
referenceCoverage(~referenceValid) = 0;

ratio = double(smoothingStrength) / 100;
% Base 是大尺度校正，采用保守的最大作用系数；原始目标差异仍先
% 按 ±.03 限幅，避免在低频结构边缘产生可见梯度。
baseCurve = ratio ^ .85;
baseAmplitudeGain = .06;
baseWeightCurve = baseAmplitudeGain .* baseCurve;
structureGate = 1 - structureProtection;
hardProtectionGate = 1 - hardProtection;
featureGate = 1 - featureProtection;
regionalSkinWeight = min(skinMask, strengthMap);
supportMap = baseWeightCurve .* regionalSkinWeight .* structureGate .* ...
    hardProtectionGate .* featureGate .* referenceCoverage;
supportMap = min(max(supportMap, 0), 1);

% 先限制未经计权的目标差异，再乘一次完整作用权重。该差异保留
% 符号，因此暗区可提亮、亮区可压低，二者使用同一条校正路径。
rawBaseDelta = localReference - base;
limitedBaseDelta = min(max(rawBaseDelta, -.03), .03);
baseDelta = limitedBaseDelta .* supportMap;
baseAfter = base + baseDelta;

luminanceResult = struct( ...
    'base', baseAfter, ...
    'baseBefore', base, ...
    'baseAfter', baseAfter, ...
    'outputBase', baseAfter, ...
    'targetBase', localReference, ...
    'baseDelta', baseDelta, ...
    'delta', baseDelta, ...
    'luminanceDelta', baseDelta, ...
    'baseCurve', baseCurve, ...
    'baseWeightCurve', baseWeightCurve, ...
    'baseAmplitudeGain', baseAmplitudeGain, ...
    'supportMap', supportMap, ...
    'baseSupport', supportMap, ...
    'alphaMap', supportMap, ...
    'reference', localReference, ...
    'referenceWeight', referenceWeight, ...
    'referenceValid', referenceValid, ...
    'imageSize', [imageSize, 3], ...
    'smoothingStrength', double(smoothingStrength));

diagnostics = struct( ...
    'base', baseAfter, ...
    'baseBefore', base, ...
    'baseAfter', baseAfter, ...
    'outputBase', baseAfter, ...
    'targetBase', localReference, ...
    'rawBaseDelta', rawBaseDelta, ...
    'limitedBaseDelta', limitedBaseDelta, ...
    'baseDelta', baseDelta, ...
    'delta', baseDelta, ...
    'luminanceDelta', baseDelta, ...
    'baseCurve', baseCurve, ...
    'baseWeightCurve', baseWeightCurve, ...
    'baseAmplitudeGain', baseAmplitudeGain, ...
    'regionalSkinWeight', regionalSkinWeight, ...
    'structureGate', structureGate, ...
    'hardProtectionGate', hardProtectionGate, ...
    'featureGate', featureGate, ...
    'referenceReliability', referenceReliability, ...
    'referenceWeight', referenceWeight, ...
    'referenceCoverage', referenceCoverage, ...
    'referenceOffset', referenceOffset, ...
    'minimumReferenceWeight', minimumReferenceWeight, ...
    'referenceValid', referenceValid, ...
    'hasReliableReference', any(referenceValid(:)), ...
    'positiveSupport', supportMap > 0 & baseDelta > 0, ...
    'negativeSupport', supportMap > 0 & baseDelta < 0, ...
    'supportMap', supportMap, ...
    'baseSupport', supportMap, ...
    'alphaMap', supportMap, ...
    'referenceSigma', referenceSigma, ...
    'faceScale', faceScale, ...
    'baseDeltaLimit', .03, ...
    'maxAbsBaseDelta', max(abs(baseDelta(:))), ...
    'frequencyUnchanged', true, ...
    'imageSize', [imageSize, 3], ...
    'smoothingStrength', double(smoothingStrength));
end

function validateFrequency(frequency)
if ~isstruct(frequency) || ~isscalar(frequency) || ...
        ~isfield(frequency, 'base')
    error('beauty:InvalidEvenLuminanceInput', ...
        'Base 亮度均匀化需要 frequency.base。');
end
base = frequency.base;
if ~isnumeric(base) || ~isreal(base) || ~ismatrix(base) || ...
        isempty(base) || any(~isfinite(base(:))) || ...
        any(base(:) < 0) || any(base(:) > 1)
    error('beauty:InvalidEvenLuminanceInput', ...
        'frequency.base 必须是 [0,1] 范围内的二维有限亮度图。');
end
end

function validateMasks(beautyMasks, imageSize)
if ~isstruct(beautyMasks) || ~isscalar(beautyMasks)
    error('beauty:InvalidEvenLuminanceInput', ...
        'Base 亮度均匀化需要标量 v3 Beauty Masks。');
end
required = {'skinMask', 'strengthMap', 'structureProtectionMask'};
for index = 1:numel(required)
    name = required{index};
    if ~isfield(beautyMasks, name)
        error('beauty:InvalidEvenLuminanceInput', ...
            'Beauty Masks 缺少字段 %s。', name);
    end
    readMask(beautyMasks, name, imageSize);
end
optional = {'hardProtectionMask', 'textureProtectionMask', ...
    'toneProtectionMask', 'chromaProtectionMask'};
for index = 1:numel(optional)
    if isfield(beautyMasks, optional{index})
        readMask(beautyMasks, optional{index}, imageSize);
    end
end
end

function value = readMask(context, name, imageSize)
value = context.(name);
if (~isnumeric(value) && ~islogical(value)) || ~isreal(value) || ...
        ~isequal(size(value), imageSize) || any(~isfinite(value(:))) || ...
        any(value(:) < 0) || any(value(:) > 1)
    error('beauty:InvalidEvenLuminanceInput', ...
        'Beauty Masks 字段 %s 无效。', name);
end
value = double(value);
end

function value = readOptionalMask(context, name, imageSize)
if isfield(context, name)
    value = readMask(context, name, imageSize);
else
    value = zeros(imageSize);
end
end

function faceScale = readFaceScale(frequency, beautyMasks, imageSize)
if isfield(beautyMasks, 'faceBox') && isnumeric(beautyMasks.faceBox) && ...
        isreal(beautyMasks.faceBox) && numel(beautyMasks.faceBox) == 4 && ...
        all(isfinite(beautyMasks.faceBox(:))) && ...
        all(double(beautyMasks.faceBox(3:4)) > 0)
    faceScale = min(double(beautyMasks.faceBox(3:4)));
elseif isfield(frequency, 'faceScale') && ...
        isnumeric(frequency.faceScale) && isreal(frequency.faceScale) && ...
        isscalar(frequency.faceScale) && isfinite(frequency.faceScale) && ...
        frequency.faceScale > 0
    faceScale = double(frequency.faceScale);
elseif isfield(frequency, 'faceBox') && ...
        isnumeric(frequency.faceBox) && numel(frequency.faceBox) == 4 && ...
        all(isfinite(frequency.faceBox(:))) && ...
        all(double(frequency.faceBox(3:4)) > 0)
    faceScale = min(double(frequency.faceBox(3:4)));
else
    faceScale = min(imageSize);
end
end

function referenceSigma = readReferenceSigma(frequency, faceScale)
% 优先复用分解阶段记录的 Base 尺度，保证同一输入使用同一尺度口径。
if isfield(frequency, 'scales') && isstruct(frequency.scales) && ...
        isscalar(frequency.scales) && ...
        isfield(frequency.scales, 'mediumSigma') && ...
        isnumeric(frequency.scales.mediumSigma) && ...
        isreal(frequency.scales.mediumSigma) && ...
        isscalar(frequency.scales.mediumSigma) && ...
        isfinite(frequency.scales.mediumSigma) && ...
        frequency.scales.mediumSigma > 0
    mediumSigma = double(frequency.scales.mediumSigma);
else
    mediumSigma = min(32, max(5, .045 * faceScale));
end
referenceSigma = min(48, max(5 * mediumSigma, .25 * faceScale));
end

function value = smoothStep(inputValue, low, high)
t = min(max((double(inputValue) - low) / max(high - low, eps), 0), 1);
value = t .^ 2 .* (3 - 2 * t);
end

function valid = isValidStrength(value)
valid = isnumeric(value) && isreal(value) && isscalar(value) && ...
    isfinite(value) && value >= 0 && value <= 100;
end
