function [smoothedFrequency, diagnostics] = smoothSkinTexture( ...
        frequency, beautyMasks, smoothingStrength, blemishMap)
%SMOOTHSKINTEXTURE 以独立保留率图连续衰减 Fine 和 Mid 纹理。
%   Base 始终不变；Fine 和 Mid 使用同一输入分解的不同保留率，
%   结构、纹理和硬保护限制作用范围，鼻部 Mid 额外使用保守门控。

if ~isstruct(frequency) || ~isscalar(frequency) || ...
        ~all(isfield(frequency, {'base', 'mid', 'fine', ...
        'sourceLuminance', 'imageSize', 'faceBox'}))
    error('beauty:InvalidFrequency', ...
        '必须提供完整的 Base/Mid/Fine 频率结构。');
end
if nargin < 2 || ~isstruct(beautyMasks) || ~isscalar(beautyMasks)
    error('beauty:InvalidMasks', '必须提供 v3 Beauty Masks。');
end
if nargin < 3 || ~isValidStrength(smoothingStrength)
    error('beauty:InvalidStrength', '磨皮强度必须是 0 到 100 的数值标量。');
end

imageSize = frequency.imageSize(1:2);
validateBand(frequency.base, imageSize, 'base');
validateBand(frequency.mid, imageSize, 'mid');
validateBand(frequency.fine, imageSize, 'fine');
requiredMaskFields = {'strengthMap', 'textureProtectionMask', ...
    'structureProtectionMask'};
if ~all(isfield(beautyMasks, requiredMaskFields))
    error('beauty:InvalidMasks', 'v3 Beauty Masks 缺少必需字段。');
end
% 色度保护只由独立色度模块消费；此处通过规范字段解析兼容 alias，
% 防止错误的 Context 在进入管线后才以难定位的方式失败。
[~, hasChromaProtection] = resolveChromaProtectionMask( ...
    beautyMasks, imageSize, 'beauty:InvalidMasks', ...
    'beauty:ChromaProtectionConflict');
if ~hasChromaProtection
    error('beauty:InvalidMasks', ...
        'v3 Beauty Masks 缺少 chromaProtectionMask。');
end
strengthMap = validateMask(beautyMasks.strengthMap, imageSize, ...
    'strengthMap');
textureProtection = validateMask(beautyMasks.textureProtectionMask, ...
    imageSize, 'textureProtectionMask');
structureProtection = validateMask(beautyMasks.structureProtectionMask, ...
    imageSize, 'structureProtectionMask');
hardProtection = optionalMask(beautyMasks, ...
    'hardProtectionMask', imageSize);
if nargin < 4 || isempty(blemishMap)
    blemishMap = zeros(imageSize);
else
    blemishMap = validateMask(blemishMap, imageSize, 'blemishMap');
end

protection = max(cat(3, textureProtection, ...
    structureProtection, hardProtection), [], 3);
profile = beautySmoothingProfile(smoothingStrength);
ratio = double(smoothingStrength) / 100;
processableSkin = strengthMap > .05 & protection < .80;
ordinarySkin = processableSkin & blemishMap < .60;
if any(processableSkin(:))
    blemishMean = mean(blemishMap(processableSkin));
    if any(ordinarySkin(:))
        fineEnergy = mean(abs(frequency.fine(ordinarySkin)));
    else
        fineEnergy = mean(abs(frequency.fine(processableSkin)));
    end
else
    blemishMean = 0;
    fineEnergy = 0;
end
faceScale = readFaceScale(frequency);
highStrengthWeight = profile.highStrengthCurve;
smallResolutionWeight = 1 - smoothStep(faceScale, 140, 180);
textureRetentionFloor = .60 + .12 * smoothStep(fineEnergy, .004, .010) ...
    - .08 * smallResolutionWeight - .08 * ...
    smoothStep(blemishMean, .08, .14);

% 适应性保留率只设置单调下降曲线的下限。用 max 而不是在高档
% 向上插值，保证固定输入下实际 Fine 保留率不会因高档自适应反弹。
fineRetention = max(profile.fineRetention, textureRetentionFloor);
smallFaceWeight = (1 - smoothStep(faceScale, 72, 96)) .* ...
    smoothStep(ratio, .05, .20);
smallFaceFloor = .66 - .06 * smallResolutionWeight;
% 小人脸只把保留率平滑地向 .60 附近收敛，且不允许低于该自然
% 质感下限；目标为常数时，随着强度增加不会出现保留率反弹。
fineRetention = fineRetention - smallFaceWeight .* ...
    max(fineRetention - smallFaceFloor, 0);
if all(isfield(beautyMasks, {'faceStrengthMap', 'nonFaceStrengthMap'}))
    nonFaceStrength = validateMask(beautyMasks.nonFaceStrengthMap, ...
        imageSize, 'nonFaceStrengthMap');
    effectStrength = profile.alphaCurve .* strengthMap;
    nonFacePixels = nonFaceStrength > .01;
    effectStrength(nonFacePixels) = profile.outsideFaceStrength .* ...
        nonFaceStrength(nonFacePixels);
else
    effectStrength = profile.alphaCurve .* strengthMap;
end
% 结构保护同时约束 Fine；直接使用原始保护值会让中等置信的
% 连续结构仍有过大的残差衰减，因此在 Fine 侧也采用连续退让。
fineStructureGate = max(0, 1 - 4 * structureProtection);
fineProtection = max(textureProtection, hardProtection);
alphaMap = effectStrength .* (1 - fineProtection) .* fineStructureGate;
alphaMap = min(max(double(alphaMap), 0), 1);
noseMask = optionalMask(beautyMasks, 'noseMask', imageSize);
% 鼻部门控随当前 Alpha 连续增加，且与既有结构保护相乘；它不能绕过
% nose 的结构保护，只能进一步降低普通 Mid 的处理量。
noseMidGate = 1 - .50 * noseMask .* profile.alphaCurve;
% Mid 承载较大尺度的明暗起伏，比 Fine 更容易误伤鼻梁、脸缘和
% 眼窝等结构，因此对已有结构保护再做一次连续退让；普通平坦皮肤
% 的 structureProtection 为 0 时不受额外影响。
midStructureGate = fineStructureGate;
midAlphaMap = alphaMap .* midStructureGate .* noseMidGate;
fineRetentionMap = 1 - alphaMap .* (1 - fineRetention);
midRetention = profile.mediumRetention;
midRetentionMap = 1 - midAlphaMap .* (1 - midRetention);
smoothedFine = frequency.fine .* fineRetentionMap;
smoothedMid = frequency.mid .* midRetentionMap;
outputLuminance = frequency.base + smoothedMid + smoothedFine;

smoothedFrequency = frequency;
smoothedFrequency.fine = smoothedFine;
smoothedFrequency.mid = smoothedMid;
smoothedFrequency.reconstructedLuminance = outputLuminance;
smoothedFrequency.outputLuminance = outputLuminance;
smoothedFrequency.alphaMap = alphaMap;
smoothedFrequency.fineAlphaMap = alphaMap;
smoothedFrequency.fineRetention = fineRetention;
smoothedFrequency.effectiveProfileFineRetention = fineRetention;
smoothedFrequency.profileFineRetention = profile.fineRetention;
smoothedFrequency.profileMediumRetention = profile.mediumRetention;
smoothedFrequency.profile = profile;
smoothedFrequency.fineRetentionMap = fineRetentionMap;
smoothedFrequency.retentionMap = fineRetentionMap;
smoothedFrequency.actualFineRetentionMap = fineRetentionMap;
smoothedFrequency.fineActualRetentionMap = fineRetentionMap;
smoothedFrequency.midAlphaMap = midAlphaMap;
smoothedFrequency.midRetention = midRetention;
smoothedFrequency.mediumRetention = midRetention;
smoothedFrequency.midRetentionMap = midRetentionMap;
smoothedFrequency.mediumRetentionMap = midRetentionMap;
smoothedFrequency.actualMidRetentionMap = midRetentionMap;
smoothedFrequency.midActualRetentionMap = midRetentionMap;
smoothedFrequency.actualMediumRetentionMap = midRetentionMap;
diagnostics = struct( ...
    'alphaMap', alphaMap, ...
    'fineAlphaMap', alphaMap, ...
    'midAlphaMap', midAlphaMap, ...
    'profile', profile, ...
    'fineRetention', fineRetention, ...
    'effectiveProfileFineRetention', fineRetention, ...
    'profileFineRetention', profile.fineRetention, ...
    'profileMediumRetention', profile.mediumRetention, ...
    'adaptiveFineRetention', fineRetention, ...
    'highStrengthWeight', highStrengthWeight, ...
    'blemishMean', blemishMean, ...
    'fineEnergy', fineEnergy, ...
    'ordinarySkinMask', ordinarySkin, ...
    'smallResolutionWeight', smallResolutionWeight, ...
    'textureRetentionFloor', textureRetentionFloor, ...
    'smallFaceWeight', smallFaceWeight, ...
    'smallFaceFloor', smallFaceFloor, ...
    'noseMask', noseMask, ...
    'noseMidGate', noseMidGate, ...
    'midStructureGate', midStructureGate, ...
    'fineStructureGate', fineStructureGate, ...
    'fineProtectionMask', fineProtection, ...
    'fineRetentionMap', fineRetentionMap, ...
    'retentionMap', fineRetentionMap, ...
    'midRetention', midRetention, ...
    'mediumRetention', midRetention, ...
    'midRetentionMap', midRetentionMap, ...
    'mediumRetentionMap', midRetentionMap, ...
    'fineActualRetentionMap', fineRetentionMap, ...
    'actualFineRetentionMap', fineRetentionMap, ...
    'midActualRetentionMap', midRetentionMap, ...
    'actualMidRetentionMap', midRetentionMap, ...
    'actualMediumRetentionMap', midRetentionMap, ...
    'protectionMask', protection, ...
    'fineBefore', frequency.fine, ...
    'fineAfter', smoothedFine, ...
    'midBefore', frequency.mid, ...
    'midAfter', smoothedMid, ...
    'fineEnergyBefore', mean(abs(frequency.fine(:))), ...
    'fineEnergyAfter', mean(abs(smoothedFine(:))), ...
    'midEnergyBefore', mean(abs(frequency.mid(:))), ...
    'midEnergyAfter', mean(abs(smoothedMid(:))), ...
    'fineActualRetention', mean(fineRetentionMap(processableSkin)), ...
    'midActualRetention', mean(midRetentionMap(processableSkin)), ...
    'baseUnchanged', isequal(smoothedFrequency.base, frequency.base), ...
    'midUnchanged', isequal(smoothedMid, frequency.mid));
end

function valid = isValidStrength(value)
valid = isnumeric(value) && isreal(value) && isscalar(value) && ...
    isfinite(value) && value >= 0 && value <= 100;
end

function validateBand(value, imageSize, name)
if ~isnumeric(value) || ~isreal(value) || ~isequal(size(value), imageSize) || ...
        any(~isfinite(value(:)))
    error('beauty:InvalidFrequency', '频率分量 %s 无效。', name);
end
end

function value = validateMask(value, imageSize, name)
if (~isnumeric(value) && ~islogical(value)) || ~isreal(value) || ...
        ~isequal(size(value), imageSize) || any(~isfinite(value(:))) || ...
        any(value(:) < 0) || any(value(:) > 1)
    error('beauty:InvalidMasks', 'Mask %s 无效。', name);
end
value = double(value);
end

function value = optionalMask(context, name, imageSize)
if isfield(context, name)
    value = validateMask(context.(name), imageSize, name);
else
    value = zeros(imageSize);
end
end

function faceScale = readFaceScale(frequency)
if isfield(frequency, 'faceScale') && isnumeric(frequency.faceScale) && ...
        isreal(frequency.faceScale) && isscalar(frequency.faceScale) && ...
        isfinite(frequency.faceScale) && frequency.faceScale > 0
    faceScale = double(frequency.faceScale);
elseif isfield(frequency, 'faceBox') && isnumeric(frequency.faceBox) && ...
        numel(frequency.faceBox) == 4
    faceScale = min(double(frequency.faceBox(3:4)));
else
    faceScale = min(size(frequency.fine));
end
end

function value = smoothStep(inputValue, low, high)
t = min(max((double(inputValue) - low) / max(high - low, eps), 0), 1);
value = t .^ 2 .* (3 - 2 * t);
end
