function [beautifiedImage, diagnostics] = beautifyImage( ...
        inputImage, params, faceBox, beautyContext)
%BEAUTIFYIMAGE 通过 v3 package 编排结构感知的磨皮和美白。

if nargin < 2
    params = [];
end
if nargin < 3
    faceBox = [];
end
validateInput(inputImage, params, faceBox);
smoothingStrength = params.smoothingStrength;
whiteningStrength = params.whiteningStrength;

% 零强度严格返回原图，同时保留轻量诊断，避免无意义地触发模型推理。
if smoothingStrength == 0 && whiteningStrength == 0
    beautifiedImage = inputImage;
    diagnostics = struct('pipeline', 'v3', 'identity', true, ...
        'imageSize', size(inputImage));
    return;
end

ensureImageProcessingToolbox();
runtimeCache = [];
if nargin < 4 || isempty(beautyContext)
    beautyContext = normalizeBeautyContext(inputImage, faceBox);
else
    if isfield(beautyContext, 'runtimeCache')
        runtimeCache = beautyContext.runtimeCache;
        beautyContext = rmfield(beautyContext, 'runtimeCache');
    end
    try
        beautyContext = normalizeBeautyContext(inputImage, faceBox, ...
            beautyContext);
    catch exception
        if startsWith(exception.identifier, 'normalizeBeautyContext:')
            error('beautifyImage:InvalidContext', ...
                'Beauty Context 无效：%s', exception.message);
        end
        rethrow(exception);
    end
end

[beautifiedImage, diagnostics] = runV3Beauty(inputImage, beautyContext, ...
    faceBox, smoothingStrength, whiteningStrength, runtimeCache);
if ~isa(beautifiedImage, 'uint8') || ...
        ~isequal(size(beautifiedImage), size(inputImage))
    error('beautifyImage:InvalidOutput', ...
        '美颜结果必须保持输入图像的尺寸和数据类型。');
end
end

function validateInput(inputImage, params, faceBox)
if nargin < 1 || ~isValidRgbImage(inputImage)
    error('beautifyImage:InvalidImage', ...
        '输入图像必须是 uint8 三通道 RGB 图像。');
end
if nargin < 2 || ~isstruct(params) || ~isscalar(params) || ...
        ~all(isfield(params, {'smoothingStrength', 'whiteningStrength'}))
    error('beautifyImage:InvalidParams', ...
        '参数必须包含 smoothingStrength 和 whiteningStrength。');
end
if isfield(params, 'pipeline')
    error('beautifyImage:InvalidParams', ...
        'pipeline 选择已移除，beautifyImage 统一使用 v3。');
end
if ~isValidStrength(params.smoothingStrength) || ...
        ~isValidStrength(params.whiteningStrength)
    error('beautifyImage:InvalidParams', ...
        '美颜强度必须是范围 0 到 100 内的有限数值标量。');
end
if nargin < 3
    error('beautifyImage:InvalidFaceBox', ...
        '必须提供位于图像范围内的 [x y width height] 人脸框。');
end
validateFaceBox(faceBox, size(inputImage, 2), size(inputImage, 1));
end

function [beautifiedImage, diagnostics] = runV3Beauty( ...
        inputImage, beautyContext, faceBox, ...
        smoothingStrength, whiteningStrength, runtimeCache)
[hasRuntimeCache, beautyMasks, maskDiagnostics, frequency, ...
    decompositionDiagnostics, blemishMap, blemishDiagnostics, ...
    cacheDiagnostics] = readRuntimeCache(inputImage, runtimeCache, faceBox, ...
    beautyContext);
if ~hasRuntimeCache
    [beautyMasks, maskDiagnostics] = masks.buildBeautyMasks( ...
        inputImage, beautyContext, faceBox);
    maskDiagnostics.reusedRuntimeCache = false;
    maskDiagnostics.runtimeCache = cacheDiagnostics;
    [frequency, decompositionDiagnostics] = beauty.decomposeSkinFrequency( ...
        inputImage, faceBox);
    [blemishMap, blemishDiagnostics] = beauty.buildBlemishMap(inputImage, ...
        frequency, beautyMasks);
else
    maskDiagnostics.reusedRuntimeCache = true;
    maskDiagnostics.runtimeCache = cacheDiagnostics;
end
[smoothedFrequency, smoothingDiagnostics] = beauty.smoothSkinTexture( ...
    frequency, beautyMasks, smoothingStrength, blemishMap);
[repairedFrequency, repairDiagnostics] = beauty.repairSkinBlemishes( ...
    smoothedFrequency, beautyMasks, blemishMap, smoothingStrength);
[baseLuminance, baseLuminanceDiagnostics] = beauty.evenSkinLuminance( ...
    frequency, beautyMasks, smoothingStrength);
[skinTone, skinToneDiagnostics] = beauty.normalizeSkinTone(inputImage, ...
    frequency, beautyMasks, blemishMap, smoothingStrength);
[whitening, whiteningDiagnostics] = beauty.applySkinWhitening(inputImage, ...
    frequency, beautyMasks, whiteningStrength);
processing = struct( ...
    'blemishMap', blemishMap, ...
    'blemish', blemishDiagnostics, ...
    'repair', repairDiagnostics, ...
    'skinTone', skinTone, ...
    'skinToneDiagnostics', skinToneDiagnostics, ...
    'whitening', whitening, ...
    'whiteningDiagnostics', whiteningDiagnostics, ...
    'baseLuminance', baseLuminance, ...
    'evenSkinLuminance', baseLuminance, ...
    'maskDiagnostics', maskDiagnostics, ...
    'decompositionDiagnostics', decompositionDiagnostics, ...
    'smoothingDiagnostics', smoothingDiagnostics);
[beautifiedImage, composeDiagnostics] = beauty.composeBeautyResult( ...
    inputImage, frequency, repairedFrequency, beautyMasks, ...
    whiteningStrength, processing);
diagnostics = struct( ...
    'pipeline', 'v3', ...
    'identity', false, ...
    'reusedRuntimeCache', hasRuntimeCache, ...
    'beautyMasks', beautyMasks, ...
    'mask', maskDiagnostics, ...
    'frequency', decompositionDiagnostics, ...
    'blemishMap', blemishMap, ...
    'blemish', blemishDiagnostics, ...
    'runtimeCache', cacheDiagnostics, ...
    'cache', cacheDiagnostics, ...
    'cacheMigration', cacheDiagnostics, ...
    'repairResult', repairedFrequency, ...
    'repair', repairDiagnostics, ...
    'smoothingResult', smoothedFrequency, ...
    'smoothing', smoothingDiagnostics, ...
    'baseLuminanceResult', baseLuminance, ...
    'baseLuminance', baseLuminanceDiagnostics, ...
    'evenSkinLuminanceResult', baseLuminance, ...
    'evenSkinLuminance', baseLuminanceDiagnostics, ...
    'skinToneResult', skinTone, ...
    'skinTone', skinToneDiagnostics, ...
    'whiteningResult', whitening, ...
    'whitening', whiteningDiagnostics, ...
    'compose', composeDiagnostics);
end

function [isUsable, beautyMasks, maskDiagnostics, frequency, ...
        decompositionDiagnostics, blemishMap, blemishDiagnostics, ...
        cacheDiagnostics] = readRuntimeCache( ...
        inputImage, runtimeCache, faceBox, beautyContext)
isUsable = false;
beautyMasks = [];
maskDiagnostics = struct();
frequency = [];
decompositionDiagnostics = struct();
blemishMap = [];
blemishDiagnostics = struct();
cacheDiagnostics = makeCacheDiagnostics('generated', ...
    '未提供运行时缓存。', []);
if isempty(runtimeCache)
    return;
end
if ~isstruct(runtimeCache) || ~isscalar(runtimeCache)
    cacheDiagnostics = makeCacheDiagnostics('regenerated', ...
        '运行时缓存格式无效，需要重新生成。', runtimeCache);
    return;
end
cache = runtimeCache;
[isValid, reason] = validateRuntimeCache(cache, inputImage, faceBox, ...
    beautyContext);
cacheDiagnostics = makeCacheDiagnostics('regenerated', reason, cache);
if ~isValid
    return;
end
beautyMasks = cache.beautyMasks;
maskDiagnostics = cache.maskDiagnostics;
frequency = cache.frequency;
decompositionDiagnostics = cache.decompositionDiagnostics;
blemishMap = cache.blemishMap;
blemishDiagnostics = cache.blemishDiagnostics;
isUsable = true;
cacheDiagnostics.status = 'reused';
cacheDiagnostics.reused = true;
cacheDiagnostics.reason = '缓存契约、输入和全部算法产物均匹配。';
end

function diagnostics = makeCacheDiagnostics(status, reason, cache)
contract = beautyPipelineContract();
sourceSchemaVersion = '';
sourceAlgorithmVersion = '';
if isstruct(cache) && isscalar(cache)
    if isfield(cache, 'schemaVersion')
        sourceSchemaVersion = versionText(cache.schemaVersion);
    end
    if isfield(cache, 'algorithmVersion')
        sourceAlgorithmVersion = versionText(cache.algorithmVersion);
    end
end
diagnostics = struct( ...
    'status', status, ...
    'reused', strcmp(status, 'reused'), ...
    'reason', reason, ...
    'schemaVersion', contract.schemaVersion, ...
    'algorithmVersion', contract.algorithmVersion, ...
    'sourceSchemaVersion', sourceSchemaVersion, ...
    'sourceAlgorithmVersion', sourceAlgorithmVersion);
end

function [valid, reason] = validateRuntimeCache( ...
        cache, inputImage, faceBox, beautyContext)
valid = false;
required = {'schemaVersion', 'algorithmVersion', 'artifactVersion', ...
    'artifactInfo', 'artifacts', 'imageSize', 'inputImage', 'faceBox', ...
    'beautyMasks', 'maskDiagnostics', 'frequency', ...
    'decompositionDiagnostics', 'blemishMap', 'blemishDiagnostics', ...
    'migration'};
if ~all(isfield(cache, required))
    reason = '运行时缓存缺少 v3.1 版本或算法产物字段。';
    return;
end
contract = beautyPipelineContract();
if ~isExactVersion(cache.schemaVersion, contract.schemaVersion)
    reason = '运行时缓存的 Schema 不是 v3.1，历史缓存需要重新生成。';
    return;
end
if ~isExactVersion(cache.algorithmVersion, contract.algorithmVersion) || ...
        ~isExactVersion(cache.artifactVersion, contract.artifactVersion)
    reason = '运行时缓存的算法产物版本不匹配，需要重新生成。';
    return;
end
if ~isequal(cache.inputImage, inputImage)
    reason = '运行时缓存的输入图像不匹配，需要重新生成。';
    return;
end
if ~isnumeric(cache.faceBox) || ~isreal(cache.faceBox) || ...
        ~isequal(size(cache.faceBox), [1, 4]) || ...
        ~isequal(double(cache.faceBox), double(faceBox))
    reason = '运行时缓存的人脸框不匹配，需要重新生成。';
    return;
end
imageSize = size(inputImage, 1:2);
if ~isnumeric(cache.imageSize) || ~isreal(cache.imageSize) || ...
        ~isequal(size(cache.imageSize), [1, 3]) || ...
        ~isequal(double(cache.imageSize), [imageSize, 3])
    reason = '运行时缓存的图像尺寸不匹配，需要重新生成。';
    return;
end
if ~validateArtifactInfo(cache.artifactInfo, contract) || ...
        ~validateArtifactInfo(cache.artifacts, contract)
    reason = '运行时缓存的算法产物清单不匹配，需要重新生成。';
    return;
end
if ~isstruct(cache.migration) || ...
        ~isscalar(cache.migration)
    reason = '运行时缓存的迁移信息无效，需要重新生成。';
    return;
end
if isfield(cache.migration, 'status') && ...
        isTextEqual(cache.migration.status, 'requiresRegeneration')
    reason = '运行时缓存已标记为需要重新生成。';
    return;
end
if ~isstruct(cache.beautyMasks) || ~isscalar(cache.beautyMasks)
    reason = '运行时缓存缺少有效的 Beauty Masks 产物。';
    return;
end
if ~validateBeautyMasks(cache.beautyMasks, imageSize, faceBox, contract)
    reason = '运行时缓存的 Beauty Masks 产物无效，需要重新生成。';
    return;
end
contextNames = {'skinMask', 'faceSkinMask', 'nonFaceSkinMask', ...
    'textureProtectionMask', 'structureProtectionMask', ...
    'whiteningProtectionMask', 'chromaProtectionMask', ...
    'toneProtectionMask', 'strengthMap', ...
    'faceStrengthMap', 'nonFaceStrengthMap'};
for index = 1:numel(contextNames)
    name = contextNames{index};
    if ~isfield(beautyContext, name) || ...
            ~isequal(double(cache.beautyMasks.(name)), ...
            double(beautyContext.(name)))
        reason = '运行时缓存的 Mask 与当前 Context 不一致，需要重新生成。';
        return;
    end
end
if ~validateFrequency(cache.frequency, imageSize, faceBox, contract)
    reason = '运行时缓存的频率产物无效，需要重新生成。';
    return;
end
if ~validateStampedArtifact(cache.maskDiagnostics, contract) || ...
        ~validateStampedArtifact(cache.decompositionDiagnostics, contract) || ...
        ~validateStampedArtifact(cache.blemishDiagnostics, contract)
    reason = '运行时缓存的诊断产物无效，需要重新生成。';
    return;
end
if ~validateMask(cache.blemishMap, imageSize, true)
    reason = '运行时缓存的瑕疵图无效，需要重新生成。';
    return;
end
valid = true;
reason = '缓存有效。';
end

function valid = validateArtifactInfo(info, contract)
required = {'schemaVersion', 'algorithmVersion', 'artifactVersion', ...
    'beautyMasks', 'frequency', 'blemishMap'};
valid = isstruct(info) && isscalar(info) && all(isfield(info, required)) && ...
    isExactVersion(info.schemaVersion, contract.schemaVersion) && ...
    isExactVersion(info.algorithmVersion, contract.algorithmVersion) && ...
    isExactVersion(info.artifactVersion, contract.artifactVersion);
if ~valid
    return;
end
names = {'beautyMasks', 'frequency', 'blemishMap'};
for index = 1:numel(names)
    valid = valid && isExactVersion(info.(names{index}), ...
        contract.artifactVersion);
end
end

function valid = validateBeautyMasks(beautyMasks, imageSize, faceBox, contract)
required = {'schemaVersion', 'algorithmVersion', 'artifactVersion', ...
    'skinMask', 'faceSkinMask', 'nonFaceSkinMask', ...
    'textureProtectionMask', 'structureProtectionMask', ...
    'whiteningProtectionMask', 'chromaProtectionMask', ...
    'toneProtectionMask', 'protectionMask', ...
    'strengthMap', 'faceStrengthMap', 'nonFaceStrengthMap', ...
    'hardProtectionMask', 'noseMask', 'faceBox', 'imageSize'};
if ~all(isfield(beautyMasks, required)) || ...
        ~isExactVersion(beautyMasks.schemaVersion, contract.schemaVersion) || ...
        ~isExactVersion(beautyMasks.algorithmVersion, ...
        contract.algorithmVersion) || ...
        ~isExactVersion(beautyMasks.artifactVersion, contract.artifactVersion)
    valid = false;
    return;
end
if ~isnumeric(beautyMasks.imageSize) || ...
        ~isequal(size(beautyMasks.imageSize), [1, 3]) || ...
        ~isequal(double(beautyMasks.imageSize), [imageSize, 3]) || ...
        ~isnumeric(beautyMasks.faceBox) || ~isreal(beautyMasks.faceBox) || ...
        ~isequal(size(beautyMasks.faceBox), [1, 4]) || ...
        ~isequal(double(beautyMasks.faceBox), double(faceBox))
    valid = false;
    return;
end
maskNames = {'skinMask', 'faceSkinMask', 'nonFaceSkinMask', ...
    'textureProtectionMask', 'structureProtectionMask', ...
    'whiteningProtectionMask', 'chromaProtectionMask', ...
    'toneProtectionMask', 'protectionMask', ...
    'strengthMap', 'faceStrengthMap', 'nonFaceStrengthMap', ...
    'hardProtectionMask', 'noseMask'};
valid = true;
for index = 1:numel(maskNames)
    valid = valid && validateMask(beautyMasks.(maskNames{index}), ...
        imageSize, true);
end
if ~valid
    return;
end
try
    [~, hasChroma] = resolveChromaProtectionMask(beautyMasks, imageSize, ...
        'beautifyImage:InvalidRuntimeCache', ...
        'beautifyImage:ChromaProtectionConflict');
    valid = hasChroma;
catch
    valid = false;
end
end

function valid = validateFrequency(frequency, imageSize, faceBox, contract)
required = {'schemaVersion', 'algorithmVersion', 'artifactVersion', ...
    'sourceLuminance', 'base', 'mid', 'fine', 'imageSize', 'faceBox'};
valid = isstruct(frequency) && isscalar(frequency) && ...
    all(isfield(frequency, required)) && ...
    isExactVersion(frequency.schemaVersion, contract.schemaVersion) && ...
    isExactVersion(frequency.algorithmVersion, contract.algorithmVersion) && ...
    isExactVersion(frequency.artifactVersion, contract.artifactVersion) && ...
    isnumeric(frequency.imageSize) && isreal(frequency.imageSize) && ...
    isequal(size(frequency.imageSize), [1, 3]) && ...
    isequal(double(frequency.imageSize), [imageSize, 3]) && ...
    isnumeric(frequency.faceBox) && isreal(frequency.faceBox) && ...
    isequal(size(frequency.faceBox), [1, 4]) && ...
    isequal(double(frequency.faceBox), double(faceBox));
if ~valid
    return;
end
for name = {'sourceLuminance', 'base', 'mid', 'fine'}
    value = frequency.(name{1});
    valid = valid && isnumeric(value) && isreal(value) && ...
        isequal(size(value), imageSize) && all(isfinite(value(:)));
end
end

function valid = validateStampedArtifact(value, contract)
valid = isstruct(value) && isscalar(value) && ...
    all(isfield(value, {'schemaVersion', 'algorithmVersion', ...
    'artifactVersion'})) && ...
    isExactVersion(value.schemaVersion, contract.schemaVersion) && ...
    isExactVersion(value.algorithmVersion, contract.algorithmVersion) && ...
    isExactVersion(value.artifactVersion, contract.artifactVersion);
end

function valid = validateMask(value, imageSize, requireRange)
valid = (isnumeric(value) || islogical(value)) && isreal(value) && ...
    isequal(size(value), imageSize) && all(isfinite(value(:)));
if valid && requireRange
    valid = all(value(:) >= 0) && all(value(:) <= 1);
end
end

function valid = isExactVersion(value, expected)
if isstring(value) && isscalar(value)
    value = char(value);
end
valid = ischar(value) && size(value, 1) == 1 && strcmp(value, expected);
end

function valid = isTextEqual(value, expected)
if isstring(value) && isscalar(value)
    value = char(value);
end
valid = ischar(value) && size(value, 1) == 1 && strcmp(value, expected);
end

function value = versionText(value)
if isstring(value) && isscalar(value)
    value = char(value);
end
if ~ischar(value) || size(value, 1) ~= 1
    value = '';
end
end

function isValid = isValidRgbImage(inputImage)
isValid = isa(inputImage, 'uint8') && isreal(inputImage) && ...
    ndims(inputImage) == 3 && size(inputImage, 3) == 3;
end

function isValid = isValidStrength(strength)
isValid = isnumeric(strength) && isreal(strength) && isscalar(strength) && ...
    isfinite(strength) && strength >= 0 && strength <= 100;
end

function validateFaceBox(faceBox, imageWidth, imageHeight)
if ~isnumeric(faceBox) || ~isreal(faceBox) || ~isequal(size(faceBox), [1, 4]) || ...
        any(~isfinite(faceBox)) || faceBox(1) < 1 || faceBox(2) < 1 || ...
        faceBox(3) <= 0 || faceBox(4) <= 0 || ...
        faceBox(1) + faceBox(3) - 1 > imageWidth || ...
        faceBox(2) + faceBox(4) - 1 > imageHeight
    error('beautifyImage:InvalidFaceBox', ...
        'faceBox 必须是位于图像范围内的 [x y width height] 矩形。');
end
end

function ensureImageProcessingToolbox
requiredFunctions = {'rgb2ycbcr', 'ycbcr2rgb', 'imgaussfilt'};
if any(cellfun(@(name) exist(name, 'file') == 0, requiredFunctions))
    error('beautifyImage:MissingToolbox', ...
        '美颜处理需要 Image Processing Toolbox。');
end
end
