function contract = beautyPipelineContract
%BEAUTYPIPELINECONTRACT 返回 v3.1 数据结构和 v3.2 算法使用的固定契约版本。

contract = struct( ...
    'schemaVersion', '3.1', ...
    'algorithmVersion', 'v3.2', ...
    'artifactVersion', 'v3.1');
end
