function profile = beautySmoothingProfile(smoothingStrength)
%BEAUTYSMOOTHINGPROFILE 返回可解释的 v3.1 磨皮参数曲线。
%   基础曲线负责低到中档的自然效果，高档延伸继续推动普通皮肤；
%   频率保留率、Alpha、瑕疵强度和脸外强度彼此独立，便于分别诊断。

if ~isnumeric(smoothingStrength) || ~isreal(smoothingStrength) || ...
        ~isscalar(smoothingStrength) || ~isfinite(smoothingStrength) || ...
        smoothingStrength < 0 || smoothingStrength > 100
    error('beautySmoothingProfile:InvalidStrength', ...
        '磨皮强度必须是范围 0 到 100 内的有限数值标量。');
end

ratio = double(smoothingStrength) / 100;

% 0--50 档沿用较快的基础起效曲线；50--100 档通过独立的高档
% 延伸继续增加 naturalRatio，避免基础曲线在高档以后冻结全部效果。
baseCurve = min(2 * ratio, .75);
highStrengthCurve = smoothStep(ratio, .50, 1.00);
naturalRatio = min(baseCurve + .25 * highStrengthCurve, 1);

fineCurve = naturalRatio ^ .85;
mediumCurve = naturalRatio ^ .65;
profile = struct( ...
    'ratio', ratio, ...
    'baseCurve', baseCurve, ...
    'highStrengthCurve', highStrengthCurve, ...
    'naturalRatio', naturalRatio, ...
    'alphaCurve', naturalRatio, ...
    'fineCurve', fineCurve, ...
    'mediumCurve', mediumCurve, ...
    'fineRetention', 1 - .55 * fineCurve, ...
    'mediumRetention', 1 - .12 * mediumCurve, ...
    'midRetention', 1 - .12 * mediumCurve, ...
    'blemishStrength', ratio ^ .85, ...
    'toneStrength', fineCurve, ...
    'outsideFaceStrength', .75 * smoothStep(ratio, 0, 1));
end

function value = smoothStep(inputValue, low, high)
t = min(max((double(inputValue) - low) / max(high - low, eps), 0), 1);
value = t ^ 2 * (3 - 2 * t);
end
