function [beautifiedImage, diagnostics] = beautifyImage( ...
        inputImage, params, faceBox, beautyContext)
%BEAUTIFYIMAGE 通过 v3 package 编排结构感知的磨皮和美白。

if nargin < 2
    params = [];
end
if nargin < 3
    faceBox = [];
end
validateInput(inputImage, params, faceBox);
smoothingStrength = params.smoothingStrength;
whiteningStrength = params.whiteningStrength;

% 零强度严格返回原图，同时保留轻量诊断，避免无意义地触发模型推理。
if smoothingStrength == 0 && whiteningStrength == 0
    beautifiedImage = inputImage;
    diagnostics = struct('pipeline', 'v3', 'identity', true, ...
        'imageSize', size(inputImage));
    return;
end

ensureImageProcessingToolbox();
runtimeCache = [];
if nargin < 4 || isempty(beautyContext)
    beautyContext = normalizeBeautyContext(inputImage, faceBox);
else
    if isfield(beautyContext, 'runtimeCache')
        runtimeCache = beautyContext.runtimeCache;
        beautyContext = rmfield(beautyContext, 'runtimeCache');
    end
    try
        beautyContext = normalizeBeautyContext(inputImage, faceBox, ...
            beautyContext);
    catch exception
        if startsWith(exception.identifier, 'normalizeBeautyContext:')
            error('beautifyImage:InvalidContext', ...
                'Beauty Context 无效：%s', exception.message);
        end
        rethrow(exception);
    end
end

[beautifiedImage, diagnostics] = runV3Beauty(inputImage, beautyContext, ...
    faceBox, smoothingStrength, whiteningStrength, runtimeCache);
if ~isa(beautifiedImage, 'uint8') || ...
        ~isequal(size(beautifiedImage), size(inputImage))
    error('beautifyImage:InvalidOutput', ...
        '美颜结果必须保持输入图像的尺寸和数据类型。');
end
end

function validateInput(inputImage, params, faceBox)
if nargin < 1 || ~isValidRgbImage(inputImage)
    error('beautifyImage:InvalidImage', ...
        '输入图像必须是 uint8 三通道 RGB 图像。');
end
if nargin < 2 || ~isstruct(params) || ~isscalar(params) || ...
        ~all(isfield(params, {'smoothingStrength', 'whiteningStrength'}))
    error('beautifyImage:InvalidParams', ...
        '参数必须包含 smoothingStrength 和 whiteningStrength。');
end
if isfield(params, 'pipeline')
    error('beautifyImage:InvalidParams', ...
        'pipeline 选择已移除，beautifyImage 统一使用 v3。');
end
if ~isValidStrength(params.smoothingStrength) || ...
        ~isValidStrength(params.whiteningStrength)
    error('beautifyImage:InvalidParams', ...
        '美颜强度必须是范围 0 到 100 内的有限数值标量。');
end
if nargin < 3
    error('beautifyImage:InvalidFaceBox', ...
        '必须提供位于图像范围内的 [x y width height] 人脸框。');
end
validateFaceBox(faceBox, size(inputImage, 2), size(inputImage, 1));
end

function [beautifiedImage, diagnostics] = runV3Beauty( ...
        inputImage, beautyContext, faceBox, ...
        smoothingStrength, whiteningStrength, runtimeCache)
[hasRuntimeCache, beautyMasks, maskDiagnostics, frequency, ...
    decompositionDiagnostics, blemishMap, blemishDiagnostics] = ...
    readRuntimeCache(inputImage, runtimeCache, faceBox);
if ~hasRuntimeCache
    beautyMasks = masks.buildBeautyMasks(inputImage, beautyContext, faceBox);
    maskDiagnostics = struct('reusedRuntimeCache', false);
    [frequency, decompositionDiagnostics] = beauty.decomposeSkinFrequency( ...
        inputImage, faceBox);
    [blemishMap, blemishDiagnostics] = beauty.buildBlemishMap(inputImage, ...
        frequency, beautyMasks);
end
[smoothedFrequency, smoothingDiagnostics] = beauty.smoothSkinTexture( ...
    frequency, beautyMasks, smoothingStrength, blemishMap);
[repairedFrequency, repairDiagnostics] = beauty.repairSkinBlemishes( ...
    smoothedFrequency, beautyMasks, blemishMap, smoothingStrength);
[skinTone, skinToneDiagnostics] = beauty.normalizeSkinTone(inputImage, ...
    frequency, beautyMasks, blemishMap, smoothingStrength);
[whitening, whiteningDiagnostics] = beauty.applySkinWhitening(inputImage, ...
    frequency, beautyMasks, whiteningStrength);
processing = struct( ...
    'blemishMap', blemishMap, ...
    'blemish', blemishDiagnostics, ...
    'repair', repairDiagnostics, ...
    'skinTone', skinTone, ...
    'skinToneDiagnostics', skinToneDiagnostics, ...
    'whitening', whitening, ...
    'whiteningDiagnostics', whiteningDiagnostics, ...
    'maskDiagnostics', maskDiagnostics, ...
    'decompositionDiagnostics', decompositionDiagnostics, ...
    'smoothingDiagnostics', smoothingDiagnostics);
[beautifiedImage, composeDiagnostics] = beauty.composeBeautyResult( ...
    inputImage, frequency, repairedFrequency, beautyMasks, ...
    whiteningStrength, processing);
diagnostics = struct( ...
    'pipeline', 'v3', ...
    'identity', false, ...
    'reusedRuntimeCache', hasRuntimeCache, ...
    'beautyMasks', beautyMasks, ...
    'mask', maskDiagnostics, ...
    'frequency', decompositionDiagnostics, ...
    'blemishMap', blemishMap, ...
    'blemish', blemishDiagnostics, ...
    'repairResult', repairedFrequency, ...
    'repair', repairDiagnostics, ...
    'skinToneResult', skinTone, ...
    'skinTone', skinToneDiagnostics, ...
    'whiteningResult', whitening, ...
    'whitening', whiteningDiagnostics, ...
    'compose', composeDiagnostics);
end

function [isUsable, beautyMasks, maskDiagnostics, frequency, ...
        decompositionDiagnostics, blemishMap, blemishDiagnostics] = ...
        readRuntimeCache(inputImage, runtimeCache, faceBox)
isUsable = false;
beautyMasks = [];
maskDiagnostics = struct();
frequency = [];
decompositionDiagnostics = struct();
blemishMap = [];
blemishDiagnostics = struct();
if ~isstruct(runtimeCache) || ~isscalar(runtimeCache)
    return;
end
cache = runtimeCache;
required = {'inputImage', 'faceBox', 'beautyMasks', 'maskDiagnostics', ...
    'frequency', 'decompositionDiagnostics', 'blemishMap', ...
    'blemishDiagnostics'};
if ~all(isfield(cache, required)) || ...
        ~isequal(cache.inputImage, inputImage) || ...
        ~isequal(double(cache.faceBox), double(faceBox))
    return;
end
beautyMasks = cache.beautyMasks;
maskDiagnostics = cache.maskDiagnostics;
frequency = cache.frequency;
decompositionDiagnostics = cache.decompositionDiagnostics;
blemishMap = cache.blemishMap;
blemishDiagnostics = cache.blemishDiagnostics;
isUsable = true;
end

function isValid = isValidRgbImage(inputImage)
isValid = isa(inputImage, 'uint8') && isreal(inputImage) && ...
    ndims(inputImage) == 3 && size(inputImage, 3) == 3;
end

function isValid = isValidStrength(strength)
isValid = isnumeric(strength) && isreal(strength) && isscalar(strength) && ...
    isfinite(strength) && strength >= 0 && strength <= 100;
end

function validateFaceBox(faceBox, imageWidth, imageHeight)
if ~isnumeric(faceBox) || ~isreal(faceBox) || ~isequal(size(faceBox), [1, 4]) || ...
        any(~isfinite(faceBox)) || faceBox(1) < 1 || faceBox(2) < 1 || ...
        faceBox(3) <= 0 || faceBox(4) <= 0 || ...
        faceBox(1) + faceBox(3) - 1 > imageWidth || ...
        faceBox(2) + faceBox(4) - 1 > imageHeight
    error('beautifyImage:InvalidFaceBox', ...
        'faceBox 必须是位于图像范围内的 [x y width height] 矩形。');
end
end

function ensureImageProcessingToolbox
requiredFunctions = {'rgb2ycbcr', 'ycbcr2rgb', 'imgaussfilt'};
if any(cellfun(@(name) exist(name, 'file') == 0, requiredFunctions))
    error('beautifyImage:MissingToolbox', ...
        '美颜处理需要 Image Processing Toolbox。');
end
end
