function contract = beautyPipelineContract
%BEAUTYPIPELINECONTRACT 返回 v3.1 数据链路使用的固定契约版本。

contract = struct( ...
    'schemaVersion', '3.1', ...
    'algorithmVersion', 'v3.1', ...
    'artifactVersion', 'v3.1');
end
