function profile = beautySmoothingProfile(smoothingStrength)
%BEAUTYSMOOTHINGPROFILE 返回连续、保留纹理的磨皮参数曲线。
if ~isnumeric(smoothingStrength) || ~isreal(smoothingStrength) || ...
        ~isscalar(smoothingStrength) || ~isfinite(smoothingStrength) || ...
        smoothingStrength < 0 || smoothingStrength > 100
    error('beautySmoothingProfile:InvalidStrength', ...
        'Smoothing strength must be a finite scalar in [0, 100].');
end
ratio = smoothingStrength / 100;
t = min(max((ratio - .5) / .5, 0), 1);
highBoost = t ^ 2 * (3 - 2 * t);
% 75 档后不再提高普通皮肤的整体模糊量；高档变化交给
% beautifyImage 中的高置信瑕疵覆盖逻辑。
normalRatio = min(ratio, .75);
normalBoost = min(highBoost, .5);
% 普通皮肤只使用较小的基础权重；瑕疵权重在 beautifyImage 中单独提升。
% 中频保留率在高档保底下限，避免大尺度光影随磨皮档位被抹平；
% 高频保留率同步保底，让 100 档仍保留毛孔级别的自然质感。
profile = struct('ratio', ratio, 'highBoost', highBoost, ...
    'baseWeight', .16 + .38 * normalRatio ^ .85 + .04 * normalBoost, ...
    'fineRetention', 1 - .36 * sqrt(normalRatio) + .10 * normalRatio - ...
    .04 * normalRatio ^ 2 - .02 * normalBoost, ...
    'mediumRetention', 1 - .45 * normalRatio ^ .45 - .05 * normalBoost, ...
    'chromaEffect', min(1, .98 * normalRatio ^ .85 + .25 * normalBoost));
end
