function [runtimeCache, diagnostics] = buildBeautyRuntimeCache( ...
        inputImage, faceBox, beautyMasks, maskDiagnostics, migration)
%BUILDBEAUTYRUNTIMECACHE 构建带版本和产物信息的 v3.1 运行时缓存。
%   缓存中的 Mask、频率分解和瑕疵图都绑定当前输入图像、人脸框及算法
%   版本。历史缓存不得通过补 alias 直接获得当前产物版本。

if nargin < 4 || isempty(maskDiagnostics)
    [beautyMasks, maskDiagnostics] = masks.buildBeautyMasks( ...
        inputImage, beautyMasks, faceBox);
end
if nargin < 5 || isempty(migration)
    migration = struct( ...
        'status', 'generated', ...
        'sourceSchemaVersion', '3.1', ...
        'message', '当前输入已重新生成运行时产物。');
end

validateImage(inputImage);
validateFaceBox(faceBox, size(inputImage, 2), size(inputImage, 1));
if ~isstruct(beautyMasks) || ~isscalar(beautyMasks)
    error('buildBeautyRuntimeCache:InvalidMasks', ...
        '运行时缓存需要标量 Beauty Masks。');
end

imageSize = size(inputImage, 1:2);
contract = beautyPipelineContract();
[chromaProtectionMask, hasChromaProtectionMask] = ...
    resolveChromaProtectionMask(beautyMasks, imageSize, ...
    'buildBeautyRuntimeCache:InvalidMasks', ...
    'buildBeautyRuntimeCache:ChromaProtectionConflict');
if ~hasChromaProtectionMask
    error('buildBeautyRuntimeCache:InvalidMasks', ...
        '运行时缓存的 Beauty Masks 缺少 chromaProtectionMask。');
end
beautyMasks.chromaProtectionMask = chromaProtectionMask;
beautyMasks.toneProtectionMask = chromaProtectionMask;
beautyMasks.schemaVersion = contract.schemaVersion;
beautyMasks.algorithmVersion = contract.algorithmVersion;
beautyMasks.artifactVersion = contract.artifactVersion;

[frequency, decompositionDiagnostics] = beauty.decomposeSkinFrequency( ...
    inputImage, faceBox);
frequency = stampArtifact(frequency, contract);
decompositionDiagnostics = stampArtifact(decompositionDiagnostics, contract);
[blemishMap, blemishDiagnostics] = beauty.buildBlemishMap( ...
    inputImage, frequency, beautyMasks);
blemishDiagnostics = stampArtifact(blemishDiagnostics, contract);
maskDiagnostics = stampArtifact(maskDiagnostics, contract);
maskDiagnostics.chromaProtectionMask = chromaProtectionMask;
maskDiagnostics.toneProtectionMask = chromaProtectionMask;

artifactInfo = struct( ...
    'schemaVersion', contract.schemaVersion, ...
    'algorithmVersion', contract.algorithmVersion, ...
    'artifactVersion', contract.artifactVersion, ...
    'beautyMasks', contract.artifactVersion, ...
    'frequency', contract.artifactVersion, ...
    'blemishMap', contract.artifactVersion);
migration = normalizeMigration(migration, contract);

runtimeCache = struct( ...
    'schemaVersion', contract.schemaVersion, ...
    'algorithmVersion', contract.algorithmVersion, ...
    'artifactVersion', contract.artifactVersion, ...
    'artifactInfo', artifactInfo, ...
    'artifacts', artifactInfo, ...
    'imageSize', size(inputImage), ...
    'inputImage', inputImage, ...
    'faceBox', double(faceBox), ...
    'beautyMasks', beautyMasks, ...
    'maskDiagnostics', maskDiagnostics, ...
    'frequency', frequency, ...
    'decompositionDiagnostics', decompositionDiagnostics, ...
    'blemishMap', blemishMap, ...
    'blemishDiagnostics', blemishDiagnostics, ...
    'migration', migration);
diagnostics = struct( ...
    'status', migration.status, ...
    'schemaVersion', contract.schemaVersion, ...
    'algorithmVersion', contract.algorithmVersion, ...
    'artifactVersion', contract.artifactVersion, ...
    'artifactInfo', artifactInfo, ...
    'migration', migration);
end

function value = stampArtifact(value, contract)
if ~isstruct(value) || ~isscalar(value)
    value = struct();
end
value.schemaVersion = contract.schemaVersion;
value.algorithmVersion = contract.algorithmVersion;
value.artifactVersion = contract.artifactVersion;
end

function migration = normalizeMigration(migration, contract)
if ~isstruct(migration) || ~isscalar(migration)
    error('buildBeautyRuntimeCache:InvalidMigration', ...
        '缓存迁移信息必须是标量结构体。');
end
if ~isfield(migration, 'status') || isempty(migration.status)
    migration.status = 'generated';
end
if ~isfield(migration, 'sourceSchemaVersion') || ...
        isempty(migration.sourceSchemaVersion)
    migration.sourceSchemaVersion = contract.schemaVersion;
end
if ~isfield(migration, 'message') || isempty(migration.message)
    migration.message = '当前输入已重新生成运行时产物。';
end
end

function validateImage(inputImage)
if ~isa(inputImage, 'uint8') || ~isreal(inputImage) || ...
        ndims(inputImage) ~= 3 || size(inputImage, 3) ~= 3
    error('buildBeautyRuntimeCache:InvalidImage', ...
        '输入图像必须是 uint8 三通道 RGB 图像。');
end
end

function validateFaceBox(faceBox, imageWidth, imageHeight)
if ~isnumeric(faceBox) || ~isreal(faceBox) || ...
        ~isequal(size(faceBox), [1, 4]) || any(~isfinite(faceBox)) || ...
        faceBox(1) < 1 || faceBox(2) < 1 || any(faceBox(3:4) <= 0) || ...
        faceBox(1) + faceBox(3) - 1 > imageWidth || ...
        faceBox(2) + faceBox(4) - 1 > imageHeight
    error('buildBeautyRuntimeCache:InvalidFaceBox', ...
        'faceBox 必须是位于图像范围内的 [x y width height] 矩形。');
end
end
