function beautyMask = createBeautyMask(inputDouble, faceBox)
%CREATEBEAUTYMASK 兼容旧调用并返回内容驱动的人脸皮肤 mask。

if ~isnumeric(inputDouble) || ~isreal(inputDouble) || ...
        ndims(inputDouble) ~= 3 || size(inputDouble, 3) ~= 3 || ...
        any(~isfinite(inputDouble(:))) || any(inputDouble(:) < 0) || ...
        any(inputDouble(:) > 1)
    error('createBeautyMask:InvalidImage', ...
        'inputDouble must be a finite RGB image in the range 0 to 1.');
end
inputImage = uint8(round(double(inputDouble) * 255));
context = normalizeBeautyContext(inputImage, faceBox, ...
    prepareBeautyContext(inputImage, faceBox));
beautyMask = context.faceSkinMask;
end
