function names = faceParsingClassNames
%FACEPARSINGCLASSNAMES 固定的 CelebAMask-HQ 19 类顺序。
names = {'background', 'skin', 'leftBrow', 'rightBrow', 'leftEye', ...
    'rightEye', 'eyeglass', 'leftEar', 'rightEar', 'earring', 'nose', ...
    'mouth', 'upperLip', 'lowerLip', 'neck', 'necklace', 'cloth', ...
    'hair', 'hat'};
end
