function report = runBeautyShadowRegression(varargin)
%RUNBEAUTYSHADOWREGRESSION 并列运行旧管线和 v3 tracer 回归。
%   两条管线共享同一合成输入、Context、强度序列和指标口径。

[privateSmoke, shouldAssert] = readOptions(varargin{:});
legacy = runBeautyRegression('Pipeline', 'legacy', ...
    'PrivateSmoke', privateSmoke, 'Assert', shouldAssert);
v3 = runBeautyRegression('Pipeline', 'v3', ...
    'PrivateSmoke', privateSmoke, 'Assert', shouldAssert);
comparison = struct( ...
    'textureEnergyDelta', [v3.smoothing.textureEnergy] - ...
    [legacy.smoothing.textureEnergy], ...
    'blemishEnergyDelta', [v3.smoothing.blemishEnergy] - ...
    [legacy.smoothing.blemishEnergy], ...
    'noseStructureDelta', [v3.smoothing.noseStructure] - ...
    [legacy.smoothing.noseStructure], ...
    'outsideStructureDelta', [v3.smoothing.outsideStructure] - ...
    [legacy.smoothing.outsideStructure], ...
    'elapsedSecondsLegacy', [legacy.smoothing.elapsedSeconds], ...
    'elapsedSecondsV3', [v3.smoothing.elapsedSeconds]);
report = struct( ...
    'strengths', legacy.strengths, ...
    'legacy', legacy, ...
    'v3', v3, ...
    'comparison', comparison, ...
    'passed', legacy.passed && v3.passed);
end

function [privateSmoke, shouldAssert] = readOptions(varargin)
privateSmoke = struct([]);
shouldAssert = false;
if mod(numel(varargin), 2) ~= 0
    error('runBeautyShadowRegression:InvalidOptions', ...
        '选项必须使用名称和值成对传入。');
end
for index = 1:2:numel(varargin)
    name = varargin{index};
    if isstring(name) && isscalar(name)
        name = char(name);
    end
    if ~ischar(name)
        error('runBeautyShadowRegression:InvalidOptions', ...
            '选项名称必须是字符向量或字符串。');
    end
    switch lower(name)
        case 'privatesmoke'
            privateSmoke = varargin{index + 1};
            if isempty(privateSmoke)
                privateSmoke = struct([]);
            elseif ~isstruct(privateSmoke)
                error('runBeautyShadowRegression:InvalidOptions', ...
                    'PrivateSmoke 必须是结构体数组。');
            end
        case 'assert'
            shouldAssert = varargin{index + 1};
            if ~islogical(shouldAssert) || ~isscalar(shouldAssert)
                error('runBeautyShadowRegression:InvalidOptions', ...
                    'Assert 必须是逻辑标量。');
            end
        otherwise
            error('runBeautyShadowRegression:InvalidOptions', ...
                '不支持的回归选项：%s。', name);
    end
end
end

