function names = schpLipClassNames
%SCHPLIPCLASSNAMES 返回官方 LIP 20 类的固定顺序。
names = {'background', 'hat', 'hair', 'glove', 'sunglasses', ...
    'upperClothes', 'dress', 'coat', 'socks', 'pants', 'jumpsuits', ...
    'scarf', 'skirt', 'face', 'leftArm', 'rightArm', 'leftLeg', ...
    'rightLeg', 'leftShoe', 'rightShoe'};
end
